extends RefCounted
## Story mode content: "PROMPT FIGHTER – DIE LETZTE ZEILE".
## Pure data. story_mode.gd plays the steps; every step is a Dictionary with a "t" (type):
##   stage   cast: [{id, x, facing}]         – place fighters (cutscene, no HUD)
##   title   text, sub                         – chapter title card
##   narrate text                              – centered narration, no speaker
##   say     who (cast id), text               – dialogue box with portrait
##   cam     shot (wide|two|close|low|sky), who, who2, time
##   move    who (stage index), x, time        – walk to x
##   pose    who, pose, time                   – play a pose (Victory, HitReact, Attack, ...)
##   face    who, facing
##   fx      kind (flash|shake|ink|burst), who
##   vanish / appear  who
##   wait    time
##   qte     kind (press|mash|sequence), keys, time, count, text, flag, success, fail
##   fight   cast, lives, teams, mods, qte, goal, time (s), damage {slot: %}, ai (1–9)
##   credits

const TITLE := "DIE LETZTE ZEILE"

## Story cast. Prompts go through the normal prompt interpreter, so every story
## fighter is a real, balanced fighter. "name" overrides the displayed fighter name.
const CAST := {
	"volt": {"name": "VOLT", "title": "Der letzte Promptgeborene", "color": "49def4",
		"prompt": "Blitzschneller Schattenninja mit elektrischen Klingen"},
	"kalden": {"name": "SIR KALDEN", "title": "Ritter der Randwache", "color": "cbd5e1",
		"prompt": "Steel Knight Ritter in Vollplatte mit eisernem Schild"},
	"bastion": {"name": "CINDER BASTION", "title": "Wächter der Glutschmiede", "color": "ff6d2b",
		"prompt": "Gepanzerter Lavagolem mit brennenden Fäusten"},
	"dreyar": {"name": "DREYAR", "title": "Klingenmeister des Kolosseums", "color": "3bfac8",
		"prompt": "Samurai Dreyar Meister mit Wind-Klingen und Sturm-Schritten"},
	"warrok": {"name": "WARROK", "title": "Herr des Kolosseums", "color": "ff8b26",
		"prompt": "Warrok Koloss Urzeitlicher Berserker mit Knochenkeule und Erdbeben"},
	"korsar": {"name": "KORSAR", "title": "Kapitän der Salzkrähe", "color": "38bdf8",
		"prompt": "Korsar Corsair Piratenkapitän mit Entermesser und Donnerbüchse"},
	"aura": {"name": "AURA", "title": "Hüterin des Lichthains", "color": "ffe26a",
		"prompt": "Strahlende Moe Valkyrie Kriegerin mit Lichtflügeln und Rapier"},
	"schatten": {"name": "SCHATTEN-VOLT", "title": "Der gelöschte Entwurf", "color": "ff3b5c",
		"prompt": "Crimson Schattenninja mit roten Klingen"},
	"nulla": {"name": "NULLA", "title": "Die Leere zwischen den Zeilen", "color": "9b30ff",
		"prompt": "Void Specter crystal phantom warrior with void lance"},
	"aria": {"name": "ARIAS STIMME", "title": "Die verschwundene Schreiberin", "color": "f9a8d4",
		"prompt": ""},
}

const CHAPTERS := [
	{
		"id": "ch1", "title": "Die erste Zeile", "arena": "blood_moon",
		"steps": [
			{"t": "stage", "cast": [{"id": "volt", "x": -2.2, "facing": 1}, {"id": "kalden", "x": 7.5, "facing": -1}]},
			{"t": "cam", "shot": "sky", "time": 0.01},
			{"t": "title", "text": "KAPITEL 1", "sub": "Die erste Zeile"},
			{"t": "narrate", "text": "Lexara war eine Welt aus Worten. Jeder Berg, jeder Sturm, jeder Held – geschrieben in den Urtext."},
			{"t": "narrate", "text": "Dann kam die Leere. Zeile um Zeile löschte sie die Welt. Wo sie vorbeizog, blieb nur schwarze Tinte zurück."},
			{"t": "cam", "shot": "close", "who": 0, "time": 2.2},
			{"t": "fx", "kind": "flash"},
			{"t": "say", "who": "aria", "text": "Wach auf. Ich habe dich als Letzten geschrieben – mit der letzten Zeile, die mir geblieben ist."},
			{"t": "say", "who": "volt", "text": "Wer … bin ich? Meine Klingen – sie summen, als wüssten sie mehr als ich."},
			{"t": "say", "who": "aria", "text": "Du bist Volt. Und du wirst die letzte Zeile schützen. Finde mich, bevor die Leere sie findet."},
			{"t": "fx", "kind": "shake"},
			{"t": "cam", "shot": "wide", "time": 1.0},
			{"t": "move", "who": 1, "x": 2.4, "time": 1.4},
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "say", "who": "kalden", "text": "Ein Ungeschriebener … auf meiner Terrasse. Die Tinte flüstert, dass du ausradiert werden musst."},
			{"t": "cam", "shot": "low", "who": 1, "time": 0.6},
			{"t": "say", "who": "volt", "text": "Deine Augen – schwarz wie Tusche. Das bist nicht du, Ritter."},
			{"t": "qte", "kind": "press", "keys": ["jump"], "time": 1.3, "text": "DIE LANZE STÖSST ZU – SPRING!", "flag": "ch1_lance",
				"success": [{"t": "pose", "who": 0, "pose": "Victory", "time": 0.5}, {"t": "say", "who": "volt", "text": "Knapp. Jetzt bin ich dran!"}],
				"fail": [{"t": "pose", "who": 0, "pose": "HitReact", "time": 0.6}, {"t": "fx", "kind": "shake"}, {"t": "say", "who": "volt", "text": "Ngh – das hat gesessen. Aber ich stehe noch."}]},
			{"t": "fight", "cast": ["volt", "kalden"], "lives": [3, 2], "qte": "ch1_lance",
				"goal": "Befreie Sir Kalden vom Tintenfluch!"},
			{"t": "stage", "cast": [{"id": "volt", "x": -1.4, "facing": 1}, {"id": "kalden", "x": 1.4, "facing": -1}]},
			{"t": "cam", "shot": "two", "who": 0, "who2": 1, "time": 0.01},
			{"t": "pose", "who": 1, "pose": "Defeat", "time": 1.2},
			{"t": "say", "who": "kalden", "text": "Die Stimmen … sind fort. Ich danke dir, Ungeschriebener. Ich habe die Randwache verraten, ohne es zu merken."},
			{"t": "say", "who": "kalden", "text": "Die Leere hat einen Namen: NULLA. Sie frisst sich vom Rand der Welt zum Herzen des Urtexts vor."},
			{"t": "say", "who": "kalden", "text": "Geh zur Glutschmiede. Wenn jemand weiß, wo die Schreiberin ist, dann ihr Wächter."},
			{"t": "say", "who": "volt", "text": "Dann gehe ich zur Schmiede. Halte die Terrasse, Sir Kalden."},
		],
	},
	{
		"id": "ch2", "title": "Glut und Asche", "arena": "volcano_sanctum",
		"steps": [
			{"t": "stage", "cast": [{"id": "volt", "x": -7.0, "facing": 1}, {"id": "bastion", "x": 3.0, "facing": -1}]},
			{"t": "cam", "shot": "sky", "time": 0.01},
			{"t": "title", "text": "KAPITEL 2", "sub": "Glut und Asche"},
			{"t": "narrate", "text": "Die Glutschmiede. Hier wurden einst die Verben geschmiedet – Worte, die Dinge in Bewegung setzen."},
			{"t": "cam", "shot": "wide", "time": 1.4},
			{"t": "move", "who": 0, "x": -2.2, "time": 1.6},
			{"t": "say", "who": "volt", "text": "Die Hitze … und trotzdem ist hier alles still. Kein Hammer, kein Funke."},
			{"t": "fx", "kind": "shake"},
			{"t": "cam", "shot": "low", "who": 1, "time": 0.8},
			{"t": "say", "who": "bastion", "text": "WER … WAGT … ZU SCHREIBEN? DIE SCHMIEDE … IST … GELÖSCHT."},
			{"t": "say", "who": "volt", "text": "Die Tinte hat dich auch erwischt. Halt still, Koloss – ich hole dich da raus!"},
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 12, "time": 3.0, "text": "DIE BRÜCKE BRICHT – HÄMMERE DICH FREI!", "flag": "ch2_bridge",
				"success": [{"t": "move", "who": 0, "x": -1.6, "time": 0.4}, {"t": "say", "who": "volt", "text": "Festen Boden unter den Füßen. Jetzt du!"}],
				"fail": [{"t": "fx", "kind": "shake"}, {"t": "pose", "who": 0, "pose": "HitReact", "time": 0.6}, {"t": "say", "who": "volt", "text": "Verbrannt … aber nicht geschmolzen."}]},
			{"t": "fight", "cast": ["volt", "bastion"], "lives": [3, 2], "qte": "ch2_bridge",
				"goal": "Kühle den Wächter der Glutschmiede ab!"},
			{"t": "stage", "cast": [{"id": "volt", "x": -1.5, "facing": 1}, {"id": "bastion", "x": 1.6, "facing": -1}]},
			{"t": "cam", "shot": "two", "who": 0, "who2": 1, "time": 0.01},
			{"t": "say", "who": "bastion", "text": "Die Glut … brennt wieder. Du hast ein Verb in mir entzündet, kleiner Blitz: ERWACHEN."},
			{"t": "say", "who": "bastion", "text": "Die Schreiberin Aria war hier. Sie schmiedete eine Feder aus Sternenstahl – und floh ins Kolosseum der Stimmen."},
			{"t": "say", "who": "bastion", "text": "Aber hüte dich vor Warrok. Er sammelt Kämpfer. Und er fragt nicht, woher ihre Kraft kommt."},
			{"t": "say", "who": "volt", "text": "Dann suche ich die Feder. Danke, Wächter."},
		],
	},
	{
		"id": "ch3", "title": "Das Kolosseum der Stimmen", "arena": "imperial_colosseum",
		"steps": [
			{"t": "stage", "cast": [{"id": "volt", "x": -2.8, "facing": 1}, {"id": "dreyar", "x": 2.8, "facing": -1}, {"id": "warrok", "x": 8.4, "facing": -1}]},
			{"t": "cam", "shot": "sky", "time": 0.01},
			{"t": "title", "text": "KAPITEL 3", "sub": "Das Kolosseum der Stimmen"},
			{"t": "narrate", "text": "Tausend Stimmen jubeln. Im Kolosseum kämpfen Promptgeborene um das Recht, im Urtext zu bleiben."},
			{"t": "cam", "shot": "close", "who": 2, "time": 1.4},
			{"t": "say", "who": "warrok", "text": "EIN NEUER! Hört ihr das, Stimmen? Der Blitz will mitspielen! Dreyar – zeig ihm unsere Gastfreundschaft."},
			{"t": "cam", "shot": "two", "who": 0, "who2": 1, "time": 1.0},
			{"t": "say", "who": "dreyar", "text": "Ich kämpfe nicht für Warrok. Ich kämpfe, weil die Klinge es verlangt. Zieh."},
			{"t": "say", "who": "volt", "text": "Ich suche nur eine Feder – und die Frau, die sie trägt."},
			{"t": "say", "who": "dreyar", "text": "Dann hole sie dir, nachdem du an mir vorbeigekommen bist."},
			{"t": "qte", "kind": "sequence", "keys": ["standard", "special", "grab"], "time": 1.1, "text": "DREI WINDKLINGEN – PARIERE SIE!", "flag": "ch3_parry",
				"success": [{"t": "pose", "who": 0, "pose": "Block", "time": 0.5}, {"t": "say", "who": "dreyar", "text": "Alle drei pariert. Du hast Talent, Blitz."}],
				"fail": [{"t": "pose", "who": 0, "pose": "HitReact", "time": 0.6}, {"t": "say", "who": "dreyar", "text": "Zu langsam. Der Wind wartet auf niemanden."}]},
			{"t": "fight", "cast": ["volt", "dreyar"], "lives": [3, 3], "qte": "ch3_parry",
				"goal": "Besiege den Klingenmeister Dreyar!"},
			{"t": "stage", "cast": [{"id": "volt", "x": -1.8, "facing": 1}, {"id": "dreyar", "x": 1.2, "facing": -1}, {"id": "warrok", "x": 5.5, "facing": -1}]},
			{"t": "cam", "shot": "two", "who": 0, "who2": 1, "time": 0.01},
			{"t": "say", "who": "dreyar", "text": "Eine ehrliche Niederlage. Die Schreiberin war hier, Volt. Warrok hat ihr die Feder abgenommen."},
			{"t": "cam", "shot": "close", "who": 2, "time": 0.8},
			{"t": "fx", "kind": "ink", "who": 2},
			{"t": "say", "who": "warrok", "text": "Die Feder? Die gehört jetzt NULLA. Und bald auch ich. Die Tinte macht mich STÄRKER, als der Urtext es je wollte!"},
			{"t": "move", "who": 2, "x": 12.0, "time": 1.2},
			{"t": "vanish", "who": 2},
			{"t": "say", "who": "dreyar", "text": "Er flieht zur Bastion. Allein schaffst du das nicht. Such die Salzkrähe im Hafen – Kapitän Korsar schuldet mir einen Gefallen."},
		],
	},
	{
		"id": "ch4", "title": "Salz und Schießpulver", "arena": "pirate_galleon",
		"steps": [
			{"t": "stage", "cast": [{"id": "volt", "x": -3.0, "facing": 1}, {"id": "korsar", "x": 3.0, "facing": -1}]},
			{"t": "cam", "shot": "sky", "time": 0.01},
			{"t": "title", "text": "KAPITEL 4", "sub": "Salz und Schießpulver"},
			{"t": "narrate", "text": "Der Hafen riecht nach Salz und Pulverdampf. Die Salzkrähe liegt vor Anker – die Kanonen auf den Steg gerichtet."},
			{"t": "cam", "shot": "close", "who": 1, "time": 1.2},
			{"t": "say", "who": "korsar", "text": "Noch ein Tintendieb! Letzte Nacht hat einer wie du mein Logbuch geleert. Jede Seite – weiß!"},
			{"t": "say", "who": "volt", "text": "Ich bin kein Dieb. Dreyar schickt mich!"},
			{"t": "say", "who": "korsar", "text": "Das kann jeder behaupten. Kanonen – FEUER!"},
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.1, "text": "KANONENKUGEL – BLOCKE!", "flag": "ch4_cannon",
				"success": [{"t": "fx", "kind": "burst", "who": 0}, {"t": "say", "who": "korsar", "text": "Abgeblockt?! Na schön, Landratte – dann eben Mann gegen … was auch immer du bist."}],
				"fail": [{"t": "fx", "kind": "shake"}, {"t": "pose", "who": 0, "pose": "HitReact", "time": 0.6}, {"t": "say", "who": "korsar", "text": "Volltreffer! Und jetzt das Entermesser!"}]},
			{"t": "fight", "cast": ["volt", "korsar"], "lives": [3, 2], "qte": "ch4_cannon",
				"goal": "Überzeuge Kapitän Korsar – mit den Fäusten."},
			{"t": "stage", "cast": [{"id": "volt", "x": -1.4, "facing": 1}, {"id": "korsar", "x": 1.4, "facing": -1}]},
			{"t": "cam", "shot": "two", "who": 0, "who2": 1, "time": 0.01},
			{"t": "say", "who": "korsar", "text": "Hah! Kein Tintendieb kämpft so sauber. Du blutest Licht, nicht Tusche."},
			{"t": "say", "who": "volt", "text": "Warrok hat die Feder der Schreiberin. Er ist auf dem Weg zur Bastion."},
			{"t": "say", "who": "korsar", "text": "Die Bastion? Dort liegt das Tor zum Herzen des Urtexts. Setzt NULLA die Feder dort an …"},
			{"t": "say", "who": "korsar", "text": "… dann schreibt sie das Ende. Gut. Die Salzkrähe segelt mit dir, Blitz."},
		],
	},
	{
		"id": "ch5", "title": "Die Bastion fällt", "arena": "gladiator_fortress",
		"steps": [
			{"t": "stage", "cast": [{"id": "volt", "x": -3.0, "facing": 1}, {"id": "korsar", "x": -4.4, "facing": 1}, {"id": "warrok", "x": 3.0, "facing": -1}, {"id": "kalden", "x": 4.6, "facing": -1}]},
			{"t": "cam", "shot": "sky", "time": 0.01},
			{"t": "title", "text": "KAPITEL 5", "sub": "Die Bastion fällt"},
			{"t": "narrate", "text": "Die Bastion brennt schwarz. Tinte rinnt die Mauern hinab wie Regen, der nach oben fällt."},
			{"t": "cam", "shot": "close", "who": 3, "time": 1.2},
			{"t": "say", "who": "volt", "text": "Sir Kalden?! Du warst frei!"},
			{"t": "say", "who": "kalden", "text": "Sie … hat mich … neu geschrieben. Lauf, Volt. Ich kann … die Hand nicht halten."},
			{"t": "cam", "shot": "low", "who": 2, "time": 0.8},
			{"t": "fx", "kind": "ink", "who": 2},
			{"t": "say", "who": "warrok", "text": "Zwei gegen zwei! Endlich ein Kampf, der dem Kolosseum würdig ist!"},
			{"t": "say", "who": "korsar", "text": "Ich nehme den Blechmann. Du den Großen. Und Volt – wirf nicht mich vom Steg."},
			{"t": "fight", "cast": ["volt", "warrok", "korsar", "kalden"], "teams": [0, 1, 0, 1], "lives": [3, 2, 2, 1],
				"goal": "Team-Kampf: Besiegt Warrok und den Tintenritter!"},
			{"t": "stage", "cast": [{"id": "volt", "x": -1.2, "facing": 1}, {"id": "korsar", "x": -2.6, "facing": 1}, {"id": "warrok", "x": 1.8, "facing": -1}]},
			{"t": "cam", "shot": "two", "who": 0, "who2": 2, "time": 0.01},
			{"t": "pose", "who": 2, "pose": "Defeat", "time": 1.0},
			{"t": "say", "who": "warrok", "text": "Die Feder … ist fort. NULLA hat sie längst. Ich war nur … eine Fußnote."},
			{"t": "say", "who": "volt", "text": "Wohin ist sie?"},
			{"t": "say", "who": "warrok", "text": "In den Lichthain. Dort, wo die Schreiberin ihre ersten Worte schrieb. NULLA will … den Anfang löschen."},
		],
	},
	{
		"id": "ch6", "title": "Das Licht im Hain", "arena": "mystic_grove",
		"steps": [
			{"t": "stage", "cast": [{"id": "volt", "x": -2.6, "facing": 1}, {"id": "aura", "x": 2.6, "facing": -1}]},
			{"t": "cam", "shot": "sky", "time": 0.01},
			{"t": "title", "text": "KAPITEL 6", "sub": "Das Licht im Hain"},
			{"t": "narrate", "text": "Im Lichthain leuchten die Bäume von innen. Hier ist die Tinte noch nicht angekommen – noch nicht."},
			{"t": "cam", "shot": "close", "who": 1, "time": 1.4},
			{"t": "say", "who": "aura", "text": "Du trägst Arias Handschrift, Blitz. Ich erkenne jeden Strich. Aber bist du stark genug für das, was kommt?"},
			{"t": "say", "who": "volt", "text": "Ich habe einen Ritter befreit, eine Schmiede entzündet und einen Kapitän überzeugt. Reicht das nicht?"},
			{"t": "say", "who": "aura", "text": "Gegen NULLA reicht nichts, was schon geschrieben wurde. Zeig mir, was du NOCH NICHT bist."},
			{"t": "fight", "cast": ["volt", "aura"], "lives": [2, 2],
				"goal": "Bestehe Auras Prüfung!"},
			{"t": "stage", "cast": [{"id": "volt", "x": -1.3, "facing": 1}, {"id": "aura", "x": 1.3, "facing": -1}]},
			{"t": "cam", "shot": "two", "who": 0, "who2": 1, "time": 0.01},
			{"t": "say", "who": "aura", "text": "Gut. Dann höre die Wahrheit. NULLA ist kein Feind von außen."},
			{"t": "say", "who": "aura", "text": "Sie ist Arias erster Entwurf. Die Seite, die sie zerknüllte, weil sie nicht gut genug war. Eine Leere, die geschrieben werden wollte."},
			{"t": "say", "who": "volt", "text": "Dann … bin ich der zweite Versuch?"},
			{"t": "say", "who": "aura", "text": "Du bist der letzte. Und in dir steckt noch ein zweiter – der Entwurf, den Aria von dir gelöscht hat. NULLA hat ihn gefunden."},
			{"t": "fx", "kind": "shake"},
			{"t": "say", "who": "aura", "text": "Er kommt. Heute Nacht, unter dem Blutmond."},
		],
	},
	{
		"id": "ch7", "title": "Blutmond", "arena": "blood_moon",
		"steps": [
			{"t": "stage", "cast": [{"id": "volt", "x": -2.4, "facing": 1}, {"id": "aura", "x": -4.0, "facing": 1}, {"id": "schatten", "x": 9.0, "facing": -1}]},
			{"t": "cam", "shot": "sky", "time": 0.01},
			{"t": "title", "text": "KAPITEL 7", "sub": "Blutmond"},
			{"t": "narrate", "text": "Der Mond färbt sich rot. Auf der Terrasse, wo alles begann, wartet ein Schatten mit Volts Gesicht."},
			{"t": "move", "who": 2, "x": 2.6, "time": 1.2},
			{"t": "cam", "shot": "close", "who": 2, "time": 0.9},
			{"t": "say", "who": "schatten", "text": "Hallo, Original. Aria hat mich zuerst geschrieben – dann hat sie mich ausradiert, weil ich zu wütend war."},
			{"t": "say", "who": "schatten", "text": "Weißt du, wie es sich anfühlt, gelöscht zu werden? Gleich schon."},
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "pose", "who": 1, "pose": "HitReact", "time": 0.5},
			{"t": "say", "who": "aura", "text": "Volt – ich falle! Die Tinte zieht mich über den Rand!"},
			{"t": "qte", "kind": "press", "keys": ["grab"], "time": 1.0, "text": "FANG AURA!", "flag": "ch7_catch",
				"success": [{"t": "move", "who": 1, "x": -3.2, "time": 0.3}, {"t": "say", "who": "aura", "text": "Gefangen … danke. Jetzt beende das, Volt."}],
				"fail": [{"t": "vanish", "who": 1}, {"t": "say", "who": "volt", "text": "AURA! … Du wirst dafür bezahlen, Schatten!"}]},
			{"t": "fight", "cast": ["volt", "schatten"], "lives": [3, 3], "qte": "ch7_catch", "mods": {"1": {"power": 1.1}},
				"goal": "Besiege deinen gelöschten Entwurf!"},
			{"t": "stage", "cast": [{"id": "volt", "x": -1.3, "facing": 1}, {"id": "schatten", "x": 1.3, "facing": -1}]},
			{"t": "cam", "shot": "two", "who": 0, "who2": 1, "time": 0.01},
			{"t": "pose", "who": 1, "pose": "Defeat", "time": 1.0},
			{"t": "say", "who": "schatten", "text": "Warum … bist du stärker? Wir sind aus derselben Tinte."},
			{"t": "say", "who": "volt", "text": "Weil ich nicht allein geschrieben wurde. Ritter, Wächter, Klingen, Kapitäne – jeder hat eine Zeile beigetragen."},
			{"t": "say", "who": "schatten", "text": "Dann … schreib mich zu Ende, Original. Nicht löschen. Zu Ende schreiben."},
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			{"t": "say", "who": "aria", "text": "Volt … ich bin am Herzen des Urtexts. NULLA hat die Feder angesetzt. Sie schreibt das Wort ENDE."},
		],
	},
	{
		"id": "ch8", "title": "Die letzte Zeile", "arena": "volcano_sanctum",
		"steps": [
			{"t": "stage", "cast": [{"id": "volt", "x": -3.0, "facing": 1}, {"id": "nulla", "x": 3.0, "facing": -1}]},
			{"t": "cam", "shot": "sky", "time": 0.01},
			{"t": "title", "text": "KAPITEL 8", "sub": "Die letzte Zeile"},
			{"t": "narrate", "text": "Das Herz des Urtexts. Jeder Satz der Welt fließt hier zusammen – und in der Mitte schwebt die Leere."},
			{"t": "cam", "shot": "low", "who": 1, "time": 1.6},
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "say", "who": "nulla", "text": "Der letzte Promptgeborene. Du bist nur eine Zeile, die noch nicht gelöscht wurde."},
			{"t": "say", "who": "nulla", "text": "Aria hat mich zerknüllt. Weggeworfen. Jetzt werfe ich ihre Welt weg. Ist das nicht gerecht?"},
			{"t": "cam", "shot": "close", "who": 0, "time": 1.0},
			{"t": "say", "who": "volt", "text": "Du willst nicht das Ende. Du willst einen Namen. Einen Satz, der dir gehört."},
			{"t": "say", "who": "nulla", "text": "Schweig! Ich werde dich in weißes Papier verwandeln!"},
			{"t": "fight", "cast": ["volt", "nulla"], "lives": [3, 3], "mods": {"1": {"power": 1.25, "kb": 0.8}},
				"goal": "ENDKAMPF: Halte NULLA auf!"},
			{"t": "stage", "cast": [{"id": "volt", "x": -1.6, "facing": 1}, {"id": "nulla", "x": 1.6, "facing": -1}]},
			{"t": "cam", "shot": "two", "who": 0, "who2": 1, "time": 0.01},
			{"t": "pose", "who": 1, "pose": "HitReact", "time": 1.0},
			{"t": "say", "who": "nulla", "text": "Die Feder … entgleitet mir. Tu es. Lösch mich. Das ist doch das Ende, das du willst."},
			{"t": "say", "who": "volt", "text": "Nein. Ich schreibe die letzte Zeile – aber nicht so, wie du denkst."},
			{"t": "qte", "kind": "sequence", "keys": ["jump", "standard", "special", "grab"], "time": 1.2, "text": "SCHREIBE DIE LETZTE ZEILE!", "flag": "ch8_line",
				"success": [{"t": "fx", "kind": "flash"}, {"t": "narrate", "text": "»Und die Leere bekam einen Namen – und wurde der Anfang einer neuen Geschichte.«"}],
				"fail": [{"t": "fx", "kind": "flash"}, {"t": "narrate", "text": "Die Feder zittert. Doch Volt setzt sie erneut an – und schreibt, Buchstabe für Buchstabe, einen Namen in die Leere."}]},
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "say", "who": "nulla", "text": "Ein … Name. Niemand hat mir je einen Namen geschrieben."},
			{"t": "say", "who": "aria", "text": "Ich hätte es tun sollen, damals. Verzeih mir. Du bist NOVA – die erste Seite einer neuen Welt."},
			{"t": "pose", "who": 0, "pose": "Victory", "time": 1.6},
			{"t": "say", "who": "volt", "text": "Die letzte Zeile ist geschrieben. Und nach der letzten Zeile … kommt die nächste Seite."},
			{"t": "narrate", "text": "Die Tinte versiegte. Lexara wurde neu geschrieben – diesmal von vielen Händen."},
			{"t": "credits"},
		],
	},
]

static func chapter_count() -> int:
	return CHAPTERS.size()
