extends RefCounted
## LEGENDEN: one short personal story per fighter, four chapters each, unlocked by playing that
## fighter (mastery stars, progression.gd MASTERY):
##   I   Herkunft      (always)   – where they come from, a first fight
##   II  Der Rivale    (★1)       – the one who knows their weak spot
##   III Der Abgrund   (★2)       – an angel or demon tests the wound
##   IV  Legende       (★3)       – the fighter meets their own shadow; ending cinematic
## Finishing chapter IV gives the fighter's relic (progression.legend_relics): +15 % healing in
## the adventure, a gold frame on the card, coins and the legend chest (rewards.gd open_legend_chest).
## Steps use the story format (story_data.gd); story_mode.gd plays them as campaign "legend".

const STARS := [0, 1, 2, 3]
const RELIC_COINS := 400
const CHAPTER_NAMES := ["Herkunft", "Der Rivale", "Der Abgrund", "Legende"]

## id: [home arena, rival id, abyss boss, epithet, origin, wound, vow, rival line, abyss line, shadow line, ending]
const LEGENDS := {
	"ninja": ["neon_metropolis", "echo", "asmodeus", "Der letzte Promptgeborene",
		"Volt wurde aus einem einzigen Satz geboren: »Sei schneller als das Ende.« Seitdem rennt er.",
		"Er hat nie gelernt, stehen zu bleiben – auch nicht, wenn jemand ihn braucht.",
		"Diesmal laufe ich nicht weg. Diesmal laufe ich hin.",
		"Ich bin du, nur ohne Zögern. Wer von uns ist das bessere Programm?",
		"Asmodeus bietet ihm unendliche Geschwindigkeit – für einen einzigen Moment Stillstand pro Herzschlag.",
		"Du rennst, weil du Angst hast, was passiert, wenn du ankommst.",
		"Volt bleibt stehen. Zum ersten Mal hört er die Stadt atmen. Und sie atmet mit ihm."],
	"golem": ["volcano_sanctum", "warrok_brute", "mammon", "Glut, die nicht erlischt",
		"Magmor war einst der Ofen einer Schmiedestadt. Als die Schmiede starben, glühte er einfach weiter.",
		"Er glaubt, er ist nur so viel wert wie die Hitze, die er abgibt.",
		"Ich bin kein Werkzeug. Ich bin das Feuer, das sie zurückgelassen haben.",
		"Steine wie du zerbrechen, Ofen. Ich habe schon Berge zerbrochen.",
		"Mammon wiegt Magmors Glut in Gold auf – und bietet ihm einen Thron aus kalter Asche.",
		"Ohne Feuer bist du nur ein Haufen Schlacke. Gib es zu.",
		"Magmor kühlt ab, ein wenig. Und merkt, dass er noch da ist. Kalt, still – und er selbst."],
	"valkyrie": ["imperial_colosseum", "steel_knight", "angelus", "Die Armbrust der Morgenwache",
		"Boltar diente der Morgenwache, bis die Wache verraten wurde. Sie war die Einzige, die das Tor hielt.",
		"Sie trägt jeden Gefallenen wie einen Pfeil im eigenen Köcher.",
		"Ich halte das Tor. So lange, bis keiner mehr hindurch muss.",
		"Du hast sie alle sterben lassen, Boltar. Ich war dabei. Ich zähle sie dir vor.",
		"Angelus prüft ihre Treue: Wem gehört ihr Schwur – den Toten oder den Lebenden?",
		"Lass die Toten los, und du hast nichts mehr, wofür du kämpfst.",
		"Boltar legt die Pfeile der Gefallenen ins Feuer. Einer nach dem anderen. Der Köcher wird leicht."],
	"dragon": ["volcano_sanctum", "pyrax", "baphomet", "Wächter der verbrannten Stadt",
		"Der Templar schwor, seine Stadt zu schützen. Dann kam der Drache – und der Templar trug ihn fortan in seiner Klinge.",
		"Er weiß nicht mehr, wo der Ritter aufhört und der Drache beginnt.",
		"Ich bin der Schwur. Nicht das Feuer.",
		"Wir sind aus derselben Glut, Ritter. Lass mich frei, und du brennst nie wieder allein.",
		"Baphomet zeigt ihm die Stadt, wie sie hätte sein können – wenn er sie dem Drachen überlassen hätte.",
		"Du hast die Stadt nicht gerettet. Du hast sie nur langsamer verbrennen lassen.",
		"Der Templar steckt die Klinge in den Boden. Aus der Asche wächst ein erster grüner Halm."],
	"kairo": ["frozen_summit", "varakh", "michael", "Der Sturmmönch",
		"Kairo meditierte dreißig Jahre auf einem Gipfel, bis der Sturm selbst bei ihm anklopfte.",
		"Er sucht Stille – und findet sie nur im Kampf.",
		"Der Sturm ist nicht mein Feind. Er ist mein Atem.",
		"Dreißig Jahre gesessen, Mönch? Ich habe in der Zeit drei Reiche erobert.",
		"Michael fragt ihn, warum ein Mann des Friedens so gern die Fäuste ballt.",
		"Deine Ruhe ist nur ein Deckel auf einem kochenden Topf.",
		"Kairo lacht – zum ersten Mal seit dreißig Jahren. Der Sturm legt sich, um zuzuhören."],
	"varakh": ["blood_moon", "kairo", "lucifer", "Der Scharlachfürst",
		"Varakh war der jüngste von sieben Prinzen. Er ließ die anderen sechs hinter sich – einen nach dem anderen.",
		"Stolz ist das Einzige, was er nie verloren hat. Er hat alles andere dafür geopfert.",
		"Ich verbeuge mich vor niemandem.",
		"Stolz ist ein schwerer Mantel, Prinz. Irgendwann erdrückt er dich.",
		"Luzifer erkennt sich in ihm wieder – und bietet ihm einen Platz an seiner Seite.",
		"Du warst nie der Größte. Du warst nur der Einsamste.",
		"Varakh senkt den Kopf. Nicht vor einem Herrscher – vor den sechs Namen, die er nie wieder aussprach."],
	"xylar": ["neon_metropolis", "oryn", "beelzebub", "Der Leerenkaiser",
		"Xylar regierte ein Reich aus Nichts. Seine Untertanen waren Echos, seine Krone ein Loch im Himmel.",
		"Er verschlingt alles, weil er nicht weiß, was es heißt, satt zu sein.",
		"Das Universum ist ein Mahl. Ich bin der Hunger.",
		"Du frisst Welten, Kaiser, und bleibst doch hohl. Ich habe deinen Untergang gesehen.",
		"Beelzebub, Herr der Gier, lacht über ihn: ein Kaiser, der nicht einmal sich selbst gehört.",
		"Du bist leer. Und das Schlimmste: Du warst es schon immer.",
		"Xylar hält eine einzige Sternschnuppe in der Hand. Er lässt sie fliegen. Es fühlt sich an wie Fülle."],
	"glaciem": ["frozen_summit", "frostwyrm", "leviathan", "Das gefrorene Herz",
		"Glaciem fror ihr eigenes Herz ein, um eine Lawine aufzuhalten, die ihr Dorf begraben hätte.",
		"Seitdem fühlt sie nichts – und hat Angst davor, wieder zu fühlen.",
		"Kälte ist ein Versprechen: Nichts kann mich mehr verletzen.",
		"Ich bin der Winter, der dich geboren hat, kleine Klinge. Komm nach Hause.",
		"Leviathan, der Neid, zeigt ihr all die warmen Herzen, die sie nie haben wird.",
		"Wenn du auftaust, zerbrichst du. Bleib Eis.",
		"Eine Träne rinnt über Glaciems Wange – und gefriert nicht. Es tut weh. Es ist wunderbar."],
	"oryn": ["blood_moon", "xylar", "dominatio", "Der Prophet, der das Ende sah",
		"Oryn sah in einer einzigen Nacht das Ende aller Welten. Er hat seitdem nicht mehr geschlafen.",
		"Er glaubt, nur er kann die Welten retten – indem er sie zerdrückt.",
		"Ich habe das Ende gesehen. Ich lasse es nicht geschehen.",
		"Prophet? Du bist nur ein Mann, der zu oft in den Abgrund geschaut hat.",
		"Dominatio, Engel der Herrschaft, fragt ihn: Wer gab dir das Recht, für alle zu entscheiden?",
		"Du willst die Welt retten, weil du nicht weißt, wie man in ihr lebt.",
		"Oryn schließt die Augen und schläft ein. Im Traum sieht er kein Ende. Nur einen Morgen."],
	"tobi": ["pirate_galleon", "pirate_captain", "mammon", "Kapitän ohne Mannschaft",
		"Tobi verlor seine Mannschaft an einen einzigen Sturm. Seitdem kämpft er für fünf.",
		"Er lacht laut, damit niemand hört, wie leise sein Schiff geworden ist.",
		"Ich brauche kein Schiff. Ich brauche nur Leute, die ich beschützen kann!",
		"Kapitän? Ohne Mannschaft bist du nur ein Junge mit großen Fäusten.",
		"Mammon bietet ihm eine Flotte aus Gold – mit Matrosen, die niemals widersprechen.",
		"Du hast sie verloren, weil du zu laut warst, um den Sturm zu hören.",
		"Am Horizont: ein kleines Boot, fünf Gestalten winken. Tobi springt ins Wasser und schwimmt."],
	"jubei": ["mystic_grove", "samurai_dreyar", "belphegor", "Meister der drei Klingen",
		"Jubei trägt drei Klingen: eine für seinen Meister, eine für seinen Rivalen, eine für sich selbst.",
		"Die dritte hat er noch nie gezogen.",
		"Zwei Klingen schneiden. Die dritte entscheidet.",
		"Du ziehst die dritte Klinge nie, Wanderer. Weil du weißt, dass du sie nicht verdienst.",
		"Belphegor, die Trägheit, flüstert: Warum kämpfen, wenn die Klinge auch in der Scheide glänzt?",
		"Die dritte Klinge bin ich. Zieh mich – wenn du dich traust.",
		"Jubei zieht die dritte Klinge. Sie ist stumpf. Er lacht – sie war nie zum Schneiden gedacht."],
	"ren": ["mystic_grove", "thorn_witch", "lilith", "Die Kirschkriegerin",
		"Ren wuchs unter einem Kirschbaum auf, der jedes Jahr blühte, bis eine Hexe ihn verfluchte.",
		"Sie kämpft, damit nie wieder etwas Schönes welkt – und vergisst dabei selbst zu blühen.",
		"Jede Blüte, die fällt, wird zur Klinge.",
		"Blüten welken, Kirschkind. Dornen bleiben.",
		"Lilith bietet ihr ewige Blüte – einen Frühling, der nie endet und nie wieder Früchte trägt.",
		"Du hast Angst vor dem Herbst. Darum wirst du nie reif.",
		"Der Kirschbaum blüht wieder. Diesmal setzt sich Ren darunter und sieht einfach nur zu."],
	"amethya": ["neon_metropolis", "sorceress_medea", "potestas", "Die Donnerhexe",
		"Amethya fing einen Blitz in einem Kristall, als sie sieben war. Er hat sie nie wieder losgelassen.",
		"Sie weiß nicht, ob sie den Donner beherrscht – oder er sie.",
		"Ich bin nicht der Sturm. Ich bin die, die ihn lenkt.",
		"Kristalle splittern, Kind. Und du splitterst mit.",
		"Potestas, Engel der Gewalten, verlangt, dass sie den Blitz zurückgibt.",
		"Ohne Donner bist du nur ein Mädchen mit einem Stein in der Hand.",
		"Amethya lässt den Blitz frei. Er tanzt um sie herum – und kehrt freiwillig zurück."],
	"bruno": ["imperial_colosseum", "warrok_brute", "belphegor", "Der Unbesiegte",
		"Bruno hat nie einen Kampf verloren. Er hat auch nie einen gewollt.",
		"Er ist so stark, dass ihm nichts mehr etwas bedeutet.",
		"… Ich hätte gern Hunger. Richtigen Hunger. Auf irgendwas.",
		"Ein Schlag, sagen sie? Dann schlag mich, Bruno. Zeig mir, dass es dir etwas bedeutet.",
		"Belphegor findet ihn gähnend – und bietet ihm den ewigen Schlaf als Belohnung.",
		"Du bist nicht stark. Du bist nur gelangweilt.",
		"Bruno verliert eine Partie Karten gegen ein Kind. Er lacht so laut, dass das Kolosseum bebt."],
	"hikaru": ["mystic_grove", "jubei", "hell_gate_boss", "Erbe der Glutklinge",
		"Hikaru erbte die Glutklinge von seiner Schwester. Sie hätte sie besser geführt, sagt er.",
		"Er kämpft mit zwei Händen: seiner eigenen und der Erinnerung an sie.",
		"Ich trage ihr Feuer, bis es meins ist.",
		"Du kopierst sie, Junge. Jeder Schritt, jeder Schnitt – nur nicht ihr Mut.",
		"Ahriman, die Finsternis, bietet ihm seine Schwester zurück – als Schatten an seiner Seite.",
		"Ohne sie bist du niemand. Gib es zu.",
		"Hikaru schwingt die Glutklinge im eigenen Rhythmus. Irgendwo, ganz leise, klatscht jemand."],
	"zip": ["neon_metropolis", "ninja", "virtus", "Der Kurier, der nie ankam",
		"Zip lieferte jede Nachricht der Stadt – außer einer: den Brief, den er an sich selbst schrieb.",
		"Er ist so schnell, dass er nie erfährt, wie die Geschichten ausgehen.",
		"Liefern, liefern, liefern – irgendwann bin ich dran!",
		"Du bist schnell, Kurier. Aber ich bin schneller – und ich weiß, was in deinem Brief steht.",
		"Virtus, Engel der Kräfte, hält ihn an: Wohin rennst du, wenn alle Briefe zugestellt sind?",
		"Lies den Brief nie. Dann musst du nie wissen, wer du bist.",
		"Zip öffnet den Brief. Darin steht nur: »Du darfst ankommen.« Er setzt sich auf eine Bank."],
	"raiga": ["frozen_summit", "albion", "bel_marduk", "Die Donnerfaust mit dem Kompass",
		"Raigas Kompass zeigt nicht nach Norden, sondern zum nächsten Kampf. Er hat nie falsch gezeigt.",
		"Sie folgt ihm blind, weil sie Angst hat, selbst eine Richtung zu wählen.",
		"Die Nadel zeigt auf dich. Also kämpfen wir.",
		"Dein Kompass zeigt nicht auf Kämpfe, Raiga. Er zeigt auf deine Angst.",
		"Bel Marduk, der Zorn, dreht die Nadel – und sie zeigt plötzlich auf Raiga selbst.",
		"Ohne den Kompass wüsstest du nicht einmal, wo vorne ist.",
		"Raiga wirft den Kompass in den Schnee und geht los. Sie weiß nicht wohin. Es fühlt sich richtig an."],
	"albion": ["frozen_summit", "frostwyrm", "seraph", "Der Silberwyrm",
		"Albion ist der letzte Silberwyrm. Seine Schuppen spiegeln jeden Sturm, der je über die Gipfel zog.",
		"Er hütet einen Schatz, an den sich niemand mehr erinnert – nicht einmal er.",
		"Ich bin der Sturm über den Wolken. Kommt hinauf, wenn ihr euch traut.",
		"Wir sind beide Wyrme, Silberner. Aber nur einer von uns ist nicht allein.",
		"Der Seraph fragt nach dem Schatz. Albion schweigt – und weiß selbst nicht, warum.",
		"Der Schatz war nie Gold. Es war jemand, den du vergessen hast.",
		"Albion findet in seinem Hort ein kleines Kinderspielzeug aus Holz. Er erinnert sich. Er lächelt."],
	"pyrax": ["volcano_sanctum", "dragon", "hell_flames_boss", "Die Glutwyvern",
		"Pyrax schlüpfte im Krater eines Vulkans und hielt Lava für Wasser, bis sie das erste Mal fror.",
		"Sie verbrennt alles, was ihr nahe kommt – und wünscht sich nichts so sehr wie Nähe.",
		"Wer mich umarmen will, muss Feuer lieben!",
		"Du wirst nie jemanden halten können, Wyvern. Dein Herz ist ein Scheiterhaufen.",
		"Lilith flüstert ihr: Lass alles brennen, dann bist du nie wieder die Einzige, die glüht.",
		"Deine Flammen sind Einsamkeit, die man sehen kann.",
		"Pyrax lernt, ihre Glut leise zu stellen. Ein Wanderer wärmt sich an ihr die Hände. Er bleibt."],
	"anubis": ["imperial_colosseum", "skeleton_reaper", "ahriman", "Das Goldkonstrukt",
		"Aurum wurde gebaut, um die Herzen der Toten zu wiegen. Eines Tages wog er sein eigenes.",
		"Seine Waage blieb stehen – genau in der Mitte. Er weiß nicht, was er ist.",
		"Ich wiege. Ich richte. Ich urteile ohne Hass.",
		"Ein Richter aus Gold? Du bist nur ein Schmuckstück, das sich für göttlich hält.",
		"Ahriman legt eine Feder auf seine Waage – schwärzer als die Nacht.",
		"Du richtest andere, weil du dein eigenes Urteil fürchtest.",
		"Aurum legt die Waage nieder und reicht einer verirrten Seele die Hand, statt sie zu wiegen."],
	"specter": ["blood_moon", "vampire_lord", "lilith", "Die Schattenklinge",
		"Ravenna starb an einem Ort ohne Licht und kehrte als Kristall zurück, der jedes Licht schluckt.",
		"Sie fürchtet, dass von ihr nur noch Schatten übrig ist.",
		"Ich bin der Schatten, der zurückschlägt.",
		"Kristall und Dunkelheit, Liebes – wir zwei gehören zusammen.",
		"Lilith ruft sie Tochter – und bietet ihr ein Reich ohne Sonne.",
		"Du warst nie lebendig. Du warst nur ein Spiegelbild.",
		"Ein Sonnenstrahl bricht durch Ravennas Kristall – und malt einen Regenbogen an die Wand."],
	"phoenix": ["volcano_sanctum", "wizard_sorcerer", "seraph", "Die Feuerjägerin",
		"Scarlet ist schon neunmal gestorben. Jedes Mal kam sie zurück – mit einer Erinnerung weniger.",
		"Sie weiß nicht mehr, wofür sie ursprünglich gekämpft hat.",
		"Ich verbrenne – und steige wieder auf!",
		"Neun Leben, Scarlet, und keines davon gehörte dir.",
		"Der Seraph fragt sie nach ihrem Namen. Ihrem ersten Namen.",
		"Beim zehnten Mal bleibt nichts mehr von dir übrig.",
		"Scarlet erinnert sich: Sie hieß Lina und liebte Erdbeeren. Sie isst eine. Sie schmeckt nach Leben."],
	"arber": ["gladiator_fortress", "grimbolt", "bel_marduk", "Der Bohrmeister",
		"Arbër kam aus den Bergen der Shqiponja, wo man sagt: Ein Wort ist ein Fels. Er wurde Handwerker und baute, was andere einrissen.",
		"Er hat einem sterbenden Freund ein Versprechen gegeben – Besa – und weiß nicht, ob er es halten kann.",
		"Besa ist Besa. Was ich verspreche, das baue ich.",
		"Zwei Bohrer, Arbër? Ich hab eine Bombe. Mal sehen, was schneller ist!",
		"Bel Marduk, der Zorn, schleift ihn in einen Saal voller zerbrochener Häuser – alles, was er nicht retten konnte.",
		"Versprechen sind Sand, Bohrmeister. Du baust auf Sand.",
		"Der Doppelkopfadler kreist über den Bergen. Arbër setzt den letzten Stein ins Haus seines Freundes. Die Besa ist gehalten."],
	"brunhild": ["gladiator_fortress", "valkyrie", "michael", "Die Riesin mit der goldenen Axt",
		"Brunhild war die kleinste ihrer Sippe – bis sie die goldene Axt aus dem Gletscher zog und wuchs.",
		"Sie glaubt, sie ist nur groß, solange sie die Axt hält.",
		"Ich bin die Wand, an der eure Heere zerbrechen!",
		"Ohne die Axt bist du wieder das kleine Mädchen im Schnee, Brunhild.",
		"Michael verlangt die Axt zurück – sie gehört dem Himmel, sagt er.",
		"Leg die Axt ab, und du schrumpfst zu nichts.",
		"Brunhild legt die Axt ab. Sie bleibt groß. Sie war es die ganze Zeit."],
	"lepora": ["mystic_grove", "celestial_fox", "virtus", "Die Mondjägerin",
		"Lepora jagt nur bei Vollmond. Den Rest des Monats sucht sie den Pfeil, den sie als Kind verschoss.",
		"Sie hat nie getroffen, was sie wirklich treffen wollte.",
		"Der Mond zielt mit mir.",
		"Du jagst einen Pfeil, der längst im Himmel steckt, Jägerin.",
		"Virtus fragt: Was willst du treffen – und was hast du Angst zu treffen?",
		"Du verfehlst absichtlich. Weil Treffen bedeutet, dass die Jagd vorbei ist.",
		"Lepora findet den alten Pfeil in einem Baum, mitten im Herzen einer Schnitzerei: ihre Mutter, lachend."],
	"thorn_witch": ["mystic_grove", "ren", "lilith", "Die Dornenhexe",
		"Die Dornenhexe pflanzte einst Rosen. Als niemand sie besuchte, ließ sie nur noch die Dornen wachsen.",
		"Sie stößt jeden weg, bevor er sie verlassen kann.",
		"Komm näher – wenn du bluten willst.",
		"Du hast meinen Baum verflucht, Hexe. Ich bin gekommen, um ihn zurückzuholen.",
		"Lilith schenkt ihr einen Garten, in dem nie wieder jemand stört.",
		"Dornen schützen nicht. Sie halten dich gefangen.",
		"Unter den Dornen der Hexe öffnet sich eine einzige weiße Rose. Ren pflückt sie nicht. Sie bleibt."],
	"nyx": ["blood_moon", "skeleton_reaper", "lucifer", "Der Seelenernter",
		"Nyx erntet die Seelen der Gefallenen, damit sie nicht in der Dunkelheit herumirren. Niemand dankt ihm.",
		"Er hat so viele Seelen getragen, dass er seine eigene nicht mehr findet.",
		"Ich bin der letzte Halt vor der Nacht.",
		"Wir sind Kollegen, Nyx. Nur dass ich meine Arbeit genieße.",
		"Luzifer bietet ihm eine Pause – für immer, auf seinem Thron.",
		"Die Seelen lieben dich nicht. Sie fürchten dich.",
		"Eine kleine Seele, die Nyx einst trug, kehrt zurück und hält ihm die Sense, während er ausruht."],
	"shira": ["neon_metropolis", "celestial_fox", "asmodeus", "Die Oni-Klinge",
		"Shira war eine Straßenkatze der Neonstadt, bis eine Oni-Maske sie fand und nicht mehr losließ.",
		"Sie weiß nicht, ob die Maske sie stark macht – oder ob sie ohne die Maske nichts ist.",
		"Neun Leben? Ich brauche nur eins. Deins.",
		"Die Maske spricht durch dich, Kätzchen. Hörst du dich überhaupt noch selbst?",
		"Asmodeus verspricht ihr die Krone der Nacht – wenn sie die Maske für immer trägt.",
		"Zieh die Maske ab, und keiner wird dich mehr fürchten.",
		"Shira nimmt die Maske ab. Ein Kind auf der Straße lächelt sie an. Niemand fürchtet sie. Es ist gut so."],
	"frostwyrm": ["frozen_summit", "albion", "cocytus_boss", "Der Frost-Wyrm",
		"Der Frostwyrm schlief tausend Jahre unter dem Eis. Er erwachte, als jemand seinen Namen rief – und niemand war da.",
		"Er sucht die Stimme, die ihn geweckt hat.",
		"Mein Atem ist der Winter. Mein Herz wartet auf den Frühling.",
		"Wer soll dich gerufen haben, Eiswurm? Du bist eine Legende, die keiner mehr erzählt.",
		"Leviathan friert ihn tiefer ein als je zuvor: Bleib unten, flüstert der Neid, dort tut nichts weh.",
		"Niemand hat gerufen. Du hast es dir eingebildet.",
		"Ein Kind zeichnet einen blauen Drachen in den Schnee und ruft ihn beim Namen. Der Frostwyrm landet sanft daneben."],
	"cyborg_mech": ["neon_metropolis", "vanguard_soldier", "ophan", "Die Maschine mit dem Herzschlag",
		"Der Cyborg Mech war ein Kampfprototyp. Eines Tages fand die Wartung in ihm einen echten Herzschlag.",
		"Er weiß nicht, ob er ein Mensch in einer Maschine ist – oder eine Maschine, die träumt.",
		"Zielerfassung aktiv. Gefühle: unbekannt. Kampfbereit.",
		"Du bist Serienmodell 7, Blechkamerad. Es gibt sechs vor dir und hundert nach dir.",
		"Die Räder des Ophan drehen sich um ihn und fragen: Was bist du, wenn man dich abschaltet?",
		"Dein Herzschlag ist nur ein Fehler im Code.",
		"Der Mech legt die Hand auf die Brust. Bumm. Bumm. Er speichert den Klang ab – als Lieblingslied."],
	"reaper_hound": ["blood_moon", "nyx", "cerberus_alias", "Der Höllenhund",
		"Der Reaper Hound bewachte das Tor der Toten. Eines Tages lief er einem Kind hinterher, das sich verirrt hatte.",
		"Er weiß nicht, ob er ein Wächter ist – oder ein Hund, der nach Hause will.",
		"GRRRR. Niemand geht hier durch. Außer, er braucht Hilfe.",
		"Komm zurück an deinen Posten, Hund. Das Tor wartet nicht.",
		"Asmodeus bietet ihm eine Leine aus Gold – und einen Herrn, der nie stirbt.",
		"Du bist nur ein Wachhund. Keiner wird dich je streicheln.",
		"Das Kind von damals, längst erwachsen, kniet sich hin und krault dem Höllenhund die knochigen Ohren."],
	"treant": ["mystic_grove", "mossback", "belphegor", "Der Uralte Wald",
		"Der Treant war schon alt, als die ersten Arenen gebaut wurden. Er zählt die Jahre in Ringen und die Kämpfe in Narben.",
		"Er hat so viele Generationen sterben sehen, dass er niemanden mehr ins Herz lässt.",
		"Ich bin geduldig. Ich bin gewachsen, bevor es dich gab.",
		"Du bist morsch, Alter. Ich bin der Wald, der nach dir kommt.",
		"Belphegor bettet ihn in ewige Ruhe: Wurzeln, die nie wieder wandern müssen.",
		"Lass los. Du bist nur noch Holz, das sich weigert zu fallen.",
		"Aus dem Treant sprießt ein junger Trieb. Er lässt ihn wachsen und erzählt ihm von allen, die er liebte."],
	"celestial_fox": ["mystic_grove", "shira", "seraph", "Der Himmelsfuchs",
		"Der Himmelsfuchs hat neun Schwänze – für jedes Jahrhundert einen. Jeder trägt eine Lüge, die er einst erzählte.",
		"Er weiß nicht mehr, welche Geschichte über ihn die wahre ist.",
		"Ich bin der Fuchs zwischen den Sternen. Fang mich – wenn du kannst.",
		"Neun Schwänze, neun Lügen. Welche erzählst du mir heute, Fuchs?",
		"Der Seraph will die Wahrheit hören – nur eine, nur einmal.",
		"Du bist nur die Summe deiner Tricks.",
		"Der Fuchs erzählt eine einzige wahre Geschichte. Ein neunter Schwanz fällt ab – und wird zu einem Stern."],
	"mossback": ["mystic_grove", "treant", "baphomet", "Die Steinbestie",
		"Mossback war ein Fels, auf dem Moos wuchs, auf dem Tiere schliefen. Irgendwann stand der Fels auf.",
		"Er trägt einen ganzen Wald auf dem Rücken und weiß nicht, ob er ihn je absetzen darf.",
		"Ich bin der Berg, der sich bewegt.",
		"Du trägst meinen Wald, Steinbeißer. Gib ihn zurück.",
		"Baphomet bietet ihm an, die Last abzuwerfen – und mit ihr alles, was auf ihm lebt.",
		"Du bist nur ein Lasttier mit Moos.",
		"Mossback legt sich an einen Fluss. Der Wald auf seinem Rücken blüht. Er muss ihn nicht tragen. Er darf."],
	"steel_knight": ["imperial_colosseum", "valkyrie", "principatus", "Der rote Mönch",
		"Cardinal legte die Rüstung nie ab, seit er im Krieg ein Kloster nicht schützen konnte.",
		"Er betet mit dem Schwert, weil er sein Gebet nicht mehr hört.",
		"Schild hoch. Gebet gesprochen. Kein Schritt zurück.",
		"Du betest, Mönch? Zu wem? Dein Kloster ist Asche.",
		"Principatus fragt: Schützt du die Schwachen – oder schützt du dich vor ihnen?",
		"In deiner Rüstung ist niemand mehr.",
		"Cardinal nimmt den Helm ab. Darunter: ein müder alter Mann. Die Kinder des neuen Klosters bringen ihm Tee."],
	"vanguard_soldier": ["neon_metropolis", "swat_specops", "potestas", "Die letzte Vorhut",
		"Vanguard war die Spitze einer Armee, die nie ankam. Er hält die Stellung seit sieben Jahren.",
		"Niemand hat ihm gesagt, dass der Krieg vorbei ist.",
		"Vorhut meldet: Stellung gehalten. Warte auf Befehle.",
		"Der Krieg ist aus, Soldat. Du bist ein Gespenst in Rüstung.",
		"Potestas befiehlt ihm, ewig weiterzukämpfen – denn ein Soldat ohne Feind ist nichts.",
		"Ohne Befehl weißt du nicht, wer du bist.",
		"Vanguard legt die Photonenkanone ab und hört zum ersten Mal Vögel statt Funkrauschen."],
	"sorceress_medea": ["blood_moon", "amethya", "lilith", "Die Erzmagierin",
		"Medea lernte jeden Zauber der Welt – bis auf den einen, der einen Menschen zurückbringt.",
		"Sie sammelt Macht, um eine Leere zu füllen, die keine Magie füllt.",
		"Die Sterne gehorchen mir. Nur einer nicht.",
		"Du kannst alles, Medea – außer loslassen.",
		"Lilith verspricht den verbotenen Zauber – zum Preis ihres eigenen Spiegelbilds.",
		"Ohne Macht bist du nur eine Frau, die jemanden vermisst.",
		"Medea zaubert nicht mehr. Sie zündet eine Kerze an, einfach so, und erzählt der Flamme eine Geschichte."],
	"skeleton_reaper": ["blood_moon", "nyx", "ahriman", "Der Häuter",
		"Flayer war einst ein Henker. Als er starb, wollte ihn niemand – weder Himmel noch Hölle.",
		"Er sucht einen Ort, an den er gehört.",
		"Knochen… erinnern sich… an alles.",
		"Du bist Abfall, Flayer. Selbst die Hölle hat dich zurückgeschickt.",
		"Ahriman bietet ihm endlich ein Zuhause – in der ewigen Finsternis.",
		"Du gehörst nirgendwohin. Das ist deine Strafe.",
		"Flayer bewacht jetzt einen alten Friedhof. Die Raben kennen ihn. Es ist ein Zuhause."],
	"mutant_titan": ["volcano_sanctum", "warrok_brute", "beelzebub", "Der Koloss aus dem Labor",
		"Der Mutant war Laborassistent, bis ein Experiment schiefging. Jetzt ist er drei Meter groß und giftgrün.",
		"Er wollte immer nur, dass jemand stolz auf ihn ist.",
		"Ich bin kein Monster. Ich bin ein Missgeschick mit Muskeln!",
		"Groß und dumm, Mutant. Genau wie ich. Lass uns sehen, wer dümmer ist.",
		"Beelzebub will ihn in eine Armee aus Mutanten verwandeln, die nie wieder ein Mensch anschaut.",
		"Niemand wird je stolz auf dich sein.",
		"Der alte Professor, der ihn erschuf, schüttelt ihm die riesige Hand. »Mein bestes Ergebnis«, sagt er."],
	"swat_specops": ["neon_metropolis", "vanguard_soldier", "virtus", "Der Agent im Einsatz",
		"Der SWAT-Agent hat in zwanzig Jahren keinen Einsatz verloren und keinen einzigen Urlaubstag genommen.",
		"Er weiß nicht, wer er ohne Funkgerät ist.",
		"Zugriff. Jetzt.",
		"Du bist ein Werkzeug der Stadt, Agent. Sie wirft dich weg, wenn du rostest.",
		"Virtus fragt ihn, wen er eigentlich beschützt, wenn er nie zu Hause ist.",
		"Ohne Einsatz bist du gar nichts.",
		"Der Agent schaltet das Funkgerät aus und fährt ans Meer. Seine Tochter wartet schon am Strand."],
	"samurai_dreyar": ["gladiator_fortress", "jubei", "michael", "Der Silberwolf",
		"Der Kommandant führte hundert Schwerter und verlor neunundneunzig in einer einzigen Nacht.",
		"Er kämpft, um den einen zu ehren, der überlebte – sich selbst kann er nicht verzeihen.",
		"Ein Wolf führt das Rudel. Auch wenn es nur noch aus Schatten besteht.",
		"Hundert Schwerter, Kommandant? Ich sehe nur eins, und das zittert.",
		"Michael fordert seine Kapitulation – vor sich selbst.",
		"Neunundneunzig starben, weil du zu stolz warst, zu fliehen.",
		"Der Kommandant pflanzt neunundneunzig Kirschbäume. Im Frühling blühen sie alle auf einmal."],
	"pirate_captain": ["pirate_galleon", "tobi", "leviathan", "Kapitänin der Salzkrähe",
		"Seraphine eroberte die Salzkrähe mit einem Messer und einem Lied. Seitdem gehört ihr das Meer.",
		"Sie hat nie gelernt, an Land zu leben.",
		"Klar Schiff! Wer an Bord kommt, tanzt nach meinem Lied!",
		"Du hast meine Leute nicht gerettet, Piratin. Du hast nur zugesehen.",
		"Leviathan erhebt sich aus der Tiefe und verlangt das Lied zurück, mit dem sie das Meer bezwang.",
		"Ohne Schiff bist du nur eine Frau mit nassen Stiefeln.",
		"Seraphine geht an Land, zum ersten Mal seit zwanzig Jahren. Der Sand ist warm. Sie singt trotzdem."],
	"vampire_lord": ["blood_moon", "specter", "lilith", "Der Vampirfürst",
		"Vlad lebt seit sechshundert Jahren und hat jeden überlebt, den er je geliebt hat.",
		"Unsterblichkeit ist für ihn ein Fluch, den er niemandem gönnt – und doch jeden verführt.",
		"Die Nacht ist jung. Ich bin es nicht.",
		"Sechshundert Jahre, Vlad – und du hast immer noch Angst vor dem Morgen.",
		"Lilith, seine Schöpferin, ruft ihn zurück an ihre Seite – für weitere sechshundert Jahre.",
		"Du bist kein Fürst. Du bist ein Gefangener in Samt.",
		"Vlad sieht einen Sonnenaufgang – durch ein Fenster aus buntem Glas. Er bleibt bis zum letzten Strahl."],
	"wizard_sorcerer": ["volcano_sanctum", "phoenix", "hell_flames_boss", "Der Feuermagier",
		"Pyrus lernte Feuer, weil ihm als Kind immer kalt war. Er hat seitdem nie wieder gefroren.",
		"Er verbrennt seine Bücher, wenn er sie gelesen hat – damit niemand ihn je übertrifft.",
		"Ein Meteor ist nur eine Idee, die schnell genug fällt.",
		"Du hast unsere Bibliothek verbrannt, Pyrus. Die Hälfte meiner Erinnerungen war darin.",
		"Der Flammenkreis der Hölle bietet ihm Feuer, das nie verlischt – und nie wärmt.",
		"Du verbrennst Wissen, weil du Angst hast, geteilt zu werden.",
		"Pyrus schreibt ein Buch über Feuer und schenkt es einer Schule. Er unterschreibt mit »für die Frierenden«."],
	"warrok_brute": ["gladiator_fortress", "bruno", "bel_marduk", "Der urzeitliche Berserker",
		"Warrok erwachte in einer Höhle unter der Arena, älter als jede Sprache. Er kennt nur ein Wort: MEHR.",
		"Er weiß nicht, ob er für etwas kämpft – oder nur, weil er nicht aufhören kann.",
		"RAAAH! MEHR!",
		"Du bist laut, Warrok. Aber bist du auch stark genug, um still zu sein?",
		"Bel Marduk, der Zorn, nennt ihn Bruder – und bietet ihm einen Krieg, der niemals endet.",
		"Ohne Krieg bist du nur ein Tier in einer Höhle.",
		"Warrok lernt ein zweites Wort. Es lautet »Danke«. Er sagt es zu einem kleinen Vogel."],
	"nekra": ["blood_moon", "skeleton_reaper", "ahriman", "Die Seelenhirtin",
		"Nekra hütet einen Garten aus Knochen, in dem die Seelen vergessener Tiere ruhen.",
		"Sie spricht mit den Toten, weil die Lebenden sie nie zurückgegrüßt haben.",
		"Ruhig, meine Kleinen. Die Hirtin ist da.",
		"Knochen sammeln, Nekra? Ich mache aus ihnen Werkzeuge. Du machst daraus Freunde.",
		"Ahriman bietet ihr eine Herde ohne Ende – alle Seelen der Welt, für immer stumm.",
		"Die Lebenden fürchten dich. Und sie haben recht.",
		"Ein lebendiger Hund folgt Nekra nach Hause. Sie nennt ihn »Morgen«. Er bleibt."],
	"grimbolt": ["gladiator_fortress", "arber", "mammon", "Der Goblin-Tüftler",
		"Grimbolt baut Bomben, Uhren und Bombenuhren. Seine Werkstatt ist explodiert – sieben Mal.",
		"Er baut zerstörerische Dinge, weil niemand je seine nützlichen kaufen wollte.",
		"Tick, tack, BUMM! Hehe!",
		"Grimbolt, du baust Bomben. Ich baue Häuser. Willst du nicht einmal etwas bauen, das stehen bleibt?",
		"Mammon kauft ihm alle Bomben ab – zum Preis jeder Erfindung, die er noch machen wird.",
		"Du wirst nie etwas erschaffen, das bleibt.",
		"Grimbolt und Arbër bauen zusammen eine Uhr für den Marktplatz. Sie tickt. Sie explodiert nicht. Fast schade."],
	"echo": ["neon_metropolis", "ninja", "ophan", "Das Hologramm",
		"Echo ist das Hologramm einer Sängerin, die längst nicht mehr lebt. Sie singt jeden Abend dasselbe Lied.",
		"Sie weiß nicht, ob sie eine Erinnerung ist – oder jemand Neues.",
		"Phasentausch! Wo bin ich jetzt? Hier? Oder da?",
		"Du bist nur ein Abbild, Echo. Ich bin auch eins – aber ich weiß es wenigstens.",
		"Der Ophan dreht seine tausend Augen auf sie: Wer singt, wenn das Licht ausgeht?",
		"Ohne Strom verschwindest du einfach.",
		"Echo singt ein neues Lied – eines, das die echte Sängerin nie kannte. Das Publikum weint."],
	"kettenwart": ["blood_moon", "vampire_lord", "lucifer", "Der Kerkermeister",
		"Der Kettenwart hütet ein Gefängnis, dessen Insassen längst Staub sind. Er schließt jede Nacht trotzdem ab.",
		"Er trägt die Schlüssel zu allen Zellen – auch zu seiner eigenen.",
		"Niemand entkommt. Nicht einmal ich.",
		"Wer bewacht den Wächter, Kettenwart? Niemand. Und genau das macht dir Angst.",
		"Luzifer bietet ihm das größte Gefängnis von allen: die ganze Hölle, mit einem Schlüssel.",
		"Du bist der einzige Gefangene hier.",
		"Der Kettenwart schließt seine eigene Zelle auf, tritt hinaus und lässt die Tür weit offen."],
	"kalyx": ["frozen_summit", "hikaru", "seraph", "Kalt und heiß",
		"Bei Kalyx' Volk wächst jedem eine Krone aus Kristall – blau für die Frostsippe, rot für die Glutsippe.",
		"Seine Krone ist vorne blau und hinten rot. Beide Sippen haben ihn verstoßen.",
		"Ich bin lieber ganz und gehöre nirgends hin – als halb und irgendwo.",
		"Mein Feuer kocht Reis. Zeig mir deine Glut, ich zeige dir meine.",
		"Seraphael will das Blau verbrennen: reine Glut, ein offenes Tor, nie wieder Zweifel.",
		"Brich die andere Hälfte ab. Es tut nur einmal weh.",
		"Am Pass steht jetzt ein drittes Tor ohne Farbe, für alle, deren Krone nicht weiß, was sie ist."],
	"vorruk": ["mystic_grove", "mutant_titan", "bel_marduk", "Der Weg nach Hause",
		"Vorruk ist mit einem Sternenschiff abgestürzt, drei Meter groß, mit Krallen wie Sicheln.",
		"Er versteht diese Welt nicht. Nur seine Hündin Zirra ist mit ihm gefallen.",
		"Vorruk baut Haus. Groß. Mit Tür für Riesen. Und Platz für Zirra.",
		"Hier gibt es kein Zuhause für Riesen. Ich zeig's dir.",
		"Bel Marduk bietet ihm das Sternenschiff zurück – für eine einzige Schlacht.",
		"Schau hoch. Nur hoch. Hier unten sind nur Fremde.",
		"Nachts schaut Vorruk noch immer in den Himmel. Aber jetzt winkt er."],
	"neris": ["cocytus", "kettenwart", "lilith", "Loslassen",
		"Neris wuchs in den Kristallhöhlen auf, wo violette Kristalle aus den Körpern der Bergleute wachsen.",
		"Ihr Bruder wurde vom Kristall verschluckt. Seitdem lässt sie nichts mehr los.",
		"Er braucht keine Kette. Er braucht Platz.",
		"Eine Kette hält nur, solange auch etwas Spiel darin ist.",
		"Lilith bietet ihr den Bruder zurück – an einer Kette, die nie wieder losgelassen wird.",
		"Fester. Noch fester. Auch wenn es ihn zerdrückt.",
		"Neris trägt nur noch ein einziges offenes Kettenglied – als Erinnerung daran, wann man loslassen muss."],
	"konrad": ["volcano_sanctum", "steel_knight", "belphegor", "Gut genug",
		"Konrad schmiedet in der Esse seiner Familie am Rand des Schwarzwalds, seit sieben Generationen.",
		"Er wirft jedes Stück zurück ins Feuer, an dem er einen Fehler findet. Er findet immer einen.",
		"Gut genug. Nein – gut. Einfach gut.",
		"Ich trage nur Perfektes, Schmied. Schlag einen Kratzer hinein, wenn du kannst.",
		"Belphegor bietet ihm ewige Ruhe: nie wieder etwas fertig machen, nie wieder einen Fehler.",
		"Ins Feuer damit. Wir dürfen nicht schlechter sein als die sieben davor.",
		"Über Konrads Tür hängt ein krummes Hufeisen, neben den sieben Hämmern seiner Ahnen."],
	"bogdan": ["frozen_summit", "warrok_brute", "baphomet", "Der Stein am Scheideweg",
		"Bogdan bewacht seit zwölf Wintern einen alten Stein an einer Weggabelung mitten in der Taiga.",
		"Er hat sich nie getraut, einen der drei Wege zu gehen.",
		"Ich bin nicht wütend. Ich hatte Angst. Und gegen Angst hilft kein Feuer.",
		"Ich habe Berge versetzt, Recke. Und du hast nur gewartet?",
		"Baphomet will seinen Zorn: all die Jahre allein im Schnee, und niemand hat ihm gedankt.",
		"Bleib. Jeder Weg kostet etwas. Nur Stehenbleiben kostet nichts.",
		"An der Kreuzung steht jetzt ein Teehaus, und auf dem Stein ein vierter Satz: Oder du trinkst erst einen Tee bei Bogdan."],
	"kaan": ["imperial_colosseum", "samurai_dreyar", "lucifer", "Ein Glas Tee",
		"Kaan ist der schnellste Säbel im großen Basar, unter der roten Fahne mit Halbmond und Stern.",
		"Er hat noch nie verloren – und noch nie verziehen, nicht einmal seinem Bruder.",
		"Stolz ist keine Rüstung. Er ist ein Käfig aus Eis.",
		"Eine Klinge ohne Zorn ist leichter als Luft, Halbmondkrieger.",
		"Luzifer bietet ihm den Stolz der ganzen Welt: Du hattest immer recht. Vergib ihm nie.",
		"Wenn du ihm verzeihst, war alles umsonst.",
		"Zwischen den zwei Läden der Brüder steht jetzt ein kleiner Tisch mit zwei Tulpengläsern Çay."],
	"amra": ["mystic_grove", "phoenix", "leviathan", "Einundzwanzig Meter",
		"Amra kommt aus einer Familie von Brückenspringern, die von der Alten Brücke in Mostar in die Neretva springen.",
		"Sie stand ein einziges Mal oben auf dem Geländer – und ist wieder hinuntergeklettert.",
		"Man springt nicht, weil man keine Angst hat. Man springt, obwohl.",
		"Ich falle nie, ich habe Flügel. Zeig mir, wie jemand fliegt, der keine hat.",
		"Leviathan flüstert ihr Neid ein: Alle springen und werden bejubelt, nur du nicht.",
		"Wir sind runtergeklettert. Das war klug.",
		"Einundzwanzig Meter, zwei Sekunden, ein Schlag ins kalte Grün – und Jubel von beiden Ufern."],
	"dusty": ["gladiator_fortress", "pirate_captain", "mammon", "Der Zaun",
		"Dusty reitet seit zwanzig Jahren von Rodeo zu Rodeo durch die Prärie unter dem Sternenbanner.",
		"Er bleibt nie länger als eine Nacht und lässt jeden Pokal im nächsten Saloon stehen.",
		"Hold your horses, Partner – diesmal reitest du ohne mich.",
		"Ich fange Leute, die weglaufen, Cowboy. Das ist mein Hobby.",
		"Mammon bietet ihm Gold für die ewige Reise: nie wieder anhalten, nie wieder bleiben.",
		"Steig auf, Partner. Wer bleibt, wird alt und langsam.",
		"Der erste Zaunpfahl ist krumm, mit einem eingeritzten Stern, und daran hängt Dustys Lasso."],
	"don_valente": ["neon_metropolis", "swat_specops", "mammon", "Der Unterweltpate",
		"Don Valente kam mit einem Koffer in die Stadt. Heute gehört ihm jede Straße – aber kein einziger Freund.",
		"Er vertraut niemandem, weil er weiß, wie leicht man jemanden kaufen kann.",
		"Ein Angebot, das du nicht ablehnen kannst.",
		"Zwanzig Jahre jage ich dich, Don. Heute endet es.",
		"Mammon ist der einzige, der ihm noch ein Geschäft anbieten kann – und er verlangt seine Seele als Anzahlung.",
		"Du kaufst Menschen, weil du nicht weißt, wie man sie gewinnt.",
		"Don Valente schließt den Koffer und gibt ihn einem Waisenhaus. Zum ersten Mal ist seine Hand leer – und frei."],
}

## Boss ids above that are not real bosses fall back to these.
const BOSS_FALLBACK := {"hell_gate_boss": "ahriman", "hell_flames_boss": "baphomet", "cocytus_boss": "lucifer", "cerberus_alias": "asmodeus"}

static func has_legend(fam: String) -> bool:
	return LEGENDS.has(fam)

## Hand-written legend of a fighter (scripts/legends/legend_<id>.gd), or null: then the short
## generic legend built from LEGENDS is used.
static func individual(fam: String):
	var path := "res://scripts/legends/legend_%s.gd" % fam
	return load(path) if ResourceLoader.exists(path) else null

static func info(fam: String) -> Dictionary:
	var ind = individual(fam)
	if ind != null: return ind.INFO
	var L: Array = LEGENDS[fam]
	return {"epithet": L[3], "summary": L[4], "relic": "Erbe von " + cast_name(fam)}

static func boss_of(fam: String) -> String:
	var b: String = LEGENDS[fam][2]
	return BOSS_FALLBACK.get(b, b)

## Stars needed for chapter k (0..3).
static func stars_needed(k: int) -> int:
	return STARS[clampi(k, 0, 3)]

static func _say(who: String, text: String) -> Dictionary:
	return {"t": "say", "who": who, "text": text}

static func _narr(text: String) -> Dictionary:
	return {"t": "narrate", "text": text}

static func _cam(shot: String, who: int = 0, time: float = 1.6, who2: int = 1) -> Dictionary:
	return {"t": "cam", "shot": shot, "who": who, "who2": who2, "time": time}

static func _stage(cast: Array) -> Dictionary:
	var c: Array = []
	for e in cast: c.append({"id": e[0], "x": e[1], "facing": e[2]})
	return {"t": "stage", "cast": c}

static func _pose(who: int, pose: String, time: float = 0.8) -> Dictionary:
	return {"t": "pose", "who": who, "pose": pose, "time": time}

static func _music(mood: String) -> Dictionary:
	return {"t": "music", "mood": mood}

## Cast of one legend: the hero, the rival, the abyss boss and the hero's shadow.
static func cast(fam: String, presets: Array) -> Dictionary:
	var ind = individual(fam)
	if ind != null:
		# "preset": roster id -> that fighter's prompt (so every story fighter is a real fighter).
		var out := {}
		for key in ind.CAST:
			var c: Dictionary = ind.CAST[key].duplicate()
			if c.has("preset"):
				for p in presets:
					if str(p.id) == str(c.preset): c["prompt"] = str(p.prompt)
			if not c.has("prompt"): c["prompt"] = ""
			out[key] = c
		return out
	var L: Array = LEGENDS[fam]
	var by_id := {}
	for p in presets: by_id[str(p.id)] = p
	var me: Dictionary = by_id.get(fam, {"name": fam.to_upper(), "prompt": fam})
	var rv: Dictionary = by_id.get(str(L[1]), by_id.get("ninja", {"name": "RIVALE", "prompt": "Crimson Schattenninja mit roten Klingen"}))
	return {
		"hero": {"name": str(me.name), "title": str(L[3]), "color": "fde68a", "prompt": str(me.prompt)},
		"rival": {"name": str(rv.name), "title": "Rivale", "color": "f87171", "prompt": str(rv.prompt)},
		"abyss": {"name": str(Bosses_name(boss_of(fam))), "title": "Der Abgrund", "color": "ff3b5c", "prompt": "", "boss": boss_of(fam)},
		"shadow": {"name": "SCHATTEN-" + str(me.name), "title": "Was du verschweigst", "color": "a855f7", "prompt": str(me.prompt)},
	}

static func Bosses_name(bid: String) -> String:
	var d: Dictionary = load("res://scripts/bosses.gd").data(bid)
	return str(d.get("name", bid.to_upper()))

## The four chapters of a legend, with short cinematics before and after every fight.
static func chapters(fam: String) -> Array:
	var ind = individual(fam)
	if ind != null: return ind.chapters()
	var L: Array = LEGENDS[fam]
	var home: String = L[0]
	var list: Array = []
	list.append({"id": fam + "_1", "title": CHAPTER_NAMES[0], "arena": home, "stars": 0, "steps": [
		_stage([["hero", -1.5, 1], ["rival", 9.0, -1]]),
		{"t": "vanish", "who": 1},
		_music("calm"),
		_cam("sky", 0, 0.01),
		{"t": "title", "text": "LEGENDE · " + str(L[3]).to_upper(), "sub": "Kapitel I – " + CHAPTER_NAMES[0]},
		_narr(L[4]),
		_cam("low", 0, 2.2),
		_pose(0, "Idle", 0.4),
		_narr(L[5]),
		_cam("close", 0, 1.4),
		_say("hero", L[6]),
		_pose(0, "Victory", 1.0),
		{"t": "fx", "kind": "flash"},
		{"t": "appear", "who": 1},
		{"t": "move", "who": 1, "x": 2.2, "time": 1.0},
		_cam("two", 0, 1.2, 1),
		_say("rival", "Ich habe von dir gehört. Mal sehen, ob die Geschichten stimmen."),
		_music("fight"),
		{"t": "fight", "cast": ["hero", "rival"], "goal": "ZEIG, WER DU BIST!", "lives": [2, 1]},
		_music("hope"),
		_cam("two", 0, 1.2, 1),
		_say("rival", "Nicht schlecht … Wir sehen uns wieder. Dann ohne Zurückhaltung."),
		{"t": "move", "who": 1, "x": 9.0, "time": 1.0},
		_cam("close", 0, 1.2),
		_narr("Die Geschichte von " + str(cast_name(fam)) + " hat gerade erst begonnen."),
	]})
	list.append({"id": fam + "_2", "title": CHAPTER_NAMES[1], "arena": home, "stars": 1, "steps": [
		_stage([["hero", -2.0, 1], ["rival", 2.0, -1]]),
		_music("tense"),
		_cam("wide", 0, 0.01),
		{"t": "title", "text": "KAPITEL II", "sub": CHAPTER_NAMES[1]},
		_cam("two", 0, 1.8, 1),
		_say("rival", L[7]),
		_cam("close", 0, 1.0),
		_pose(0, "Charge", 1.0),
		_say("hero", L[6]),
		{"t": "fx", "kind": "shake"},
		_music("fight"),
		{"t": "fight", "cast": ["hero", "rival"], "goal": "BESIEGE DEINEN RIVALEN!", "lives": [2, 2]},
		_music("calm"),
		_cam("two", 1, 1.4, 0),
		_pose(1, "HitReact", 0.6),
		_say("rival", "… Du hast dich verändert. Pass auf dich auf. Da unten wartet etwas Schlimmeres als ich."),
		_narr("Etwas regt sich unter der Arena. Etwas, das " + str(cast_name(fam)) + " schon lange kennt."),
	]})
	list.append({"id": fam + "_3", "title": CHAPTER_NAMES[2], "arena": home, "stars": 2, "steps": [
		_stage([["hero", -2.5, 1], ["abyss", 3.0, -1]]),
		{"t": "vanish", "who": 1},
		_music("tense"),
		_cam("low", 0, 0.01),
		{"t": "title", "text": "KAPITEL III", "sub": CHAPTER_NAMES[2]},
		_narr(L[8]),
		{"t": "fx", "kind": "ink", "who": 0},
		{"t": "appear", "who": 1},
		_cam("sky", 1, 2.4),
		_cam("close", 0, 1.2),
		_say("hero", "Ich weiß, was du willst. Du bekommst es nicht."),
		_music("boss"),
		{"t": "fight", "cast": ["hero", "abyss"], "goal": "BESTEHE DIE PRÜFUNG DES ABGRUNDS!", "lives": [3, 1]},
		_music("hope"),
		{"t": "fx", "kind": "flash"},
		_cam("close", 0, 1.6),
		_narr("Der Abgrund schließt sich. Aber in der Stille bleibt eine Stimme, die genauso klingt wie " + str(cast_name(fam)) + "."),
	]})
	list.append({"id": fam + "_4", "title": CHAPTER_NAMES[3], "arena": home, "stars": 3, "steps": [
		_stage([["hero", -2.0, 1], ["shadow", 2.0, -1]]),
		{"t": "vanish", "who": 1},
		_music("sad"),
		_cam("wide", 0, 0.01),
		{"t": "title", "text": "KAPITEL IV", "sub": CHAPTER_NAMES[3]},
		_cam("close", 0, 2.0),
		_narr("Am Ende jedes Weges wartet nur ein Gegner, den man nicht ausweichen kann."),
		{"t": "fx", "kind": "ink", "who": 0},
		{"t": "appear", "who": 1},
		_cam("two", 0, 1.6, 1),
		_say("shadow", L[9]),
		_pose(0, "Idle", 0.6),
		_say("hero", "Vielleicht. Aber ich bin trotzdem hier."),
		_music("boss_final"),
		{"t": "fight", "cast": ["hero", "shadow"], "goal": "STELL DICH DIR SELBST!", "lives": [2, 2]},
		# Ending cinematic.
		_music("hope"),
		{"t": "vanish", "who": 1},
		{"t": "fx", "kind": "flash"},
		_cam("low", 0, 2.4),
		_pose(0, "Victory", 1.2),
		_narr(L[10]),
		_cam("sky", 0, 3.0),
		{"t": "title", "text": "LEGENDE VOLLENDET", "sub": str(cast_name(fam)) + " · " + str(L[3])},
		_narr("Relikt erhalten: Erbe von " + str(cast_name(fam)) + "  ·  +%d Münzen  ·  Goldrahmen  ·  Legenden-Truhe" % RELIC_COINS),
	]})
	return list

static func cast_name(fam: String) -> String:
	return str(_NAMES.get(fam, fam.to_upper()))

## Display names (same as the roster cards).
const _NAMES := {"ninja": "VOLT", "golem": "MAGMOR", "valkyrie": "BOLTAR", "dragon": "TEMPLAR", "anubis": "AURUM", "specter": "RAVENNA",
	"phoenix": "SCARLET", "arber": "ARBËR", "steel_knight": "CARDINAL", "vanguard_soldier": "VANGUARD", "sorceress_medea": "MEDEA",
	"skeleton_reaper": "FLAYER", "mutant_titan": "MUTANT", "swat_specops": "DER AGENT", "samurai_dreyar": "DER KOMMANDANT",
	"pirate_captain": "SERAPHINE", "vampire_lord": "VLAD", "wizard_sorcerer": "PYRUS", "warrok_brute": "WARROK", "thorn_witch": "DIE DORNENHEXE",
	"nyx": "NYX", "shira": "SHIRA", "frostwyrm": "DER FROSTWYRM", "cyborg_mech": "DER MECH", "reaper_hound": "DER HÖLLENHUND",
	"treant": "DER TREANT", "celestial_fox": "DER HIMMELSFUCHS", "mossback": "MOSSBACK", "don_valente": "DON VALENTE",
	"kalyx": "KALYX", "vorruk": "VORRUK", "neris": "NERIS",
	"konrad": "KONRAD", "bogdan": "BOGDAN", "kaan": "KAAN", "amra": "AMRA", "dusty": "DUSTY"}
