extends RefCounted
## Legende: ORYN, DER SCHWERKRAFTPROPHET – „Die tausendste Nacht“.
## Ein Prophet, der seit tausend Nächten nicht geschlafen hat, weil er das Ende aller Welten sah.
## Eine Bäckerstochter mit Kamillentee, ein blinder Lehrer, ein Kaiser aus Nichts – und die Wahrheit,
## dass das Ende, das Oryn sah, sein eigenes Werk war. Hier erklärt sich der schwarze Stern in seiner Hand.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die tausendste Nacht",
	"summary": "Seit tausend Nächten schläft Oryn nicht mehr, denn er hat gesehen, wie alle Sterne in einen einzigen Punkt stürzen. Jetzt steht die Leere vor der Tür – und er hält diesen Punkt in der Hand.",
	"relic": "Selkas Kamillenkanne",
	"relic_text": "Eine verbeulte Blechkanne, noch warm. Wer daraus trinkt, darf heute Nacht einfach schlafen.",
}

const CAST := {
	"hero": {"preset": "oryn", "name": "ORYN", "title": "Der Schwerkraftprophet", "color": "9900ee"},
	"selka": {"preset": "lepora", "name": "SELKA", "title": "Bäckerstochter mit Sternkarte", "color": "fbbf24"},
	"quill": {"preset": "wizard_sorcerer", "name": "MEISTER QUILL", "title": "Blinder Sternkundiger", "color": "93c5fd"},
	"herold": {"preset": "specter", "name": "DER HEROLD", "title": "Stimme des Leerenkaisers", "color": "6d28d9"},
	"xylar": {"preset": "xylar", "name": "XYLAR", "title": "Der Leerenkaiser", "color": "4c1d95"},
	"dominatio": {"boss": "dominatio", "name": "DOMINATIO", "title": "Die Herrschaft", "color": "e9d5ff"},
	"wacher": {"preset": "oryn", "name": "ORYN, DER WACHENDE", "title": "Der Teil, der nie die Augen schließt", "color": "3b0764"},
}

static func chapters() -> Array:
	return [
		{"id": "oryn_1", "title": "Die tausendste Nacht", "arena": "bg_moon_temple", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["selka", 4.5, -1], ["quill", -3.6, 1], ["herold", 9.0, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "ORYN · DIE TAUSENDSTE NACHT", "sub": "Kapitel I – Die tausendste Nacht"},
			S._narr("Auf dem Sternwartenberg zählt ein Mann die Nächte, in denen er nicht geschlafen hat. Heute ist es die tausendste."),
			S._narr("Vor tausend Nächten sah Oryn das Ende: Alle Sterne fielen nach innen, in einen einzigen schwarzen Punkt. Dann wurde es still."),
			S._narr("Als er aufwachte, lag der Punkt in seiner Hand. Klein wie ein Kirschkern. Schwer wie ein Berg."),
			S._cam("close", 0, 1.6),
			S._pose(0, "Summon", 1.0),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Seitdem fällt alles zu ihm hin, wenn er es will. Steine, Regen, Licht. Die Leute im Dorf nennen es Schwerkraft. Er nennt es Last."),
			S._cam("two", 0, 1.4, 2),
			S._say("quill", "Du gehst wieder auf und ab, Junge. Ich höre es. Ich bin blind, nicht taub."),
			S._say("hero", "Vierzig Nächte noch, Meister. Dann fallen die Sterne. Ich habe es gesehen."),
			S._say("quill", "Ich habe dir beigebracht, die Sterne zu lesen. Nicht, vor ihnen Angst zu haben. Und schlafen solltest du auch mal."),
			{"t": "appear", "who": 1},
			{"t": "move", "who": 1, "x": 1.6, "time": 1.2},
			S._cam("two", 0, 1.2, 1),
			S._say("selka", "Brotlieferung! Und Kamillentee. Mama sagt, wer nicht schläft, wird durchsichtig. Du bist schon ein bisschen durchsichtig."),
			S._say("hero", "Danke, Selka. Stell es zu den anderen neunhundertneunundneunzig Kannen."),
			S._say("selka", "Hab ich gemerkt. Du trinkst nie was. Ich hab dir außerdem eine Sternkarte gemalt. Da, unten rechts – das ist die Sonne. Die fehlt auf deinen immer."),
			S._cam("close", 0, 1.2),
			S._narr("Oryn sieht auf die Karte. Er hat seit tausend Nächten keine Sonne mehr gezeichnet. Nur Sterne, die fallen."),
			{"t": "choice", "text": "Soll Oryn dem Dorf von seiner Prophezeiung erzählen?", "options": [
				{"label": "Warne das Dorf", "flag": "oryn_warned", "steps": [
					S._say("hero", "Selka. Sag deiner Mutter, sie soll das Dorf versammeln. Ich muss allen etwas sagen. Etwas Schweres."),
					S._say("selka", "Ist es so schwer wie dein Kirschkern? Dann trag ich es mit.")]},
				{"label": "Schweig und trag es allein", "flag": "oryn_silent", "steps": [
					S._say("hero", "Es ist nichts, Selka. Geh nach Hause, bevor es dunkel wird."),
					S._say("selka", "Es ist immer dunkel, wenn du das sagst. Du lügst schlecht, Oryn.")]},
			]},
			S._music("tense"),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": 3.2, "time": 1.0},
			S._cam("low", 3, 1.4),
			S._say("herold", "Prophet. Der Kaiser lässt grüßen. Er hat Hunger, und eure Welt riecht nach Abendbrot."),
			S._say("hero", "Der Kaiser … Ich habe ihn gesehen. Einen Schlund ohne Boden. Bist du der Anfang vom Ende?"),
			S._say("herold", "Ich bin nur die Vorspeise. Und du siehst aus, als würdest du gleich umfallen."),
			S._narr("Tausend Nächte ohne Schlaf. Oryns Knie zittern, bevor der erste Schlag fällt."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "herold"], "goal": "KÄMPFE GEGEN DEN HEROLD – UND DEINE MÜDIGKEIT!", "lives": [3, 2], "damage": {"0": 35}, "ai": 3},
			S._music("calm"),
			{"t": "vanish", "who": 3},
			S._cam("two", 0, 1.4, 1),
			S._narr("Der Herold zerfließt wie Tinte im Regen. Seine letzten Worte hängen noch in der Luft: »Wir SIND das Ende, Prophet.«"),
			{"t": "branch", "flag": "oryn_warned", "steps": [
				S._say("selka", "Die Leute packen schon. Ein paar lachen über dich. Die meisten nicht. Der Schmied hat gesagt, er glaubt dir."),
				S._say("hero", "Zum ersten Mal seit tausend Nächten weiß es jemand außer mir. Es ist … leichter."),
			], "else": [
				S._say("selka", "Du hast es niemandem gesagt, oder? Ich seh's an deinem Gesicht. Du guckst wie einer, der allein ein Klavier trägt."),
				S._say("hero", "Ein Klavier wäre leichter."),
			]},
			S._cam("sky", 0, 2.2),
			S._narr("Unten in der Stadt Lumenhall geht in dieser Nacht eine Straße verloren. Nicht zerstört. Einfach weg."),
		]},
		{"id": "oryn_2", "title": "Der Kaiser aus Nichts", "arena": "neon_metropolis", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["xylar", 3.0, -1], ["selka", -4.2, 1], ["quill", -5.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Kaiser aus Nichts"},
			S._narr("Lumenhall, die leuchtende Stadt am Fuß des Berges. Wo gestern ein Marktplatz war, ist heute ein Loch im Bild der Welt."),
			S._cam("two", 0, 1.4, 2),
			S._say("selka", "Hier war die Bäckerei von meiner Tante. Und jetzt ist hier … nichts. Nicht mal Staub."),
			S._say("hero", "Bleib hinter mir. Wenn ich die Hand hebe, lauf. Nicht stehen bleiben, nicht umdrehen."),
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "appear", "who": 1},
			S._cam("low", 1, 1.8),
			S._pose(1, "Roar", 1.0),
			S._say("xylar", "Prophet? Du bist nur ein Mann, der zu oft in den Abgrund geschaut hat. Und der Abgrund hat sich deine Adresse gemerkt."),
			S._say("hero", "Xylar. Ich habe dein Ende gesehen, Kaiser. Und das Ende von allem, was du frisst."),
			S._say("xylar", "Du hast gar nichts gesehen. Ich war einmal eine Welt, Prophet. Mit Flüssen. Mit Bäckereien."),
			S._say("xylar", "Dann kam einer wie du. Er hat mich zusammengedrückt, um mich zu retten. Was übrig blieb, ist dieser Hunger."),
			S._cam("close", 0, 1.2),
			S._pose(0, "Dazed", 0.8),
			S._narr("Oryn spürt, wie der schwarze Stern in seiner Hand schwerer wird. Als hätte er etwas wiedererkannt."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "SCHWARZER STERN – ZIEH IHN ZU DIR!", "flag": "oryn_pull",
				"success": [{"t": "fx", "kind": "burst", "who": 0}, S._narr("Laternen, Pflastersteine, ein verirrtes Fahrrad – alles stürzt zu Oryn hin und bildet eine Mauer vor Selka.")],
				"fail": [{"t": "fx", "kind": "shake"}, S._narr("Der Stern zieht – aber in die falsche Richtung. Oryn stolpert drei Schritte auf den Kaiser zu.")]},
			{"t": "branch", "flag": "oryn_warned", "steps": [
				S._narr("Weil Oryn sie gewarnt hat, sind die meisten schon auf dem Weg nach draußen. Er muss den Kaiser nur kurz aufhalten."),
				S._music("fight"),
				{"t": "fight", "cast": ["hero", "xylar"], "goal": "HALTE XYLAR AUF, BIS DIE STADT LEER IST!", "lives": [3, 3], "time": 60, "qte": "oryn_pull", "ai": 5},
			], "else": [
				S._narr("Niemand wurde gewarnt. In jedem Fenster brennt noch Licht. Die Stadt braucht Zeit – viel Zeit."),
				S._music("fight"),
				{"t": "fight", "cast": ["hero", "xylar"], "goal": "HALTE XYLAR AUF, BIS DIE STADT LEER IST!", "lives": [3, 3], "time": 90, "qte": "oryn_pull",
					"mods": {"1": {"power": 1.25}}, "ai": 5},
			]},
			S._music("sad"),
			S._cam("two", 0, 1.4, 1),
			S._say("xylar", "Lauf ruhig, kleine Stadt. Wir sehen uns am Ende, Prophet. Du wirst es selbst herbeiführen. Das tun Leute wie du immer."),
			{"t": "vanish", "who": 1},
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": -1.0, "time": 1.4},
			S._cam("two", 0, 1.4, 3),
			S._say("quill", "Ich bin den ganzen Berg runtergestolpert, Junge. Zwei Mal gegen einen Baum. Also erzähl mir jetzt deinen Plan."),
			S._say("hero", "Der Planetenbann. Wenn ich die Welt klein genug mache – klein genug für den schwarzen Stern –, dann kann die Leere sie nicht fressen."),
			S._say("quill", "Du willst die Welt retten, indem du sie in deine Hosentasche steckst? Das ist kein Retten. Das ist Einsperren."),
			S._say("hero", "Hast du einen besseren Plan, Meister?"),
			S._say("quill", "Ja. Schlaf eine Nacht drüber. Ein Mann, der tausend Nächte wach war, sollte keine Welten zusammenfalten."),
			S._cam("sky", 0, 2.0),
			S._narr("Oryn schläft nicht. Er steigt in derselben Nacht auf den höchsten Turm von Lumenhall und lässt sich nach oben fallen."),
		]},
		{"id": "oryn_3", "title": "Das Rad der Herrschaft", "arena": "wheel_heaven", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["dominatio", 3.0, -1], ["quill", -4.4, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das Rad der Herrschaft"},
			S._narr("Wer die Schwerkraft umdreht, fällt in den Himmel. Oryn fällt drei Tage lang. Dann landet er auf einem Rad aus Licht, das sich langsam dreht."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("dominatio", "Oryn von der Sternwarte. Du willst eine ganze Welt in deine Faust nehmen. Wer gab dir das Recht, für alle zu entscheiden?"),
			S._say("hero", "Niemand. Ich habe es gesehen. Wer das Ende sieht, muss etwas tun. Sonst ist er schuld."),
			S._say("dominatio", "Dann sieh noch einmal hin. Diesmal ganz."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._cam("close", 0, 1.6),
			S._narr("Die Vision kehrt zurück. Die Sterne fallen nach innen. In einen schwarzen Punkt. Und der Punkt liegt in einer Hand, die einen Stab hält."),
			S._narr("Es ist Oryns Hand. Das Ende, das er vor tausend Nächten sah, war nicht die Leere. Es war der Planetenbann. Es war er."),
			S._pose(0, "Defeat", 1.2),
			S._say("hero", "Nein. Nein, ich wollte sie retten. Ich wollte sie doch nur festhalten, damit nichts verloren geht."),
			S._say("dominatio", "Festhalten, bis nichts mehr atmet. Das ist Herrschaft, Prophet. Ich kenne sie gut. Ich bin sie."),
			S._say("dominatio", "Knie nieder und gib mir den Stern. Ich werde entscheiden, statt deiner. Das ist leichter, glaub mir."),
			{"t": "qte", "kind": "sequence", "keys": ["block", "jump", "special"], "time": 3.0, "text": "STEH WIEDER AUF!", "flag": "oryn_stood",
				"success": [S._pose(0, "Rise", 1.0), S._say("hero", "Nein. Wenn jemand diesen Fehler nicht macht, dann ich. Nicht du.")],
				"fail": [S._pose(0, "Dazed", 1.0), S._narr("Oryns Knie berühren das Rad. Nur eines. Das andere hält er gerade, mit allem, was er hat.")]},
			S._music("boss"),
			{"t": "branch", "flag": "oryn_warned", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.2, "time": 1.0},
				S._cam("two", 0, 1.2, 2),
				S._say("quill", "Die Leute aus dem Dorf haben mich auf den Turm geschoben. Sie sagten: Du hast uns gewarnt, jetzt warnen wir dich. Ich bin hier, Junge."),
				S._say("hero", "Meister, du bist blind! Wie hast du mich gefunden?"),
				S._say("quill", "Du bist das Schwerste im ganzen Himmel. Ich bin einfach runtergefallen. Also: nach oben."),
				{"t": "fight", "cast": ["hero", "quill", "dominatio"], "goal": "DIE HERRSCHAFT FORDERT DEN STERN – VERWEIGERE ES!", "lives": [3, 2, 1], "teams": [0, 0, 1], "qte": "oryn_stood"},
			], "else": [
				S._narr("Niemand weiß, wo Oryn ist. Niemand kommt. Er hat es so gewollt – und jetzt steht er allein auf dem Rad."),
				{"t": "fight", "cast": ["hero", "dominatio"], "goal": "DIE HERRSCHAFT FORDERT DEN STERN – VERWEIGERE ES!", "lives": [3, 1], "qte": "oryn_stood", "ai": 6},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 1},
			S._cam("two", 0, 1.4, 1),
			S._say("dominatio", "Du lässt dich nicht beherrschen, Oryn. Nicht von mir. Gut. Dann lass dich auch nicht von deiner Angst beherrschen."),
			{"t": "vanish", "who": 1},
			S._cam("close", 0, 1.6),
			S._say("hero", "Wenn ich das Ende bin … wer hält dann die Leere auf?"),
			S._narr("Unter ihm, ganz klein, färbt sich der Mond über dem Sternwartenberg rot. Die vierzigste Nacht hat begonnen."),
		]},
		{"id": "oryn_4", "title": "Der Morgen nach dem Ende", "arena": "blood_moon", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["wacher", 2.2, -1], ["selka", -3.8, 1], ["xylar", 5.0, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der Morgen nach dem Ende"},
			S._narr("Die vierzigste Nacht. Der Mond ist rot. Über dem Dorf öffnet sich der Himmel wie ein Mund."),
			S._cam("two", 0, 1.6, 2),
			S._say("selka", "Oryn! Du warst drei Tage weg! Ich hab dir jeden Tag Tee hingestellt. Jetzt hast du tausendunddrei Kannen."),
			S._say("hero", "Selka, geh ins Tal. Bitte. Ich weiß nicht, was ich gleich tue."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("wacher", "Doch, du weißt es. Drück zu. Planetenbann. Nur du kannst es. Du hast es gesehen, also musst du es tun."),
			S._say("wacher", "Du willst die Welt retten, weil du nicht weißt, wie man in ihr lebt. Also nimm sie dir. Dann musst du nie wieder darin leben."),
			S._say("hero", "Du bist der Teil von mir, der tausend Nächte Wache gehalten hat. Du bist sehr müde, oder?"),
			S._say("wacher", "Ich darf nicht müde sein. Wenn ich die Augen schließe, fällt alles."),
			{"t": "appear", "who": 3},
			{"t": "fx", "kind": "shake"},
			S._cam("low", 3, 1.4),
			S._say("xylar", "Hier sind wir, Prophet. Die zwei Enden deiner Welt. Das eine frisst sie. Das andere drückt sie zusammen. Such dir eins aus."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "wacher", "xylar"], "goal": "ZWEI ENDEN – BESIEGE BEIDE!", "lives": [3, 2, 1], "teams": [0, 1, 1], "mods": {"0": {"power": 1.15}}, "ai": 6},
			S._music("tense"),
			{"t": "vanish", "who": 1},
			S._cam("close", 0, 1.4),
			S._narr("Der Wachende ist fort. Aber der Himmel ist noch offen, und die Leere zieht. Der schwarze Stern in Oryns Hand will zudrücken. Wie immer."),
			{"t": "qte", "kind": "mash", "keys": ["special"], "count": 12, "time": 3.0, "text": "ÖFFNE DIE HAND!", "flag": "oryn_open",
				"success": [S._narr("Zum ersten Mal zieht Oryn nicht. Er stößt. Die Abstoßungswelle rollt vom Berg wie ein Atemzug, den die Welt lange angehalten hat.")],
				"fail": [S._narr("Die Hand will nicht. Dann legt Selka ihre kleine Hand darauf. Finger für Finger öffnet sie sich.")]},
			{"t": "fx", "kind": "flash"},
			S._pose(0, "Beam", 1.2),
			S._music("hope"),
			S._narr("Die Leere weicht zurück. Nicht zerstört. Nur weggedrückt, wie Wasser von einem Stein. Der Himmel schließt sich langsam."),
			S._cam("two", 0, 1.6, 3),
			S._say("xylar", "Du drückst mich weg, statt mich zu zerquetschen? Warum?"),
			S._say("hero", "Weil du einmal eine Welt warst. Hier. Nimm den Stern. In ihm ist genug Schwere für einen Anfang. Vielleicht wird wieder eine Welt aus dir."),
			S._pose(3, "Idle", 1.0),
			S._narr("Xylar hält den schwarzen Stern wie ein Kind einen Vogel. Dann ist er fort. Irgendwo dort draußen, sehr weit weg, beginnt etwas zu leuchten."),
			{"t": "vanish", "who": 3},
			S._cam("two", 0, 1.6, 2),
			S._say("selka", "Und jetzt? Ist die Prophezeiung kaputt?"),
			S._say("hero", "Ich glaube, ich habe nur das Ende gesehen, weil ich vergessen hatte, nach dem Morgen zu schauen. Hast du noch Tee?"),
			{"t": "branch", "flag": "oryn_warned", "steps": [
				S._narr("Im Morgengrauen kommt das Dorf den Berg herauf, das Oryn gewarnt hatte. Mit Decken, mit Brot – und mit tausendundvier Fragen."),
			], "else": [
				S._narr("Am Morgen erzählt Selka dem Dorf, was passiert ist. Niemand glaubt ihr. Sie lächelt trotzdem den ganzen Tag."),
			]},
			S._cam("sky", 0, 3.0),
			S._narr("Oryn trinkt eine einzige Kanne Kamillentee. Dann schläft er ein, auf zwei Mehlsäcken, mitten im Satz. Im Traum sieht er kein Ende. Nur einen Morgen."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Oryn · Die tausendste Nacht"},
			S._narr("Relikt erhalten: Selkas Kamillenkanne  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
