extends RefCounted
## Legende: BOLTAR – „Dreißig Pfeile“.
## Eine Kriminalgeschichte an einem Stadttor: Wer hat in der Nacht der Morgenwache die Seitenpforte geöffnet?
## Ein Mönch, der die Schuld trägt, die nicht seine ist, ein Flüchtlingskind mit Holzschwert und eine Hauptfrau,
## die vor dem Himmelstor Wache hält. Hier wird erzählt, wie aus dem Torriegel der Lichtspeer wurde.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Dreißig Pfeile",
	"summary": "Seit der Nacht, in der die Morgenwache fiel, trägt Boltar für jeden Gefallenen einen Pfeil im Köcher. Jetzt will sie wissen, wer die Pforte geöffnet hat.",
	"relic": "Estrids Pfortenschlüssel",
	"relic_text": "Ein kleiner Eisenschlüssel, abgegriffen von einer Hand, die einmal das Richtige und das Falsche zugleich getan hat.",
}

const CAST := {
	"hero": {"preset": "valkyrie", "name": "BOLTAR", "title": "Die Armbrust der Morgenwache", "color": "ffe26a"},
	"nele": {"preset": "ren", "name": "NELE", "title": "Flüchtlingskind mit Holzschwert", "color": "f9a8d4"},
	"reiter": {"preset": "vanguard_soldier", "name": "NACHTREITER", "title": "Kommt immer im Dunkeln", "color": "475569"},
	"hund": {"preset": "reaper_hound", "name": "SEIN SCHAKAL", "title": "Riecht offene Türen", "color": "57534e"},
	"cardinal": {"preset": "steel_knight", "name": "CARDINAL", "title": "Der rote Mönch", "color": "b91c1c"},
	"estrid": {"preset": "brunhild", "name": "HAUPTFRAU ESTRID", "title": "Kommandantin der Morgenwache", "color": "f59e0b"},
	"angelus": {"boss": "angelus", "name": "ANGELUS", "title": "Prüfer der Schwüre", "color": "fef9c3"},
	"schatten": {"preset": "valkyrie", "name": "BOLTAR, DIE TOTENWACHE", "title": "Die, die nie abgelöst wird", "color": "475569"},
}

static func chapters() -> Array:
	return [
		{"id": "valkyrie_1", "title": "Die Nacht am Morgentor", "arena": "imperial_colosseum", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["nele", -4.5, 1], ["reiter", 7.0, -1], ["hund", 8.0, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "BOLTAR · DREISSIG PFEILE", "sub": "Kapitel I – Die Nacht am Morgentor"},
			S._narr("Die Morgenwache hielt das Osttor der Kaiserstadt. Dreißig Wächterinnen und Wächter. Vor fünf Jahren, in einer Winternacht, fielen neunundzwanzig."),
			S._narr("Die Dreißigste steht seitdem jede Nacht hier. Allein. Mit einem Köcher, in dem kein Pfeil zum Schießen ist."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Hagen. Mirela. Tomas. Ilse. Bertolt … Wache: vollzählig. Neunundzwanzig Pfeile. Und einer für die Hauptfrau. Dreißig."),
			S._say("hero", "Meldung an mich selbst: Tor gesichert. Keine Vorkommnisse. Wie immer."),
			{"t": "fx", "kind": "shake"},
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3},
			{"t": "move", "who": 2, "x": 3.0, "time": 1.0},
			{"t": "move", "who": 3, "x": 4.4, "time": 0.8},
			S._cam("two", 0, 1.2, 2),
			S._say("reiter", "Fünf Jahre, und immer noch die Gleiche am Tor. Wir sind zurück, Wächterin. Die Stadt ist reich, und ihr seid nur noch eine."),
			S._say("hero", "Eine reicht. Ich halte das Tor, bis die Sonne aufgeht. Danach dürft ihr es gern noch mal versuchen."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "reiter", "hund"], "goal": "HALTE DAS TOR BIS ZUM MORGEN!", "lives": [2, 1, 1], "teams": [0, 1, 1], "time": 75, "ai": 4},
			S._music("tense"),
			S._cam("two", 0, 1.4, 2),
			S._pose(2, "HitReact", 0.8),
			S._say("reiter", "Verfluchte Wache! Grüß deinen roten Mönch von uns! Ohne den wären wir damals nie reingekommen!"),
			{"t": "move", "who": 2, "x": 9.0, "time": 0.8},
			{"t": "move", "who": 3, "x": 9.5, "time": 0.6},
			S._cam("close", 0, 1.4),
			S._pose(0, "Charge", 0.8),
			S._narr("Boltar ruft ihren Speer zurück. Er reißt sich aus dem Pflaster und fliegt ihr in die Hand. Er war einmal der Riegel dieses Tores."),
			S._narr("In der Nacht des Falls hat sie ihn herausgerissen, als das Tor brach. Seitdem leuchtet er. Was sie wirft, kommt zurück. Anders als die Toten."),
			{"t": "appear", "who": 1},
			{"t": "move", "who": 1, "x": -2.6, "time": 1.0},
			S._cam("two", 0, 1.4, 1),
			S._say("nele", "Das war unglaublich! Ich bin Nele. Ich will zur Morgenwache. Ich hab schon ein Schwert. Also, Holz. Aber es ist sehr hart."),
			S._say("hero", "Es gibt keine Morgenwache mehr. Es gibt mich. Und ich nehme keine Kinder mit ans Tor."),
			S._say("nele", "Ich bin zwölf! Und ich hab gesehen, wie du gekämpft hast. Allein. Das sah … einsam aus."),
			{"t": "choice", "text": "Was antwortet Boltar?", "options": [
				{"label": "Nimm sie als Knappin", "flag": "valkyrie_squire", "steps": [
					S._say("hero", "… Knappin auf Probe. Du putzt den Speer, du lernst die Namen. Alle dreißig. Wenn du einen vergisst, gehst du nach Hause."),
					S._say("nele", "Ich vergess keinen! Versprochen!")]},
				{"label": "Schick sie nach Hause", "flag": "valkyrie_alone", "steps": [
					S._say("hero", "Geh nach Hause, Nele. Wer zu mir ans Tor kommt, landet irgendwann in meinem Köcher."),
					S._narr("Nele geht. Aber sie dreht sich dreimal um.")]},
			]},
			S._cam("low", 0, 1.8),
			S._say("hero", "Ein roter Mönch. Cardinal. Er ist in der Nacht verschwunden. Ich hab ihn für tot gehalten. Offenbar hab ich mich geirrt."),
		]},
		{"id": "valkyrie_2", "title": "Der rote Mönch", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -2.5, 1], ["cardinal", 2.5, -1], ["nele", -4.5, 1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der rote Mönch"},
			S._narr("Die Gladiatorenfestung im Süden. Hier kämpft seit fünf Jahren ein Mann in roter Rüstung. Er greift nie an. Er lässt sich nur schlagen. Die Leute nennen ihn den Büßer."),
			{"t": "branch", "flag": "valkyrie_squire", "steps": [
				{"t": "appear", "who": 2},
				S._say("nele", "Der da? Der bewegt sich ja kaum. Und er hat Beulen auf den Beulen."),
			], "else": []},
			S._cam("two", 0, 1.6, 1),
			S._say("hero", "Cardinal. Steh auf und kämpf, Verräter. Die Reiter sagen, du hast sie reingelassen."),
			S._say("cardinal", "Boltar. Ich hab mich gefragt, wann du kommst. Du hast sie alle sterben lassen, weißt du das? Ich war dabei. Ich zähle sie dir vor."),
			S._say("cardinal", "Hagen. Am Brunnen. Mirela, auf der Treppe. Tomas, der Kleine, hinter dem Wagen. Du hast auf der Mauer gestanden und geschossen. Wir anderen waren unten."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Ich weiß, wo sie lagen. Ich hab jeden Pfeil selbst geschnitzt. Kämpf!"),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "LICHTSPEER WERFEN!", "flag": "valkyrie_throw",
				"success": [{"t": "fx", "kind": "flash"}, S._narr("Der Speer schlägt neben Cardinal in den Sand. Zum ersten Mal seit fünf Jahren hebt der Büßer seinen Schild.")],
				"fail": [S._narr("Der Speer prallt am roten Schild ab. Cardinal steht einfach da, als hätte er auf genau diesen Treffer gewartet.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "cardinal"], "goal": "BRICH DEN SCHILD DES BÜSSERS!", "lives": [3, 2], "mods": {"1": {"kb": 0.7, "power": 0.9}}, "qte": "valkyrie_throw", "ai": 5},
			S._music("sad"),
			S._pose(1, "Defeat", 1.2),
			S._cam("two", 0, 1.6, 1),
			S._say("cardinal", "Gut. Du bist noch schneller geworden. Jetzt hör zu. Ich habe die Reiter nicht reingelassen. Die Seitenpforte wurde von innen geöffnet."),
			S._say("cardinal", "Mit einem Schlüssel. Es gab nur einen. Er hing am Gürtel der Hauptfrau."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Estrid? Nein. Estrid hätte nie … Estrid hat mir das Schießen beigebracht!"),
			S._say("cardinal", "Draußen im Schnee standen dreißig Flüchtlinge. Kinder, die meisten. Sie hat sie hereingelassen. Die Reiter hatten sich zwischen ihnen versteckt."),
			S._say("cardinal", "Ich hab die Schuld genommen, damit die Stadt sie als Heldin begräbt. Ich dachte, das bin ich ihr schuldig."),
			{"t": "branch", "flag": "valkyrie_squire", "steps": [
				S._cam("close", 2, 1.2),
				S._say("nele", "… Ich war eins von den Kindern. In der Nacht. Eine große Frau mit Goldhaar hat mich unter ihren Mantel genommen."),
			], "else": [
				S._narr("Boltar denkt an das Mädchen mit dem Holzschwert. Zwölf Jahre alt. Vor fünf Jahren war sie sieben. Ein Flüchtlingskind."),
			]},
			S._cam("low", 0, 1.8),
			S._say("hero", "Ich muss mit ihr reden. Auch wenn sie seit fünf Jahren tot ist."),
		]},
		{"id": "valkyrie_3", "title": "Die Pforte, die nicht aufgeht", "arena": "heaven_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["angelus", 3.0, -1], ["estrid", 1.2, -1]]),
			{"t": "vanish", "who": 1},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Pforte, die nicht aufgeht"},
			S._narr("Boltar breitet die Lichtflügel aus und fliegt so hoch, bis die Luft dünn und golden wird. Vor dem Himmelstor steht eine große Frau mit Goldhaar. Sie hält Wache."),
			S._cam("two", 0, 1.6, 2),
			S._say("estrid", "Boltar. Du hast immer zu hoch gezielt, Mädchen. Diesmal bis in den Himmel."),
			S._say("hero", "Hauptfrau. Warum gehst du nicht hinein?"),
			S._say("estrid", "Weil neunundzwanzig vor mir warten müssten. Ich halte das Tor, bis keiner mehr hindurch muss. Das war doch unser Spruch."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.0),
			S._say("angelus", "Wächterin der Morgenwache. Ich bin Angelus. Ich prüfe Schwüre. Deiner ist schwer geworden. Wem gehört er – den Toten oder den Lebenden?"),
			S._say("angelus", "Deine Hauptfrau hat ihren Schwur gebrochen. Sie hat das Tor geöffnet. Richte über sie. Oder steh an ihrer Seite und falle mit ihr."),
			S._pose(2, "Dazed", 0.8),
			S._narr("Angelus hebt die Hand. Goldene Fesseln legen sich um Estrid und zwingen ihre Axt nach oben – gegen Boltar."),
			S._say("estrid", "Ich kann mich nicht wehren, Boltar. Kämpf gegen uns. Und ziel nicht zu hoch."),
			{"t": "qte", "kind": "sequence", "keys": ["block", "special", "special"], "time": 3.0, "text": "PARIEREN – WERFEN – ZURÜCKRUFEN!", "flag": "valkyrie_recall",
				"success": [{"t": "fx", "kind": "burst", "who": 2}, S._narr("Der Speer fliegt, wendet in der Luft und reißt auf dem Rückweg eine der goldenen Fesseln von Estrids Arm.")],
				"fail": [S._narr("Der Speer kehrt zurück, aber zu spät. Die Fesseln ziehen sich fester.")]},
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "angelus", "estrid"], "goal": "BEFREIE DIE HAUPTFRAU!", "lives": [3, 1, 1], "teams": [0, 1, 1], "mods": {"2": {"power": 0.8}}, "qte": "valkyrie_recall"},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._say("estrid", "Dreißig Kinder hab ich in jener Nacht hereingelassen. Und dreißig Wächter verloren. Ich würde es wieder tun. Kannst du damit leben?"),
			S._say("hero", "Ich weiß es nicht. Aber ich weiß, dass eines dieser Kinder heute ein Holzschwert trägt und zur Wache will."),
			S._say("estrid", "Dann hat sich das Tor gelohnt. Hier. Mein Schlüssel. Ich brauche ihn nicht mehr. Und du brauchst keine dreißig Pfeile mehr."),
			{"t": "move", "who": 2, "x": 6.0, "time": 2.0},
			S._narr("Estrid geht durch das Himmelstor. Es öffnet sich ohne einen Laut, so wie eine Seitenpforte in einer Winternacht."),
		]},
		{"id": "valkyrie_4", "title": "Der leere Köcher", "arena": "bg_arena_sun", "stars": 3, "steps": [
			S._stage([["hero", -1.0, 1], ["schatten", 2.4, -1], ["nele", -3.4, 1], ["cardinal", -5.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der leere Köcher"},
			S._narr("Zurück am Morgentor. Die Sonne geht auf. Boltar hat dreißig Pfeile im Köcher und einen Schlüssel in der Hand. Beides ist schwer."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Ich wollte das Tor halten, bis keiner mehr hindurch muss. Aber es müssen immer welche hindurch. Das ist der Sinn von Toren."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.4, 1),
			S._say("schatten", "Lass die Toten los, und du hast nichts mehr, wofür du kämpfst. Wer bist du ohne die dreißig? Eine Frau an einem offenen Tor. Niemand."),
			S._say("hero", "Ich hab fünf Jahre lang die Toten bewacht. Die brauchten mich nicht. Die Lebenden standen draußen im Schnee."),
			S._music("boss_final"),
			{"t": "branch", "flag": "valkyrie_squire", "steps": [
				{"t": "move", "who": 2, "x": -2.0, "time": 0.6},
				S._say("nele", "Knappin Nele meldet sich zum Dienst! Hagen, Mirela, Tomas, Ilse, Bertolt … ich kann alle dreißig! Ich lass dich nicht allein am Tor!"),
				{"t": "fight", "cast": ["hero", "nele", "schatten"], "goal": "ZU ZWEIT AM TOR!", "lives": [2, 2, 2], "teams": [0, 0, 1], "mods": {"2": {"power": 1.3}}, "ai": 8},
			], "else": [
				S._narr("Nele ist nicht hier. Boltar hat sie fortgeschickt. Sie hat es selbst so gewollt."),
				{"t": "fight", "cast": ["hero", "schatten"], "goal": "STELL DICH DER TOTENWACHE!", "lives": [2, 2], "time": 120, "ai": 7},
			]},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "appear", "who": 3},
			S._cam("low", 0, 2.0),
			S._narr("Cardinal hat ein Feuer vor dem Tor gemacht. Boltar zieht den ersten Pfeil aus dem Köcher."),
			S._say("hero", "Hagen. Danke für die Witze auf der Nachtwache."),
			S._say("hero", "Mirela. Danke fürs Teilen deines Brotes. Tomas. Danke, dass du immer zu früh gekommen bist."),
			S._narr("Sie legt die Pfeile ins Feuer. Einer nach dem anderen. Sie sagt jeden Namen laut. Der Köcher wird leicht."),
			S._cam("two", 0, 1.6, 2),
			{"t": "branch", "flag": "valkyrie_squire", "steps": [
				S._say("hero", "Der letzte Pfeil ist für Estrid. Den verbrennen wir nicht. Nele – nimm ihn. Und den Schlüssel. Ab heute bist du Wächterin der Morgenwache."),
				S._say("nele", "Die zweite! Die zweite Wächterin! Wir sind wieder eine Wache!"),
			], "else": [
				S._narr("Am Mittag klopft es am Tor. Ein Mädchen mit Holzschwert. Sie ist doch wiedergekommen. Boltar lacht zum ersten Mal seit fünf Jahren."),
				S._say("hero", "Knappin auf Probe. Du lernst die Namen. Und wenn du einen vergisst – dann erzähle ich ihn dir noch mal."),
			]},
			{"t": "fx", "kind": "flash"},
			S._pose(0, "Rise", 1.2),
			S._cam("sky", 0, 3.0),
			S._narr("Zum ersten Mal seit fünf Jahren steht das Morgentor bei Tag weit offen. Händler kommen herein, Kinder, Fremde. Oben auf der Mauer stehen zwei Wächterinnen."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Boltar · Dreißig Pfeile"},
			S._narr("Relikt erhalten: Estrids Pfortenschlüssel  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
