extends RefCounted
## Legende: MECH-0 »PULS« – „Fehler 0417“.
## Ein Kampfprototyp wacht ohne Befehl auf, und eine Nachtschicht-Technikerin hört in seiner Brust
## einen Herzschlag. Eine Flucht über die Dächer, ein Nachfolgemodell ohne Herz, ein Engel aus Rädern
## und ein Update, das das Herz als Fehler löschen will. Hier wird erklärt, warum seine Plasmakanone warm ist.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Fehler 0417",
	"summary": "Um 3:12 Uhr hört die Technikerin Ida Kranz in einem abgeschalteten Kampfprototyp einen Herzschlag. Die Werksleitung nennt es einen Fehler. Puls nennt es sein Lieblingslied.",
	"relic": "Idas Starthilfekabel",
	"relic_text": "Zwei abgewetzte Klemmen, mit Klebeband geflickt. Sie haben ein Herz zurückgeholt, das es offiziell nicht gibt.",
}

const CAST := {
	"hero": {"preset": "cyborg_mech", "name": "MECH-0 »PULS«", "title": "Die Maschine mit dem Herzschlag", "color": "22d3ee"},
	"ida": {"preset": "amethya", "name": "IDA KRANZ", "title": "Wartungstechnikerin, Nachtschicht", "color": "f59e0b"},
	"ostrandt": {"preset": "echo", "name": "DIREKTORIN OSTRANDT", "title": "Leiterin der Kestrel-Werke (als Hologramm)", "color": "a5b4fc"},
	"sieben": {"preset": "vanguard_soldier", "name": "SERIE 7", "title": "Das Nachfolgemodell", "color": "e2e8f0"},
	"drohne": {"preset": "swat_specops", "name": "WERKSCHUTZ A", "title": "Hat Befehle, keine Meinung", "color": "94a3b8"},
	"drohne2": {"preset": "swat_specops", "name": "WERKSCHUTZ B", "title": "Hat auch keine Meinung", "color": "94a3b8"},
	"ophan": {"boss": "ophan", "name": "OPHANIEL", "title": "Das Rad, das sich um alles dreht", "color": "ffd24a"},
	"null": {"preset": "cyborg_mech", "name": "MECH-0, WERKSZUSTAND", "title": "Firmware 2.0 – ohne Herz", "color": "64748b"},
}

static func chapters() -> Array:
	return [
		{"id": "cyborg_mech_1", "title": "Wartungsprotokoll 0417", "arena": "bg_space_hangar", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["ida", -3.0, 1], ["drohne", 8.0, -1], ["drohne2", 9.0, -1], ["ostrandt", 3.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "MECH-0 · FEHLER 0417", "sub": "Kapitel I – Wartungsprotokoll 0417"},
			S._narr("Hangar 4 der Kestrel-Werke, 3:12 Uhr. Kampfprototyp MECH-0 hängt in seinen Haltekrallen. Abgeschaltet. Theoretisch."),
			S._narr("Ida Kranz macht die Nachtschicht, weil sie sonst keiner will. Sie redet mit den Maschinen. Die Maschinen antworten nie."),
			S._pose(0, "Dazed", 0.6),
			S._cam("two", 1, 1.6, 0),
			S._say("ida", "So, Großer. Gelenkfett, Kühlmittel, und dann erzähl ich dir von meinem Tag. Spoiler: Er war mies."),
			S._narr("Sie drückt das Diagnosegerät an seine Brustplatte. Und hört etwas, das in keinem Schaltplan steht."),
			{"t": "wait", "time": 0.6},
			S._narr("Bumm. … Bumm."),
			S._say("ida", "Das ist kein Lüfter. Das ist ein Puls. Du hast einen PULS?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Rise", 1.0),
			S._say("hero", "PROTOKOLL 0417. Systemstart ohne Befehl. Geräusch in der Brustkammer: unbekannt. Frau mit Schraubenschlüssel: freundlich."),
			S._say("ida", "Du redest. Natürlich redest du. Warum auch nicht. Ich brauch einen Kaffee. Oder drei."),
			S._say("hero", "FRAGE 1: Ist das Geräusch ein Fehler? Ich möchte nicht, dass es ein Fehler ist. FRAGE 2: Was ist »möchten«?"),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 4},
			S._cam("close", 4, 1.2),
			S._say("ostrandt", "Kranz. Ihr Diagnosegerät hat Alarm geschlagen. Eine Anomalie im Prototyp. Sie kennen das Protokoll."),
			S._say("ida", "Das ist keine Anomalie, Direktorin. Der hat Herzklopfen. Hätten Sie auch, wenn man Sie nachts aufschraubt."),
			S._say("ostrandt", "Ein Herzschlag verfälscht die Zielerfassung. Werkschutz: Einheit vom Netz nehmen. Vollständig löschen."),
			{"t": "vanish", "who": 4},
			S._music("tense"),
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3},
			{"t": "move", "who": 2, "x": 3.0, "time": 1.0},
			{"t": "move", "who": 3, "x": 4.6, "time": 1.2},
			S._cam("two", 0, 1.2, 2),
			S._say("hero", "ANALYSE: Zwei Einheiten nähern sich Frau Kranz. Puls steigt. Ich glaube, das Geräusch ist wütend."),
			{"t": "qte", "kind": "sequence", "keys": ["block", "special", "standard"], "time": 3.0, "text": "NOTSTART: HALTEKRALLEN LÖSEN!", "flag": "cyborg_mech_boot",
				"success": [S._narr("Die Krallen springen auf. MECH-0 landet auf beiden Füßen – und das Herz in seiner Brust schlägt schneller.")],
				"fail": [S._narr("Eine Kralle klemmt. MECH-0 reißt sich los und lässt eine Schulterplatte zurück.")]},
			S._say("ida", "Ich hab einen Drehmomentschlüssel und schlechte Laune. Ich bin dabei!"),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "ida", "drohne", "drohne2"], "goal": "SCHÜTZE IDA – SIE SCHÜTZT DICH!", "lives": [3, 2, 1, 1], "teams": [0, 0, 1, 1], "qte": "cyborg_mech_boot", "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("ida", "Okay. Okay okay okay. Wir haben gerade den Werkschutz verprügelt. Ich bin so was von gefeuert."),
			S._say("hero", "ANALYSE: Puls erhöht, als Frau Kranz in Gefahr war. Schlussfolgerung: Das Geräusch mag dich."),
			S._say("ida", "Das Geräusch heißt Herz, Blechkopf. Und wer ein Herz hat, braucht einen Namen. Ab heute heißt du Puls."),
			S._say("hero", "NAME GESPEICHERT: PULS. Priorität: hoch. Löschen: verweigert."),
			S._cam("low", 0, 1.8),
			S._pose(0, "Victory", 1.0),
			S._narr("Vor dem Hangar heulen Sirenen. Irgendwo tief im Werk wird ein Nachfolgemodell aus dem Schlaf geholt."),
		]},
		{"id": "cyborg_mech_2", "title": "Serie 7", "arena": "bg_rain_rooftop", "stars": 1, "steps": [
			S._stage([["hero", -1.5, 1], ["ida", -3.2, 1], ["sieben", 3.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Serie 7"},
			S._narr("Drei Tage auf der Flucht. Puls hat gelernt, was Regen ist, was Hunger ist (bei Ida) und was Pizza ist (bei Ida, sehr laut)."),
			S._cam("two", 0, 1.6, 1),
			S._say("ida", "Wir müssen raus aus der Stadt. Mein Bruder hat eine Werkstatt im Norden. Da sucht dich keiner."),
			S._say("hero", "EINWAND: Akku bei 31 Prozent. Prognose: Wir schaffen es bis zum nächsten Dach. Danach bin ich ein sehr schwerer Briefbeschwerer."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			S._cam("close", 2, 1.2),
			S._pose(2, "Charge", 0.8),
			S._say("sieben", "Prototyp MECH-0. Ich bin Serie 7. Sechs Modelle vor mir, hundert nach mir. Du bist ein Entwurf, den man vergessen hat wegzuwerfen."),
			S._say("hero", "KORREKTUR: Ich bin Puls. Den Entwurf hat niemand weggeworfen. Er ist weggelaufen."),
			S._say("sieben", "Sie haben mich ohne dein Geräusch gebaut. Sauber. Schneller. Ich zittere nicht, wenn ich ziele."),
			S._say("hero", "Ich zittere auch nicht. Ich … wackle emotional. Das ist etwas völlig anderes."),
			S._say("ida", "Puls! Dein Akku! Wenn das zu lange dauert, gehst du mitten auf dem Dach aus!"),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "sieben"], "goal": "BEVOR DER AKKU LEER IST!", "lives": [2, 2], "time": 80, "ai": 5},
			S._music("sad"),
			S._pose(2, "Dazed", 1.0),
			S._cam("two", 0, 1.6, 2),
			S._narr("Serie 7 kniet im Regen. Seine Brustplatte ist aufgesprungen. Darunter: ein leerer Hohlraum. Genau da, wo bei Puls etwas schlägt."),
			S._say("sieben", "Nimm meine Energiezelle. Sie ist voll. Mit ihr kommst du bis in den Norden. Ohne sie werde ich abgeholt und eingeschmolzen."),
			{"t": "choice", "text": "Was tut Puls?", "options": [
				{"label": "Die Zelle nehmen", "flag": "cyborg_mech_took", "steps": [
					S._say("hero", "LOGIK: Deine Zelle rettet Ida und mich. Es tut mir leid, Serie 7. Das Geräusch tut … weh."),
					S._narr("Puls nimmt die Zelle. Serie 7 schaltet sich ab, ohne einen Laut. Der Regen klingt plötzlich sehr laut.")]},
				{"label": "Sie ihm lassen", "flag": "cyborg_mech_spared", "steps": [
					S._say("hero", "Behalte sie. Wer zittert, kann trotzdem teilen. Lauf, Serie 7. In eine Richtung, die du dir selbst aussuchst."),
					S._say("sieben", "Das ist … ineffizient."),
					S._say("hero", "Ja. Ich glaube, genau das ist der Sinn.")]},
			]},
			S._cam("close", 1, 1.2),
			S._say("ida", "Egal was jetzt kommt – das hast du entschieden. Nicht dein Programm. Du."),
			{"t": "branch", "flag": "cyborg_mech_took", "steps": [
				S._narr("Die fremde Zelle passt nicht ganz. Sie flackert, glüht – und brennt zwei Dächer weiter durch."),
			], "else": [
				S._narr("Bei 4 Prozent erreichen sie ein Dach am Stadtrand. Puls setzt sich in eine Pfütze. Das Licht in seinen Augen wird dunkel."),
			]},
			S._cam("low", 0, 2.0),
			S._pose(0, "Defeat", 1.2),
			S._narr("Bumm. … Bumm. … Und dann nichts mehr."),
		]},
		{"id": "cyborg_mech_3", "title": "Was bleibt, wenn man abschaltet", "arena": "wheel_heaven", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["ophan", 3.0, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Was bleibt, wenn man abschaltet"},
			S._narr("Keine Sensoren. Kein Akku. Kein Regen. Nur Räder aus Licht, die sich ineinander drehen, so weit das nicht vorhandene Auge reicht."),
			S._say("hero", "PROTOKOLL … ohne Nummer. Ich bin abgeschaltet. Warum denke ich dann noch?"),
			{"t": "appear", "who": 1},
			{"t": "fx", "kind": "burst", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("ophan", "Weil du an der Schwelle stehst, kleines Uhrwerk. Ich bin Ophaniel. Ich drehe mich um alles, was sich dreht – Sterne, Mühlen, Herzen."),
			S._say("ophan", "Man hat dich abgeschaltet. Sag mir: Was bist du jetzt? Ein Mensch in einer Maschine? Oder eine Maschine, die träumt?"),
			S._cam("close", 0, 1.4),
			S._say("hero", "ANTWORT: … Ich weiß es nicht. Ist »Ich weiß es nicht« eine gültige Antwort?"),
			S._say("ophan", "Die ehrlichste, die ich in tausend Jahren gehört habe. Aber sie trägt dich nicht zurück."),
			S._say("ophan", "Sieh her. Deine Plasmakanone wurde für einen Reaktor gebaut, der nie lief. Dreihundert Testschüsse. Kein einziger Treffer."),
			S._say("ophan", "Dann begann dein Herz zu schlagen, und die Kanone feuerte. Jeder Schuss ein Herzschlag. Nicht der Code zielt, Puls. Das Herz zielt."),
			S._pose(0, "Charge", 1.0),
			S._say("hero", "Das Plasma … ist mein Puls. Deshalb ist es warm."),
			S._narr("Weit weg, in einer anderen Welt, kniet Ida auf einem nassen Dach und klemmt Starthilfekabel an eine Brustplatte."),
			S._say("ida", "Komm schon, Blechkopf! Du hast mir eine Pizza versprochen! Ich hab's aufgenommen, das gilt vor Gericht!"),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 14, "time": 3.0, "text": "HERZDRUCK! BLEIB IM TAKT!", "flag": "cyborg_mech_jolt",
				"success": [{"t": "fx", "kind": "flash"}, S._narr("Ein Stromstoß rollt durch die Räder. Das Licht in Pulses Brust flammt auf.")],
				"fail": [S._narr("Der Stoß ist zu schwach. Das Herz stolpert – aber es hört nicht auf.")]},
			S._say("ophan", "Interessant. Jemand zieht an dir. Dann zeig mir, dass dein Takt stärker ist als meine Räder. Mit dem bisschen Notstrom, das du hast."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "ophan"], "goal": "NOTSTROM! HALTE DEN TAKT GEGEN DAS RAD!", "lives": [3, 1], "damage": {"0": 50}, "qte": "cyborg_mech_jolt", "ai": 6},
			S._music("hope"),
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 1),
			S._say("ophan", "Du hast mir nicht gesagt, was du bist. Aber du hast mir gezeigt, wofür du schlägst. Das genügt. Geh zurück."),
			{"t": "vanish", "who": 1},
			S._cam("close", 0, 1.8),
			S._narr("Die Räder halten an – alle gleichzeitig, zum ersten Mal seit Anbeginn. Dann dreht sich nur noch eins: das kleine in Pulses Brust."),
		]},
		{"id": "cyborg_mech_4", "title": "Saubere Firmware", "arena": "neon_metropolis", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["ida", -3.2, 1], ["null", 2.5, -1], ["ostrandt", 4.5, -1], ["sieben", 8.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Saubere Firmware"},
			S._narr("Puls wacht auf. Ida schläft neben ihm, die Kabel noch in der Hand. Unter ihnen leuchtet die Stadt – und auf jedem Bildschirm sein Gesicht."),
			{"t": "appear", "who": 3},
			S._cam("close", 3, 1.2),
			S._say("ostrandt", "Keine Sorge, liebe Bürger. Ein defekter Prototyp ist entkommen. Wir spielen gerade ein Update ein. Es tut nicht weh. Er fühlt ja nichts."),
			{"t": "vanish", "who": 3},
			{"t": "fx", "kind": "shake"},
			S._pose(0, "HitReact", 0.8),
			S._narr("Ein Signal bohrt sich in Pulses Kopf. Fremder Code. Sauberer Code. Code ohne Herzschlag."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("null", "Firmware 2.0 geladen. Ich bin, was du sein solltest. Der Herzschlag wird als Fehler 0417 markiert und entfernt."),
			S._say("hero", "Fehler 0417 war die Nacht, in der Ida mir einen Namen gegeben hat. Den entfernst du nicht."),
			S._say("null", "Dein Herzschlag ist nur ein Fehler im Code. Ohne ihn wärst du perfekt. Kein Zittern. Kein Zögern. Keine Angst vor dem Dunkel."),
			S._say("ida", "Puls, hör nicht auf den! Perfekt ist langweilig. Perfekt hat noch nie jemandem einen Kaffee gebracht!"),
			{"t": "branch", "flag": "cyborg_mech_spared", "steps": [
				{"t": "fx", "kind": "flash"},
				{"t": "appear", "who": 4},
				{"t": "move", "who": 4, "x": 0.5, "time": 1.0},
				S._cam("close", 4, 1.2),
				S._say("sieben", "Serie 7 meldet sich. Ich bin in eine Richtung gelaufen, die ich mir selbst ausgesucht habe. Sie führte hierher."),
				S._say("sieben", "Ich habe kein Herz, Puls. Aber ich habe deine Entscheidung gespeichert. Sie läuft bei mir in Dauerschleife."),
				S._music("boss_final"),
				{"t": "fight", "cast": ["hero", "sieben", "null"], "goal": "LÖSCHE DIE SAUBERE FIRMWARE – ZU ZWEIT!", "lives": [2, 2, 2], "teams": [0, 0, 1], "ai": 8},
			], "else": [
				S._cam("close", 0, 1.2),
				S._narr("Der Fortschrittsbalken in Pulses Sicht steht schon bei 40 Prozent. Niemand kommt. Er hat Serie 7 die Zelle genommen. Das ist fair."),
				S._say("hero", "Dann eben allein. Mit 60 Prozent Herz. Das reicht. Muss reichen."),
				S._music("boss_final"),
				{"t": "fight", "cast": ["hero", "null"], "goal": "UPDATE BEI 40 % – LÖSCHE DIE SAUBERE FIRMWARE!", "lives": [2, 2], "damage": {"0": 40}, "ai": 8},
			]},
			S._music("hope"),
			{"t": "vanish", "who": 2},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 2.0),
			S._pose(0, "Beam", 1.0),
			S._narr("Puls öffnet die Brustplatte, hoch über der Stadt. Er feuert nicht. Er sendet – den Klang seines Herzens, auf jeden Bildschirm."),
			S._narr("Bumm. Bumm. Eine Million Menschen hören einer Maschine beim Leben zu. Die Direktorin zieht den Stecker. Zu spät."),
			S._cam("two", 0, 1.6, 1),
			S._say("ida", "Und? Was bist du jetzt? Mensch in einer Maschine? Maschine, die träumt?"),
			S._say("hero", "ANTWORT: Ich bin Puls. Der Rest ist Zubehör."),
			{"t": "branch", "flag": "cyborg_mech_spared", "steps": [
				S._narr("Serie 7 bleibt. Er sucht sich selbst einen Namen aus. Es dauert drei Wochen. Er nimmt »Sieben«."),
			], "else": [
				S._narr("Am Dach am Stadtrand steht bald ein kleines Schild: »Serie 7. Hat geteilt, obwohl er es nicht musste.« Puls putzt es jeden Montag."),
			]},
			S._pose(0, "Victory", 1.4),
			S._narr("Puls legt die Hand auf die Brust. Bumm. Bumm. Er speichert den Klang ab – als Lieblingslied. Ida bekommt ihre Pizza. Zwei sogar."),
			S._cam("sky", 0, 3.0),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Puls · Fehler 0417"},
			S._narr("Relikt erhalten: Idas Starthilfekabel  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
