extends RefCounted
## Legende: RAIGA, DIE DONNERFAUST – „Wo vorne ist“.
## Ein Kompass, der nie nach Norden zeigt, sondern auf den nächsten Kampf. Ein Mädchen mit einer Laterne,
## ein Kindheitsfreund mit einem Magnetstein und ein Rad aus tausend Augen, das ihr jede Entscheidung
## abnehmen will. Hier erklärt sich das Sternsiegel – das Kartenzeichen ihrer verschollenen Mutter.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Wo vorne ist",
	"summary": "Raigas Kompass zeigt nicht nach Norden, sondern auf den nächsten Kampf. Er hat nie falsch gezeigt – bis jemand ihr erzählt, worauf er wirklich zeigt.",
	"relic": "Torus Magnetstein",
	"relic_text": "Ein kleiner grauer Stein, der einmal einen Kompass verdorben hat. Er zieht Eisen an – aber keine Richtung.",
}

const CAST := {
	"hero": {"preset": "raiga", "name": "RAIGA", "title": "Die Donnerfaust", "color": "00e5ff"},
	"bullo": {"preset": "warrok_brute", "name": "BULLO", "title": "Champion des Nachtmarkt-Rings", "color": "f97316"},
	"suzu": {"preset": "ren", "name": "SUZU", "title": "Laternenmädchen vom Nachtmarkt", "color": "fca5a5"},
	"kenta": {"preset": "tobi", "name": "KENTA", "title": "Suzus Bruder, Raigas größter Fan", "color": "fde047"},
	"toru": {"preset": "jubei", "name": "TORU", "title": "Der Kartenzeichner", "color": "a3e635"},
	"ophan": {"boss": "ophan", "name": "OPHANIEL", "title": "Das Rad, das alle Wege sieht", "color": "ffd24a"},
	"nadel": {"preset": "raiga", "name": "RAIGA, DIE NADEL", "title": "Die, die nie selbst wählt", "color": "64748b"},
}

static func chapters() -> Array:
	return [
		{"id": "raiga_1", "title": "Die Nadel zeigt auf den Ring", "arena": "bg_night_market", "stars": 0, "steps": [
			S._stage([["hero", -2.0, 1], ["bullo", 2.5, -1], ["suzu", -5.0, 1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "RAIGA · WO VORNE IST", "sub": "Kapitel I – Die Nadel zeigt auf den Ring"},
			S._narr("Raiga hat keinen Plan, keine Karte und keine Adresse. Sie hat einen Kompass. Er zeigt nicht nach Norden. Er zeigt auf den nächsten Kampf."),
			S._narr("Heute zeigt er auf den Nachtmarkt von Kasuri. Zwischen Garküchen und Papierlaternen steht ein Ring aus alten Seilen."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Sie zittert. Die Nadel zittert immer, kurz bevor es knallt. Na gut. Wer ist dran?"),
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Roar", 1.0),
			S._say("bullo", "Ich! Bullo! Neunzehn Siege in diesem Ring! Und du bist die Kleine, die nur kämpft, wo ihr Spielzeug hinzeigt?"),
			S._say("hero", "Kein Spielzeug. Er hat noch nie falsch gezeigt. Schlag zu, Bullo. Ich antworte."),
			S._narr("Raigas Stil ist einfach: Sie wartet. Sie lässt den anderen kommen. Und dann antwortet sie mit Donner."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.4, "text": "DONNERKONTER – BLOCKEN!", "flag": "raiga_counter",
				"success": [S._pose(0, "Counter", 0.6), {"t": "fx", "kind": "flash"},
					S._narr("Bullos Faust trifft nur Funken. Raigas Antwort trifft ihn am Kinn.")],
				"fail": [S._pose(0, "HitReact", 0.6),
					S._say("hero", "Au. Okay. Das war ein guter Schlag. Den merk ich mir.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "bullo"], "goal": "GEWINNE DEN NACHTMARKT-RING!", "lives": [3, 2], "qte": "raiga_counter", "ai": 3,
				"mods": {"1": {"power": 1.15, "kb": 0.9}}},
			S._music("calm"),
			S._pose(1, "Defeat", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -3.4, "time": 1.0},
			S._cam("two", 0, 1.4, 2),
			S._say("suzu", "Du bist die Donnerfaust, oder? Mein Bruder Kenta hat dein Bild über dem Bett. Er ist seit drei Tagen weg."),
			S._say("suzu", "Er hat gesagt, er geht dahin, wo du hingehst. Er will so werden wie du. Bitte. Hilf mir, ihn zu finden."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Ich … finde keine Leute. Ich finde Kämpfe. Die Nadel zeigt auf –"),
			S._narr("Die Nadel zittert. Sie zeigt nach Norden, zu den Gipfeln. Suzus Laterne zeigt in die dunklen Gassen."),
			{"t": "choice", "text": "Wohin geht Raiga?", "options": [
				{"label": "Mit Suzu durch die Gassen", "flag": "raiga_suzu", "steps": [
					S._say("hero", "Na gut. Eine Nacht. Halt die Laterne hoch, damit ich sehe, wo ich hintrete."),
					S._say("suzu", "Wirklich? Danke! Ich rede viel, wenn ich Angst hab. Ist das schlimm?"),
					S._say("hero", "Red ruhig. Dann weiß ich, dass du noch hinter mir bist.")]},
				{"label": "Der Nadel nach", "flag": "raiga_needle", "steps": [
					S._say("hero", "Tut mir leid. Die Nadel zeigt nach Norden. Sie hat noch nie falsch gezeigt."),
					S._pose(2, "Dazed", 0.8),
					S._say("suzu", "Dann hoffe ich, dass sie dich wenigstens zu ihm führt.")]},
			]},
			{"t": "branch", "flag": "raiga_suzu", "steps": [
				S._narr("Im Morgengrauen finden sie Kentas Schal an einem Karren, der nach Norden fährt. Zum ersten Mal zeigen Nadel und Laterne in dieselbe Richtung."),
			], "else": [
				{"t": "move", "who": 2, "x": -7.0, "time": 1.2},
				S._narr("Raiga geht allein. Hinter ihr verlischt eine Laterne."),
			]},
			S._cam("low", 0, 1.8),
			S._narr("Im Staub des Rings bleibt ein Abdruck zurück: ein Stern mit zwölf Strahlen. Er bleibt überall, wo Raiga zuschlägt."),
			S._narr("Ihre Mutter hat genau dieses Zeichen auf jede Karte gestempelt, die sie zeichnete. Bis sie eines Tages losging und nicht wiederkam."),
		]},
		{"id": "raiga_2", "title": "Der Kartenzeichner", "arena": "frozen_summit", "stars": 1, "steps": [
			S._stage([["hero", -2.5, 1], ["toru", 2.5, -1], ["kenta", 6.0, -1], ["suzu", -4.2, 1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Kartenzeichner"},
			S._narr("Die Nadel führt Raiga drei Tage durch den Schnee, bis zu einem Lager am Gipfel. Dort sitzt jemand am Feuer und zeichnet Karten."),
			{"t": "branch", "flag": "raiga_suzu", "steps": [
				{"t": "appear", "who": 3},
				S._say("suzu", "Meine Zehen sind Eiszapfen. Wenn Kenta da oben ist, kriegt er Ärger. Von mir. Nachdem ich ihn umarmt hab."),
			]},
			S._cam("two", 0, 1.6, 1),
			S._say("toru", "Raiga. Du trägst ihn immer noch. Den Kompass, den deine Mutter uns beiden dagelassen hat."),
			S._say("hero", "Toru. Du hast ihn mir nie gegönnt. Und jetzt zeigt er auf dich. Also kämpfen wir."),
			S._say("toru", "Er zeigt auf mich, weil ich Eisen am Gürtel trage. Nicht, weil ich ein Kampf bin."),
			S._cam("close", 0, 1.2),
			S._pose(0, "Dazed", 1.0),
			S._say("toru", "Weißt du noch, der Sommer, als wir zehn waren? Ich hab die Nadel mit einem Magnetstein bestrichen. Aus Spaß. Seitdem zeigt sie auf Eisen."),
			S._say("toru", "Schwerter, Rüstungen, Kettenhemden. Kämpfer tragen Eisen, Raiga. Dein Kompass hat nie Kämpfe gefunden. Er hat Schrott gefunden."),
			S._say("hero", "Lüg nicht. Er hat mich mein ganzes Leben geführt."),
			S._say("toru", "Eben. Dein ganzes Leben ist ein Witz, den ich mit zehn gemacht habe. Es tut mir leid. Aber irgendwer musste es dir sagen."),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": 4.0, "time": 0.9},
			S._cam("two", 0, 1.2, 2),
			S._pose(2, "Victory", 0.8),
			S._say("kenta", "Moment! DIE Raiga? Die Donnerfaust? Ich bin Kenta! Ich hab dein Bild! Ich kann den Donnerkonter! Fast!"),
			{"t": "branch", "flag": "raiga_suzu", "steps": [
				{"t": "move", "who": 3, "x": 2.8, "time": 0.8},
				S._say("suzu", "KENTA! Du Riesenidiot! Drei Tage!"),
				S._say("kenta", "Suzu?! Und … die Donnerfaust hat mich gesucht? Mich? Ich glaub, ich fall gleich um."),
			], "else": [
				S._say("kenta", "Ich bin ganz allein von Kasuri hergelaufen. Ohne jemandem Bescheid zu sagen. Genau wie du!"),
				S._say("hero", "… Genau wie ich."),
			]},
			S._cam("two", 0, 1.2, 1),
			S._say("toru", "Wenn du mir nicht glaubst, dann tu, was du immer tust. Folge der Nadel. Sie zeigt auf mich. Aber beeil dich – der Sturm kommt."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "toru"], "goal": "BESIEG TORU, BEVOR DER SCHNEESTURM KOMMT!", "lives": [2, 2], "time": 80, "ai": 5},
			S._music("sad"),
			S._pose(1, "Defeat", 1.0),
			S._cam("two", 0, 1.4, 1),
			S._say("toru", "Gut. Du hast gewonnen. Und jetzt? Wohin zeigt sie?"),
			S._narr("Raiga hebt den Kompass. Die Nadel dreht sich langsam zu Torus Gürtelschnalle. Dann zu Kentas Eisenhandschuh. Dann zu ihrem eigenen Armband."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Sie zeigt … auf mich."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Und da beginnt die Nadel zu glühen. Der Himmel über dem Gipfel öffnet sich wie ein Rad, und das Rad hat Augen."),
			{"t": "fx", "kind": "flash"},
			{"t": "vanish", "who": 0},
		]},
		{"id": "raiga_3", "title": "Das Rad mit den tausend Augen", "arena": "wheel_heaven", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["ophan", 3.0, -1], ["kenta", -5.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das Rad mit den tausend Augen"},
			S._narr("Raiga erwacht auf einem Rad aus Licht, das sich ohne Ende dreht. Jede Speiche ist ein Weg. Jeder Weg hat ein Auge."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.2),
			S._say("ophan", "Kleine Donnerfaust. Ich bin Ophaniel. Ich sehe alle Richtungen zugleich. Ich habe deine Nadel zu mir gezogen."),
			S._say("ophan", "Du hast Angst zu wählen. Ich nehme sie dir ab. Sei meine Speiche. Ich drehe dich, du schlägst zu. Für immer, ohne Zweifel."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ohne Zweifel. Klingt gut. Ehrlich. Ich hab mein Leben lang nichts anderes gewollt."),
			S._say("hero", "… Aber dann wär ich wieder nur eine Nadel. Und diesmal wüsste ich es."),
			S._say("ophan", "Dann zeige ich dir, wohin deine Mutter gegangen ist. Welchen Weg sie gewählt hat. Du musst nur Ja sagen."),
			S._pose(0, "Dazed", 1.0),
			S._narr("Für einen Herzschlag sieht Raiga eine Frau auf einer fernen Speiche, Karten unter dem Arm. Sie dreht sich nicht um."),
			S._say("hero", "Nein. Wenn ich sie finde, dann weil ich hingehe. Nicht weil du mich drehst."),
			S._music("boss"),
			{"t": "qte", "kind": "sequence", "keys": ["block", "special", "standard"], "time": 3.0, "text": "STERNSIEGEL: BLOCKEN – LADEN – SCHLAGEN!", "flag": "raiga_seal",
				"success": [{"t": "fx", "kind": "burst", "who": 0}, S._pose(0, "Slam", 0.8),
					S._narr("Raiga schlägt die Faust auf die Speiche. Ein Stern mit zwölf Strahlen brennt sich ins Licht. Das Zeichen ihrer Mutter: Hier war ich. Hier hab ich gewählt.")],
				"fail": [S._say("ophan", "Siehst du? Ohne Richtung trifft deine Faust nur Luft.")]},
			{"t": "branch", "flag": "raiga_suzu", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.2, "time": 0.8},
				S._say("kenta", "Ich bin am Licht hochgeklettert! Suzu hält unten die Laterne! Sie sagt, wir lassen dich nicht allein, weil du uns nicht allein gelassen hast!"),
				S._say("hero", "Dann bleib links von mir. Und wenn er zuschlägt – nicht ausweichen. Antworten."),
				{"t": "fight", "cast": ["hero", "kenta", "ophan"], "goal": "BRICH DAS RAD – MIT KENTA!", "lives": [3, 2, 1], "teams": [0, 0, 1], "qte": "raiga_seal"},
			], "else": [
				S._narr("Niemand kommt. Niemand weiß, wo sie ist. Das war immer der Preis dafür, nur der Nadel zu folgen."),
				{"t": "fight", "cast": ["hero", "ophan"], "goal": "BRICH DAS RAD – ALLEIN!", "lives": [2, 1], "qte": "raiga_seal", "ai": 6,
					"mods": {"1": {"power": 1.2}}},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._cam("close", 0, 1.6),
			S._narr("Das Rad bleibt stehen. Die tausend Augen schließen sich, eines nach dem anderen. Das letzte zwinkert. Fast freundlich."),
			S._say("hero", "Danke für das Angebot, Rad. Aber wenn ich im Kreis laufe, dann such ich mir den Kreis selbst aus."),
		]},
		{"id": "raiga_4", "title": "Wo vorne ist", "arena": "bg_aurora_peaks", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["nadel", 2.0, -1], ["toru", -3.6, 1], ["suzu", -6.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Wo vorne ist"},
			S._narr("Zurück auf den Gipfeln. Das Polarlicht hängt über dem Tal wie eine Karte, auf der noch nichts eingezeichnet ist."),
			S._cam("two", 0, 1.6, 2),
			S._say("toru", "Ich könnte die Nadel neu magnetisieren. Richtig diesmal. Nach Norden."),
			S._say("hero", "Dann weiß ich, wo Norden ist. Toll. Ich weiß immer noch nicht, wo ICH hinwill."),
			S._pose(0, "Crouch", 1.0),
			S._narr("Raiga legt den Kompass in den Schnee. Ohne ihn fühlt sich ihre Hand fremd an. Leer. Und aus dieser Leere steht jemand auf."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("nadel", "Heb ihn auf. Ohne den Kompass weißt du nicht mal, wo vorne ist."),
			S._say("hero", "Du bist ich. Die, die immer nur losgerannt ist, wenn irgendwas gezittert hat."),
			S._say("nadel", "Ich bin die, die nie verloren hat. Weil ich nie gewählt habe. Wer nicht wählt, wählt nie falsch."),
			S._say("hero", "Wer nicht wählt, kommt auch nie an. Komm. Schlag zuerst. Du weißt ja, wie ich antworte."),
			S._music("boss_final"),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 14, "time": 3.0, "text": "KOMPASSNOVA – AUFLADEN!", "flag": "raiga_nova",
				"success": [S._pose(0, "Charge", 0.8),
					S._narr("Zwölf Strahlen. Zwölf Richtungen. Und zum ersten Mal entscheidet Raiga selbst, in welche sie schlägt.")],
				"fail": [S._narr("Die Nova flackert. Irgendwo in ihr zittert die Nadel noch.")]},
			{"t": "fight", "cast": ["hero", "nadel"], "goal": "WÄHLE SELBST!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7, "qte": "raiga_nova"},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 1.8),
			S._pose(0, "Rise", 1.0),
			S._narr("Der Schatten zerfällt zu Schnee. Raiga hebt den Kompass auf – und wirft ihn, so weit sie kann, ins Tal."),
			S._cam("two", 0, 1.2, 2),
			S._say("toru", "Den hätte ich reparieren können!"),
			S._say("hero", "Ich weiß. Deshalb werf ich ihn ja."),
			S._narr("Dann schlägt sie die Faust in den Schnee. Ein Stern mit zwölf Strahlen. Ihr erstes eigenes Zeichen auf ihrer ersten eigenen Karte."),
			{"t": "branch", "flag": "raiga_suzu", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -2.6, "time": 1.0},
				S._say("suzu", "Kenta will, dass du zum Laternenfest kommst. Er hat ein neues Bild von dir gemalt. Diesmal lächelst du drauf."),
				S._say("hero", "Dann geh ich nach Kasuri. Nicht weil was zittert. Weil ich will."),
			], "else": [
				S._say("hero", "Da unten in Kasuri wartet ein Mädchen mit einer Laterne. Ich schulde ihr eine Nacht. Da geh ich zuerst hin."),
				S._say("toru", "Und dann?"),
				S._say("hero", "Dann such ich meine Mutter. Und jeden Weg zeichne ich selbst ein."),
			]},
			S._cam("sky", 0, 3.0),
			S._narr("Raiga geht los. Sie weiß nicht genau, wohin. Aber zum ersten Mal ist vorne da, wo sie hinschaut."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Raiga · Wo vorne ist"},
			S._narr("Relikt erhalten: Torus Magnetstein  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
