extends RefCounted
## Legende: TEMPLAR – „Die Glut in der Klinge“.
## Der Wächter von Aschfurt erschlug die alte Drachin Vulkara, und ihr Feuer fuhr in sein Schwert.
## Seitdem schützt er die Stadt mit genau der Glut, die sie einst verbrannte. Ihre Tochter Pyrax
## will das Feuer zurück, die Stadt will ihn loswerden, und der Drache in der Klinge will frei sein.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die Glut in der Klinge",
	"summary": "Templar erschlug die Drachin, die Aschfurt verbrannte – und trägt seitdem ihr Feuer im Schwert. Jetzt will ihre Tochter es zurück, und die Stadt fürchtet ihren eigenen Wächter.",
	"relic": "Der kalte Schwertknauf",
	"relic_text": "Der Knauf des Drachenschwerts, zum ersten Mal seit zwanzig Jahren kalt. Er wärmt trotzdem die Hand, die ihn hält.",
}

const CAST := {
	"hero": {"preset": "dragon", "name": "TEMPLAR", "title": "Wächter von Aschfurt", "color": "f97316"},
	"pyrax": {"preset": "pyrax", "name": "PYRAX", "title": "Tochter der Drachin", "color": "fb923c"},
	"cardinal": {"preset": "steel_knight", "name": "CARDINAL", "title": "Hauptmann der Stadtwache", "color": "cbd5e1"},
	"raider": {"preset": "warrok_brute", "name": "ASCHEPLÜNDERER", "title": "Kommt mit dem Rauch", "color": "a8a29e"},
	"baphomet": {"boss": "baphomet", "name": "BAPHOMET", "title": "Der Zerrspiegel", "color": "ff3b30"},
	"klinge": {"preset": "dragon", "name": "DER DRACHE IN DER KLINGE", "title": "Vulkaras letzte Glut", "color": "dc2626"},
}

static func chapters() -> Array:
	return [
		{"id": "dragon_1", "title": "Die Nacht der Glut", "arena": "volcano_sanctum", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["raider", 2.5, -1], ["pyrax", 9.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "TEMPLAR · DIE GLUT IN DER KLINGE", "sub": "Kapitel I – Die Nacht der Glut"},
			S._narr("Vor zwanzig Jahren kam die Drachin Vulkara über Aschfurt. Drei Tage brannte die Stadt. Am vierten stand ein junger Ritter auf ihrem Hals."),
			S._narr("Er stieß sein Schwert in ihr Herz. Ihr Feuer ging nicht aus. Es kroch die Klinge hinauf und blieb."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Zwanzig Jahre. Und jede Nacht brennt sie ein wenig heller, wenn ich die Augen schließe."),
			S._cam("two", 0, 1.4, 1),
			S._say("raider", "Der Rauch über dem Krater sagt, die Drachenbrut ist wieder wach. Gute Zeit, um eine Stadt auszuräumen."),
			S._say("hero", "Aschfurt hat einmal gebrannt. Seitdem stehe ich hier, damit es nie wieder Leute wie dich anzieht."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "KLINGE ENTFACHEN!", "flag": "dragon_kindled",
				"success": [S._narr("Die Klinge fängt Feuer. Für einen Atemzug sieht man darin ein goldenes Auge.")],
				"fail": [S._narr("Die Glut zögert, als wolle sie nicht für ihn brennen.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "raider"], "goal": "HALTE DAS STADTTOR!", "lives": [3, 2], "qte": "dragon_kindled", "ai": 3},
			S._music("tense"),
			{"t": "fx", "kind": "shake"},
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": 3.5, "time": 1.0},
			S._cam("close", 2, 1.4),
			S._pose(2, "Roar", 1.0),
			S._say("pyrax", "Du riechst nach ihr. Nach meiner Mutter. Du hast ihr Feuer gestohlen, Ritter!"),
			S._say("hero", "Ich habe eine Stadt gerettet. Das Feuer ist nur geblieben."),
			S._say("pyrax", "Dann behalte es noch ein bisschen. Ich komme es holen. Und dann brennt hier alles noch einmal."),
			{"t": "move", "who": 2, "x": 10.0, "time": 1.0},
			S._cam("low", 0, 1.6),
			S._narr("Die Klinge in seiner Hand glüht noch lange, nachdem die junge Wyvern verschwunden ist. Sie glüht, als hätte sie jemanden erkannt."),
		]},
		{"id": "dragon_2", "title": "Der Rat von Aschfurt", "arena": "imperial_colosseum", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["cardinal", 2.0, -1], ["pyrax", 9.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Rat von Aschfurt"},
			S._narr("Am Morgen ruft der Rat den Wächter in die alte Arena. Hauptmann Cardinal liest das Urteil vor. Seine Stimme ist ruhig. Seine Hand liegt am Schild."),
			S._cam("two", 0, 1.6, 1),
			S._say("cardinal", "Die Leute haben Angst, Templar. Nicht vor der Wyvern. Vor dir. Dein Schwert hat gestern eine Scheune angesteckt."),
			S._say("hero", "Mein Schwert hat gestern sechs Plünderer verjagt."),
			S._say("cardinal", "Und eine Scheune angesteckt. Der Rat bittet dich, die Klinge abzugeben. Oder die Stadt zu verlassen."),
			S._cam("close", 0, 1.4),
			S._narr("Die Klinge brummt leise. Nur er hört es: Lass sie nur. Sie haben dich nie verdient."),
			{"t": "choice", "text": "Was tut Templar?", "options": [
				{"label": "Die Klinge abgeben", "flag": "dragon_yielded", "steps": [
					S._say("hero", "Nimm sie, Cardinal. Wenn Aschfurt mich ohne Schwert nicht will, dann will es mich gar nicht."),
					S._say("cardinal", "Du überraschst mich. Aber erst prüfe ich, ob du sie mir wirklich überlässt – oder sie dich.")]},
				{"label": "Bleiben und kämpfen", "flag": "dragon_defiant", "steps": [
					S._say("hero", "Ich habe diese Stadt aus der Asche getragen. Ich gehe nicht, weil eine Scheune brennt."),
					S._say("cardinal", "Dann entscheidet die alte Sitte. Ein Duell. Verlierst du, gehst du.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "cardinal"], "goal": "BESTEHE DAS EHRENDUELL!", "lives": [2, 2], "ai": 4},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "dragon_yielded", "steps": [
				S._say("cardinal", "Du hast mit halber Kraft gekämpft. Damit die Glut nicht überspringt. Das war kein Drache. Das warst du."),
				S._say("cardinal", "Behalte die Klinge. Aber wenn sie dich je mehr hält als du sie, rufst du mich."),
			], "else": [
				S._say("cardinal", "Du hast gewonnen. Aber hast du gesehen, wie die Funken auf die Ränge flogen? Die Leute haben es gesehen."),
				S._say("hero", "Ich habe es gesehen."),
			]},
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			S._cam("close", 2, 1.2),
			S._say("pyrax", "Ritter! Der Krater öffnet sich. Etwas Großes riecht das Feuer meiner Mutter – und es ist nicht aus dieser Welt!"),
			S._narr("Unter Aschfurt reißt die Erde auf. Rote Hitze steigt aus dem Spalt, und eine Stimme lacht in vielen Tonlagen."),
		]},
		{"id": "dragon_3", "title": "Die Stadt im Zerrspiegel", "arena": "hell_flames", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["baphomet", 3.0, -1], ["pyrax", -4.0, 1], ["cardinal", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Stadt im Zerrspiegel"},
			S._narr("Templar fällt durch Rauch und Glut in den Flammenkreis. Vor ihm steht Aschfurt – unversehrt, golden, ohne einen einzigen Brandfleck."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("baphomet", "Schön, nicht wahr? So sähe deine Stadt aus, wenn du Vulkara damals nicht bekämpft hättest. Sie wollte nur ihr Ei schützen."),
			S._say("baphomet", "Du hast eine Mutter getötet, Ritter. Die Stadt brannte, weil IHR zuerst in ihren Krater gegraben habt."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Das … das hat mir niemand gesagt."),
			S._say("baphomet", "Natürlich nicht. Helden erzählt man nur die Hälfte. Gib mir die Glut, und ich mache diese Stadt wahr. Ohne Schuld."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Eine Stadt ohne Schuld ist eine Lüge. Ich trage meine. Du bekommst sie nicht."),
			S._music("boss"),
			{"t": "branch", "flag": "dragon_yielded", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("cardinal", "Du hast gerufen, Wächter. Nicht laut. Aber ich habe es gehört."),
				{"t": "fight", "cast": ["hero", "cardinal", "baphomet"], "goal": "ZERBRICH DEN ZERRSPIEGEL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("pyrax", "Ich hasse dich, Ritter. Aber ich hasse ihn mehr. Er hat mit der Stimme meiner Mutter gesprochen."),
				{"t": "fight", "cast": ["hero", "pyrax", "baphomet"], "goal": "ZERBRICH DEN ZERRSPIEGEL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Das goldene Aschfurt zerspringt wie Glas. Dahinter: die echte Stadt, schief, geflickt, voller Leute, die trotzdem dort leben."),
			S._say("hero", "Sie hat ihr Ei beschützt. Und ich meine Stadt. Wir hatten beide recht. Das ist das Schlimmste daran."),
		]},
		{"id": "dragon_4", "title": "Das Feuer zurückgeben", "arena": "volcano_sanctum", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["klinge", 2.0, -1], ["pyrax", 4.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das Feuer zurückgeben"},
			S._narr("Am Rand des Kraters, wo alles begann. Pyrax wartet. Sie greift nicht an."),
			S._cam("two", 0, 1.6, 2),
			S._say("pyrax", "Ich weiß jetzt, warum sie gekämpft hat. Und warum du gekämpft hast. Gib mir das Feuer, Ritter. Bitte."),
			S._say("hero", "Wenn ich es abgebe, bin ich nur noch ein Mann mit einem kalten Schwert."),
			S._say("pyrax", "Vielleicht ist das genug."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("klinge", "Nein. Zwanzig Jahre war ich deine Kraft. Ohne mich hätte dich Aschfurt längst vergessen. Du gehörst mir, Ritter."),
			S._say("hero", "Ich habe dich getragen, weil ich musste. Nicht, weil ich wollte."),
			S._say("klinge", "Lüg nicht. Du hast es geliebt. Die Funken. Die Angst in ihren Augen. Den Moment, in dem du größer warst als ein Mensch."),
			S._say("hero", "Ja. Darum muss ich dich loslassen."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "klinge"], "goal": "BEZWINGE DEN DRACHEN IN DER KLINGE!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._pose(0, "Cast", 1.0),
			S._narr("Templar hält die Klinge in den Krater. Die Glut fließt heraus, ein goldener Strom, und legt sich um die junge Wyvern wie ein Mantel."),
			S._say("pyrax", "Sie ist warm. Sie ist … nicht wütend. Sie war nie wütend auf dich."),
			S._say("hero", "Dann war ich es. Zwanzig Jahre lang. Auf mich."),
			S._cam("close", 0, 1.4),
			S._narr("Das Schwert ist kalt. Templar steckt es in die Scheide und merkt, dass seine Hände nicht mehr zittern."),
			S._say("pyrax", "Wenn wieder Plünderer kommen, Ritter … ruf mich. Ich habe jetzt genug Feuer für uns beide."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Templar · Die Glut in der Klinge"},
			S._narr("Relikt erhalten: Der kalte Schwertknauf  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
