extends RefCounted
## Legende: THEO, DER MUTANT – „Mein bestes Ergebnis“.
## Gestern Laborassistent mit Kaffeefleck, heute drei Meter groß und giftgrün. Zwei übergründliche
## Wachroboter, ein Schaukampf-Riese, der früher Steinmetz war, ein Mädchen, das keine Angst hat,
## und ein Geheimnis über die vertauschten Fläschchen. Hier erklärt sich Serum Z-7 – Theos Zorn.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Mein bestes Ergebnis",
	"summary": "Laborassistent Theo wacht drei Meter groß und giftgrün in einem Tank auf. Sein Professor ist verschwunden – und Theo will nur eins: dass jemand stolz auf ihn ist.",
	"relic": "Die Tasse mit dem Kaffeefleck",
	"relic_text": "Theos Lieblingstasse, aus der er jetzt mit zwei Fingern trinkt. Sie steht im Labor auf einem Ehrenplatz – mit Schild.",
}

const CAST := {
	"hero": {"preset": "mutant_titan", "name": "THEO", "title": "Der Mutant", "color": "84cc16"},
	"klee": {"preset": "wizard_sorcerer", "name": "PROFESSOR KLEE", "title": "Erfinder von Serum Z-7", "color": "e5e7eb"},
	"k9": {"preset": "cyborg_mech", "name": "WACHEINHEIT K-9", "title": "Sicherheitsroboter, sehr gründlich", "color": "94a3b8"},
	"k10": {"preset": "cyborg_mech", "name": "WACHEINHEIT K-10", "title": "Der noch gründlichere Kollege", "color": "64748b"},
	"warrok": {"preset": "warrok_brute", "name": "WARROK", "title": "Herr der Schaukämpfe", "color": "ff8b26"},
	"mina": {"preset": "lepora", "name": "MINA", "title": "Acht Jahre, keine Angst", "color": "fda4af"},
	"klee_fly": {"preset": "wizard_sorcerer", "name": "PROFESSOR KLEE", "title": "Besessen – summt seltsam", "color": "4d7c0f"},
	"beelzebub": {"boss": "beelzebub", "name": "BEELZEBUB", "title": "Herr der Fliegen", "color": "65a30d"},
	"monster": {"preset": "mutant_titan", "name": "DAS MONSTER", "title": "Was die Leute in Theo sehen", "color": "3f6212"},
}

static func chapters() -> Array:
	return [
		{"id": "mutant_titan_1", "title": "Versuch Z-7", "arena": "bg_space_hangar", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["klee", 1.4, -1], ["k9", 8.0, -1], ["k10", 9.0, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("close", 0, 0.01),
			{"t": "title", "text": "MUTANT · MEIN BESTES ERGEBNIS", "sub": "Kapitel I – Versuch Z-7"},
			S._narr("Forschungsstation Hangar 7, drei Uhr nachts. In Tank Nummer vier schwimmt etwas Großes, Grünes – und es schnarcht."),
			S._narr("Gestern war Theo Pfennig noch Laborassistent. Ein Meter achtundsechzig, Brille, Kittel mit Kaffeefleck."),
			{"t": "fx", "kind": "shake"},
			S._pose(0, "Rise", 1.0),
			S._say("hero", "Hm? Professor? Wieso ist der Tank so klein? Wieso bin ICH so … ach du grüne Neune."),
			S._narr("Er ist jetzt drei Meter groß. Giftgrün. Die Brille passt ihm noch auf den kleinen Finger."),
			S._say("hero", "Okay. Ruhig bleiben, Theo. Atmen. Du bist Wissenschaftler. Fast. Du hast den Kaffee für Wissenschaftler gekocht."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.4, 1),
			S._say("klee", "Theo, falls du diese Aufzeichnung hörst: Es tut mir leid. Der Vorstand sagt, ich hätte ein Monster gemacht. Ich … ich muss weg."),
			S._say("hero", "Professor, warten Sie! Ich bin kein Monster! Ich bin ein Missgeschick mit Muskeln!"),
			{"t": "vanish", "who": 1},
			S._narr("Das Hologramm flackert und erlischt. Dafür gehen die roten Lampen an."),
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3},
			{"t": "move", "who": 2, "x": 2.8, "time": 1.0},
			{"t": "move", "who": 3, "x": 4.2, "time": 1.2},
			S._cam("two", 0, 1.2, 2),
			S._say("k9", "BIOGEFÄHRDUNG ERKANNT. GRÖSSE: GROSS. FARBE: UNGESUND. EINLEITUNG: ENTSORGUNG."),
			S._say("k10", "ERGÄNZUNG: OBJEKT HAT KEINEN TERMIN. OBJEKT WIRD TROTZDEM ENTSORGT."),
			S._say("hero", "Ich hab euch jeden Montag abgestaubt! Ich hab euch NAMEN gegeben! Du bist Klaus! Und du bist Klaus Zwei!"),
			S._say("k10", "NAME »KLAUS ZWEI« WIRD ALS BELEIDIGUNG GESPEICHERT."),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 12, "time": 3.0, "text": "SPRENG DEN TANK!", "flag": "mutant_titan_tank",
				"success": [{"t": "fx", "kind": "burst", "who": 0}, S._narr("Panzerglas, Nährlösung und eine Gummiente – der Tank platzt, und Theo steht mitten in der Pfütze.")],
				"fail": [S._narr("Theo drückt höflich gegen die Scheibe. Die Scheibe gibt höflich nach. Es dauert nur etwas länger.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "k9", "k10"], "goal": "ENTKOMM DER STATION!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "mutant_titan_tank", "ai": 3},
			S._music("hope"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Roar", 1.0),
			S._narr("Als der letzte Roboter qualmt, merkt Theo etwas: Sein Herz schlägt wie eine Trommel, und seine Haut leuchtet. Je wütender er wird, desto größer die Fäuste."),
			S._say("hero", "Serum Z-7. »Z« wie Zorn. Der Professor hat immer gesagt, das sei nur ein Arbeitstitel."),
			S._say("hero", "Na schön. Ich finde ihn. Und dann sag ich ihm, dass ich kein Unfall bin. Ich bin ein Ergebnis. Mit Kaffeefleck."),
		]},
		{"id": "mutant_titan_2", "title": "Das Monster der Manege", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["warrok", 2.5, -1], ["mina", -4.0, 1]]),
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Das Monster der Manege"},
			S._narr("Wer drei Meter groß und grün ist, findet schwer Arbeit. Bäckerei, Bücherei, Blumenladen. Die Blumen sind verwelkt, als er gelächelt hat."),
			S._narr("Bleibt die Festung der Schaukämpfe. Hier zahlt man Riesen gut – solange sie brüllen."),
			S._cam("two", 0, 1.4, 1),
			S._say("warrok", "Groß und dumm, Mutant. Genau wie ich. Lass uns sehen, wer dümmer ist."),
			S._say("hero", "Ich habe ein angefangenes Chemiestudium! Drei Semester! Und eine Lieblingstasse!"),
			S._say("warrok", "Hör zu, Grünling. Die Leute zahlen nicht für Semester. Die zahlen für MONSTER. Du brüllst, du zerschlägst was, du tust, als würdest du den Ringrichter fressen."),
			S._say("warrok", "Ich war auch mal was anderes. Steinmetz. Jetzt bin ich Warrok der Schreckliche. Das Geld ist besser, und keiner stellt Fragen."),
			S._cam("two", 0, 1.4, 2),
			S._say("mina", "Mama sagt, das Monster frisst Kinder. Stimmt das? Du hast eine Brille am kleinen Finger."),
			S._say("hero", "Ich esse am liebsten Haferflocken. Mit Banane. Aber verrat's keinem, ich hab einen Ruf zu verlieren. Seit gestern."),
			{"t": "choice", "text": "Wie tritt Theo in der Arena auf?", "options": [
				{"label": "Spiel das Monster – die Menge will es", "flag": "mutant_titan_monster", "steps": [
					S._pose(0, "Roar", 1.0),
					{"t": "fx", "kind": "shake"},
					S._narr("Theo brüllt. Die Tribünen toben. Ganz vorne hält sich ein kleines Mädchen die Augen zu."),
					S._say("warrok", "Na also! Ein Naturtalent!")]},
				{"label": "Sei du selbst – mit Brille", "flag": "mutant_titan_self", "steps": [
					S._say("hero", "Guten Abend! Ich bin Theo, ehemals Laborassistent. Ich kämpfe heute fair und räume hinterher auf."),
					S._narr("Stille. Dann ein einzelnes Kichern. Dann lacht die ganze Arena – aber nicht gemein. Mina klatscht am lautesten.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "warrok"], "goal": "GEWINNE DIE SHOW – IN 90 SEKUNDEN!", "lives": [2, 2], "time": 90, "ai": 5, "mods": {"1": {"power": 1.15}}},
			S._music("hope"),
			{"t": "branch", "flag": "mutant_titan_monster", "steps": [
				S._cam("two", 0, 1.4, 2),
				S._say("mina", "Du hast doch gesagt, du frisst keine Kinder. Warum hast du dann so geguckt?"),
				S._say("hero", "Das … war nur Show, Mina. Nur Show."),
				{"t": "move", "who": 2, "x": -9.0, "time": 1.2},
				S._narr("Mina geht trotzdem. Und Theo merkt: Der Applaus von tausend Fremden ist leiser als ein einziges Kind, das wegläuft."),
			], "else": [
				S._cam("two", 0, 1.4, 1),
				S._say("warrok", "Du hast die Leute zum Lachen gebracht UND mich verhauen. Das hat noch keiner geschafft. Steinmetz-Ehrenwort."),
				S._say("mina", "Theo! Theo! Darf ich deine Brille halten?"),
				S._say("hero", "Nur wenn du versprichst, sie nicht zu essen."),
			]},
			S._cam("low", 0, 1.8),
			S._narr("In der Nacht summt etwas über der Festung. Ein schwarzer Schwarm in der Form eines Gesichts. Er flüstert: »Ich habe deinen Professor.«"),
		]},
		{"id": "mutant_titan_3", "title": "Der Herr der Fliegen", "arena": "hell_flames", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["klee_fly", 1.4, -1], ["beelzebub", 3.6, -1], ["klee", 1.4, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Herr der Fliegen"},
			S._narr("Der Schwarm führt Theo bis vor eine Pforte aus Flammen. Dort steht der Professor – mit leeren Augen und einem Summen in der Stimme."),
			{"t": "fx", "kind": "ink", "who": 2},
			{"t": "appear", "who": 2},
			S._cam("sky", 2, 2.4),
			S._say("beelzebub", "Ein Riese aus dem Reagenzglas! Prächtig! Dein Professor wird mir tausend von dir brauen. Eine Armee, die kein Mensch je wieder anschaut."),
			S._say("beelzebub", "Denn was niemand anschaut, gehört mir. Mutanten, Missgeschicke, Vergessene – ich sammle sie wie Fliegen faules Obst."),
			S._cam("two", 0, 1.4, 1),
			S._say("klee_fly", "Theo … es tut mir … bzzzt … Versuch Z-8 … Z-9 … Z-tausend …"),
			S._say("hero", "Raus aus seinem Kopf! Der Mann hat mir beigebracht, wie man eine Pipette hält! Falsch, aber trotzdem!"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Charge", 1.0),
			{"t": "fx", "kind": "flash"},
			S._narr("Und diesmal macht Theo es mit Absicht. Er lässt den Zorn kommen. Die Haut glüht grün, die Adern leuchten – sieben Sekunden reiner Z-7."),
			S._say("hero", "Professor, falls Sie mich hören: Das hier zählt als Feldversuch!"),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "klee_fly", "beelzebub"], "goal": "BEFREIE DEN PROFESSOR – ZERSCHLAG DEN SCHWARM!",
				"lives": [3, 1, 1], "teams": [0, 1, 1], "mods": {"1": {"power": 0.7}}, "ai": 6},
			S._music("sad"),
			{"t": "fx", "kind": "burst", "who": 2},
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 1}, {"t": "appear", "who": 3},
			S._pose(3, "Dazed", 1.0),
			S._cam("two", 0, 1.6, 3),
			S._narr("Der Schwarm zerstiebt. Der Professor sinkt auf die Knie – klein, grau, mit zitternden Händen."),
			S._say("klee", "Theo. Du hättest nicht kommen sollen. Ich habe dein Leben ruiniert. Ich habe die Fläschchen verwechselt."),
			S._say("hero", "Haben Sie nicht."),
			S._say("klee", "Wie bitte?"),
			S._say("hero", "Sie wollten Z-7 an sich selbst testen. Wegen Ihrer Hände. Wegen dem Zittern. Ich hab die Fläschchen vertauscht, bevor Sie trinken konnten."),
			S._cam("close", 3, 1.4),
			S._say("klee", "Du … warum hast du nie etwas gesagt?"),
			S._say("hero", "Weil's dumm war. Und weil ich nicht wollte, dass Sie mir was schulden. Ich wollte nur, dass Sie … na ja. Stolz sind. Irgendwann."),
			S._narr("Der Professor sagt lange nichts. Dann nimmt er die riesige grüne Hand. Er sagt immer noch nichts. Theo hält das für ein schlechtes Zeichen."),
		]},
		{"id": "mutant_titan_4", "title": "Tag der offenen Tür", "arena": "bg_sunset_stadium", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["monster", 2.0, -1], ["klee", -3.4, 1], ["mina", -4.6, 1], ["warrok", 4.6, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("hope"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Tag der offenen Tür"},
			S._narr("Eine Woche später lädt Professor Klee die ganze Stadt ins Stadion. »Tag der offenen Tür«, steht auf den Plakaten. Darunter: »Bitte nicht wegrennen.«"),
			S._cam("two", 0, 1.4, 2),
			S._say("klee", "Ich halte eine Rede, Theo. Über Z-7. Über dich. Diesmal die Wahrheit."),
			S._say("hero", "Und wenn die Leute mich trotzdem für ein Monster halten?"),
			S._narr("Die Tribünen füllen sich. Flüstern. Ausgestreckte Finger. Theos Herz schlägt schneller – und seine Haut beginnt zu leuchten."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._music("tense"),
			S._cam("two", 0, 1.6, 1),
			S._say("monster", "Niemand wird je stolz auf dich sein. Sieh sie dir an. Sie sehen ein Monster. Also SEI eins. Das ist einfacher."),
			S._say("monster", "Brüll sie an. Zerschlag die Bühne. Dann rennen sie weg, und du musst nie wieder hoffen."),
			S._say("hero", "Du bist nicht ich. Du bist nur das, wovor ich Angst hab, wenn ich in den Spiegel gucke. Mit schlechterem Haarschnitt."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.4, "text": "ATME! HALTE DEN ZORN IM ZAUM!", "flag": "mutant_titan_calm",
				"success": [S._narr("Theo atmet ein. Vier Sekunden. Atmet aus. Der Zorn ist noch da – aber jetzt gehört er ihm.")],
				"fail": [S._narr("Der Zorn schießt hoch. Theo wird noch größer. Das Monster grinst.")]},
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "monster"], "goal": "DOPPELTER ZORN – BESIEGE DAS MONSTER, NICHT DIE MENSCHEN!", "lives": [2, 3],
				"mods": {"0": {"power": 1.25}, "1": {"power": 1.25}}, "ai": 7, "qte": "mutant_titan_calm"},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 1.8),
			S._pose(0, "Idle", 0.8),
			S._narr("Das Monster zerfällt zu grünem Nebel. Im Stadion ist es mucksmäuschenstill."),
			{"t": "appear", "who": 3},
			{"t": "branch", "flag": "mutant_titan_self", "steps": [
				S._cam("two", 0, 1.4, 3),
				S._say("mina", "THEO! Ich hab meine ganze Klasse mitgebracht! Die wollen alle wissen, ob du wirklich Haferflocken isst!"),
				S._narr("Und plötzlich ist es keine Stille mehr, sondern hundert Kinderstimmen."),
			], "else": [
				S._cam("two", 0, 1.4, 3),
				S._say("mina", "Ich hatte Angst vor dir. In der Arena. Aber eben hast du das Monster weggeschickt. Das war mutig."),
				S._say("hero", "Es tut mir leid, Mina. Ich wollte nie, dass du die Augen zumachst."),
				S._narr("Mina nimmt seinen kleinen Finger. Mehr passt nicht in ihre Hand."),
			]},
			{"t": "appear", "who": 4},
			S._cam("two", 0, 1.2, 4),
			S._say("warrok", "Grünling! Ich hab meinen alten Meißel ausgegraben. Steinmetz Warrok. Klingt gar nicht so schlecht, was?"),
			S._cam("two", 0, 1.6, 2),
			S._say("klee", "Theo Pfennig. Laborassistent. Drei Semester Chemie. Und der mutigste Mensch, den ich kenne."),
			S._say("klee", "Mein bestes Ergebnis. Nein – entschuldige. Mein bester Kollege."),
			S._say("hero", "Professor … darf ich trotzdem weiter den Kaffee kochen? Ich hab mich so dran gewöhnt."),
			S._cam("sky", 0, 3.0),
			S._narr("Über dem Stadion geht die Sonne unter, grün und golden. Auf der Anzeigetafel steht: »Forschungsstation Hangar 7 – jetzt mit Besuchszeiten.«"),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Theo · Mein bestes Ergebnis"},
			S._narr("Relikt erhalten: Die Tasse mit dem Kaffeefleck  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
