extends RefCounted
## Legende: CARDINAL, DER ROTE MÖNCH – „Das Gebet aus Eisen“.
## Ein namenloser Champion des Kolosseums, der sein Preisgeld heimlich an ein Waisenhaus schickt.
## Ein Mädchen mit einer Laterne, eine Armbrustschützin mit einer anderen Erinnerung an die Nacht des
## Brandes und ein Engel, der nur eine Frage stellt. Hier erfährt man, warum sein Schild wie eine Glocke klingt.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Das Gebet aus Eisen",
	"summary": "Seit sein Kloster brannte, kämpft Cardinal namenlos im Kolosseum und nimmt nie den Helm ab. Dann folgt ihm ein Mädchen mit einer Laterne – und einem Siegel, das er kennt.",
	"relic": "Die Glockenzunge",
	"relic_text": "Der Klöppel der alten Klosterglocke. Wer ihn hält, hört ein fernes Läuten, wenn jemand Schutz braucht.",
}

const CAST := {
	"hero": {"preset": "steel_knight", "name": "CARDINAL", "title": "Der rote Mönch", "color": "dc2626"},
	"liora": {"preset": "shira", "name": "LIORA", "title": "Waise mit Laterne", "color": "fcd34d"},
	"sigrun": {"preset": "valkyrie", "name": "SIGRUN", "title": "Armbrust der Morgenwache", "color": "38bdf8"},
	"varro": {"preset": "don_valente", "name": "MEISTER VARRO", "title": "Spielgeber des Kolosseums", "color": "eab308"},
	"gorm": {"preset": "warrok_brute", "name": "GORM", "title": "Liebling der Ränge", "color": "ea580c"},
	"jaspis": {"preset": "jubei", "name": "JASPIS", "title": "Die Zwillingsklinge", "color": "a78bfa"},
	"principatus": {"boss": "principatus", "name": "PRINCIPATUS", "title": "Der Fürst, der fragt", "color": "fef3c7"},
	"leer": {"preset": "steel_knight", "name": "DIE LEERE RÜSTUNG", "title": "Niemand darin", "color": "475569"},
}

static func chapters() -> Array:
	return [
		{"id": "steel_knight_1", "title": "Zweihundertundeins", "arena": "imperial_colosseum", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["varro", -4.6, 1], ["gorm", 3.0, -1], ["jaspis", 4.6, -1], ["liora", -8.0, 1]]),
			{"t": "vanish", "who": 4},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "CARDINAL · DAS GEBET AUS EISEN", "sub": "Kapitel I – Zweihundertundeins"},
			S._narr("Im Kolosseum kennt ihn jeder und niemand. Rote Rüstung, verbeult. Ein Schild, der klingt wie eine Glocke, wenn man ihn trifft."),
			S._narr("Er hat nie seinen Namen gesagt. Die Zuschauer nennen ihn den roten Mönch, denn vor jedem Kampf kniet er. Sein Gebet hat keine Worte."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Crouch", 1.2),
			S._cam("two", 1, 1.2, 0),
			S._say("varro", "Meine Damen und Herren! Zweihundertmal ungeschlagen! Er spricht nicht, er lacht nicht, er nimmt nicht mal den Helm ab – DER ROOOTE MÖNCH!"),
			S._say("varro", "Und heute, zur Feier des Tages, gleich ZWEI Gegner! Gorm, der Liebling der Ränge! Und Jaspis, die Zwillingsklinge!"),
			S._cam("two", 0, 1.4, 2),
			S._say("gorm", "Sag mal, Mönch, wofür kämpfst du eigentlich? Du nimmst das Preisgeld und bist weg. Kein Fest, keine Taverne, nix."),
			S._pose(0, "Block", 0.8),
			S._say("hero", "Schild hoch. Gebet gesprochen. Kein Schritt zurück."),
			S._say("jaspis", "Das sagt er JEDES Mal. Ich glaube, er kann nur diesen einen Satz. Wie ein Papagei aus Blech."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "gorm", "jaspis"], "goal": "SIEG NUMMER ZWEIHUNDERTUNDEINS!", "lives": [3, 1, 1], "teams": [0, 1, 1], "ai": 4},
			S._music("calm"),
			S._cam("low", 0, 1.6),
			S._narr("Nach dem Kampf, im Gang unter den Rängen. Dort, wo sonst nur Ratten warten, wartet ein Mädchen mit einer Laterne."),
			{"t": "appear", "who": 4},
			{"t": "move", "who": 4, "x": -3.4, "time": 1.2},
			S._cam("two", 0, 1.4, 4),
			S._say("liora", "Du bist es. Du bringst das Geld ins Waisenhaus am Brunnentor. Jede Woche. Ohne Brief. Die Schwestern denken, du bist ein Geist."),
			S._say("hero", "Du irrst dich, Kind."),
			S._say("liora", "Dein Schild klingt wie eine Glocke. Ich höre ihn bis auf die Straße. Und auf deinem Geldbeutel ist dasselbe Siegel wie auf unserer Tür."),
			S._cam("close", 0, 1.4),
			S._narr("Unter dem Helm schließt ein alter Mann die Augen. Das Siegel zeigt einen Brunnen – das Zeichen eines Klosters, das es nicht mehr gibt."),
			S._say("liora", "Wir bauen das Kloster am Stillen Brunnen wieder auf. Die Schwestern, die Kinder, ich. Aber nachts kommen Räuber. Wir brauchen einen Wächter."),
			S._say("hero", "Ich habe einmal ein Kloster beschützt. Es ist Asche. Such dir einen besseren Wächter."),
			{"t": "move", "who": 0, "x": 6.0, "time": 2.0},
			S._narr("Er geht. Doch die Laterne folgt ihm bis zum Stadttor. Und am nächsten Morgen ist sie immer noch da."),
		]},
		{"id": "steel_knight_2", "title": "Die Armbrust der Morgenwache", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["liora", -3.5, 1], ["sigrun", 3.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Armbrust der Morgenwache"},
			S._narr("Die Räuber kommen aus einer alten Festung am Pass. Cardinal geht hin, um Liora zu beweisen, dass er nicht helfen kann. So sagt er es jedenfalls."),
			S._cam("two", 0, 1.4, 1),
			S._say("liora", "Du hättest nicht mitkommen müssen."),
			S._say("hero", "Du wärst allein gegangen."),
			S._say("liora", "Ja."),
			S._say("hero", "… Eben."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			S._pose(0, "Block", 0.6),
			{"t": "fx", "kind": "shake"},
			S._narr("Ein Bolzen schlägt in den Schild. Der Klang rollt durch die Festung wie das Läuten zur Abendandacht."),
			S._cam("close", 2, 1.2),
			S._say("sigrun", "Diesen Klang kenne ich. Zwölf Jahre nicht gehört. Du betest noch, Mönch? Zu wem? Dein Kloster ist Asche."),
			S._say("hero", "Sigrun. Du hast in der Nacht des Brandes deinen Posten verlassen. Ich habe das Tor allein gehalten."),
			S._say("sigrun", "Ich bin gegangen, weil DU es befohlen hast, du sturer Eisenkopf! »Bring die Kinder durch den Tunnel!« Weißt du das nicht mehr?"),
			S._cam("close", 0, 1.6),
			S._pose(0, "Dazed", 1.0),
			S._narr("Er weiß es nicht mehr. Von jener Nacht ist ihm nur das Feuer geblieben. Und dass niemand zurückkam."),
			S._say("sigrun", "Ich kam nicht zurück, weil es kein Zurück gab. Die Räuber da unten sind meine Leute. Sie hungern. Also nehme ich, was wir brauchen."),
			{"t": "choice", "text": "Wie tritt Cardinal Sigrun gegenüber?", "options": [
				{"label": "Schwert ablegen", "flag": "steel_knight_sword_down", "steps": [
					S._pose(0, "Block", 1.0),
					S._narr("Cardinal stößt das Schwert in den Boden. Nur der Schild bleibt."),
					S._say("hero", "Du hast meine Kinder gerettet. Gegen dich hebe ich keine Klinge. Nur das Tor."),
					S._say("sigrun", "Ein Mönch, der nur blockt. Das wird ein langer Nachmittag.")]},
				{"label": "Schwert ziehen", "flag": "steel_knight_sword_up", "steps": [
					S._pose(0, "Attack", 0.8),
					S._say("hero", "Wer hungrige Leute schickt, um Waisen zu bestehlen, hat seine Wache verloren. Zieh."),
					S._say("sigrun", "Da ist er ja. Der alte Eisenkopf.")]},
			]},
			S._music("fight"),
			{"t": "branch", "flag": "steel_knight_sword_down", "steps": [
				{"t": "fight", "cast": ["hero", "sigrun"], "goal": "NUR MIT DEM SCHILD – HALTE STAND!", "lives": [3, 1], "mods": {"0": {"power": 0.6}}, "ai": 4},
			], "else": [
				{"t": "fight", "cast": ["hero", "sigrun"], "goal": "BESIEGE DIE MORGENWACHE!", "lives": [2, 2], "ai": 6},
			]},
			S._music("hope"),
			S._cam("two", 0, 1.4, 2),
			{"t": "branch", "flag": "steel_knight_sword_down", "steps": [
				S._say("sigrun", "Eine Stunde. Nicht ein einziger Schlag von dir. Und ich habe dich nicht ein einziges Mal richtig getroffen."),
				S._say("sigrun", "Eins der Kinder aus dem Tunnel hat später eine Tochter bekommen. Die trägt eine Laterne. Ich glaube, ihr kennt euch."),
				S._say("liora", "Mama hat immer erzählt, ein roter Riese hätte das Tor gehalten, damit sie fliehen konnte. Ich dachte, das ist ein Märchen."),
			], "else": [
				S._say("sigrun", "Gut. Du hast gewonnen. Meine Leute ziehen ab. Aber sie hungern trotzdem, Mönch."),
				S._say("liora", "Dann sollen sie zum Brunnen kommen. Wir haben Suppe. Nicht viel, aber genug, wenn keiner stiehlt."),
				S._say("sigrun", "Eine Waise, die ihre Räuber bekocht. Wer hat ihr das denn beigebracht?"),
			]},
			S._cam("low", 0, 1.8),
			S._narr("Auf dem Heimweg sagt Cardinal kein Wort. Aber er geht langsamer, damit Liora mit ihrer Laterne Schritt halten kann."),
		]},
		{"id": "steel_knight_3", "title": "Die Frage des Fürsten", "arena": "heaven_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["liora", -3.8, 1], ["principatus", 3.0, -1], ["sigrun", -6.0, 1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Frage des Fürsten"},
			S._narr("Die Nacht der Weihe. Das neue Kloster hat ein Dach, eine Tür und zwölf Kinder. Nur keine Glocke. Die alte ist im Feuer geschmolzen."),
			S._narr("Um Mitternacht reißt der Himmel auf. Weißes Licht fällt in den Hof – so hell, dass es keine Schatten mehr gibt."),
			{"t": "fx", "kind": "flash"},
			S._music("tense"),
			{"t": "appear", "who": 2},
			S._cam("sky", 2, 2.4),
			S._say("principatus", "Rote Rüstung. Ich habe dich gesehen in jener Nacht. Du standest vor dem brennenden Tor. Und dann bist du fortgegangen."),
			S._say("principatus", "Ich frage dich, Krieger: Schützt du die Schwachen – oder schützt du dich vor ihnen? Vor ihren Augen, ihren Fragen, ihrem Dank?"),
			S._cam("close", 0, 1.2),
			S._say("hero", "Ich schütze das Tor."),
			S._say("principatus", "Das Tor ist Holz. Hinter dem Tor steht ein Kind. Wem gilt dein Gebet?"),
			S._cam("two", 0, 1.4, 1),
			S._narr("Ein Speer aus Licht löst sich aus dem Himmel. Er zielt nicht auf Cardinal. Er zielt auf Liora."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.4, "text": "SCHILD HOCH!", "flag": "steel_knight_bell",
				"success": [
					{"t": "move", "who": 0, "x": -3.0, "time": 0.3},
					S._pose(0, "Block", 0.8),
					{"t": "fx", "kind": "burst", "who": 0},
					S._narr("Der Speer trifft den Schild – und der Schild LÄUTET. Ein tiefer, voller Glockenschlag, der durch das ganze Tal rollt.")],
				"fail": [
					{"t": "move", "who": 0, "x": -3.0, "time": 0.5},
					S._pose(0, "HitReact", 0.8),
					{"t": "fx", "kind": "shake"},
					S._narr("Er wirft sich zu spät dazwischen. Der Speer streift die Schulter. Und trotzdem läutet der Schild, leise, wie von fern.")]},
			S._cam("close", 0, 1.6),
			S._narr("Jetzt erinnert er sich. Nach dem Brand zog er die geschmolzene Glocke aus der Asche und schmiedete sie zu einem Schild. Damit das Kloster nicht ganz verstummt."),
			S._narr("Darum hält sein Schildwall jeden Stoß auf und wirft Geschosse zurück: Eine Glocke ruft. Sie lässt sich nicht zum Schweigen bringen."),
			S._say("liora", "Deine Glocke hat nie aufgehört zu läuten, Vater Cardinal. Du hast nur nicht mehr zugehört."),
			S._music("boss"),
			{"t": "branch", "flag": "steel_knight_sword_down", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.0, "time": 0.8},
				S._say("sigrun", "Morgenwache, zur Stelle! Diesmal halten wir das Tor zu zweit, Eisenkopf. Und keiner schickt keinen weg."),
				{"t": "fight", "cast": ["hero", "sigrun", "principatus"], "goal": "HALTET DAS TOR ZU ZWEIT!", "lives": [3, 2, 1], "teams": [0, 0, 1], "qte": "steel_knight_bell", "ai": 6},
			], "else": [
				S._say("hero", "Kind. Hinter mich. Und wenn ich falle – läute."),
				{"t": "fight", "cast": ["hero", "principatus"], "goal": "DAS TOR HÄLT!", "lives": [3, 1], "mods": {"1": {"power": 1.15}}, "qte": "steel_knight_bell", "ai": 6},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 1.6),
			S._narr("Das weiße Licht zieht sich zurück. Principatus neigt den Kopf, kaum merklich, wie vor einem Gleichgestellten."),
			S._say("principatus", "Die Frage war nie, ob du siegst. Sondern wohin du dich drehst, wenn der Speer kommt. Du hast dich zum Kind gedreht."),
			{"t": "vanish", "who": 2},
			S._say("hero", "Schild hoch. Gebet gesprochen. Kein Schritt zurück … und keiner mehr weg."),
		]},
		{"id": "steel_knight_4", "title": "Niemand in der Rüstung", "arena": "bg_ruined_city", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["leer", 2.0, -1], ["liora", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Niemand in der Rüstung"},
			S._narr("Ein Jahr später kehrt Cardinal ein letztes Mal zu den Ruinen des alten Klosters zurück. Er wollte allein gehen. Liora ist natürlich trotzdem da."),
			S._cam("two", 0, 1.4, 2),
			S._say("liora", "Warum hierher? Das neue Kloster steht doch."),
			S._say("hero", "Ich habe hier etwas liegen lassen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._narr("Aus der Asche steht eine Rüstung auf. Rot, verbeult, genau wie seine. Der Visierschlitz ist leer. Dahinter: nur Dunkelheit."),
			S._say("leer", "In deiner Rüstung ist niemand mehr. Seit zwölf Jahren. Ich bin, was übrig blieb: Eisen, das betet, weil es vergessen hat, wie man fühlt."),
			S._say("leer", "Nimm den Helm nicht ab. Darunter ist nur ein alter Mann, der versagt hat. Hier drin bist du ein Wächter. Für immer."),
			S._say("liora", "Hör nicht auf ihn! Der alte Mann unterm Helm hat mir Lesen beigebracht. Und er sitzt bei jedem Gewitter an meinem Bett!"),
			S._cam("close", 0, 1.2),
			S._pose(0, "Block", 0.8),
			S._say("hero", "Schild hoch. Gebet gesprochen. … Und diesmal höre ich es."),
			S._narr("Die leere Rüstung weicht nicht. Stöße prallen an ihr ab wie Regen. Nur der Gegenhieb im richtigen Moment bringt sie ins Wanken."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "leer"], "goal": "SCHILDRICHTER – RICHTE DIE LEERE!", "lives": [2, 2], "mods": {"1": {"kb": 0.6, "power": 1.15}}, "ai": 8},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 2.0),
			S._narr("Die leere Rüstung fällt in sich zusammen. Nur ein Haufen altes Blech. Darunter blüht eine Distel."),
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 1.0),
			S._narr("Dann tut Cardinal, was er seit zwölf Jahren nicht getan hat. Er löst die Schnallen. Er nimmt den Helm ab."),
			S._narr("Darunter: ein müder alter Mann mit grauem Bart. Er blinzelt in die Sonne wie jemand, der sehr lange in einem Keller war."),
			S._cam("two", 0, 1.4, 2),
			S._say("liora", "Du hast ja Falten! So viele Falten! Die Kinder werden lachen."),
			S._say("hero", "Lass sie lachen. Das ist ein schönerer Klang als jede Glocke."),
			{"t": "branch", "flag": "steel_knight_sword_down", "steps": [
				S._narr("Sein Schwert steckt noch immer im Boden der Festung am Pass. Sigrun hat einen Kranz darumgehängt. Sie sagt, es sei ein Denkmal für Sturköpfe."),
			], "else": [
				S._narr("Sein Schwert hängt jetzt über der Klostertür. Sigrun putzt es jeden Sonntag und behauptet, sie könne bloß keinen Rost sehen."),
			]},
			S._cam("sky", 0, 3.0),
			S._narr("Im neuen Kloster am Stillen Brunnen bringen ihm die Kinder jeden Abend Tee. Er erzählt Geschichten. Die besten handeln von einem Mädchen mit einer Laterne."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Cardinal · Das Gebet aus Eisen"},
			S._narr("Relikt erhalten: Die Glockenzunge  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
