extends RefCounted
## Legende: GRIMBOLT, DER GOBLIN-TÜFTLER – „Etwas, das bleibt“.
## Grimbolt baut Bomben, Uhren und Bombenuhren. Seine Werkstatt ist siebenmal explodiert. Er baut
## Zerstörerisches, weil niemand je seine nützlichen Erfindungen wollte. Arbër der Bohrmeister baut
## Häuser, Mammon kauft ihm alle Bomben ab – und am Ende baut Grimbolt eine Uhr für den Marktplatz.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Etwas, das bleibt",
	"summary": "Grimbolts Werkstatt ist siebenmal explodiert. Er baut Bomben, weil niemand seine nützlichen Erfindungen kaufen wollte. Insgeheim wünscht er sich nur eins: etwas zu bauen, das stehen bleibt.",
	"relic": "Das Zahnrad der Marktuhr",
	"relic_text": "Ein kleines Messingzahnrad mit eingravierten Initialen: G und A. Es stammt aus einer Uhr, die nicht explodiert ist. Bis heute nicht.",
}

const CAST := {
	"hero": {"preset": "grimbolt", "name": "GRIMBOLT", "title": "Der Goblin-Tüftler", "color": "84cc16"},
	"arber": {"preset": "arber", "name": "ARBËR", "title": "Der Bohrmeister", "color": "e41e20"},
	"oma": {"preset": "nekra", "name": "OMA RUSSELKNOPF", "title": "Grimbolts Großmutter", "color": "a3e635"},
	"haendler": {"preset": "don_valente", "name": "WAFFENHÄNDLER", "title": "Kauft jede Bombe", "color": "d4af37"},
	"kunde": {"preset": "pirate_captain", "name": "UNZUFRIEDENE KUNDIN", "title": "Wollte nur einen Wecker", "color": "f87171"},
	"mammon": {"boss": "mammon", "name": "MAMMON", "title": "Der Käufer aller Dinge", "color": "eab308"},
	"bumm": {"preset": "grimbolt", "name": "BUMM", "title": "Grimbolts Lieblingsgeräusch", "color": "dc2626"},
}

static func chapters() -> Array:
	return [
		{"id": "grimbolt_1", "title": "Die siebte Explosion", "arena": "gladiator_fortress", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["kunde", 2.8, -1], ["haendler", 5.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("hope"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "GRIMBOLT · ETWAS, DAS BLEIBT", "sub": "Kapitel I – Die siebte Explosion"},
			S._narr("Grimbolt hat einen Wecker erfunden, der einem morgens Kaffee kocht. Einen Regenschirm, der sich selbst aufspannt. Eine Uhr, die nie nachgeht."),
			S._narr("Keiner wollte sie kaufen. Dann baute er aus Versehen eine Bombe. Alle wollten sie kaufen. Seitdem baut er Bomben. Seine Werkstatt ist siebenmal explodiert."),
			{"t": "fx", "kind": "flash"},
			{"t": "fx", "kind": "shake"},
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 0.8),
			S._say("hero", "Hust! Hehe. Das war Nummer sieben. Ein neuer Rekord! Die Tür ist diesmal bis zur Arena geflogen!"),
			S._cam("two", 0, 1.4, 1),
			S._say("kunde", "GRIMBOLT! Ich habe bei dir einen WECKER bestellt! Einen ganz normalen Wecker! Er hat mein Schlafzimmer gesprengt!"),
			S._say("hero", "Er hat dich aber geweckt, oder? Tick, tack, BUMM! Hehe!"),
			S._say("kunde", "Ich will mein Geld zurück! Oder deinen Kopf!"),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "ZEITBOMBE!", "flag": "grimbolt_bomb",
				"success": [S._narr("Grimbolt wirft eine kleine tickende Kugel. Sie rollt der Kundin genau vor die Stiefel. Sie springt.")],
				"fail": [S._narr("Die Bombe tickt. Und tickt. Und tickt. Nichts passiert. Peinlich.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "kunde"], "goal": "ENTKOMME DER WÜTENDEN KUNDIN!", "lives": [3, 2], "qte": "grimbolt_bomb", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("haendler", "Grimbolt, mein Lieblingsgoblin. Ich nehme alles, was du hast. Alles, was knallt. Doppelter Preis."),
			S._say("hero", "Ich hab auch einen Regenschirm. Er spannt sich von selbst auf. Willst du den?"),
			S._say("haendler", "Explodiert er?"),
			S._say("hero", "… Nein."),
			S._say("haendler", "Dann nicht."),
			S._cam("close", 0, 1.4),
			S._narr("Grimbolt verkauft ihm zwölf Bomben. Den Regenschirm stellt er zurück in die Ecke. Dort stehen schon dreißig andere Erfindungen, die niemand wollte."),
		]},
		{"id": "grimbolt_2", "title": "Die Mauer des Bohrmeisters", "arena": "bg_warehouse", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["arber", 2.5, -1], ["oma", -3.5, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Mauer des Bohrmeisters"},
			S._narr("Für einen Test braucht Grimbolt eine Mauer. Er findet eine am Hang über dem Dorf. Sie ist schön gerade. Sie wäre schöner, wenn sie BUMM machen würde."),
			{"t": "fx", "kind": "flash"},
			{"t": "fx", "kind": "shake"},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("arber", "Das war Ilirs Ostmauer. Ich habe sie für ein Versprechen gebaut. Für eine Familie, die vor dem Winter ein Dach braucht."),
			S._say("hero", "Ups. Hehe. Entschuldigung? Mauern sind halt langweilig. Alle bauen Mauern."),
			S._say("arber", "Grimbolt, du baust Bomben. Ich baue Häuser. Willst du nicht einmal etwas bauen, das stehen bleibt?"),
			S._cam("close", 0, 1.4),
			S._narr("Niemand hat ihn das je gefragt. Grimbolt öffnet den Mund für einen Witz. Es kommt keiner."),
			{"t": "choice", "text": "Was antwortet Grimbolt?", "options": [
				{"label": "Ehrlich sein", "flag": "grimbolt_honest", "steps": [
					S._say("hero", "Ich … habe einen Regenschirm gebaut. Und einen Wecker mit Kaffee. Keiner wollte sie. Bomben wollen alle."),
					S._say("arber", "Dann hast du für die falschen Leute gebaut. Zeig mir, was du kannst. Erst im Kampf, danach mit dem Werkzeug.")]},
				{"label": "Frech bleiben", "flag": "grimbolt_cheeky", "steps": [
					S._say("hero", "Stehen bleiben? PAH! Das Schönste an allem ist der Moment, in dem es umfällt!"),
					S._say("arber", "Dann zeig mir, wie schön es ist, wenn du umfällst.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "arber"], "goal": "BOMBE GEGEN BOHRER!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "grimbolt_honest", "steps": [
				S._say("arber", "Am Hang liegt ein Fels, der das Fundament blockiert. Sprengen, nicht das Haus. Kannst du das? Genau? Nur so viel wie nötig?"),
				S._say("hero", "Genau? Nur so viel wie nötig? Das … das hat noch nie jemand von mir verlangt. Ja. Ja, ich glaube, das kann ich."),
			], "else": [
				S._say("arber", "Du bist schnell. Und laut. Und jedes Mal, wenn es knallt, guckst du dich um, ob jemand zuschaut. Wer soll zuschauen, Goblin?"),
			]},
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("oma", "Grimbolt Russelknopf! Ein Mann in Gold war in deiner Werkstatt. Er hat gesagt, er kauft alles. Für immer. Er wartet unten im Keller. Der Keller war gestern noch nicht so tief."),
		]},
		{"id": "grimbolt_3", "title": "Der Käufer aller Dinge", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["mammon", 3.0, -1], ["arber", -4.0, 1], ["oma", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Käufer aller Dinge"},
			S._narr("Der Keller führt hinab in eine Stadt aus Gold. Überall Waren: Kronen, Schwerter, Seelen in Flaschen. Und ganz vorne, im Schaufenster: Grimbolts Bomben."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("mammon", "Der Goblin! Mein bester Lieferant. Ich kaufe dir alles ab. Jede Bombe. Für immer. Gold, so viel du tragen kannst."),
			S._say("mammon", "Der Preis ist klein: jede Erfindung, die du noch machen wirst. Sie gehören mir. Du baust nur noch, was ich bestelle. Bomben."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Jede Erfindung? Auch die Uhr, an der ich arbeite? Die mit dem Glockenspiel?"),
			S._say("mammon", "Wer braucht Glockenspiele? Du wirst nie etwas erschaffen, das bleibt. Also verkauf mir lieber, was kaputtgeht."),
			S._say("hero", "Ich habe sieben Werkstätten in die Luft gejagt. Aber keine davon habe ich verkauft. Die Uhr bekommst du nicht."),
			S._music("boss"),
			{"t": "branch", "flag": "grimbolt_honest", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("arber", "Partner! Du hast meinen Fels gesprengt – nur den Fels. Jetzt helfe ich dir, diesen Goldsack zu sprengen. Aber genau!"),
				{"t": "fight", "cast": ["hero", "arber", "mammon"], "goal": "VERKAUF NICHT DEINE ZUKUNFT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("oma", "Niemand kauft meinen Enkel! Ich habe ihm sein erstes Zündholz geschenkt, und ich nehme es ihm notfalls wieder weg!"),
				{"t": "fight", "cast": ["hero", "oma", "mammon"], "goal": "VERKAUF NICHT DEINE ZUKUNFT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Mammons Schaufenster zerspringt. Die Bomben darin zischen – und sprühen nur Konfetti. Grimbolt hat sie heimlich umgebaut. Das war sein bester Trick."),
			S._say("mammon", "Konfetti?! Du hast mir KONFETTI verkauft? Zum Preis von Bomben?"),
			S._say("hero", "Hehe! Kein Umtausch, keine Rückgabe! Steht klein gedruckt auf der Rechnung. Ganz, ganz klein."),
			S._say("mammon", "Ich kaufe alles, Goblin. Irgendwann auch dich."),
			S._say("hero", "Dann musst du warten, bis ich explodiere. Und das habe ich mir gerade abgewöhnt."),
			S._narr("Zurück in der Werkstatt holt Grimbolt den Regenschirm aus der Ecke. Er spannt sich auf. Er explodiert nicht. Grimbolt lächelt."),
		]},
		{"id": "grimbolt_4", "title": "Die Uhr auf dem Marktplatz", "arena": "bg_night_market", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["bumm", 2.0, -1], ["arber", -3.5, 1], ["oma", 4.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Die Uhr auf dem Marktplatz"},
			S._narr("Auf dem Marktplatz steht ein Gerüst. Darin eine Uhr, halb fertig, mit einem Glockenspiel aus alten Bombenhüllen. Grimbolt sitzt davor und zittert."),
			S._cam("two", 0, 1.6, 2),
			S._say("arber", "Das letzte Zahnrad. Setz es ein. Dann läuft sie."),
			S._say("hero", "Und wenn sie explodiert? Alles, was ich baue, explodiert irgendwann. Das ist mein Ding. Das bin ich."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("bumm", "Mach sie BUMM! Das ist doch das Beste! Das Geräusch, wenn alles auseinanderfliegt! Dann gucken alle! Dann sehen dich alle!"),
			S._say("hero", "Sie gucken. Und dann rennen sie weg. Ich will, dass sie bleiben. Ich will, dass sie stehen bleiben und auf die Uhr gucken."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "bumm"], "goal": "ENTSCHÄRFE DEIN LIEBLINGSGERÄUSCH!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Cast", 1.0),
			S._narr("Grimbolt setzt das letzte Zahnrad ein. Klick. Die Zeiger springen an. Tick. Tack. Tick. Tack. Kein Bumm."),
			S._narr("Zur vollen Stunde spielt das Glockenspiel. Eine kleine, schiefe Melodie. Auf dem ganzen Marktplatz bleiben die Leute stehen und schauen hoch."),
			S._cam("two", 0, 1.6, 3),
			S._say("oma", "Sie bleibt stehen, Grimbolt. Deine Uhr. Sie bleibt einfach stehen und geht trotzdem."),
			S._say("hero", "Hehe. Hehe! Sie explodiert nicht! Arbër! Sie explodiert nicht!"),
			S._say("arber", "Ich habe es gesehen. Und morgen baust du mir einen Wecker mit Kaffee. Ich zahle doppelt."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Grimbolt · Etwas, das bleibt"},
			S._narr("Relikt erhalten: Das Zahnrad der Marktuhr  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
