extends RefCounted
## Legende: KALYX, DER ZWIEKRISTALL – „Kalt und heiß“.
## Kalyx stammt aus einem Volk, dessen Kronen aus Kristall wachsen. Bei allen anderen ist die Krone
## entweder Frost oder Glut. Seine ist beides – und darum war er nie einer von ihnen. Hikaru zeigt ihm,
## dass Feuer nicht zerstören muss, Seraphael will ihn ganz verbrennen, und am Ende hört er auf zu wählen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Kalt und heiß",
	"summary": "Bei Kalyx' Volk wächst jedem eine Krone aus Kristall – blau für die Frostsippe, rot für die Glutsippe. Seine ist vorne blau und hinten rot. Beide Sippen haben ihn verstoßen.",
	"relic": "Der Zwiesplitter",
	"relic_text": "Ein Kristallsplitter, der in der Hand kühl ist und in der Faust warm. Er ist aus Kalyx' Krone gebrochen, als er aufgehört hat zu wählen.",
}

const CAST := {
	"hero": {"preset": "kalyx", "name": "KALYX", "title": "Der Zwiekristall", "color": "7dd3fc"},
	"frostwache": {"preset": "glaciem", "name": "FROSTWACHE", "title": "Hütet das blaue Tor", "color": "bae6fd"},
	"glutwache": {"preset": "pyrax", "name": "GLUTWACHE", "title": "Hütet das rote Tor", "color": "ff6610"},
	"hikaru": {"preset": "hikaru", "name": "HIKARU", "title": "Feuer, das wärmt", "color": "ff7a2e"},
	"seraph": {"boss": "seraph", "name": "SERAPHAEL", "title": "Das brennende Auge", "color": "fde68a"},
	"schatten": {"preset": "kalyx", "name": "DER HALBE", "title": "Der Kalyx, der sich entscheiden will", "color": "1e3a8a"},
}

static func chapters() -> Array:
	return [
		{"id": "kalyx_1", "title": "Zwei Tore", "arena": "frozen_summit", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["frostwache", 2.8, -1], ["glutwache", 4.0, -1]]),
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KALYX · KALT UND HEISS", "sub": "Kapitel I – Zwei Tore"},
			S._narr("Im Kristallgebirge gibt es zwei Städte: die blaue der Frostsippe und die rote der Glutsippe. Wer geboren wird, dem wächst eine Krone – und sie sagt, wohin er gehört."),
			S._narr("Kalyx' Krone ist vorne blau und hinten rot. Er steht zwischen den beiden Toren. Wie jedes Jahr."),
			S._cam("two", 0, 1.6, 1),
			S._say("frostwache", "Halb rot. Du gehörst nicht zu uns, Zwiekristall."),
			S._say("glutwache", "Halb blau. Zu uns auch nicht. Geh zurück in die Mitte, wo du hingehörst."),
			S._say("hero", "In der Mitte ist nur der Pass. Und der Wind. Ich will nur einmal hinein. Ein einziges Mal."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "frostwache", "glutwache"], "goal": "BEIDE TORE GEGEN DICH!", "lives": [3, 1, 1], "teams": [0, 1, 1], "ai": 3},
			S._music("calm"),
			S._cam("close", 0, 1.4),
			S._narr("Beide Wachen liegen im Schnee. Beide Tore bleiben zu. Kalyx' Krone flackert – blau, rot, blau – wie ein Herz, das nicht weiß, in welche Richtung es schlagen soll."),
			S._say("hero", "Gewonnen. Und trotzdem draußen."),
		]},
		{"id": "kalyx_2", "title": "Feuer, das wärmt", "arena": "volcano_sanctum", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["hikaru", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Feuer, das wärmt"},
			S._narr("Kalyx verlässt das Gebirge. Am Rand eines Vulkans trifft er einen Wanderer mit einer glühenden Klinge, der am Feuer sitzt und Reis kocht."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("hikaru", "Deine Krone flackert. Hunger oder Wut?"),
			S._say("hero", "Beides. Ich weiß nie, welches Element gerade gewinnt. Glut zerstört. Frost hält fest. Ich will keins von beiden sein."),
			S._say("hikaru", "Mein Feuer kocht Reis. Hat noch nie etwas zerstört, was ich nicht wollte. Komm, zeig mir deine Glut – ich zeige dir meine."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "hikaru"], "goal": "KRISTALL GEGEN GLUTKLINGE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("hikaru", "Siehst du? Du hast im Kampf dreimal gewechselt. Und jedes Mal genau im richtigen Moment."),
			S._say("hero", "Weil ich musste. Nicht, weil ich wollte."),
			S._say("hikaru", "Vielleicht ist das dasselbe. Iss. Der Reis wird kalt – oder heiß, wie du willst."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht öffnet sich über dem Vulkan ein brennendes Auge. Es sieht nur die rote Hälfte seiner Krone. Und es will den Rest."),
		]},
		{"id": "kalyx_3", "title": "Das brennende Auge", "arena": "empyrean", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["seraph", 3.0, -1], ["hikaru", -4.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das brennende Auge"},
			S._narr("Licht so heiß, dass der Schnee in Kalyx' Krone verdampft. Vor ihm schwebt ein Wesen aus Flügeln und Flammen."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("seraph", "Halbes Kind. Ich kann dich ganz machen. Lass mich das Blau verbrennen, und du wirst reine Glut. Die Glutsippe wird dir das Tor öffnen."),
			S._say("hero", "Ein offenes Tor … Nach all den Jahren."),
			S._say("seraph", "Ein kleiner Schmerz. Dann nie wieder Zweifel. Nur noch Feuer."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
			S._say("hikaru", "Kalyx! Ohne dein Blau hättest du mich gestern in Brand gesteckt. Das Blau hat mich gerettet. Und das Rot hat uns warm gehalten."),
			S._say("hero", "… Ich habe nicht gewählt, als ich dich nicht verletzt habe. Ich war einfach beides."),
			S._say("hero", "Brennendes Auge – du siehst nur die Hälfte. Schau mich ganz an."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "hikaru", "seraph"], "goal": "FROST UND GLUT ZUGLEICH!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Eis und Feuer treffen das Auge zugleich. Dampf füllt den Himmel. Als er sich lichtet, ist der Seraph fort – und Kalyx' Krone leuchtet in beiden Farben auf einmal."),
		]},
		{"id": "kalyx_4", "title": "Der Pass", "arena": "frozen_summit", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["hikaru", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der Pass"},
			S._narr("Zurück am Pass zwischen den Toren. Dort steht ein Kalyx mit halber Krone – die andere Hälfte abgebrochen, die Bruchkante scharf wie ein Messer."),
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schatten", "Brich die andere Hälfte ab. Ich habe es getan. Jetzt gehöre ich irgendwo hin. Es tut nur einmal weh."),
			S._say("hero", "Und dann bist du halb. Für immer. Ich bin lieber ganz und gehöre nirgends hin – als halb und irgendwo."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schatten"], "goal": "BLEIB GANZ!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._narr("Ein Splitter löst sich aus Kalyx' Krone, nicht abgebrochen, sondern gewachsen. Kühl in der Hand, warm in der Faust."),
			S._say("hikaru", "Und jetzt? Blaues Tor oder rotes?"),
			S._say("hero", "Keins. Ich baue hier am Pass ein drittes. Für alle, deren Krone nicht weiß, was sie ist."),
			S._narr("Im Frühling steht am Pass eine kleine Hütte mit einem Tor ohne Farbe. Das erste Kind, das anklopft, hat eine Krone, die grün schimmert."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Kalyx · Kalt und heiß"},
			S._narr("Relikt erhalten: Der Zwiesplitter  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
