extends RefCounted
## Legende: MOSSBACK, DIE STEINBESTIE – „Das Gewicht des Waldes“.
## Dreihundert Jahre lag ein Fels am Rand des Hains, bis die Dürre kam und eine Haselmaus ihn
## überredete aufzustehen. Ein verbrannter Eichenhüter, eine Köhlerin im Dienst eines Dämons und
## die Frage, ob man eine Last tragen muss – oder tragen darf. Hier entsteht der Mooszorn.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Das Gewicht des Waldes",
	"summary": "Dreihundert Jahre war Mossback ein Fels mit einem Wald auf dem Rücken. Dann versiegt der Bach – und eine Haselmaus bittet den Berg, endlich zu gehen.",
	"relic": "Das Moospolster",
	"relic_text": "Ein Stück Moos von Mossbacks Rücken. Es bleibt grün, solange jemand darauf schläft.",
}

const CAST := {
	"hero": {"preset": "mossback", "name": "MOSSBACK", "title": "Die Steinbestie", "color": "84cc16"},
	"haselnuss": {"preset": "lepora", "name": "HASELNUSS", "title": "Haselmaus im Moos", "color": "d6a26b"},
	"altholz": {"preset": "treant", "name": "ALTHOLZ", "title": "Der letzte Eichenhüter", "color": "a16207"},
	"asche": {"preset": "pyrax", "name": "ASCHENMUTTER", "title": "Köhlerin vom Rußtal", "color": "f97316"},
	"funke": {"preset": "zip", "name": "FUNKE", "title": "Ihr Lehrling mit Zunder", "color": "fde047"},
	"baphomet": {"boss": "baphomet", "name": "BAPHOMET", "title": "Der Bock, der Lasten frisst", "color": "7f1d1d"},
	"fels": {"preset": "mossback", "name": "DER NACKTE FELS", "title": "Mossback ohne Wald", "color": "78716c"},
}

static func chapters() -> Array:
	return [
		{"id": "mossback_1", "title": "Der Fels steht auf", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["haselnuss", -3.2, 1], ["asche", 9.0, -1], ["funke", 10.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "MOSSBACK · DAS GEWICHT DES WALDES", "sub": "Kapitel I – Der Fels steht auf"},
			S._narr("Dreihundert Jahre lag ein Fels am Rand des Hains. Moos wuchs auf ihm, dann Farn, dann eine kleine Eiche. Tiere schliefen in seinen Ritzen."),
			S._narr("Niemand wusste, dass der Fels atmete. Einmal pro Woche. Sehr langsam."),
			S._cam("two", 0, 1.6, 1),
			S._say("haselnuss", "Fels? Felsi? Großer grauer Herr? Ich weiß, dass du wach bist. Du hast vorhin gegähnt. Drei Eichhörnchen sind runtergefallen."),
			S._say("hero", "… Hm."),
			S._say("haselnuss", "Der Bach ist weg. Seit zwanzig Tagen kein Tropfen. Die Farne werden braun, und die Igelkinder weinen nachts."),
			S._say("haselnuss", "Und heute Morgen hab ich Rauch gerochen. Aus dem Rußtal. Die Köhler kommen."),
			S._music("tense"),
			{"t": "fx", "kind": "shake"},
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3},
			{"t": "move", "who": 2, "x": 3.2, "time": 1.0},
			{"t": "move", "who": 3, "x": 4.6, "time": 1.2},
			S._cam("two", 0, 1.2, 2),
			S._say("asche", "Seht euch das an. Ein ganzer Hain, trocken wie Zunder. Daraus brennen wir Kohle für drei Winter."),
			S._say("funke", "Und der große Stein da, Meisterin? Der sieht aus, als hätte er ein Gesicht."),
			S._say("asche", "Steine haben keine Gesichter, Funke. Zünd den Farn an. Fang bei dem Moos auf dem Felsen an."),
			S._cam("close", 0, 1.4),
			S._say("haselnuss", "Fels! Jetzt! Wenn du jemals aufstehen wolltest, dann JETZT! Bitte!"),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 14, "time": 3.0, "text": "STEH AUF!", "flag": "mossback_rise",
				"success": [
					{"t": "fx", "kind": "shake"},
					S._pose(0, "Rise", 1.2),
					S._narr("Der Boden reißt. Wurzeln springen aus der Erde wie Saiten. Der Fels steht auf – der Wald auf seinem Rücken schwankt, aber er hält.")],
				"fail": [
					S._pose(0, "Rise", 1.6),
					S._narr("Er stemmt sich hoch, Zentimeter um Zentimeter. Ein Stück Moos reißt ab. Ein Spatz flucht sehr laut.")]},
			S._say("funke", "Meisterin … der Stein hat Beine."),
			S._pose(0, "Roar", 1.0),
			S._say("hero", "Mein. Wald."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "asche", "funke"], "goal": "VERTREIB DIE KÖHLER, BEVOR DER HAIN BRENNT!", "lives": [3, 1, 1], "teams": [0, 1, 1], "time": 80, "qte": "mossback_rise", "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.6, 1),
			S._narr("Die Köhler rennen bis ins Rußtal. Funke dreht sich zweimal um, als könnte er nicht glauben, was er gesehen hat."),
			S._say("haselnuss", "Du hast GESPROCHEN. Zwei Wörter! Ich hab mein ganzes Leben auf zwei Wörter gewartet! Und das meiner Oma!"),
			S._say("hero", "Durst."),
			S._say("haselnuss", "Ja. Alle haben Durst. Hinter dem Dschungel soll es einen Fluss geben, der nie versiegt. Sagt die Elster. Die lügt aber oft."),
			S._cam("low", 0, 2.0),
			S._narr("Und so ging der Berg. Mit einer Eiche, vierzig Vögeln, einer Igelfamilie und einer Haselmaus, die nie aufhörte zu reden."),
		]},
		{"id": "mossback_2", "title": "Der Alte im Dschungel", "arena": "bg_jungle_ruins", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["haselnuss", -3.4, 1], ["altholz", 3.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("hope"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Alte im Dschungel"},
			S._narr("Sechs Tage Wanderung. Mossback geht so langsam, dass auf seinem Rücken Blumen aufblühen und verwelken, während er einen Hügel nimmt."),
			S._cam("two", 0, 1.4, 1),
			S._say("haselnuss", "Du könntest ein winziges bisschen schneller gehen. Nur so schnell wie eine Schnecke mit einem Termin."),
			S._say("hero", "Nein. Nester."),
			S._say("haselnuss", "… Wegen der Nester. Natürlich. Entschuldigung, Herr Berg."),
			{"t": "fx", "kind": "shake"},
			{"t": "appear", "who": 2},
			S._cam("close", 2, 1.4),
			S._pose(2, "Roar", 1.0),
			S._narr("Zwischen den Ruinen erhebt sich ein Baum, der kein Baum ist. Seine Rinde ist schwarz versengt, seine Äste knarren wie alte Türen."),
			S._say("altholz", "Steinbeißer. Ich kenne die Eiche auf deinem Rücken. Sie ist aus meiner Eichel gewachsen."),
			S._say("altholz", "Mein Hain ist verbrannt. Alles, was von mir übrig ist, trägst du spazieren. Du trägst meinen Wald. Gib ihn zurück."),
			S._cam("two", 0, 1.4, 2),
			S._say("hero", "Nicht. Dein. Wald."),
			S._say("haselnuss", "Genau genommen hat ein Eichhörnchen die Eichel vergraben und vergessen. Gehört der Wald dann nicht dem Eichhörnchen?"),
			S._say("altholz", "Schweig, Nagetier. Dann nehme ich ihn mir. Mit den Wurzeln."),
			S._narr("Altholz kämpft auf eigenem Boden. Die Ruinen gehorchen ihm, jede Ranke ist seine Hand."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "altholz"], "goal": "STEH GEGEN DEN EICHENHÜTER!", "lives": [2, 2], "mods": {"1": {"power": 1.25, "kb": 0.85}}, "ai": 5},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._cam("low", 0, 1.6),
			S._pose(0, "Roar", 1.0),
			S._narr("Mitten im Kampf hatte Mossback grün geglüht. Kein Licht – Zorn. Jeder Vogel, jeder Igel, jede Ameise auf seinem Rücken war wütend geworden."),
			S._narr("Und all diese kleine Wut floss zusammen in den Fels. So entstand der Mooszorn: die Kraft von allen, die er trägt."),
			S._say("haselnuss", "Das war ICH! Also, wir alle! Ich war auch wütend. Sehr. Für meine Größe."),
			S._pose(2, "Dazed", 1.0),
			S._cam("two", 0, 1.4, 2),
			S._say("altholz", "Dreihundert Jahre habe ich gewartet, dass mir jemand zurückgibt, was das Feuer genommen hat. Niemand kam."),
			{"t": "choice", "text": "Altholz kniet vor seinen verkohlten Wurzeln. Was tut Mossback?", "options": [
				{"label": "Gib ihm Setzlinge", "flag": "mossback_shared", "steps": [
					S._pose(0, "Crouch", 1.0),
					S._narr("Mossback senkt den Rücken. Haselnuss gräbt sieben kleine Eichen aus dem Moos und setzt sie in die schwarze Erde."),
					S._say("altholz", "Du gibst freiwillig, was ich rauben wollte?"),
					S._say("hero", "Wald. Will. Wandern.")]},
				{"label": "Behalte den Wald", "flag": "mossback_kept", "steps": [
					S._say("hero", "Nein. Sie. Schlafen."),
					S._say("haselnuss", "Er meint: Die Tiere schlafen gerade. Er weckt keinen. Nicht mal für dich."),
					S._say("altholz", "Dann geh, Steinbeißer. Aber merk dir: Ein Wald, den nur einer trägt, stirbt mit ihm.")]},
			]},
			S._cam("low", 0, 1.8),
			S._narr("In dieser Nacht spürt Mossback zum ersten Mal, wie schwer der Wald ist. Nicht in den Schultern. Irgendwo tiefer."),
		]},
		{"id": "mossback_3", "title": "Der Bock am Knochendamm", "arena": "hell_flames", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["haselnuss", -3.8, 1], ["baphomet", 3.0, -1], ["asche", 4.6, -1], ["altholz", -6.0, 1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Bock am Knochendamm"},
			S._narr("Der Fluss, der nie versiegt, ist versiegt. Wo er war, gähnt ein Riss. Haselnuss hört tief darunter Wasser rauschen. Also steigt der Berg hinab."),
			S._narr("Unten brennt der Boden. Ein Damm aus Knochen und Kohle hält den Fluss gefangen. Und davor sitzt eine bekannte Gestalt."),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.4, 3),
			S._say("asche", "Na sieh an. Der Stein mit dem Gesicht. Weißt du, wer meine Kohle jetzt kauft? Jemand, der besser zahlt als jeder Schmied."),
			{"t": "fx", "kind": "ink", "who": 2},
			{"t": "appear", "who": 2},
			S._cam("sky", 2, 2.4),
			S._music("boss"),
			S._say("baphomet", "Ich staue den Fluss, kleiner Berg. Wasser ist Last. Wälder sind Last. Alles, was lebt, will getragen werden."),
			S._say("baphomet", "Leg ihn ab. Den Wald, die Maus, die Nester. Ich nehme alles. Und du wirst leicht. Zum ersten Mal in dreihundert Jahren: leicht."),
			S._cam("close", 0, 1.6),
			S._pose(0, "Dazed", 1.0),
			S._narr("Und Mossback – das ist das Schlimmste – denkt darüber nach. Nur einen Herzschlag lang. Aber sein Herz schlägt sehr langsam."),
			S._say("haselnuss", "Herr Berg? … Du denkst doch nicht wirklich darüber nach. Oder? Sag was. Zwei Wörter. Eins reicht auch."),
			{"t": "qte", "kind": "sequence", "keys": ["block", "grab", "standard"], "time": 3.0, "text": "HALT DEN WALD FEST!", "flag": "mossback_hold",
				"success": [
					S._pose(0, "Block", 0.8),
					S._narr("Mossback stemmt alle vier Beine in die Glut. Kein Blatt fällt. Kein Nest rutscht."),
					S._say("hero", "Mein. Gewicht.")],
				"fail": [
					{"t": "fx", "kind": "shake"},
					S._narr("Ein Ast bricht. Ein Nest fällt in die Glut – Haselnuss springt hinterher und rettet drei Eier. Mossback brüllt, wie er noch nie gebrüllt hat.")]},
			{"t": "branch", "flag": "mossback_shared", "steps": [
				{"t": "fx", "kind": "shake"},
				{"t": "appear", "who": 4},
				{"t": "move", "who": 4, "x": -1.2, "time": 1.0},
				S._say("altholz", "Meine Wurzeln reichen weit, Steinbeißer. Sieben Eichen haben mir gesagt, wo du bist. Ich schulde dir einen Wald."),
				{"t": "fight", "cast": ["hero", "altholz", "baphomet", "asche"], "goal": "BRECHT DEN KNOCHENDAMM!", "lives": [3, 2, 1, 1], "teams": [0, 0, 1, 1], "qte": "mossback_hold", "ai": 6},
			], "else": [
				S._say("haselnuss", "Dann allein! Alle zusammen allein! Mooszorn, Herr Berg!"),
				{"t": "fight", "cast": ["hero", "baphomet", "asche"], "goal": "BRICH DEN KNOCHENDAMM!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "mossback_hold", "ai": 5},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			{"t": "vanish", "who": 2},
			S._cam("wide", 0, 1.6),
			S._narr("Der Damm bricht. Der Fluss kommt zurück – nicht als Rinnsal, als Lawine aus Wasser. Baphomet wird fortgespült, meckernd und fluchend."),
			S._say("haselnuss", "Wir sind nass! Wir sind ALLE nass! Herr Berg, du hast den Fluss befreit!"),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ich. Bin. Müde."),
			S._narr("Es ist das Ehrlichste, was er je gesagt hat."),
		]},
		{"id": "mossback_4", "title": "Das Lasttier", "arena": "bg_aurora_peaks", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["fels", 2.0, -1], ["haselnuss", -3.4, 1], ["altholz", -6.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das Lasttier"},
			S._narr("Der Fluss führt ihn hinauf, bis unter die Lichter am Himmel. Hier oben ist die Luft dünn – und der Wald so schwer wie nie."),
			S._cam("two", 0, 1.4, 2),
			S._say("haselnuss", "Herr Berg, du zitterst. Berge zittern nicht. Das ist nur ein Erdbeben, oder?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Crouch", 1.2),
			S._narr("Mossback legt sich hin. Und als er die Augen schließt, steht aus seinem Schatten ein Fels auf. Grau. Nackt. Kein Halm darauf."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("fels", "Sieh mich an. So warst du, bevor sie kamen. Kein Moos, keine Mäuse, kein Gewicht. Nur Stein. Frei."),
			S._say("fels", "Du bist nur ein Lasttier mit Moos. Sie benutzen dich, Berg. Schüttel sie ab, und wir sind wieder eins."),
			S._say("haselnuss", "Das stimmt nicht! … Oder? Herr Berg, sag ihm, dass das nicht stimmt!"),
			S._cam("close", 0, 1.2),
			S._pose(0, "Rise", 1.0),
			S._say("hero", "Lasttier … nein."),
			{"t": "branch", "flag": "mossback_shared", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -2.6, "time": 1.0},
				S._say("altholz", "Sieben Eichen wachsen, Steinbeißer. Ich bin hier, um zu sehen, ob der, der sie getragen hat, auch selbst steht."),
				S._music("boss_final"),
				{"t": "fight", "cast": ["hero", "altholz", "fels"], "goal": "ZEIG DEM FELS, WAS TRAGEN HEISST!", "lives": [2, 1, 2], "teams": [0, 0, 1], "mods": {"2": {"power": 1.2}}, "ai": 7},
			], "else": [
				S._say("haselnuss", "Dann zeig's ihm! Wir sind alle wütend! Mooszorn, Herr Berg – für jeden Grashalm!"),
				S._music("boss_final"),
				{"t": "fight", "cast": ["hero", "fels"], "goal": "ZEIG DEM FELS, WAS TRAGEN HEISST!", "lives": [2, 2], "damage": {"0": 35}, "ai": 7},
			]},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 2.0),
			S._narr("Der nackte Fels zerbröckelt zu Sand. Und im Sand keimt – natürlich – Moos."),
			S._narr("Mossback steigt zum Fluss hinunter und legt sich ans Ufer. Nicht, weil er nicht mehr kann. Weil er hier bleiben möchte."),
			S._cam("two", 0, 1.6, 2),
			S._say("haselnuss", "Und jetzt? Gehst du nie wieder? Trägst du uns nie wieder?"),
			S._say("hero", "Muss nicht tragen."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Darf."),
			{"t": "branch", "flag": "mossback_shared", "steps": [
				S._narr("Am anderen Ufer wächst ein junger Hain. Sieben Eichen und dazwischen ein alter Baum, der so tut, als würde er nicht herüberwinken."),
			], "else": [
				S._narr("Jedes Frühjahr fliegen Samen von seinem Rücken übers Wasser. Am anderen Ufer wächst ein neuer Wald. Er gehört niemandem. Genau richtig."),
			]},
			S._cam("sky", 0, 3.0),
			S._narr("Der Wald auf seinem Rücken blüht. Die Igelkinder lernen schwimmen. Und eine Haselmaus erzählt jedem Wanderer, dass sie mit einem Berg befreundet ist."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Mossback · Das Gewicht des Waldes"},
			S._narr("Relikt erhalten: Das Moospolster  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
