extends RefCounted
## Legende: KETTENWART, DER KERKERMEISTER – „Der letzte Schlüssel“.
## Der Kettenwart hütet ein Gefängnis, dessen Insassen längst Staub sind. Er schließt jede Nacht
## trotzdem ab. Er trägt die Schlüssel zu allen Zellen – auch zu seiner eigenen. Vlad war sein letzter
## Gefangener, Luzifer bietet ihm die ganze Hölle als Kerker, und am Ende schließt er seine Zelle auf.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der letzte Schlüssel",
	"summary": "Der Kettenwart hütet ein Gefängnis voller Staub. Er schließt jede Nacht ab, obwohl niemand mehr drin ist. Am Schlüsselbund hängt ein Schlüssel, den er nie benutzt: der zu seiner eigenen Zelle.",
	"relic": "Der rostige Zellenschlüssel",
	"relic_text": "Ein großer, rostiger Schlüssel mit der Nummer 0. Er schließt eine Tür auf, die immer offen war – man musste nur einmal drücken.",
}

const CAST := {
	"hero": {"preset": "kettenwart", "name": "KETTENWART", "title": "Der Kerkermeister", "color": "94a3b8"},
	"vlad": {"preset": "vampire_lord", "name": "VLAD", "title": "Sein letzter Gefangener", "color": "991b1b"},
	"maus": {"preset": "zip", "name": "PIEPS", "title": "Ein Dieb, der einbricht statt aus", "color": "fde68a"},
	"ausbrecher": {"preset": "reaper_hound", "name": "KERKERGEIST", "title": "Will endlich raus", "color": "475569"},
	"ausbrecher2": {"preset": "skeleton_reaper", "name": "KERKERGEIST", "title": "Will endlich raus", "color": "475569"},
	"lucifer": {"boss": "lucifer", "name": "LUZIFER", "title": "Der Gefangene im Eis", "color": "e0e7ff"},
	"zelle": {"preset": "kettenwart", "name": "ZELLE NULL", "title": "Der Gefangene, der er ist", "color": "1f2937"},
}

static func chapters() -> Array:
	return [
		{"id": "kettenwart_1", "title": "Nachtrunde", "arena": "blood_moon", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["ausbrecher", 2.8, -1], ["ausbrecher2", 4.0, -1], ["maus", -3.5, 1]]),
			{"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KETTENWART · DER LETZTE SCHLÜSSEL", "sub": "Kapitel I – Nachtrunde"},
			S._narr("Unter dem Blutmond steht der Turm von Schwarzfels. Dreihundert Zellen. Dreihundert Schlösser. Seit hundert Jahren kein Gefangener mehr. Nur Staub."),
			S._narr("Jede Nacht geht der Kettenwart seine Runde. Er rüttelt an jeder Tür. Er schließt jede ab. Dann hängt er die Schlüssel zurück an seinen Gürtel. Einer davon ist nie benutzt worden."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Zelle zweihundertneunundneunzig: verschlossen. Zelle dreihundert: verschlossen. Niemand entkommt. Nicht einmal ich."),
			S._cam("two", 0, 1.4, 1),
			S._say("ausbrecher", "Wärter. Wir sind seit hundert Jahren tot. Unsere Körper sind Staub. Lass wenigstens unsere Geister gehen."),
			S._say("hero", "Ein Urteil ist ein Urteil. Ich habe keinen Befehl, euch freizulassen."),
			S._say("ausbrecher2", "Der Richter, der uns verurteilt hat, ist auch Staub! Wer soll dir den Befehl geben?"),
			{"t": "qte", "kind": "press", "keys": ["grab"], "time": 1.3, "text": "SEELENKETTEN!", "flag": "kettenwart_chains",
				"success": [S._narr("Die Ketten schießen aus seinem Mantel und wickeln sich um die Geister. Sie zappeln.")],
				"fail": [S._narr("Die Ketten rasseln, aber greifen ins Leere. Der Kettenwart ist alt geworden.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "ausbrecher", "ausbrecher2"], "goal": "NIEMAND ENTKOMMT!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "kettenwart_chains", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("maus", "Huch! Ein Wärter! Ich bin nur hier eingebrochen, weil man sagt, hier gibt's den größten Schlüsselbund der Welt. Ich sammle Schlüssel!"),
			S._say("hero", "Du bist eingebrochen? In ein Gefängnis? Das macht niemand."),
			S._say("maus", "Ich bin Pieps. Ich mache Sachen, die niemand macht. Darf ich mal den Bund sehen? Nur gucken!"),
			S._cam("close", 0, 1.4),
			S._narr("Der Kettenwart sollte ihn einsperren. Er hat seit hundert Jahren mit niemandem gesprochen. Er lässt ihn gucken."),
			S._say("maus", "Dreihundertundeins Schlüssel. Und der hier – Nummer null – der ist ja ganz neu! Wo ist Zelle null?"),
			S._say("hero", "… Es gibt keine Zelle null."),
			S._say("maus", "Jeder Schlüssel hat eine Tür. Das ist die erste Regel des Schlüsselsammelns. Die zweite: Die interessanteste Tür ist immer die, die keiner sucht."),
			S._cam("close", 0, 1.4),
			S._narr("Der Kettenwart nimmt den Schlüssel zurück. Er ist warm von der Hand des Diebes. Seit hundert Jahren hat ihn niemand außer ihm berührt."),
			S._say("hero", "Du kannst bleiben. Eine Nacht. In einer offenen Zelle. Nicht weil du verurteilt bist. Weil es draußen regnet."),
			S._say("maus", "Eine offene Zelle! Das ist ja wie ein Hotel! Mit Ketten-Deko!"),
			S._narr("In dieser Nacht schließt der Kettenwart eine Tür nicht ab. Zelle zwölf. Es fühlt sich falsch an. Und ein bisschen gut."),
		]},
		{"id": "kettenwart_2", "title": "Der letzte Gefangene", "arena": "hell_gate", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["vlad", 2.5, -1], ["maus", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der letzte Gefangene"},
			S._narr("Pieps bleibt. Er hilft bei der Nachtrunde und stellt Fragen. Zu viele Fragen. Eines Nachts klopft jemand von außen ans Tor. Der letzte Mann, der je aus Schwarzfels entkam."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("vlad", "Kerkermeister. Vor hundert Jahren saß ich in Zelle dreihundert. Ich bin durch das Fenster als Nebel entkommen. Du hast nie aufgehört, nach mir zu suchen, oder?"),
			S._say("hero", "Du bist der einzige, der je entkommen ist. Seitdem schließe ich jede Nacht zweimal ab."),
			S._say("vlad", "Wer bewacht den Wächter, Kettenwart? Niemand. Und genau das macht dir Angst. Ich bin zurückgekommen, um dir das zu sagen."),
			{"t": "choice", "text": "Was tut der Kettenwart?", "options": [
				{"label": "Vlad zuhören", "flag": "kettenwart_listened", "steps": [
					S._say("hero", "Warum bist du zurückgekommen? Ein Entflohener kehrt nicht zurück."),
					S._say("vlad", "Weil ich frei bin und du nicht. Das ist ungerecht. Und weil ich gelernt habe, dass man Gefängnisse von innen aufschließt. Wehr dich – ich will sehen, ob du noch kämpfen kannst.")]},
				{"label": "Vlad einsperren", "flag": "kettenwart_jailer", "steps": [
					S._say("hero", "Zelle dreihundert ist noch frei. Dein Urteil ist nicht verjährt."),
					S._say("vlad", "Dann komm und hol mich.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "vlad"], "goal": "KETTE GEGEN NEBEL!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "kettenwart_listened", "steps": [
				S._say("vlad", "Du hast nicht versucht, mich in die Zelle zu werfen. Du hast nur gekämpft. Vielleicht willst du gar keinen Gefangenen. Vielleicht willst du einen Freund."),
			], "else": [
				S._say("vlad", "Ketten, Kettenwart. Immer nur Ketten. Du hast so viele davon, dass du nicht merkst, an welcher du selbst hängst."),
			]},
			S._say("maus", "Wärter! Der Schlüssel Nummer null glüht! Er wird ganz heiß!"),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Der Schlüssel zieht. Nach unten. Durch den Boden, durch den Fels, bis dorthin, wo der größte Gefangene von allen im Eis steckt."),
		]},
		{"id": "kettenwart_3", "title": "Der König der Gefangenen", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lucifer", 3.0, -1], ["vlad", -4.0, 1], ["maus", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der König der Gefangenen"},
			S._narr("Am Grund der Hölle steckt ein König bis zur Brust im Eis. Er ist gefangen, seit es Gefangene gibt. Und er lächelt den Kettenwart an wie einen Kollegen."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lucifer", "Endlich. Ein richtiger Wärter. Ich biete dir das größte Gefängnis von allen: die ganze Hölle. Mit einem einzigen Schlüssel. Deinem."),
			S._say("lucifer", "Du wirst nie wieder zweifeln müssen. Du wirst jeden einsperren, der fällt. Für immer. Ist das nicht dein Traum?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Für immer abschließen. Jede Nacht. Ohne Ende."),
			S._say("lucifer", "Du bist der einzige Gefangene hier, Kettenwart. Das weißt du. Also kannst du auch gleich mein Wärter werden. Es ändert nichts."),
			S._say("hero", "Doch. Es ändert, wer den Schlüssel hält. Und den letzten Schlüssel behalte ich. Für eine Tür, die ich selbst aufmachen werde."),
			S._music("boss"),
			{"t": "branch", "flag": "kettenwart_listened", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("vlad", "Ich bin aus deinem Turm entkommen. Jetzt helfe ich dir, aus seinem zu entkommen. Das nennt man Ironie, glaube ich."),
				{"t": "fight", "cast": ["hero", "vlad", "lucifer"], "goal": "VERWEIGERE DEN SCHLÜSSEL ZUR HÖLLE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("maus", "Ich bin dem Schlüssel nachgerutscht! Den ganzen Weg! Ich lasse meinen Wärter doch nicht allein!"),
				{"t": "fight", "cast": ["hero", "maus", "lucifer"], "goal": "VERWEIGERE DEN SCHLÜSSEL ZUR HÖLLE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Luzifer sinkt zurück ins Eis. Er lächelt immer noch. Aber zum ersten Mal hat jemand ein Gefängnis abgelehnt, das ihm angeboten wurde."),
		]},
		{"id": "kettenwart_4", "title": "Zelle null", "arena": "bg_ruined_city", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["zelle", 2.0, -1], ["maus", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Zelle null"},
			S._narr("Ganz unten im Turm, hinter dem Wachraum, ist eine Tür ohne Nummer. Der Kettenwart hat sie hundert Jahre lang übersehen. Er hat jeden Abend davor gesessen."),
			S._cam("two", 0, 1.6, 2),
			S._say("maus", "Das ist sie, oder? Zelle null. Das ist ja … das ist dein Wachraum. Du hast die ganze Zeit in Zelle null gewohnt."),
			S._say("hero", "Ich wurde verurteilt, Pieps. Vor hundert Jahren. Weil ich einen Gefangenen habe entkommen lassen. Man machte mich zum Wärter. Als Strafe. Für immer."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("zelle", "Und du hast das Urteil vollstreckt. Jede Nacht. Ohne Richter. Bleib. Draußen weißt du nicht, wer du bist."),
			S._say("hero", "Drinnen weiß ich es auch nicht. Ich weiß nur, wie man abschließt."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "zelle"], "goal": "SCHLIESS DEINE ZELLE AUF!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 1.0),
			S._narr("Der Kettenwart steckt den Schlüssel Nummer null ins Schloss. Er dreht. Nichts. Er drückt gegen die Tür. Sie geht auf. Sie war nie verschlossen."),
			S._say("hero", "Hundert Jahre. Und sie war offen."),
			S._cam("two", 0, 1.6, 2),
			S._say("maus", "Darf ich den Schlüsselbund haben? Jetzt, wo du ihn nicht mehr brauchst?"),
			S._say("hero", "Alle bis auf einen. Nummer null behalte ich. Damit ich nie vergesse, dass man drücken muss, nicht nur schließen."),
			S._narr("Am Morgen öffnet der Kettenwart alle dreihundert Zellen. Die Geister ziehen hinaus, einer nach dem anderen, ins Licht. Er sieht ihnen nach. Dann geht er selbst."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Kettenwart · Der letzte Schlüssel"},
			S._narr("Relikt erhalten: Der rostige Zellenschlüssel  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
