extends RefCounted
## Legende: FROSTWYRM – „Wer hat gerufen?“.
## Der Frostwyrm schlief tausend Jahre unter dem Eis. Er erwachte, als jemand seinen Namen rief –
## und niemand war da. Der Silberwyrm Albion hält ihn für eine vergessene Legende, Luzifer friert ihn
## tiefer ein als je zuvor, und am Ende findet er die Stimme, die ihn geweckt hat.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Wer hat gerufen?",
	"summary": "Tausend Jahre schlief der Frostwyrm unter dem Eis. Dann rief jemand seinen Namen, und er erwachte. Doch als er die Augen öffnete, war niemand da.",
	"relic": "Die Kinderzeichnung",
	"relic_text": "Ein blauer Drache mit Wachsmalstift auf Packpapier. Unten steht in krummen Buchstaben: FROSTI. Das schönste Bild, das je von ihm gemalt wurde.",
}

const CAST := {
	"hero": {"preset": "frostwyrm", "name": "FROSTWYRM", "title": "Der Frost-Wyrm", "color": "38bdf8"},
	"albion": {"preset": "albion", "name": "ALBION", "title": "Der Silberwyrm", "color": "e2e8f0"},
	"ida": {"preset": "lepora", "name": "IDA", "title": "Ein Mädchen mit Wachsmalstiften", "color": "fde68a"},
	"miner": {"preset": "warrok_brute", "name": "EISBRECHER", "title": "Gräbt nach dem Herzkristall", "color": "a8a29e"},
	"miner2": {"preset": "cyborg_mech", "name": "BOHRMASCHINE", "title": "Gräbt nach dem Herzkristall", "color": "94a3b8"},
	"lucifer": {"boss": "lucifer", "name": "LUZIFER", "title": "Der König im Eis", "color": "e0e7ff"},
	"schlaf": {"preset": "frostwyrm", "name": "DER TAUSENDJÄHRIGE SCHLAF", "title": "Wo nichts wehtut", "color": "1e3a8a"},
}

static func chapters() -> Array:
	return [
		{"id": "frostwyrm_1", "title": "Erwachen", "arena": "frozen_summit", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["miner", 2.8, -1], ["miner2", 4.0, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "FROSTWYRM · WER HAT GERUFEN?", "sub": "Kapitel I – Erwachen"},
			S._narr("Tausend Jahre schlief der Frostwyrm unter dem Gletscher. Er träumte von nichts. Das war schön."),
			S._narr("Dann, in einer klaren Winternacht, rief jemand seinen Namen. Nicht laut. Aber deutlich. Er öffnete die Augen – und das Eis über ihm zersprang."),
			S._cam("close", 0, 1.6),
			S._pose(0, "Roar", 1.0),
			S._say("hero", "Wer … hat … gerufen?"),
			S._narr("Niemand antwortet. Nur der Wind. Und, weiter unten, das Kreischen von Bohrern."),
			{"t": "appear", "who": 1}, {"t": "appear", "who": 2},
			S._cam("two", 0, 1.4, 1),
			S._say("miner", "Der Gletscher ist aufgebrochen! Darunter muss der Herzkristall liegen – alle Legenden sagen das!"),
			S._say("miner2", "Messung: großes Lebewesen. Sehr groß. Empfehlung: Rückzug."),
			S._say("miner", "Unsinn! Drachen gibt es nur in Märchen. Bohr weiter!"),
			S._say("hero", "Ihr habt gerufen? Nein. Ihr klingt nicht wie die Stimme. Ihr klingt wie Lärm."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "GLETSCHERATEM!", "flag": "frostwyrm_breath",
				"success": [S._narr("Ein Atemstoß, und die Bohrer frieren mitten in der Drehung ein.")],
				"fail": [S._narr("Tausend Jahre Schlaf. Der erste Atem ist nur ein Husten aus Schnee.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "miner", "miner2"], "goal": "VERTREIBE DIE EISBRECHER!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "frostwyrm_breath", "ai": 3},
			S._music("sad"),
			S._cam("close", 0, 1.4),
			S._narr("Die Gräber fliehen. Der Wyrm sieht ihnen nach. Sie hatten Angst vor ihm. Das ist das Erste, was er in der neuen Welt lernt."),
			S._say("hero", "Jemand hat meinen Namen gerufen. Ich werde ihn finden."),
			S._cam("sky", 0, 2.0),
			S._narr("Er fliegt über das Tal. Wo früher ein Dorf aus Holz stand, steht eine Stadt aus Glas. Tausend Jahre. Er kennt nichts mehr."),
			S._say("hero", "Die Wälder sind weg. Die Burgen auch. Und die Lieder, in denen ich vorkam – singt die noch jemand?"),
			S._narr("Unten in der Stadt zeigen Menschen auf ihn und rennen. Ein Kind bleibt stehen und winkt. Er sieht es nicht. Er ist zu hoch."),
		]},
		{"id": "frostwyrm_2", "title": "Die vergessene Legende", "arena": "bg_aurora_peaks", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["albion", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die vergessene Legende"},
			S._narr("Der Wyrm fliegt von Gipfel zu Gipfel und lauscht. Unter dem Polarlicht landet ein zweiter Drache neben ihm. Silbern, schlank, ein Gesicht voller Narben."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("albion", "Ein Frostwyrm. Ich dachte, eure Art ist ausgestorben. Die Menschen erzählen eure Geschichten nicht mehr."),
			S._say("hero", "Jemand hat meinen Namen gerufen. Weißt du wer?"),
			S._say("albion", "Wer soll dich gerufen haben, Eiswurm? Du bist eine Legende, die keiner mehr erzählt. Niemand kennt deinen Namen."),
			{"t": "choice", "text": "Was antwortet der Frostwyrm?", "options": [
				{"label": "Zornig werden", "flag": "frostwyrm_angry", "steps": [
					S._say("hero", "Du lügst. Ich habe es gehört. Und ich friere jeden ein, der mir etwas anderes erzählt!"),
					S._say("albion", "Zorn passt nicht zu dir. Aber gut. Zeig, ob du mehr bist als ein Märchen.")]},
				{"label": "Zuhören", "flag": "frostwyrm_listen", "steps": [
					S._say("hero", "Vielleicht hast du recht. Aber du hast auch Narben, Silberwyrm. Wer hat dich vergessen?"),
					S._say("albion", "… Mehr Leute, als ich zählen will. Gut. Kämpf mit mir. Unter Drachen redet man so.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "albion"], "goal": "DRACHE GEGEN DRACHE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "frostwyrm_listen", "steps": [
				S._say("albion", "Du kämpfst wie einer, der etwas sucht, nicht wie einer, der etwas verteidigt. Ich helfe dir suchen, wenn du willst."),
			], "else": [
				S._say("albion", "Viel Kraft. Wenig Richtung. Pass auf, Eiswurm – Zorn friert man nicht so leicht ein wie Wasser."),
			]},
			{"t": "fx", "kind": "shake"},
			S._narr("Unter dem Gletscher grollt es. Eine Stimme, kalt wie der Grund der Welt, ruft seinen Namen. Diesmal klingt sie falsch."),
			S._say("hero", "Das ist sie nicht. Das ist eine Lüge mit meinem Namen darin."),
		]},
		{"id": "frostwyrm_3", "title": "Der König im Eis", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lucifer", 3.0, -1], ["albion", -4.0, 1], ["ida", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der König im Eis"},
			S._narr("Der falsche Ruf zieht ihn hinab, durch Spalten und Seen, bis zum tiefsten Eis der Welt. Dort steckt ein König bis zur Brust im See und lächelt."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lucifer", "Bruder des Eises. Ich war es, der dich gerufen hat. Wer sonst? Oben erinnert sich niemand an dich."),
			S._say("lucifer", "Bleib hier unten. Leg dich zu mir ins Eis. Hier tut nichts weh, und niemand vergisst dich, weil niemand dich je kannte."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Deine Stimme … sie ist kalt. Die Stimme, die mich geweckt hat, war warm. Ganz klein und warm."),
			S._say("lucifer", "Niemand hat gerufen. Du hast es dir eingebildet. Ein Wurm, der träumt, wichtig zu sein."),
			S._say("hero", "Dann träume ich weiter. Aber nicht hier unten."),
			S._music("boss"),
			{"t": "branch", "flag": "frostwyrm_listen", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("albion", "Ich habe gesagt, ich helfe dir suchen. Das gilt auch für Höllen."),
				{"t": "fight", "cast": ["hero", "albion", "lucifer"], "goal": "BRICH AUS DEM TIEFSTEN EIS!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "fight", "cast": ["hero", "lucifer"], "goal": "BRICH AUS DEM TIEFSTEN EIS!", "lives": [3, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Der See bricht. Luzifer versinkt wieder bis zum Hals. Und von ganz weit oben, durch tausend Schichten Eis, hört der Wyrm ein Geräusch: ein Kind, das singt."),
		]},
		{"id": "frostwyrm_4", "title": "Frosti", "arena": "frozen_summit", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schlaf", 2.0, -1], ["ida", -3.5, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Frosti"},
			S._narr("Der Wyrm kehrt zum Gletscher zurück. Er ist müde. Die Kälte in ihm ist schwer, und das Eis lockt mit dem alten Schlaf."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schlaf", "Leg dich hin. Tausend Jahre noch. Dann ist alles, was dich vergessen hat, selbst vergessen. Kein Ruf. Keine Suche. Nur Ruhe."),
			S._say("hero", "Ich habe ein Lied gehört. Ganz oben."),
			S._say("schlaf", "Lieder hören auf. Schlaf nicht."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schlaf"], "goal": "BLEIB WACH!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -0.2, "time": 1.2},
			S._cam("two", 0, 1.6, 2),
			S._narr("Ein kleines Mädchen stapft durch den Schnee, eine Rolle Packpapier unter dem Arm. Sie bleibt stehen. Sie hat keine Angst."),
			S._say("ida", "FROSTI! Ich wusste es! Ich habe dich gemalt und deinen Namen gerufen, ganz laut, und dann hat der Berg gekracht!"),
			S._say("hero", "Du … hast mich gerufen? Du kennst mich?"),
			S._say("ida", "Aus Omas Buch! Da bist du drin, ganz hinten. Keiner liest die hinteren Seiten. Nur ich."),
			S._cam("close", 0, 1.6),
			S._narr("Sie rollt das Papier aus. Ein blauer Drache, krumm, mit zu vielen Zähnen und einem Lächeln. Darunter: FROSTI."),
			S._say("hero", "Tausend Jahre habe ich geschlafen. Und eine einzige kleine Stimme hat gereicht."),
			S._say("ida", "Darf ich dich Frosti nennen? Oder ist das unhöflich bei einem Drachen?"),
			S._say("hero", "Niemand hat mich je so genannt. … Ja. Du darfst."),
			S._say("ida", "Dann schreibe ich ein neues Kapitel für Omas Buch. Ganz vorne. Damit alle es lesen."),
			S._narr("Der Frostwyrm legt sich in den Schnee neben das Mädchen. Sie malt. Er hält still. Zum ersten Mal seit tausend Jahren ist er wach – und will es bleiben."),
			S._narr("Seitdem fällt im Tal jeden Winter ein besonders schöner Schnee. Die Kinder sagen, das ist Frosti, der Hallo sagt."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Frostwyrm · Wer hat gerufen?"},
			S._narr("Relikt erhalten: Die Kinderzeichnung  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
