extends RefCounted
## Legende: JUBEI, DER WINDKLINGEN-WANDERER – „Die dritte Klinge“.
## Jubei trägt drei Klingen: eine für seinen Meister, eine für seinen Rivalen, eine für sich selbst.
## Die dritte hat er nie gezogen. Der Kommandant, der seinen Meister in jener Nacht verlor, Belphegor,
## der ihm einflüstert, die Klinge glänze in der Scheide am schönsten, und am Ende: er selbst.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die dritte Klinge",
	"summary": "Jubei kämpft mit zwei Klingen und trägt eine dritte, die er nie gezogen hat. Sie gehört ihm selbst – und er glaubt, er hat sie nicht verdient.",
	"relic": "Die stumpfe dritte Klinge",
	"relic_text": "Ein Schwert ohne Schneide. Es schneidet nichts – außer den Gedanken, man müsse erst würdig sein, bevor man anfängt.",
}

const CAST := {
	"hero": {"preset": "jubei", "name": "JUBEI", "title": "Der Windklingen-Wanderer", "color": "34d399"},
	"kommandant": {"preset": "samurai_dreyar", "name": "DER KOMMANDANT", "title": "Der Silberwolf", "color": "cbd5e1"},
	"hikaru": {"preset": "hikaru", "name": "HIKARU", "title": "Junger Glutklingen-Schüler", "color": "f97316"},
	"bandit": {"preset": "pirate_captain", "name": "STRASSENRÄUBERIN", "title": "Am Pass der Kiefern", "color": "94a3b8"},
	"belphegor": {"boss": "belphegor", "name": "BELPHEGOR", "title": "Die Trägheit", "color": "a3a3a3"},
	"dritte": {"preset": "jubei", "name": "DIE DRITTE KLINGE", "title": "Jubei, wie er sein könnte", "color": "ecfccb"},
}

static func chapters() -> Array:
	return [
		{"id": "jubei_1", "title": "Zwei Klingen am Pass", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["bandit", 3.0, -1], ["hikaru", -3.5, 1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "JUBEI · DIE DRITTE KLINGE", "sub": "Kapitel I – Zwei Klingen am Pass"},
			S._narr("Jubei trägt drei Klingen am Gürtel. Die erste schmiedete sein Meister. Die zweite gewann er von einem Rivalen. Die dritte hat er selbst geschmiedet – und nie gezogen."),
			S._narr("Er wandert seit zwölf Jahren. Sein Meister starb in einer Nacht, in der Jubei hätte da sein sollen. Er war es nicht."),
			S._cam("two", 0, 1.4, 1),
			S._say("bandit", "Drei Schwerter für einen Mann? Das ist eins zu viel. Gib mir das in der Mitte, das sieht neu aus."),
			S._say("hero", "Das in der Mitte ist das einzige, das ich dir nicht gebe. Die anderen zwei reichen für dich."),
			{"t": "qte", "kind": "sequence", "keys": ["standard", "special"], "time": 1.0, "text": "ZWEI KLINGEN!", "flag": "jubei_draw",
				"success": [S._narr("Zwei Klingen verlassen die Scheide in einem einzigen Laut. Der Wind dreht sich.")],
				"fail": [S._narr("Die zweite Klinge hakt. Jubei flucht leise.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "bandit"], "goal": "SÄUBERE DEN PASS!", "lives": [3, 2], "qte": "jubei_draw", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.8, "time": 0.8},
			S._cam("two", 0, 1.6, 2),
			S._say("hikaru", "Meister! Ich habe alles gesehen! Bitte nehmt mich als Schüler! Ich kann schon die erste Form!"),
			S._say("hero", "Ich bin kein Meister. Meister ziehen alle ihre Klingen."),
			S._say("hikaru", "Warum zieht Ihr die dritte nicht?"),
			S._cam("close", 0, 1.4),
			S._narr("Niemand hatte das je gefragt. Jubei antwortet nicht. Aber er schickt den Jungen auch nicht weg."),
			S._say("hikaru", "Ich heiße Hikaru. Ich koche gut, ich trage Gepäck und ich rede nur, wenn es wichtig ist."),
			S._say("hero", "Du hast in den letzten drei Minuten elfmal geredet."),
			S._say("hikaru", "Es war alles wichtig!"),
			S._narr("Jubei geht weiter den Pass hinauf. Hinter ihm stapft ein Junge mit zu großem Rucksack. Er dreht sich nicht um. Aber er geht ein bisschen langsamer."),
		]},
		{"id": "jubei_2", "title": "Der Silberwolf", "arena": "bg_dojo", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["kommandant", 2.5, -1], ["hikaru", -3.5, 1]]),
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Silberwolf"},
			S._narr("Im alten Dojo seines Meisters wartet jemand. Silberne Rüstung, ein Wolf auf dem Helm. Der Kommandant – der Mann, der in jener Nacht dort war, wo Jubei hätte sein sollen."),
			S._cam("two", 0, 1.6, 1),
			S._say("kommandant", "Zwölf Jahre, Jubei. Dein Meister fragte in seiner letzten Stunde nach dir. Ich musste ihm sagen, dass du nicht kommst."),
			S._say("hero", "Ich weiß, was ich getan habe. Ich trage es an meinem Gürtel."),
			S._say("kommandant", "Du trägst ein Schwert, das du nie ziehst. Das ist keine Buße. Das ist Feigheit mit Scheide."),
			S._say("hikaru", "Sagt so etwas nicht! Er hat mich am Pass gerettet!"),
			{"t": "choice", "text": "Wie antwortet Jubei?", "options": [
				{"label": "Die Wahrheit sagen", "flag": "jubei_truth", "steps": [
					S._say("hero", "Ich war in jener Nacht in einer Schenke. Ich habe getrunken, weil ich dachte, ich sei schon gut genug. Das ist die ganze Wahrheit."),
					S._say("kommandant", "Endlich. Zwölf Jahre habe ich darauf gewartet. Jetzt zeig mir, was du seitdem gelernt hast.")]},
				{"label": "Schweigen", "flag": "jubei_silent", "steps": [
					S._narr("Jubei sagt nichts. Er zieht zwei Klingen. Das muss reichen."),
					S._say("kommandant", "Dann reden die Schwerter. Wie immer bei dir.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "kommandant"], "goal": "DUELL MIT DEM SILBERWOLF!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "jubei_truth", "steps": [
				S._say("kommandant", "Du kämpfst besser als damals. Und ehrlicher. Dein Meister hätte das gern gesehen."),
				S._say("hero", "Er sieht es nicht. Das ist der Punkt."),
			], "else": [
				S._say("kommandant", "Gut gekämpft. Schlecht geschwiegen. Irgendwann wird dir das Schweigen schwerer als jede Klinge."),
			]},
			{"t": "fx", "kind": "shake"},
			S._narr("Der Boden des Dojos wird weich wie Moos. Eine schläfrige Stimme gähnt aus der Tiefe."),
			S._say("hikaru", "Meister Jubei – der Boden! Er zieht Euch hinunter!"),
		]},
		{"id": "jubei_3", "title": "Der weiche Abgrund", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["belphegor", 3.0, -1], ["hikaru", -4.0, 1], ["kommandant", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der weiche Abgrund"},
			S._narr("Jubei erwacht auf weichem Eis, umgeben von schlafenden Kriegern. Sie haben alle eine Hand am Schwert. Keiner hat es je gezogen."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("belphegor", "Willkommen, Wanderer. Ruh dich aus. Warum kämpfen, wenn die Klinge in der Scheide so schön glänzt?"),
			S._say("belphegor", "Du hast die dritte nie gezogen. Ich bewundere das. Wer nie anfängt, kann nie versagen."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Wer nie anfängt … kann nie versagen."),
			S._say("belphegor", "Siehst du? Wir verstehen uns. Leg dich hin. Die anderen hier schlafen seit Jahrhunderten. Sie haben nie verloren."),
			S._say("hero", "Sie haben nie verloren, weil sie nie gekämpft haben. Ich habe schon einmal geschlafen, als es wichtig war. Nie wieder."),
			S._music("boss"),
			{"t": "branch", "flag": "jubei_truth", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("kommandant", "Diesmal bin ich da, wo ich sein soll. Neben dir, Wanderer."),
				{"t": "fight", "cast": ["hero", "kommandant", "belphegor"], "goal": "ERWACHE AUS DER TRÄGHEIT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("hikaru", "Ich bin hinterhergesprungen! Ein Schüler lässt seinen Meister nicht allein schlafen!"),
				{"t": "fight", "cast": ["hero", "hikaru", "belphegor"], "goal": "ERWACHE AUS DER TRÄGHEIT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Belphegor gähnt ein letztes Mal und versinkt in seinem eigenen weichen Eis. Um Jubei herum öffnen die schlafenden Krieger, einer nach dem anderen, die Augen."),
			S._say("hero", "Steht auf. Alle. Eure Klingen glänzen schön genug. Jetzt zeigt, ob sie auch schneiden."),
			S._narr("Und sie stehen auf. Hundert Krieger, die nie gekämpft haben, ziehen zum ersten Mal ihre Schwerter. Nicht gegeneinander. Einfach, um zu sehen, wie es ist."),
			S._say("hero", "Zwei Klingen schneiden. Die dritte entscheidet. Es ist Zeit, dass ich mich entscheide."),
		]},
		{"id": "jubei_4", "title": "Ziehen", "arena": "bg_moon_temple", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["dritte", 2.0, -1], ["hikaru", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Ziehen"},
			S._narr("Im Mondtempel, an dem Grab seines Meisters, legt Jubei die drei Klingen nebeneinander auf den Stein."),
			S._cam("two", 0, 1.6, 2),
			S._say("hikaru", "Ihr wollt sie ziehen. Ich sehe es an Euren Händen."),
			S._say("hero", "Ich habe Angst, dass sie nichts taugt. Dass ich nichts tauge. Solange sie in der Scheide ist, kann sie alles sein."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("dritte", "Ich bin die Klinge, die du nie gezogen hast. Ich bin alles, was du hättest werden können. Besieg mich – wenn du dich traust."),
			S._say("hero", "Ich traue mich nicht. Ich mache es trotzdem."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "dritte"], "goal": "BESIEGE DIE DRITTE KLINGE!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Charge", 1.0),
			S._narr("Jubei zieht die dritte Klinge. Sie ist stumpf. Sie war es immer. Er hat sie damals als Junge geschmiedet und nie geschliffen."),
			S._say("hero", "Sie ist stumpf. Zwölf Jahre Angst vor einem stumpfen Schwert."),
			S._say("hikaru", "Dann schleifen wir sie. Zusammen. Ihr zeigt mir wie."),
			S._cam("two", 0, 1.6, 2),
			S._narr("Bis zum Morgengrauen sitzen Meister und Schüler am Grab und schleifen. Der Wind trägt das Geräusch über den Tempel – wie ein langes, ruhiges Ausatmen."),
			S._say("hero", "Sie wird nie so gut sein wie die anderen beiden."),
			S._say("hikaru", "Muss sie nicht. Sie muss nur Eure sein."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Jubei · Die dritte Klinge"},
			S._narr("Relikt erhalten: Die stumpfe dritte Klinge  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
