extends RefCounted
## Legende: SWAT-AGENT – „Feierabend“.
## Zwanzig Jahre, kein verlorener Einsatz, kein einziger Urlaubstag. Der Agent weiß nicht, wer er ohne
## Funkgerät ist. Seine Tochter wartet seit Jahren am Meer, Don Valente will ihn endlich loswerden,
## Virtus fragt, wen er eigentlich beschützt – und das Funkgerät will ihn nie wieder loslassen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Feierabend",
	"summary": "Der SWAT-Agent hat in zwanzig Jahren keinen Einsatz verloren und keinen einzigen Urlaubstag genommen. Seine Tochter hat aufgehört, ihn zu ihrem Geburtstag einzuladen.",
	"relic": "Die Muschel vom Strand",
	"relic_text": "Eine gewöhnliche Muschel mit einem Loch, aufgefädelt an einer Schnur. Ein Geschenk von seiner Tochter. Er trägt sie an der Stelle, wo früher das Funkgerät hing.",
}

const CAST := {
	"hero": {"preset": "swat_specops", "name": "SWAT-AGENT", "title": "Der Agent im Einsatz", "color": "64748b"},
	"vanguard": {"preset": "vanguard_soldier", "name": "VANGUARD", "title": "Der Soldat auf der Brücke", "color": "60a5fa"},
	"mia": {"preset": "lepora", "name": "MIA", "title": "Seine Tochter", "color": "fde68a"},
	"don": {"preset": "don_valente", "name": "DON VALENTE", "title": "Der Unterweltpate", "color": "d4af37"},
	"goon": {"preset": "pirate_captain", "name": "LEIBWÄCHTERIN", "title": "Familie Valente", "color": "57534e"},
	"virtus": {"boss": "virtus", "name": "VIRTUS", "title": "Engel der Kräfte", "color": "fde68a"},
	"funk": {"preset": "swat_specops", "name": "DAS FUNKGERÄT", "title": "Einsatz. Immer. Jetzt.", "color": "1f2937"},
}

static func chapters() -> Array:
	return [
		{"id": "swat_specops_1", "title": "Zugriff", "arena": "neon_metropolis", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["don", 3.2, -1], ["goon", 2.0, -1]]),
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "SWAT-AGENT · FEIERABEND", "sub": "Kapitel I – Zugriff"},
			S._narr("Zwanzig Jahre im Dienst. Vierhundertzwölf Einsätze. Kein einziger verloren. Kein einziger Urlaubstag. Das Funkgerät an seiner Schulter hat ihn nie schlafen lassen."),
			S._narr("Heute: die Lagerhalle von Don Valente. Zwanzig Jahre jagt er den Paten. Heute endet es."),
			S._cam("two", 0, 1.4, 2),
			S._say("don", "Der Agent. Pünktlich wie immer. Weißt du, was heute für ein Tag ist? Der Geburtstag deiner Tochter. Sie wird sechzehn."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 0.8),
			S._say("hero", "Woher wissen Sie das?"),
			S._say("don", "Ich weiß alles über die Menschen, die mich jagen. Du offenbar weniger über deine Familie. Erledige ihn, Bianca."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.2, "text": "DECKUNG!", "flag": "swat_specops_cover",
				"success": [S._narr("Der Schild fängt die Kugeln. Zwanzig Jahre Routine.")],
				"fail": [S._narr("Er ist eine halbe Sekunde zu spät. Zum ersten Mal in zwanzig Jahren. Wegen eines Geburtstags.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "goon"], "goal": "SCHALTE DIE LEIBWÄCHTERIN AUS!", "lives": [3, 2], "qte": "swat_specops_cover", "ai": 3},
			S._music("tense"),
			S._cam("two", 0, 1.6, 1),
			S._say("don", "Gut gekämpft. Aber ich bin schon weg, wie immer. Ruf deine Tochter an, Agent. Sie ist am Meer. Sie wartet seit drei Jahren dort an ihrem Geburtstag."),
			{"t": "move", "who": 1, "x": 10.0, "time": 1.0},
			S._narr("Das Funkgerät knackt: Einsatz an der Brücke. Ein Soldat verweigert die Räumung. Sofort ausrücken."),
			S._say("hero", "Verstanden. Bin unterwegs."),
			S._narr("Er sagt es, bevor er nachdenkt. Wie immer. Das Handy in seiner Tasche bleibt dunkel."),
			S._cam("close", 0, 1.4),
			S._narr("Im Einsatzwagen tippt er eine Nachricht: Alles Gute zum Sechzehnten. Er löscht sie. Er tippt sie noch einmal. Er schickt sie nicht."),
			S._say("hero", "Nach dem Einsatz. Nach diesem einen noch. Dann rufe ich an."),
			S._narr("Das hat er auch letztes Jahr gesagt. Und das Jahr davor."),
		]},
		{"id": "swat_specops_2", "title": "Der Mann auf der Brücke", "arena": "bg_ruined_city", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["vanguard", 2.5, -1]]),
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Mann auf der Brücke"},
			S._narr("An der alten Brücke steht ein Soldat in verbeulter Rüstung, der seit sieben Jahren auf Befehle wartet. Der Agent hat ihn schon einmal räumen wollen."),
			S._cam("two", 0, 1.6, 1),
			S._say("vanguard", "Agent. Sie schon wieder. Haben Sie inzwischen einen gültigen Befehl?"),
			S._say("hero", "Ich habe denselben wie letztes Mal. Formular 27-B. Du musst hier weg."),
			S._say("vanguard", "Darf ich etwas fragen? Wann hatten Sie Ihren letzten freien Tag?"),
			S._cam("close", 0, 1.4),
			S._narr("Der Agent öffnet den Mund. Er findet keine Antwort. Er rechnet nach. Neunzehn Jahre? Zwanzig?"),
			{"t": "choice", "text": "Was antwortet der Agent?", "options": [
				{"label": "Die Wahrheit", "flag": "swat_specops_mirror", "steps": [
					S._say("hero", "Ich weiß es nicht. Ich glaube, ich habe nie einen gehabt."),
					S._say("vanguard", "Dann sind wir gleich. Wir warten beide auf einen Befehl, der uns erlaubt aufzuhören. Kämpfen wir trotzdem? Aus Gewohnheit?")]},
				{"label": "Den Befehl ausführen", "flag": "swat_specops_duty", "steps": [
					S._say("hero", "Das tut nichts zur Sache. Zugriff."),
					S._say("vanguard", "Feindkontakt. Stellung wird verteidigt.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "vanguard"], "goal": "RÄUME DIE BRÜCKE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "swat_specops_mirror", "steps": [
				S._say("vanguard", "Sie kämpfen wie ich. Perfekt. Und völlig leer. Gehen Sie zu Ihrer Tochter, Agent. Ich bleibe noch. Einer von uns sollte es lernen."),
			], "else": [
				S._say("vanguard", "Sie haben gewonnen. Ich gehe. Aber wer räumt Sie, Agent? Wer sagt Ihnen, dass Ihr Krieg vorbei ist?"),
			]},
			{"t": "fx", "kind": "flash"},
			S._narr("Das Funkgerät knackt. Eine Stimme, die er noch nie gehört hat: Einsatz. Sphäre der Kräfte. Höchste Priorität."),
		]},
		{"id": "swat_specops_3", "title": "Wen beschützt du?", "arena": "heaven_spheres", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["virtus", 3.0, -1], ["vanguard", -4.0, 1], ["mia", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Wen beschützt du?"},
			S._narr("Der Einsatzort liegt über den Wolken. Er fragt nicht, wie er dorthin kommt. Er fragt nie."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("virtus", "Agent. Ich bin die Kraft, die Dinge bewegt. Ich habe dich hergerufen, weil du dich nicht mehr selbst bewegst. Nur noch das Funkgerät bewegt dich."),
			S._say("virtus", "Eine Frage: Wen beschützt du eigentlich, wenn du nie zu Hause bist?"),
			S._cam("close", 0, 1.4),
			S._say("hero", "Die Stadt. Die Leute. Alle."),
			S._say("virtus", "Alle außer einer. Sie steht jedes Jahr am Strand. Sie hat aufgehört zu weinen. Das ist schlimmer."),
			S._say("hero", "Hör auf. Das ist kein Einsatzthema."),
			S._say("virtus", "Ohne Einsatz bist du gar nichts – das glaubst du. Beweise das Gegenteil."),
			S._music("boss"),
			{"t": "branch", "flag": "swat_specops_mirror", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("vanguard", "Diesmal habe ich keinen Befehl gebraucht, Agent. Ich bin einfach gekommen. Fühlt sich seltsam an. Gut seltsam."),
				{"t": "fight", "cast": ["hero", "vanguard", "virtus"], "goal": "BEANTWORTE DIE FRAGE DES ENGELS!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "fight", "cast": ["hero", "virtus"], "goal": "BEANTWORTE DIE FRAGE DES ENGELS!", "lives": [3, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._say("virtus", "Du hast gekämpft wie immer. Jetzt geh und tu etwas, was du noch nie getan hast."),
			S._say("hero", "Was denn?"),
			S._say("virtus", "Komm zu spät. Zu einem Einsatz. Absichtlich. Und sei pünktlich bei ihr."),
			S._cam("close", 0, 1.4),
			S._narr("Der Agent nimmt das Handy aus der Tasche. Er wählt. Es klingelt einmal. Zweimal. Dann legt er auf, bevor jemand abnimmt."),
			S._say("hero", "Nicht am Telefon. Das hat sie nicht verdient. Ich fahre hin."),
		]},
		{"id": "swat_specops_4", "title": "Feierabend", "arena": "pirate_galleon", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["funk", 2.0, -1], ["mia", 4.5, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Feierabend"},
			S._narr("Der Hafen am Meer. Ein altes Schiff liegt an der Mole. Dahinter der Strand. Der Agent hat sich noch nie so unsicher gefühlt, nicht einmal unter Beschuss."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("funk", "Einsatz. Banküberfall in der Innenstadt. Sofort ausrücken. Du bist der Beste. Ohne dich scheitern sie."),
			S._say("hero", "Dann scheitern sie eben einmal. Es gibt andere Agenten."),
			S._say("funk", "Es gibt keinen wie dich. Ohne mich bist du nur ein Mann am Strand. Was willst du da? Muscheln suchen?"),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "funk"], "goal": "SCHALTE DAS FUNKGERÄT AB!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._narr("Er dreht den Knopf. Das Funkgerät verstummt. Zum ersten Mal seit zwanzig Jahren ist es still in seinem Ohr. Er hört das Meer."),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("mia", "Papa? Du bist … gekommen? Es ist nicht mal ein Notfall."),
			S._say("hero", "Doch. Der größte, den ich je hatte. Ich habe ihn nur zwanzig Jahre lang nicht gemeldet."),
			S._narr("Sie geben sich nicht die Hand, sie umarmen sich nicht, nicht sofort. Sie suchen einfach zusammen Muscheln. Er findet eine mit einem Loch. Sie fädelt sie auf."),
			S._say("mia", "Für deine Schulter. Da, wo das Funkgerät war."),
			S._say("hero", "Mia. Ich habe drei Geburtstage verpasst. Ich weiß nicht, wie ich das gutmachen soll."),
			S._say("mia", "Gar nicht. Man kann es nicht gutmachen. Aber du kannst nächstes Jahr wiederkommen. Und das Jahr danach."),
			S._say("hero", "Ich habe Urlaub eingereicht. Zwanzig Jahre Resturlaub. Die Personalabteilung ist in Ohnmacht gefallen."),
			S._narr("Mia lacht. Es klingt wie damals, als sie vier war. Er hatte vergessen, wie es klingt."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "SWAT-Agent · Feierabend"},
			S._narr("Relikt erhalten: Die Muschel vom Strand  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
