extends RefCounted
## Legende: VLAD, DER VAMPIRFÜRST – „Der Morgen“.
## Vlad lebt seit sechshundert Jahren und hat jeden überlebt, den er je geliebt hat. Ravenna, das
## Phantom ohne Spiegelbild, ist die Einzige, die ihn durchschaut. Lilith, seine Schöpferin, ruft ihn
## für weitere sechshundert Jahre zurück – und Vlad will nur ein einziges Mal die Sonne sehen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der Morgen",
	"summary": "Sechshundert Jahre lebt Vlad schon, und er hat jeden überlebt, den er je geliebt hat. Er fürchtet nicht den Tod. Er fürchtet den nächsten Abschied.",
	"relic": "Das Buntglasfenster",
	"relic_text": "Eine kleine Scheibe aus rotem und goldenem Glas. Wer hindurchsieht, sieht einen Sonnenaufgang – egal, wie spät es ist.",
}

const CAST := {
	"hero": {"preset": "vampire_lord", "name": "VLAD", "title": "Der Vampirfürst", "color": "991b1b"},
	"ravenna": {"preset": "specter", "name": "RAVENNA", "title": "Das Phantom ohne Spiegelbild", "color": "6366f1"},
	"elena": {"preset": "sorceress_medea", "name": "ELENA", "title": "Glasmacherin im Dorf", "color": "fde68a"},
	"hunter": {"preset": "steel_knight", "name": "VAMPIRJÄGER", "title": "Orden des Pfahls", "color": "cbd5e1"},
	"hunter2": {"preset": "swat_specops", "name": "VAMPIRJÄGERIN", "title": "Orden des Pfahls", "color": "cbd5e1"},
	"lilith": {"boss": "lilith", "name": "LILITH", "title": "Seine Schöpferin", "color": "e11d48"},
	"nacht": {"preset": "vampire_lord", "name": "DIE EWIGE NACHT", "title": "Vlad in sechshundert Jahren", "color": "1c1917"},
}

static func chapters() -> Array:
	return [
		{"id": "vampire_lord_1", "title": "Sechshundert Winter", "arena": "blood_moon", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["hunter", 2.8, -1], ["hunter2", 4.0, -1], ["elena", -3.5, 1]]),
			{"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "VLAD · DER MORGEN", "sub": "Kapitel I – Sechshundert Winter"},
			S._narr("Seit sechshundert Jahren steht das Schloss unter dem Blutmond. Seit sechshundert Jahren hat sein Fürst keinen Sonnenaufgang gesehen."),
			S._narr("Er hatte Freunde. Eine Frau. Einen Sohn. Er hat sie alle begraben. Jeden einzelnen. Seitdem lässt er niemanden mehr bleiben."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Die Nacht ist jung. Ich bin es nicht."),
			S._cam("two", 0, 1.4, 1),
			S._say("hunter", "Fürst der Nacht. Der Orden des Pfahls ist gekommen. Sechshundert Jahre sind genug."),
			S._say("hero", "Da sind wir uns ausnahmsweise einig. Aber nicht durch euch."),
			S._say("hunter2", "Er spielt mit uns. Pfähle bereit!"),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "KARMESIN-NEBEL!", "flag": "vampire_lord_mist",
				"success": [S._narr("Vlad zerfällt in roten Nebel und Fledermausschatten. Die Pfähle stechen ins Leere.")],
				"fail": [S._narr("Der Nebel kommt einen Herzschlag zu spät. Ein Pfahl streift seinen Mantel.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "hunter", "hunter2"], "goal": "VERTREIBE DEN ORDEN DES PFAHLS!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "vampire_lord_mist", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("elena", "Fürst? Ich bin Elena, die Glasmacherin aus dem Dorf. Die Jäger haben bei uns gewohnt. Ich wollte Sie warnen. Ich war zu spät."),
			S._say("hero", "Du warnst einen Vampir? Bist du lebensmüde, Mädchen?"),
			S._say("elena", "Nein. Aber Sie haben meinem Großvater einmal das Leben gerettet. In einem Winter, als die Wölfe kamen. Er hat es nie vergessen."),
			S._cam("close", 0, 1.4),
			S._narr("Vlad erinnert sich. Ein Junge im Schnee, vor siebzig Jahren. Er hat ihn vergessen wollen. Wie alle."),
			S._say("hero", "Geh nach Hause. Und komm nicht wieder. Wer bei mir bleibt, den begrabe ich irgendwann."),
		]},
		{"id": "vampire_lord_2", "title": "Kein Spiegelbild", "arena": "bg_night_market", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["ravenna", 2.5, -1], ["elena", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Kein Spiegelbild"},
			S._narr("Elena kommt trotzdem wieder. Jede Woche. Sie bringt Glasscherben mit, bunt wie Sonnenlicht. Vlad schickt sie weg. Sie kommt wieder."),
			S._narr("Auf dem Nachtmarkt, zwischen Lampions, wartet eine Gestalt, die in keinem Schaufenster einen Spiegel wirft. Wie er."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("ravenna", "Sechshundert Jahre, Vlad – und du hast immer noch Angst vor dem Morgen. Ich sehe es. Wir beide haben kein Spiegelbild. Wir sehen nur einander."),
			S._say("hero", "Was willst du, Phantom?"),
			S._say("ravenna", "Das Mädchen. Du lässt sie kommen, obwohl du sie wegschickst. Das wird wehtun. Ihr oder dir. Ich will wissen, wem."),
			{"t": "choice", "text": "Was tut Vlad?", "options": [
				{"label": "Elena wegschicken", "flag": "vampire_lord_alone", "steps": [
					S._say("hero", "Elena. Geh. Diesmal meine ich es. Komm nie wieder."),
					S._say("elena", "Sie lügen schlecht, Fürst. Für jemanden, der so viel Übung hatte.")]},
				{"label": "Sie bleiben lassen", "flag": "vampire_lord_stay", "steps": [
					S._say("hero", "Sie bleibt, so lange sie will. Und wenn es wehtut, dann tut es weh."),
					S._say("ravenna", "Mutig. Dann zeig mir, ob du stark genug bist, sie zu schützen.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "ravenna"], "goal": "BLUT GEGEN LEERE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "vampire_lord_stay", "steps": [
				S._say("ravenna", "Du hast gekämpft wie einer, der etwas zu verlieren hat. Das habe ich bei dir seit dreihundert Jahren nicht gesehen."),
			], "else": [
				S._say("ravenna", "Du kämpfst gut. Und leer. Wie jemand, der schon alles verloren hat, bevor es angefangen hat."),
			]},
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Ein Duft von Rosen und Asche weht über den Markt. Vlad erkennt ihn. Nach sechshundert Jahren erkennt er ihn sofort."),
			S._say("hero", "Sie ruft. Meine Mutter in der Nacht. Die, die mich gemacht hat."),
		]},
		{"id": "vampire_lord_3", "title": "Die Schöpferin", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lilith", 3.0, -1], ["ravenna", -4.0, 1], ["elena", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Schöpferin"},
			S._narr("Hinter dem Höllentor ein Ballsaal aus Samt. Musik ohne Musiker. Und auf dem Thron die Frau, die ihm vor sechshundert Jahren das ewige Leben schenkte."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lilith", "Mein schönster Sohn. Sechshundert Jahre. Komm zurück an meine Seite. Für weitere sechshundert. Für immer."),
			S._say("lilith", "Die Kleine mit dem Glas? Sie wird alt, Vlad. Sie wird sterben. Wie alle. Und du wirst wieder allein am Grab stehen."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Ich weiß. Ich habe zweiundvierzig Gräber gesehen. Ich zähle sie jede Nacht."),
			S._say("lilith", "Dann hör auf zu zählen. Bei mir stirbt niemand. Bei mir lebt auch niemand. Es ist friedlich."),
			S._say("hero", "Du bist kein Frieden. Du bist ein Gefängnis in Samt. Und ich habe sechshundert Jahre darin gewohnt."),
			S._music("boss"),
			{"t": "branch", "flag": "vampire_lord_stay", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("elena", "Ich habe Glas mitgebracht. Spiegelglas. Mal sehen, ob die Dame ihr eigenes Gesicht aushält!"),
				{"t": "fight", "cast": ["hero", "elena", "lilith"], "goal": "BRICH AUS DEM GEFÄNGNIS AUS SAMT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("ravenna", "Kein Spiegelbild, kein Herr. Ich hatte auch einmal eine Schöpferin. Ich helfe dir, deine loszuwerden."),
				{"t": "fight", "cast": ["hero", "ravenna", "lilith"], "goal": "BRICH AUS DEM GEFÄNGNIS AUS SAMT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Der Ballsaal zerfällt zu Rosenblättern. Lilith bleibt zurück, allein auf ihrem Thron. Zum ersten Mal hat einer ihrer Söhne Nein gesagt."),
			S._say("lilith", "Du wirst zurückkommen, Vlad. Wenn das Mädchen tot ist. Wenn du wieder allein am Grab stehst. Dann kommst du."),
			S._say("hero", "Vielleicht. Aber bis dahin habe ich Jahre. Mit ihr. Das sind mehr als in den letzten sechshundert zusammen."),
			S._say("lilith", "Jahre. Was sind schon Jahre für einen wie dich?"),
			S._say("hero", "Alles. Ich habe es nur vergessen, weil ich zu viele davon hatte."),
			S._narr("Vlad dreht sich um und geht. Er sieht nicht zurück. Das hat er von den Sterblichen gelernt: Man sieht nach vorne, weil man nicht ewig Zeit hat."),
		]},
		{"id": "vampire_lord_4", "title": "Der Morgen", "arena": "bg_moon_temple", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["nacht", 2.0, -1], ["elena", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der Morgen"},
			S._narr("Im Mondtempel hat Elena ein Fenster eingesetzt. Rotes und goldenes Glas, so dick, dass die Sonne hindurchscheint, ohne zu brennen. Sie hat ein Jahr daran gearbeitet."),
			S._cam("two", 0, 1.6, 2),
			S._say("elena", "In einer Stunde geht die Sonne auf. Durch dieses Glas kann sie Ihnen nichts tun. Ich habe es berechnet. Zwölfmal."),
			S._say("hero", "Und wenn du dich verrechnet hast?"),
			S._say("elena", "Dann haben Sie wenigstens einmal etwas Schönes gesehen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("nacht", "Ich bin, was du in sechshundert Jahren sein wirst. Kalt. Allein. Sicher. Geh zurück in den Keller. Der Morgen bringt nur Abschied."),
			S._say("hero", "Jeder Morgen bringt Abschied. Von der Nacht. Ich habe sechshundert Jahre lang nicht losgelassen."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "nacht"], "goal": "BESIEGE DIE EWIGE NACHT!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 1.0),
			S._narr("Die Sonne geht auf. Rotes und goldenes Licht fällt durch das Glas auf Vlads Gesicht. Es brennt nicht. Es wärmt."),
			S._say("hero", "Ich hatte vergessen, dass Licht eine Farbe hat."),
			S._cam("two", 0, 1.6, 2),
			S._say("elena", "Ich werde alt, Fürst. Sie wissen das. Irgendwann stehen Sie an meinem Grab."),
			S._say("hero", "Ja. Und es wird wehtun. Aber bis dahin sehe ich jeden Morgen durch dein Fenster. Das ist es wert."),
			S._narr("Zweiundvierzig Gräber zählt Vlad jede Nacht. Seit diesem Morgen zählt er auch Sonnenaufgänge. Die Zahl wächst schneller."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Vlad · Der Morgen"},
			S._narr("Relikt erhalten: Das Buntglasfenster  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
