extends RefCounted
## Legende: TOBI, DIE FEDERFAUST – „Fünf Teller“.
## Ein Kapitän ohne Schiff, der jeden Abend fünf Teller deckt. Ein Schiffsjunge, der blinder Passagier
## in Tobis Leben wird, eine Piratin, die eine Schande verschweigt, und ein goldener Hafen, in dem
## Matrosen niemals widersprechen. Hier erfährt man, woher die Federfäuste stammen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Fünf Teller",
	"summary": "Seit dem Sturm deckt Tobi jeden Abend fünf Teller für eine Mannschaft, die nicht mehr kommt. Dann klaut ein Junge die Wurst vom fünften Teller – und alles gerät in Fahrt.",
	"relic": "Der sechste Teller",
	"relic_text": "Ein verbeulter Blechteller. Auf der Rückseite hat Muschel mit einem Nagel eingeritzt: MANNSCHAFT.",
}

const CAST := {
	"hero": {"preset": "tobi", "name": "TOBI", "title": "Die Federfaust", "color": "ff2b2b"},
	"muschel": {"preset": "zip", "name": "MUSCHEL", "title": "Blinder Passagier, zwölf Jahre", "color": "38bdf8"},
	"brise": {"preset": "brunhild", "name": "OMA BRISE", "title": "Wirtin der Hafenkneipe", "color": "a3e635"},
	"goldzahn": {"preset": "don_valente", "name": "GOLDZAHN", "title": "Geldverleiher am Kai", "color": "eab308"},
	"schlaeger": {"preset": "swat_specops", "name": "KAISCHLÄGER", "title": "Zählt Münzen mit den Fäusten", "color": "78716c"},
	"seraphine": {"preset": "pirate_captain", "name": "SERAPHINE", "title": "Kapitänin der Salzkrähe", "color": "0ea5e9"},
	"knurr": {"preset": "warrok_brute", "name": "KNURR", "title": "Bootsmann der Salzkrähe", "color": "a16207"},
	"mammon": {"boss": "mammon", "name": "MAMMON", "title": "Der Gierige", "color": "facc15"},
	"hannes": {"preset": "golem", "name": "SMUTJE HANNES", "title": "Schiffskoch, jetzt aus Gold", "color": "fcd34d"},
	"laut": {"preset": "tobi", "name": "TOBI, DER LAUTE", "title": "Lacht, damit es nicht still wird", "color": "7f1d1d"},
}

static func chapters() -> Array:
	return [
		{"id": "tobi_1", "title": "Fünf Teller", "arena": "bg_night_market", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["brise", -3.2, 1], ["muschel", 4.0, -1], ["goldzahn", 8.0, -1], ["schlaeger", 9.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "TOBI · FÜNF TELLER", "sub": "Kapitel I – Fünf Teller"},
			S._narr("Hafen Krummanker. In Oma Brises Kneipe sitzt jeden Abend derselbe junge Mann am größten Tisch. Er deckt fünf Teller. Dann isst er allein."),
			S._narr("Vor einem Jahr nahm ein Sturm sein Schiff, die Möwenherz. Und mit ihr: Hannes, Lotte, Fiete, Ida und den alten Brakel."),
			S._cam("two", 0, 1.6, 1),
			S._say("brise", "Fünf Teller, Junge. Wie jeden Abend. Ich spül die übrigens auch jeden Abend, nur damit du's weißt."),
			S._say("hero", "HAHA! Danke, Oma Brise! Die kommen wieder! Hannes hasst es, wenn sein Teller kalt ist!"),
			S._say("brise", "Du lachst so laut, dass die Möwen vom Dach fallen. Aber deine Augen lachen nicht mit, Tobi."),
			S._cam("close", 0, 1.2),
			S._narr("Tobi sieht auf seine Unterarme. Zwei Schienen aus Messing, darin aufgerollte Stahlfedern, so dick wie ein Daumen."),
			S._narr("Smutje Hannes hat sie geschmiedet – aus den Federn der alten Schiffsuhr. »Damit deine Faust weiter reicht als dein Mut«, hat er gesagt."),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": 1.4, "time": 0.6},
			S._pose(2, "Dash", 0.5),
			{"t": "move", "who": 2, "x": 3.5, "time": 0.6},
			S._cam("two", 0, 1.0, 2),
			S._say("muschel", "Die Wurst lag auf einem Teller, wo keiner sitzt! Das zählt nicht als Klauen, das ist … Fundsache!"),
			S._say("hero", "HAHAHA! Fundsache! Das hätte Fiete auch gesagt! Wie heißt du, Kleiner?"),
			S._say("muschel", "Muschel. Weil ich in einer Kiste Muscheln an Land geschmuggelt wurde. Blinder Passagier. Sehr erfolgreich."),
			S._music("tense"),
			{"t": "appear", "who": 3}, {"t": "appear", "who": 4},
			{"t": "move", "who": 3, "x": 5.6, "time": 1.0},
			{"t": "move", "who": 4, "x": 6.6, "time": 1.2},
			S._cam("low", 3, 1.4),
			S._say("goldzahn", "Da ist ja mein kleiner Schuldner. Drei Goldstücke für die Überfahrt, Muschel. Plus Zinsen. Plus Zinsen auf die Zinsen."),
			S._say("muschel", "Ich bin in einer Kiste gereist! Kisten zahlen keine Überfahrt!"),
			S._narr("Goldzahn dreht eine Münze zwischen den Fingern. Darauf ein Gesicht mit Hörnern, das zu grinsen scheint."),
			S._say("hero", "Der Kleine sitzt an meinem Tisch, Goldzahn. Wer an meinem Tisch sitzt, gehört zur Mannschaft. Und meine Mannschaft zahlt nicht an Haie."),
			S._say("muschel", "Ich gehör zur Mannschaft? Echt? Dann – dann kämpf ich mit! Ich kann beißen!"),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "SCHLEUDERFAUST – SCHNAPP DIR DIE MÜNZE!", "flag": "tobi_coin",
				"success": [S._pose(0, "Attack", 0.6), S._narr("Die Feder schnalzt. Tobis Faust fliegt quer durch die Kneipe und kommt mit Goldzahns Münze zurück.")],
				"fail": [S._pose(0, "HitReact", 0.6), S._narr("Die Feder schnalzt – und Tobis Faust erwischt den Kronleuchter. Oma Brise seufzt sehr laut.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "muschel", "goldzahn", "schlaeger"], "goal": "VERTEIDIGE DEINEN NEUEN MATROSEN!", "lives": [3, 2, 1, 1], "teams": [0, 0, 1, 1], "qte": "tobi_coin", "ai": 3},
			S._music("hope"),
			{"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._cam("two", 0, 1.4, 1),
			S._say("brise", "Die Münze, die du Goldzahn abgenommen hast … Ich kenne das Gesicht. Die Salzkrähe hat in der Sturmnacht genau so ein Gold an Bord gesehen."),
			S._say("hero", "Die Salzkrähe? Seraphines Schiff? Die war DA, in der Nacht? Die ist einfach weitergesegelt?"),
			S._say("muschel", "Gehen wir sie fragen? Wir zwei? Die Mannschaft?"),
			S._pose(0, "Victory", 1.0),
			S._say("hero", "Kapitän Tobi und Matrose Muschel! HAHA! Oma Brise – leih uns dein Ruderboot!"),
		]},
		{"id": "tobi_2", "title": "Die Salzkrähe", "arena": "pirate_galleon", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["muschel", -3.4, 1], ["seraphine", 2.8, -1], ["knurr", 4.4, -1]]),
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Salzkrähe"},
			S._narr("Die Salzkrähe ankert hinter der Nebelbank. Bis dorthin sind es drei Seemeilen – in einem Ruderboot, das leckt."),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 14, "time": 3.0, "text": "RUDERN! RUDERN! RUDERN!", "flag": "tobi_rowed",
				"success": [S._narr("Die Federn in Tobis Armen machen aus jedem Ruderschlag drei. Sie erreichen das Schiff noch vor dem Morgengrauen.")],
				"fail": [S._narr("Muschel schöpft, Tobi rudert, das Boot säuft trotzdem halb ab. Sie klettern klatschnass und völlig erledigt an Bord.")]},
			S._cam("two", 0, 1.4, 2),
			S._say("seraphine", "Sieh an. Ein nasser Junge und ein noch nasserer Junge. Wer an Bord kommt, tanzt nach meinem Lied, ihr zwei."),
			S._say("hero", "Du warst in der Sturmnacht da, Seraphine. Du hast meine Leute nicht gerettet. Du hast nur zugesehen!"),
			S._say("seraphine", "Kapitän? Ohne Mannschaft bist du nur ein Junge mit großen Fäusten."),
			S._say("muschel", "Er HAT eine Mannschaft. Mich. Ich bin zwölf. Das ist mehr als nichts!"),
			S._cam("two", 2, 1.2, 3),
			S._say("knurr", "Kapitänin, soll ich die zwei zurück ins Wasser werfen? Ich werf gern."),
			{"t": "choice", "text": "Was tut Tobi?", "options": [
				{"label": "Entern! Sofort!", "flag": "tobi_stormed", "steps": [
					S._say("hero", "Genug geredet! Möwenherz-Mannschaft – ENTERN!"),
					S._say("seraphine", "Ha! Endlich mal einer mit Rückgrat. Knurr, zeig ihm das Deck!")]},
				{"label": "Erst zuhören", "flag": "tobi_listened", "steps": [
					S._narr("Tobi holt Luft, um zu brüllen. Dann lässt er sie wieder raus. Leise. Das hat er seit einem Jahr nicht mehr getan."),
					S._say("hero", "… Erzähl mir, was du gesehen hast. Bitte."),
					S._say("seraphine", "Hm. Nach Piratenrecht: Wer nach einer Minute noch steht, hat das Recht auf die Wahrheit. Knurr, halt dich raus.")]},
			]},
			S._music("fight"),
			{"t": "branch", "flag": "tobi_listened", "steps": [
				{"t": "fight", "cast": ["hero", "seraphine"], "goal": "STEH NACH EINER MINUTE NOCH!", "lives": [2, 3], "time": 60, "qte": "tobi_rowed", "ai": 5},
			], "else": [
				{"t": "fight", "cast": ["hero", "seraphine", "knurr"], "goal": "ENTERE DIE SALZKRÄHE!", "lives": [3, 2, 1], "teams": [0, 1, 1], "qte": "tobi_rowed", "ai": 4},
			]},
			S._music("sad"),
			S._cam("two", 0, 1.6, 2),
			S._say("seraphine", "Gut. Du kriegst sie, die Wahrheit. In der Sturmnacht sah ich ein Schiff aus Gold. Es fischte Menschen aus dem Wasser – mit Netzen aus Münzen."),
			S._say("seraphine", "Ich bin nicht hingefahren. Gold, das Menschen fischt, fährt man nicht hinterher. Ich hatte Angst. Das ist meine Schande, Federfaust."),
			S._cam("close", 0, 1.2),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Sie … sie sind nicht ertrunken? Hannes und die anderen – die wurden GEFISCHT?"),
			{"t": "branch", "flag": "tobi_listened", "steps": [
				S._say("seraphine", "Du hast mir zugehört, statt mir die Nase einzuschlagen. Das ist mir seit zwanzig Jahren nicht passiert. Ich komme mit."),
				S._say("knurr", "Die Kapitänin segelt einem Goldschiff hinterher. Ich hasse Gold. Ich komm auch mit."),
			], "else": [
				S._say("seraphine", "Den Kurs zum Goldhafen kriegst du. Mein Schiff nicht. Und jetzt runter von meinem Deck, bevor ich's mir anders überlege."),
				S._say("muschel", "Sie mag uns. Ich merk so was."),
			]},
			S._cam("sky", 0, 2.0),
			S._narr("Der Kurs führt nach Süden. Dorthin, wo das Meer aufhört, blau zu sein, und anfängt zu glänzen."),
		]},
		{"id": "tobi_3", "title": "Der Hafen aus Gold", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["mammon", 3.2, -1], ["hannes", 1.4, -1], ["seraphine", -4.2, 1], ["muschel", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Hafen aus Gold"},
			S._narr("Ein Hafen, in dem alles glänzt. Goldene Kräne, goldene Möwen, goldene Matrosen, die stumm Kisten tragen. Niemand lacht hier."),
			S._cam("close", 2, 1.6),
			S._narr("Und vorne am Kai, mit einer goldenen Schöpfkelle in der Hand, steht ein Koch mit einem Bauch wie ein Fass."),
			S._say("hero", "HANNES! Hannes, ich bin's! Tobi! Ich hab dir jeden Abend einen Teller gedeckt!"),
			S._narr("Hannes antwortet nicht. Er hebt nur die Kelle. Langsam. Als würde jemand anders seinen Arm bewegen."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.2),
			S._say("mammon", "Willkommen im schönsten Hafen der Welt, kleiner Kapitän. Gefällt dir meine Flotte? Hundert Schiffe. Tausend Matrosen."),
			S._say("mammon", "Und das Beste: Sie widersprechen nie. Sie lachen nicht zu laut. Sie gehen nie verloren. Ich schenke dir fünf davon. Die fünf, die du kennst."),
			S._say("hero", "Das ist keine Mannschaft. Das sind Gefangene mit Glanz drauf."),
			S._say("mammon", "Ist das ein Unterschied? Du hast sie doch auch nie gefragt, was sie wollen. Du hast nur gebrüllt. Fang, Kapitän!"),
			S._cam("two", 0, 1.2, 2),
			S._narr("Hannes' Lippen bewegen sich. Ganz leise: »Tobi … hau ruhig. Bin aus Gold. Tut nicht weh. Ich halte die Kelle schief, so gut ich kann.«"),
			S._music("boss"),
			{"t": "branch", "flag": "tobi_listened", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.2, "time": 0.8},
				S._say("seraphine", "Diesmal fahre ich nicht vorbei. Federfaust – du links, ich rechts!"),
				{"t": "fight", "cast": ["hero", "seraphine", "mammon", "hannes"], "goal": "BEFREIE HANNES – SCHLAG DIE GIER!", "lives": [3, 2, 1, 1], "teams": [0, 0, 1, 1],
					"mods": {"3": {"power": 0.6}}},
			], "else": [
				S._say("muschel", "Ich bin nur zwölf, aber ich halt dir den Rücken frei! Also … von ganz hinten!"),
				{"t": "fight", "cast": ["hero", "mammon", "hannes"], "goal": "BEFREIE HANNES – SCHLAG DIE GIER!", "lives": [3, 1, 1], "teams": [0, 1, 1],
					"mods": {"2": {"power": 0.6}}, "ai": 5},
			]},
			S._music("sad"),
			{"t": "fx", "kind": "burst", "who": 1},
			S._cam("two", 0, 1.4, 1),
			S._say("mammon", "Du hast meinen Hafen zerkratzt. Gut, behalte deine Fünf. Aber sie gehören jetzt dem Meer. Hol sie, wenn du sie hörst."),
			S._say("mammon", "Und das wirst du nie. Du hast nie zugehört, Kapitän. Darum hat der Sturm sie dir genommen."),
			{"t": "vanish", "who": 1},
			S._narr("Der goldene Hafen bricht wie dünnes Eis. Die fünf Statuen kippen ins Wasser und sinken. Tobi springt hinterher und greift ins Leere."),
			S._cam("close", 0, 1.6),
			S._pose(0, "Defeat", 1.2),
			S._say("hero", "Ich hab sie fast gehabt. Ich hatte Hannes' Hand. Sie war warm, Muschel. Unter dem Gold war sie warm."),
		]},
		{"id": "tobi_4", "title": "Was der Sturm sagt", "arena": "bg_storm_roof", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["laut", 2.2, -1], ["muschel", -3.8, 1], ["brise", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Was der Sturm sagt"},
			S._narr("Ein Jahr nach dem ersten Sturm kommt der zweite. Tobi steigt auf das Dach des Leuchtturms von Krummanker, so hoch, wie man nur steigen kann."),
			S._cam("two", 0, 1.6, 2),
			S._say("muschel", "Was machst du hier oben? Der Wind bläst dich weg!"),
			S._say("hero", "Mammon hat gesagt, ich muss sie hören. Also brülle ich, bis sie antworten! HANNES! LOTTE! FIETE! IDA! BRAKEL!"),
			{"t": "fx", "kind": "shake"},
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Roar", 1.0),
			S._say("laut", "HAHAHA! Genau so! Lauter! Wenn du laut genug lachst, hörst du nicht, wie still es geworden ist!"),
			S._say("laut", "Du hast sie verloren, weil du zu laut warst, um den Sturm zu hören. Hannes hat gerufen: Reff die Segel! Und du hast gesungen."),
			S._cam("close", 0, 1.2),
			S._say("hero", "… Ich weiß. Ich hab es gehört. Ich wollte nur, dass alle keine Angst haben."),
			S._say("laut", "Dann sei weiter laut! Für fünf! Für immer! Das ist das Einzige, was du kannst!"),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "laut"], "goal": "BESIEGE DEN LÄRM IN DIR!", "lives": [2, 3], "mods": {"0": {"power": 1.25}, "1": {"kb": 0.85}}, "ai": 8},
			{"t": "vanish", "who": 1},
			S._music("calm"),
			S._cam("close", 0, 1.6),
			S._narr("Tobi steht allein auf dem Dach. Er brüllt nicht mehr. Er lacht nicht. Zum ersten Mal seit einem Jahr ist er ganz still."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.6, "text": "SEI STILL. HÖR HIN.", "flag": "tobi_heard",
				"success": [S._narr("Im Heulen des Windes, ganz schwach, ein Lied. Hannes' Lied. Das, bei dem Brakel immer falsch einsetzt.")],
				"fail": [S._narr("Erst hört Tobi nur Wind. Dann hält Muschel ihm den Mund zu. Und da ist es: ein Lied, schief und falsch und wunderschön.")]},
			S._music("hope"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.4, 3),
			S._say("brise", "Muschel, den Spiegel! Dreh die Lampe aufs Meer, Junge, so weit, wie sie leuchtet!"),
			S._cam("sky", 0, 2.4),
			S._narr("Der Lichtstrahl fällt aufs Wasser. Mitten in den Wellen: ein kleines Boot. Fünf Gestalten. Sie winken. Sie sind nicht mehr aus Gold."),
			S._pose(0, "Dash", 0.8),
			S._narr("Tobi springt vom Leuchtturm ins Meer und schwimmt. Die Federn in seinen Armen werfen ihn durch die Wellen, Zug um Zug."),
			S._say("muschel", "ER IST GESPRUNGEN! Oma Brise, er ist einfach gesprungen! Ist das normal bei Kapitänen?"),
			S._say("brise", "Bei dem? Ja. Setz Wasser auf, Kleiner. Und hol die Teller."),
			S._cam("two", 2, 1.6, 3),
			S._narr("Am nächsten Abend deckt Oma Brise den großen Tisch. Sechs Teller. Diesmal sind alle besetzt, und auf dem sechsten sitzt Muschel."),
			S._say("hero", "Hannes, das ist Muschel. Neuer Matrose. Er klaut Würste und hört besser zu als ich. Er bleibt."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Tobi · Fünf Teller"},
			S._narr("Relikt erhalten: Der sechste Teller  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
