extends RefCounted
## Legende: KAAN, DER HALBMONDKRIEGER – „Ein Glas Tee“.
## Kaan ist der beste Säbelfechter im großen Basar, aufbrausend und stolz. Er hat noch nie verloren
## und noch nie verziehen. Der Kommandant zeigt ihm eine Klinge, die nicht zürnt, Luzifer bietet ihm den
## Stolz der ganzen Welt, und am Ende teilt er ein Glas Çay mit dem, den er am meisten gehasst hat.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Ein Glas Tee",
	"summary": "Kaan ist der schnellste Säbel im großen Basar. Er hat noch nie verloren – und noch nie verziehen. Sein Bruder Emre hat vor Jahren den Familienladen verlassen, und Kaan hat seitdem kein Wort mit ihm gesprochen.",
	"relic": "Das Tulpenglas",
	"relic_text": "Ein kleines Teeglas in Tulpenform. Wer daraus trinkt, muss mit dem reden, der gegenüber sitzt. Das ist die einzige Regel.",
}

const CAST := {
	"hero": {"preset": "kaan", "name": "KAAN", "title": "Der Halbmondkrieger", "color": "e30a17"},
	"emre": {"preset": "jubei", "name": "EMRE", "title": "Sein Bruder", "color": "99f6e4"},
	"dieb": {"preset": "specter", "name": "BASARDIEB", "title": "Schnelle Finger", "color": "9b30ff"},
	"kommandant": {"preset": "samurai_dreyar", "name": "DER KOMMANDANT", "title": "Eine Klinge ohne Zorn", "color": "99f6e4"},
	"lucifer": {"boss": "lucifer", "name": "LUZIFER", "title": "Der Hochmut", "color": "7dd3fc"},
	"schatten": {"preset": "kaan", "name": "DER STOLZ", "title": "Der Kaan, der nie vergibt", "color": "7f1d1d"},
}

static func chapters() -> Array:
	return [
		{"id": "kaan_1", "title": "Der große Basar", "arena": "imperial_colosseum", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["dieb", 2.8, -1]]),
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAAN · EIN GLAS TEE", "sub": "Kapitel I – Der große Basar"},
			S._narr("Im großen Basar duftet es nach Gewürzen, Leder und frischem Simit. Über dem Laden der Familie hängt eine rote Fahne mit Halbmond und Stern. Davor steht Kaan, die Hand am Säbel."),
			S._narr("Früher standen hier zwei Brüder. Jetzt steht hier nur noch einer. Er hat gelernt, doppelt so schnell zu sein."),
			S._cam("two", 0, 1.6, 1),
			S._say("dieb", "Schöne Teekannen hast du da, Säbelmann. Die nehme ich mit. Alle."),
			S._say("hero", "Die Kanne meiner Großmutter? Haydi – versuch es."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "dieb"], "goal": "SCHÜTZE DEN LADEN!", "lives": [3, 1], "ai": 3},
			S._music("calm"),
			S._cam("close", 0, 1.4),
			S._say("dieb", "Schon gut, schon gut! Der Laden gegenüber hat mich übrigens auch verjagt. Der Typ dort kämpft fast wie du."),
			S._say("hero", "… Welcher Laden gegenüber?"),
			S._narr("Kaan sieht über die Gasse. Dort, wo früher ein leerer Stand war, hängt ein neues Schild. Darunter steht sein Bruder Emre und schenkt Tee aus."),
		]},
		{"id": "kaan_2", "title": "Eine Klinge ohne Zorn", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["kommandant", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Eine Klinge ohne Zorn"},
			S._narr("Kaan geht nicht über die Gasse. Er geht in die Arena, wo ein fremder Schwertmeister jeden Säbel der Stadt herausfordert. Kämpfen ist leichter als reden."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("kommandant", "Du kämpfst wie ein Gewitter, Halbmondkrieger. Viel Donner. Wem gilt er?"),
			S._say("hero", "Niemandem. Er gilt dir."),
			S._say("kommandant", "Nein. Ich habe deinen Blick gesehen, als du hereinkamst. Du suchst jemanden, den du nicht schlagen kannst. Also schlägst du mich."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "kommandant"], "goal": "SÄBEL GEGEN KATANA!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("kommandant", "Du bist schnell. Aber dein Zorn macht deine Klinge schwer. Eine Klinge ohne Zorn ist leichter als Luft."),
			S._say("hero", "Und wenn der Zorn das Einzige ist, was mir von meinem Bruder geblieben ist?"),
			S._say("kommandant", "Dann ist es Zeit, ihn gegen etwas Besseres zu tauschen."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht leuchtet der Mond über dem Basar dünn wie eine Sichel. Und aus seinem Schatten tritt jemand, der sehr, sehr stolz ist."),
		]},
		{"id": "kaan_3", "title": "Der Hochmut", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lucifer", 3.0, -1], ["emre", -4.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Hochmut"},
			S._narr("Eis, so weit das Auge reicht. Darin ein gefallener Fürst, der lächelt, als hätte er auf Kaan gewartet."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lucifer", "Endlich jemand, der mich versteht. Dein Bruder ist gegangen. Du bist geblieben. Du hast recht, Kaan. Du hattest immer recht."),
			S._say("hero", "Ich hatte recht … Ja. Er hat uns im Stich gelassen."),
			S._say("lucifer", "Dann vergib ihm nie. Stolz ist die einzige Rüstung, die nie bricht. Ich trage sie seit dem Anfang der Zeit."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
			S._say("emre", "Kaan! Ich bin dir gefolgt. Ich bin nicht gegangen, um dich allein zu lassen. Ich wollte einen eigenen Laden. Ich hätte es dir sagen sollen. Ich hatte Angst vor deinem Säbel."),
			S._say("hero", "Und ich hatte Angst, dass du ohne mich glücklicher bist."),
			S._say("hero", "Hör zu, Gefallener. Stolz ist keine Rüstung. Er ist ein Käfig aus Eis. Du steckst seit dem Anfang der Zeit darin fest."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "emre", "lucifer"], "goal": "BRÜDER GEGEN DEN HOCHMUT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Zwei Klingen, ein Takt. Luzifer sinkt zurück ins Eis. Zum ersten Mal hört er auf zu lächeln."),
		]},
		{"id": "kaan_4", "title": "Ein Glas Tee", "arena": "imperial_colosseum", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["emre", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Ein Glas Tee"},
			S._narr("Zurück im Basar. Mitten in der Gasse zwischen den zwei Läden wartet ein Krieger in dunklem Rot: Kaan, wie er sich selbst im Spiegel sieht, wenn er wütend ist."),
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schatten", "Er hat dich verlassen. Wenn du ihm verzeihst, war alles umsonst. Die Jahre allein. Die Wut. Alles."),
			S._say("hero", "Die Jahre waren nicht umsonst. Ich bin schneller geworden. Aber jetzt will ich langsamer werden. Lange genug für ein Glas Tee."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schatten"], "goal": "BESIEGE DEINEN STOLZ!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._say("emre", "Çay? Frisch aufgebrüht. In Omas Kanne – ich habe sie damals heimlich mitgenommen. Die echte. Deine ist eine Kopie."),
			S._say("hero", "… Du Dieb. Schenk ein, Bruder."),
			S._narr("Seit diesem Tag stehen zwei Läden in der Gasse, und dazwischen ein kleiner Tisch mit zwei Tulpengläsern. Wer streitet, muss sich dort hinsetzen. Das ist die Regel."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Kaan · Ein Glas Tee"},
			S._narr("Relikt erhalten: Das Tulpenglas  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
