extends RefCounted
## Legende: KONRAD, DER SCHMIEDEMEISTER – „Gut genug“.
## Konrad schmiedet in einem Dorf am Rand des Schwarzwalds, seit sieben Generationen in derselben Esse.
## Kein Stück verlässt seine Werkstatt, das nicht perfekt ist – und deshalb fast keins. Der Kardinal
## fordert ihn heraus, Belphegor bietet ihm ewige Ruhe, und am Ende schmiedet er ein krummes Hufeisen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Gut genug",
	"summary": "Konrad schmiedet in der Esse seiner Familie am Rand des Schwarzwalds. Er wirft jedes Stück zurück ins Feuer, an dem er einen Fehler findet. Er findet immer einen.",
	"relic": "Das krumme Hufeisen",
	"relic_text": "Ein Hufeisen mit einer kleinen Delle. Ein Kind hat beim Schmieden den Hammer gehalten. Es hängt über Konrads Tür und bringt mehr Glück als alle perfekten.",
}

const CAST := {
	"hero": {"preset": "konrad", "name": "KONRAD", "title": "Der Schmiedemeister", "color": "ffce00"},
	"lehrling": {"preset": "grimbolt", "name": "FRITZI", "title": "Lehrling mit zu vielen Ideen", "color": "f59e0b"},
	"kunde": {"preset": "vanguard_soldier", "name": "DER KUNDE", "title": "Will sein Schwert heute", "color": "94a3b8"},
	"kardinal": {"preset": "steel_knight", "name": "CARDINAL", "title": "Trägt nur Perfektes", "color": "e2e8f0"},
	"belphegor": {"boss": "belphegor", "name": "BELPHEGOR", "title": "Die Trägheit", "color": "a3e635"},
	"schatten": {"preset": "konrad", "name": "DER MEISTER", "title": "Der Konrad, der nie zufrieden ist", "color": "1a1a1a"},
}

static func chapters() -> Array:
	return [
		{"id": "konrad_1", "title": "Sieben Generationen", "arena": "volcano_sanctum", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["kunde", 2.5, -1], ["lehrling", -3.5, 1]]),
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KONRAD · GUT GENUG", "sub": "Kapitel I – Sieben Generationen"},
			S._narr("Am Rand des Schwarzwalds steht eine Schmiede, so alt wie das Dorf. Über der Tür hängen sieben Hämmer – einer für jeden Meister der Familie. Der achte gehört Konrad."),
			S._narr("Seit drei Wochen arbeitet er an einem einzigen Schwert. Er hat es elfmal zurück ins Feuer geworfen."),
			S._cam("two", 0, 1.6, 1),
			S._say("kunde", "Meister Konrad, ich habe vor drei Wochen bezahlt. Ich brauche das Schwert heute. Es sieht doch fertig aus!"),
			S._say("hero", "Die Klinge ist um einen halben Millimeter schief. Mein Urgroßvater hätte das gesehen. Also sehe ich es auch."),
			S._say("lehrling", "Meister, er hat eine Hellebarde dabei. Und er sieht nicht so aus, als würde er noch eine Woche warten."),
			S._say("kunde", "Dann hole ich es mir eben! Schief oder nicht!"),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "kunde"], "goal": "VERTEIDIGE DIE WERKSTATT!", "lives": [3, 1], "ai": 3},
			S._music("calm"),
			S._cam("close", 0, 1.4),
			S._say("lehrling", "Das Schwert hat Ihnen das Leben gerettet. Sie haben damit pariert. Mit der schiefen Klinge."),
			S._say("hero", "… Sie hat gehalten."),
			S._narr("Konrad legt das Schwert auf den Amboss. Er nimmt den Hammer. Dann legt er den Hammer wieder weg. Zum ersten Mal seit drei Wochen."),
		]},
		{"id": "konrad_2", "title": "Der Kardinal", "arena": "imperial_colosseum", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["kardinal", 2.5, -1], ["lehrling", -3.8, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Kardinal"},
			S._narr("Die Nachricht spricht sich herum: Ein Schmied im Schwarzwald hat ein Schwert geschmiedet, das einem Angriff standhielt. Der Kardinal kommt, der Ritter in der makellosen Rüstung."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("kardinal", "Man sagt, du seist der Beste. Ich trage nur Perfektes. Meine Rüstung hat keinen einzigen Kratzer. Schmiede mir ein Schwert, das dazu passt."),
			S._say("hero", "Keine Rüstung ist ohne Kratzer. Nur ohne Kampf."),
			S._say("kardinal", "Dann prüfe sie. Wenn du einen Kratzer hineinschlägst, nehme ich jedes Schwert, das du mir gibst – auch ein schiefes."),
			S._say("lehrling", "Meister, das ist eine Falle. Oder ein Kompliment. Bei Rittern weiß man das nie."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "kardinal"], "goal": "HAMMER GEGEN VOLLPLATTE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("kardinal", "Ein Kratzer. Hier, an der Schulter. Hundert Kämpfe ohne, und jetzt einer."),
			S._say("hero", "Jetzt ist es eine Rüstung, die gekämpft hat. Das ist mehr wert als eine, die nur glänzt."),
			S._say("kardinal", "… Das hätte ich gern früher gehört. Schmiede mir das Schwert, Meister. So, wie es wird."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht wird es kalt in der Schmiede. Die Esse brennt, aber Konrad spürt die Wärme nicht. Etwas flüstert ihm zu, dass er müde ist. Sehr, sehr müde."),
		]},
		{"id": "konrad_3", "title": "Feierabend für immer", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["belphegor", 3.0, -1], ["lehrling", -4.2, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Feierabend für immer"},
			S._narr("Konrad wacht in einer Stadt auf, in der niemand arbeitet. Die Werkstätten sind leer, die Feuer kalt. Auf einem Thron aus Kissen liegt Belphegor und gähnt."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("belphegor", "Konrad. Sieben Generationen haben sich krumm geschuftet. Und keiner war je zufrieden. Leg den Hammer hin. Bei mir musst du nie wieder etwas fertig machen."),
			S._say("hero", "Nie wieder etwas fertig machen … Dann kann auch nichts mehr schief sein."),
			S._say("belphegor", "Genau! Kein Fehler, nie mehr. Weil du nichts mehr tust. Das ist die einzige Perfektion, die es gibt."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
			S._say("lehrling", "Meister! Ich bin durch Ihre Esse gekrochen! Die Werkstatt brennt nicht mehr – ohne Sie geht hier gar nichts!"),
			S._say("hero", "Fritzi. Was du baust, ist immer schief. Und es funktioniert trotzdem. Jedes Mal."),
			S._say("hero", "Belphegor – ich bin nicht müde von der Arbeit. Ich bin müde davon, nie zufrieden zu sein. Das ist ein Unterschied. Und den schmiede ich jetzt aus."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "lehrling", "belphegor"], "goal": "ZURÜCK AN DEN AMBOSS!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Die Kissen fliegen, der Thron kippt. Belphegor schläft einfach ein, mitten im Fallen. In den leeren Werkstätten der Stadt glimmt hier und da ein Funke."),
		]},
		{"id": "konrad_4", "title": "Das achte Stück", "arena": "volcano_sanctum", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["lehrling", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das achte Stück"},
			S._narr("Zurück in der Schmiede. Konrad will das Schwert für den Kardinal beenden. Da steht jemand an seinem Amboss: er selbst, ganz in Schwarz, mit einem Hammer, der nie stillsteht."),
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schatten", "Ins Feuer damit. Und das nächste auch. Wir sind der achte Meister. Wir dürfen nicht schlechter sein als die sieben davor."),
			S._say("hero", "Die sieben davor haben Hufeisen gemacht, Pflüge, Türangeln. Sie haben gemacht, was das Dorf brauchte. Nicht, was perfekt war."),
			S._say("schatten", "Dann bist du nur ein Handwerker."),
			S._say("hero", "Ja. Endlich."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schatten"], "goal": "SCHMIEDE DEN ZWEIFEL AUS!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._say("lehrling", "Meister, darf ich mal? Nur ein Hufeisen. Für das Pony von der Bäckerin."),
			S._narr("Fritzi hält den Hammer, Konrad hält die Zange. Das Hufeisen bekommt eine Delle. Konrad sieht sie. Er sagt nichts. Er hängt es über die Tür, neben die sieben Hämmer."),
			S._say("hero", "Gut genug. Nein – gut. Einfach gut."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Konrad · Gut genug"},
			S._narr("Relikt erhalten: Das krumme Hufeisen  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
