extends RefCounted
## Legende: AMRA, DIE BRÜCKENSPRINGERIN – „Einundzwanzig Meter“.
## Amra stammt aus einer Familie von Brückenspringern in Mostar. Ihr Vater sprang hunderte Male von der
## Alten Brücke in die Neretva. Amra stand einmal oben – und ist nicht gesprungen. Scarlet zeigt ihr das
## Fliegen, Leviathan den Neid, und am Ende springt sie.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Einundzwanzig Meter",
	"summary": "Amra kommt aus einer Familie von Brückenspringern. Ihr Vater sprang hunderte Male von der Alten Brücke in Mostar. Sie stand ein einziges Mal oben auf dem Geländer – und ist wieder hinuntergeklettert.",
	"relic": "Das Springerband",
	"relic_text": "Ein blaues Stirnband mit gelbem Saum, verblichen vom Flusswasser. Ihr Vater trug es bei seinem ersten Sprung, sie bei ihrem.",
}

const CAST := {
	"hero": {"preset": "amra", "name": "AMRA", "title": "Die Brückenspringerin", "color": "38bdf8"},
	"tarik": {"preset": "zip", "name": "TARIK", "title": "Ihr kleiner Cousin", "color": "fecb00"},
	"rabauke": {"preset": "tobi", "name": "RABAUKE", "title": "Will auf die Brücke", "color": "1e3a8a"},
	"scarlet": {"preset": "phoenix", "name": "SCARLET", "title": "Fliegt, ohne zu fallen", "color": "ff8a1f"},
	"leviathan": {"boss": "leviathan", "name": "LEVIATHAN", "title": "Der Neid", "color": "38bdf8"},
	"schatten": {"preset": "amra", "name": "DIE ZÖGERNDE", "title": "Die Amra, die nie springt", "color": "002395"},
}

static func chapters() -> Array:
	return [
		{"id": "amra_1", "title": "Die Alte Brücke", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["rabauke", 2.8, -1], ["tarik", -3.5, 1]]),
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "AMRA · EINUNDZWANZIG METER", "sub": "Kapitel I – Die Alte Brücke"},
			S._narr("Über der grünen Neretva spannt sich ein steinerner Bogen, schlank wie eine Mondsichel. Einundzwanzig Meter tief darunter rauscht das eiskalte Wasser."),
			S._narr("Amra trainiert jeden Tag am Ufer. Saltos, Schrauben, Handstände. Nur auf die Brücke steigt sie nicht mehr."),
			S._cam("two", 0, 1.6, 1),
			S._say("tarik", "Amra! Der Typ da will vom Geländer springen – ohne Training! Er sagt, das kann jeder!"),
			S._say("rabauke", "Was soll da schon passieren? Wasser ist weich!"),
			S._say("hero", "Aus einundzwanzig Metern ist Wasser so hart wie Stein. Komm da runter. Ajde – runter, sag ich!"),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "rabauke"], "goal": "HOL IHN VOM GELÄNDER!", "lives": [3, 1], "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.4, 2),
			S._say("tarik", "Du hättest ihn auch einfach springen lassen können. Dein Papa hat immer gesagt, du springst am schönsten von allen."),
			S._say("hero", "Papa hat viel gesagt, Tarik."),
			S._narr("Amra sieht hinauf zum Bogen. Das Geländer ist genau dort, wo sie es vor drei Jahren losgelassen hat. Andersherum."),
		]},
		{"id": "amra_2", "title": "Fliegen lernen", "arena": "heaven_spheres", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["scarlet", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Fliegen lernen"},
			S._narr("Eine Kriegerin mit Flügeln aus Feuer landet am Ufer. Sie hat von der Springerin gehört, die am Ufer fliegt und an der Brücke stehen bleibt."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("scarlet", "Ich bin Scarlet. Ich falle nie – ich habe Flügel. Ich wollte sehen, wie jemand fliegt, der keine hat."),
			S._say("hero", "Ich fliege nicht. Ich falle. Mit Stil. Das ist ein Unterschied."),
			S._say("scarlet", "Dann zeig mir den Unterschied. In der Luft."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "scarlet"], "goal": "SPRUNG GEGEN FLÜGEL!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("scarlet", "Du hast keine Flügel und warst trotzdem länger in der Luft als ich. Wovor hast du Angst?"),
			S._say("hero", "Vor dem Moment, in dem man loslässt. Danach ist alles leicht. Aber davor …"),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht ist die Neretva plötzlich schwarz. Etwas Großes bewegt sich darin. Es flüstert: Warum springen die anderen und du nicht?"),
		]},
		{"id": "amra_3", "title": "Der Neid", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["leviathan", 3.0, -1], ["tarik", -4.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Neid"},
			S._narr("Unter dem Fluss liegt ein zweiter Fluss, kalt und grün. Darin windet sich eine Schlange, so lang wie die Neretva selbst."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("leviathan", "Jedes Jahr springen sie. Die Jungen, die Alten, die Touristen. Und alle jubeln. Nur dir jubelt niemand. Ist das nicht ungerecht?"),
			S._say("hero", "Sie springen … und ich stehe da und klatsche. Jedes Jahr."),
			S._say("leviathan", "Dann komm zu mir. Hier unten springt niemand. Hier musst du nie wieder zusehen."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
			S._say("tarik", "Amra! Ich bin dir nachgetaucht! Ich kann nicht mal richtig schwimmen! Komm zurück, oben warten alle auf dich!"),
			S._say("hero", "Tarik … Du bist gesprungen. Für mich."),
			S._say("hero", "Hör zu, Schlange. Ich beneide sie nicht. Ich vermisse es. Das ist etwas ganz anderes – und das kriegst du nicht."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "tarik", "leviathan"], "goal": "TAUCH AUF!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Ein Strudel, ein Lichtstrahl, und dann Sonne auf dem Wasser. Amra zieht Tarik ans Ufer. Er hustet und grinst."),
		]},
		{"id": "amra_4", "title": "Einundzwanzig Meter", "arena": "mystic_grove", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["tarik", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Einundzwanzig Meter"},
			S._narr("Der Tag des großen Springens. Hunderte Menschen auf der Brücke und am Ufer. Amra steigt die Stufen hinauf. Oben am Geländer wartet jemand: sie selbst, mit den Händen fest um den Stein."),
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schatten", "Weißt du noch, wie es war? Der Wind. Die Höhe. Das Wasser so weit unten. Wir sind runtergeklettert. Das war klug."),
			S._say("hero", "Es war nicht klug. Es war nur sicher. Papa hat gesagt: Man springt nicht, weil man keine Angst hat. Man springt, obwohl."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schatten"], "goal": "LASS DAS GELÄNDER LOS!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("sky", 0, 2.4),
			S._narr("Amra steht auf dem Geländer. Sie breitet die Arme aus wie eine Schwalbe. Unten wird es still. Dann lässt sie los."),
			S._narr("Einundzwanzig Meter. Zwei Sekunden. Ein Schlag ins kalte Grün – und dann der Jubel, so laut, dass er von beiden Ufern widerhallt."),
			S._cam("two", 0, 1.6, 2),
			S._say("tarik", "Bravo! BRAVO! Das war der schönste Sprung, den ich je gesehen hab!"),
			S._say("hero", "Nächstes Jahr springst du. Ich bring es dir bei. Ab heute jeden Tag."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Amra · Einundzwanzig Meter"},
			S._narr("Relikt erhalten: Das Springerband  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
