extends RefCounted
## Legende: CELESTIAL FOX, DER HIMMELSFUCHS – „Die neunte Lüge“.
## Neun Schwänze, einer für jedes Jahrhundert, jeder trägt eine Lüge, die der Fuchs einst erzählte.
## Er weiß nicht mehr, welche Geschichte über ihn die wahre ist. Shira hat er einst belogen, der Seraph
## will nur eine einzige Wahrheit hören, und am Ende muss der Fuchs die neunte Lüge zurücknehmen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die neunte Lüge",
	"summary": "Der Himmelsfuchs hat neun Schwänze, einen für jedes Jahrhundert. Jeder trägt eine Lüge. Inzwischen weiß er selbst nicht mehr, welche Geschichte über ihn die wahre ist.",
	"relic": "Der abgefallene Schwanz",
	"relic_text": "Ein flauschiger, silberner Fuchsschwanz, der beim Berühren leise lacht. Er erzählt nur eine Geschichte – und die stimmt.",
}

const CAST := {
	"hero": {"preset": "celestial_fox", "name": "HIMMELSFUCHS", "title": "Der Fuchs zwischen den Sternen", "color": "fde68a"},
	"shira": {"preset": "shira", "name": "SHIRA", "title": "Hat ihm nie verziehen", "color": "c084fc"},
	"lepora": {"preset": "lepora", "name": "LEPORA", "title": "Die Mondjägerin", "color": "e0e7ff"},
	"haendler": {"preset": "don_valente", "name": "SCHWANZHÄNDLER", "title": "Kauft Fuchsfeuer", "color": "d4d4d8"},
	"seraph": {"boss": "seraph", "name": "SERAPHAEL", "title": "Will eine einzige Wahrheit", "color": "fde047"},
	"luege": {"preset": "celestial_fox", "name": "DIE NEUN LÜGEN", "title": "Alles, was er je erzählt hat", "color": "a16207"},
}

static func chapters() -> Array:
	return [
		{"id": "celestial_fox_1", "title": "Neun Geschichten", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["haendler", 3.0, -1], ["lepora", -3.5, 1]]),
			{"t": "vanish", "who": 2},
			S._music("hope"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "HIMMELSFUCHS · DIE NEUNTE LÜGE", "sub": "Kapitel I – Neun Geschichten"},
			S._narr("Man erzählt sich neun Geschichten über den Himmelsfuchs. Er sei ein gefallener Stern. Er sei der Diener einer Mondgöttin. Er habe einen Drachen mit einem Witz besiegt."),
			S._narr("Der Fuchs hat alle neun selbst in die Welt gesetzt. Für jedes Jahrhundert eine. Für jede ein Schwanz. Und irgendwann vergaß er, welche Geschichte nicht gelogen war."),
			S._cam("two", 0, 1.4, 1),
			S._say("haendler", "Fuchsfeuer, frisch vom Schwanz! Ich zahle gut. Einen Schwanz, nur einen, du hast doch neun."),
			S._say("hero", "Neun Schwänze, neun Geschichten. Welche willst du? Die vom Stern? Die von der Göttin? Die, in der ich dir jetzt das Fell über die Ohren ziehe?"),
			S._say("haendler", "Die letzte klingt gelogen."),
			S._say("hero", "Oh, die ist neu. Mal sehen, ob sie wahr wird."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "FUCHSFEUER!", "flag": "celestial_fox_fire",
				"success": [S._narr("Neun blaue Flammen tanzen um den Händler und jagen ihn wie Glühwürmchen mit schlechter Laune.")],
				"fail": [S._narr("Die Flammen flackern und fragen: Welcher Schwanz soll eigentlich brennen?")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "haendler"], "goal": "VERJAG DEN SCHWANZHÄNDLER!", "lives": [3, 2], "qte": "celestial_fox_fire", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("lepora", "Fuchs. Ich habe dich getroffen, im Mondtempel. Du hast mir eine Wahrheit gegeben. Gibst du dir auch mal eine?"),
			S._say("hero", "Mir? Ich bin der Einzige, den ich nie anlüge. Das ist … das ist schon wieder gelogen, oder?"),
			S._say("lepora", "Welche der neun Geschichten ist denn deine liebste?"),
			S._say("hero", "Die vom Stern. Ich falle vom Himmel, alle schauen hoch, alle staunen. Niemand fragt, woher ich wirklich komme."),
			S._say("lepora", "Und woher kommst du wirklich?"),
			S._say("hero", "Aus … aus einem Bau? Unter einer Wurzel? Oder war das die Geschichte vom Wurzelgeist? Ach, Mist."),
			S._cam("close", 0, 1.4),
			S._narr("Zum ersten Mal seit neunhundert Jahren weiß der Fuchs nicht, was er als Nächstes sagen soll."),
			S._narr("In dieser Nacht zählt er seine Schwänze. Neun. Er zählt sie noch einmal. Bei jedem fällt ihm eine Lüge ein – und bei keinem die Wahrheit, die darunter lag."),
		]},
		{"id": "celestial_fox_2", "title": "Die Katze, die nicht verzeiht", "arena": "bg_neon_skyline", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["shira", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Katze, die nicht verzeiht"},
			S._narr("Auf den Dächern der Neonstadt wartet jemand mit gezogenen Klingen. Shira. Ohne Maske – aber mit sehr viel Wut."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("shira", "Du hast mir erzählt, du hättest die Maske von Asmodeus gestohlen. Stimmt das? Oder hast du sie mir absichtlich hingelegt?"),
			S._say("hero", "Ich … weiß es nicht mehr. Wirklich nicht. Es gibt drei Geschichten darüber. Ich habe alle drei erzählt."),
			S._say("shira", "Die Maske hat drei Jahre durch mich gesprochen. Drei Jahre, in denen ich nicht wusste, welche Worte meine waren. Weißt du, wie sich das anfühlt?"),
			S._say("hero", "… Ja. Leider ja. Ganz genau sogar."),
			S._say("shira", "Neun Schwänze, neun Lügen. Welche erzählst du mir heute, Fuchs?"),
			{"t": "choice", "text": "Was sagt der Fuchs?", "options": [
				{"label": "Ich weiß es nicht", "flag": "celestial_fox_honest", "steps": [
					S._say("hero", "Ich weiß es nicht, Shira. Das ist das Ehrlichste, was ich seit Jahrhunderten gesagt habe. Es tut mir leid."),
					S._say("shira", "Das reicht nicht. Aber es ist ein Anfang. Wehr dich trotzdem.")]},
				{"label": "Eine schöne Geschichte", "flag": "celestial_fox_tale", "steps": [
					S._say("hero", "Ich habe sie dir gegeben, weil ich sah, dass du stark sein wolltest. Ein Geschenk! Ein großherziges Geschenk!"),
					S._say("shira", "Du lügst. Ich sehe es an deinem vierten Schwanz. Er wackelt.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "shira"], "goal": "STELL DICH DER KATZE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "celestial_fox_honest", "steps": [
				S._say("shira", "Du hast nicht getrickst. Kein einziges Mal. Das macht dich langsamer. Und irgendwie … ehrlicher."),
			], "else": [
				S._say("shira", "Du hast in jedem Zug getrickst. Und trotzdem siehst du aus, als hättest du verloren."),
			]},
			{"t": "fx", "kind": "flash"},
			S._narr("Ein Licht fällt vom Himmel. Ein Auge in sechs Flügeln. Es spricht nur einen Satz: Komm, Fuchs. Erzähl mir die Wahrheit."),
		]},
		{"id": "celestial_fox_3", "title": "Nur einmal", "arena": "empyrean", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["seraph", 3.0, -1], ["shira", -4.0, 1], ["lepora", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Nur einmal"},
			S._narr("Im Empyreum gibt es keine Schatten. Kein Versteck. Keine Ecke, um die man huschen könnte. Für einen Fuchs ist es der unheimlichste Ort der Welt."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("seraph", "Neunhundert Jahre Geschichten, Fuchs. Ich will eine. Nur eine. Die wahre. Woher kommst du?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Ich bin ein Stern. Nein. Ein Diener der Mondgöttin. Nein. Ich … ich weiß es nicht mehr."),
			S._say("seraph", "Dann bist du nur die Summe deiner Tricks. Und Tricks gehören nicht ins Licht."),
			S._say("hero", "Vielleicht. Aber ein Trick hat einer Jägerin geholfen, ihren Pfeil zu finden. Das war echt. Auch wenn ich es nicht bin."),
			S._music("boss"),
			{"t": "branch", "flag": "celestial_fox_honest", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("shira", "Ich verzeihe dir noch nicht. Aber niemand außer mir darf dich verprügeln."),
				{"t": "fight", "cast": ["hero", "shira", "seraph"], "goal": "BESTEHE VOR DEM BRENNENDEN AUGE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("lepora", "Du hast mir eine Wahrheit geschenkt. Ich bringe dir eine zurück: Du bist mehr als deine Tricks."),
				{"t": "fight", "cast": ["hero", "lepora", "seraph"], "goal": "BESTEHE VOR DEM BRENNENDEN AUGE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._say("seraph", "Du hast keine Wahrheit gesagt. Aber du hast für jemanden gekämpft, ohne zu lügen. Geh. Und finde deine Geschichte."),
		]},
		{"id": "celestial_fox_4", "title": "Die wahre Geschichte", "arena": "bg_moon_temple", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["luege", 2.0, -1], ["shira", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Die wahre Geschichte"},
			S._narr("Im Mondtempel legt sich der Fuchs auf den kalten Stein und rollt seine neun Schwänze um sich. Jeder flüstert eine andere Geschichte."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("luege", "Wir sind du. Neun Geschichten, neun Masken. Ohne uns bist du nur ein Fuchs. Ein kleiner, hungriger, gewöhnlicher Fuchs."),
			S._say("hero", "Ein kleiner, hungriger, gewöhnlicher Fuchs …"),
			S._narr("Und plötzlich erinnert er sich. Ein Bau unter einer Wurzel. Ein Winter, zu kalt. Ein alter Mönch, der ihm ein Stück Brot hinwarf und eine Geschichte erzählte, damit er nicht einschläft."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "luege"], "goal": "BESIEGE DIE NEUN LÜGEN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._say("hero", "Ich war ein gewöhnlicher Fuchs. Ein Mönch hat mir Geschichten erzählt, damit ich nicht erfriere. Ich habe nie aufgehört, Geschichten zu erzählen, weil ich Angst hatte, wieder zu frieren."),
			S._narr("Ein Schwanz löst sich und fällt sanft auf den Stein. Der neunte. Der Fuchs fühlt sich leichter als seit Jahrhunderten."),
			S._cam("two", 0, 1.6, 2),
			S._say("shira", "Ein gewöhnlicher Fuchs. Das ist die langweiligste Geschichte, die du je erzählt hast."),
			S._say("hero", "Und die einzige wahre. Wollen wir ein Brot teilen? Ich kenne einen Bäcker. Der ist echt. Versprochen."),
			S._say("shira", "Versprochen? Von dir?"),
			S._say("hero", "Von mir. Dem gewöhnlichen Fuchs. Der hat noch nie gelogen. Er ist erst seit heute da."),
			S._narr("Shira lacht. Es ist kein Verzeihen. Noch nicht. Aber es ist der Anfang einer neuen Geschichte – und diesmal erzählen sie sie zu zweit."),
			S._narr("Der Fuchs behält acht Schwänze. Er lügt manchmal noch. Aber nur noch bei Kartenspielen. Und nur, wenn alle es wissen."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Himmelsfuchs · Die neunte Lüge"},
			S._narr("Relikt erhalten: Der abgefallene Schwanz  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
