extends RefCounted
## Legende: SHIRA – „Die Maske“.
## Shira war eine Straßenkatze der Neonstadt, bis eine Oni-Maske sie fand und nicht mehr losließ.
## Sie weiß nicht, ob die Maske sie stark macht – oder ob sie ohne sie nichts ist. Der Himmelsfuchs
## kennt die Maske von früher, Asmodeus bietet die Krone der Nacht, und unter der Maske wartet ein Kind.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die Maske",
	"summary": "Shira war eine Straßenkatze ohne Namen, bis eine Oni-Maske sie fand. Seitdem fürchtet sie jeder. Aber wer ist sie, wenn sie die Maske abnimmt?",
	"relic": "Das Halsband mit Glöckchen",
	"relic_text": "Ein billiges rotes Halsband mit einem Glöckchen. Jemand hat es einem Straßenkind geschenkt, lange bevor eine Maske kam. Es klingelt bei jedem Schritt – und das ist gut so.",
}

const CAST := {
	"hero": {"preset": "shira", "name": "SHIRA", "title": "Die Oni-Klinge", "color": "c084fc"},
	"fox": {"preset": "celestial_fox", "name": "HIMMELSFUCHS", "title": "Kennt die Maske", "color": "fde68a"},
	"momo": {"preset": "lepora", "name": "MOMO", "title": "Straßenkind, wie sie früher", "color": "fda4af"},
	"gang": {"preset": "swat_specops", "name": "NEONBANDE", "title": "Will das Viertel", "color": "f472b6"},
	"gang2": {"preset": "don_valente", "name": "NEONBANDE", "title": "Will das Viertel", "color": "f472b6"},
	"asmodeus": {"boss": "asmodeus", "name": "ASMODEUS", "title": "König der Begierde", "color": "be123c"},
	"oni": {"preset": "shira", "name": "DIE ONI-MASKE", "title": "Was durch sie spricht", "color": "7f1d1d"},
}

static func chapters() -> Array:
	return [
		{"id": "shira_1", "title": "Die Katze vom Neonviertel", "arena": "neon_metropolis", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["gang", 2.8, -1], ["gang2", 4.0, -1], ["momo", -3.5, 1]]),
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "SHIRA · DIE MASKE", "sub": "Kapitel I – Die Katze vom Neonviertel"},
			S._narr("Im Neonviertel nennt man sie nur die Oni-Klinge. Eine Gestalt mit roter Dämonenmaske, die nachts über die Dächer springt. Die Banden zahlen Schutzgeld – an sie."),
			S._narr("Niemand weiß, dass unter der Maske eine junge Frau steckt, die früher in Mülltonnen nach Fischköpfen gesucht hat."),
			S._cam("two", 0, 1.4, 1),
			S._say("gang", "Das Viertel gehört ab heute uns. Die Katze hat ausgeschnurrt."),
			S._say("hero", "Neun Leben? Ich brauche nur eins. Deins."),
			S._cam("close", 0, 1.4),
			S._narr("Die Worte kommen aus ihrem Mund. Aber sie hat sie nicht gedacht. Sie denkt sie nie. Die Maske spricht schneller."),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 8, "time": 2.4, "text": "KRALLENSTURM!", "flag": "shira_claws",
				"success": [S._narr("Ein Wirbel aus Klingen und Neonlicht. Die Bande weicht zurück.")],
				"fail": [S._narr("Shira zögert. Die Maske knurrt in ihrem Kopf: Schneller!")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "gang", "gang2"], "goal": "VERTEIDIGE DAS NEONVIERTEL!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "shira_claws", "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.6, 3),
			S._say("momo", "Du bist die Oni-Klinge! Wow! Ich will auch so werden wie du! Wo kriegt man so eine Maske?"),
			S._say("hero", "Man kriegt sie nicht. Sie kriegt einen."),
			S._say("momo", "Hast du Hunger? Ich hab einen Fischkopf. Den kannst du haben."),
			S._say("hero", "Fischköpfe? Die … die habe ich früher auch gegessen."),
			S._say("momo", "Echt? Die Oni-Klinge hat Fischköpfe gegessen? Dann bist du ja wie ich!"),
			S._cam("close", 0, 1.4),
			S._narr("Für einen Moment, nur einen, lacht Shira. Und die Maske wird still."),
			S._narr("Dann knurrt sie wieder in ihrem Kopf: Schwäche. Weg mit dem Kind. Shira gehorcht nicht. Zum ersten Mal seit drei Jahren gehorcht sie nicht."),
			S._say("hero", "Du schläfst heute auf meinem Dach, Kleine. Da ist es warm. Wegen der Lüftung."),
		]},
		{"id": "shira_2", "title": "Der Fuchs auf dem Dach", "arena": "bg_holo_city", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["fox", 2.5, -1], ["momo", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Fuchs auf dem Dach"},
			S._narr("Seit Momo da ist, schläft die Maske manchmal. Shira träumt dann – von einem Glöckchen, von einer Hand, die ihr Milch hinstellt."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("fox", "Ich kenne die Maske, Kätzchen. Ich habe sie vor dreihundert Jahren einem Dämon abgeluchst. Und dann verloren. Sie gehört mir."),
			S._say("hero", "Sie gehört niemandem. Sie nimmt sich, was sie will."),
			S._say("fox", "Die Maske spricht durch dich. Hörst du dich überhaupt noch selbst?"),
			{"t": "choice", "text": "Was tut Shira?", "options": [
				{"label": "Die Maske verteidigen", "flag": "shira_kept", "steps": [
					S._say("hero", "Ohne sie bin ich nichts. Eine Straßenkatze. Du kriegst sie nicht, Fuchs."),
					S._say("fox", "Dann muss ich sie dir vom Gesicht kratzen. Tut mir leid. Nicht sehr.")]},
				{"label": "Den Fuchs um Rat fragen", "flag": "shira_asked", "steps": [
					S._say("hero", "Wie bekomme ich sie ab? Ich habe es versucht. Sie hält fest."),
					S._say("fox", "Ehrliche Frage. Selten. Erst kämpfst du – mit der Maske, gegen mich. Dann sehe ich, wie tief sie sitzt.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "fox"], "goal": "KATZE GEGEN FUCHS!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "shira_asked", "steps": [
				S._say("fox", "Sie sitzt tief. Aber nicht ganz. Da ist etwas darunter, das sie nicht erreicht. Ein Glöckchen. Hörst du es?"),
				S._say("hero", "Ich … ja. Ganz leise."),
			], "else": [
				S._say("fox", "Sie sitzt tiefer, als ich dachte. Pass auf, Kätzchen. Der, der sie gemacht hat, wird sie zurückwollen. Und dich gleich mit."),
			]},
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht verschwindet Momo. Auf ihrem Schlafplatz liegt eine schwarze Rose. Die Maske flüstert: Er ruft uns."),
		]},
		{"id": "shira_3", "title": "Die Krone der Nacht", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["asmodeus", 3.0, -1], ["fox", -4.0, 1], ["momo", 5.0, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Krone der Nacht"},
			S._narr("Hinter dem Höllentor wartet ein Thron. Daneben sitzt Momo, eingeschlafen, in einen Mantel aus Samt gewickelt."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("asmodeus", "Meine Maske. Und ihre hübsche Trägerin. Ich habe dich beobachtet. Du bist die Beste, die sie je hatte."),
			S._say("asmodeus", "Trag sie für immer, und ich mache dich zur Königin der Nacht. Jede Stadt, jedes Dach, jeder Schatten gehört dir. Die Kleine darf deine Dienerin sein."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Für immer … dann wäre ich nie wieder die Katze aus der Mülltonne."),
			S._say("asmodeus", "Nie wieder. Zieh die Maske ab, und keiner wird dich mehr fürchten. Willst du das?"),
			S._cam("two", 0, 1.6, 3),
			S._narr("Momo regt sich im Schlaf. Sie murmelt: Shira, hast du Hunger?"),
			S._say("hero", "Sie hat keine Angst vor mir. Sie hat nie Angst gehabt. Das ist besser als jede Krone."),
			S._music("boss"),
			{"t": "branch", "flag": "shira_asked", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("fox", "Ich habe die Maske einmal von ihm gestohlen. Ich helfe gern, sie ein zweites Mal zu stehlen. Diesmal für immer."),
				{"t": "fight", "cast": ["hero", "fox", "asmodeus"], "goal": "VERWEIGERE DIE KRONE DER NACHT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "fight", "cast": ["hero", "asmodeus"], "goal": "VERWEIGERE DIE KRONE DER NACHT!", "lives": [3, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Asmodeus verschwindet in einer Wolke aus Rosenblättern. Shira hebt Momo auf. Die Kleine wacht nicht auf. Sie schnurrt fast."),
		]},
		{"id": "shira_4", "title": "Das Gesicht darunter", "arena": "bg_neon_alley", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["oni", 2.0, -1], ["momo", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das Gesicht darunter"},
			S._narr("Die Gasse, in der sie aufgewachsen ist. Dieselbe Mülltonne. Dasselbe flackernde Neonschild. Shira greift an die Maske."),
			S._cam("two", 0, 1.6, 2),
			S._say("momo", "Was ist, wenn du darunter hässlich bist? Ist mir egal. Ich will es nur sehen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("oni", "Ich habe dich groß gemacht, Katze. Ich habe dir Krallen gegeben, einen Namen, Angst in den Augen der anderen. Ohne mich bist du Müll."),
			S._say("hero", "Ohne dich bin ich hungrig und klein und habe ein Glöckchen. Und jemand teilt seinen Fischkopf mit mir."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "oni"], "goal": "REISS DIE MASKE AB!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._narr("Die Maske fällt. Sie zerbricht auf dem Asphalt in zwei Hälften und ist nur noch bemaltes Holz."),
			S._narr("Darunter: ein Gesicht mit Sommersprossen. Ein bisschen müde. Ein bisschen erschrocken. Ganz normal."),
			S._cam("two", 0, 1.6, 2),
			S._say("momo", "Du siehst aus wie jemand, der Fischköpfe mag."),
			S._say("hero", "Ich hasse Fischköpfe. Ich habe sie nur gegessen, weil es nichts anderes gab."),
			S._say("momo", "Dann teilen wir morgen ein Brötchen. Ich weiß, wo eins ist."),
			S._say("hero", "Ohne Maske bin ich langsamer. Und leiser. Die Banden werden zurückkommen."),
			S._say("momo", "Dann kommen sie eben. Du hast sie mit Maske verjagt. Ohne Maske verjagst du sie halt mit Glöckchen."),
			S._narr("Shira kramt in ihrer Tasche. Ganz unten, unter Klingen und Schutzgeld, liegt ein rotes Halsband mit einem Glöckchen. Jemand hat es ihr geschenkt, lange bevor die Maske kam."),
			S._say("hero", "Ich hatte vergessen, dass ich es noch habe. Ich hatte vergessen, wer es mir geschenkt hat. … Eine alte Frau. Sie hat mir Milch hingestellt."),
			S._narr("Auf dem Neonviertel liegt kein Schutzgeld mehr. Nur zwei Katzen, die über die Dächer laufen. Eine mit Glöckchen."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Shira · Die Maske"},
			S._narr("Relikt erhalten: Das Halsband mit Glöckchen  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
