extends RefCounted
## Legende: ARBËR, DER BOHRMEISTER – „Die Besa“.
## Ein Versprechen an einen sterbenden Freund: das Haus seiner Familie vor dem ersten Schnee
## wieder aufzubauen. Ein Goblin, der alles in die Luft jagt, ein Kriegsdämon, der vom Zorn lebt,
## und die Frage, ob ein Versprechen stärker ist als der Zweifel. Hier erscheint zum ersten Mal
## die Shqiponja, der Doppelkopfadler.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die Besa",
	"summary": "Arbër hat Ilir am Sterbebett geschworen, das Haus seiner Familie vor dem ersten Schnee wieder aufzubauen. Ein Wort ist ein Fels – doch der Winter kommt früh.",
	"relic": "Ilirs Wasserwaage",
	"relic_text": "Die alte Wasserwaage seines Freundes. Die Blase steht immer in der Mitte – so wie ein gehaltenes Wort.",
}

const CAST := {
	"hero": {"preset": "arber", "name": "ARBËR", "title": "Der Bohrmeister", "color": "e41e20"},
	"ilir": {"preset": "samurai_dreyar", "name": "ILIR", "title": "Sein ältester Freund", "color": "cbd5e1"},
	"drita": {"preset": "lepora", "name": "DRITA", "title": "Ilirs Tochter", "color": "fde68a"},
	"grimbolt": {"preset": "grimbolt", "name": "GRIMBOLT", "title": "Goblin mit Zündschnur", "color": "84cc16"},
	"looter": {"preset": "swat_specops", "name": "PLÜNDERER", "title": "Kommt nach jedem Unglück", "color": "94a3b8"},
	"looter2": {"preset": "pirate_captain", "name": "PLÜNDERIN", "title": "Kommt nach jedem Unglück", "color": "94a3b8"},
	"marduk": {"boss": "bel_marduk", "name": "BEL MARDUK", "title": "Der Krieg", "color": "ff3b30"},
	"zweifel": {"preset": "arber", "name": "ARBËR, DER ZWEIFLER", "title": "Der Teil von ihm, der aufgeben will", "color": "64748b"},
}

static func chapters() -> Array:
	return [
		{"id": "arber_1", "title": "Das Wort am Bett", "arena": "bg_foundry", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["ilir", 1.2, -1], ["looter", 9.0, -1], ["looter2", 10.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "ARBËR · DIE BESA", "sub": "Kapitel I – Das Wort am Bett"},
			S._narr("In den Bergen, wo die Adler wohnen, sagt man: Ein Wort ist ein Fels. Wer es bricht, dem fällt der Berg auf den Kopf."),
			S._narr("Ein Erdbeben hat das Dorf getroffen. Ilirs Haus ist eingestürzt – und Ilir lag darunter."),
			S._cam("two", 0, 2.0, 1),
			S._pose(1, "Dazed", 1.0),
			S._say("ilir", "Arbër … mein Haus. Drita und die Kleinen haben keinen Winter mehr, wenn es nicht steht."),
			S._say("hero", "Red nicht so. Du baust es selbst wieder auf. Ich halte dir nur die Leiter."),
			S._say("ilir", "Versprich es mir. Nicht als Freund. Als Albaner. Gib mir deine Besa."),
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 0.8),
			S._narr("Die Besa ist kein Satz, den man leicht sagt. Sie ist ein Stein, den man sein Leben lang trägt."),
			S._say("hero", "Du hast meine Besa, Ilir. Vor dem ersten Schnee steht dein Haus. Mit jedem Stein."),
			S._pose(1, "Defeat", 1.2),
			{"t": "vanish", "who": 1},
			S._music("calm"),
			S._narr("Ilir lächelte. Dann wurde es still in der Werkstatt."),
			S._cam("low", 0, 1.8),
			{"t": "fx", "kind": "shake"},
			S._narr("Doch noch in derselben Nacht kamen die, die nach jedem Unglück kommen."),
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3},
			{"t": "move", "who": 2, "x": 3.0, "time": 1.0},
			{"t": "move", "who": 3, "x": 4.6, "time": 1.2},
			S._cam("two", 0, 1.2, 2),
			S._say("looter", "Ein Toter braucht kein Werkzeug, Alter. Wir nehmen die Bohrer und das Kupfer."),
			S._say("hero", "Das sind Ilirs Werkzeuge. Und ich habe heute Nacht ein Versprechen gegeben. Ihr seid zur falschen Zeit gekommen."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "BOHRER ANWERFEN!", "flag": "arber_spinup",
				"success": [S._narr("Zwei Motoren heulen auf. Die Plünderer zucken zusammen.")],
				"fail": [S._narr("Der Akku stottert. Die Plünderer lachen.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "looter", "looter2"], "goal": "SCHÜTZE ILIRS WERKSTATT!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "arber_spinup", "ai": 3},
			S._music("calm"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Victory", 1.0),
			S._narr("Am Morgen packte Arbër Ilirs alte Wasserwaage ein. Die Blase stand genau in der Mitte."),
			S._say("hero", "Vierzig Tage bis zum ersten Schnee. Hajde, Arbër. Fang an."),
		]},
		{"id": "arber_2", "title": "Der Goblin mit der Zündschnur", "arena": "bg_warehouse", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["drita", -3.4, 1], ["grimbolt", 3.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("hope"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Goblin mit der Zündschnur"},
			S._narr("Zwanzig Tage später. Die Grundmauern stehen. Drita trägt die Steine, Arbër bohrt die Anker."),
			S._cam("two", 0, 1.6, 1),
			S._say("drita", "Du schläfst nicht, Onkel Arbër. Vater hätte geschimpft."),
			S._say("hero", "Dein Vater hat mir die Leiter nie gehalten, wenn ich geschimpft habe. Er hat einfach weitergebaut."),
			{"t": "fx", "kind": "flash"},
			{"t": "fx", "kind": "shake"},
			S._narr("BUMM. Die Ostmauer – eben noch gerade – liegt in Stücken im Schlamm."),
			{"t": "appear", "who": 2},
			S._cam("close", 2, 1.2),
			S._pose(2, "Victory", 0.8),
			S._say("grimbolt", "Hehe! Entschuldigung! Das war eine Probe. Meine Zeitbombe tickt jetzt mit zwei Sekunden Verspätung, nicht mehr mit drei!"),
			S._say("hero", "Du hast eine Mauer gesprengt, die ein Versprechen trägt."),
			S._say("grimbolt", "Mauern! Langweilig! Alle bauen Mauern. Niemand will mal etwas Schönes, das BUMM macht."),
			S._cam("two", 0, 1.2, 2),
			{"t": "choice", "text": "Was macht Arbër mit dem Goblin?", "options": [
				{"label": "Jag ihn davon", "flag": "arber_chased", "steps": [
					S._say("hero", "Verschwinde von dieser Baustelle, bevor ich dich in die Ostmauer einbetoniere."),
					S._say("grimbolt", "Pah! Dann eben auf die harte Tour!")]},
				{"label": "Gib ihm Arbeit", "flag": "arber_hired", "steps": [
					S._say("hero", "Du kannst sprengen? Gut. Am Hang liegt ein Fels, der das Fundament blockiert. Sprengen, nicht das Haus."),
					S._say("grimbolt", "Ein … Auftrag? Für MICH? Ich – na gut, aber erst prüfe ich, ob du es wert bist!")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "grimbolt"], "goal": "BEVOR DIE ZÜNDSCHNUR ABBRENNT!", "lives": [2, 2], "time": 90, "ai": 4},
			S._music("hope"),
			{"t": "branch", "flag": "arber_hired", "steps": [
				S._cam("two", 0, 1.4, 2),
				S._say("grimbolt", "Du kämpfst wie mein Großvater. Der hat auch nie aufgegeben, obwohl er alles falsch gemacht hat."),
				S._say("grimbolt", "Gut. Ich sprenge deinen Fels. Und nur den Fels! Grimbolt-Ehrenwort. Ist das so was wie deine Besa?"),
				S._say("hero", "Fast. Bei uns explodiert man nicht, wenn man sie bricht. Aber es fühlt sich so an."),
			], "else": [
				S._cam("close", 2, 1.2),
				S._say("grimbolt", "Na gut, na gut, ich gehe! Aber ich komme wieder. Mit einer GRÖSSEREN Bombe!"),
				{"t": "move", "who": 2, "x": 9.0, "time": 1.0},
				S._say("drita", "Er wird wiederkommen."),
				S._say("hero", "Dann bauen wir die Mauer eben zweimal."),
			]},
			S._cam("low", 0, 1.8),
			S._narr("In dieser Nacht träumte Arbër von einem schwarzen Adler mit zwei Köpfen. Der eine sah nach vorne. Der andere zurück."),
		]},
		{"id": "arber_3", "title": "Der Saal der zerbrochenen Häuser", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["marduk", 3.0, -1], ["drita", -4.0, 1], ["grimbolt", -4.6, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Saal der zerbrochenen Häuser"},
			S._narr("Zehn Tage vor dem Schnee bebt die Erde ein zweites Mal. Diesmal reißt sie auf – und zieht Arbër hinunter."),
			S._narr("Er erwacht in einem endlosen Saal. Überall Häuser. Halbe Häuser, verbrannte Häuser, Häuser ohne Dach. Alle, die er nicht retten konnte."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("marduk", "Bohrmeister. Ich bin der Zorn, der nach jedem Erdbeben kommt. Ich habe gezählt: Dreiundzwanzig Häuser hast du versprochen. Neun stehen."),
			S._say("marduk", "Gib mir deine Wut. Dann musst du nie wieder etwas versprechen. Dann zerbricht nichts mehr – weil dir nichts mehr wichtig ist."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Neun stehen. Neun Familien haben ein Dach. Du zählst die falschen Häuser, Dämon."),
			{"t": "fx", "kind": "flash"},
			S._music("boss"),
			S._narr("Da schreit es hoch über dem Saal. Ein Schatten mit zwei Köpfen stürzt herab und packt Arbër an den Schultern."),
			S._narr("Die Shqiponja. Der Adler der Berge, den die Alten nur in Liedern kannten. Er trägt nur die, die ihr Wort halten."),
			{"t": "branch", "flag": "arber_hired", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("grimbolt", "Ich hab ein Loch in die Hölle gesprengt! Nur ein kleines! Ich helfe dir, Partner!"),
				{"t": "fight", "cast": ["hero", "grimbolt", "marduk"], "goal": "FLIEG MIT DER SHQIPONJA – BESIEGE DEN ZORN!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("drita", "Ich bin dem Adler gefolgt! Vater hätte dich nicht allein gelassen. Ich auch nicht."),
				{"t": "fight", "cast": ["hero", "drita", "marduk"], "goal": "FLIEG MIT DER SHQIPONJA – BESIEGE DEN ZORN!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._cam("close", 0, 1.6),
			S._narr("Bel Marduk zerfällt zu Staub und Mörtel. Die zerbrochenen Häuser im Saal bleiben – aber sie sehen nicht mehr aus wie Vorwürfe. Nur wie Arbeit."),
			S._say("hero", "Shqiponja. Bring mich nach Hause. Ich habe noch ein Dach zu decken."),
		]},
		{"id": "arber_4", "title": "Das Haus am Hang", "arena": "frozen_summit", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["zweifel", 2.0, -1], ["drita", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das Haus am Hang"},
			S._narr("Der letzte Abend vor dem Schnee. Das Haus hat Mauern, Fenster, eine Tür. Nur das Dach fehlt noch – und die Kraft."),
			S._cam("two", 0, 1.6, 2),
			S._say("drita", "Morgen schneit es, Onkel Arbër. Wir schaffen das Dach nicht mehr. Es ist nicht schlimm. Wir ziehen zu Tante Mira."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._narr("Arbër setzt sich auf einen Balken. Seine Hände zittern. Und aus seinem Schatten steht jemand auf, der genauso aussieht wie er."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("zweifel", "Gib auf. Niemand wird es dir übelnehmen. Ilir ist tot, er sieht es nicht. Eine Besa für einen Toten ist nur Stolz."),
			S._say("hero", "Eine Besa für einen Toten ist die schwerste. Weil nur noch ich weiß, dass es sie gibt."),
			S._say("zweifel", "Dann beweis es. Hier oben, in der Kälte. Ohne Adler, ohne Hilfe. Nur du und ich."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "zweifel"], "goal": "BESIEGE DEINEN ZWEIFEL!", "lives": [2, 2], "damage": {"0": 40}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 2.0),
			S._pose(0, "Charge", 1.0),
			S._narr("Arbër steht auf. Er bohrt die erste Dachlatte fest. Dann die zweite. Er hört nicht auf, als die Nacht kommt."),
			S._narr("Gegen Mitternacht hört er Schritte. Das ganze Dorf steigt den Hang hinauf – mit Laternen, Ziegeln und Leitern."),
			{"t": "branch", "flag": "arber_hired", "steps": [
				S._narr("Vorneweg ein kleiner grüner Goblin, der zum ersten Mal in seinem Leben etwas baut, das nicht explodiert."),
			], "else": [
				S._narr("Und ganz hinten ein kleiner grüner Goblin, der so tut, als sei er nur zufällig da – und dann die meisten Ziegel trägt."),
			]},
			S._cam("two", 0, 1.6, 2),
			S._say("drita", "Du hast nie gefragt, ob dir jemand hilft."),
			S._say("hero", "Eine Besa gibt man allein. Aber halten … halten kann man sie zusammen."),
			S._cam("sky", 0, 3.0),
			S._narr("Bei Sonnenaufgang fällt der erste Schnee. Er bleibt auf einem roten Dach liegen. Über den Bergen kreist ein schwarzer Adler mit zwei Köpfen."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Arbër · Die Besa"},
			S._narr("Relikt erhalten: Ilirs Wasserwaage  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
