extends RefCounted
## Legende: XYLAR, DER LEERENKAISER – „Satt“.
## Xylar herrscht über ein Reich aus Nichts und verschlingt Welten, weil er nicht weiß, was satt sein ist.
## Ein Prophet hat seinen Untergang gesehen, ein Straßenkoch bietet ihm eine Schale Suppe an,
## und Beelzebub, die Gier, will ihn endgültig zu seinem Diener machen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Satt",
	"summary": "Xylar hat hundert Welten verschlungen und ist hungrig wie am ersten Tag. Ein Prophet sagt seinen Untergang voraus – und ein Straßenkoch stellt ihm eine Schale Suppe hin.",
	"relic": "Die leere Suppenschale",
	"relic_text": "Eine angeschlagene Schale aus der Neonstadt. Leer gegessen. Das Erste, was der Leerenkaiser je bis zum Boden geleert hat, ohne dass danach etwas fehlte.",
}

const CAST := {
	"hero": {"preset": "xylar", "name": "XYLAR", "title": "Der Leerenkaiser", "color": "a855f7"},
	"oryn": {"preset": "oryn", "name": "ORYN", "title": "Der Prophet, der ihn fallen sah", "color": "818cf8"},
	"koch": {"preset": "bruno", "name": "MEISTER BAO", "title": "Garküche Ecke 7", "color": "fbbf24"},
	"guard": {"preset": "vanguard_soldier", "name": "STADTGARDE", "title": "Letzte Verteidigung", "color": "94a3b8"},
	"guard2": {"preset": "swat_specops", "name": "STADTGARDE", "title": "Letzte Verteidigung", "color": "94a3b8"},
	"beelzebub": {"boss": "beelzebub", "name": "BEELZEBUB", "title": "Herr der Gier", "color": "65a30d"},
	"hunger": {"preset": "xylar", "name": "DER HUNGER", "title": "Was in der Krone wohnt", "color": "3b0764"},
}

static func chapters() -> Array:
	return [
		{"id": "xylar_1", "title": "Die hundertste Welt", "arena": "neon_metropolis", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["guard", 2.5, -1], ["guard2", 3.8, -1], ["oryn", 9.0, -1]]),
			{"t": "vanish", "who": 3},
			S._music("boss"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "XYLAR · SATT", "sub": "Kapitel I – Die hundertste Welt"},
			S._narr("Neunundneunzig Welten hat Xylar verschlungen. Ihre Sterne sind Perlen in seiner Krone, ihre Meere Tinte in seinem Thronsaal."),
			S._narr("Die hundertste Welt ist eine Stadt aus Neon. Sie leuchtet so hell, dass er sie aus dem Nichts heraus gerochen hat."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Hundert. Eine runde Zahl. Vielleicht ist es diesmal genug. Vielleicht bin ich danach endlich satt."),
			S._cam("two", 0, 1.4, 1),
			S._say("guard", "Halt! Im Namen der Stadt – zieh dein Loch aus unserem Himmel zurück!"),
			S._say("hero", "Ein Loch? Das ist meine Krone, Sterblicher. Und ihr seid die Vorspeise."),
			S._say("guard2", "Feuer frei! Alles, was wir haben!"),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "NADELSTRAHL!", "flag": "xylar_needle",
				"success": [S._narr("Ein violetter Faden durchsticht die Schilde der Garde. Sie wanken.")],
				"fail": [S._narr("Der Strahl verpufft im Neonlicht. Diese Stadt ist hartnäckiger als die letzten.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "guard", "guard2"], "goal": "VERSCHLINGE DEN WIDERSTAND!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "xylar_needle", "ai": 3},
			S._music("tense"),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": 3.0, "time": 1.0},
			S._cam("two", 0, 1.6, 3),
			S._say("oryn", "Leerenkaiser. Ich habe deinen Untergang gesehen. In tausend Nächten, immer gleich."),
			S._say("hero", "Propheten. Ich habe hundert gefressen. Sie schmecken alle nach Angst."),
			S._say("oryn", "Du fällst nicht durch ein Schwert. Du fällst, weil du eines Tages satt bist – und nicht weißt, was dann."),
			S._cam("close", 0, 1.4),
			S._narr("Zum ersten Mal seit Äonen zögert Xylar. Der Prophet hat das eine Wort gesagt, das er nicht kennt."),
			S._say("hero", "Satt. Was soll das sein? Ein Zustand? Eine Krankheit?"),
			S._say("oryn", "Ein Gefühl. Man isst, und danach fehlt nichts. Die meisten Menschen kennen es. Du nicht. Darum fällst du."),
			S._narr("Der Prophet geht. Der Kaiser verschlingt die Stadt nicht – noch nicht. Er will erst wissen, was dieses Wort schmeckt."),
		]},
		{"id": "xylar_2", "title": "Garküche Ecke 7", "arena": "bg_night_market", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["koch", 1.5, -1], ["oryn", 4.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Garküche Ecke 7"},
			S._narr("Xylar wandert durch den Nachtmarkt. Die Leute fliehen vor ihm. Nur ein dicker Mann hinter einem dampfenden Topf bleibt stehen."),
			S._cam("two", 0, 1.6, 1),
			S._say("koch", "Du siehst hungrig aus. Setz dich. Nudelsuppe, scharf. Drei Münzen."),
			S._say("hero", "Ich verschlinge Welten, Koch. Glaubst du, eine Schale Suppe ändert etwas?"),
			S._say("koch", "Keine Ahnung. Hast du es mal probiert? Langsam? Mit Löffel?"),
			S._cam("close", 0, 1.4),
			S._narr("Niemand hat Xylar je etwas angeboten. Man hat ihm Tribut gezahlt, Opfer gebracht, Städte überlassen. Angeboten nie."),
			{"t": "choice", "text": "Was tut Xylar?", "options": [
				{"label": "Sich setzen", "flag": "xylar_soup", "steps": [
					S._narr("Der Leerenkaiser setzt sich auf einen Plastikhocker. Er ist zu groß dafür. Der Hocker hält trotzdem."),
					S._say("koch", "Erst essen, dann reden. Aber vorher – du zahlst nicht mit Welten. Du hilfst mir, den Topf zu tragen. Wenn du ihn heben kannst.")]},
				{"label": "Den Topf verschlingen", "flag": "xylar_devour", "steps": [
					S._say("hero", "Ich nehme alles. Den Topf. Den Stand. Dich."),
					S._say("koch", "Dann musst du erst an mir vorbei. Ich habe dreißig Jahre Nudeln gezogen. Meine Arme sind härter als dein Nichts.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "koch"], "goal": "DER KOCH MACHT KEINE AUSNAHMEN!", "lives": [2, 2], "ai": 4},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "xylar_soup", "steps": [
				S._say("koch", "Na also. Hier. Langsam essen. Nicht schlingen."),
				S._narr("Xylar isst. Langsam. Er schmeckt Chili, Ingwer, Brühe, die seit Stunden zieht. Er schmeckt, dass jemand sich Mühe gegeben hat."),
				S._say("hero", "Das ist … seltsam. Es ist weg, und trotzdem fehlt nichts."),
			], "else": [
				S._say("koch", "Du hast gewonnen. Bitte. Iss den Topf. Er ist leer. Ich koche morgen einen neuen."),
				S._say("hero", "Warum lachst du? Ich habe dir alles genommen."),
				S._say("koch", "Einen Topf. Mein Rezept hast du nicht. Das kann man nicht fressen."),
			]},
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.4, 2),
			S._say("oryn", "Hörst du das, Kaiser? Das Summen in deiner Krone? Etwas anderes ist auch hungrig. Und es kommt dich holen."),
		]},
		{"id": "xylar_3", "title": "Das Festmahl der Fliegen", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["beelzebub", 3.0, -1], ["koch", -4.0, 1], ["oryn", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das Festmahl der Fliegen"},
			S._narr("Das Summen wird zum Brausen. Xylar wird durch seine eigene Krone gezogen – in eine Stadt, in der Tische bis zum Horizont stehen. Alle gedeckt. Alle leer."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("beelzebub", "Mein bester Kunde! Neunundneunzig Welten – und jede hast du für mich gefressen. Du wusstest es nicht? Dein Hunger ist meiner."),
			S._say("beelzebub", "Ich habe ihn dir eingepflanzt, als du noch ein kleiner Stern warst. Ein Kaiser, der nie satt wird. Das perfekte Maul."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Mein Hunger … gehört nicht mir?"),
			S._say("beelzebub", "Nichts gehört dir. Du bist leer. Und das Schlimmste: Du warst es immer."),
			S._say("hero", "Gestern war ich das nicht. Gestern habe ich eine Schale Suppe gegessen. Die gehört mir."),
			S._music("boss"),
			{"t": "branch", "flag": "xylar_soup", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("koch", "Du hast meinen Topf noch. Den will ich zurück. Und du schuldest mir drei Münzen."),
				{"t": "fight", "cast": ["hero", "koch", "beelzebub"], "goal": "VERDIRB DAS FESTMAHL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("oryn", "In tausend Nächten sah ich dich fallen. In keiner sah ich dich hier. Vielleicht irren Propheten doch."),
				{"t": "fight", "cast": ["hero", "oryn", "beelzebub"], "goal": "VERDIRB DAS FESTMAHL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Die Fliegen stieben auseinander. Die endlosen Tische kippen. Aus Xylars Krone löst sich ein Stern nach dem anderen – und fliegt nach Hause."),
		]},
		{"id": "xylar_4", "title": "Satt", "arena": "bg_neon_skyline", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["hunger", 2.0, -1], ["oryn", -3.5, 1], ["koch", -4.6, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Satt"},
			S._narr("Neunundneunzig Sterne sind zurückgekehrt. Xylars Krone ist fast leer. Nur ein dunkles Loch bleibt in der Mitte – und es pulsiert."),
			S._cam("two", 0, 1.6, 2),
			S._say("oryn", "Das ist der Moment, den ich sah. Der Kaiser ist satt. Und weiß nicht, was dann."),
			S._say("hero", "Was dann, Prophet? Sag es mir. Du hast es doch gesehen."),
			S._say("oryn", "Ich sah nur bis hierhin. Danach war … nichts. Kein Untergang. Einfach nichts mehr, das ich sehen durfte."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("hunger", "Ich bin nicht Beelzebubs. Ich bin DEINER. Was bleibt von dir ohne mich? Ein Mann ohne Reich auf einem Plastikhocker."),
			S._say("hero", "Ja. Genau das. Ein Mann auf einem Plastikhocker. Das klingt besser als alles, was ich hatte."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "hunger"], "goal": "BESIEGE DEN HUNGER!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._narr("Das Loch in der Krone schließt sich. Xylar nimmt sie ab. Sie ist leicht. Sie war nie schwer – nur hungrig."),
			S._cam("two", 0, 1.6, 3),
			S._say("koch", "Morgen früh, sechs Uhr. Der Teig muss gezogen werden. Mit so großen Händen bist du schneller als ich."),
			S._say("hero", "Ein Kaiser zieht keine Nudeln."),
			S._say("koch", "Du bist kein Kaiser mehr. Du bist hungrig auf Frühstück, wie jeder andere auch."),
			S._narr("Und der ehemalige Leerenkaiser lacht. Zum ersten Mal. Es klingt nicht leer."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Xylar · Satt"},
			S._narr("Relikt erhalten: Die leere Suppenschale  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
