extends RefCounted
## Legende: VANGUARD – „Stellung gehalten“.
## Vanguard war die Spitze einer Armee, die nie ankam. Er hält seine Stellung seit sieben Jahren,
## und niemand hat ihm gesagt, dass der Krieg vorbei ist. Ein SWAT-Agent soll ihn räumen, Potestas
## befiehlt ihm, ewig weiterzukämpfen – und am Ende muss er den letzten Befehl selbst geben.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Stellung gehalten",
	"summary": "Vanguard hält seit sieben Jahren eine Stellung für eine Armee, die nie kam. Niemand hat ihm gesagt, dass der Krieg vorbei ist – und er hat nie gefragt.",
	"relic": "Das stumme Funkgerät",
	"relic_text": "Ein altes Feldfunkgerät, die Batterie seit Jahren leer. Wenn man es ans Ohr hält, hört man trotzdem etwas: Vögel.",
}

const CAST := {
	"hero": {"preset": "vanguard_soldier", "name": "VANGUARD", "title": "Die letzte Vorhut", "color": "60a5fa"},
	"agent": {"preset": "swat_specops", "name": "SWAT-AGENT", "title": "Soll die Stellung räumen", "color": "94a3b8"},
	"lena": {"preset": "lepora", "name": "LENA", "title": "Bringt jeden Tag Brot", "color": "fde68a"},
	"pluenderer": {"preset": "mutant_titan", "name": "SCHROTTSAMMLER", "title": "Will die Kanone", "color": "a8a29e"},
	"pluenderer2": {"preset": "grimbolt", "name": "SCHROTTSAMMLER", "title": "Will die Kanone", "color": "a8a29e"},
	"potestas": {"boss": "potestas", "name": "POTESTAS", "title": "Der ewige Befehl", "color": "fbbf24"},
	"befehl": {"preset": "vanguard_soldier", "name": "DER LETZTE BEFEHL", "title": "Was ihn aufrecht hält", "color": "1e3a8a"},
}

static func chapters() -> Array:
	return [
		{"id": "vanguard_soldier_1", "title": "Tag 2555", "arena": "bg_ruined_city", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["pluenderer", 2.8, -1], ["pluenderer2", 4.0, -1], ["lena", -3.5, 1]]),
			{"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "VANGUARD · STELLUNG GEHALTEN", "sub": "Kapitel I – Tag 2555"},
			S._narr("Vor sieben Jahren bekam Vanguard einen Befehl: Halte die Brücke, bis die Armee eintrifft. Er hält sie noch heute."),
			S._narr("Die Armee kam nie. Die Stadt dahinter wurde wieder aufgebaut, die Ruinen davor bewachsen. Vanguard meldet jeden Abend: Stellung gehalten. Niemand antwortet."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Vorhut an Hauptquartier. Tag zweitausendfünfhundertfünfundfünfzig. Stellung gehalten. Warte auf Befehle. Ende."),
			S._cam("two", 0, 1.4, 1),
			S._say("pluenderer", "Der Blechmann mit der Photonenkanone. Die bringt auf dem Schrottmarkt ein Vermögen. Und er ist allein."),
			S._say("pluenderer2", "Allein und verrückt! Er redet mit einem kaputten Funkgerät!"),
			S._say("hero", "Feindkontakt. Zwei Ziele. Stellung wird verteidigt."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "PHOTONEN-SALVE!", "flag": "vanguard_soldier_salvo",
				"success": [S._narr("Die Kanone summt, dann schlägt eine Salve vor den Schrottsammlern ein. Sie werfen sich in Deckung.")],
				"fail": [S._narr("Die Kanone klickt nur. Sieben Jahre ohne Wartung.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "pluenderer", "pluenderer2"], "goal": "HALTE DIE BRÜCKE!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "vanguard_soldier_salvo", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("lena", "Hier, dein Brot. Und eine Zeitung. Da steht wieder drin, dass der Krieg seit sieben Jahren vorbei ist. Lies sie doch mal."),
			S._say("hero", "Zeitungen können Propaganda sein. Ich warte auf einen offiziellen Befehl."),
			S._say("lena", "Du wartest auf Leute, die nicht mehr kommen. Ich bringe dir Brot, weil ich es nicht ertrage, dich verhungern zu sehen."),
			S._cam("close", 0, 1.4),
			S._narr("Er nimmt das Brot. Die Zeitung legt er ungelesen zu den anderen. Es sind zweitausend."),
			S._say("lena", "Warum bist du eigentlich so sicher, dass sie kommen?"),
			S._say("hero", "Mein Kommandant hat es mir versprochen. Er hat mir die Hand gegeben. Er hat noch nie gelogen."),
			S._say("lena", "Vielleicht hat er nicht gelogen. Vielleicht konnte er nur nicht mehr kommen."),
			S._narr("Vanguard antwortet nicht. In dieser Nacht meldet er sich zweimal beim Hauptquartier. Beim zweiten Mal flüstert er."),
		]},
		{"id": "vanguard_soldier_2", "title": "Räumungsbefehl", "arena": "neon_metropolis", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["agent", 2.5, -1], ["lena", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Räumungsbefehl"},
			S._narr("Die Stadt will die alte Brücke abreißen und eine neue bauen. Sie schickt ihren besten Mann, um den Soldaten zu räumen."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("agent", "Soldat. Der Krieg ist aus. Du bist ein Gespenst in Rüstung. Ich habe den Auftrag, dich hier wegzubringen. Freiwillig oder nicht."),
			S._say("hero", "Ich nehme Befehle nur vom Hauptquartier. Wer ist Ihr Kommandant?"),
			S._say("agent", "Die Stadtverwaltung. Abteilung Infrastruktur. Formular 27-B."),
			S._say("hero", "Kein gültiger Befehl."),
			{"t": "choice", "text": "Wie reagiert Vanguard?", "options": [
				{"label": "Verhandeln", "flag": "vanguard_soldier_talk", "steps": [
					S._say("hero", "Agent. Sie tragen auch eine Uniform. Wenn Ihnen jemand sagt, Ihr Einsatz ist vorbei – woher wissen Sie, dass es stimmt?"),
					S._say("agent", "… Gute Frage. Ich habe sie mir nie gestellt. Trotzdem: Befehl ist Befehl. Erst die Pflicht.")]},
				{"label": "Stellung verteidigen", "flag": "vanguard_soldier_hold", "steps": [
					S._say("hero", "Feindkontakt. Stellung wird verteidigt. Bis zum letzten Schuss."),
					S._say("agent", "Wie du willst. Zugriff. Jetzt.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "agent"], "goal": "SOLDAT GEGEN AGENT!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "vanguard_soldier_talk", "steps": [
				S._say("agent", "Wir sind gleich, du und ich. Wir wissen nicht, wer wir ohne Einsatz sind. Ich lasse dich noch einen Tag. Einen."),
			], "else": [
				S._say("agent", "Du kämpfst gut. Für nichts. Ich komme wieder. Mit mehr Leuten."),
				S._say("lena", "Hörst du dich eigentlich selbst? Bis zum letzten Schuss? Für eine Brücke?"),
			]},
			{"t": "fx", "kind": "flash"},
			S._narr("In der Nacht knistert das tote Funkgerät. Eine Stimme, klar wie Glas: Vorhut. Hier spricht das Oberkommando. Halten Sie die Stellung. Für immer."),
		]},
		{"id": "vanguard_soldier_3", "title": "Das Oberkommando", "arena": "heaven_spheres", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["potestas", 3.0, -1], ["agent", -4.0, 1], ["lena", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das Oberkommando"},
			S._narr("Die Stimme führt ihn hinauf. Über die Wolken, in eine Sphäre aus Gold und Ordnung. Dort steht ein Engel in Rüstung, mit einem Stab wie ein Marschallstab."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("potestas", "Soldat. Ich bin die Macht hinter jedem Befehl. Ich habe dich beobachtet. Sieben Jahre Treue. Vorbildlich."),
			S._say("potestas", "Kämpfe weiter. Ewig. Denn ein Soldat ohne Feind ist nichts. Ohne Befehl weißt du nicht, wer du bist."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Endlich ein Befehl. Sieben Jahre habe ich darauf gewartet."),
			S._narr("Er salutiert. Und dann, mitten im Salut, hält er inne. Er denkt an Brot. An eine Frau, die jeden Morgen kommt, obwohl niemand es ihr befohlen hat."),
			S._say("hero", "Sie haben mich sieben Jahre nicht gerufen. Lena kam jeden Tag. Ich weiß jetzt, wem ich gehorche."),
			S._music("boss"),
			{"t": "branch", "flag": "vanguard_soldier_talk", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("agent", "Formular 27-B ist ungültig, hast du gesagt. Dieser Engel hier hat gar keins. Ich bin dabei."),
				{"t": "fight", "cast": ["hero", "agent", "potestas"], "goal": "VERWEIGERE DEN EWIGEN BEFEHL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("lena", "Ich habe keine Kanone. Aber ich habe einen Brotkorb und bin sehr wütend!"),
				{"t": "fight", "cast": ["hero", "lena", "potestas"], "goal": "VERWEIGERE DEN EWIGEN BEFEHL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Potestas weicht zurück, verwirrt. Er kennt jede Form von Gehorsam. Aber noch nie hat ihm jemand aus Freundschaft widersprochen."),
		]},
		{"id": "vanguard_soldier_4", "title": "Ende der Meldung", "arena": "bg_ruined_city", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["befehl", 2.0, -1], ["lena", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Ende der Meldung"},
			S._narr("Zurück an der Brücke. Vanguard nimmt das Funkgerät in die Hand. Zum ersten Mal weiß er nicht, was er sagen soll."),
			S._cam("two", 0, 1.6, 2),
			S._say("lena", "Du musst nichts melden. Es hört keiner zu. Es hat nie jemand zugehört. Außer mir."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("befehl", "Halte die Brücke. Das bist du. Wenn du gehst, warst du sieben Jahre lang ein Narr. Willst du das zugeben?"),
			S._say("hero", "Ja. Ich war sieben Jahre lang ein Narr. Und das ist leichter zu tragen als noch ein Tag hier."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "befehl"], "goal": "GIB DIR DEN LETZTEN BEFEHL!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 1.0),
			S._say("hero", "Vorhut an … an mich. Einsatz beendet. Stellung wird aufgegeben. Gut gemacht, Soldat. Ende."),
			S._narr("Er legt die Photonenkanone auf die Brücke. Sie ist leichter, als er dachte. Er setzt sich daneben. Und hört zum ersten Mal Vögel statt Funkrauschen."),
			S._cam("two", 0, 1.6, 2),
			S._say("lena", "Und jetzt?"),
			S._say("hero", "Jetzt lese ich zweitausend Zeitungen. Und dann frage ich dich, wie man Brot backt."),
			S._say("lena", "Fang mit der ersten Zeitung an. Die von vor sieben Jahren. Da steht etwas über deinen Kommandanten."),
			S._narr("Vanguard liest. Der Kommandant fiel am ersten Tag des Waffenstillstands, auf dem Weg zur Brücke. In seiner Tasche fand man einen Befehl: Vorhut abziehen. Gut gemacht."),
			S._say("hero", "Er wollte kommen. Er war schon auf dem Weg. Er hat nicht gelogen."),
			S._say("lena", "Nein. Er hat nicht gelogen. Und du darfst jetzt nach Hause."),
			S._narr("Vanguard faltet die Zeitung zusammen und steckt sie in die Brusttasche, dorthin, wo sieben Jahre lang der Funkspruch stand."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Vanguard · Stellung gehalten"},
			S._narr("Relikt erhalten: Das stumme Funkgerät  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
