extends RefCounted
## Legende: TREANT GOLEM – „Der letzte Ring“.
## Der Treant war schon alt, als die ersten Arenen gebaut wurden. Er hat so viele sterben sehen,
## dass er niemanden mehr ins Herz lässt. Mossback hält ihn für morsch, ein Holzfällerkonzern will
## seinen Hain, Belphegor bietet ewige Ruhe – und aus seinem Stamm will etwas Neues wachsen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der letzte Ring",
	"summary": "Der Treant zählt die Jahre in Ringen und die Kämpfe in Narben. Er hat so viele kommen und gehen sehen, dass er niemanden mehr nah an sich heranlässt.",
	"relic": "Der grüne Trieb",
	"relic_text": "Ein junger Zweig in einem Tontopf, kaum fingerlang. Er wächst aus einem Holz, das älter ist als jede Sprache – und er hat schon zwei Blätter.",
}

const CAST := {
	"hero": {"preset": "treant", "name": "TREANT", "title": "Der Uralte Wald", "color": "65a30d"},
	"mossback": {"preset": "mossback", "name": "MOSSBACK", "title": "Der Wald, der nach ihm kommt", "color": "84cc16"},
	"finn": {"preset": "zip", "name": "FINN", "title": "Ein Junge, der auf Bäume klettert", "color": "fde68a"},
	"logger": {"preset": "cyborg_mech", "name": "RODUNGSMECH", "title": "Konzern Grauholz", "color": "94a3b8"},
	"logger2": {"preset": "swat_specops", "name": "VORARBEITER", "title": "Konzern Grauholz", "color": "94a3b8"},
	"belphegor": {"boss": "belphegor", "name": "BELPHEGOR", "title": "Die ewige Ruhe", "color": "a3a3a3"},
	"stumpf": {"preset": "treant", "name": "DER STUMPF", "title": "Holz, das sich weigert zu fallen", "color": "57534e"},
}

static func chapters() -> Array:
	return [
		{"id": "treant_1", "title": "Ringe und Narben", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["logger", 2.8, -1], ["logger2", 4.0, -1], ["finn", -3.5, 1]]),
			{"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "TREANT · DER LETZTE RING", "sub": "Kapitel I – Ringe und Narben"},
			S._narr("Der Treant war schon alt, als man die erste Arena baute. Er zählt die Jahre in Ringen: viertausend und elf. Die Kämpfe in Narben: zu viele."),
			S._narr("Er hat Könige gesehen, die unter seinen Ästen spielten, und dieselben Könige, die man unter seinen Wurzeln begrub. Irgendwann hat er aufgehört, sich Namen zu merken."),
			S._cam("two", 0, 1.4, 1),
			S._say("logger2", "Der Hain wird gerodet. Konzern Grauholz hat die Papiere. Der große Baum zuerst – der ist hohl, der fällt eh bald."),
			S._say("hero", "Ich bin nicht hohl. Ich bin nur leise. Das verwechseln Menschen oft."),
			S._say("logger", "Ziel spricht. Ziel ist Holz. Fortfahren."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "WURZELGRIFF!", "flag": "treant_roots",
				"success": [S._narr("Wurzeln brechen aus dem Boden und umklammern die Beine des Mechs. Viertausend Jahre Geduld haben Kraft.")],
				"fail": [S._narr("Die Wurzeln sind langsam. Viel zu langsam. Der Mech weicht aus.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "logger", "logger2"], "goal": "SCHÜTZE DEN HAIN!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "treant_roots", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("finn", "Das war SO cool! Darf ich auf dich klettern? Ganz nach oben? Ich bin der beste Kletterer im Dorf!"),
			S._say("hero", "Nein. Geh nach Hause, Junge. Ich merke mir keine Namen mehr. Es lohnt sich nicht."),
			S._say("finn", "Ich heiße Finn. Ich sag es dir so oft, bis du es dir merkst."),
			S._cam("close", 0, 1.4),
			S._narr("Der Junge klettert trotzdem. Der Treant lässt ihn. Er weiß nicht, warum."),
			S._say("finn", "Von hier oben sieht man das ganze Dorf! Und den Fluss! Und – ist das ein Vogelnest? In deinem Kopf?"),
			S._say("hero", "Drosseln. Seit dreihundert Jahren. Immer andere Drosseln. Ich habe aufgehört, ihnen Namen zu geben."),
			S._say("finn", "Dann gebe ich ihnen welche. Die da heißt Pip. Und die da Krümel."),
			S._narr("Der Treant spürt, wie sich etwas in seinem Kernholz regt. Ganz leise. Wie ein Ring, der wachsen will, obwohl der Sommer längst vorbei ist."),
		]},
		{"id": "treant_2", "title": "Der junge Wald", "arena": "bg_jungle_ruins", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["mossback", 2.5, -1], ["finn", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der junge Wald"},
			S._narr("Der Konzern kommt wieder, mit mehr Maschinen. Der Treant zieht mit seinem Hain in die alten Dschungelruinen. Dort wohnt schon jemand."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("mossback", "Der Alte. Ich dachte, du wärst längst umgefallen. Du bist morsch. Ich bin der Wald, der nach dir kommt."),
			S._say("hero", "Ich bin hier gewachsen, als du noch eine Eichel warst, Bestie."),
			S._say("mossback", "Eben. Du hattest deine Zeit. Mach Platz für Lebendigeres."),
			S._say("finn", "Hey! Er ist lebendig! Er hat mich gerettet! Und er kennt meinen Namen!"),
			S._cam("close", 0, 1.4),
			S._narr("Der Treant öffnet den Mund, um zu widersprechen. Dann merkt er: Er kennt den Namen wirklich. Finn."),
			{"t": "choice", "text": "Was antwortet der Treant?", "options": [
				{"label": "Seinen Platz verteidigen", "flag": "treant_proud", "steps": [
					S._say("hero", "Ich mache keinen Platz. Ich habe diesen Boden viertausend Jahre gehalten."),
					S._say("mossback", "Dann zeig, dass du noch stehen kannst, wenn man dich schubst.")]},
				{"label": "Mossback einladen", "flag": "treant_shared", "steps": [
					S._say("hero", "Die Ruinen sind groß. Der Konzern auch. Wir könnten zusammen wachsen."),
					S._say("mossback", "Zusammen? Mit einem alten Baum? Erst sehe ich, ob du mich halten kannst.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "mossback"], "goal": "ALTER WALD GEGEN JUNGEN WALD!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "treant_shared", "steps": [
				S._say("mossback", "Du bist zäher, als du aussiehst. Gut. Ich wachse links, du rechts. Und der Junge klettert auf uns beide."),
			], "else": [
				S._say("mossback", "Du stehst noch. Aber du stehst allein, Alter. Wie lange noch?"),
			]},
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht wird der Treant müde. So müde wie nie. Eine sanfte Stimme summt ein Wiegenlied tief unter seinen Wurzeln."),
		]},
		{"id": "treant_3", "title": "Wurzeln, die nie wandern", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["belphegor", 3.0, -1], ["finn", -4.0, 1], ["mossback", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Wurzeln, die nie wandern"},
			S._narr("Seine Wurzeln wachsen nach unten, tiefer und tiefer, bis sie Eis berühren. Dort liegt jemand auf einem Bett aus Moos und gähnt."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("belphegor", "Alter Freund. Viertausend Jahre aufrecht stehen. Das ist anstrengend, nicht wahr? Leg dich hin."),
			S._say("belphegor", "Ich biete dir ewige Ruhe. Wurzeln, die nie wieder wandern müssen. Keine Narben mehr. Keine Namen mehr, die man vergessen muss."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Keine Namen mehr … Das klingt gut. Ich habe so viele verloren."),
			S._say("belphegor", "Lass los. Du bist nur noch Holz, das sich weigert zu fallen."),
			S._say("hero", "Finn. Der Junge heißt Finn. Wenn ich mich hinlege, wer fängt ihn auf, wenn er aus den Ästen fällt?"),
			S._music("boss"),
			{"t": "branch", "flag": "treant_shared", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("mossback", "Ich wachse links, du rechts. Das war die Abmachung. Von Hinlegen war nie die Rede."),
				{"t": "fight", "cast": ["hero", "mossback", "belphegor"], "goal": "STEH AUF, ALTER WALD!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("finn", "Ich bin an deinen Wurzeln runtergeklettert! Ganz tief! Du hast gesagt, ich bin der beste Kletterer – nein, das hab ich gesagt. Egal!"),
				{"t": "fight", "cast": ["hero", "finn", "belphegor"], "goal": "STEH AUF, ALTER WALD!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Belphegor versinkt gähnend in seinem Moos. Die Wurzeln des Treants ziehen sich nach oben zurück – und bringen etwas mit: Wärme."),
			S._say("hero", "Ich hätte mich fast hingelegt. Viertausend Jahre, und ich hätte mich fast hingelegt, weil jemand freundlich gesummt hat."),
			S._say("belphegor", "Irgendwann legst du dich hin, Alter. Jeder tut das. Ich warte. Ich bin sehr gut im Warten."),
			S._say("hero", "Ich auch. Aber ich warte jetzt auf etwas anderes."),
			S._say("hero", "Ich warte darauf, dass Finn alt genug ist, um nicht mehr runterzufallen."),
		]},
		{"id": "treant_4", "title": "Der letzte Ring", "arena": "mystic_grove", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["stumpf", 2.0, -1], ["finn", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der letzte Ring"},
			S._narr("Der Hain ist gerettet. Der Konzern ist abgezogen. Aber der Treant spürt, dass sein Holz trocken wird. Viertausend Jahre sind genug für jeden Baum."),
			S._cam("two", 0, 1.6, 2),
			S._say("finn", "Du stirbst doch nicht, oder? Bäume sterben nicht einfach!"),
			S._say("hero", "Doch, Finn. Wir tun es nur langsamer. Ich habe Angst davor. Darum habe ich nie jemanden nah rangelassen. Damit es keinem wehtut."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("stumpf", "Dann bleib. Für immer. Ein Stumpf, der nicht fällt und nicht wächst. Kein Ende. Kein Anfang. Nur Stehen."),
			S._say("hero", "Ein Stumpf gibt keinen Schatten. Und keine Äste zum Klettern."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "stumpf"], "goal": "BESIEGE DEN STUMPF!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._narr("Der Treant setzt sich. Langsam, wie ein Berg, der sich hinlegt. Und aus einer Narbe in seinem Stamm sprießt ein grüner Trieb. Zwei Blätter. Zitternd."),
			S._say("hero", "Sieh mal, Finn. Ein neuer Ring. Der erste."),
			S._cam("two", 0, 1.6, 2),
			S._say("finn", "Darf ich ihn gießen? Jeden Tag? Und ihm deinen Namen sagen, damit er ihn sich merkt?"),
			S._say("hero", "Sag ihm deinen. Meinen kennt er schon."),
			S._narr("Der alte Treant lebt noch viele Jahre. Aber von diesem Tag an zählt er nicht mehr Ringe und Narben. Er zählt Besuche."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Treant · Der letzte Ring"},
			S._narr("Relikt erhalten: Der grüne Trieb  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
