extends RefCounted
## Legende: BOGDAN, DER BOGATYR – „Der Stein am Scheideweg“.
## Bogdan bewacht seit Jahren einen alten Stein an einer Weggabelung in der Taiga. Auf dem Stein steht:
## „Links verlierst du dein Pferd, rechts verlierst du dich, geradeaus verlierst du deinen Weg.“ Er hat
## sich nie getraut, einen der drei Wege zu gehen. Warrok fordert ihn heraus, Baphomet will seinen Zorn,
## und am Ende baut er an der Kreuzung ein Teehaus.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der Stein am Scheideweg",
	"summary": "Bogdan steht seit Jahren an einer Weggabelung in der Taiga und bewacht einen alten Stein mit drei Warnungen. Er hat sich nie getraut, einen der drei Wege zu gehen.",
	"relic": "Der Samowar vom Scheideweg",
	"relic_text": "Ein verbeulter Samowar aus Messing. In ihm kocht immer Tee für drei – für jeden Weg einen Gast.",
}

const CAST := {
	"hero": {"preset": "bogdan", "name": "BOGDAN", "title": "Der Bogatyr", "color": "bfdbfe"},
	"mascha": {"preset": "lepora", "name": "MASCHA", "title": "Reisende mit Laterne", "color": "f1f5f9"},
	"wolf": {"preset": "reaper_hound", "name": "TAIGAWOLF", "title": "Hungrig im Winter", "color": "57534e"},
	"warrok": {"preset": "warrok_brute", "name": "WARROK", "title": "Der Stärkste im Osten", "color": "f97316"},
	"baphomet": {"boss": "baphomet", "name": "BAPHOMET", "title": "Der Zorn", "color": "f97316"},
	"schatten": {"preset": "bogdan", "name": "DER WÄCHTER", "title": "Der Bogdan, der nie geht", "color": "0039a6"},
}

static func chapters() -> Array:
	return [
		{"id": "bogdan_1", "title": "Drei Wege", "arena": "frozen_summit", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["wolf", 3.0, -1], ["mascha", -3.5, 1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "BOGDAN · DER STEIN AM SCHEIDEWEG", "sub": "Kapitel I – Drei Wege"},
			S._narr("Mitten in der Taiga teilt sich der Weg in drei. Dort steht ein Stein, älter als jedes Dorf. Und neben dem Stein steht Bogdan, groß wie eine Birke, still wie der Schnee."),
			S._narr("Auf dem Stein steht: »Links verlierst du dein Pferd. Rechts verlierst du dich. Geradeaus verlierst du deinen Weg.« Bogdan ist noch nie weitergegangen."),
			S._cam("two", 0, 1.6, 1),
			S._say("hero", "Kein Reisender in drei Wochen. Nur du, Wolf. Und du bist auch nicht zum Reden gekommen."),
			{"t": "appear", "who": 2},
			S._say("mascha", "Hilfe! Der Wolf ist mir seit dem Fluss gefolgt! Ist hier jemand?"),
			S._say("hero", "Stell dich hinter den Stein. Er hat schon Schlimmeres gesehen als einen Wolf."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "wolf"], "goal": "SCHÜTZE DIE REISENDE!", "lives": [3, 1], "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.4, 2),
			S._say("mascha", "Danke, Recke. Ich bin Mascha. Welcher Weg führt nach Norden?"),
			S._say("hero", "Alle drei. Und keiner. Ich weiß es nicht. Ich war nie dort."),
			S._say("mascha", "Du bewachst einen Scheideweg und bist nie einen Weg gegangen? Dann komm doch einfach ein Stück mit."),
			S._narr("Bogdan schüttelt den Kopf. Aber als Mascha geht, sieht er ihr lange nach. Länger als jedem Reisenden davor."),
		]},
		{"id": "bogdan_2", "title": "Der Stärkste im Osten", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["warrok", 2.5, -1], ["mascha", -3.6, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Stärkste im Osten"},
			S._narr("Mascha kommt zurück, mit einer Nachricht: In der Festung jenseits der Steppe sucht ein Koloss den stärksten Krieger der Welt. Er hat von dem Bogatyr am Stein gehört."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("warrok", "DU bist der Recke vom Stein? Ich habe Berge versetzt. Was hast du getan?"),
			S._say("hero", "Ich habe gewartet."),
			S._say("warrok", "GEWARTET? Worauf? Komm her und zeig mir, ob dein Warten stark macht!"),
			S._say("mascha", "Bogdan, du bist zum ersten Mal von deinem Stein weg. Weißt du das? Mach was draus!"),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "warrok"], "goal": "BOGATYR GEGEN KOLOSS!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("warrok", "Du schlägst wie ein Winter. Langsam. Und dann auf einmal überall."),
			S._say("hero", "Ich hatte viel Zeit zum Üben. Zu viel."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht träumt Bogdan von Feuer. Ein Feuer, das sagt: All die Jahre am Stein. Wer hat dich dorthin gestellt? Wer hat dir das genommen? Werd wütend, Recke."),
		]},
		{"id": "bogdan_3", "title": "Der Zorn", "arena": "hell_flames", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["baphomet", 3.0, -1], ["mascha", -4.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Zorn"},
			S._narr("Bogdan steht in Flammen, die nicht wärmen. Ein gehörnter Fürst sitzt auf einem Thron aus Asche und lacht."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("baphomet", "So viele Jahre im Schnee. Niemand hat dir gedankt. Niemand hat dich abgelöst. Spürst du es nicht? Die Wut darüber?"),
			S._say("hero", "Ich spüre … Kälte. Nur Kälte."),
			S._say("baphomet", "Dann lass mich dich wärmen. Ein bisschen Zorn, und du zerschlägst den Stein und jeden, der dich je dorthin gestellt hat."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
			S._say("mascha", "Bogdan! Niemand hat dich hingestellt! Du bist geblieben, weil du Angst vor dem Weg hattest. Das ist keine Schande. Aber es ist auch nicht seine Schuld."),
			S._say("hero", "… Sie hat recht, Gehörnter. Ich bin nicht wütend. Ich hatte Angst. Und gegen Angst hilft kein Feuer."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "mascha", "baphomet"], "goal": "LÖSCH DAS FEUER MIT WINTER!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Ein eisiger Wind fegt durch die Flammen. Baphomet brüllt, und dann ist da nur noch Schnee, der leise auf die Asche fällt."),
		]},
		{"id": "bogdan_4", "title": "Der vierte Weg", "arena": "frozen_summit", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["mascha", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der vierte Weg"},
			S._narr("Zurück am Scheideweg. Neben dem Stein steht schon jemand: Bogdan, mit Schnee auf den Schultern, der sich seit Jahren nicht bewegt hat."),
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schatten", "Bleib. Links das Pferd, rechts du selbst, geradeaus der Weg. Jeder Weg kostet etwas. Nur Stehenbleiben kostet nichts."),
			S._say("hero", "Stehenbleiben hat mich zwölf Winter gekostet. Und jeden Reisenden, mit dem ich nicht gegangen bin."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schatten"], "goal": "GEH DEINEN WEG!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._say("mascha", "Und? Links, rechts oder geradeaus?"),
			S._say("hero", "Keiner. Ich baue hier ein Haus. Mit einem Samowar. Wer an den Scheideweg kommt, bekommt Tee – und Gesellschaft für ein Stück des Weges."),
			S._narr("Im Frühling steht an der Kreuzung ein kleines Teehaus. Auf den Stein hat jemand einen vierten Satz gekratzt: »Oder du trinkst erst einen Tee bei Bogdan.«"),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Bogdan · Der Stein am Scheideweg"},
			S._narr("Relikt erhalten: Der Samowar vom Scheideweg  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
