extends RefCounted
## Legende: VORRUK, DER STERNENKOLOSS – „Der Weg nach Hause“.
## Vorruk ist mit einem Sternenschiff auf dieser Welt abgestürzt. Er ist riesig, spricht kaum und versteht
## nichts – außer seiner Hündin Zirra, die mit ihm gefallen ist. Der Mutant hält ihn für ein Monster,
## Bel Marduk will ihn als Waffe, und am Ende findet er ein Zuhause, das nicht zwischen den Sternen liegt.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der Weg nach Hause",
	"summary": "Vorruk ist mit einem Sternenschiff abgestürzt. Er ist drei Meter groß, spricht kaum und versteht diese Welt nicht. Nur seine Hündin Zirra ist mit ihm gefallen. Jede Nacht starrt er in den Himmel.",
	"relic": "Zirras Halsband",
	"relic_text": "Ein Ring aus Sternenmetall, der in der Nacht leise summt. Er klingt wie der Ort, von dem Vorruk kam – und ein bisschen wie der, an dem er geblieben ist.",
}

const CAST := {
	"hero": {"preset": "vorruk", "name": "VORRUK", "title": "Der Sternenkoloss", "color": "c084fc"},
	"lepora": {"preset": "lepora", "name": "LEPORA", "title": "Jägerin im Hain", "color": "f1f5f9"},
	"jaeger": {"preset": "swat_specops", "name": "MONSTERJÄGER", "title": "Will das Ding im Wald", "color": "fb923c"},
	"mutant": {"preset": "mutant_titan", "name": "MUTANT", "title": "Der andere Riese", "color": "84cc16"},
	"marduk": {"boss": "bel_marduk", "name": "BEL MARDUK", "title": "Der Krieg", "color": "dc2626"},
	"schatten": {"preset": "vorruk", "name": "DER FREMDE", "title": "Der Vorruk, der nie ankommt", "color": "1e1b4b"},
}

static func chapters() -> Array:
	return [
		{"id": "vorruk_1", "title": "Gefallen", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["jaeger", 3.0, -1], ["lepora", -3.6, 1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "VORRUK · DER WEG NACH HAUSE", "sub": "Kapitel I – Gefallen"},
			S._narr("Vor drei Monden fiel ein Stern in den Hain. Seitdem erzählen die Dörfer von einem Riesen mit Krallen wie Sicheln, der nachts in den Himmel starrt. Und von einem lila Hund, der leuchtet."),
			S._cam("two", 0, 1.6, 1),
			S._say("jaeger", "Da ist es. Das Monster aus dem Krater. Hundert Goldstücke für seinen Kopf."),
			S._say("hero", "Vorruk … nicht Monster. Vorruk … sucht Weg. Nach oben."),
			S._say("jaeger", "Es spricht! Umso besser – dann kann es um Gnade betteln."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "jaeger"], "goal": "SCHÜTZE ZIRRA!", "lives": [3, 1], "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("lepora", "Du hättest ihn zerquetschen können. Hast du nicht. Du hast nur deine Hündin beschützt."),
			S._say("hero", "Zirra … alles was Vorruk hat. Zirra und Himmel."),
			S._say("lepora", "Ich bin Lepora. Ich jage nachts unter dem Mond. Ich weiß, wie es ist, in den Himmel zu schauen und etwas zu vermissen."),
			S._narr("Zirra schnüffelt an Leporas Hand und wedelt mit dem leuchtenden Schwanz. Vorruk hat sie noch nie bei jemand anderem wedeln sehen."),
		]},
		{"id": "vorruk_2", "title": "Zwei Riesen", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["mutant", 2.5, -1], ["lepora", -3.8, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Zwei Riesen"},
			S._narr("Lepora führt Vorruk zur alten Festung. Man sagt, dort lebt ein anderer Riese, der auch nicht von hier ist. Vielleicht weiß er einen Weg zu den Sternen."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("mutant", "NOCH so einer. Die Menschen haben dich auch Monster genannt, oder? Gewöhn dich dran. Oder schlag zurück. Das hab ich getan."),
			S._say("hero", "Vorruk … will nicht schlagen. Vorruk will nach Hause."),
			S._say("mutant", "Hier gibt es kein Zuhause für Riesen. Ich zeig's dir."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "mutant"], "goal": "RIESE GEGEN RIESE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("mutant", "Du bist stärker als ich. Und trotzdem hast du aufgehört, als ich am Boden lag. Warum?"),
			S._say("hero", "Zirra … mag keinen Lärm. Und du … auch allein. Wie Vorruk."),
			S._say("mutant", "… Ja. Schon lange."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht donnert es ohne Wolken. Ein Krieger in roter Rüstung steigt aus einem brennenden Riss. Er hat gesehen, wie stark der Sternenkoloss ist."),
		]},
		{"id": "vorruk_3", "title": "Die Waffe", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["marduk", 3.0, -1], ["mutant", -4.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Waffe"},
			S._narr("Vor dem Tor der Hölle wartet der Krieg selbst. Hinter ihm glüht etwas, das aussieht wie ein Sternenschiff."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("marduk", "Dein Schiff, Koloss. Ich habe es aus dem Krater geholt. Es fliegt wieder. Diene mir eine Schlacht lang, und es bringt dich nach Hause."),
			S._say("hero", "Nach Hause … Sterne … Vorruk sieht Sterne wieder?"),
			S._say("marduk", "Eine einzige Schlacht. Gegen die Menschen, die dich gejagt haben. Ist das nicht gerecht?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
			S._say("mutant", "Riese! Lepora schickt mich. Sie sagt: Wer für den Krieg kämpft, kommt nie nach Hause. Egal wohin er fliegt."),
			S._say("hero", "… Lepora hat recht. Zirra … hat Angst vor Krieg. Vorruk auch."),
			S._say("hero", "Roter Mann. Behalt Schiff. Vorruk kämpft nicht für dich."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "mutant", "marduk"], "goal": "KEIN KRIEG FÜR DEN HEIMWEG!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Bel Marduk stürzt durch sein eigenes Tor. Das Sternenschiff zerbricht dabei in tausend glitzernde Stücke. Vorruk sieht zu. Er weint nicht. Zirra leckt ihm die Kralle."),
		]},
		{"id": "vorruk_4", "title": "Unter neuen Sternen", "arena": "mystic_grove", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["lepora", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Unter neuen Sternen"},
			S._narr("Zurück im Hain, am Krater. Darin steht ein Vorruk mit leeren Augen, den Kopf im Nacken, und starrt in den Himmel. Er hat seit drei Monden nicht geblinzelt."),
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schatten", "Schau hoch. Nur hoch. Hier unten ist nichts. Hier unten sind nur Fremde."),
			S._say("hero", "Hier unten … Lepora. Mutant. Zirra. Vorruk war hochschauen so lange … nicht gesehen, was unten ist."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schatten"], "goal": "SCHAU NACH UNTEN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._say("lepora", "Und? Wirst du ein neues Schiff bauen?"),
			S._say("hero", "Nein. Vorruk baut … Haus. Groß. Mit Tür für Riesen. Und Platz für Zirra."),
			S._narr("Im Krater wächst ein Haus aus Sternenmetall und Moos. Die Kinder aus dem Dorf kommen, um Zirra zu streicheln. Nachts schaut Vorruk noch immer in den Himmel. Aber jetzt winkt er."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Vorruk · Der Weg nach Hause"},
			S._narr("Relikt erhalten: Zirras Halsband  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
