extends RefCounted
## Legende: NERIS, DIE KETTENHAND – „Loslassen“.
## Neris wuchs in den Kristallhöhlen auf, wo violette Kristalle in den Körpern der Bergleute wachsen.
## Ihr Bruder wurde vom Kristall verschluckt; seitdem trägt sie den Kettenhandschuh, mit dem sie ihn
## nicht festhalten konnte. Der Kettenwart lehrt sie, was Festhalten kostet, Lilith bietet ihr den
## Bruder zurück, und am Ende lernt sie, die Kette loszulassen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Loslassen",
	"summary": "In den Kristallhöhlen wachsen violette Kristalle aus den Körpern der Bergleute. Neris' Bruder Tavi wurde ganz vom Kristall verschluckt. Ihr Kettenhandschuh hat ihn nicht halten können. Seitdem lässt sie nichts mehr los.",
	"relic": "Das letzte Glied",
	"relic_text": "Ein einzelnes, offenes Kettenglied. Es hält nichts mehr fest – und trotzdem trägt Neris es jeden Tag.",
}

const CAST := {
	"hero": {"preset": "neris", "name": "NERIS", "title": "Die Kettenhand", "color": "a78bfa"},
	"vorarbeiter": {"preset": "don_valente", "name": "VORARBEITER", "title": "Will die Kristalle", "color": "facc15"},
	"tavi": {"preset": "echo", "name": "TAVI", "title": "Ihr Bruder im Kristall", "color": "8b5cf6"},
	"kettenwart": {"preset": "kettenwart", "name": "KETTENWART", "title": "Kennt jede Kette", "color": "94a3b8"},
	"lilith": {"boss": "lilith", "name": "LILITH", "title": "Die Verführerin", "color": "f472b6"},
	"schatten": {"preset": "neris", "name": "DIE FESTHALTENDE", "title": "Die Neris, die nie loslässt", "color": "4c1d95"},
}

static func chapters() -> Array:
	return [
		{"id": "neris_1", "title": "Kristallhöhlen", "arena": "cocytus", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["vorarbeiter", 2.8, -1]]),
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "NERIS · LOSLASSEN", "sub": "Kapitel I – Kristallhöhlen"},
			S._narr("Unter dem Berg leuchten die Höhlen türkis. Die Bergleute schlagen violette Kristalle aus dem Fels – und manchmal wachsen ihnen die Kristalle aus der Haut."),
			S._narr("Neris hat Kristalle auf den Schultern und goldene Adern auf den Armen. Und eine Kette an der rechten Hand, die sie nie abnimmt."),
			S._cam("two", 0, 1.6, 1),
			S._say("vorarbeiter", "Der große Kristall im Schacht sieben bringt mehr Gold als die ganze Mine. Wir sprengen ihn morgen."),
			S._say("hero", "In Schacht sieben ist mein Bruder. Er ist im Kristall. Wenn ihr sprengt, sprengt ihr ihn."),
			S._say("vorarbeiter", "Dein Bruder ist seit zwei Jahren ein Stein, Mädchen. Geh mir aus dem Weg."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "vorarbeiter"], "goal": "SCHÜTZE SCHACHT SIEBEN!", "lives": [3, 1], "ai": 3},
			S._music("calm"),
			S._cam("close", 0, 1.4),
			S._narr("Die Sprengladung liegt entschärft im Staub. Neris steigt in Schacht sieben hinab, zu dem großen violetten Kristall. Darin schläft ein Junge mit ihrem Gesicht."),
			S._say("hero", "Tavi. Ich hatte dich an der Kette. Ich hatte dich. Und dann ist sie gerissen."),
		]},
		{"id": "neris_2", "title": "Der Kerkermeister", "arena": "blood_moon", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["kettenwart", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Kerkermeister"},
			S._narr("Man sagt, im Turm unter dem Blutmond lebt einer, der jede Kette der Welt kennt. Neris will wissen, wie man eine Kette schmiedet, die nie reißt."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("kettenwart", "Eine Kette, die nie reißt? Die habe ich. Hundert Jahre lang habe ich mich selbst damit festgehalten."),
			S._say("hero", "Dann gib sie mir. Ich hole meinen Bruder aus dem Kristall, und diesmal lasse ich nicht los."),
			S._say("kettenwart", "Zeig mir erst, wie fest du hältst."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "kettenwart"], "goal": "KETTE GEGEN KETTE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("kettenwart", "Du hältst fest wie ich. Zu fest. Du hast dich verkrampft. Darum bist du langsam."),
			S._say("hero", "Wenn ich locker lasse, verliere ich."),
			S._say("kettenwart", "Ich habe hundert Jahre festgehalten und alles verloren. Eine Kette hält nur, solange auch etwas Spiel darin ist."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Auf dem Heimweg duftet die Luft plötzlich nach Rosen. Eine Stimme flüstert Tavis Namen – mit Tavis Stimme."),
		]},
		{"id": "neris_3", "title": "Die Verführerin", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lilith", 3.0, -1], ["kettenwart", -4.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Verführerin"},
			S._narr("Eine Stadt aus rotem Samt. In ihrer Mitte sitzt eine Frau mit Augen wie Mondsteine, und neben ihr steht – Tavi. Lebendig. Lächelnd."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lilith", "Ich habe ihn aus dem Kristall geholt, Kettenhand. Er gehört dir. Du musst nur deine Kette um ihn legen und nie wieder loslassen. Nie wieder."),
			S._say("hero", "Tavi … Du siehst so aus wie früher."),
			S._say("lilith", "Für immer so. Bei mir altert niemand. Niemand geht. Niemand lässt los."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
			S._say("kettenwart", "Neris! Sieh genau hin. Er lächelt immer gleich. Er blinzelt nicht. Das ist kein Bruder, das ist ein Käfig mit seinem Gesicht."),
			S._say("hero", "… Tavi hat nie so lange stillgehalten. Nie. Er war immer zu schnell für meine Kette."),
			S._say("hero", "Du hast mir keinen Bruder gegeben, Verführerin. Du hast mir einen Gefangenen angeboten."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "kettenwart", "lilith"], "goal": "ZERREISS DEN KÄFIG!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Der falsche Tavi zerfällt zu Rosenblättern. Lilith verschwindet im Samt. Zurück bleibt nur der Duft – und Neris' Kette, die zum ersten Mal locker in ihrer Hand hängt."),
		]},
		{"id": "neris_4", "title": "Loslassen", "arena": "cocytus", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["tavi", 3.6, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Loslassen"},
			S._narr("Schacht sieben. Der große Kristall glüht, als würde er atmen. Davor steht eine Neris, deren Kette so fest um den Kristall gewickelt ist, dass er Risse bekommt."),
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schatten", "Fester. Noch fester. Wenn wir festhalten, kann er nicht weg. Auch wenn es ihn zerdrückt."),
			S._say("hero", "Du zerdrückst ihn. Merkst du das nicht? Er braucht keine Kette. Er braucht Platz."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schatten"], "goal": "LASS DIE KETTE LOS!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._narr("Neris öffnet den Handschuh. Die Kette fällt klirrend zu Boden. Und der Kristall, der zwei Jahre lang keinen Laut gemacht hat, beginnt zu singen."),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("tavi", "Neris? Du hast losgelassen. Ich konnte nicht raus, solange du gezogen hast. Der Kristall wächst nur nach innen, wenn man an ihm zerrt."),
			S._say("hero", "Tavi … Es tut mir leid. Ich hatte solche Angst, dich zu verlieren, dass ich dich festgehalten habe, bis du fast verschwunden bist."),
			S._narr("Tavi hat jetzt auch Kristalle auf den Schultern. Er findet sie schön. Neris trägt nur noch ein einziges offenes Kettenglied – als Erinnerung daran, wann man loslassen muss."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Neris · Loslassen"},
			S._narr("Relikt erhalten: Das letzte Glied  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
