extends RefCounted
## Legende: FLAYER, DER HÄUTER – „Das Buch der Hundertdreizehn“.
## Ein Henker, den weder Himmel noch Hölle wollen, und ein Grab, das ihn immer wieder ausspuckt.
## Eine Totengräberin mit Rückenschmerzen, ein Junge in zu großen Schuhen und hundertdreizehn
## Namen, die nie jemand ausgesprochen hat. Hier erklärt sich, woher Flayers Seelenwirbel kommt.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Das Buch der Hundertdreizehn",
	"summary": "Die Erde von Rabenstein spuckt ihren alten Henker immer wieder aus. Vielleicht, weil er noch Schulden hat: hundertdreizehn Namen, die er nie kannte.",
	"relic": "Das Buch der Hundertdreizehn",
	"relic_text": "Ein schwarzes Henkersbuch. Früher standen darin nur Nummern – jetzt steht neben jeder ein Name, in Odas krakeliger Schrift.",
}

const CAST := {
	"hero": {"preset": "skeleton_reaper", "name": "FLAYER", "title": "Der Häuter", "color": "a78bfa"},
	"oda": {"preset": "thorn_witch", "name": "ODA", "title": "Totengräberin von Rabenstein", "color": "a8a29e"},
	"gerwin": {"preset": "kettenwart", "name": "VOGT GERWIN", "title": "Hält das Dorf in Ordnung", "color": "b45309"},
	"knecht": {"preset": "bruno", "name": "FACKELKNECHT", "title": "Hat Angst, tut aber mutig", "color": "f59e0b"},
	"jorin": {"preset": "ren", "name": "JORIN", "title": "Nummer hundertdreizehn", "color": "7dd3fc"},
	"nyx": {"preset": "nyx", "name": "NYX", "title": "Die Seelenernterin", "color": "c084fc"},
	"ahriman": {"boss": "ahriman", "name": "AHRIMAN", "title": "Die Finsternis, die nichts fragt", "color": "312e81"},
	"henker": {"preset": "skeleton_reaper", "name": "DER HENKER", "title": "Wer Flayer einmal war", "color": "52525b"},
}

static func chapters() -> Array:
	return [
		{"id": "skeleton_reaper_1", "title": "Das Grab, das nicht hält", "arena": "blood_moon", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["oda", 1.6, -1], ["gerwin", 9.0, -1], ["knecht", 10.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "FLAYER · DAS BUCH DER HUNDERTDREIZEHN", "sub": "Kapitel I – Das Grab, das nicht hält"},
			S._narr("Auf dem Rabenhügel hinter dem Dorf Rabenstein liegt ein Friedhof. Und auf dem Friedhof liegt ein Grab, das niemanden behalten will."),
			S._narr("Dreimal hat die Totengräberin Oda den Knochenmann begraben. Dreimal hat die Erde ihn wieder ausgespuckt."),
			{"t": "fx", "kind": "shake"},
			S._pose(0, "Rise", 1.0),
			S._cam("two", 0, 1.6, 1),
			S._say("oda", "Schon wieder. Weißt du, wie schwer Lehm im Herbst ist, Knochenmann? Mein Rücken weiß es."),
			S._say("hero", "Ver…zeihung. Ich… liege… still. Wirklich. Die Erde… mag mich nicht."),
			S._say("oda", "Die Erde mag niemanden. Aber sie nimmt jeden. Nur dich nicht. Was hast du angestellt?"),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ich war… der Henker. Von Rabenstein. Hundertdreizehn Mal… habe ich den Hebel gezogen."),
			S._narr("Als Flayer starb, klopfte er ans Himmelstor. Es blieb zu. Er klopfte ans Höllentor. Man schickte ihn zurück – mit dem Vermerk: »Nicht zuständig.«"),
			S._say("oda", "Nicht zuständig. Ha! Das steht auch auf jeder Antwort, die ich vom Vogt kriege."),
			S._cam("low", 0, 1.6),
			{"t": "fx", "kind": "shake"},
			S._narr("Unten im Dorf flackern Fackeln. Jemand hat den Wiedergänger auf dem Hügel gesehen."),
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3},
			{"t": "move", "who": 2, "x": 3.2, "time": 1.0},
			{"t": "move", "who": 3, "x": 4.6, "time": 1.2},
			S._music("tense"),
			S._cam("two", 0, 1.2, 2),
			S._say("gerwin", "Da ist er! Der Henker steht wieder auf. Das Ding bringt Unglück über Rabenstein. Verbrennt ihn!"),
			S._say("knecht", "Ä-äh, Herr Vogt? Muss ich ihn anfassen? Er guckt so … knochig."),
			S._say("hero", "Ich… will niemandem… wehtun. Nie wieder."),
			S._say("oda", "Dann halt sie bloß hin, bis die Morgenglocke schlägt. Bei Tageslicht traut sich der Vogt nichts – da sehen ihn ja alle."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.4, "text": "SENSE QUER – HALTE DIE FACKELN AB!", "flag": "skeleton_reaper_guard",
				"success": [S._narr("Die Sense fängt beide Fackeln. Funken regnen auf die Gräber, und der Knecht quiekt.")],
				"fail": [S._narr("Eine Fackel streift den Mantel. Knochen brennen schlecht. Aber es tut trotzdem weh.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "gerwin", "knecht"], "goal": "HALTE DURCH BIS ZUR MORGENGLOCKE!", "lives": [3, 2, 2], "teams": [0, 1, 1],
				"time": 60, "ai": 3, "qte": "skeleton_reaper_guard"},
			S._music("calm"),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._cam("wide", 0, 1.4),
			S._narr("Die Glocke schlägt. Der Vogt flucht, der Knecht rennt, und über den Gräbern geht eine bleiche Sonne auf."),
			S._cam("two", 0, 1.4, 1),
			S._say("oda", "Hier. Das lag mit dir im Sarg. Dein Henkersbuch. Hundertdreizehn Zeilen – aber keine Namen. Nur Nummern."),
			S._say("hero", "Man… sagte mir keine Namen. Ein Henker… soll nicht wissen, wen er… Aber Knochen… erinnern sich trotzdem."),
			S._say("oda", "Vielleicht will dich die Erde nicht, weil du noch Schulden hast. Hundertdreizehn Namen, Knochenmann. Fang an zu suchen."),
			S._cam("close", 0, 1.6),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Als Flayer das Buch aufschlägt, kreist etwas um ihn. Ein violetter Wirbel. Leise Stimmen. Er zählt sie nicht – er weiß, wie viele es sind."),
		]},
		{"id": "skeleton_reaper_2", "title": "Die Nummer hundertdreizehn", "arena": "mystic_grove", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["jorin", 0.6, -1], ["nyx", 7.0, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Nummer hundertdreizehn"},
			S._narr("Zehn Nächte lang wühlt Flayer sich durch Kirchenbücher, Gerichtsakten und Odas Erinnerungen. Hundertzwölf Namen findet er. Einer fehlt."),
			S._narr("Und jede Nacht, wenn der Wirbel um ihn kreist, bleibt eine Stimme näher bei ihm als die anderen."),
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("jorin", "Du hörst mich endlich. Ich bin die Hundertdreizehn. Ich heiße Jorin. Ich war vierzehn."),
			S._say("hero", "Der… Müllersjunge. Der Mehldieb. Ich erinnere mich… an deine Schuhe. Sie waren… zu groß."),
			S._say("jorin", "Die waren von meinem Vater. Und ich hab kein Mehl gestohlen. Das war der Vogt. Ich hab ihn gesehen – deswegen musste ich weg."),
			S._pose(0, "Dazed", 1.0),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ich… wusste es. Am Galgen… hast du es gesagt. Ich habe… nicht zugehört. Der Hebel… war meine Arbeit."),
			S._narr("Der Wirbel heult auf. Hundertdreizehn Seelen, die nie gehen konnten – weil der, der sie geschickt hat, nie ihre Namen kannte."),
			S._music("tense"),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": 2.6, "time": 1.0},
			S._cam("two", 0, 1.2, 2),
			S._say("nyx", "Na sieh an. Der Abfall sammelt Seelen. Das ist mein Beruf, Henker. Und du stehst mir seit Jahren im Weg."),
			S._say("nyx", "Selbst die Hölle hat dich zurückgeschickt. Gib mir den Jungen. Er gehört über den Fluss, nicht an deine Sense."),
			S._say("jorin", "Ich will nicht gehen, bevor jemand im Dorf die Wahrheit weiß. Sonst bin ich für immer der Mehldieb."),
			{"t": "choice", "text": "Was tut Flayer mit Jorins Seele?", "options": [
				{"label": "Gib ihn Nyx – er soll Frieden haben", "flag": "skeleton_reaper_gave", "steps": [
					S._say("hero", "Geh mit ihr, Jorin. Du hast… lange genug gewartet. Die Wahrheit… trage ich für dich."),
					S._say("nyx", "Vernünftig. Für einen Haufen Knochen. Aber erst will ich sehen, ob du die anderen auch so leicht hergibst.")]},
				{"label": "Behalte ihn – die Wahrheit zuerst", "flag": "skeleton_reaper_kept", "steps": [
					S._say("hero", "Nein. Man hat ihn… einmal nicht ausreden lassen. Diesmal… entscheidet er."),
					S._say("nyx", "Rührend. Dann hole ich ihn mir eben. Und deine Knochen gleich dazu.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "nyx"], "goal": "SENSE GEGEN SENSE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 2),
			{"t": "branch", "flag": "skeleton_reaper_kept", "steps": [
				S._say("nyx", "Du kämpfst, als hätten die Seelen in deinem Wirbel dich gern. Das … habe ich noch nie gesehen."),
				S._say("jorin", "Ein paar haben ihn gern. Wir anderen arbeiten noch dran."),
				S._say("hero", "Das… ist mehr… als ich verdiene."),
			], "else": [
				S._say("nyx", "Abgemacht ist abgemacht. Ich bringe ihn rüber. Und, Henker – du schuldest mir einen Gefallen."),
				S._say("jorin", "Sag es ihnen, Flayer. Sag es dem ganzen Dorf."),
				{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
				S._narr("Jorins Stimme fehlt im Wirbel. Es ist leiser geworden. Flayer hätte nie gedacht, dass Stille so wehtun kann."),
			]},
			S._cam("low", 0, 1.8),
			S._narr("In derselben Nacht öffnet sich unter dem Friedhof von Rabenstein ein Spalt. Kein Feuer. Kein Licht. Nur Dunkelheit, die freundlich klingt."),
		]},
		{"id": "skeleton_reaper_3", "title": "Ein Zuhause ohne Namen", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["ahriman", 3.0, -1], ["jorin", -4.0, 1], ["nyx", -4.6, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Ein Zuhause ohne Namen"},
			S._narr("Flayer steigt hinab. Nicht, weil er muss. Sondern weil von unten jemand ruft: »Willkommen daheim.«"),
			S._narr("Am Grund der Welt liegt ein See aus Eis. Darauf steht ein Tisch, gedeckt für einen einzigen Gast."),
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("ahriman", "Setz dich, Henker. Ich bin Ahriman, die Finsternis vor dem ersten Licht. Hier fragt niemand nach Namen. Hier fragt niemand nach gar nichts."),
			S._say("ahriman", "Der Himmel war zu fein für dich, die Hölle zu beschäftigt. Ich habe Platz. Ewig. Gib mir nur die Stimmen in deinem Wirbel – sie stören die Stille."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ein Zuhause… Ich habe… so lange gesucht."),
			S._pose(0, "Crouch", 1.0),
			S._narr("Für einen Herzschlag – falls Knochen so etwas haben – setzt Flayer sich beinahe. Der Wirbel um ihn wird blass."),
			S._say("hero", "Aber ein Zuhause… in dem keiner nach Namen fragt… Das hatte ich schon. Es hieß Galgen."),
			S._pose(0, "Rise", 0.8),
			{"t": "fx", "kind": "flash"},
			S._music("boss"),
			S._say("ahriman", "Dann verschwinde im Dunkel, wie alle Undankbaren."),
			{"t": "branch", "flag": "skeleton_reaper_kept", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.2, "time": 0.8},
				S._say("jorin", "Ich bin noch da! Ich hab mich in deinem Mantel versteckt. Du hast mich nicht weggegeben – jetzt geb ich dich auch nicht her!"),
				S._narr("Der Wirbel färbt sich violett, dann golden. Hundertdreizehn Stimmen rufen zugleich – zum ersten Mal nicht gegen ihn, sondern für ihn."),
				{"t": "fight", "cast": ["hero", "jorin", "ahriman"], "goal": "DER WIRBEL KÄMPFT MIT DIR – VERTREIBE DIE FINSTERNIS!",
					"lives": [3, 2, 1], "teams": [0, 0, 1], "mods": {"2": {"power": 1.2}}, "ai": 6},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.2, "time": 0.8},
				S._say("nyx", "Ich sagte doch, du schuldest mir was. Aber meine Kundschaft lass ich mir nicht von einer Pfütze Dunkelheit wegnehmen."),
				S._narr("Nyx hat Jorin über den Fluss gebracht. Und von drüben hat er ihr eine Botschaft mitgegeben: »Hilf ihm.«"),
				{"t": "fight", "cast": ["hero", "nyx", "ahriman"], "goal": "ZWEI SENSEN GEGEN DIE FINSTERNIS!",
					"lives": [3, 2, 1], "teams": [0, 0, 1], "mods": {"2": {"power": 1.2}}, "ai": 6},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			{"t": "vanish", "who": 1},
			S._cam("close", 0, 1.6),
			S._narr("Ahriman zerfällt wie Rauch in einem Luftzug. Der gedeckte Tisch bleibt stehen – mit einem leeren Stuhl."),
			S._say("hero", "Behalte… den Stuhl. Ich habe… noch einen Hügel. Und eine Totengräberin… mit Rückenschmerzen."),
			S._narr("Und endlich begreift Flayer, woher sein Wirbel kommt: Es sind die Seelen, die er geschickt hat. Sie haben ihn nie verfolgt. Sie haben auf ihn gewartet."),
		]},
		{"id": "skeleton_reaper_4", "title": "Hundertdreizehn Namen", "arena": "bg_moon_temple", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["henker", 2.0, -1], ["oda", -3.5, 1], ["gerwin", 4.5, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Hundertdreizehn Namen"},
			S._narr("Am Abend des Totenfests steht ganz Rabenstein vor der alten Mondkapelle. Oda hat alle gerufen. Niemand weiß, warum."),
			S._cam("two", 0, 1.6, 2),
			S._say("oda", "Du musst sie nicht alle vorlesen, Knochenmann. Hundertdreizehn. Das dauert bis Mitternacht."),
			S._say("hero", "Sie… haben länger gewartet."),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.2, 3),
			S._say("gerwin", "Schon wieder dieser Wiedergänger! Leute, hört nicht auf ihn. Ein Henker lügt. Das ist sein Handwerk."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._narr("Flayer hebt das Buch. Da steigt aus seinem Schatten eine Gestalt mit Kapuze, die Schlinge über der Schulter, die Hand schon am Hebel."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("henker", "Du gehörst nirgendwohin. Das ist deine Strafe. Die Leute wollen keine Namen hören. Sie wollen, dass du verschwindest."),
			S._say("henker", "Ich war der Teil von dir, der funktioniert hat. Kein Zögern, keine Fragen, kein Zuhören. Nimm mich zurück, und du fühlst nie wieder etwas."),
			S._say("hero", "Du… hast nie zugehört. Ich… höre jetzt zu. Hundertdreizehn Mal."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "henker"], "goal": "BESIEGE DEN HENKER IN DIR!", "lives": [2, 3], "damage": {"0": 35}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 2.0),
			S._pose(0, "Charge", 1.0),
			S._narr("Der Henker zerfällt zu Asche. Flayer schlägt das Buch auf. Und er beginnt zu lesen."),
			{"t": "qte", "kind": "sequence", "keys": ["standard", "special", "standard", "block"], "time": 3.0, "text": "LIES DIE NAMEN – OHNE ZU STOCKEN!",
				"flag": "skeleton_reaper_names",
				"success": [S._narr("»Agnes Wendt. Bertold Kehr. Klara aus dem Mühltal …« Mit jedem Namen wird der Wirbel um ihn heller.")],
				"fail": [S._narr("Beim neunten Namen bricht ihm die Stimme. Oda legt ihm die Hand auf die Schulter. Er fängt noch einmal an.")]},
			S._narr("Bis Mitternacht liest er. Niemand geht nach Hause. Und dann kommt die letzte Zeile. Nummer hundertdreizehn."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Jorin, Sohn des Müllers. Vierzehn Jahre. Kein Dieb. Das Mehl… hat Vogt Gerwin genommen. Ich wusste es. Und habe trotzdem gezogen."),
			S._cam("two", 0, 1.2, 3),
			S._say("gerwin", "Das – das ist eine Lüge! Wer glaubt denn einem Skelett?"),
			S._say("oda", "Ich. Und die Müllerin sagt seit zwanzig Jahren, dass ihr Junge unschuldig war. Wir haben nur nie zugehört."),
			{"t": "branch", "flag": "skeleton_reaper_kept", "steps": [
				S._narr("Da tritt ein blasser Junge in zu großen Schuhen aus dem Wirbel, nickt seiner Mutter zu – und geht endlich über den Fluss."),
			], "else": [
				S._narr("Da weht vom Fluss ein Wind herüber, der nach Mehl riecht. Am anderen Ufer winkt Nyx – und neben ihr ein Junge in zu großen Schuhen."),
			]},
			{"t": "move", "who": 3, "x": 9.0, "time": 1.2},
			S._narr("Der Vogt rennt. Weit kommt er nicht. Das ganze Dorf hat ihn gehört."),
			S._music("calm"),
			S._cam("two", 0, 1.6, 2),
			S._say("oda", "Die Erde will dich immer noch nicht, Knochenmann. Aber ich brauch einen, der mir den Lehm schaufelt."),
			S._say("hero", "Das… ist ein Zuhause. Glaube ich. Die Raben… sagen ja."),
			S._cam("sky", 0, 3.0),
			S._narr("Seither hat der Friedhof von Rabenstein einen Wächter. Er gräbt nicht, er richtet nicht. Er kennt nur alle Namen – und die Raben kennen ihn."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Flayer · Das Buch der Hundertdreizehn"},
			S._narr("Relikt erhalten: Das Buch der Hundertdreizehn  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
