extends RefCounted
## Legende: WARROK, DER URZEITLICHE BERSERKER – „Das zweite Wort“.
## Warrok erwachte in einer Höhle unter der Arena, älter als jede Sprache. Er kennt nur ein Wort: MEHR.
## Bruno will wissen, ob er stark genug ist, um still zu sein; Bel Marduk nennt ihn Bruder und bietet
## einen Krieg ohne Ende; und ein kleines Mädchen bringt ihm ein zweites Wort bei.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Das zweite Wort",
	"summary": "Warrok ist älter als jede Sprache und kennt nur ein Wort: MEHR. Er weiß nicht, ob er für etwas kämpft – oder nur, weil er nicht aufhören kann.",
	"relic": "Der bemalte Kieselstein",
	"relic_text": "Ein flacher Stein, mit Kinderfarbe bemalt: ein großer grüner Klumpen und ein kleiner gelber Punkt, Hand in Hand. Darunter ein Wort in krummen Buchstaben: DANKE.",
}

const CAST := {
	"hero": {"preset": "warrok_brute", "name": "WARROK", "title": "Der urzeitliche Berserker", "color": "a16207"},
	"bruno": {"preset": "bruno", "name": "BRUNO", "title": "Der Einschlag-Held", "color": "fbbf24"},
	"pia": {"preset": "lepora", "name": "PIA", "title": "Tochter des Arenawärters", "color": "fde047"},
	"promoter": {"preset": "don_valente", "name": "ARENAPROMOTER", "title": "Verkauft Warrok als Monster", "color": "d4af37"},
	"champ": {"preset": "mutant_titan", "name": "ARENACHAMPION", "title": "Der Koloss von Ost", "color": "65a30d"},
	"marduk": {"boss": "bel_marduk", "name": "BEL MARDUK", "title": "Der Krieg, der Bruder sagt", "color": "ff3b30"},
	"bestie": {"preset": "warrok_brute", "name": "MEHR", "title": "Das einzige Wort", "color": "450a0a"},
}

static func chapters() -> Array:
	return [
		{"id": "warrok_brute_1", "title": "MEHR", "arena": "gladiator_fortress", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["champ", 2.8, -1], ["promoter", 5.0, -1], ["pia", -3.5, 1]]),
			{"t": "vanish", "who": 3},
			S._music("fight"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "WARROK · DAS ZWEITE WORT", "sub": "Kapitel I – MEHR"},
			S._narr("Unter der Festung der Gladiatoren lag eine Höhle, älter als die Steine darüber. Darin schlief etwas, das schon wach war, bevor Menschen sprechen konnten."),
			S._narr("Als die Bauarbeiter die Höhle aufbrachen, öffnete Warrok die Augen. Er kannte ein einziges Wort. Er brüllte es so laut, dass die Arena bebte."),
			S._cam("close", 0, 1.6),
			S._pose(0, "Roar", 1.2),
			S._say("hero", "RAAAH! MEHR!"),
			S._cam("two", 0, 1.4, 2),
			S._say("promoter", "Meine Damen und Herren! Das Urzeitmonster! Kein Hirn, keine Sprache, nur Muskeln! Heute gegen den Koloss von Ost!"),
			S._say("champ", "Ich habe noch nie verloren, Höhlenmann. Heute auch nicht."),
			S._say("hero", "MEHR!"),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 10, "time": 2.6, "text": "BERSERKER!", "flag": "warrok_brute_rage",
				"success": [S._narr("Warrok schlägt die Knochenkeule auf den Boden. Die Ränge springen auf.")],
				"fail": [S._narr("Warrok sieht die Menge an. So viele Augen. Er weiß nicht, warum sie schreien.")]},
			{"t": "fight", "cast": ["hero", "champ"], "goal": "GEWINNE DEN SCHAUKAMPF!", "lives": [3, 2], "qte": "warrok_brute_rage", "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.4, 2),
			S._say("promoter", "Fantastisch! Morgen noch einmal! Und übermorgen! Er will ja MEHR, hahaha!"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("pia", "Du blutest am Arm. Hier. Ich hab ein Pflaster. Es ist klein, aber Papa sagt, Pflaster helfen immer."),
			S._narr("Warrok starrt das Mädchen an. Er könnte sie mit einem Finger umwerfen. Sie klebt ihm ein gelbes Pflaster mit Sternchen auf den Unterarm."),
			S._say("hero", "… MEHR?"),
			S._say("pia", "Nein, eins reicht. Man sagt jetzt Danke. Danke. Sag mal: Danke."),
			S._cam("close", 0, 1.4),
			S._narr("Warrok öffnet den Mund. Kein Laut kommt heraus. Das Wort ist zu klein für seine Kehle."),
		]},
		{"id": "warrok_brute_2", "title": "Laut und still", "arena": "imperial_colosseum", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["bruno", 2.5, -1], ["pia", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Laut und still"},
			S._narr("Hundert Kämpfe in hundert Tagen. Warrok gewinnt alle. Er wird jeden Tag lauter. Und jeden Abend kommt Pia mit Pflastern und übt mit ihm ein Wort."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("bruno", "Man sagt, du bist der Stärkste hier. Ich habe nur eine Frage: Bist du laut, weil du stark bist – oder weil du Angst hast, still zu sein?"),
			S._say("hero", "MEHR!"),
			S._say("bruno", "Du bist laut, Warrok. Aber bist du auch stark genug, um still zu sein?"),
			S._say("pia", "Er übt! Er kann schon fast »Da« sagen! Das »nke« fehlt noch!"),
			{"t": "choice", "text": "Was tut Warrok?", "options": [
				{"label": "Brüllen", "flag": "warrok_brute_roar", "steps": [
					S._pose(0, "Roar", 1.0),
					S._say("hero", "RAAAAAH! MEHR! MEHR!"),
					S._say("bruno", "Dachte ich mir. Na komm.")]},
				{"label": "Schweigen", "flag": "warrok_brute_quiet", "steps": [
					S._narr("Warrok schließt den Mund. Es kostet ihn mehr Kraft als jeder Kampf. Er bleibt still. Drei Herzschläge lang."),
					S._say("bruno", "Drei Sekunden. Das ist mehr, als die meisten schaffen. Jetzt kämpfen wir. Ohne Brüllen, wenn du kannst.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "bruno"], "goal": "KRAFT GEGEN KRAFT!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "warrok_brute_quiet", "steps": [
				S._say("bruno", "Du hast keinen einzigen Laut gemacht. Ich glaube, du bist stärker als ich. Hier drin."),
				S._narr("Bruno tippt sich an die Brust. Warrok tippt sich an die Brust. Er versteht nicht ganz. Aber es fühlt sich richtig an."),
			], "else": [
				S._say("bruno", "Du hast gewonnen. Und gebrüllt, bis dir die Luft ausging. Was kommt nach MEHR, Warrok? Weißt du das?"),
			]},
			{"t": "fx", "kind": "shake"},
			S._narr("In der Nacht bebt die Höhle unter der Arena. Eine Stimme ruft von ganz unten. Sie benutzt dasselbe Wort wie Warrok. Nur tiefer. Und älter."),
		]},
		{"id": "warrok_brute_3", "title": "Bruder", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["marduk", 3.0, -1], ["pia", -4.0, 1], ["bruno", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Bruder"},
			S._narr("Warrok folgt der Stimme hinab, durch die Höhle, durch den Fels, bis in eine Stadt aus Eisen, in der jeder Stein nach Krieg riecht."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("marduk", "Bruder. Endlich. Ich habe dich gemacht, weißt du. Am Anfang der Zeit. Mein erstes Werk. Ein Ding, das nur ein Wort kennt."),
			S._say("marduk", "Komm zu mir. Ich biete dir einen Krieg, der niemals endet. Nie wieder Ruhe. Immer mehr. MEHR."),
			S._cam("close", 0, 1.4),
			S._say("hero", "… MEHR."),
			S._say("marduk", "Ja! Ohne Krieg bist du nur ein Tier in einer Höhle. Mit mir bist du ein Gott."),
			S._cam("close", 0, 1.4),
			S._narr("Warrok sieht auf seinen Arm. Das gelbe Pflaster mit den Sternchen klebt noch. Es ist schmutzig. Es hält trotzdem."),
			S._say("hero", "… Nein."),
			S._narr("Es ist sein zweites Wort. Nicht das, das Pia ihm beibringen wollte. Aber ein Anfang."),
			S._music("boss"),
			{"t": "branch", "flag": "warrok_brute_quiet", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("bruno", "Er hat Nein gesagt. Ich habe es gehört. Und ich respektiere ein Nein mit allem, was ich habe."),
				{"t": "fight", "cast": ["hero", "bruno", "marduk"], "goal": "SAG NEIN ZUM KRIEG!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "fight", "cast": ["hero", "marduk"], "goal": "SAG NEIN ZUM KRIEG!", "lives": [3, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Bel Marduk taumelt zurück. Sein erstes Werk hat ihm widersprochen. Das ist seit Anbeginn der Zeit nicht passiert."),
			S._say("marduk", "Du wirst wiederkommen, Bruder. Das Wort wohnt in dir."),
			S._say("hero", "Nein."),
		]},
		{"id": "warrok_brute_4", "title": "Das zweite Wort", "arena": "bg_sunset_stadium", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["bestie", 2.0, -1], ["pia", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das zweite Wort"},
			S._narr("Ein leeres Stadion bei Sonnenuntergang. Der Promoter hat Warrok verkauft – an einen Zirkus. Morgen kommt der Käfig."),
			S._cam("two", 0, 1.6, 2),
			S._say("pia", "Ich lasse das nicht zu. Papa auch nicht. Du bist kein Monster. Monster nehmen keine Pflaster."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("bestie", "MEHR! MEHR! MEHR! Zerschlag den Käfig! Zerschlag den Zirkus! Zerschlag alles!"),
			S._narr("Das Wort brüllt in seinem Kopf, so laut wie nie. Warrok hält sich die Ohren zu. Es hilft nicht. Es kommt von innen."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "bestie"], "goal": "BRING DAS WORT ZUM SCHWEIGEN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 1.0),
			S._narr("Stille. Zum ersten Mal, seit Warrok die Augen geöffnet hat, ist es in seinem Kopf still."),
			S._cam("two", 0, 1.6, 2),
			S._narr("Am nächsten Morgen kommt kein Käfig. Pias Vater hat den Vertrag zerrissen. Warrok darf in der Höhle bleiben – als Wächter der Arena."),
			S._say("pia", "Hier. Ich hab dir einen Stein bemalt. Das bist du, und das bin ich."),
			S._narr("Warrok nimmt den kleinen Stein vorsichtig zwischen zwei riesige Finger. Er öffnet den Mund. Es dauert lange."),
			S._say("hero", "Da … nke."),
			S._say("pia", "Du hast es gesagt! Du hast es wirklich gesagt!"),
			S._say("hero", "Danke. … Danke. Danke."),
			S._narr("Er sagt es zu jedem, der an diesem Tag an der Arena vorbeikommt. Auch zu den Tauben. Auch zum Regen, als er anfängt."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Warrok · Das zweite Wort"},
			S._narr("Relikt erhalten: Der bemalte Kieselstein  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
