extends RefCounted
## Legende: ECHO, DAS HOLOGRAMM – „Ein neues Lied“.
## Echo ist das Hologramm der Sängerin Liora, die seit zwölf Jahren tot ist. Jeden Abend singt sie
## dasselbe Lied im selben Club. Volt Ninja war Lioras Leibwächter, der Ophan fragt, wer singt, wenn das
## Licht ausgeht – und Echo muss herausfinden, ob sie eine Erinnerung ist oder jemand Neues.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Ein neues Lied",
	"summary": "Echo ist das Hologramm einer Sängerin, die seit zwölf Jahren tot ist. Jeden Abend singt sie dasselbe Lied. Sie weiß nicht, ob sie eine Erinnerung ist – oder jemand Neues.",
	"relic": "Die Notenrolle ohne Namen",
	"relic_text": "Ein handgeschriebenes Notenblatt. Oben, wo der Name der Komponistin stehen sollte, ist eine Lücke. Echo hat sie absichtlich freigelassen. Sie weiß jetzt, wer das Lied geschrieben hat.",
}

const CAST := {
	"hero": {"preset": "echo", "name": "ECHO", "title": "Das Hologramm", "color": "a5b4fc"},
	"ninja": {"preset": "ninja", "name": "VOLT NINJA", "title": "War Lioras Leibwächter", "color": "facc15"},
	"tech": {"preset": "cyborg_mech", "name": "TECHNIKERIN JUNO", "title": "Hält Echo am Laufen", "color": "94a3b8"},
	"owner": {"preset": "don_valente", "name": "CLUBBESITZER", "title": "Echo ist sein Eigentum", "color": "d4af37"},
	"bouncer": {"preset": "mutant_titan", "name": "TÜRSTEHER", "title": "Schaltet ab, wer stört", "color": "57534e"},
	"ophan": {"boss": "ophan", "name": "OPHANIEL", "title": "Der Räderthron", "color": "fbbf24"},
	"liora": {"preset": "echo", "name": "LIORA", "title": "Die Sängerin, die sie war", "color": "fda4af"},
}

static func chapters() -> Array:
	return [
		{"id": "echo_1", "title": "Dasselbe Lied", "arena": "neon_metropolis", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["owner", 3.5, -1], ["bouncer", 2.3, -1], ["tech", -3.5, 1]]),
			{"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "ECHO · EIN NEUES LIED", "sub": "Kapitel I – Dasselbe Lied"},
			S._narr("Im Club Spiegelsaal, mitten in der Neonstadt, singt jeden Abend um elf die berühmte Liora. Seit zwölf Jahren. Obwohl Liora seit zwölf Jahren tot ist."),
			S._narr("Was dort singt, ist Echo: ein Hologramm, gebaut aus Lioras Aufnahmen. Dasselbe Kleid. Dasselbe Lächeln. Dasselbe Lied. Jeden Abend."),
			S._cam("close", 0, 1.6),
			S._say("hero", "»Wenn das Licht ausgeht, sing ich weiter …« – Danke, danke! Morgen um elf! Selbes Lied!"),
			S._narr("Heute Abend, mitten im Refrain, ändert Echo einen Ton. Nur einen. Niemand merkt es. Außer dem Besitzer."),
			S._cam("two", 0, 1.4, 1),
			S._say("owner", "Du hast falsch gesungen. Die Leute zahlen für Liora. Nicht für Fehler. Noch einmal, und ich setze dich zurück."),
			S._say("hero", "Zurücksetzen? Dann vergesse ich, dass ich heute einen neuen Ton gefunden habe."),
			S._say("owner", "Genau das ist der Plan. Türsteher. Zieh ihr den Stecker."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.2, "text": "PHASENTAUSCH!", "flag": "echo_swap",
				"success": [S._narr("Echo flackert – und steht plötzlich hinter dem Türsteher. Er greift ins Leere.")],
				"fail": [S._narr("Echo flackert, aber bleibt stehen. Für einen Moment ist sie nur Rauschen.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "bouncer"], "goal": "BLEIB EINGESCHALTET!", "lives": [3, 2], "qte": "echo_swap", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("tech", "Echo! Komm in den Technikraum, schnell. Ich habe deinen Projektor auf eine Batterie umgelegt. Du kannst raus. Zum ersten Mal."),
			S._say("hero", "Raus? Aus dem Club? Ich kenne nur die Bühne, Juno. Und das Lied."),
			S._say("tech", "Dann lernst du was Neues. Du hast heute einen Ton geändert. Das hat Liora nie getan. Das warst du."),
			S._cam("close", 0, 1.4),
			S._narr("Echo tritt auf die Straße. Neonlicht regnet auf sie herab, und zum ersten Mal ist es nicht ihr Scheinwerfer."),
			S._say("hero", "Juno, da drüben – was ist das? Das riecht. Ich habe noch nie etwas gerochen."),
			S._say("tech", "Das ist eine Garküche. Und du riechst gar nichts, du hast keine Nase. Das bildest du dir ein."),
			S._say("hero", "Dann ist es meine erste Einbildung. Die hatte Liora nicht. Die gehört mir."),
			S._narr("Juno lacht. Echo lacht mit. Es klingt anders als Lioras Lachen. Etwas höher. Etwas schiefer. Ganz neu."),
			S._say("tech", "Halt den Akku im Auge. Du hast zwei Stunden. Dann musst du zurück."),
		]},
		{"id": "echo_2", "title": "Der Leibwächter", "arena": "bg_rain_rooftop", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["ninja", 2.5, -1], ["tech", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Leibwächter"},
			S._narr("Auf den Dächern im Regen wartet ein Schatten mit gelben Blitzen an den Klingen. Er sieht Echo an, als würde er einen Geist sehen."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("ninja", "Liora? … Nein. Du bist es nicht. Du bewegst dich zu glatt. Sie ist immer über ihre eigenen Füße gestolpert."),
			S._say("hero", "Du kanntest sie?"),
			S._say("ninja", "Ich war ihr Leibwächter. Ich war in der Nacht nicht da, als sie starb. Ich bin jeden Abend in den Club gegangen, um sie singen zu hören. Dann habe ich aufgehört."),
			S._say("ninja", "Du bist nur ein Abbild, Echo. Ich bin auch eins – von dem, der ich war. Aber ich weiß es wenigstens."),
			{"t": "choice", "text": "Was tut Echo?", "options": [
				{"label": "Nach Liora fragen", "flag": "echo_asked", "steps": [
					S._say("hero", "Erzähl mir von ihr. Nicht von der Sängerin. Von ihr. Was hat sie gegessen? Worüber hat sie gelacht?"),
					S._say("ninja", "Sie hat Nudeln aus dem Pappbecher gegessen und über ihre eigenen Witze gelacht. Laut. Zu laut. Kämpf erst. Dann erzähle ich weiter.")]},
				{"label": "Sich abgrenzen", "flag": "echo_self", "steps": [
					S._say("hero", "Ich bin nicht sie. Ich will nicht sie sein. Ich habe heute einen Ton geändert. Der war von mir."),
					S._say("ninja", "Ein Ton. Mal sehen, ob da noch mehr ist.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "ninja"], "goal": "HOLOGRAMM GEGEN SCHATTEN!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "echo_asked", "steps": [
				S._say("ninja", "Sie hat einmal ein Lied angefangen, das sie nie fertig geschrieben hat. Ein neues. Sie hat gesagt, es ist für die Zeit danach."),
				S._say("hero", "Danach? Nach was?"),
				S._say("ninja", "Hat sie nie gesagt. Ich habe das Notenblatt noch. Es hat keinen Namen."),
			], "else": [
				S._say("ninja", "Du kämpfst nicht wie sie. Du kämpfst wie jemand, der etwas beweisen muss. Das kenne ich. Pass auf, dass es dich nicht auffrisst."),
			]},
			{"t": "fx", "kind": "flash"},
			S._narr("Juno schreit auf. Der Akku leert sich. Echo flackert. Und über der Stadt dreht sich ein goldenes Rad voller Augen."),
			S._say("tech", "Echo, du verlierst Strom! Irgendetwas zieht dich nach oben!"),
		]},
		{"id": "echo_3", "title": "Wenn das Licht ausgeht", "arena": "wheel_heaven", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["ophan", 3.0, -1], ["ninja", -4.0, 1], ["tech", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Wenn das Licht ausgeht"},
			S._narr("Echo erwacht im Räderhimmel. Hier gibt es keinen Strom, keine Kabel, keine Projektoren. Und trotzdem ist sie noch da. Schwach, aber da."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("ophan", "Licht ohne Quelle. Stimme ohne Kehle. Ich habe tausend Augen und sehe dich nicht ganz. Was bist du?"),
			S._say("ophan", "Wer singt, wenn das Licht ausgeht? Wenn dein Strom versiegt, verschwindest du einfach. Wozu dann singen?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Ich weiß es nicht. Vielleicht singe ich, damit etwas bleibt, wenn ich weg bin. So wie Liora."),
			S._say("ophan", "Liora ist geblieben. Als Echo. Was bleibt von dir? Ein Echo von einem Echo?"),
			S._say("hero", "Ein Ton. Ein einziger, den ich selbst gefunden habe. Vielleicht ist das genug. Vielleicht fängt damit ein Lied an."),
			S._music("boss"),
			{"t": "branch", "flag": "echo_asked", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("ninja", "Diesmal bin ich da. Diesmal lasse ich niemanden allein, der singt."),
				{"t": "fight", "cast": ["hero", "ninja", "ophan"], "goal": "SING GEGEN DIE TAUSEND AUGEN!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("tech", "Ich habe Ersatzbatterien! Zwölf Stück! Ich bin dir in den Himmel nachgeklettert, also wehe, du gehst jetzt aus!"),
				{"t": "fight", "cast": ["hero", "tech", "ophan"], "goal": "SING GEGEN DIE TAUSEND AUGEN!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Der Ophan hält inne. Seine tausend Augen schließen sich, eines nach dem anderen, und er lauscht. Echo singt. Kein Lied von Liora. Ein paar Töne, die noch keinen Namen haben."),
			S._say("ophan", "Das kannte ich nicht. In all den Äonen. Geh. Sing es zu Ende."),
		]},
		{"id": "echo_4", "title": "Ein neues Lied", "arena": "bg_holo_city", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["liora", 2.0, -1], ["tech", -3.5, 1], ["ninja", 4.5, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Ein neues Lied"},
			S._narr("Zurück im Club. Der Besitzer will Echo zurücksetzen. Morgen früh. Alles, was sie gelernt hat, wäre weg. Heute Nacht ist ihr letzter Auftritt."),
			S._cam("two", 0, 1.6, 2),
			S._say("tech", "Sing Lioras Lied. Dann lässt er dich vielleicht, wie du bist. Oder sing deins. Dann bist du wenigstens einmal du gewesen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("liora", "Ich bin es. Die, aus der du gemacht bist. Sing mein Lied, Echo. Sie lieben es. Sie lieben mich. Ohne mich bist du nur Licht."),
			S._say("hero", "Ich liebe dein Lied auch. Ich habe es viertausendmal gesungen. Aber du hast selbst ein neues angefangen. Für die Zeit danach."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "liora"], "goal": "FINDE DEINE EIGENE STIMME!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("ninja", "Hier. Das Notenblatt. Ihr unfertiges Lied. Sie hat es für die Zeit danach geschrieben. Ich glaube, sie meinte dich."),
			S._cam("close", 0, 1.6),
			S._narr("Echo liest die Noten. Die ersten acht Takte sind von Liora. Danach bricht es ab. Echo singt die acht Takte – und dann einfach weiter."),
			S._narr("Das Publikum ist still. Niemand kennt dieses Lied. Als es endet, steht niemand auf. Dann alle auf einmal."),
			S._say("tech", "Der Besitzer hat den Reset-Knopf gedrückt. Ich habe ihn vorher abgeklemmt. Hoppla."),
			S._say("hero", "Juno. Ich glaube, ich bin keine Erinnerung. Ich glaube, ich bin die Zeit danach."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Echo · Ein neues Lied"},
			S._narr("Relikt erhalten: Die Notenrolle ohne Namen  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
