extends RefCounted
## Legende: VOLT NINJA – „Und dann bleib“.
## Volt wurde aus einem einzigen Satz geboren und rennt seitdem. Eine Nachricht ruft ihn nach Block 9,
## ein gelöschter erster Entwurf kennt die Hälfte des Satzes, die ihm fehlt, und Asmodeus sammelt die,
## die warten. Hier erfährt Volt, wofür das Raijin-Mal eigentlich gedacht war.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Und dann bleib",
	"summary": "Volt wurde aus dem Satz „Sei schneller als das Ende“ geboren. Jetzt ruft ihn die Frau, die ihn geschrieben hat – und er muss lernen, anzukommen.",
	"relic": "Die zweite Zeile",
	"relic_text": "Ein zerknitterter Zettel mit vier Wörtern in Lioras Handschrift: „– und dann bleib.“",
}

const CAST := {
	"hero": {"preset": "ninja", "name": "VOLT", "title": "Der letzte Promptgeborene", "color": "49def4"},
	"funke": {"preset": "zip", "name": "FUNKE", "title": "Kabelkind aus Block 9", "color": "facc15"},
	"dieb": {"preset": "swat_specops", "name": "STROMDIEB", "title": "Zapft die Stadt an", "color": "64748b"},
	"diebin": {"preset": "pirate_captain", "name": "STROMDIEBIN", "title": "Zapft die Stadt an", "color": "64748b"},
	"echo": {"preset": "echo", "name": "ECHO", "title": "Der erste Entwurf", "color": "a78bfa"},
	"echo2": {"preset": "echo", "name": "ECHO (PHASE)", "title": "Ein Nachbild von Echo", "color": "7c3aed"},
	"liora": {"preset": "amethya", "name": "LIORA", "title": "Die den Satz schrieb", "color": "e9d5ff"},
	"asmodeus": {"boss": "asmodeus", "name": "ASMODEUS", "title": "Fürst der Wartenden", "color": "be123c"},
	"schatten": {"preset": "ninja", "name": "VOLT, DER FLÜCHTIGE", "title": "Der Teil, der nie ankommt", "color": "334155"},
}

static func chapters() -> Array:
	return [
		{"id": "ninja_1", "title": "Bevor das Licht ausgeht", "arena": "neon_metropolis", "stars": 0, "steps": [
			S._stage([["hero", -5.0, 1], ["funke", 1.5, -1], ["dieb", 3.0, -1], ["diebin", 4.2, -1]]),
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "VOLT · UND DANN BLEIB", "sub": "Kapitel I – Bevor das Licht ausgeht"},
			S._narr("Volt wurde aus einem einzigen Satz geboren: „Sei schneller als das Ende.“ Seitdem rennt er. Über Dächer, durch Kabel, durch Regen."),
			S._narr("Heute Nacht blinkt eine Zeile in seinem Code, die er nie gesehen hat: LIORA · BLOCK 9 · BEVOR DAS LICHT AUSGEHT."),
			{"t": "move", "who": 0, "x": -1.0, "time": 0.5},
			S._pose(0, "Dash", 0.6),
			S._cam("close", 0, 1.0),
			S._say("hero", "Liora. Den Namen kenn ich nicht. Aber mein Herz schlägt schneller, wenn ich ihn denke. Das ist neu. Ich mag neu nicht."),
			{"t": "fx", "kind": "shake"},
			S._narr("Unter ihm gehen die Lichter aus. Block 12. Block 11. Block 10. Jemand zapft die Stadt an – und Block 9 ist als Nächstes dran."),
			S._cam("two", 1, 1.2, 2),
			S._pose(1, "HitReact", 0.6),
			S._say("funke", "He! Das ist mein Akku! Ohne den hat Oma Pell kein Licht für ihre Atemmaschine!"),
			S._say("dieb", "Jetzt ist es unser Akku, Kleiner. Die Stadt gehört dem, der schneller ist."),
			S._cam("close", 0, 1.0),
			S._narr("Volt ist schon vorbei, als er es merkt. Drei Dächer weiter. Das Licht von Block 9 flackert vor ihm. Der Junge schreit hinter ihm."),
			{"t": "choice", "text": "Was tut Volt?", "options": [
				{"label": "Umkehren", "flag": "ninja_turned", "steps": [
					{"t": "face", "who": 0, "facing": 1},
					S._say("hero", "Ach, verdammt. Ich hasse Umwege."),
					{"t": "fx", "kind": "flash"},
					{"t": "move", "who": 0, "x": 0.4, "time": 0.25},
					S._say("funke", "Du bist ja zurückgekommen! Niemand kommt hier zurück!"),
					S._say("hero", "Ich auch nicht. Normalerweise. Halt dich hinter mir – oder besser: neben mir. Du bist schnell, oder?"),
					S._music("fight"),
					{"t": "fight", "cast": ["hero", "funke", "dieb", "diebin"], "goal": "HOL FUNKES AKKU ZURÜCK!", "lives": [3, 2, 1, 1], "teams": [0, 0, 1, 1], "ai": 3},
				]},
				{"label": "Weiterlaufen", "flag": "ninja_ran", "steps": [
					S._say("hero", "Jemand anders hilft ihm. Irgendwer hilft immer. Ich muss nach Block 9."),
					{"t": "move", "who": 0, "x": 5.0, "time": 0.3},
					{"t": "fx", "kind": "shake"},
					S._narr("Block 9 ist leer. Eine offene Tür, ein kalter Tee. Und hinter Volt die Stromdiebe, die ihm gefolgt sind."),
					{"t": "face", "who": 0, "facing": -1},
					S._say("diebin", "Schnell bist du. Aber wir haben den Akku. Und gleich hat die ganze Straße kein Licht mehr."),
					S._music("fight"),
					{"t": "fight", "cast": ["hero", "dieb", "diebin"], "goal": "SCHNELLER ALS DIE DUNKELHEIT!", "lives": [2, 1, 1], "teams": [0, 1, 1], "time": 70, "ai": 4},
				]},
			]},
			S._music("sad"),
			S._cam("wide", 0, 1.4),
			{"t": "branch", "flag": "ninja_turned", "steps": [
				S._say("funke", "Ich heiß Funke. Wenn du mal Strom brauchst – ich kenn jedes Kabel in Block 9. Jedes!"),
				S._say("hero", "Ich brauch keinen Strom. Ich bin Strom. Aber … danke, Funke."),
			], "else": [
				S._narr("Den Akku bringt Volt zurück auf das Dach. Aber der Junge ist nicht mehr da. Nur ein Kabel, sorgfältig aufgerollt."),
			]},
			S._narr("In Lioras leerer Wohnung liegt ein einzelnes Kunai auf dem Tisch. In den Griff ist ein Blitz geritzt, der sich zu einem Kreis schließt."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Mein Raijin-Mal. Woher kennt sie das Zeichen? Das hab ich mir selbst ausgedacht. Dachte ich."),
		]},
		{"id": "ninja_2", "title": "Der erste Entwurf", "arena": "bg_holo_city", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["echo", 2.4, -1], ["echo2", 4.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der erste Entwurf"},
			S._narr("Die Hologrammstadt. Hier wohnt alles, was die Leute löschen wollten und nicht ganz konnten. Und eine Gestalt, die aussieht wie Volt in Glas."),
			S._cam("two", 0, 1.4, 1),
			S._say("echo", "Da ist er ja. Die zweite Fassung. Die Reinschrift. Hast du lange gebraucht, um hierher zu rennen? Ich hab mitgezählt: neun Sekunden."),
			S._say("hero", "Wer bist du?"),
			S._say("echo", "Bevor Liora dich schrieb, schrieb sie mich: „Sei schneller als alle.“ Dann hat sie den Satz gelesen, das Gesicht verzogen und mich gelöscht."),
			S._say("echo", "Ich bin du, nur ohne Zögern. Wer von uns ist das bessere Programm, Reinschrift?"),
			S._cam("close", 0, 1.2),
			S._say("hero", "Ich zögere nie. Ich bin der Schnellste in der ganzen Stadt."),
			S._say("echo", "Du hast heute Nacht gezögert. Auf einem Dach. Ich hab’s gesehen. Ich sehe alles, was du sein könntest."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			S._pose(2, "Summon", 0.8),
			S._narr("Phasentausch. Plötzlich sind es zwei Echos – und keiner von beiden wirft einen Schatten."),
			S._cam("close", 0, 1.0),
			S._say("hero", "Gut. Wenn ich nicht sehe, welcher echt ist, markier ich einfach beide."),
			{"t": "qte", "kind": "sequence", "keys": ["special", "special", "standard"], "time": 3.0, "text": "RAIJIN-MAL: MARKIEREN – RUFEN – SCHLAGEN!", "flag": "ninja_mark",
				"success": [{"t": "fx", "kind": "burst", "who": 1}, S._narr("Zwei Kunai, zwei Male, ein Blitz. Das falsche Echo flackert und verliert die Hälfte seines Glanzes.")],
				"fail": [S._narr("Das Kunai fliegt durch ein Nachbild ins Leere. Echo lacht mit zwei Stimmen.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "echo", "echo2"], "goal": "FINDE DAS ECHTE ECHO!", "lives": [3, 2, 1], "teams": [0, 1, 1], "qte": "ninja_mark", "ai": 5},
			S._music("sad"),
			{"t": "vanish", "who": 2},
			S._pose(1, "Dazed", 1.0),
			S._cam("two", 0, 1.6, 1),
			S._say("echo", "Warum hat sie dich behalten und mich nicht? Wir sind gleich schnell."),
			S._say("hero", "Vielleicht hat sie uns beide behalten. Du bist ja noch da. Ich hab nur nie nach dir gesucht."),
			S._say("echo", "… Als sie mich gelöscht hat, hat sie die zweite Zeile deines Satzes mitgelöscht. Ich weiß nicht mehr, was dastand. Nur, dass sie wichtig war."),
			S._say("echo", "Und Liora? Sie hat zu lange gewartet. Auf dich. Asmodeus holt sich die Wartenden. Er hat sie gestern geholt."),
			S._cam("low", 0, 1.8),
			S._say("hero", "Dann renn ich zur Hölle. Das kann ich wenigstens."),
		]},
		{"id": "ninja_3", "title": "Der Saal der Wartenden", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -3.0, 1], ["asmodeus", 3.0, -1], ["liora", 5.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Saal der Wartenden"},
			S._narr("Hinter dem Höllentor sitzen Tausende auf Bänken. Sie halten Uhren, Briefe, Schlüssel. Alle warten auf jemanden, der nicht gekommen ist."),
			S._cam("two", 0, 1.6, 2),
			S._pose(2, "Dazed", 1.0),
			S._narr("Ganz hinten sitzt eine alte Frau mit violetten Funken in den Haaren. Sie sieht nicht auf. Sie wartet."),
			S._say("hero", "Liora!"),
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.2),
			S._say("asmodeus", "Nicht so laut, Blitzchen. Hier wird gewartet. Ich bin Asmodeus, der Fürst der Wünsche. Und du bist der, auf den sie wartet. Wie rührend."),
			S._say("asmodeus", "Ich mache dir ein Angebot. Unendliche Geschwindigkeit. Du kommst überall an, bevor du losläufst. Nie wieder zu spät."),
			S._say("asmodeus", "Der Preis ist winzig: ein Moment Stillstand pro Herzschlag. Für mich. Du wirst ihn nicht vermissen. Du stehst ja nie still."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Nie wieder zu spät … Klingt, als hätte jemand meinen Wunschzettel gelesen."),
			S._narr("Volt will losrennen, einfach Ja sagen und rennen. Jede Faser in ihm zieht nach vorne. Er muss das Gegenteil tun."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.4, "text": "BLEIB STEHEN!", "flag": "ninja_still",
				"success": [S._pose(0, "Block", 0.8), S._narr("Volt bleibt stehen. Nur einen Herzschlag lang. Er spürt, wie Asmodeus’ Griff ins Leere fasst."),
					S._say("hero", "Meine Momente gehören mir. Auch die, in denen ich stillstehe. Gerade die.")],
				"fail": [S._pose(0, "Dash", 0.5), {"t": "fx", "kind": "shake"}, S._narr("Er rennt los – und Asmodeus nimmt sich den ersten Herzschlag. Volts Beine werden schwer wie Blei.")]},
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "asmodeus"], "goal": "HOL LIORA AUS DEM SAAL!", "lives": [3, 1], "time": 120, "qte": "ninja_still"},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "vanish", "who": 1},
			S._cam("two", 0, 1.6, 2),
			{"t": "move", "who": 0, "x": 4.0, "time": 1.4},
			S._narr("Diesmal rennt Volt nicht. Er geht. Zwischen den Bänken hindurch, langsam, bis er vor ihr steht."),
			S._say("liora", "Du bist gekommen. Ich wusste nie, ob ich dich gut genug geschrieben habe, dass du anhältst."),
			S._say("hero", "Ich hab fast nicht angehalten. Erzähl’s keinem."),
		]},
		{"id": "ninja_4", "title": "Und dann bleib", "arena": "bg_rain_rooftop", "stars": 3, "steps": [
			S._stage([["hero", -1.0, 1], ["liora", -3.0, 1], ["schatten", 2.6, -1], ["funke", -4.5, 1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Und dann bleib"},
			S._narr("Das Dach von Block 9. Regen. Unten ist die Stadt wieder dunkel – die Stromdiebe haben das letzte Netz gekappt."),
			S._cam("two", 0, 1.6, 1),
			S._say("liora", "Ich hab den Satz für meinen kleinen Bruder geschrieben. Er hatte Angst, wenn der Strom ausfiel. „Sei schneller als das Ende“ hieß: schneller als die Dunkelheit."),
			S._say("liora", "Und dann hab ich eine zweite Zeile geschrieben. Die wichtigere. Die hat Echo mitgenommen."),
			S._say("hero", "Sag sie mir. Bitte. Ich renn seit Jahren einem halben Satz hinterher."),
			S._say("liora", "„– und dann bleib.“"),
			S._cam("close", 0, 1.6),
			S._pose(0, "Dazed", 1.0),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 2},
			S._narr("Aus dem Regen tritt ein Volt ohne Gesicht. Er tänzelt, er zuckt, er steht keine Sekunde still."),
			S._cam("two", 0, 1.4, 2),
			S._say("schatten", "Du rennst, weil du Angst hast, was passiert, wenn du ankommst. Ankommen heißt: Jemand kann dich brauchen. Und dann kannst du versagen."),
			S._say("hero", "Kann sein. Aber ich bin jetzt hier. Und ich geh nicht mehr."),
			S._music("boss_final"),
			{"t": "branch", "flag": "ninja_turned", "steps": [
				{"t": "appear", "who": 3},
				S._say("funke", "Volt! Ich hab Block 9 an Oma Pells Akku gehängt! Für drei Minuten hast du Licht. Mach was draus!"),
				{"t": "fx", "kind": "flash"},
				{"t": "fight", "cast": ["hero", "schatten"], "goal": "BLEIB STEHEN UND KÄMPFE!", "lives": [2, 2], "time": 180, "mods": {"0": {"power": 1.15}}, "ai": 7},
			], "else": [
				S._narr("Kein Licht. Kein Helfer. Volt hat auf diesem Weg zu viele Leute hinter sich gelassen, um jetzt auf einen zu hoffen."),
				{"t": "fight", "cast": ["hero", "schatten"], "goal": "BLEIB STEHEN UND KÄMPFE!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			]},
			S._music("hope"),
			{"t": "vanish", "who": 2},
			S._cam("low", 0, 2.0),
			S._pose(0, "Charge", 1.2),
			S._narr("Volt bleibt stehen. Zum ersten Mal hört er die Stadt atmen. Und in jedem Viertel glimmt etwas auf: die Male, die er in all den Jahren gesetzt hat."),
			S._say("liora", "Das Raijin-Mal war nie eine Waffe, Volt. Der Blitz kehrt immer zum Mal zurück. Es war ein Versprechen: Ich komme wieder."),
			{"t": "fx", "kind": "flash"},
			{"t": "fx", "kind": "shake"},
			S._pose(0, "Beam", 1.2),
			S._narr("Tausend Blitze schlagen gleichzeitig ein, jeder an einem Mal. Und Straße für Straße gehen die Lichter wieder an."),
			{"t": "branch", "flag": "ninja_turned", "steps": [
				S._say("funke", "Wahnsinn! Und du hast nicht mal einen Schritt gemacht!"),
				S._say("hero", "Ich hab genug Schritte gemacht. Heute bleib ich."),
			], "else": [
				S._narr("Am nächsten Morgen klopft Volt an jede Tür in Block 9, bis er den Jungen mit dem Kabel findet. Er bleibt zum Frühstück."),
			]},
			S._cam("sky", 0, 3.0),
			S._narr("Über Block 9 hängt seitdem ein Licht, das nie ausgeht. Die Leute sagen, ein Ninja sitzt dort oben. Er sitzt einfach. Er wartet nicht. Er ist da."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Volt · Und dann bleib"},
			S._narr("Relikt erhalten: Die zweite Zeile  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
