extends RefCounted
## Legende: AURUM, DAS GOLDKONSTRUKT – „Die Waage in der Mitte“.
## Aurum wurde gebaut, um die Herzen der Toten gegen eine Feder zu wiegen. Eines Tages wog er
## sein eigenes – und die Waage blieb genau in der Mitte stehen. Ein Seelenernter will ihm die Toten
## abnehmen, Ahriman legt eine schwarze Feder in die Schale, und Aurum muss ein Urteil fällen, das
## er nicht berechnen kann.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die Waage in der Mitte",
	"summary": "Aurum wiegt die Herzen der Toten, seit es Tote gibt. Als er sein eigenes Herz wog, blieb die Waage in der Mitte stehen. Seitdem weiß er nicht, ob er gut ist – oder überhaupt jemand.",
	"relic": "Die Feder der Ma'at",
	"relic_text": "Eine weiße Feder, leichter als Luft. Wer sie hält, spürt keine Schuld und keinen Stolz – nur das Gewicht dessen, was er heute tun wird.",
}

const CAST := {
	"hero": {"preset": "anubis", "name": "AURUM", "title": "Das Goldkonstrukt", "color": "fbbf24"},
	"flayer": {"preset": "skeleton_reaper", "name": "FLAYER", "title": "Der Seelenernter", "color": "a3a3a3"},
	"seele": {"preset": "phoenix", "name": "NEFERET", "title": "Eine verirrte Seele", "color": "fde68a"},
	"grabraeuber": {"preset": "grimbolt", "name": "GRABRÄUBER", "title": "Gold ist Gold", "color": "84cc16"},
	"grabraeuber2": {"preset": "pirate_captain", "name": "GRABRÄUBERIN", "title": "Gold ist Gold", "color": "84cc16"},
	"ahriman": {"boss": "ahriman", "name": "AHRIMAN", "title": "Die schwarze Feder", "color": "7c3aed"},
	"richter": {"preset": "anubis", "name": "DER RICHTER", "title": "Aurum ohne Zweifel", "color": "b45309"},
}

static func chapters() -> Array:
	return [
		{"id": "anubis_1", "title": "Die Halle des Wiegens", "arena": "imperial_colosseum", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["grabraeuber", 2.8, -1], ["grabraeuber2", 4.0, -1], ["seele", -3.5, 1]]),
			{"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "AURUM · DIE WAAGE IN DER MITTE", "sub": "Kapitel I – Die Halle des Wiegens"},
			S._narr("Seit dreitausend Jahren steht in der Halle unter der Arena eine Waage. Links ein Herz. Rechts eine Feder. Daneben ein Wächter aus Gold, der nie schläft."),
			S._narr("Aurum hat elf Millionen Herzen gewogen. Eines Nachts legte er sein eigenes Zahnrad-Herz in die Schale. Die Waage blieb stehen. Genau in der Mitte."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Weder schwer noch leicht. Weder gut noch schlecht. Was bin ich, wenn die Waage nichts sagt?"),
			S._cam("two", 0, 1.4, 1),
			S._say("grabraeuber", "Ein großer Haufen Gold, Kumpel! Und die Waage da ist auch aus Gold! Wir nehmen beides."),
			S._say("hero", "Ihr betretet die Halle der Toten. Eure Herzen wurden noch nicht gewogen. Ich könnte damit anfangen."),
			S._say("grabraeuber2", "Der redet! Schnell, bevor er rechnet!"),
			{"t": "qte", "kind": "press", "keys": ["grab"], "time": 1.3, "text": "KHOPESH-HAKEN!", "flag": "anubis_hook",
				"success": [S._narr("Der Sichelhaken fängt den Goblin am Gürtel und zieht ihn zurück. Gold klimpert auf den Boden.")],
				"fail": [S._narr("Der Haken greift ins Leere. Die Räuber grinsen.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "grabraeuber", "grabraeuber2"], "goal": "SCHÜTZE DIE HALLE DES WIEGENS!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "anubis_hook", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("seele", "Verzeihung … Wächter? Ich bin gestorben, glaube ich. Aber niemand hat mich gewogen. Ich warte schon so lange."),
			S._say("hero", "Die Waage steht still, Seele. Seit ich mein eigenes Herz darauf gelegt habe. Sie wiegt niemanden mehr."),
			S._say("seele", "Dann wiegst du eben ohne Waage. Kannst du das?"),
			S._cam("close", 0, 1.4),
			S._narr("Aurum weiß es nicht. In dreitausend Jahren hat er nie geurteilt. Er hat nur abgelesen."),
			S._say("seele", "Du darfst dir Zeit lassen. Ich warte. Ich bin ja schon tot, ich habe es nicht eilig."),
			S._say("hero", "Warum lachst du? Du bist tot. Du weißt nicht, wohin du gehst."),
			S._say("seele", "Weil mein Bruder auch immer so ernst geguckt hat wie du. Das hat mich jedes Mal zum Lachen gebracht."),
			S._narr("Etwas in Aurums Brust tickt. Nicht im Takt der Zahnräder. Anders. Wie eine Frage."),
		]},
		{"id": "anubis_2", "title": "Der Seelenernter", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["flayer", 2.5, -1], ["seele", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Seelenernter"},
			S._narr("Ohne Waage stauen sich die Seelen. Hunderte warten in der Festung über der Halle. Und dann kommt jemand, der sie nicht wiegt, sondern erntet."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("flayer", "Ein Richter aus Gold, dessen Waage streikt. Du bist nur ein Schmuckstück, das sich für göttlich hält."),
			S._say("flayer", "Ich nehme sie dir ab. Alle. Ich wiege nicht, ich sammle. Das geht schneller."),
			S._say("seele", "Bitte, Wächter. Ich will nicht gesammelt werden. Ich will wissen, ob ich gut war."),
			{"t": "choice", "text": "Was tut Aurum?", "options": [
				{"label": "Die Seele selbst richten", "flag": "anubis_judged", "steps": [
					S._say("hero", "Neferet. Erzähl mir dein Leben. Nicht für die Waage. Für mich."),
					S._say("seele", "Ich habe Brot gebacken. Ich habe gelogen, einmal, schlimm. Ich habe meinen Bruder gepflegt, als er krank war. Ist das genug?"),
					S._say("hero", "Ich weiß es nicht. Aber ich werde es nicht ihm überlassen, das zu entscheiden.")]},
				{"label": "Nach Regeln kämpfen", "flag": "anubis_rules", "steps": [
					S._say("hero", "Die Seelen dieser Halle gehören der Waage. Regel eins. Du bist ein Dieb. Dein Urteil ist einfach."),
					S._say("flayer", "Regeln! Wie langweilig. Komm, Schmuckstück.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "flayer"], "goal": "VERTEIDIGE DIE WARTENDEN SEELEN!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "anubis_judged", "steps": [
				S._say("flayer", "Du hast für eine einzige Seele gekämpft, als wäre sie eine Million. Seltsam für eine Maschine."),
				S._say("hero", "Sie ist eine. Eine ist genug."),
			], "else": [
				S._say("flayer", "Du kämpfst wie ein Paragraf. Präzise. Leer. Was würdest du tun, wenn die Regel falsch wäre?"),
			]},
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Eine Feder schwebt in die Festung. Sie ist schwarz wie eine mondlose Nacht – und sie fällt nach oben."),
		]},
		{"id": "anubis_3", "title": "Die schwarze Feder", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["ahriman", 3.0, -1], ["seele", -4.0, 1], ["flayer", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die schwarze Feder"},
			S._narr("Aurum folgt der Feder bis an das Tor der Hölle. Dort steht eine zweite Waage, aus Obsidian. Daneben ein Mann aus Marmor mit einem Lächeln aus Rauch."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("ahriman", "Bruder Waagschale. Ich habe deine Arbeit immer bewundert. So gerecht. So ohne Hass. So ohne alles."),
			S._say("ahriman", "Lass mich dir helfen. Lege meine Feder in deine Schale statt der weißen. Dann sinkt jedes Herz – und du musst nie wieder zweifeln."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Jedes Herz wäre schuldig."),
			S._say("ahriman", "Jedes Herz IST schuldig. Du richtest andere nur, weil du dein eigenes Urteil fürchtest. Ich nehme dir die Angst."),
			S._say("hero", "Wenn alle schuldig sind, ist Urteilen bedeutungslos. Ich habe drei Jahrtausende nicht geurteilt. Jetzt fange ich an. Mit dir."),
			S._music("boss"),
			{"t": "branch", "flag": "anubis_judged", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("seele", "Ich habe einmal schlimm gelogen. Aber ich lasse nicht zu, dass er meinen Bruder für schuldig erklärt!"),
				{"t": "fight", "cast": ["hero", "seele", "ahriman"], "goal": "WIRF DIE SCHWARZE FEDER AUS DER SCHALE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("flayer", "Wenn alle schuldig sind, habe ich nichts mehr zu ernten. Das ist schlecht fürs Geschäft. Ich helfe dir, Schmuckstück."),
				{"t": "fight", "cast": ["hero", "flayer", "ahriman"], "goal": "WIRF DIE SCHWARZE FEDER AUS DER SCHALE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Die Obsidianwaage zerspringt. Die schwarze Feder verbrennt in der Luft – und darunter liegt, unversehrt, eine weiße."),
			S._say("hero", "Die Feder der Ma'at. Er hatte sie gestohlen. Darum stand meine Waage still – nicht wegen meines Herzens."),
			S._say("ahriman", "Glaubst du das wirklich? Oder willst du es nur glauben, Schmuckstück?"),
			S._say("hero", "Ich weiß es nicht. Und zum ersten Mal ist das in Ordnung."),
		]},
		{"id": "anubis_4", "title": "Das Urteil", "arena": "bg_arena_sun", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["richter", 2.0, -1], ["seele", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das Urteil"},
			S._narr("Zurück in der Halle des Wiegens. Die weiße Feder liegt in Aurums Hand. Die Waage steht noch immer in der Mitte."),
			S._cam("two", 0, 1.6, 2),
			S._say("seele", "Leg dein Herz noch einmal darauf. Vielleicht weiß sie es jetzt."),
			S._say("hero", "Und wenn sie wieder schweigt?"),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("richter", "Dann bin ich da. Der Aurum ohne Zweifel. Ich lese ab, ich zweifle nicht, ich fühle nichts. Ich bin, was du dreitausend Jahre warst."),
			S._say("richter", "Kehr zu mir zurück. Zweifeln ist ein Defekt."),
			S._say("hero", "Zweifeln ist der Grund, warum ich Neferet zugehört habe. Du hättest sie einfach abgelesen."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "richter"], "goal": "BESIEGE DEN RICHTER OHNE ZWEIFEL!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._narr("Aurum legt die Waage nieder. Er wird nicht mehr ablesen. Er wird zuhören, jedem einzeln, so lange es dauert."),
			S._say("hero", "Die Waage stand in der Mitte, weil ich noch nicht fertig war. Niemand ist fertig, solange er wählen kann."),
			S._cam("two", 0, 1.6, 2),
			S._say("hero", "Neferet. Du hast gelogen und du hast geliebt. Ich urteile: Geh weiter. Dein Bruder wartet am anderen Ufer."),
			S._say("seele", "Woher weißt du das?"),
			S._say("hero", "Ich weiß es nicht. Ich habe entschieden, es zu glauben. Das ist der Unterschied zwischen einer Waage und einem Richter."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Aurum · Die Waage in der Mitte"},
			S._narr("Relikt erhalten: Die Feder der Ma'at  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
