extends RefCounted
## Legende: ALBION, DER SILBERWYRM – „Der vergessene Hort“.
## Vierhundert Jahre hütet Albion eine Truhe, deren Inhalt er vergessen hat. Eine Diebin mit losem Mundwerk,
## ein eifersüchtiger Vetter aus Eis und ein Seraph, der nichts vergisst, reißen ihm die Erinnerung in
## Scherben zurück. Hier erklärt sich der Sturmstrahl: ein ganzer Sturm, eingeatmet aus Liebe.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der vergessene Hort",
	"summary": "Albion hütet seit vierhundert Jahren eine Truhe, deren Inhalt er nicht kennt. Dann bricht eine Diebin ein – und behauptet, der Schatz gehöre ihrer Familie.",
	"relic": "Linneas Holzdrache",
	"relic_text": "Ein schief geschnitzter Drache mit Glasperlenaugen. Der wertvollste Schatz, den je ein Wyrm gehütet hat.",
}

const CAST := {
	"hero": {"preset": "albion", "name": "ALBION", "title": "Der Silberwyrm", "color": "e0f2fe"},
	"pip": {"preset": "shira", "name": "PIP", "title": "Schatzjägerin mit losem Mundwerk", "color": "fbbf24"},
	"hrimgar": {"preset": "frostwyrm", "name": "HRIMGAR", "title": "Der Frost-Wyrm, sein Vetter", "color": "38bdf8"},
	"linnea": {"preset": "lepora", "name": "LINNEA", "title": "Ein Hirtenmädchen, vor vierhundert Jahren", "color": "fde68a"},
	"edda": {"preset": "brunhild", "name": "GROSSMUTTER EDDA", "title": "Pips Großmutter", "color": "d6d3d1"},
	"seraph": {"boss": "seraph", "name": "SERAPHAEL", "title": "Das brennende Auge", "color": "ff3b1f"},
	"hort": {"preset": "albion", "name": "ALBION, DER HORT", "title": "Der Teil von ihm, der lieber zählt als fühlt", "color": "94a3b8"},
}

static func chapters() -> Array:
	return [
		{"id": "albion_1", "title": "Die Diebin im Hort", "arena": "frozen_summit", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["pip", 2.2, -1]]),
			{"t": "vanish", "who": 1},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "ALBION · DER VERGESSENE HORT", "sub": "Kapitel I – Die Diebin im Hort"},
			S._narr("Über den Wolken, wo selbst die Adler umkehren, liegt der Hort des letzten Silberwyrms. Gold, Kronen, Edelsteine. Und eine kleine Truhe, die er nie öffnet."),
			S._narr("Albion weiß nicht, was darin ist. Er weiß nur: Er würde für sie sterben."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Vierhundert Winter. Und keiner wagte den Aufstieg. Wir hatten beinahe vergessen, wie Besuch klingt."),
			S._narr("Besuch klingt, wie sich herausstellt, wie ein Dietrich in einem Schloss."),
			{"t": "fx", "kind": "shake"},
			{"t": "appear", "who": 1},
			S._pose(1, "Crouch", 0.6),
			S._cam("two", 0, 1.2, 1),
			S._say("pip", "Oh. Hallo. Du bist größer als auf den Bildern. Und glänzender. Ich klau nichts. Ich leih nur was aus. Für immer."),
			S._say("hero", "Ein Menschenkind. In UNSEREM Hort. Mit der Hand an UNSERER Truhe. Nenne deinen Namen, damit wir ihn auf deinen Grabstein meißeln können."),
			S._say("pip", "Pip. Und Grabstein ist ein bisschen dramatisch. Meine Familie erzählt seit Generationen, dass du unseren Schatz hast. Ich hol ihn nur zurück."),
			S._say("hero", "Jeder Dieb behauptet, das Gold habe seinem Großvater gehört."),
			S._say("pip", "Ich hab nicht Gold gesagt."),
			S._pose(1, "Dash", 0.5),
			{"t": "move", "who": 1, "x": 5.0, "time": 0.6},
			{"t": "qte", "kind": "press", "keys": ["jump"], "time": 1.4, "text": "SIE RENNT MIT DER TRUHE – SPRING HINTERHER!", "flag": "albion_chase",
				"success": [S._pose(0, "Dash", 0.6),
					S._narr("Albion stürzt sich über die Goldberge. Münzen regnen wie Hagel.")],
				"fail": [S._pose(0, "HitReact", 0.6),
					S._say("hero", "Wir sind auf eine Krone getreten. Das ist … sehr unwürdig.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "pip"], "goal": "FANG DIE DIEBIN, BEVOR SIE ENTKOMMT!", "lives": [3, 1], "time": 60, "qte": "albion_chase", "ai": 4,
				"mods": {"1": {"kb": 0.75}}},
			S._music("calm"),
			{"t": "move", "who": 1, "x": 2.0, "time": 0.6},
			S._pose(1, "Dazed", 1.0),
			S._cam("two", 0, 1.4, 1),
			S._say("pip", "Okay, okay! Ich ergebe mich! Aber sag mir eins: Was IST in der Truhe?"),
			S._cam("close", 0, 1.4),
			S._narr("Albion öffnet das Maul. Und schließt es wieder. Er weiß es nicht. Er hat es nie gewusst – oder er hat es vergessen."),
			S._say("hero", "Das … geht dich nichts an."),
			S._say("pip", "Du weißt es nicht! Du hütest seit vierhundert Jahren eine Truhe und weißt nicht, was drin ist! Das ist das Traurigste, was ich je gehört hab."),
			{"t": "fx", "kind": "flash"},
			S._stage([["linnea", -1.0, 1], ["hero", 1.8, -1]]),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "ERINNERUNG", "sub": "Scherbe I – Die Scheune"},
			S._pose(0, "Victory", 0.8),
			S._say("linnea", "Du bist viel zu groß für unsere Scheune, Silberner. Aber du darfst bleiben, bis der Sturm vorbei ist. Willst du Heu?"),
			{"t": "fx", "kind": "flash"},
			S._stage([["hero", -1.5, 1], ["pip", 2.0, -1]]),
			S._cam("two", 0, 0.8, 1),
			S._say("hero", "Ein Mädchen. In einer Scheune. Wir … erinnern uns an eine Scheune."),
			S._say("pip", "Dann komm mit runter ins Tal und find raus, was es war. Ich trag die Truhe. Ich bin sehr zuverlässig. Meistens."),
		]},
		{"id": "albion_2", "title": "Der blaue Vetter", "arena": "bg_aurora_peaks", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["pip", -3.6, 1], ["hrimgar", 3.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("hope"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der blaue Vetter"},
			S._narr("Der Abstieg dauert. Pip redet die ganze Zeit. Albion tut so, als würde er nicht zuhören, und lacht zweimal. Heimlich."),
			S._cam("two", 0, 1.4, 1),
			S._say("pip", "Und dann hab ich zum Wachhund gesagt: »Ich bin die Post!« Und er hat's GEGLAUBT. Weil Hunde nicht lesen können."),
			S._say("hero", "Wir sind beeindruckt. Ein wenig. Nicht sehr."),
			{"t": "fx", "kind": "shake"},
			S._music("tense"),
			{"t": "appear", "who": 2},
			S._cam("low", 2, 1.4),
			S._pose(2, "Roar", 1.0),
			S._say("hrimgar", "Silberner! Du verlässt deinen Gipfel? Nach vierhundert Jahren? Für einen Menschenwelpen mit einer Kiste?"),
			S._say("hero", "Hrimgar. Vetter. Du riechst noch immer nach nassem Gletscher."),
			S._say("hrimgar", "Und du nach Staub. Wir sind beide Wyrme, Albion. Aber nur einer von uns ist nicht allein. Ich habe meinen Winter. Was hast du?"),
			S._say("hrimgar", "Gib mir den Gipfel. Du weißt ja nicht mal, was du da oben hütest. Das weiß das ganze Gebirge."),
			S._cam("two", 0, 1.2, 1),
			S._say("pip", "Stimmt das? Du weißt es echt nicht?"),
			{"t": "choice", "text": "Was antwortet Albion?", "options": [
				{"label": "Die Wahrheit sagen", "flag": "albion_truth", "steps": [
					S._say("hero", "Es stimmt. Wir wissen nicht, was in der Truhe liegt. Wir wissen nicht einmal mehr, warum wir sie hüten. Das ist … beschämend."),
					S._say("pip", "Nee. Beschämend ist, so zu tun als ob. Hast du grad nicht gemacht. Ich helf dir, Großer.")]},
				{"label": "Stolz bleiben", "flag": "albion_pride", "steps": [
					S._say("hero", "Ein Silberwyrm vergisst nichts. Er schweigt nur, wenn Dummköpfe fragen."),
					S._say("pip", "Okay. Dann bin ich halt ein Dummkopf. Aber du lügst echt schlecht, weißt du das?")]},
			]},
			S._cam("two", 0, 1.2, 2),
			S._say("hrimgar", "Genug geredet. Mein Sturm, mein Berg. Zeig mir, ob dein Atem noch Silber ist!"),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "hrimgar"], "goal": "BESTEHE IM SCHNEESTURM DES VETTERS!", "lives": [2, 2], "ai": 5,
				"mods": {"1": {"power": 1.25, "kb": 0.85}}},
			S._music("hope"),
			S._pose(2, "Defeat", 1.0),
			S._cam("two", 0, 1.4, 2),
			S._say("hrimgar", "Dein Atem … der ist nicht von dieser Welt. Woher hast du so einen Sturm, Vetter? Den hattest du früher nicht."),
			S._narr("Albion sieht auf seine Klauen. Silberne Blitze tanzen darüber. Er weiß es nicht. Noch eine Scherbe, die fehlt."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "HALT DIE ERINNERUNG FEST!", "flag": "albion_shard",
				"success": [{"t": "fx", "kind": "flash"},
					S._narr("Scherbe II: eine Lawine. Schreie aus einem Tal. Ein Wyrm, der den Sturm einatmet, bis seine Brust zu zerreißen droht.")],
				"fail": [S._narr("Die Erinnerung zerfällt wie Pulverschnee. Nur ein Wort bleibt übrig: Lawine.")]},
			S._say("hrimgar", "Geh, Silberner. Aber über den Wolken warten welche, die alles sehen. Auch das, was du vergessen hast."),
			S._cam("sky", 0, 2.0),
			S._narr("Und noch bevor Albion antworten kann, fällt Licht vom Himmel wie ein Speer."),
		]},
		{"id": "albion_3", "title": "Das Auge, das nicht vergisst", "arena": "heaven_spheres", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["seraph", 3.0, -1], ["pip", -4.6, 1], ["linnea", -0.4, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das Auge, das nicht vergisst"},
			S._narr("Das Licht trägt Albion höher, als je ein Wyrm geflogen ist. Die kleine Truhe hängt an seiner Klaue."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.6),
			S._say("seraph", "Albion. Ich bin Seraphael, das brennende Auge. Ich sehe, was ist. Und was war."),
			S._say("seraph", "Du trägst eine Truhe und kennst ihren Inhalt nicht. Öffne sie vor mir – oder ich verbrenne sie. Und dich."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Wir öffnen sie nicht. Nicht vor dir. Nicht vor irgendwem."),
			S._say("seraph", "Warum? Du weißt es nicht. Ich aber. Sieh hin."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.4, 3),
			{"t": "title", "text": "ERINNERUNG", "sub": "Scherbe III – Die Lawine"},
			S._say("linnea", "Silberner! Der Schnee kommt den Berg runter! Meine Mama ist noch im Dorf!"),
			S._pose(0, "Beam", 1.2),
			S._narr("Albion atmete den Sturm ein. Den ganzen Sturm. Und spie ihn als silbernen Strahl in den Himmel, wo er niemandem mehr schaden konnte."),
			S._narr("Das Dorf blieb stehen. Aber ein Sturm nimmt immer etwas mit. Dieser nahm Albions Erinnerung an das Mädchen."),
			{"t": "vanish", "who": 3},
			S._cam("two", 0, 1.4, 1),
			S._say("seraph", "Das ist dein Sturmstrahl, Wyrm. Aus Liebe gemacht. Und Liebe, die man vergessen hat, brennt am schlimmsten. Lass mich sie dir abnehmen."),
			S._pose(0, "Roar", 1.0),
			S._music("boss"),
			S._say("hero", "Behalte dein Feuer, Auge. Wir haben gerade erst etwas wiedergefunden. Das geben wir nicht her."),
			{"t": "branch", "flag": "albion_truth", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -0.8, "time": 0.8},
				S._say("pip", "Ich hab mich an deinem Schwanz festgeklammert! Den ganzen Flug! Ich hasse Höhe! Wir machen das zusammen!"),
				{"t": "fight", "cast": ["hero", "pip", "seraph"], "goal": "STURMSTRAHL – MIT PIP GEGEN DAS AUGE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				S._narr("Pip ist unten im Tal geblieben. Albion hat sie nicht gefragt. Stolz ist schwer, und er trägt ihn allein."),
				{"t": "fight", "cast": ["hero", "seraph"], "goal": "STURMSTRAHL – ALLEIN GEGEN DAS AUGE!", "lives": [2, 1], "damage": {"0": 35}, "ai": 6},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._cam("close", 1, 1.4),
			S._narr("Seraphael schließt das Auge. Kein Zorn mehr darin. Nur Licht, mild wie ein Wintermorgen."),
			S._say("seraph", "Du hast den Schmerz behalten, um die Liebe zu behalten. Das ist das Klügste, was je ein Drache getan hat."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Wir hatten Hilfe. Von einem Mädchen in einer Scheune. Vor sehr langer Zeit."),
		]},
		{"id": "albion_4", "title": "Was der Hort hütet", "arena": "mystic_grove", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["hort", 2.0, -1], ["pip", -3.2, 1], ["edda", -5.5, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Was der Hort hütet"},
			S._narr("Im Tal von Silberbach steht ein Dorf, das es ohne Albion nicht gäbe. Am Dorfrand ein Hain. Pip stellt die Truhe auf einen Baumstumpf."),
			S._cam("two", 0, 1.4, 2),
			S._say("pip", "Hier hat meine Ur-ur-ur-Oma gewohnt. Linnea. Bei uns sagt man: Sie gab dem Silberdrachen ihr Liebstes. Und er gab uns allen das Leben."),
			S._say("hero", "Linnea. … Linnea. Der Name schmeckt nach Heu und Schneeluft."),
			S._cam("close", 0, 1.4),
			S._narr("Albion hebt die Klaue zum Schloss. Und da ist er wieder: der Griff in seiner Brust, der ihn vierhundert Jahre lang festgehalten hat."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("hort", "Nicht öffnen. Solange sie zu ist, kann alles darin sein. Gold. Kronen. Ein Grund. Öffnest du sie, ist es vielleicht nur Staub."),
			S._say("hero", "Du bist der Teil von uns, der lieber zählt als fühlt."),
			S._say("hort", "Ich bin der Teil, der dich vierhundert Jahre am Leben gehalten hat. Hüten ist sicher. Erinnern tut weh."),
			S._say("pip", "Hey, Glänzer Nummer zwei! Du redest wie mein Onkel, wenn er sich nicht den Zahn ziehen lassen will!"),
			S._music("boss_final"),
			{"t": "branch", "flag": "albion_truth", "steps": [
				S._say("hero", "Pip. Halt die Truhe. Was auch passiert – lass sie nicht los."),
				S._say("pip", "Mit meinem Leben, Großer. Na ja. Mit beiden Händen jedenfalls."),
				{"t": "fight", "cast": ["hero", "hort"], "goal": "ÖFFNE DEN HORT IN DIR!", "lives": [2, 2], "ai": 7, "mods": {"1": {"power": 0.9}}},
			], "else": [
				S._say("pip", "Du hast mich oben am Berg angelogen. Mach das nicht nochmal. Nicht mit dir selbst."),
				{"t": "fight", "cast": ["hero", "hort"], "goal": "ÖFFNE DEN HORT IN DIR!", "lives": [2, 2], "ai": 8, "mods": {"1": {"power": 1.15}}},
			]},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._narr("Albion öffnet die Truhe. Kein Gold. Keine Krone. Nur ein kleiner Drache aus Holz, schief geschnitzt, mit Augen aus zwei Glasperlen."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": -4.4, "time": 1.2},
			S._cam("two", 0, 1.4, 3),
			S._say("edda", "Den hat Linnea geschnitzt. Sie gab ihn dir, als du weggeflogen bist. Damit du nicht allein bist da oben. So erzählt man es bei uns."),
			S._say("hero", "Sie war acht. Sie trug Holzschuhe. Sie nannte uns »Silberner« und bot uns Heu an, obwohl Drachen kein Heu essen."),
			S._say("hero", "Wir haben es gegessen. Es war furchtbar. Wir haben es nie jemandem erzählt."),
			S._say("pip", "Du ERINNERST dich!"),
			S._cam("sky", 0, 3.0),
			S._narr("Der Silberwyrm lacht. Es klingt wie ein Sturm, der beschlossen hat, ein Wind zu sein."),
			{"t": "branch", "flag": "albion_truth", "steps": [
				S._narr("Seitdem liegt im Winter ein silberner Drache auf dem Dach von Pips Haus. Er sagt, er passe auf. Pip sagt, er friert nur ungern allein."),
			], "else": [
				S._narr("Er fliegt zurück auf seinen Gipfel. Aber jeden Winter landet er im Tal, entschuldigt sich bei Pip – und isst höflich ihr Heu."),
			]},
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Albion · Der vergessene Hort"},
			S._narr("Relikt erhalten: Linneas Holzdrache  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
