extends RefCounted
## Legende: HIKARU, ERBE DER GLUTKLINGE – „Die dreizehnte Form“.
## Seine Schwester Akane kannte alle zwölf Formen der Glutklinge. Hikaru kennt sie auch – aber nur als
## Kopie. Erinnerungskämpfe im Lichthain, ein Junge, der unbedingt sein Schüler werden will, ein
## Lehrmeister, der jeden Schnitt vorhersieht, und eine Finsternis, die ihm seine Schwester zurückgibt.
## Hier entsteht das Sonnenrad – die Form, die nur ihm gehört.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die dreizehnte Form",
	"summary": "Hikaru führt die Glutklinge seiner Schwester – Form für Form, genau wie sie. Doch die Klinge kühlt ab, denn sie brennt nur für den, der sein eigenes Feuer findet.",
	"relic": "Akanes Holzschwert",
	"relic_text": "Das Übungsschwert aus dem Lichthain, voller Kerben. Die tiefste ist von Hikaru.",
}

const CAST := {
	"hero": {"preset": "hikaru", "name": "HIKARU", "title": "Erbe der Glutklinge", "color": "ff6524"},
	"akane": {"preset": "phoenix", "name": "AKANE", "title": "Seine Schwester · Erinnerung", "color": "f97316"},
	"kenta": {"preset": "tobi", "name": "KENTA", "title": "Will unbedingt sein Schüler werden", "color": "facc15"},
	"tsuru": {"preset": "samurai_dreyar", "name": "MEISTERIN TSURU", "title": "Schmiedin der Glutklinge", "color": "94a3b8"},
	"jubei": {"preset": "jubei", "name": "JUBEI", "title": "Sein Lehrmeister", "color": "3bfac8"},
	"ahriman": {"boss": "ahriman", "name": "AHRIMAN", "title": "Die Finsternis", "color": "1e1b4b"},
	"shade": {"preset": "phoenix", "name": "AKANES SCHATTEN", "title": "Von der Finsternis geformt", "color": "7f1d1d"},
	"copy": {"preset": "hikaru", "name": "HIKARU, DIE KOPIE", "title": "Der, der nur nachmacht", "color": "64748b"},
}

static func chapters() -> Array:
	return [
		{"id": "hikaru_1", "title": "Zwölf Formen", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.6, 1], ["akane", 1.6, -1]]),
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "HIKARU · DIE DREIZEHNTE FORM", "sub": "Kapitel I – Zwölf Formen"},
			{"t": "fx", "kind": "flash"},
			S._narr("Erinnerung. Der Lichthain, vor zehn Jahren. Zwei Geschwister, ein Holzschwert und eine Klinge, die glüht wie ein Morgen."),
			S._cam("two", 0, 1.6, 1),
			S._say("akane", "Erste Form: Morgenrot. Du schneidest nicht ins Holz, Hikaru. Du schneidest durch die Nacht."),
			S._say("hero", "Durch die Nacht. Klar. Und wie schneidet man durch etwas, das gar nicht da ist?"),
			S._say("akane", "Indem man an den Morgen glaubt. Komm schon, kleiner Bruder. Triff mich ein einziges Mal, dann gibt's Reisbällchen."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "akane"], "goal": "ERINNERUNG: TRIFF DEINE SCHWESTER!", "lives": [1, 1], "mods": {"1": {"power": 0.6}}, "ai": 2},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Victory", 0.8),
			S._say("akane", "Hah! Getroffen! Na gut, eher gestreift. Ich zähle es trotzdem."),
			S._say("akane", "Zwölf Formen hat die Glutklinge. Ich kann sie alle. Aber die dreizehnte … die muss jeder selbst finden. Sie steht in keinem Buch."),
			S._say("hero", "Dann such ich sie für dich. Und du musst sie mir dann beibringen."),
			S._music("sad"),
			S._cam("close", 1, 1.8),
			S._narr("Ein Jahr später brannte ihr Dorf. Akane trug ihren kleinen Bruder aus dem Feuer. Dann ging sie zurück, um die anderen zu holen."),
			S._narr("Als Jubei den Jungen aus der Asche zog, hielt er die Glutklinge in den Händen. Sie war noch warm."),
			{"t": "fx", "kind": "flash"},
			S._stage([["hero", -1.0, 1], ["kenta", 3.0, -1], ["tsuru", -3.4, 1]]),
			{"t": "vanish", "who": 1},
			S._music("calm"),
			S._cam("wide", 0, 1.2),
			S._narr("Heute. Hikaru ist so alt wie Akane damals. Er kniet vor der Schmiede im Lichthain und hält ihr die Klinge hin."),
			S._cam("two", 0, 1.4, 2),
			S._say("tsuru", "Die Glut wird schwächer, Junge. Eine Glutklinge brennt nur für den, der sie mit eigenem Feuer füttert. Du fütterst sie mit Erinnerungen."),
			S._say("hero", "Erinnerungen sind das Einzige, was ich von ihr habe, Meisterin Tsuru."),
			S._say("tsuru", "Eben. Und davon kann auf Dauer nicht einmal eine Klinge leben."),
			{"t": "appear", "who": 1},
			{"t": "move", "who": 1, "x": 1.6, "time": 0.6},
			S._cam("close", 1, 1.0),
			S._say("kenta", "Bist du der mit der Feuerklinge? Bring mir alles bei! Ich bin Kenta! Ich kann schon fast einen Purzelbaum!"),
			S._say("hero", "Ich bin kein Lehrer. Ich bin nur der, der übrig geblieben ist."),
			{"t": "fx", "kind": "shake"},
			S._narr("Da kracht es im Hain. Eine uralte Zeder, vom Sturm gelockert, kippt – genau auf den Jungen zu."),
			{"t": "qte", "kind": "sequence", "keys": ["special", "standard", "special"], "time": 3.0, "text": "ERSTE FORM: MORGENROT!", "flag": "hikaru_form1",
				"success": [S._pose(0, "SpecialAttack", 0.8), {"t": "fx", "kind": "burst", "who": 0}, S._narr("Ein Schnitt wie ein Sonnenaufgang. Die Zeder fällt in zwei Hälften links und rechts an Kenta vorbei.")],
				"fail": [S._pose(0, "Attack", 0.8), S._narr("Der Schnitt ist krumm. Hikaru reißt Kenta im letzten Moment zur Seite. Die Zeder landet da, wo eben noch ein Kind stand.")]},
			S._say("kenta", "WOW! Wie hast du das gemacht?!"),
			S._cam("close", 0, 1.4),
			S._say("hero", "Hab ich nicht. Das war sie. Ich habe nur ihre Bewegung nachgemacht."),
		]},
		{"id": "hikaru_2", "title": "Der Meister, der jeden Schnitt kennt", "arena": "bg_dojo", "stars": 1, "steps": [
			S._stage([["hero", -1.6, 1], ["jubei", 2.4, -1], ["kenta", -4.2, 1]]),
			S._music("tense"),
			S._cam("low", 1, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Meister, der jeden Schnitt kennt"},
			S._narr("Jubeis Dojo. Hikaru hat hier zehn Jahre lang trainiert. Kenta ist ihm einfach gefolgt. Er sitzt in der Ecke und isst Hikarus Proviant."),
			S._say("jubei", "Du kommst zurück, weil die Klinge kalt wird. Ich weiß. Ich habe es gesehen, bevor du es gemerkt hast."),
			S._say("hero", "Dann zeig mir, was ich falsch mache, Meister. Ich kann alle zwölf Formen. Genau wie sie."),
			S._say("jubei", "Zeig sie mir. Alle zwölf. Hintereinander."),
			{"t": "qte", "kind": "sequence", "keys": ["standard", "special", "jump", "standard"], "time": 3.0, "text": "DIE ZWÖLF FORMEN – OHNE FEHLER!", "flag": "hikaru_forms",
				"success": [S._pose(0, "Spin", 0.8), S._narr("Zwölf Formen, sauber wie gezeichnet. Kenta lässt vor Staunen sein Reisbällchen fallen.")],
				"fail": [S._pose(0, "Dazed", 0.6), S._narr("Bei der neunten Form stolpert er. Er fängt sich und macht weiter – genau an der Stelle, an der Akane immer Luft geholt hat.")]},
			S._cam("two", 0, 1.4, 1),
			S._say("jubei", "Du kopierst sie, Junge. Jeder Schritt, jeder Schnitt – nur nicht ihr Mut. Akane hat nie eine Form zweimal gleich gemacht."),
			S._say("hero", "Weil sie es konnte. Ich darf nichts weglassen. Wenn ich etwas weglasse, dann … geht noch mehr von ihr verloren."),
			S._say("jubei", "Dann kämpf gegen mich. Und entscheide, wer heute die Klinge führt."),
			{"t": "choice", "text": "Wie kämpft Hikaru gegen seinen Meister?", "options": [
				{"label": "Wie Akane – Form für Form", "flag": "hikaru_akane", "steps": [
					S._say("hero", "Wie sie. Sauber. Vollständig. So, wie sie es mir gezeigt hat."),
					S._say("jubei", "Gut. Dann weiß ich jetzt schon, wo du in drei Atemzügen stehen wirst.")]},
				{"label": "Wie Hikaru – auch wenn es falsch ist", "flag": "hikaru_own", "steps": [
					S._say("hero", "Ich … weiß nicht genau, wie ich kämpfe. Aber ich glaube, ich will es herausfinden."),
					S._say("jubei", "Endlich ein Satz, der nicht von ihr stammt.")]},
			]},
			S._music("fight"),
			{"t": "branch", "flag": "hikaru_akane", "steps": [
				{"t": "fight", "cast": ["hero", "jubei"], "goal": "ER KENNT JEDE FORM – BESIEGE IHN TROTZDEM!", "lives": [2, 2], "mods": {"1": {"power": 1.2, "kb": 0.75}}, "ai": 7},
			], "else": [
				{"t": "fight", "cast": ["hero", "jubei"], "goal": "FINDE DEINEN EIGENEN RHYTHMUS!", "lives": [2, 2], "time": 100, "ai": 5},
			]},
			S._music("hope"),
			S._pose(1, "Idle", 0.8),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "hikaru_akane", "steps": [
				S._say("jubei", "Perfekt. Exakt wie sie. Und genau deshalb habe ich jeden Schnitt kommen sehen. Ich habe ihr diese Formen beigebracht, Hikaru."),
				S._say("hero", "Ich habe trotzdem gewonnen."),
				S._say("jubei", "Knapp. Mit ihrem Schwert, ihren Schritten, ihrem Atem. Frag dich, wer da eigentlich gewonnen hat."),
			], "else": [
				S._say("jubei", "Unsauber. Wild. Zum ersten Mal seit zehn Jahren wusste ich nicht, was du als Nächstes tust."),
				S._say("hero", "War das … gut?"),
				S._say("jubei", "Das war deins. Ob es gut ist, entscheidest du nicht heute."),
			]},
			{"t": "move", "who": 2, "x": -2.4, "time": 0.6},
			S._say("kenta", "Meister Hikaru, du warst unglaublich!"),
			S._say("hero", "Nenn mich nicht Meister. Ich hab dir nicht mal einen Purzelbaum beigebracht."),
			S._music("tense"),
			S._cam("close", 1, 1.6),
			S._say("jubei", "Noch etwas. Die Finsternis hat nach dir gefragt. Ahriman sammelt Erinnerungen, die man nicht loslassen kann. Du bist für ihn ein Festmahl."),
		]},
		{"id": "hikaru_3", "title": "Was die Finsternis zurückgibt", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -1.8, 1], ["ahriman", 3.6, -1], ["shade", 1.8, -1], ["kenta", -4.4, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Was die Finsternis zurückgibt"},
			S._narr("Am Tor der Hölle brennt kein Feuer. Hier ist es so dunkel, dass selbst die Glutklinge nur noch wie eine Kerze glimmt."),
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.2),
			S._music("boss"),
			S._say("ahriman", "Erbe der Glutklinge. Du riechst nach Asche und nach Heimweh. Ich habe etwas für dich gefunden. Ganz unten. Es hat nach dir gerufen."),
			{"t": "appear", "who": 2},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 2, 1.6),
			S._say("shade", "Hikaru? Du bist so groß geworden. Du trägst ja mein Schwert."),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Akane …"),
			S._say("ahriman", "Sie bleibt an deiner Seite. Für immer. Du musst nur aufhören, nach vorne zu gehen. Ist das nicht ein kleiner Preis?"),
			{"t": "fx", "kind": "shake"},
			{"t": "appear", "who": 3},
			S._narr("Hinter Hikaru stolpert jemand durch das Tor. Klein, außer Atem, mit einem Holzschwert in der Hand. Kenta ist ihm wieder gefolgt."),
			{"t": "qte", "kind": "press", "keys": ["jump"], "time": 1.4, "text": "DER BODEN BRICHT – FANG KENTA!", "flag": "hikaru_catch",
				"success": [{"t": "move", "who": 3, "x": -2.6, "time": 0.4}, S._narr("Hikaru springt, packt den Jungen am Kragen und landet sicher. Kenta strahlt, als wäre das Absicht gewesen.")],
				"fail": [{"t": "fx", "kind": "shake"}, S._narr("Kenta rutscht über die Kante. Hikaru bekommt ihn erst im zweiten Griff zu fassen und schürft sich den Arm auf.")]},
			S._cam("two", 0, 1.4, 2),
			S._say("shade", "Wer ist der Junge? Lass ihn liegen. Du brauchst keinen Schüler, Hikaru. Du hast doch mich."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Nein. Akane hätte ihn hochgehoben, ihm den Staub abgeklopft und ihm sofort die erste Form gezeigt."),
			S._say("hero", "Du hast ihr Gesicht. Aber du hast nie im Lichthain gestanden."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "ahriman", "shade"], "goal": "ALLEIN GEGEN FINSTERNIS UND ERINNERUNG!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "hikaru_catch", "ai": 5},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "burst", "who": 0},
			S._cam("sky", 0, 2.0),
			S._narr("Mitten im Kampf hat sich Hikarus Glut zum ersten Mal zu einem Rad gedreht – zu einer Sonne, die aufsteigt. Keine der zwölf Formen sieht so aus."),
			S._pose(2, "Defeat", 1.0),
			S._cam("two", 0, 1.4, 2),
			S._say("shade", "Dieses Rad … das kenne ich nicht."),
			S._say("hero", "Ich auch nicht. Ich glaube, es ist von mir."),
			{"t": "vanish", "who": 2},
			S._cam("close", 3, 1.2),
			S._say("kenta", "Sie hätte gelacht, oder? Über das Rad. Und dann hätte sie es dir nachgemacht."),
			S._say("hero", "… Ja. Ganz genau das hätte sie."),
		]},
		{"id": "hikaru_4", "title": "Die dreizehnte Form", "arena": "bg_moon_temple", "stars": 3, "steps": [
			S._stage([["hero", -1.2, 1], ["copy", 2.2, -1], ["kenta", -3.0, 1], ["jubei", -4.2, 1], ["tsuru", -5.4, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Die dreizehnte Form"},
			S._narr("Der Mondtempel über dem alten Dorf. Hier steht Akanes Stein. Heute ist ihr Tag. Hikaru ist vor Sonnenaufgang gekommen, wie jedes Jahr."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Ich hab sie gefunden, glaube ich. Die dreizehnte. Sie ist schief. Sie dreht sich falsch herum. Du würdest dich totlachen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("copy", "Eine eigene Form? Du? Du hast zehn Jahre lang nachgemacht. Du bist ein Spiegel, in dem sie noch ein bisschen weiterlebt."),
			S._say("copy", "Ohne sie bist du niemand. Gib es zu. Leg das Rad weg und mach wieder die zwölf Formen. Dann bleibt sie bei dir."),
			S._say("hero", "Sie bleibt nicht in den Formen. Sie bleibt in dem, was ich damit mache."),
			{"t": "branch", "flag": "hikaru_akane", "steps": [
				S._say("copy", "Wirklich? Bei Jubei hast du noch ihre Schritte gewählt. Ich bin all die Jahre, in denen du sie nachgemacht hast. Ich bin stark geworden."),
				S._music("boss_final"),
				{"t": "fight", "cast": ["hero", "copy"], "goal": "BIS DIE SONNE AUFGEHT!", "lives": [2, 2], "time": 110, "mods": {"1": {"power": 1.2}}, "ai": 7},
			], "else": [
				S._say("copy", "Bei Jubei hast du deinen eigenen Weg gewählt. Ein Mal. Ein Mal ist kein Leben, Kleiner."),
				S._music("boss_final"),
				{"t": "fight", "cast": ["hero", "copy"], "goal": "BIS DIE SONNE AUFGEHT!", "lives": [2, 2], "time": 110, "ai": 7},
			]},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			S._cam("sky", 0, 2.4),
			S._narr("Die Sonne steigt über den Tempel. Hikaru hebt die Glutklinge – und zum ersten Mal ist ihre Flamme nicht orange wie Akanes, sondern golden wie der Morgen."),
			S._pose(0, "SpecialAttack", 1.2),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Die dreizehnte Form. Ein Sonnenrad, das sich schief dreht, falsch herum, und genau deshalb niemandem gehört außer ihm."),
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3}, {"t": "appear", "who": 4},
			S._cam("two", 0, 1.4, 2),
			S._narr("Hinter ihm klatscht jemand. Ganz leise erst, dann lauter. Kenta. Neben ihm Jubei, der so tut, als hätte er Staub im Auge."),
			S._say("tsuru", "Die Klinge brennt wieder. Nicht mit ihrem Feuer. Mit deinem. Ich habe nicht geglaubt, dass ich das noch erlebe."),
			S._say("kenta", "Bringst du mir das bei? Das Rad? Bitte, bitte, bitte?"),
			S._cam("close", 0, 1.6),
			S._say("hero", "Erste Lektion: Du schneidest nicht ins Holz. Du schneidest durch die Nacht. Die ist von meiner Schwester."),
			S._say("hero", "Die zweite Lektion ist von mir. Und ich glaube, sie wird ein bisschen schief."),
			S._pose(0, "Victory", 1.2),
			S._cam("sky", 0, 3.0),
			S._narr("Auf Akanes Stein liegt seitdem jedes Jahr ein neues Holzschwert. Und jedes Jahr hat es eine Kerbe mehr."),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Hikaru · Die dreizehnte Form"},
			S._narr("Relikt erhalten: Akanes Holzschwert  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
