extends RefCounted
## Legende: MAGMOR – „Die Glocke von Eisgrund“.
## Vierzig Jahre hat der Schmiedeofen von Ambosstal allein weitergeglüht. Dann klopft ein Mädchen aus
## einem Dorf ohne Sommer an. Ein frierender Bergbrecher, ein Dämon, der Wärme in Gold aufwiegt, und eine
## Glocke, die nie gegossen wurde. Hier erfährt man, was in Magmors Magmaklumpen eigentlich glüht.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die Glocke von Eisgrund",
	"summary": "Seit vierzig Jahren glüht Magmor in einer leeren Schmiede. Als ein Mädchen aus einem Dorf ohne Sommer ihn um Wärme bittet, verlässt er zum ersten Mal seinen Platz.",
	"relic": "Brandts Gießkelle",
	"relic_text": "Eine schwarze Kelle mit einem Rest Bronze darin. Sie ist immer ein kleines bisschen warm.",
}

const CAST := {
	"hero": {"preset": "golem", "name": "MAGMOR", "title": "Glut, die nicht erlischt", "color": "ff6d2b"},
	"brandt": {"preset": "bruno", "name": "MEISTER BRANDT", "title": "Der letzte Schmied von Ambosstal", "color": "d6a77a"},
	"siri": {"preset": "glaciem", "name": "SIRI", "title": "Schmiedelehrling aus Eisgrund", "color": "93c5fd"},
	"ole": {"preset": "tobi", "name": "OLE", "title": "Siris kleiner Bruder", "color": "fcd34d"},
	"warrok": {"preset": "warrok_brute", "name": "WARROK", "title": "Der Bergbrecher", "color": "a16207"},
	"mammon": {"boss": "mammon", "name": "MAMMON", "title": "Der Wäger", "color": "eab308"},
	"schlacke": {"preset": "golem", "name": "MAGMOR, DIE SCHLACKE", "title": "Was ohne Feuer übrig bleibt", "color": "44403c"},
}

static func chapters() -> Array:
	return [
		{"id": "golem_1", "title": "Vierzig Jahre Glut", "arena": "bg_foundry", "stars": 0, "steps": [
			S._stage([["hero", -0.5, 1], ["brandt", 1.8, -1], ["siri", 7.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "MAGMOR · DIE GLOCKE VON EISGRUND", "sub": "Kapitel I – Vierzig Jahre Glut"},
			S._narr("Ambosstal. Vor vierzig Jahren war hier die lauteste Schmiede im Gebirge. Hundert Hämmer, ein Ofen. Der Ofen hieß Magmor."),
			S._cam("two", 0, 1.6, 1),
			S._say("brandt", "Halt die Glut, Großer. Morgen gießen wir die Glocke für die Stadt. Die erste, die man bis ins Tal hört."),
			S._say("hero", "Ich. Halte. Die Glut."),
			S._narr("Am nächsten Morgen kam niemand. Der Berg war unruhig geworden, die Stadt zog fort. Meister Brandt ging ein letztes Mal in den Stollen. Er kam nicht zurück."),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("close", 0, 1.8),
			S._narr("Magmor hielt die Glut. Vierzig Jahre lang. Er zählte die Zeit in Schichten. Es waren vierzehntausendsechshundert."),
			S._say("hero", "Schicht vierzehntausendsechshundertundeins. Glut: gut. Hämmer: keine. Meister: kommt morgen."),
			{"t": "fx", "kind": "shake"},
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": 2.6, "time": 1.0},
			S._cam("two", 0, 1.2, 2),
			S._say("siri", "Da bist du ja, du Riesenkessel. Halt still. Ich schneid dir nur den Kern raus, dann bin ich schon weg."),
			S._say("hero", "Vorsicht. Ich bin heiß. Du bist … kalt. Sehr kalt. Wenn ich zuschlage, zerbrichst du."),
			S._say("siri", "Dann schlag halt nicht zu! Ich hab drei Wochen Fußmarsch hinter mir, ich geh nicht ohne Wärme nach Hause!"),
			S._narr("Magmor hat seit vierzig Jahren niemanden berührt. Er hat Angst, dass alles, was er anfasst, schmilzt."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "siri"], "goal": "NICHT ZU FEST ZUSCHLAGEN!", "lives": [2, 2], "mods": {"0": {"power": 0.6}}, "ai": 3},
			S._music("hope"),
			S._pose(1, "Dazed", 1.0),
			S._cam("two", 0, 1.6, 1),
			S._say("siri", "Uff. Du hättest mich zerquetschen können. Hast du aber nicht. Warum?"),
			S._say("hero", "Ein Ofen ist zum Wärmen. Nicht zum Zerquetschen. Hat Brandt gesagt."),
			S._say("siri", "In Eisgrund, meinem Dorf, ist seit drei Jahren Winter. Kein Sommer, keine Sonne. Die Alten sagen, in Ambosstal brennt ein Ofen, der nie ausgeht."),
			S._cam("close", 0, 1.6),
			S._pose(0, "Charge", 1.0),
			S._narr("Magmor greift in seine Brust. Dort schwappt etwas Schweres, Goldenes: die Bronze für Brandts Glocke. Vierzig Jahre flüssig gehalten."),
			S._say("hero", "Wenn ich werfe, werfe ich Glockenbronze. Sie will raus. Vielleicht will sie nach Eisgrund."),
			S._say("hero", "Ich verlasse die Schmiede. Zum ersten Mal. Brandt … wenn du morgen kommst: Ich bin bald zurück."),
		]},
		{"id": "golem_2", "title": "Der Pass der Bergbrecher", "arena": "frozen_summit", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["siri", -3.6, 1], ["warrok", 3.0, -1]]),
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Pass der Bergbrecher"},
			S._narr("Zwölf Tage durch Schnee. Bei jedem Schritt zischt es unter Magmors Füßen. Und bei jedem Schritt bekommt seine Kruste einen neuen Riss."),
			S._cam("two", 0, 1.4, 1),
			S._say("siri", "Du knackst. Das klingt nicht gut. Das klingt wie Eis auf dem See, kurz bevor man einbricht."),
			S._say("hero", "Kälte. Nicht gut für Öfen. Weitergehen."),
			{"t": "fx", "kind": "shake"},
			S._pose(2, "Roar", 1.0),
			S._cam("close", 2, 1.2),
			S._say("warrok", "HALT! Das ist mein Pass. Wer hier durch will, zahlt Zoll. Und ich nehm kein Gold. Ich nehm WÄRME."),
			S._say("warrok", "Steine wie du zerbrechen, Ofen. Ich hab schon Berge zerbrochen. Drei Stück. Unter Bergen ist es warm, weißt du."),
			S._say("hero", "Unter Bergen ist es dunkel. Ich war vierzig Jahre in einem. Gib den Weg frei."),
			S._narr("Die Kälte hat Magmor schon halb zerrissen. Er muss die Glut in seiner Brust anfachen, bevor der Riese zuschlägt."),
			{"t": "qte", "kind": "mash", "keys": ["special"], "count": 12, "time": 3.0, "text": "GLUT ANFACHEN!", "flag": "golem_glut",
				"success": [{"t": "fx", "kind": "burst", "who": 0}, S._narr("Die Risse in Magmors Kruste leuchten orange. Der Schnee um ihn herum verdampft in einer weißen Wolke.")],
				"fail": [S._narr("Nur ein müdes Glimmen. Warrok grinst und lässt die Knochenkeule kreisen.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "warrok"], "goal": "BRICH DEN BERGBRECHER!", "lives": [2, 2], "damage": {"0": 35}, "qte": "golem_glut", "ai": 5},
			S._music("calm"),
			S._pose(2, "Defeat", 1.2),
			S._cam("two", 0, 1.6, 2),
			S._narr("Warrok liegt im Schnee und zittert. Nicht vor Angst. Vor Kälte. Magmor sieht ihn lange an. Dann setzt er sich neben ihn."),
			S._say("warrok", "… Was machst du da?"),
			S._say("hero", "Wärmen. Ich bin ein Ofen."),
			S._say("warrok", "Hm. Ist gut. Ist sehr gut. Hör zu, Ofen: Euer Sommer ist nicht weg. Den hat einer gekauft. Ein goldener Kerl mit einer Waage."),
			S._say("warrok", "Hat meiner Sippe Gold dafür gezahlt, dass wir den Pass bewachen. Gold wärmt nicht. Hab ich zu spät gemerkt."),
			S._say("siri", "Jemand hat unseren Sommer gekauft? Wie kauft man einen Sommer?!"),
			S._say("hero", "Weiß nicht. Aber man kann ihn zurückholen. Warrok. Du trägst ab jetzt das Gepäck."),
			S._say("warrok", "Ich bin ein Bergbrecher! Ich trag doch kein … na gut. Aber nur, wenn ich neben dir laufen darf."),
		]},
		{"id": "golem_3", "title": "Die Waage", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["mammon", 2.8, -1], ["warrok", -4.0, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Waage"},
			S._narr("Unter dem Gletscher liegt eine Stadt aus Gold. Dort ist es eiskalt. Gold hält keine Wärme, es zeigt sie nur."),
			S._narr("In der Mitte hängt eine Sonne in einem Käfig. Klein, blass, eingesperrt. Der Sommer von Eisgrund."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.2),
			S._say("mammon", "Ein Ofen! Wie selten. Lass dich wiegen, Großer. Vierzig Jahre Glut, ohne Pause … Das ist mehr wert als drei Sommer zusammen."),
			S._say("mammon", "Ich mache dir ein faires Geschäft. Ich bin immer fair. Dein Feuer gegen den Sommer von Eisgrund. Du wirst kalt. Das Dorf wird warm."),
			S._cam("close", 0, 1.4),
			S._say("warrok", "Hör nicht auf ihn, Ofen. Der hat mir auch was Faires angeboten."),
			S._say("hero", "Ohne Feuer bin ich … was?"),
			S._say("mammon", "Schlacke. Grauer Stein. Aber ein Dorf voller Kinder hätte Sonne. Rechne selbst."),
			{"t": "choice", "text": "Magmors Feuer gegen den Sommer?", "options": [
				{"label": "Das Feuer verkaufen", "flag": "golem_sold", "steps": [
					S._say("hero", "Nimm es. Kinder sind wichtiger als Öfen."),
					{"t": "fx", "kind": "ink", "who": 0},
					S._pose(0, "Dazed", 1.2),
					S._narr("Die Glut fließt aus Magmor in Mammons Waage. Die Sonne im Käfig wird hell und steigt fort – nach Eisgrund. Magmor wird grau."),
					S._say("mammon", "Wunderbar. Den Sommer gebe ich frei, wie versprochen. Von meinem Schatzwächter habe ich allerdings nichts gesagt. Der bin ich."),
					S._music("boss"),
					{"t": "fight", "cast": ["hero", "mammon"], "goal": "KALT, ABER NICHT GEBROCHEN!", "lives": [3, 1], "mods": {"0": {"power": 0.75, "kb": 1.1}}},
				]},
				{"label": "Das Feuer behalten", "flag": "golem_kept", "steps": [
					S._say("hero", "Nein. Das Feuer gehört mir nicht. Es gehört Brandt. Und der Glocke. Ich hol den Sommer anders."),
					S._say("mammon", "Anders? Mit Gewalt? Wie unhöflich. Dann wiege ich dich eben – auf meine Art."),
					S._pose(1, "Summon", 1.0),
					S._music("boss"),
					{"t": "fight", "cast": ["hero", "mammon"], "goal": "SPRENG DEN KÄFIG DER SONNE!", "lives": [3, 1], "mods": {"1": {"power": 1.25}}},
				]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "vanish", "who": 1},
			S._cam("two", 0, 1.6, 2),
			{"t": "branch", "flag": "golem_sold", "steps": [
				S._narr("Mammons Gold zerfällt zu kaltem Sand. Magmor steht da, grau und still. Er hat gewonnen. Er spürt es nicht."),
				S._say("warrok", "Ofen? Du bist ja ganz kalt. Komm. Diesmal trag ich dich."),
			], "else": [
				S._narr("Der Käfig schmilzt unter einem Klumpen Glockenbronze. Die kleine Sonne schüttelt sich und steigt auf – nach Eisgrund."),
				S._say("warrok", "Hah! Ein Ofen, der einen Dämon einschmilzt! Das erzähl ich meinen Enkeln. Wenn ich mal welche hab."),
			]},
		]},
		{"id": "golem_4", "title": "Die Glocke von Eisgrund", "arena": "bg_aurora_peaks", "stars": 3, "steps": [
			S._stage([["hero", -1.0, 1], ["siri", -3.0, 1], ["schlacke", 2.4, -1], ["warrok", -4.4, 1], ["ole", 8.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 4},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Die Glocke von Eisgrund"},
			S._narr("Eisgrund. Der Schnee schmilzt, die Bäche laufen wieder. Doch heute Nacht zieht ein letzter Sturm über die Eisfelder – und Ole ist nicht nach Hause gekommen."),
			S._cam("two", 0, 1.6, 1),
			S._say("siri", "Mein kleiner Bruder ist da draußen. Man sieht die Hand vor Augen nicht. Früher hat das Dorf bei Sturm die Glocke geläutet. Wir haben keine mehr."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Ich habe Bronze. Genug für eine Glocke. Aber wenn ich sie gieße, gebe ich mein Herz her."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.4, 2),
			S._say("schlacke", "Ohne Feuer bist du nur ein Haufen Schlacke. Gib es zu. Gieß die Glocke, und von dir bleibt das hier: ich. Grau. Nutzlos. Vergessen."),
			S._say("hero", "Vierzig Jahre hab ich die Glut gehalten. Für eine Glocke. Nicht für mich."),
			S._say("schlacke", "Dann zeig mir, wie viel du wert bist, wenn du nicht heiß bist."),
			S._music("boss_final"),
			{"t": "branch", "flag": "golem_sold", "steps": [
				S._narr("Magmor ist kalt seit der Waage. Aber er steht."),
				{"t": "fight", "cast": ["hero", "schlacke"], "goal": "SEI MEHR ALS DEINE HITZE!", "lives": [2, 2], "damage": {"0": 45}, "mods": {"1": {"power": 0.85}}, "ai": 6},
			], "else": [
				{"t": "fight", "cast": ["hero", "schlacke"], "goal": "SEI MEHR ALS DEINE HITZE!", "lives": [2, 2], "ai": 7},
			]},
			S._music("hope"),
			{"t": "vanish", "who": 2},
			{"t": "branch", "flag": "golem_sold", "steps": [
				S._cam("two", 0, 1.6, 1),
				S._narr("Siri holt ein Streichholz aus der Tasche. Sie hält es an Magmors graue Brust. Es zischt. Ganz tief drinnen glimmt etwas."),
				S._say("siri", "Feuer kann man nicht verkaufen, du Dummkopf. Man kann es nur weitergeben. Und manchmal gibt’s einer zurück."),
			], "else": []},
			S._cam("low", 0, 2.0),
			S._pose(0, "SpecialAttack", 1.4),
			{"t": "fx", "kind": "flash"},
			S._narr("Magmor öffnet seine Brust. Die Bronze fließt in eine Form aus Schnee und Stein, die Warrok mit bloßen Fäusten gegraben hat."),
			S._narr("Sie zischt. Sie kühlt. Und dann schlägt Magmor zum ersten Mal in seinem Leben vorsichtig zu."),
			{"t": "fx", "kind": "shake"},
			S._narr("DONG. Die Glocke von Ambosstal läutet über Eisgrund. Man hört sie bis ins Tal. So, wie Brandt es wollte."),
			{"t": "appear", "who": 4},
			{"t": "move", "who": 4, "x": 1.5, "time": 1.6},
			S._cam("two", 1, 1.4, 4),
			S._say("ole", "Ich bin einfach dem Ton nachgelaufen! Siri, Siri! Wer ist der große, rauchende Mann?"),
			S._say("hero", "Kein Mann. Ein Ofen. … Nein. Magmor. Ich heiße Magmor."),
			S._cam("close", 0, 1.6),
			S._narr("Magmor ist jetzt kleiner. Kühler. Still. Und er merkt, dass er immer noch da ist. Kinder sitzen an ihm und wärmen sich die Hände."),
			S._say("warrok", "Und? Wie fühlt es sich an, nur noch lauwarm zu sein?"),
			S._say("hero", "Gut. Lauwarm ist genau richtig zum Anlehnen."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Magmor · Die Glocke von Eisgrund"},
			S._narr("Relikt erhalten: Brandts Gießkelle  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
