extends RefCounted
## Legende: SCARLET, DIE FEUERJÄGERIN – „Der zehnte Name“.
## Scarlet ist neunmal gestorben und neunmal aus der Asche gestiegen – jedes Mal mit einer
## Erinnerung weniger. Pyrus, der Feuermagier, hat ihre Bücher verbrannt; der Seraph fragt nach
## ihrem ersten Namen; und beim zehnten Mal könnte nichts mehr von ihr übrig bleiben.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der zehnte Name",
	"summary": "Scarlet ist neunmal gestorben. Jedes Mal stieg sie aus der Asche – und jedes Mal fehlte eine Erinnerung mehr. Sie weiß nicht mehr, wofür sie ursprünglich gekämpft hat.",
	"relic": "Die Erdbeere aus Glut",
	"relic_text": "Eine Erdbeere aus rotem Glas, warm wie eine Hand. Wer sie hält, erinnert sich an den ersten Sommer, an den er sich nicht mehr erinnern konnte.",
}

const CAST := {
	"hero": {"preset": "phoenix", "name": "SCARLET", "title": "Die Feuerjägerin", "color": "f43f5e"},
	"pyrus": {"preset": "wizard_sorcerer", "name": "PYRUS", "title": "Der Feuermagier", "color": "f97316"},
	"hikaru": {"preset": "hikaru", "name": "HIKARU", "title": "Kennt sie aus einem früheren Leben", "color": "fb923c"},
	"jaeger": {"preset": "vanguard_soldier", "name": "FEDERJÄGER", "title": "Phönixfedern bringen Unsterblichkeit", "color": "94a3b8"},
	"seraph": {"boss": "seraph", "name": "SERAPHAEL", "title": "Das brennende Auge", "color": "fde047"},
	"asche": {"preset": "phoenix", "name": "DIE ZEHNTE ASCHE", "title": "Scarlet, wenn nichts mehr bleibt", "color": "52525b"},
}

static func chapters() -> Array:
	return [
		{"id": "phoenix_1", "title": "Neun Mal", "arena": "volcano_sanctum", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["jaeger", 3.0, -1], ["hikaru", -3.5, 1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "SCARLET · DER ZEHNTE NAME", "sub": "Kapitel I – Neun Mal"},
			S._narr("Scarlet ist neunmal gestorben. Ein Pfeil, ein Sturz, ein Fieber, ein Duell, fünf Mal Feuer. Neunmal stieg sie aus der Asche auf, mit Federn wie Glut."),
			S._narr("Doch jedes Mal blieb etwas in der Asche zurück. Der Name ihrer Stadt. Das Gesicht ihrer Mutter. Das Lied, das sie als Kind sang."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Ich weiß, dass ich jage. Ich weiß nicht mehr, warum. Irgendwann habe ich es aufgeschrieben. Die Bücher sind weg."),
			S._cam("two", 0, 1.4, 1),
			S._say("jaeger", "Eine Phönixfeder macht unsterblich, sagt man. Ich brauche nur eine. Oder alle. Halt still, Vogel."),
			S._say("hero", "Unsterblich? Glaub mir, Jäger. Du willst nicht, was ich habe."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "PHÖNIXFLAMME!", "flag": "phoenix_flare",
				"success": [S._narr("Scarlets Gleve flammt auf. Die Federn auf ihren Schultern leuchten wie ein Sonnenaufgang.")],
				"fail": [S._narr("Die Flamme stottert. Für einen Moment hat sie vergessen, wie es geht.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "jaeger"], "goal": "VERTREIBE DEN FEDERJÄGER!", "lives": [3, 2], "qte": "phoenix_flare", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.8, "time": 0.8},
			S._cam("two", 0, 1.6, 2),
			S._say("hikaru", "Lina? Lina, bist du das? Du bist … größer. Und rot. Aber du stehst genauso da wie früher!"),
			S._say("hero", "Ich heiße Scarlet. Wer ist Lina?"),
			S._say("hikaru", "Wir sind zusammen aufgewachsen. Du hast mir beigebracht, wie man ein Feuer macht. Weißt du das nicht mehr?"),
			S._cam("close", 0, 1.4),
			S._narr("Sie weiß es nicht. Aber das Wort Lina kribbelt in ihrem Nacken wie Funken."),
			S._say("hikaru", "Du hast immer gesagt, wenn ich dich je vergesse, soll ich dir einen Kieselstein an den Kopf werfen."),
			S._say("hero", "Wirf ihn nicht."),
			S._say("hikaru", "Ich habe ihn schon seit sieben Jahren in der Tasche. Für den Fall. Ich werfe ihn nicht. Ich gebe ihn dir."),
			S._narr("Ein glatter grauer Stein. Er bedeutet ihr nichts. Sie steckt ihn trotzdem ein, dicht neben ihr Herz."),
		]},
		{"id": "phoenix_2", "title": "Die verbrannte Bibliothek", "arena": "bg_foundry", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["pyrus", 2.5, -1], ["hikaru", -3.5, 1]]),
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die verbrannte Bibliothek"},
			S._narr("Hikaru führt sie zu einer Gießerei am Fluss. Früher war hier eine Bibliothek. Scarlet hat dort ihre Bücher geschrieben. Dann kam ein Magier."),
			S._cam("two", 0, 1.6, 1),
			S._say("pyrus", "Die Feuerjägerin. Ich habe deine Tagebücher gelesen, weißt du. Bevor ich sie verbrannt habe. Interessante Lektüre."),
			S._say("hero", "Du hast meine Erinnerungen verbrannt?"),
			S._say("pyrus", "Ich verbrenne jedes Buch, das ich gelesen habe. Damit niemand mich je übertrifft. Deine waren nicht einmal besonders gut geschrieben."),
			S._say("hikaru", "Sag ihr, was darin stand, Magier!"),
			{"t": "choice", "text": "Was will Scarlet von Pyrus?", "options": [
				{"label": "Die Wahrheit hören", "flag": "phoenix_asked", "steps": [
					S._say("hero", "Ich will nicht kämpfen. Erzähl mir einen Satz daraus. Nur einen."),
					S._say("pyrus", "Einen? … »Ich kämpfe, damit Hikaru nie allein ist.« Da. Zufrieden? Jetzt verschwinde.")]},
				{"label": "Rache nehmen", "flag": "phoenix_revenge", "steps": [
					S._say("hero", "Dann brenne ich, was von dir übrig ist."),
					S._say("pyrus", "Feuer gegen Feuer? Wie originell.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "pyrus"], "goal": "FEUER GEGEN FEUER!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "phoenix_asked", "steps": [
				S._say("pyrus", "Du kämpfst für den Jungen da. Das stand im Buch. Seite zwölf. Ich … habe mir die Seite gemerkt. Warum, weiß ich nicht."),
				S._say("hikaru", "Für mich?"),
			], "else": [
				S._say("pyrus", "Rache. Wie langweilig. Im Buch stand, dass du nie aus Rache kämpfst. Du hast es also auch vergessen."),
				S._narr("Das trifft härter als jede Flamme."),
			]},
			{"t": "fx", "kind": "flash"},
			S._narr("Über der Gießerei öffnet sich der Himmel. Ein riesiges Auge in sechs Flügeln blickt herab. Es ruft einen Namen. Nicht Scarlet."),
		]},
		{"id": "phoenix_3", "title": "Der erste Name", "arena": "empyrean", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["seraph", 3.0, -1], ["hikaru", -4.0, 1], ["pyrus", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der erste Name"},
			S._narr("Das Licht zieht sie hinauf ins Empyreum, wo alles brennt und nichts verbrennt. Ein Auge, größer als eine Stadt, sieht sie an."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("seraph", "Phönix. Neunmal bist du hierher aufgestiegen, neunmal hast du mir einen anderen Namen genannt. Heute will ich den ersten."),
			S._say("seraph", "Wer ihn vergessen hat, gehört dem Feuer. Wer ihn kennt, darf zurück."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Ich … der Junge hat mich Lina genannt. Aber ich weiß nicht, ob das stimmt. Ich erinnere mich nicht."),
			S._say("seraph", "Dann bleibst du hier. Asche zu Asche."),
			S._say("hero", "Neun Leben lang bin ich aufgestanden, ohne zu wissen warum. Ich stehe auch ein zehntes Mal auf."),
			S._music("boss"),
			{"t": "branch", "flag": "phoenix_asked", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("hikaru", "Sie heißt Lina! Ich erinnere mich für sie! Und ich lasse sie nicht allein, nicht nach allem, was sie für mich getan hat!"),
				{"t": "fight", "cast": ["hero", "hikaru", "seraph"], "goal": "STEIG ÜBER DAS BRENNENDE AUGE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("pyrus", "Ich habe deine Bücher verbrannt. Ich schulde dir wohl ein Kapitel. Nur dieses eine."),
				{"t": "fight", "cast": ["hero", "pyrus", "seraph"], "goal": "STEIG ÜBER DAS BRENNENDE AUGE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Das Auge schließt sich langsam. Nicht besiegt. Zufrieden. Aus seinen Wimpern fällt eine einzige Feder in Scarlets Hand. Sie ist warm."),
			S._say("seraph", "Du kennst deinen ersten Namen noch nicht. Aber du hast gekämpft, als würdest du ihn kennen. Geh. Such ihn dort, wo du ihn verloren hast."),
			S._say("hero", "Wo habe ich ihn verloren?"),
			S._say("seraph", "Nicht im Feuer. Davor. Dort, wo es noch warm war, ohne zu brennen."),
		]},
		{"id": "phoenix_4", "title": "Der zehnte Name", "arena": "bg_sunset_stadium", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["asche", 2.0, -1], ["hikaru", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der zehnte Name"},
			S._narr("Ein leeres Stadion bei Sonnenuntergang. Hier haben sie als Kinder gespielt, sagt Hikaru. Scarlet sieht nur Sitze und Licht."),
			S._cam("two", 0, 1.6, 2),
			S._say("hikaru", "Du hast hier Erdbeeren verkauft, im Sommer. Und alle selbst gegessen, bevor jemand kam."),
			S._say("hero", "Das klingt nach jemandem, den ich gern gekannt hätte."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("asche", "Beim zehnten Mal bleibt nichts übrig. Kein Name. Kein Junge. Kein Sommer. Nur Feuer, das weiß, wie man jagt."),
			S._say("asche", "Ist das so schlimm? Ohne Erinnerungen tut nichts weh."),
			S._say("hero", "Ohne Erinnerungen tut nichts weh. Und nichts schmeckt. Ich will wieder wissen, wie Erdbeeren schmecken."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "asche"], "goal": "STEIG EIN LETZTES MAL AUF!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Rise", 1.0),
			S._narr("Die Asche zerfällt. Darin, ganz unten, leuchtet etwas Kleines. Ein Bild: ein Mädchen mit roten Fingern, das lacht."),
			S._say("hero", "Lina. Ich hieß Lina. Und ich mochte Erdbeeren lieber als alles auf der Welt."),
			S._cam("two", 0, 1.6, 2),
			S._narr("Hikaru hält ihr eine Schale hin. Woher er die hat, sagt er nicht. Sie isst eine. Sie schmeckt nach Sommer. Sie schmeckt nach Leben."),
			S._say("hikaru", "Und? Wie heißt du jetzt?"),
			S._say("hero", "Scarlet. Und Lina. Beides. Ich habe neun Leben verloren, um zu lernen, dass man ein altes Ich nicht wegwerfen muss."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Scarlet · Der zehnte Name"},
			S._narr("Relikt erhalten: Die Erdbeere aus Glut  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
