extends RefCounted
## Legende: AMETHYA, DIE DONNERHEXE – „Gewitterkind“.
## Mit sieben fing sie einen Blitz in einem Kristall. Dreizehn Jahre später geht in Neon-Metropolis
## das Licht aus, eine Erzmagierin will den Kristall, und ein Engel verlangt ihn zurück – denn der
## Blitz ist kein Blitz, sondern ein Kind des Sturms. Hier zeigt sich, woher ihre Blitzspur kommt.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Gewitterkind",
	"summary": "Amethya trägt seit ihrem siebten Geburtstag einen gefangenen Blitz bei sich. Als die Stadt im Dunkeln liegt, erfährt sie, dass ihr Donner lebt – und dass seine Mutter ihn sucht.",
	"relic": "Der offene Kristall",
	"relic_text": "Ein Amethyst mit einem Sprung. Er hält nichts mehr fest – und knistert trotzdem, wenn Funke in der Nähe ist.",
}

const CAST := {
	"hero": {"preset": "amethya", "name": "AMETHYA", "title": "Die Donnerhexe", "color": "60d5ff"},
	"raska": {"preset": "wizard_sorcerer", "name": "OMA RASKA", "title": "Wetterhexe im Ruhestand", "color": "fbbf24"},
	"pixa": {"preset": "shira", "name": "PIXA", "title": "Stromdiebin aus dem Kabelviertel", "color": "f472b6"},
	"hunter": {"preset": "swat_specops", "name": "KRISTALLJÄGER", "title": "Medeas Mann fürs Grobe", "color": "6b7280"},
	"hunter2": {"preset": "vanguard_soldier", "name": "KRISTALLJÄGERIN", "title": "Medeas Frau fürs Grobe", "color": "6b7280"},
	"medea": {"preset": "sorceress_medea", "name": "MEDEA", "title": "Die Erzmagierin vom Sturmturm", "color": "a855f7"},
	"funke": {"preset": "celestial_fox", "name": "FUNKE", "title": "Das Gewitterkind", "color": "fb923c"},
	"potestas": {"boss": "potestas", "name": "POTESTAS", "title": "Engel der Gewalten", "color": "fde68a"},
	"leer": {"preset": "amethya", "name": "AMETHYA OHNE DONNER", "title": "Nur ein Mädchen mit einem Stein", "color": "64748b"},
}

static func chapters() -> Array:
	return [
		{"id": "amethya_1", "title": "Stromausfall", "arena": "neon_metropolis", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["raska", -3.2, 1], ["pixa", 2.5, -1], ["hunter", 8.0, -1], ["hunter2", 9.5, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "AMETHYA · GEWITTERKIND", "sub": "Kapitel I – Stromausfall"},
			S._narr("Neon-Metropolis leuchtet heller als jeder Stern. Bis um 23:14 Uhr alle Lichter gleichzeitig ausgehen."),
			S._narr("Nur ein Fenster brennt noch: die Werkstatt von Oma Raska. Dort summt ein violetter Kristall wie ein Herz."),
			S._cam("two", 0, 1.6, 1),
			S._say("raska", "Kind, das ist kein normaler Ausfall. Jemand saugt den Strom aus der ganzen Stadt. Wie mit einem Strohhalm."),
			S._say("hero", "Dann zieh ich den Strohhalm raus. Zack. Erledigt. Wo ist der Becher?"),
			S._say("raska", "Das Krankenhaus läuft auf Notstrom. Noch zehn Minuten. Du bist die Einzige in der Stadt, die genug Saft hat."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Charge", 1.0),
			{"t": "fx", "kind": "flash"},
			S._narr("Amethya war sieben, als sie auf einem Dach nach einem Blitz griff und ihn in einem Kristall festhielt. Seitdem schläft sie nie ganz. Der Donner auch nicht."),
			S._say("hero", "Halt dich fest, Kleiner. Wir machen Überstunden."),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": 1.2, "time": 0.8},
			S._cam("close", 2, 1.2),
			S._say("pixa", "Ey! Ihr habt Licht? Ich bin Pixa. Ich klaue Strom – aber nur von Leuten, die zu viel davon haben."),
			S._say("hero", "Perfekt. Dann kennst du die Leitungen. Zeig mir den schnellsten Weg zum Krankenhaus. Über die Dächer."),
			S._say("pixa", "Über die Dächer? Bei dem Wind? Du bist ja komplett durchgebrannt."),
			S._say("hero", "Durchgebrannt ist mein zweiter Vorname. Lauf!"),
			{"t": "qte", "kind": "sequence", "keys": ["jump", "special", "jump"], "time": 3.0, "text": "SPRING VON MAST ZU MAST!", "flag": "amethya_route",
				"success": [S._narr("Ein violetter Strich zieht über die dunkle Stadt. Wo Amethya rennt, bleibt der Blitz noch einen Herzschlag lang in der Luft hängen.")],
				"fail": [S._pose(0, "HitReact", 0.6), S._narr("Sie verfehlt einen Mast, landet in einer Regentonne und flucht in zwei Sprachen. Aber sie kommt an.")]},
			{"t": "appear", "who": 3}, {"t": "appear", "who": 4},
			{"t": "move", "who": 3, "x": 3.2, "time": 1.0},
			{"t": "move", "who": 4, "x": 4.6, "time": 1.2},
			S._cam("two", 0, 1.2, 3),
			S._say("hunter", "Da ist der Kristall. Die Herrin will ihn haben. Mit oder ohne Hand dran."),
			S._say("pixa", "Medeas Leute! Ihr Turm frisst nachts mehr Strom als zehn Viertel zusammen. Ich wusste, dass die dahinterstecken!"),
			S._say("hero", "Neun Minuten bis zum Notstrom-Ende. Ihr habt also ungefähr eine. Danach hab ich keine Zeit mehr für euch."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "hunter", "hunter2"], "goal": "BEVOR DER NOTSTROM AUSFÄLLT!", "lives": [2, 1, 1], "teams": [0, 1, 1], "time": 80, "qte": "amethya_route", "ai": 3},
			S._music("hope"),
			S._cam("wide", 0, 1.4),
			S._narr("Die Jäger fliehen. Amethya legt die Hand auf den Hauptverteiler. Die Lichter springen an – Stockwerk für Stockwerk, Station für Station."),
			S._pose(0, "Victory", 1.0),
			S._cam("two", 0, 1.4, 1),
			S._say("raska", "Gut gemacht. Aber hast du es gehört? Als du den Strom abgegeben hast. Der Kristall hat geweint."),
			S._say("hero", "Kristalle weinen nicht, Oma. Die knistern."),
			S._cam("close", 0, 1.8),
			S._music("sad"),
			S._narr("Doch in dieser Nacht knistert er anders. Leiser. Wie jemand, der Heimweh hat."),
		]},
		{"id": "amethya_2", "title": "Die Erzmagierin", "arena": "bg_storm_roof", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["pixa", -3.6, 1], ["medea", 2.6, -1], ["funke", -1.0, 1]]),
			{"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 2, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Erzmagierin"},
			S._narr("Drei Nächte später. Auf dem Dach von Medeas Sturmturm fällt der Regen waagerecht."),
			S._say("medea", "Die kleine Donnerhexe. Du hältst den Kristall wie ein Spielzeug. Weißt du überhaupt, was darin wohnt?"),
			S._cam("close", 0, 1.2),
			S._say("hero", "Ein Blitz. Meiner. Ich hab ihn gefangen, ich hab ihn gefüttert, ich hab mit ihm Mathe gemacht. Er war besser als ich."),
			S._say("medea", "Ein Blitz dauert einen Augenblick. Was du da trägst, lebt seit dreizehn Jahren. Das ist ein Kind des Sturms. Und seine Mutter sucht es."),
			{"t": "fx", "kind": "shake"},
			S._cam("sky", 0, 2.0),
			S._narr("Über der Stadt dreht sich eine Gewitterwand. Seit Wochen. In den Nachrichten heißt sie nur »Wetterphänomen«."),
			S._cam("two", 0, 1.4, 2),
			S._say("medea", "Gib ihn mir. Mein Turm kann ihn halten. Der Sturm bekommt ihn nie zurück – und die Stadt hat Strom für hundert Jahre."),
			S._say("hero", "Du willst ihn genauso einsperren wie ich. Nur mit einem größeren Käfig und schlechterer Aussicht."),
			S._say("medea", "Kristalle splittern, Kind. Und du splitterst mit."),
			S._say("pixa", "Amethya … das Ding kratzt gerade von innen. Wie ein Hund an der Tür."),
			{"t": "choice", "text": "Was tut Amethya mit dem Kristall?", "options": [
				{"label": "Den Kristall öffnen", "flag": "amethya_opened", "steps": [
					S._pose(0, "Cast", 0.8),
					S._narr("Sie dreht den Kristall, bis er klickt. Zum ersten Mal seit dreizehn Jahren fällt Licht heraus."),
					S._say("hero", "Hallo? Ich … ich hätte dich fragen sollen. Ganz am Anfang. Tut mir leid."),
					S._narr("Eine Stimme wie Funkenregen: »Endlich redest du MIT mir. Nicht immer nur ÜBER mich.«")]},
				{"label": "Den Kristall festhalten", "flag": "amethya_kept", "steps": [
					S._pose(0, "Block", 0.8),
					S._say("hero", "Nein. Er ist alles, was ich hab. Ohne ihn bin ich … irgendwer. Der Kristall bleibt zu."),
					S._narr("Der Kristall wird heiß in ihrer Hand. Fast zu heiß, um ihn zu halten.")]},
			]},
			S._narr("Medea hebt die Arme. Aus dem Turm schießt der gestohlene Strom der ganzen Stadt in sie hinein."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "medea"], "goal": "BRICH DIE MACHT DES STURMTURMS!", "lives": [2, 2], "mods": {"1": {"power": 1.25, "kb": 0.85}}, "ai": 5},
			S._music("calm"),
			{"t": "branch", "flag": "amethya_opened", "steps": [
				{"t": "appear", "who": 3},
				{"t": "fx", "kind": "burst", "who": 3},
				S._cam("close", 3, 1.4),
				S._say("funke", "Ich bin Funke. Und eins muss ich richtigstellen: Ich hab dich damals vom Dach gezogen. Du warst kurz vorm Fallen."),
				S._say("hero", "Moment. Ich dachte, ICH hab DICH gefangen."),
				S._say("funke", "Wir haben uns gegenseitig festgehalten. Das ist was ganz anderes."),
				{"t": "vanish", "who": 3},
			], "else": [
				S._cam("two", 0, 1.4, 2),
				S._say("medea", "Du hältst ihn genau wie ich. Merk dir das, wenn der Himmel kommt, um ihn zu holen."),
				S._say("hero", "Der Himmel kann sich hinten anstellen."),
			]},
			{"t": "fx", "kind": "flash"},
			S._cam("sky", 0, 2.4),
			S._narr("In der Gewitterwand über der Stadt öffnet sich etwas. Kein Blitz. Ein Auge aus Licht."),
		]},
		{"id": "amethya_3", "title": "Das Gericht der Gewalten", "arena": "heaven_spheres", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["potestas", 3.0, -1], ["funke", -3.4, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das Gericht der Gewalten"},
			S._narr("Ein Blitz holt sie vom Dach. Nicht der Sturm – etwas, das über dem Sturm wohnt."),
			S._narr("Amethya landet auf einer Scheibe aus Glas, die zwischen leuchtenden Sphären treibt. Jede Sphäre summt in einem anderen Wetter."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._music("boss"),
			S._say("potestas", "Amethya, Enkelin der Raska. Ich bin Potestas. Ich ordne die Gewalten: Wind, Feuer, Donner. Du hast eine davon gestohlen."),
			S._say("hero", "Gestohlen? Ich war SIEBEN. Ich hab nach etwas gegriffen, das leuchtet. Das machen alle Kinder so."),
			S._say("potestas", "Und dreizehn Jahre lang hast du nicht losgelassen. Die Mutter des Sturms wütet über deiner Stadt. Gib zurück, was nicht dir gehört."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.4, "text": "DER RICHTSPRUCH FÄLLT – BLOCKEN!", "flag": "amethya_verdict",
				"success": [S._pose(0, "Block", 0.6), S._narr("Der Lichtschlag prallt an ihrem Blitzschild ab. Potestas hebt eine Braue. Das hat lange niemand geschafft.")],
				"fail": [S._pose(0, "HitReact", 0.6), {"t": "fx", "kind": "shake"}, S._say("hero", "Au. Okay. Das war ein sehr deutliches Urteil.")]},
			{"t": "branch", "flag": "amethya_opened", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.0, "time": 0.6},
				S._say("funke", "Ich geh nicht zurück, bevor sie fertig ist! Ich will kämpfen. MIT ihr. Nicht IN ihr."),
				S._say("potestas", "Ein Sturmkind, das wählt. Das ist … neu. Dann zeigt mir, ob eure Wahl Bestand hat."),
				S._music("fight"),
				{"t": "fight", "cast": ["hero", "funke", "potestas"], "goal": "DONNER UND HEXE – GEMEINSAM!", "lives": [3, 2, 2], "teams": [0, 0, 1], "qte": "amethya_verdict", "ai": 6},
			], "else": [
				S._say("potestas", "Du willst ihn behalten? Dann trag ihn auch, wenn er schwer wird."),
				{"t": "fx", "kind": "ink", "who": 0},
				S._narr("Der Kristall glüht so heiß, dass jede Bewegung brennt. Der Donner darin tobt – gegen den Engel und gegen sie."),
				S._music("fight"),
				{"t": "fight", "cast": ["hero", "potestas"], "goal": "HALTE DURCH – TROTZ DER GLUT IM KRISTALL!", "lives": [2, 1], "damage": {"0": 50}, "qte": "amethya_verdict", "ai": 5},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._pose(1, "Idle", 0.8),
			S._say("potestas", "Genug. Ich nehme ihn dir nicht weg. Aber der Sturm über deiner Stadt hört nicht auf, bis seine Mutter ihr Kind gesehen hat."),
			S._say("potestas", "Das ist kein Urteil, Donnerhexe. Das ist Familie. Die kann kein Engel ordnen."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Familie. Super. Ausgerechnet das Fach, in dem ich noch schlechter bin als in Mathe."),
		]},
		{"id": "amethya_4", "title": "Das Dach, auf dem alles anfing", "arena": "bg_neon_skyline", "stars": 3, "steps": [
			S._stage([["hero", -1.0, 1], ["leer", 2.2, -1], ["funke", -2.4, 1], ["raska", -4.0, 1], ["pixa", -5.2, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("sad"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das Dach, auf dem alles anfing"},
			S._narr("Das Dach, auf dem eine Siebenjährige einmal nach einem Blitz gegriffen hat. Die Gewitterwand hängt jetzt direkt darüber."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Okay. Okay, okay, okay. Ich lass ihn raus. Und dann bin ich … einfach ich. Was auch immer das ist."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("leer", "Weißt du, was du ohne ihn bist? Ein Mädchen mit einem Stein in der Hand. Keine Spur am Himmel. Niemand, der hinsieht."),
			S._say("hero", "Du klingst wie ich um drei Uhr morgens."),
			S._say("leer", "Ich BIN du um drei Uhr morgens. Ohne Donner bist du langsam. Laut. Und ganz allein auf einem Dach."),
			S._pose(0, "Cast", 1.0),
			{"t": "fx", "kind": "flash"},
			S._narr("Amethya öffnet den Kristall ganz. Der Donner steigt aus ihr heraus – und mit ihm die Hälfte ihrer Kraft."),
			{"t": "appear", "who": 2},
			{"t": "branch", "flag": "amethya_opened", "steps": [
				S._say("funke", "Ich bin gleich zurück. Versprochen. Ich sag nur kurz Mama Hallo."),
			], "else": [
				S._narr("Ein kleiner Fuchs aus Licht springt heraus. Er sieht sie einmal an – unsicher, fremd – und rennt hinauf in den Sturm."),
			]},
			{"t": "move", "who": 2, "x": -9.0, "time": 0.8},
			{"t": "vanish", "who": 2},
			S._cam("low", 1, 1.2),
			S._say("leer", "Siehst du? Weg. Und jetzt zeig mir, was übrig ist."),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 12, "time": 3.0, "text": "BLEIB AUF DEN BEINEN!", "flag": "amethya_stand",
				"success": [S._narr("Ihre Knie zittern. Sie steht trotzdem. Kein Blitz hilft ihr dabei. Nur sie selbst.")],
				"fail": [S._pose(0, "Dazed", 0.8), S._narr("Sie fällt auf ein Knie. Und steht wieder auf, langsamer als je zuvor.")]},
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "leer"], "goal": "OHNE DONNER – NUR DU!", "lives": [2, 2], "mods": {"0": {"power": 0.85}}, "qte": "amethya_stand", "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			S._cam("sky", 0, 2.4),
			S._narr("Die Gewitterwand teilt sich. Ein riesiger Umriss aus Blitzen beugt sich über die Stadt – und ein winziger Funke springt in seine Arme."),
			S._narr("Dann wird es still. Amethya steht im Regen. Keine Spur am Himmel. Nur ihr eigener Atem."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -0.2, "time": 0.6},
			S._narr("Bis es hinter ihr knistert."),
			S._cam("two", 0, 1.4, 2),
			{"t": "branch", "flag": "amethya_opened", "steps": [
				S._say("funke", "Mama sagt, ich darf wählen. Ich wähle dich. Aber diesmal ohne Kristall. Ich wohne BEI dir, nicht IN dir."),
			], "else": [
				S._say("funke", "Ich kenne dich kaum. Aber du hast mich gehen lassen. Das will ich kennenlernen."),
			]},
			S._say("hero", "Dann … Partner? Du rennst vor, ich zieh die Spur hinterher?"),
			S._say("funke", "Umgekehrt. Aber nett, dass du fragst."),
			S._pose(0, "Victory", 1.0),
			{"t": "appear", "who": 3}, {"t": "appear", "who": 4},
			S._say("raska", "Dein Donner ist freiwillig zurückgekommen, Kind. Das schaffen die wenigsten mit ihren Kindern."),
			S._say("pixa", "Und die Stadt hat wieder Strom. Ich klau ab jetzt nur noch halb so viel. Ehrenwort. Fast."),
			S._cam("sky", 0, 3.0),
			S._narr("Seitdem zieht sich nachts eine Blitzspur in zwei Farben über Neon-Metropolis: violett – und ein kleines bisschen fuchsrot."),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Amethya · Gewitterkind"},
			S._narr("Relikt erhalten: Der offene Kristall  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
