extends RefCounted
## Legende: LEPORA, DIE MONDJÄGERIN – „Der erste Pfeil“.
## Lepora jagt nur bei Vollmond. Den Rest des Monats sucht sie den Pfeil, den sie als Kind
## verschoss – den einzigen, den ihre Mutter ihr geschnitzt hat. Der Himmelsfuchs weiß, wo er
## steckt, Virtus fragt sie, was sie wirklich treffen will, und Lepora verfehlt absichtlich.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der erste Pfeil",
	"summary": "Lepora trifft alles, was sie anvisiert – außer dem, was sie wirklich treffen will. Seit Jahren sucht sie den ersten Pfeil, den ihre Mutter ihr schnitzte und den sie als Kind in die Nacht schoss.",
	"relic": "Der Pfeil aus Mondholz",
	"relic_text": "Ein kleiner, krummer Kinderpfeil, schief befiedert. Er fliegt nie geradeaus – aber immer dorthin, wo jemand wartet.",
}

const CAST := {
	"hero": {"preset": "lepora", "name": "LEPORA", "title": "Die Mondjägerin", "color": "e0e7ff"},
	"fox": {"preset": "celestial_fox", "name": "HIMMELSFUCHS", "title": "Weiß, wo der Pfeil steckt", "color": "fde68a"},
	"mossback": {"preset": "mossback", "name": "MOSSBACK", "title": "Hüter des Waldes", "color": "65a30d"},
	"wilderer": {"preset": "swat_specops", "name": "WILDERER", "title": "Jagt, was nicht seins ist", "color": "94a3b8"},
	"wilderer2": {"preset": "vanguard_soldier", "name": "WILDERER", "title": "Jagt, was nicht seins ist", "color": "94a3b8"},
	"virtus": {"boss": "virtus", "name": "VIRTUS", "title": "Engel der Kräfte", "color": "fde68a"},
	"zielt": {"preset": "lepora", "name": "DIE VERFEHLENDE", "title": "Lepora, die nie trifft", "color": "818cf8"},
}

static func chapters() -> Array:
	return [
		{"id": "lepora_1", "title": "Vollmond", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["wilderer", 2.8, -1], ["wilderer2", 4.0, -1], ["mossback", -4.0, 1]]),
			{"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "LEPORA · DER ERSTE PFEIL", "sub": "Kapitel I – Vollmond"},
			S._narr("Lepora jagt nur bei Vollmond. Dann trifft sie alles: eine fallende Eichel auf hundert Schritt, die Sehne eines fremden Bogens, eine Lüge im Flug."),
			S._narr("Den Rest des Monats sucht sie. Einen kleinen, krummen Pfeil, den ihre Mutter ihr schnitzte. Sie schoss ihn mit sieben Jahren in den Mond. Am nächsten Tag war die Mutter fort."),
			S._cam("two", 0, 1.4, 1),
			S._say("wilderer", "Der Mondhirsch. Sein Geweih leuchtet im Dunkeln. Der bringt mehr als ein Jahreslohn."),
			S._say("hero", "Der Mondhirsch steht unter dem Schutz dieses Waldes. Und unter meinem."),
			S._say("wilderer2", "Eine Bogenschützin gegen zwei Gewehre? Das ist keine Jagd, das ist Mathematik."),
			S._say("hero", "Dann rechne mit dem Mond. Heute ist er voll."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.2, "text": "MONDPFEIL!", "flag": "lepora_moon",
				"success": [S._narr("Ein silberner Pfeil spaltet den Lauf eines Gewehrs. Der Wilderer starrt fassungslos.")],
				"fail": [S._narr("Der Pfeil streift nur den Ärmel. Lepora runzelt die Stirn. Das passiert ihr bei Vollmond nie.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "wilderer", "wilderer2"], "goal": "SCHÜTZE DEN MONDHIRSCH!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "lepora_moon", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("mossback", "Gut geschossen, Jägerin. Der Wald dankt. Aber er fragt sich, warum du jedes Mal danebenschießt, wenn du den Mond anvisierst."),
			S._say("hero", "Ich schieße nicht auf den Mond. Ich suche nur etwas, das dort hingeflogen ist."),
			S._say("mossback", "Der Fuchs mit den neun Schwänzen weiß, wo alles liegt, was in den Himmel geflogen ist. Aber er lügt bei jeder zweiten Antwort."),
			S._say("hero", "Dann frage ich ihn zweimal."),
			S._say("mossback", "Klug. Aber er merkt das. Er merkt alles. Nur nicht, was er selbst sucht."),
			S._cam("close", 0, 1.4),
			S._narr("Lepora sieht zum Mond hinauf. Er ist voll und rund und still. Siebzehn Jahre hat sie auf ihn geschossen. Siebzehn Jahre hat er geschwiegen."),
			S._say("hero", "Ich komme, Fuchs. Halt deine Lügen bereit."),
		]},
		{"id": "lepora_2", "title": "Neun Antworten", "arena": "bg_moon_temple", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["fox", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Neun Antworten"},
			S._narr("Im Mondtempel, wo der Himmel durch das zerbrochene Dach fällt, wartet der Himmelsfuchs. Er hat sie erwartet. Er erwartet jeden."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("fox", "Die Mondjägerin! Du suchst einen Pfeil. Ich habe neun Antworten für dich. Eine davon ist wahr."),
			S._say("hero", "Ich habe keine Zeit für neun. Ich will die wahre."),
			S._say("fox", "Die wahre kostet einen Treffer. Triff mich – nur einmal, richtig – und ich sage sie dir. Aber ich glaube, du willst gar nicht treffen."),
			{"t": "choice", "text": "Wie jagt Lepora den Fuchs?", "options": [
				{"label": "Mit dem Mond zielen", "flag": "lepora_moonaim", "steps": [
					S._say("hero", "Der Mond zielt mit mir. Er hat mich nie im Stich gelassen."),
					S._say("fox", "Der Mond nicht. Aber du dich selbst? Mal sehen.")]},
				{"label": "Mit dem Herzen zielen", "flag": "lepora_heart", "steps": [
					S._narr("Lepora senkt den Bogen. Sie schließt die Augen. So hat ihre Mutter es ihr beigebracht, bevor sie ging."),
					S._say("fox", "Oho. Das ist neu. Das ist gefährlich. Für dich, nicht für mich.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "fox"], "goal": "TRIFF DEN HIMMELSFUCHS!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "lepora_heart", "steps": [
				S._say("fox", "Getroffen. Mitten in die Wahrheit. Also gut: Dein Pfeil steckt nicht im Mond. Er steckt in einem Baum. Und der Baum steht nicht auf dieser Welt."),
			], "else": [
				S._say("fox", "Getroffen, aber am Rand. Halbe Wahrheit, halber Treffer: Der Pfeil ist nicht im Mond. Den Rest musst du selbst finden."),
			]},
			S._say("hero", "Ein Baum, der nicht auf dieser Welt steht? Das ist doch wieder gelogen."),
			S._say("fox", "Vielleicht. Vielleicht meinte ich: nicht in der Welt, in der du suchst. Füchse sind ungenau, wenn es um Wahrheit geht."),
			S._say("hero", "Wo dann?"),
			S._say("fox", "Frag den Engel, der alles Bewegte zählt. Er weiß, wo jeder Pfeil gelandet ist. Er fragt aber zurück."),
		]},
		{"id": "lepora_3", "title": "Was willst du treffen?", "arena": "heaven_spheres", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["virtus", 3.0, -1], ["fox", -4.0, 1], ["mossback", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Was willst du treffen?"},
			S._narr("Lepora steigt die Sphären hinauf, bis der Mond unter ihr liegt wie ein Teich. Dort zählt ein Engel alles, was sich bewegt."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("virtus", "Elftausend Pfeile hast du verschossen, Jägerin. Zehntausendneunhundertneunundneunzig haben getroffen. Einer nicht. Absichtlich."),
			S._say("virtus", "Was willst du treffen? Und was hast du Angst zu treffen?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Ich … wenn ich den Pfeil finde, ist die Suche vorbei. Dann muss ich wissen, warum sie gegangen ist."),
			S._say("virtus", "Du verfehlst, weil Treffen bedeutet, dass die Jagd vorbei ist. Ich zeige dir, wo er steckt. Aber erst zeigst du mir, dass du treffen WILLST."),
			S._music("boss"),
			{"t": "branch", "flag": "lepora_heart", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("fox", "Die Wahrheit war ein Treffer wert. Jetzt bin ich neugierig, wie die Geschichte ausgeht. Ich kämpfe mit!"),
				{"t": "fight", "cast": ["hero", "fox", "virtus"], "goal": "TRIFF, WAS DU TREFFEN WILLST!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("mossback", "Der Wald schickt mich. Er will seine Jägerin zurück. Ganz."),
				{"t": "fight", "cast": ["hero", "mossback", "virtus"], "goal": "TRIFF, WAS DU TREFFEN WILLST!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._say("virtus", "Getroffen. Der Pfeil steckt in einer alten Eiche, mitten im Wald, aus dem du kommst. Er war nie weit weg."),
		]},
		{"id": "lepora_4", "title": "Der Baum der Mutter", "arena": "mystic_grove", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["zielt", 2.0, -1], ["mossback", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der Baum der Mutter"},
			S._narr("Die alte Eiche steht hinter dem Haus, in dem sie aufwuchs. Lepora ist tausendmal an ihr vorbeigelaufen. Sie hat nie nach oben geschaut."),
			S._cam("two", 0, 1.6, 2),
			S._say("mossback", "Klettere hinauf, Jägerin. Oder schieß. Aber hör auf, vorbeizugehen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("zielt", "Geh weiter. Wie immer. Solange du nicht nachsiehst, ist sie vielleicht nur kurz weg. Solange du verfehlst, kommt sie vielleicht wieder."),
			S._say("hero", "Seit siebzehn Jahren verfehle ich. Sie ist nicht wiedergekommen."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "zielt"], "goal": "BESIEGE DIE VERFEHLENDE!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 1.8),
			S._narr("Lepora klettert. Oben, mitten im Stamm, steckt ein kleiner krummer Pfeil – im Herzen einer Schnitzerei, die sie nie gesehen hat."),
			S._narr("Eine Frau mit Bogen. Lachend. Darunter, in die Rinde geritzt: Ich musste gehen, um dich zu schützen. Triff immer, was du liebst."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Sie hat mich nicht verlassen. Sie hat mir eine Nachricht geschnitzt – und ich habe siebzehn Jahre nicht hochgeschaut."),
			S._cam("two", 0, 1.6, 2),
			S._say("mossback", "Was wirst du jetzt jagen, wenn die Suche vorbei ist?"),
			S._say("hero", "Sie. Sie lebt irgendwo. Und diesmal treffe ich."),
			S._say("mossback", "Und wenn du sie findest – was sagst du ihr?"),
			S._say("hero", "Dass ich die Nachricht gelesen habe. Spät. Aber ich habe sie gelesen."),
			S._narr("In der nächsten Vollmondnacht spannt Lepora den kleinen krummen Pfeil auf. Sie zielt nicht. Sie lässt einfach los."),
			S._narr("Er fliegt schief, wie immer. Nach Osten, über die Berge. Lepora schultert den Bogen und folgt ihm."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Lepora · Der erste Pfeil"},
			S._narr("Relikt erhalten: Der Pfeil aus Mondholz  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
