extends RefCounted
## Legende: SERAPHINE, KAPITÄNIN DER SALZKRÄHE – „Das Lied des Meeres“.
## Seraphine eroberte die Salzkrähe mit einem Messer und einem Lied – einem Lied, das sie dem Meer
## gestohlen hat. Tobi wirft ihr vor, seine Leute im Sturm nicht gerettet zu haben, Leviathan will
## das Lied zurück, und am Ende muss sie an Land gehen, zum ersten Mal seit zwanzig Jahren.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Das Lied des Meeres",
	"summary": "Seraphine eroberte die Salzkrähe mit einem Messer und einem Lied, das sie dem Meer gestohlen hat. Seitdem gehorcht ihr jede Welle. Nur an Land hat sie nie gelernt zu leben.",
	"relic": "Die Sanduhr mit Strandsand",
	"relic_text": "Eine kleine Sanduhr, gefüllt mit dem ersten Sand, den Seraphine nach zwanzig Jahren unter den Füßen hatte. Sie läuft langsamer als jede andere.",
}

const CAST := {
	"hero": {"preset": "pirate_captain", "name": "SERAPHINE", "title": "Kapitänin der Salzkrähe", "color": "0ea5e9"},
	"tobi": {"preset": "tobi", "name": "TOBI", "title": "Der Federfaust-Raufbold", "color": "ef4444"},
	"maat": {"preset": "warrok_brute", "name": "BOOTSMANN KNUD", "title": "Ihr ältester Matrose", "color": "a16207"},
	"marine": {"preset": "steel_knight", "name": "ADMIRAL EISENHAND", "title": "Flotte des Königs", "color": "94a3b8"},
	"marine2": {"preset": "vanguard_soldier", "name": "MARINESOLDAT", "title": "Flotte des Königs", "color": "94a3b8"},
	"leviathan": {"boss": "leviathan", "name": "LEVIATHAN", "title": "Das Meer selbst", "color": "0ea5e9"},
	"meer": {"preset": "pirate_captain", "name": "DIE SALZKRÄHE", "title": "Seraphine, die nie an Land geht", "color": "164e63"},
}

static func chapters() -> Array:
	return [
		{"id": "pirate_captain_1", "title": "Klar Schiff", "arena": "pirate_galleon", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["marine", 2.8, -1], ["marine2", 4.0, -1], ["maat", -3.5, 1]]),
			S._music("fight"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "SERAPHINE · DAS LIED DES MEERES", "sub": "Kapitel I – Klar Schiff"},
			S._narr("Vor zwanzig Jahren kletterte ein Mädchen mit einem Messer zwischen den Zähnen an Bord der Salzkrähe. Sie sang ein Lied. Die See wurde still. Die Mannschaft legte die Waffen nieder."),
			S._narr("Niemand weiß, woher Seraphine das Lied hat. Nur sie. Sie hat es dem Meer gestohlen, in einer Nacht, als es schlief."),
			S._cam("two", 0, 1.4, 1),
			S._say("marine", "Seraphine! Im Namen des Königs: Die Salzkrähe ist beschlagnahmt. Ergib dich, oder wir versenken dich."),
			S._say("hero", "Klar Schiff, Jungs! Wer an Bord kommt, tanzt nach meinem Lied!"),
			S._say("maat", "Kapitänin, die haben drei Fregatten! Wir sind allein!"),
			S._say("hero", "Wir sind nie allein, Knud. Wir haben das Meer."),
			{"t": "qte", "kind": "sequence", "keys": ["special", "standard", "special"], "time": 1.0, "text": "DAS LIED!", "flag": "pirate_captain_song",
				"success": [S._narr("Seraphine singt. Eine Welle hebt sich und wirft die Fregatten zurück wie Spielzeug.")],
				"fail": [S._narr("Sie verpasst einen Ton. Das Meer zögert, als hätte es sich verhört.")]},
			{"t": "fight", "cast": ["hero", "marine", "marine2"], "goal": "VERTEIDIGE DIE SALZKRÄHE!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "pirate_captain_song", "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.6, 3),
			S._say("maat", "Kapitänin. Das Meer hat sich komisch angefühlt. Wie ein Hund, der beißen will und es noch nicht tut."),
			S._say("hero", "Unsinn. Das Meer gehorcht mir. Seit zwanzig Jahren."),
			S._say("maat", "Seit zwanzig Jahren warst du nicht an Land. Nicht einmal im Hafen. Warum eigentlich?"),
			S._cam("close", 0, 1.4),
			S._say("hero", "Weil das Land mir nie etwas gegeben hat, Knud. Außer einem Waisenhaus und einem Messer."),
			S._narr("Unten im Kielraum knarrt das Holz. Es klingt, als würde jemand das Lied summen. Falsch. Und sehr, sehr tief."),
		]},
		{"id": "pirate_captain_2", "title": "Der Junge aus dem Sturm", "arena": "bg_storm_roof", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["tobi", 2.5, -1], ["maat", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Junge aus dem Sturm"},
			S._narr("Ein Hafenstädtchen im Sturm. Seraphine bleibt an Bord, wie immer. Doch auf dem Dach der Hafenmeisterei wartet jemand mit Fäusten wie Federn."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("tobi", "Seraphine! Vor fünf Jahren, im großen Sturm. Das Fischerboot meines Vaters. Du warst da. Du hast gesungen – und die Wellen haben DICH durchgelassen. Uns nicht."),
			S._say("hero", "Ich erinnere mich an keinen Fischkutter."),
			S._say("tobi", "Du hast meine Leute nicht gerettet, Piratin. Du hast nur zugesehen."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 0.8),
			{"t": "choice", "text": "Was antwortet Seraphine?", "options": [
				{"label": "Die Wahrheit", "flag": "pirate_captain_truth", "steps": [
					S._say("hero", "Ich habe sie gesehen. Ich habe gesungen, so laut ich konnte. Das Lied hat nur das Schiff geschützt, auf dem ich stand. Es schützt nie mehr."),
					S._say("tobi", "Dann ist es ein schlechtes Lied. Ich prügele trotzdem auf dich ein, damit es mir besser geht. Okay?"),
					S._say("hero", "Okay. Das ist fair.")]},
				{"label": "Abwehren", "flag": "pirate_captain_proud", "steps": [
					S._say("hero", "Das Meer nimmt, wen es will. Ich bin nicht sein Kindermädchen."),
					S._say("tobi", "Falsch. Du bist seine Kapitänin. Das hast du selbst gesagt.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "tobi"], "goal": "STELL DICH DEM FEDERFAUST-JUNGEN!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "pirate_captain_truth", "steps": [
				S._say("tobi", "Geht mir nicht besser. Aber du hast mich nicht angelogen. Das ist mehr, als ich erwartet habe."),
				S._say("hero", "Wie hieß dein Vater?"),
				S._say("tobi", "Jonte. Er hat immer gesagt, das Meer singt nur für die, die ihm zuhören. Nicht für die, die es beherrschen."),
			], "else": [
				S._say("tobi", "Du kämpfst wie das Meer. Du hörst nie zu. Irgendwann kommt eine Welle, die zurückschlägt."),
			]},
			{"t": "fx", "kind": "shake"},
			S._narr("Draußen im Hafen hebt sich das Wasser. Höher als jede Welle. Ein Kopf, so groß wie die Salzkrähe, steigt aus der Tiefe."),
			S._say("maat", "KAPITÄNIN! DAS MEER! DAS MEER STEHT AUF!"),
		]},
		{"id": "pirate_captain_3", "title": "Das gestohlene Lied", "arena": "pirate_galleon", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["leviathan", 3.0, -1], ["tobi", -4.0, 1], ["maat", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das gestohlene Lied"},
			S._narr("Die Salzkrähe tanzt auf einer Welle, die nicht fällt. Vor ihr: Leviathan. Das Meer in Gestalt. Es hat zwanzig Jahre geschlafen. Jetzt ist es wach."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("leviathan", "Diebin. Du hast mir mein Lied genommen, als ich schlief. Mit meiner eigenen Stimme hast du mich zum Hund gemacht."),
			S._say("leviathan", "Gib es zurück. Oder ich nehme dein Schiff, deine Mannschaft und alles, was je auf dir geschwommen ist."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ohne das Lied bin ich nichts. Ein Mädchen aus dem Waisenhaus mit einem Messer."),
			S._say("leviathan", "Ohne Schiff bist du nur eine Frau mit nassen Stiefeln. Ja. Und?"),
			S._say("hero", "Und … ich habe gesungen, damit mich nie wieder jemand wegschickt. Aber du hast recht. Es gehört nicht mir."),
			S._say("maat", "Kapitänin! Wir sind bei dir! Mit Lied oder ohne!"),
			S._music("boss"),
			{"t": "branch", "flag": "pirate_captain_truth", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("tobi", "Mein Vater hat gesagt, man soll dem Meer zuhören. Heute hört es mal uns zu! Gum-Faust voraus!"),
				{"t": "fight", "cast": ["hero", "tobi", "leviathan"], "goal": "BESTEHE VOR DEM MEER!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "fight", "cast": ["hero", "maat", "leviathan"], "goal": "BESTEHE VOR DEM MEER!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Seraphine singt ein letztes Mal. Dann öffnet sie die Hand, und das Lied fliegt wie ein Möwenschwarm zurück ins Wasser."),
			S._say("leviathan", "Du hast es freiwillig gegeben. Das hat noch kein Mensch getan. Ich lasse dein Schiff schwimmen. Aber es wird nie wieder gehorchen. Nur mitfahren."),
		]},
		{"id": "pirate_captain_4", "title": "Nasse Stiefel", "arena": "bg_sunset_stadium", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["meer", 2.0, -1], ["maat", -3.5, 1], ["tobi", 4.5, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Nasse Stiefel"},
			S._narr("Ein Hafen bei Sonnenuntergang. Die Salzkrähe liegt am Steg. Seraphine steht an der Reling. Zwischen ihr und dem Land: eine einzige Planke."),
			S._cam("two", 0, 1.6, 2),
			S._say("maat", "Es ist nur Holz, Kapitänin. Ein Schritt. Ich halte dich, wenn du wackelst."),
			S._say("hero", "Ich wackle nicht. Ich … ich habe vergessen, wie man an Land geht."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("meer", "Bleib an Bord. Hier bist du Kapitänin. Da drüben bist du ein Waisenkind, das keiner wollte."),
			S._say("hero", "Ich war zwanzig Jahre Kapitänin, weil ich Angst hatte, wieder das Kind zu sein. Die Angst hat gut gesegelt. Aber sie ist nie angekommen."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "meer"], "goal": "GEH VON BORD!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 1.8),
			S._narr("Seraphine geht über die Planke. Ihr erster Schritt auf Land seit zwanzig Jahren. Der Boden schwankt nicht. Sie schon."),
			S._narr("Der Sand ist warm. Er rinnt ihr in die Stiefel. Sie zieht sie aus und lacht."),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("tobi", "Na? Wie fühlt sich das Land an?"),
			S._say("hero", "Seltsam. Still. Es bewegt sich nicht. Man muss sich selbst bewegen."),
			S._say("tobi", "Mein Vater hatte eine Hütte hier. Sie steht leer. Er hätte gewollt, dass jemand drin wohnt, der das Meer versteht."),
			S._say("hero", "Ich verstehe es nicht. Ich habe es nur beherrscht. Aber ich kann lernen, zuzuhören."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Seraphine · Das Lied des Meeres"},
			S._narr("Relikt erhalten: Die Sanduhr mit Strandsand  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
