extends RefCounted
## Legende: PYRUS, DER FEUERMAGIER – „Die letzte Seite“.
## Pyrus lernte Feuer, weil ihm als Kind immer kalt war. Er verbrennt jedes Buch, das er gelesen hat,
## damit ihn niemand übertrifft. Scarlet, deren Tagebücher er verbrannte, will ihre Erinnerungen
## zurück; Baphomet bietet Feuer, das nie verlischt und nie wärmt; und am Ende muss Pyrus teilen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die letzte Seite",
	"summary": "Pyrus verbrennt jedes Buch, das er gelesen hat – damit niemand ihn je übertrifft. Ihm ist nie wieder kalt geworden. Aber warm war ihm auch nie.",
	"relic": "Das Buch mit der leeren Seite",
	"relic_text": "Ein kleines, abgegriffenes Notizbuch. Jede Seite ist beschrieben – in vielen Handschriften. Nur die letzte ist leer, damit der Nächste weiterschreiben kann.",
}

const CAST := {
	"hero": {"preset": "wizard_sorcerer", "name": "PYRUS", "title": "Der Feuermagier", "color": "f97316"},
	"scarlet": {"preset": "phoenix", "name": "SCARLET", "title": "Deren Bücher er verbrannte", "color": "f43f5e"},
	"nils": {"preset": "zip", "name": "NILS", "title": "Lehrling wider Willen", "color": "fde68a"},
	"rival": {"preset": "sorceress_medea", "name": "ERZMAGIERIN MEDEA", "title": "Die mit den elftausend Büchern", "color": "a78bfa"},
	"golem": {"preset": "golem", "name": "SCHMIEDEGOLEM", "title": "Bewacht die Akademie", "color": "fb923c"},
	"baphomet": {"boss": "baphomet", "name": "BAPHOMET", "title": "Herr des Flammenkreises", "color": "ff3b30"},
	"kalt": {"preset": "wizard_sorcerer", "name": "DER FRIERENDE JUNGE", "title": "Pyrus, mit sieben Jahren", "color": "bae6fd"},
}

static func chapters() -> Array:
	return [
		{"id": "wizard_sorcerer_1", "title": "Meteor", "arena": "volcano_sanctum", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["golem", 3.0, -1], ["nils", -3.5, 1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "PYRUS · DIE LETZTE SEITE", "sub": "Kapitel I – Meteor"},
			S._narr("Als Pyrus sieben war, erfror sein kleiner Bruder in einem Winter ohne Holz. Pyrus überlebte. Er schwor, dass ihm nie wieder kalt werden würde."),
			S._narr("Er lernte Feuer. Dann mehr Feuer. Dann Meteore. Jedes Buch, das er las, verbrannte er danach. Damit niemand dasselbe lernen konnte. Damit niemand besser wurde als er."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Ein Meteor ist nur eine Idee, die schnell genug fällt. Und meine Ideen fallen sehr schnell."),
			S._cam("two", 0, 1.4, 1),
			S._say("golem", "DIE AKADEMIE SCHÜTZT IHRE BIBLIOTHEK. DU HAST DREI REGALE VERBRANNT. HALT."),
			S._say("hero", "Ich habe sie gelesen. Danach brauchte sie niemand mehr."),
			S._say("golem", "ANDERE WOLLEN AUCH LESEN."),
			S._say("hero", "Andere sollen sich ihr eigenes Feuer suchen."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "METEORSCHAUER!", "flag": "wizard_sorcerer_meteor",
				"success": [S._narr("Der Himmel über dem Vulkan öffnet sich. Drei glühende Steine schlagen um den Golem ein.")],
				"fail": [S._narr("Die Meteore verglühen zu früh. Pyrus flucht – er hat sich verrechnet. Das passiert ihm nie.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "golem"], "goal": "BEZWINGE DEN SCHMIEDEGOLEM!", "lives": [3, 2], "qte": "wizard_sorcerer_meteor", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("nils", "Meister Pyrus! Die Akademie hat mich geschickt. Ich soll Ihr Lehrling sein. Strafe für Sie, haben sie gesagt. Strafe für mich auch, glaube ich."),
			S._say("hero", "Ich nehme keine Lehrlinge. Lehrlinge lernen, was man weiß. Und dann sind sie besser."),
			S._say("nils", "Ich bin nicht besonders gut. Wirklich nicht. Ich habe zwei Jahre gebraucht, um eine Kerze anzuzünden."),
			S._cam("close", 0, 1.4),
			S._narr("Pyrus mustert den Jungen. Dünn. Frierend. Die Hände in den Ärmeln. Er sieht weg. Sehr schnell."),
			S._say("hero", "Du kannst Holz tragen. Mehr nicht."),
		]},
		{"id": "wizard_sorcerer_2", "title": "Seite zwölf", "arena": "bg_foundry", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["scarlet", 2.5, -1], ["nils", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Seite zwölf"},
			S._narr("In der alten Gießerei, die früher eine Bibliothek war, wartet eine Frau mit Federn aus Glut. Pyrus erkennt sie. Er hat ihre Tagebücher verbrannt."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("scarlet", "Magier. Du hast meine Erinnerungen verbrannt. Neun Leben stand in diesen Büchern. Ich weiß nicht einmal mehr meinen ersten Namen."),
			S._say("hero", "Ich verbrenne alles, was ich gelesen habe. Persönlich war es nicht."),
			S._say("scarlet", "Für mich schon."),
			S._say("nils", "Meister … Sie haben das Tagebuch eines Menschen verbrannt? Nicht nur Zauberbücher?"),
			{"t": "choice", "text": "Was tut Pyrus?", "options": [
				{"label": "Sich erinnern", "flag": "wizard_sorcerer_recall", "steps": [
					S._narr("Pyrus schließt die Augen. Er hat ein perfektes Gedächtnis. Er hat es nie benutzt, um etwas zurückzugeben."),
					S._say("hero", "Seite zwölf: »Ich kämpfe, damit Hikaru nie allein ist.« Seite dreißig: »Ich hieß Lina.« Ich … ich habe mir alles gemerkt."),
					S._say("scarlet", "Lina … Erzähl weiter. Nein – erst kämpfen. Sonst glaube ich dir nicht.")]},
				{"label": "Abweisen", "flag": "wizard_sorcerer_refuse", "steps": [
					S._say("hero", "Was verbrannt ist, ist verbrannt. Such dir neue Erinnerungen."),
					S._say("scarlet", "Dann verbrenne ich jetzt etwas von dir.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "scarlet"], "goal": "FEUER GEGEN FEUER!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "wizard_sorcerer_recall", "steps": [
				S._say("scarlet", "Du hast dir jedes Wort gemerkt. Warum? Du hättest sie einfach vergessen können."),
				S._say("hero", "Weil sie gut geschrieben waren. Besser als meine Zauberbücher. Ich … wollte nicht, dass sie ganz weg sind."),
			], "else": [
				S._say("scarlet", "Du kämpfst, als hättest du Angst, dass dir jemand etwas wegnimmt. Dabei bist du derjenige, der nimmt."),
			]},
			S._say("nils", "Meister? Mir ist kalt. Der Boden – er wird heiß und trotzdem ist mir kalt."),
			{"t": "fx", "kind": "shake"},
			S._narr("Unter der Gießerei öffnet sich ein Ring aus Flammen. Er riecht nach Schwefel. Und er ruft Pyrus beim Vornamen, den niemand mehr kennt."),
		]},
		{"id": "wizard_sorcerer_3", "title": "Feuer, das nicht wärmt", "arena": "hell_flames", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["baphomet", 3.0, -1], ["nils", -4.0, 1], ["scarlet", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Feuer, das nicht wärmt"},
			S._narr("Der Flammenkreis der Hölle. Hier brennt alles seit dem Anfang der Zeit. Und trotzdem ist es hier so kalt wie im Winter, in dem sein Bruder starb."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("baphomet", "Feuermagier. Ich biete dir Feuer, das nie verlischt. Ewige Flammen. Nie wieder frieren. Nie wieder ein Winter ohne Holz."),
			S._say("baphomet", "Der Preis? Du teilst es mit niemandem. Niemals. Aber das tust du ja ohnehin nicht."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Nie wieder frieren … Warum ist es dann hier so kalt?"),
			S._say("baphomet", "Weil Feuer, das man nicht teilt, nicht wärmt. Das wusstest du nicht? Dein ganzes Leben lang hast du allein vor dem Kamin gesessen."),
			S._say("hero", "Mein Bruder und ich hatten nur eine Decke. Wir haben sie geteilt. Ihm wurde trotzdem kalt. Ich dachte, Teilen reicht nicht."),
			S._say("hero", "Aber es war das Letzte, was mich gewärmt hat."),
			S._music("boss"),
			{"t": "branch", "flag": "wizard_sorcerer_recall", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("scarlet", "Du hast mir Seite dreißig zurückgegeben. Ich schulde dir ein Kapitel. Lass uns zusammen brennen – richtig."),
				{"t": "fight", "cast": ["hero", "scarlet", "baphomet"], "goal": "LÖSCHE DAS FEUER, DAS NICHT WÄRMT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("nils", "Meister! Ich habe eine Kerze angezündet! Ganz allein! Sie ist winzig, aber sie wärmt – fühlen Sie mal!"),
				{"t": "fight", "cast": ["hero", "nils", "baphomet"], "goal": "LÖSCHE DAS FEUER, DAS NICHT WÄRMT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Der Flammenkreis erlischt. Nur eine kleine Flamme bleibt übrig, zwischen Pyrus und dem, der neben ihm steht. Sie ist winzig. Und sie wärmt beide."),
		]},
		{"id": "wizard_sorcerer_4", "title": "Die letzte Seite", "arena": "bg_aurora_peaks", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["kalt", 2.0, -1], ["nils", -3.5, 1], ["rival", 4.5, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Die letzte Seite"},
			S._narr("Ein Winterabend unter dem Polarlicht. Es schneit. Pyrus sitzt an einem kleinen Feuer und friert. Zum ersten Mal seit vierzig Jahren erlaubt er es sich."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("kalt", "Mir ist kalt. Mir ist so kalt. Mach das Feuer größer. Größer! Verbrenn alles, damit es nie wieder kalt wird!"),
			S._say("hero", "Ich habe alles verbrannt. Es wurde nie warm. Wir haben die falschen Dinge verbrannt, kleiner Pyrus."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "kalt"], "goal": "WÄRME DEN FRIERENDEN JUNGEN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._narr("Pyrus zieht seinen Mantel aus und legt ihn Nils um die Schultern. Dann holt er ein leeres Buch aus der Tasche."),
			S._say("hero", "Ich habe vierzig Jahre lang Bücher verbrannt. Jetzt schreibe ich alles auf, was ich weiß. Alles. Für dich."),
			S._say("nils", "Und wenn ich dann besser werde als Sie?"),
			S._say("hero", "Dann hat das Buch seinen Zweck erfüllt."),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("rival", "Pyrus. Ich habe gehört, du schreibst ein Buch. Statt eines zu verbrennen. Meine Bibliothek ist offen. Für deins ist noch ein Platz frei."),
			S._say("hero", "Medea. Danke. Aber erst lernt der Junge, wie man eine Kerze für jemand anderen anzündet."),
			S._narr("Das Buch füllt sich in einem Jahr. Die letzte Seite lässt Pyrus leer. Für den, der nach Nils kommt."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Pyrus · Die letzte Seite"},
			S._narr("Relikt erhalten: Das Buch mit der leeren Seite  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
