extends RefCounted
## Legende: GLACIEM, DIE FROSTASSASSINE – „Das gefrorene Herz“.
## Vor hundert Jahren fror Glaciem ihr Herz ein, um eine Lawine über ihrem Dorf zu halten.
## Die Lawine hängt noch immer am Berg – und taut, wenn Glaciem fühlt. Der Frostwyrm, der sie
## einst gelehrt hat, will sie heimholen; Leviathan zeigt ihr alle Wärme, die sie nie haben wird.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Das gefrorene Herz",
	"summary": "Glaciem hält seit hundert Jahren eine Lawine über ihrem Dorf – mit einem Herzen aus Eis. Jedes Gefühl lässt den Schnee rutschen. Also fühlt sie nichts.",
	"relic": "Die Schneeflocke im Glas",
	"relic_text": "Eine einzige Schneeflocke in einem kleinen Glas. Sie schmilzt nie – aber wenn man das Glas hält, beschlägt es von innen.",
}

const CAST := {
	"hero": {"preset": "glaciem", "name": "GLACIEM", "title": "Die Frostassassine", "color": "7dd3fc"},
	"wyrm": {"preset": "frostwyrm", "name": "FROSTWYRM", "title": "Der Winter, der sie lehrte", "color": "38bdf8"},
	"mira": {"preset": "lepora", "name": "MIRA", "title": "Das Mädchen aus dem Dorf", "color": "fde68a"},
	"thief": {"preset": "shira", "name": "EISDIEBIN", "title": "Will den Gipfelkristall", "color": "c084fc"},
	"leviathan": {"boss": "leviathan", "name": "LEVIATHAN", "title": "Der Neid", "color": "0ea5e9"},
	"eis": {"preset": "glaciem", "name": "DAS EISHERZ", "title": "Was sie vor hundert Jahren wurde", "color": "e0f2fe"},
}

static func chapters() -> Array:
	return [
		{"id": "glaciem_1", "title": "Die Lawine, die nicht fällt", "arena": "frozen_summit", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["thief", 3.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "GLACIEM · DAS GEFRORENE HERZ", "sub": "Kapitel I – Die Lawine, die nicht fällt"},
			S._narr("Über dem Dorf Weißbach hängt seit hundert Jahren eine Lawine. Sie fällt nicht. Sie wartet. Und auf dem Gipfel darüber steht eine Frau, die nie blinzelt."),
			S._narr("Glaciem hat ihr Herz gefroren, als der Schnee zu rutschen begann. Seither hält ihr Eis den Berg. Solange sie nichts fühlt, bleibt der Schnee oben."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Hundert Jahre. Dreiundsechzig Hochzeiten im Tal. Einundneunzig Beerdigungen. Ich habe keine davon gespürt."),
			{"t": "appear", "who": 1},
			{"t": "move", "who": 1, "x": 2.5, "time": 0.8},
			S._cam("two", 0, 1.4, 1),
			S._say("thief", "Der Gipfelkristall! Damit hält man den Berg? Die Händler in der Neonstadt zahlen ein Vermögen für so ein Ding."),
			S._say("hero", "Nimm ihn, und die Lawine fällt. Zweihundert Menschen schlafen darunter."),
			S._say("thief", "Zweihundert Fremde. Ich kenne keinen davon."),
			S._say("hero", "Ich auch nicht. Das ist nicht der Punkt."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "EISSPLITTER!", "flag": "glaciem_shard",
				"success": [S._narr("Ein Splitter nagelt den Ärmel der Diebin an den Fels. Sie faucht.")],
				"fail": [S._narr("Der Splitter verfehlt. Die Diebin grinst und zieht ihre Klinge.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "thief"], "goal": "SCHÜTZE DEN GIPFELKRISTALL!", "lives": [3, 2], "qte": "glaciem_shard", "ai": 3},
			S._music("calm"),
			S._cam("close", 0, 1.4),
			S._narr("Die Diebin flieht den Hang hinab. Glaciem sieht ihr nach – und spürt etwas. Ganz leise. Ärger vielleicht."),
			{"t": "fx", "kind": "shake"},
			S._narr("Oben am Berg knackt es. Ein Brocken Schnee löst sich und rollt ins Tal. Nur ein kleiner. Diesmal."),
			S._say("hero", "Nicht fühlen. Nicht fühlen. Nicht fühlen."),
		]},
		{"id": "glaciem_2", "title": "Das Mädchen mit dem Tee", "arena": "bg_aurora_peaks", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["mira", -0.2, 1], ["wyrm", 3.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("hope"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Das Mädchen mit dem Tee"},
			S._narr("Seit dem Schneebrocken kommt jeden Morgen jemand den Berg herauf: Mira, zwölf Jahre alt, mit einer Kanne heißem Tee, der auf dem Weg kalt wird."),
			S._cam("two", 0, 1.6, 1),
			S._say("mira", "Meine Oma sagt, du hältst den Berg. Sie sagt, du warst ihre große Schwester. Stimmt das?"),
			S._say("hero", "Ich erinnere mich nicht. Erinnern ist ein Gefühl."),
			S._say("mira", "Dann erinnere ich mich für dich. Oma sagt, du hast immer falsch gesungen und laut gelacht."),
			{"t": "fx", "kind": "shake"},
			S._narr("Der Berg knackt wieder. Glaciem dreht sich weg, bevor das Mädchen ihr Gesicht sieht."),
			{"t": "appear", "who": 2},
			S._cam("sky", 2, 2.0),
			S._pose(2, "Roar", 1.0),
			S._say("wyrm", "Kleine Klinge. Du taust. Ich rieche es bis in mein Eisgrab. Komm nach Hause, in den Winter, der dich geboren hat."),
			S._say("hero", "Du hast mich gelehrt, mein Herz zu frieren, Wyrm. Du hast nicht gesagt, wie lange es dauert."),
			S._say("wyrm", "Für immer. So war der Handel. Das Kind lenkt dich ab. Schick es fort."),
			{"t": "choice", "text": "Was tut Glaciem?", "options": [
				{"label": "Mira wegschicken", "flag": "glaciem_alone", "steps": [
					S._say("hero", "Geh, Mira. Komm nicht wieder. Es ist sicherer für alle."),
					S._say("mira", "Du lügst. Oma sagt, du hast auch früher immer gelogen, wenn du Angst hattest.")]},
				{"label": "Mira bleiben lassen", "flag": "glaciem_tea", "steps": [
					S._say("hero", "Sie bleibt. Sie bringt jeden Morgen Tee. Der Tee ist kalt, aber sie bringt ihn."),
					S._say("wyrm", "Dann zeige ich dir, was Wärme dich kostet.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "wyrm"], "goal": "STELL DICH DEM WINTER!", "lives": [2, 2], "ai": 4},
			S._music("tense"),
			S._cam("two", 0, 1.4, 2),
			S._say("wyrm", "Du kämpfst wie damals, als du jung warst. Mit Wut. Ich dachte, die hätte ich dir abgewöhnt."),
			S._narr("Der Wyrm gleitet zurück ins Eis. Unter ihm öffnet sich ein Spalt, tief und dunkel und voller Wasser."),
			S._narr("Aus dem Spalt ruft eine Stimme, die wie das Meer klingt."),
		]},
		{"id": "glaciem_3", "title": "Die warmen Fenster", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["leviathan", 3.0, -1], ["mira", -4.0, 1], ["wyrm", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die warmen Fenster"},
			S._narr("Im gefrorenen See am Grund der Hölle stehen Fenster im Eis. In jedem Fenster ein warmes Zimmer. In jedem Zimmer Menschen, die sich halten."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("leviathan", "Sieh sie dir an, Eisfrau. Die Hochzeiten, die du verpasst hast. Die Kinder, die du nie hattest. Das alles hätte deins sein können."),
			S._say("leviathan", "Bleib hier unten bei mir. Hier ist alles Eis. Hier bist du nicht die Einzige, die friert."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Ich … ich will das alles nicht sehen."),
			S._say("leviathan", "Doch. Du willst. Darum taust du ja. Neid ist auch ein Gefühl, Glaciem."),
			S._say("hero", "Dann fühle ich eben. Und ich fühle, dass ich dich nicht mag."),
			S._music("boss"),
			{"t": "branch", "flag": "glaciem_tea", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("mira", "Ich bin dem Spalt nachgeklettert! Der Tee ist diesmal heiß – ich hab ihn in meine Jacke gewickelt!"),
				{"t": "fight", "cast": ["hero", "mira", "leviathan"], "goal": "ZERSCHLAGE DIE FENSTER DES NEIDS!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("wyrm", "Niemand außer mir darf meine Schülerin brechen. Nicht einmal der Neid."),
				{"t": "fight", "cast": ["hero", "wyrm", "leviathan"], "goal": "ZERSCHLAGE DIE FENSTER DES NEIDS!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Die Fenster zerspringen. Dahinter ist nichts. Nur Eis. Die Wärme war nie hier unten."),
			S._say("hero", "Sie ist oben. Im Tal. Bei den Leuten, die ich halte. Ich muss zurück."),
		]},
		{"id": "glaciem_4", "title": "Tauwetter", "arena": "frozen_summit", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["eis", 2.0, -1], ["mira", -3.5, 1], ["wyrm", 4.5, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Tauwetter"},
			S._narr("Zurück auf dem Gipfel. Der Berg knackt ununterbrochen. Glaciem fühlt zu viel auf einmal, und der Schnee weiß es."),
			S._cam("two", 0, 1.6, 2),
			S._say("mira", "Wenn du auftaust, fällt die Lawine. Oma hat es mir erzählt. Darum hast du es gemacht."),
			S._say("hero", "Ja. Und jetzt weiß ich nicht mehr, wie man aufhört zu fühlen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("eis", "Ich weiß es. Ich bin du – vor hundert Jahren. Gib mir dein Herz zurück, und alles ist wieder still."),
			S._say("hero", "Still war es. Sicher auch. Aber Mira hätte mich nie gefunden, wenn ich still geblieben wäre."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "eis"], "goal": "BESIEGE DAS EISHERZ!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("tense"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "shake"},
			S._narr("Das Eisherz zerspringt – und die Lawine fällt. Hundert Jahre Schnee donnern auf Weißbach zu."),
			{"t": "qte", "kind": "mash", "keys": ["special"], "count": 10, "time": 3.0, "text": "HALTE DEN BERG!", "flag": "glaciem_held",
				"success": [S._narr("Glaciem reißt beide Arme hoch. Eiswände schießen aus dem Hang und fangen die Lawine – nicht mit einem gefrorenen Herzen, sondern mit Wut und Angst und Liebe.")],
				"fail": [S._narr("Glaciem wankt. Doch dann ist der Wyrm da, legt seinen Leib vor das Dorf, und die Lawine bricht an seinen Schuppen.")]},
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("wyrm", "Mit warmem Herzen. Das hätte ich dir nie beigebracht. Du hast es trotzdem gelernt."),
			S._music("hope"),
			S._cam("close", 0, 1.6),
			S._narr("Eine Träne rinnt über Glaciems Wange. Sie gefriert nicht. Es tut weh, und es ist gut."),
			S._say("mira", "Komm runter ins Dorf. Oma wartet. Sie sagt, du singst immer noch falsch."),
			S._say("hero", "Dann wird es Zeit, dass ich es wieder übe."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Glaciem · Das gefrorene Herz"},
			S._narr("Relikt erhalten: Die Schneeflocke im Glas  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
