extends RefCounted
## Legende: BRUNO, DER UNBESIEGTE – „Hunger“.
## Mit zehn schlug er einen Meteor zurück in den Himmel. Seitdem hat er nie verloren – und nie wieder
## etwas gespürt. Ein Kind mit Spielkarten, ein Rivale mit zwölf Jahren Training und ein Veranstalter mit
## einem Geheimnis im Keller. Eine Komödie über einen Mann, der lernen will, wie man verliert.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Hunger",
	"summary": "Neunhundertzweiundachtzig Siege, jeder mit einem Schlag – und Bruno spürt dabei gar nichts. Bis ein Kind gegen ihn wettet und ein alter Rivale ihn endlich zurückschlägt.",
	"relic": "Milas Joker",
	"relic_text": "Eine abgegriffene Spielkarte. Der Joker grinst, weil er weiß: Man kann verlieren und trotzdem glücklich sein.",
}

const CAST := {
	"hero": {"preset": "bruno", "name": "BRUNO", "title": "Der Unbesiegte", "color": "ffd23f"},
	"mila": {"preset": "ren", "name": "MILA", "title": "Kartenhai, neun Jahre alt", "color": "fb7185"},
	"krumm": {"preset": "don_valente", "name": "IMPRESARIO KRUMM", "title": "Veranstalter mit Schnurrbart", "color": "c084fc"},
	"granito": {"preset": "mutant_titan", "name": "GRANITO", "title": "Der Zermalmer · Herausforderer Nr. 983", "color": "a3a3a3"},
	"warrok": {"preset": "warrok_brute", "name": "WARROK", "title": "Zwölf Jahre Training für einen Kampf", "color": "ff8b26"},
	"belphegor": {"boss": "belphegor", "name": "BELPHEGOR", "title": "Der Dämon der Trägheit", "color": "7c3aed"},
	"shadow": {"preset": "bruno", "name": "BRUNO, DER GELANGWEILTE", "title": "Der Teil von ihm, dem alles egal ist", "color": "64748b"},
}

static func chapters() -> Array:
	return [
		{"id": "bruno_1", "title": "Kampf Nummer 983", "arena": "imperial_colosseum", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["granito", 3.0, -1], ["mila", -4.2, 1], ["krumm", 6.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "BRUNO · HUNGER", "sub": "Kapitel I – Kampf Nummer 983"},
			S._narr("Das Kaiserliche Kolosseum. Achtzigtausend Plätze. Sechstausend besetzt. Die meisten davon schlafen."),
			S._cam("close", 3, 1.2),
			S._pose(3, "Victory", 0.8),
			S._say("krumm", "Meine Damen und Herren! Ungeschlagen in neunhundertzweiundachtzig Kämpfen! Der Mann, der nie schwitzt! BRUNOOO!"),
			S._narr("Bruno betritt die Arena. Er gähnt. Das Publikum gähnt mit."),
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Roar", 1.0),
			S._say("granito", "Ich bin Granito der Zermalmer! Ich habe drei Jahre lang Felsen gefrühstückt – nur für diesen Tag!"),
			S._say("hero", "Hm. Felsen. Schmeckt das?"),
			S._say("granito", "… Was?"),
			S._say("hero", "Ich frag nur. Ich weiß nicht mehr, wie Sachen schmecken."),
			S._cam("sky", 0, 2.2),
			S._music("sad"),
			S._narr("Bruno war zehn, als ein Meteor auf sein Dorf zuraste. Alle rannten. Er nicht. Er ballte die Faust und schlug ihn zurück in den Himmel."),
			S._narr("Seitdem trägt seine Faust das Gewicht eines Sterns. Und seitdem spürt er nichts mehr. Keinen Schmerz. Keine Angst. Keinen Hunger."),
			S._music("calm"),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -2.8, "time": 0.8},
			S._cam("two", 0, 1.2, 2),
			S._say("mila", "Psst. Großer. Ich hab mein ganzes Taschengeld gewettet, dass du NICHT mit einem Schlag gewinnst. Elf Münzen und ein Knopf."),
			S._say("hero", "Warum wettest du gegen mich?"),
			S._say("mila", "Weil die Quote gut ist. Und weil dir eh alles egal ist. Dann kannst du's auch langsam machen."),
			{"t": "choice", "text": "Wie kämpft Bruno?", "options": [
				{"label": "Ein Schlag. Wie immer.", "flag": "bruno_onepunch", "steps": [
					S._say("hero", "Tut mir leid, Kleine. Ich weiß nicht, wie man langsam macht."),
					S._say("mila", "Dann bist du ein langweiliger Riese und ich bin pleite.")]},
				{"label": "Langsam. Für sie.", "flag": "bruno_slow", "steps": [
					S._say("hero", "Hm. Ich versuch's. Ich hab noch nie versucht, etwas NICHT zu schaffen."),
					S._say("mila", "Mach die Fäuste klein. Wie Kekse. Kleine Kekse.")]},
			]},
			S._music("fight"),
			{"t": "branch", "flag": "bruno_slow", "steps": [
				{"t": "fight", "cast": ["hero", "granito"], "goal": "GEWINN – ABER MIT KEKSFÄUSTEN!", "lives": [2, 2], "mods": {"0": {"power": 0.5}}, "ai": 5},
			], "else": [
				{"t": "fight", "cast": ["hero", "granito"], "goal": "KAMPF NUMMER 983.", "lives": [1, 1], "ai": 3},
			]},
			S._music("calm"),
			S._pose(1, "Defeat", 1.0),
			{"t": "branch", "flag": "bruno_slow", "steps": [
				S._narr("Es dauert vier Minuten. Granito fällt mit einem Lächeln, als hätte er zum ersten Mal einen richtigen Kampf gehabt."),
				S._say("mila", "Ich hab GEWONNEN! Dreiundzwanzig Münzen und zwei Knöpfe! Du bist der beste langweilige Riese der Welt!"),
				S._say("hero", "Hm. Das war … fast etwas. Hier drin."),
			], "else": [
				S._narr("Ein Schlag. Granito liegt im Sand, bevor er die Fäuste gehoben hat."),
				S._say("mila", "Elf Münzen. Und ein Knopf. Danke für nichts, Riese."),
				S._say("hero", "… Ich kauf dir einen neuen Knopf."),
			]},
			S._cam("close", 0, 1.6),
			S._narr("Am Ausgang wartet ein Brief. Darin nur ein Satz in krakeliger Schrift: »Schlag mich, Bruno. Wenn du dich traust. – W.«"),
		]},
		{"id": "bruno_2", "title": "Der Mann, der zurückschlägt", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -1.5, 1], ["warrok", 2.5, -1], ["krumm", -5.0, 1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 1, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Mann, der zurückschlägt"},
			S._narr("Die Gladiatorenfestung. Hier hat Bruno vor zwölf Jahren Warrok besiegt. Mit einem Schlag. Warrok hat seitdem nichts anderes getan als trainiert."),
			S._pose(1, "Roar", 1.0),
			S._say("warrok", "Zwölf Jahre, Bruno. Ich habe Berge zerbrochen. Gletscher umgedreht. Alles, um EINMAL nicht umzufallen."),
			S._say("hero", "Hm. Hast du zwischendurch auch gegessen?"),
			S._say("warrok", "WAS SPIELT DAS FÜR EINE ROLLE?!"),
			S._say("hero", "Ich frag nur. Irgendwer sollte das fragen."),
			S._cam("two", 0, 1.4, 1),
			S._say("warrok", "Ein Schlag, sagen sie? Dann schlag mich, Bruno. Zeig mir, dass es dir etwas bedeutet. Dass ICH dir etwas bedeute."),
			S._say("hero", "Ich will nicht. Wenn ich zuschlage, ist es vorbei. Und dann bist du wieder zwölf Jahre allein im Wald."),
			S._narr("Also schlägt Bruno nicht. Zehn Minuten lang lässt er Warrok auf sich einprügeln. Er will wissen, ob es irgendwann wehtut."),
			{"t": "fx", "kind": "shake"},
			S._pose(0, "HitReact", 0.6),
			{"t": "fx", "kind": "shake"},
			S._cam("close", 0, 1.2),
			S._say("hero", "… Da. Ganz hinten im Arm. Ein Ziepen. Warrok, ich glaube, du hast mir wehgetan."),
			S._say("warrok", "Das ist kein Kompliment, das ist eine BELEIDIGUNG! Wehr dich endlich!"),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -3.2, "time": 0.8},
			S._cam("close", 2, 1.0),
			S._say("krumm", "Bruno! Du bist ein Champion, kein Sandsack! Ich habe Verträge! Schlag zu, bevor die Leute es sehen!"),
			S._narr("Zum ersten Mal sieht Bruno seinen Veranstalter genauer an. Krumm schwitzt. Krumm schwitzt sonst nie."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "DIE METEORFAUST GLÜHT – JETZT!", "flag": "bruno_meteor",
				"success": [S._pose(0, "Charge", 0.8), S._narr("Die Faust glüht wie ein fallender Stern. Bruno hält sie zurück. Er will sie erst einsetzen, wenn es zählt.")],
				"fail": [S._say("hero", "Hm. Meine Faust ist eingeschlafen. Das ist neu.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "warrok"], "goal": "60 % SCHADEN – WEHR DICH ENDLICH!", "lives": [2, 2], "damage": {"0": 60}, "mods": {"1": {"power": 1.3}}, "qte": "bruno_meteor", "ai": 6},
			S._music("hope"),
			S._pose(1, "Defeat", 1.0),
			S._cam("two", 0, 1.4, 1),
			S._say("warrok", "Du hast … geschwitzt. Ich hab's gesehen. Ein Tropfen. Da. An der Schläfe."),
			S._say("hero", "Hm. Ja. Ich hatte kurz Angst, dass ich verliere. Das war schön, Warrok. Danke."),
			S._say("warrok", "Sag nie wieder »schön« zu mir."),
			S._cam("close", 2, 1.2),
			S._say("krumm", "Großartig, großartig. Ruht euch aus, Jungs. Ich muss … kurz in den Keller."),
			{"t": "move", "who": 2, "x": -9.0, "time": 1.0},
			S._music("tense"),
			S._narr("Die Gladiatorenfestung hat keinen Keller. Aber unter ihr gibt es Hitze, die nach Schwefel riecht."),
		]},
		{"id": "bruno_3", "title": "Der Vertrag im Eis", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["belphegor", 3.4, -1], ["krumm", 1.4, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Vertrag im Eis"},
			S._narr("Bruno folgt dem Geruch. Treppen. Noch mehr Treppen. Dann ein See aus Eis, so still, dass man das eigene Herz hört."),
			S._cam("two", 0, 1.4, 2),
			S._say("hero", "Krumm. Warum riecht dein Keller nach Hölle?"),
			S._say("krumm", "Bruno … vor zwanzig Jahren warst du ein Junge, der einen Meteor zurückgeschlagen hat. Ich sah einen Champion."),
			S._say("krumm", "Ich habe einen Vertrag gemacht. Für dich! Du solltest nie verlieren. Der Preis war nur dein Hunger. Ich dachte, den brauchst du nicht."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.2),
			S._music("boss"),
			S._say("belphegor", "Und ich habe ihn gut verwahrt. Zwanzig Jahre Hunger, Neugier und Lust auf morgen. Schmeckt wie eingelegte Pflaumen."),
			S._say("belphegor", "Du bist nicht stark, Bruno. Du bist nur gelangweilt. Leg dich hin. Schlaf. Für immer. Das ist das Einzige, was du noch kannst."),
			S._narr("Der See atmet Müdigkeit aus. Brunos Lider werden schwer. Schwerer als ein Meteor."),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 14, "time": 3.0, "text": "BLEIB WACH!", "flag": "bruno_awake",
				"success": [S._narr("Bruno beißt sich auf die Zunge. Es tut weh. Gut. Weh heißt wach.")],
				"fail": [S._pose(0, "Dazed", 0.8), S._narr("Er nickt kurz weg. Als er die Augen aufreißt, steht der Dämon viel zu nah.")]},
			S._cam("close", 2, 1.0),
			S._say("krumm", "Er sagt, wenn ich ihm nicht helfe, nimmt er MEINEN Hunger auch! Es tut mir leid, Bruno! Es tut mir so leid!"),
			S._say("hero", "Hm. Du hast mir zwanzig Jahre Essen gestohlen, Krumm. Darüber reden wir nachher. Beim Essen. Du zahlst."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "belphegor", "krumm"], "goal": "BEVOR DU EINSCHLÄFST!", "lives": [3, 2, 1], "teams": [0, 1, 1], "time": 90, "qte": "bruno_awake", "ai": 5},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "vanish", "who": 1},
			S._cam("close", 0, 1.6),
			S._narr("Belphegor zerplatzt wie eine Seifenblase voller Gähnen. Aus dem Eis steigt etwas Warmes und fließt in Bruno zurück. Zwanzig Jahre Hunger auf einmal."),
			S._pose(0, "Roar", 1.2),
			S._say("hero", "Oh. Oh nein. Oh JA. Ich hab Hunger. Ich hab SO einen Hunger. Krumm, wo gibt es hier die nächste Nudelsuppe?"),
			S._say("krumm", "Du … bist nicht wütend auf mich?"),
			S._say("hero", "Doch. Sehr. Es ist großartig. Ich hatte vergessen, wie sich wütend anfühlt. Erst essen. Dann wütend sein."),
		]},
		{"id": "bruno_4", "title": "Der Nachtmarkt", "arena": "bg_night_market", "stars": 3, "steps": [
			S._stage([["hero", -1.0, 1], ["shadow", 2.4, -1], ["mila", -3.0, 1], ["warrok", -4.4, 1], ["krumm", -5.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der Nachtmarkt"},
			S._narr("Der Nachtmarkt duftet nach Brühe, Röstzwiebeln und gebrannten Mandeln. Bruno hat schon vier Schüsseln gegessen. Er weint ein bisschen. Vor Glück."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Wusstet ihr, dass Suppe heiß ist? Und salzig? Und dass man sich die Zunge verbrennen kann? Fantastisch."),
			S._music("tense"),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("shadow", "Genieß es nicht zu sehr. Morgen schmeckt es wie heute. Übermorgen auch. Und in einem Jahr bist du wieder ich."),
			S._say("hero", "Du bist der Bruno, der gegähnt hat."),
			S._say("shadow", "Ich bin der Bruno, der nie verloren hat. Wer nie verliert, dem bedeutet nichts etwas. Willst du wirklich wieder verlieren können?"),
			S._say("hero", "Hm. Ja. Ich glaube, das will ich am meisten."),
			S._say("shadow", "Dann verlier. Gegen mich. Ich habe deine Faust. Ich habe deinen Stern. Und mir ist alles egal."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Charge", 1.0),
			S._narr("Zum ersten Mal seit zwanzig Jahren hat Bruno Angst vor einem Kampf. Seine Hände zittern. Er findet es wunderbar."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "shadow"], "goal": "BESIEGE DEN GELANGWEILTEN!", "lives": [2, 2], "mods": {"1": {"kb": 0.75}}, "ai": 8},
			S._music("hope"),
			{"t": "fx", "kind": "flash"},
			{"t": "vanish", "who": 1},
			S._cam("low", 0, 1.8),
			S._narr("Die Meteorfaust trifft. Der gelangweilte Bruno zerfällt zu Sternenstaub – und gähnt dabei ein letztes Mal."),
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3}, {"t": "appear", "who": 4},
			{"t": "move", "who": 2, "x": 0.8, "time": 0.8},
			{"t": "face", "who": 2, "facing": -1},
			S._cam("two", 0, 1.4, 2),
			{"t": "branch", "flag": "bruno_slow", "steps": [
				S._say("mila", "Großer! Damals hast du für mich langsam gemacht. Jetzt spielen wir Karten. Und diesmal machst du NICHT langsam."),
			], "else": [
				S._say("mila", "Großer. Du schuldest mir noch elf Münzen und einen Knopf. Ich nehme das in Karten. Setz dich."),
			]},
			S._narr("Sie spielen eine Runde. Dann zwei. Dann zehn. Warrok kiebitzt. Krumm zahlt die Suppe. Alle Suppen."),
			S._say("mila", "Joker. Gewonnen. Schon wieder. Du hast ein Gesicht wie ein offenes Buch, Bruno."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Victory", 1.2),
			{"t": "fx", "kind": "shake"},
			S._narr("Bruno verliert. Zum ersten Mal in seinem Leben. Und er lacht so laut, dass am anderen Ende der Stadt das Kolosseum bebt."),
			S._say("hero", "Noch eine Runde. Und noch eine Suppe. Ich habe so viel nachzuholen."),
			S._say("warrok", "Und danach ich. Revanche. Diesmal mit Hunger auf beiden Seiten."),
			S._cam("sky", 0, 3.0),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Bruno · Hunger"},
			S._narr("Relikt erhalten: Milas Joker  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
