extends RefCounted
## Legende: NYX, DER SEELENERNTER – „Die lange Schicht“.
## Eine einzige Nacht, von 23 Uhr bis zum Morgengrauen. Eine kleine Seele namens Motte, die nicht ans Ufer will,
## ein Laternenhändler aus Knochen, eine Fährfrau mit sehr wenig Geduld und ein Thron, auf dem man nie wieder müde ist.
## Hier wird erklärt, warum Nyx' Sense nach jedem Wurf zu ihm zurückkehrt.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die lange Schicht",
	"summary": "Siebenhundert Jahre ohne eine Nacht Schlaf. In dieser Nacht fehlen siebenundzwanzig Seelen – und eine kleine Seele will einfach nicht ans Ufer.",
	"relic": "Mottes Papierlaterne",
	"relic_text": "Eine kleine, zerknitterte Laterne. Wer sie trägt, findet im Dunkeln immer einen Weg zurück – auch zu sich selbst.",
}

const CAST := {
	"hero": {"preset": "nyx", "name": "NYX", "title": "Der Seelenernter", "color": "a855f7"},
	"motte": {"preset": "zip", "name": "MOTTE", "title": "Eine Seele, die nicht mitwill", "color": "fde047"},
	"ilva": {"preset": "pirate_captain", "name": "FÄHRFRAU ILVA", "title": "Rudert die Seelen über den Schwarzsee", "color": "38bdf8"},
	"soldat": {"preset": "vanguard_soldier", "name": "DER UNRUHIGE SOLDAT", "title": "Weiß nicht, dass er tot ist", "color": "a3a3a3"},
	"flayer": {"preset": "skeleton_reaper", "name": "FLAYER", "title": "Der Laternenhändler", "color": "e5e7eb"},
	"lucifer": {"boss": "lucifer", "name": "LUZIFER", "title": "Der Thron am Grund", "color": "ff3b30"},
	"hohl": {"preset": "nyx", "name": "DER HOHLE ERNTER", "title": "Nyx ohne Seele", "color": "312e81"},
}

static func chapters() -> Array:
	return [
		{"id": "nyx_1", "title": "23:00 – Das Feld nach der Schlacht", "arena": "blood_moon", "stars": 0, "steps": [
			S._stage([["hero", -2.0, 1], ["soldat", 2.6, -1], ["motte", -7.0, 1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "NYX · DIE LANGE SCHICHT", "sub": "23:00 Uhr – Das Feld nach der Schlacht"},
			S._narr("Jedes Mal, wenn irgendwo jemand stirbt, schlägt in Nyx eine Glocke. Er bringt die Verlorenen zum Ufer, damit sie nicht im Dunkeln herumirren."),
			S._narr("Dank bekommt er dafür keinen. Urlaub auch nicht. Seit siebenhundert Jahren nicht."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Dreihundertzwölf Seelen heute. Ein Schlachtfeld, ein Fieberhaus, ein Kerl, der für eine Wette auf einen Turm geklettert ist. Einer noch."),
			S._cam("two", 0, 1.2, 1),
			S._say("soldat", "Halt! Wer da? Parole! Die Linie wird gehalten, bis Verstärkung kommt!"),
			S._say("hero", "Die Verstärkung kam vor drei Tagen, Soldat. Ihr habt gewonnen. Und du bist dabei gefallen. Es tut mir leid. Komm. Das Ufer ist ruhig."),
			S._say("soldat", "Lügner! Ich bin nicht tot! Tote frieren nicht! Und mir ist so kalt …"),
			S._narr("Seelen, die nicht wissen, dass sie tot sind, werden wild. Sie schlagen um sich, bis jemand sie müde macht. Das ist der unschöne Teil der Arbeit."),
			S._pose(1, "Charge", 0.6),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.4, "text": "DAS BAJONETT! BLOCKEN!", "flag": "nyx_guard",
				"success": [S._pose(0, "Block", 0.6), S._narr("Nyx fängt den Stoß mit dem Sensenstiel ab, ohne den Soldaten zu verletzen. Siebenhundert Jahre Übung.")],
				"fail": [S._pose(0, "HitReact", 0.6), S._say("hero", "Au. Auch Tote haben spitze Ellbogen.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "soldat"], "goal": "BRING DIE WILDE SEELE ZUR RUHE!", "lives": [3, 2], "qte": "nyx_guard", "ai": 4,
				"mods": {"1": {"power": 1.3}}},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Defeat", 1.2),
			S._say("soldat", "Es ist … nicht mehr kalt. Sag meiner Mutter … nein. Sie weiß es schon, oder?"),
			S._say("hero", "Sie weiß es. Sie hat eine Kerze ins Fenster gestellt. Die siehst du gleich, vom Wasser aus."),
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "vanish", "who": 1},
			S._pose(0, "Attack", 0.8),
			S._narr("Nyx wirft die Sense. Sie fliegt über das Feld, dreht wie ein Bumerang und kehrt zu ihm zurück – mit einem hellen Funken im Bogen. Der Soldat."),
			S._narr("Seine Sense kommt immer zurück. Er hat nie gefragt, warum."),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -3.6, "time": 1.0},
			S._cam("two", 0, 1.2, 2),
			S._say("motte", "Machst du das jede Nacht? Ganz allein? Darf ich mitkommen? Ich bin Motte! Ich bin seit Dienstag tot!"),
			S._say("hero", "Nein. Nein. Nein. Und nein. Du gehörst ans Ufer, kleine Seele."),
			S._say("motte", "Das Ufer ist langweilig. Du bist nicht langweilig. Du bist traurig. Das ist viel interessanter."),
			S._cam("close", 0, 1.4),
			S._say("hero", "… Bis zum Morgengrauen. Dann bringe ich dich rüber. Und du fasst nichts an."),
		]},
		{"id": "nyx_2", "title": "01:00 – Der Laternenmarkt", "arena": "bg_night_market", "stars": 1, "steps": [
			S._stage([["hero", -1.8, 1], ["motte", -3.2, 1], ["flayer", 2.8, -1], ["ilva", -7.0, 1]]),
			{"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "01:00 Uhr – Der Laternenmarkt"},
			S._narr("Um eins zählt Nyx die Seelen am Ufer. Es fehlen siebenundzwanzig. Und Motte fasst – natürlich – alles an."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": -4.6, "time": 1.2},
			S._cam("two", 0, 1.2, 3),
			S._say("ilva", "Siebenundzwanzig zu wenig, Ernter. Mein Boot fährt nicht halb leer. Das ist Verschwendung von Ruderkraft."),
			S._say("hero", "Ilva. Ich hab sie alle eingesammelt, ich schwöre es. Irgendwer hat sie mir unterwegs aus dem Netz gezupft."),
			S._say("ilva", "Dann geh auf den Nachtmarkt. Dort verkauft einer Laternen, die viel zu hell leuchten."),
			S._cam("close", 2, 1.2),
			S._pose(2, "Victory", 0.8),
			S._say("flayer", "Laternen! Schöne Laternen! Jede mit echter Seele, garantiert warm, leuchtet hundert Jahre! Ah – Kollege!"),
			S._say("flayer", "Wir sind Kollegen, Nyx. Nur dass ich meine Arbeit genieße. Du trägst sie ans Ufer, ich hänge sie mir ins Wohnzimmer."),
			S._say("motte", "Die im blauen Glas, das ist Herr Brenner! Der hat mir immer Äpfel geschenkt! Lass ihn raus, du Knochengestell!"),
			S._say("flayer", "Knochengestell. Charmant. Das kostet dich extra, Kleine."),
			S._cam("two", 0, 1.2, 2),
			{"t": "choice", "text": "Was tut Nyx zuerst?", "options": [
				{"label": "Erst die Laternen befreien", "flag": "nyx_freed", "steps": [
					S._say("hero", "Motte, Ilva – die Laternen. Ich halte ihn auf, solange es eben dauert."),
					{"t": "fx", "kind": "flash"},
					S._narr("Glas klirrt. Siebenundzwanzig Lichter steigen auf. Flayer verliert seine Kraftquelle – aber Nyx kassiert einen Hieb in den Rücken, während er zusieht.")]},
				{"label": "Erst Flayer stellen", "flag": "nyx_duel", "steps": [
					S._say("hero", "Erst du. Dann die Laternen. Ich hab keine Zeit für Ordnung, ich hab eine Schicht."),
					S._say("flayer", "Oh, gut. Siebenundzwanzig Seelen leuchten für mich. Spürst du, wie stark ich bin?")]},
			]},
			S._music("fight"),
			{"t": "branch", "flag": "nyx_freed", "steps": [
				{"t": "fight", "cast": ["hero", "flayer"], "goal": "STELL DEN LATERNENHÄNDLER!", "lives": [2, 2], "damage": {"0": 45}, "ai": 5,
					"mods": {"1": {"power": 0.8}}},
			], "else": [
				{"t": "fight", "cast": ["hero", "flayer"], "goal": "STELL DEN LATERNENHÄNDLER!", "lives": [2, 3], "ai": 6,
					"mods": {"1": {"power": 1.2}}},
			]},
			S._music("sad"),
			S._cam("two", 0, 1.4, 2),
			S._pose(2, "Defeat", 1.0),
			{"t": "branch", "flag": "nyx_freed", "steps": [
				S._say("flayer", "Meine Sammlung … dreihundert Jahre Arbeit."),
				S._say("hero", "Arbeit ist, sie loszulassen, Flayer. Festhalten kann jeder."),
			], "else": [
				S._narr("Im Kampf zerspringen die Laternen von allein. Siebenundzwanzig Lichter steigen auf – aber drei sind zu schwach. Sie verlöschen, bevor Ilva sie erreicht."),
				S._say("hero", "Drei. Drei habe ich verloren, weil ich zuerst gewinnen wollte."),
				S._say("ilva", "Du hast vierundzwanzig gerettet, Ernter. Zähl die auch."),
			]},
			S._say("flayer", "Weißt du, warum sie lieber bei mir geblieben sind? Weil ich sie wenigstens angesehen habe. Du trägst sie wie Kartoffelsäcke."),
			{"t": "vanish", "who": 2},
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("motte", "Stimmt das? Schaust du sie nicht an?"),
			S._say("hero", "Wenn ich sie anschaue, Motte, dann trage ich sie. Jede Einzelne. Und ich hab nur zwei Hände."),
		]},
		{"id": "nyx_3", "title": "03:00 – Der Thron im Eis", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["lucifer", 3.0, -1], ["motte", -3.8, 1], ["ilva", -7.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "03:00 Uhr – Der Thron im Eis"},
			S._narr("Um drei Uhr nachts ist jeder am müdesten. Auch die, die keine Menschen mehr sind."),
			S._narr("Nyx bringt die letzten Seelen ans Ufer. Doch der Schwarzsee ist zugefroren. Und tief unter dem Eis leuchtet ein Thron."),
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lucifer", "Siebenhundert Jahre ohne eine Nacht Schlaf. Ich habe Respekt vor so viel Pflicht. Wirklich."),
			S._say("lucifer", "Setz dich. Nur einen Moment. Der Thron ist warm. Die Seelen erntet ab jetzt ein anderer. Keiner wird merken, dass du fehlst."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Keiner … wird es merken."),
			S._narr("Das ist das Gemeinste, was man einem Müden sagen kann. Nicht, dass er gehen soll. Sondern dass es egal ist, ob er bleibt."),
			{"t": "move", "who": 0, "x": 1.4, "time": 2.2},
			S._pose(0, "Crouch", 1.2),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Nyx setzt sich. Der Frost kriecht seine Flügel hinauf. Es fühlt sich an wie Schlaf. Es ist keiner."),
			S._cam("close", 2, 1.0),
			S._say("motte", "Nyx? NYX! Steh auf! Du hast gesagt, du bringst mich im Morgengrauen rüber! Du hast es VERSPROCHEN!"),
			{"t": "qte", "kind": "mash", "keys": ["standard"], "count": 14, "time": 3.0, "text": "MOTTE RÜTTELT AN IHM – HILF IHR!", "flag": "nyx_awake",
				"success": [{"t": "fx", "kind": "flash"}, S._pose(0, "Rise", 0.8), S._say("hero", "… Motte. Du fasst schon wieder alles an.")],
				"fail": [{"t": "fx", "kind": "shake"}, S._pose(0, "Dazed", 0.8), S._say("hero", "… Fünf Minuten noch. Nein. NEIN. Keine fünf Minuten.")]},
			{"t": "move", "who": 0, "x": -1.0, "time": 0.8},
			S._music("boss"),
			S._say("lucifer", "Eine kleine Seele hält dich wach? Wie rührend. Dann reiße ich sie dir eben aus den Händen."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": -5.0, "time": 1.0},
			S._say("ilva", "Ich halte das Eis offen, solange ich rudern kann, Ernter. Zwei Minuten. Dann friert der See für immer zu – mit dir drin."),
			{"t": "fight", "cast": ["hero", "lucifer"], "goal": "BRICH DEN THRON IN ZWEI MINUTEN!", "lives": [2, 1], "time": 120, "damage": {"0": 35},
				"qte": "nyx_awake", "ai": 7},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "vanish", "who": 1},
			S._narr("Der Thron zerspringt in tausend Scherben. Das Eis bricht, und Ilvas Boot gleitet hindurch, voll mit Lichtern."),
			S._cam("two", 0, 1.4, 3),
			S._say("hero", "Ich hätte fast Ja gesagt, Ilva."),
			S._say("ilva", "Ich weiß. Darum rudere ich seit siebenhundert Jahren hinter dir her. Komm jetzt. Es ist bald fünf."),
		]},
		{"id": "nyx_4", "title": "05:00 – Morgengrauen", "arena": "bg_aurora_peaks", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["hohl", 2.2, -1], ["motte", -3.0, 1], ["ilva", -7.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "05:00 Uhr – Morgengrauen"},
			S._narr("Fünf Uhr. Die letzte Seele der Nacht ist Motte. Nyx steht mit ihr auf einem Gipfel, von dem aus man das Ufer sieht."),
			S._cam("two", 0, 1.4, 2),
			S._say("motte", "Ich hab noch eine Frage. Die letzte, versprochen. Wo ist deine Seele, Nyx? Du hast Tausende getragen. Wer trägt deine?"),
			S._say("hero", "Ich habe keine. Ernter brauchen keine. Das macht die Arbeit leichter."),
			S._say("motte", "Lügner. Ich hab sie gesehen. In deiner Sense. Sie leuchtet jedes Mal, wenn die Klinge zu dir zurückfliegt."),
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.8),
			S._narr("Und Nyx erinnert sich. An die erste Nacht vor siebenhundert Jahren. An die Seuche, an die vielen, die im Dunkeln weinten, und an einen jungen Totengräber."),
			S._narr("Er schnitt seine eigene Seele los, legte sie in die Klinge und wurde der Ernter. Darum kehrt die Sense immer zurück. Sie will nach Hause."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.4, 1),
			S._say("hohl", "Und ich bin, was übrig blieb. Ein Mantel. Eine Pflicht. Kein Schlaf, kein Name, kein Dank. Ich bin der bessere Ernter. Mir tut nichts weh."),
			S._say("hohl", "Die Seelen lieben dich nicht, Nyx. Sie fürchten dich. Gib mir die Kleine. Ich bringe sie rüber. Schnell und ohne Gefühl."),
			S._say("motte", "Ich hab keine Angst vor Nyx! Ich hab Angst vor DIR. Du bist bloß ein Kleiderständer mit Flügeln!"),
			S._say("hero", "Sie hat recht. Und sie hat noch nie etwas nicht angefasst. Komm, Motte. Diesmal tragen wir zusammen."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "motte", "hohl"], "goal": "HOL DIR DEINE SEELE ZURÜCK!", "lives": [2, 1, 3], "teams": [0, 0, 1], "ai": 7,
				"mods": {"2": {"power": 1.2}}},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "vanish", "who": 1},
			S._cam("low", 0, 2.0),
			S._pose(0, "Summon", 1.0),
			S._narr("Nyx wirft die Sense ein letztes Mal. Sie fliegt in den Sonnenaufgang, dreht – und als sie zurückkehrt, bleibt das Licht nicht in der Klinge. Es geht in seine Brust."),
			S._say("hero", "Es ist warm. Ich wusste nicht mehr, dass das so warm ist."),
			{"t": "branch", "flag": "nyx_freed", "steps": [
				S._narr("Unten am Ufer leuchten siebenundzwanzig Lichter auf. Eines davon winkt mit einem Apfel."),
			], "else": [
				S._narr("Unten am Ufer leuchten vierundzwanzig Lichter auf. Daneben drei kleine Kerzen, die Ilva für die Verlorenen angezündet hat."),
			]},
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": -4.6, "time": 1.2},
			S._say("ilva", "Das Boot wartet, Motte."),
			S._say("motte", "Gleich. Nyx, leg dich hin. Nur bis die Sonne ganz oben ist. Ich halte die Sense. Ich fass auch nichts an."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Crouch", 1.4),
			S._narr("Zum ersten Mal in siebenhundert Jahren schläft der Seelenernter. Eine kleine Seele hält seine Sense, ganz ernst, ganz stolz. Sie fasst nur ein bisschen was an."),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Nyx · Die lange Schicht"},
			S._narr("Relikt erhalten: Mottes Papierlaterne  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
