extends RefCounted
## Legende: REN, DIE KIRSCHKRIEGERIN – „Herbst“.
## Ren wuchs unter einem Kirschbaum auf, der verflucht wurde und nie wieder blühte. Sie kämpft,
## damit nie wieder etwas Schönes welkt. Die Dornenhexe, die den Fluch sprach, hatte einen Grund,
## Lilith bietet einen Frühling ohne Ende – und Ren muss lernen, dass auch der Herbst dazugehört.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Herbst",
	"summary": "Ren kämpft, damit nichts Schönes mehr welkt. Seit ihr Kirschbaum verflucht wurde, hat sie Angst vor jedem Herbst – und vergisst dabei, selbst zu blühen.",
	"relic": "Die erste Kirsche",
	"relic_text": "Eine einzige Kirsche, dunkelrot und reif. Sie wächst nur an Bäumen, die vorher geblüht und geweint haben.",
}

const CAST := {
	"hero": {"preset": "ren", "name": "REN", "title": "Die Kirschkriegerin", "color": "f9a8d4"},
	"witch": {"preset": "thorn_witch", "name": "DIE DORNENHEXE", "title": "Die den Fluch sprach", "color": "16a34a"},
	"oma": {"preset": "sorceress_medea", "name": "GROSSMUTTER SAKI", "title": "Pflanzte den Baum", "color": "e9d5ff"},
	"woodcutter": {"preset": "warrok_brute", "name": "HOLZFÄLLER", "title": "Totes Holz brennt gut", "color": "a16207"},
	"lilith": {"boss": "lilith", "name": "LILITH", "title": "Der ewige Frühling", "color": "e11d48"},
	"bluete": {"preset": "ren", "name": "DIE EWIGE BLÜTE", "title": "Ren, die nie welken will", "color": "fbcfe8"},
}

static func chapters() -> Array:
	return [
		{"id": "ren_1", "title": "Der Baum, der nicht blüht", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["woodcutter", 3.0, -1], ["oma", -3.5, 1]]),
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "REN · HERBST", "sub": "Kapitel I – Der Baum, der nicht blüht"},
			S._narr("Hinter Großmutter Sakis Haus steht ein Kirschbaum. Ren hat unter ihm laufen gelernt, gelesen, geweint. Er blühte jedes Frühjahr – bis eine Hexe ihn verfluchte."),
			S._narr("Seit sieben Jahren steht er kahl. Ren pflegt ihn trotzdem jeden Morgen. Sie redet mit ihm. Er antwortet nicht."),
			S._cam("two", 0, 1.4, 1),
			S._say("woodcutter", "Totes Holz. Brennt gut. Die Alte hat gesagt, ich kann ihn haben."),
			S._say("oma", "Ich habe gesagt, du kannst ihn haben, wenn Ren es erlaubt. Sie erlaubt es nicht."),
			S._say("hero", "Er ist nicht tot. Er schläft nur. Wer ihn anrührt, bekommt jede Blüte, die er je hatte, als Klinge zurück."),
			S._say("woodcutter", "Blüten. Ich sehe keine einzige."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "BLÜTENWIRBEL!", "flag": "ren_petals",
				"success": [S._narr("Aus dem Nichts wirbeln rosa Blätter auf – Rens Erinnerung an jeden Frühling, scharf wie Glas.")],
				"fail": [S._narr("Nur ein paar welke Blätter. Der Holzfäller lacht.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "woodcutter"], "goal": "SCHÜTZE DEN KIRSCHBAUM!", "lives": [3, 2], "qte": "ren_petals", "ai": 3},
			S._music("sad"),
			S._cam("two", 0, 1.6, 2),
			S._say("oma", "Ren, mein Kind. Du kämpfst für diesen Baum wie andere für ein Königreich."),
			S._say("hero", "Er ist mein Königreich. Alles Schöne welkt, Oma. Ich lasse es nicht zu. Nicht bei ihm."),
			S._say("oma", "Und du selbst? Wann hast du das letzte Mal etwas für dich getan? Du bist neunzehn und lebst wie ein Wachhund."),
			S._cam("close", 0, 1.4),
			S._narr("Ren antwortet nicht. Sie sieht zum Wald. Dort, irgendwo, wohnt die Hexe, die den Baum verflucht hat."),
			S._say("oma", "Du willst zu ihr. Ich sehe es dir an. Du hast dieselbe Falte zwischen den Augen wie deine Mutter."),
			S._say("hero", "Sie hat uns den Frühling genommen, Oma. Ich hole ihn zurück."),
			S._say("oma", "Dann nimm Proviant mit. Und hör ihr zu, bevor du zuschlägst. Hexen haben selten keinen Grund."),
			S._narr("Ren packt Reiskugeln und ihr Schwert. Das mit dem Zuhören packt sie nicht ein. Noch nicht."),
		]},
		{"id": "ren_2", "title": "Das Haus aus Dornen", "arena": "bg_jungle_ruins", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["witch", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Das Haus aus Dornen"},
			S._narr("Drei Tage geht Ren durch die Ruinen im Dschungel. Am Ende steht ein Haus, ganz aus Dornenranken gewachsen. Darin blüht nichts."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("witch", "Das Kirschkind. Ich habe gewusst, dass du kommst. Du riechst nach Blüten, die es nicht mehr gibt."),
			S._say("hero", "Nimm den Fluch von meinem Baum."),
			S._say("witch", "Weißt du, warum ich ihn gesprochen habe? Deine Großmutter hat ihn gepflanzt – auf dem Grab meiner Schwester. Sie wusste es nicht. Aber der Baum trank von ihr."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("witch", "Blüten welken, Kirschkind. Dornen bleiben. Ich wollte, dass er so leer ist wie ich."),
			{"t": "choice", "text": "Was tut Ren?", "options": [
				{"label": "Zuhören", "flag": "ren_listened", "steps": [
					S._say("hero", "Wie hieß deine Schwester?"),
					S._say("witch", "Hana. Sie mochte Kirschen. … Warum fragst du? Kämpf lieber. Das kann ich besser als reden.")]},
				{"label": "Den Fluch erzwingen", "flag": "ren_forced", "steps": [
					S._say("hero", "Deine Trauer gibt dir nicht das Recht, meine zu machen. Nimm ihn zurück. Jetzt."),
					S._say("witch", "Dann komm und hol ihn dir aus meinen Dornen.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "witch"], "goal": "BLÜTE GEGEN DORN!", "lives": [2, 2], "ai": 5},
			S._music("sad"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "ren_listened", "steps": [
				S._say("witch", "Du kämpfst wie Hana. Immer nach vorne, nie zur Seite. Ich kann den Fluch nicht zurücknehmen. Aber ich kann dir zeigen, wo er wohnt."),
			], "else": [
				S._say("witch", "Selbst besiegt kann ich ihn nicht lösen. Ein Fluch gehört nicht mir, wenn er einmal gesprochen ist. Er gehört der, die ihn gekauft hat."),
				S._say("hero", "Gekauft? Von wem?"),
			]},
			S._narr("Die Dornen weichen auseinander. Dahinter ein Garten voller Blumen, die nie verwelken. Sie riechen nach nichts."),
		]},
		{"id": "ren_3", "title": "Der ewige Frühling", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lilith", 3.0, -1], ["witch", -4.0, 1], ["oma", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der ewige Frühling"},
			S._narr("Der Garten endet an einem Tor. Dahinter blühen Bäume, so weit das Auge reicht. Kein Blatt fällt. Keine Frucht wächst. Kein Vogel singt."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lilith", "Ren. Ich habe der Hexe ihren Fluch verkauft. Und dir verkaufe ich jetzt die Heilung: einen Frühling, der nie endet."),
			S._say("lilith", "Dein Baum wird blühen. Für immer. Kein Herbst. Kein Welken. Nie wieder Abschied. Das willst du doch."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Für immer blühen … ohne je Kirschen zu tragen?"),
			S._say("lilith", "Früchte heißen Herbst. Herbst heißt Ende. Du hast Angst vor dem Ende, Kirschkind. Darum wirst du nie reif."),
			S._say("hero", "Oma hat gesagt, die besten Kirschen wachsen nach dem kältesten Winter. Ich habe es nie geglaubt. Jetzt schon."),
			S._music("boss"),
			{"t": "branch", "flag": "ren_listened", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("witch", "Für Hana. Und für den Baum, der von ihr getrunken hat. Er soll Kirschen tragen, die sie gemocht hätte."),
				{"t": "fight", "cast": ["hero", "witch", "lilith"], "goal": "BRICH DEN EWIGEN FRÜHLING!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("oma", "Ich bin alt, aber nicht tot. Und mein Stock ist aus Kirschholz."),
				{"t": "fight", "cast": ["hero", "oma", "lilith"], "goal": "BRICH DEN EWIGEN FRÜHLING!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Die ewigen Bäume lassen zum ersten Mal ihre Blätter fallen. Es sieht traurig aus. Und dann, ganz langsam, wie Erleichterung."),
			S._say("lilith", "Du hättest alles haben können, Kirschkind. Ewige Schönheit."),
			S._say("hero", "Schönheit, die nicht vergeht, schaut irgendwann keiner mehr an. Man sieht Kirschblüten an, weil sie gehen."),
			S._say("hero", "Ich gehe nach Hause. Mein Baum wartet. Und ich habe Angst vor seinem Herbst. Ich gehe trotzdem."),
		]},
		{"id": "ren_4", "title": "Herbst", "arena": "mystic_grove", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["bluete", 2.0, -1], ["oma", -3.5, 1], ["witch", 4.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Herbst"},
			S._narr("Zuhause. Der Kirschbaum ist noch immer kahl. Aber an einem Zweig, ganz oben, sitzt eine einzige Knospe."),
			S._cam("two", 0, 1.6, 2),
			S._say("oma", "Sie wird aufgehen. Und dann wird sie welken. Und dann wird eine Kirsche daraus. So ist das."),
			S._say("hero", "Ich weiß. Ich weiß es jetzt. Es fühlt sich trotzdem an, als müsste ich sie beschützen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("bluete", "Dann beschütze sie. Für immer. Sei die Ren, die niemals loslässt. Die ewig blüht und nie fällt."),
			S._say("hero", "Du bist hübsch. Und du riechst nach nichts. Genau wie Liliths Garten."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "bluete"], "goal": "LASS DIE EWIGE BLÜTE WELKEN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._narr("Die Knospe öffnet sich. Eine Blüte, rosa und zerbrechlich. Ren setzt sich darunter, zum ersten Mal seit sieben Jahren ohne Schwert in der Hand."),
			S._narr("Am nächsten Morgen ist die Blüte gefallen. Ren weint ein bisschen. Dann sieht sie, was an ihrer Stelle wächst."),
			{"t": "branch", "flag": "ren_listened", "steps": [
				S._cam("two", 0, 1.6, 3),
				S._say("witch", "Eine Kirsche. Hana hätte sie sofort gegessen. Ohne zu teilen."),
				S._say("hero", "Dann teilen wir sie. Für sie."),
			], "else": [
				S._say("oma", "Eine Kirsche. Die erste. Sie gehört dir, Ren. Du hast sie dir verdient, indem du sie hast fallen lassen."),
			]},
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Ren · Herbst"},
			S._narr("Relikt erhalten: Die erste Kirsche  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
