extends RefCounted
## Legende: ZIP, DER BLITZKURIER – „Der Brief an mich“.
## Zip liefert jede Nachricht der Neonstadt – außer dem Brief, den er als Kind an sich selbst schrieb.
## Volt Ninja will ihn als schnellsten Läufer ablösen, Virtus hält ihn an und fragt, wohin er rennt,
## und am Ende muss Zip den einzigen Brief öffnen, vor dem er immer davongelaufen ist.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der Brief an mich",
	"summary": "Zip liefert jede Nachricht der Stadt in unter einer Minute. Nur einen Brief trägt er seit zehn Jahren ungeöffnet in der Tasche: den, den er als Kind an sich selbst schrieb.",
	"relic": "Der zerknitterte Umschlag",
	"relic_text": "Zehn Jahre in einer Kuriertasche, geöffnet an einem einzigen Abend. Auf der Rückseite steht in Kinderschrift: Nicht so schnell.",
}

const CAST := {
	"hero": {"preset": "zip", "name": "ZIP", "title": "Der Blitzkurier", "color": "38bdf8"},
	"ninja": {"preset": "ninja", "name": "VOLT NINJA", "title": "Will der Schnellste sein", "color": "facc15"},
	"oma": {"preset": "nekra", "name": "FRAU WEBER", "title": "Wartet auf einen Brief", "color": "e9d5ff"},
	"rival": {"preset": "echo", "name": "DROHNENKURIER 9000", "title": "Die Konkurrenz", "color": "a5b4fc"},
	"virtus": {"boss": "virtus", "name": "VIRTUS", "title": "Engel der Kräfte", "color": "fde68a"},
	"klein": {"preset": "zip", "name": "DER KLEINE ZIP", "title": "Der den Brief schrieb", "color": "bae6fd"},
}

static func chapters() -> Array:
	return [
		{"id": "zip_1", "title": "Neunundfünfzig Sekunden", "arena": "neon_metropolis", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["rival", 3.0, -1], ["oma", -3.5, 1]]),
			{"t": "vanish", "who": 2},
			S._music("hope"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "ZIP · DER BRIEF AN MICH", "sub": "Kapitel I – Neunundfünfzig Sekunden"},
			S._narr("Kein Brief in der Neonstadt braucht länger als eine Minute. Dafür sorgt Zip. Er rennt seit zehn Jahren. Er hat nie angehalten."),
			S._narr("In seiner Tasche: dreihundert Briefe am Tag. Und einer, der nie ausgeliefert wird. Adresse: An mich. Später."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Neunundfünfzig Sekunden, Rekord gehalten! Nächster! Nächster! Wer will was loswerden?"),
			S._cam("two", 0, 1.4, 1),
			S._say("rival", "Kurier Zip. Ihre Dienste sind überholt. Die Firma Drohnex liefert ab heute in achtundfünfzig Sekunden. Bitte räumen Sie die Straße."),
			S._say("hero", "Achtundfünfzig? Ha! Fang mich erst mal, Toaster."),
			{"t": "qte", "kind": "mash", "keys": ["jump"], "count": 8, "time": 2.4, "text": "TURBO!", "flag": "zip_turbo",
				"success": [S._narr("Zip wird zu einem blauen Strich zwischen den Hochhäusern. Die Drohne piept verwirrt.")],
				"fail": [S._narr("Zip stolpert über einen Bordstein. Zum ersten Mal seit Jahren.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "rival"], "goal": "SCHNELLER ALS DIE DROHNE!", "lives": [3, 2], "time": 90, "qte": "zip_turbo", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("oma", "Junger Mann. Sie bringen jeden Brief. Aber meinen nie. Ich warte seit zehn Jahren auf einen Brief von meinem Enkel."),
			S._say("hero", "Ich … habe keinen für Sie, Frau Weber. Es tut mir leid. Ich muss weiter!"),
			S._say("oma", "Er hieß Tobias. Er ist mit neun weggelaufen, aus dem Heim. Ich war seine Großmutter, aber sie haben mich ihn nicht besuchen lassen."),
			S._cam("close", 0, 1.4),
			S._narr("Er rennt los. Aber an der nächsten Ecke bleibt er stehen. Zum ersten Mal seit zehn Jahren. Nur eine Sekunde. Es fühlt sich an wie eine Stunde."),
			S._say("hero", "Mit neun. Aus dem Heim. … Zufall. Das ist ein Zufall. In dieser Stadt laufen jeden Tag Kinder weg."),
			S._narr("Er greift in die Tasche. Der Umschlag ist noch da. Er war immer da. Er ist schwerer als alle dreihundert anderen Briefe zusammen."),
		]},
		{"id": "zip_2", "title": "Ein Blitz gegen den anderen", "arena": "bg_rain_rooftop", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["ninja", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Ein Blitz gegen den anderen"},
			S._narr("Regen auf den Dächern. Zip rennt seine Abendrunde, als neben ihm ein zweiter Blitz einschlägt – gelb, nicht blau."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("ninja", "Man sagt, du bist der Schnellste in der Stadt. Ich bin hier, um das zu ändern."),
			S._say("hero", "Ich habe keine Zeit für Rennen. Ich habe dreihundert Briefe."),
			S._say("ninja", "Dreihundert und einen. Ich habe ihn gesehen, in deiner Tasche. An mich. Später. Du rennst nicht, um zu liefern. Du rennst davor weg."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 0.8),
			{"t": "choice", "text": "Was antwortet Zip?", "options": [
				{"label": "Ehrlich sein", "flag": "zip_honest", "steps": [
					S._say("hero", "Ich habe ihn mit neun geschrieben. Am Tag, als meine Eltern weg waren. Ich weiß nicht mehr, was drinsteht. Ich will es nicht wissen."),
					S._say("ninja", "Dann lauf. Aber lauf gegen mich, nicht vor dir weg.")]},
				{"label": "Weglachen", "flag": "zip_joke", "steps": [
					S._say("hero", "Das ist ein Werbeprospekt! Pizzaservice! Hahaha! Los, Rennen, du gelbe Glühbirne!"),
					S._say("ninja", "Wie du willst. Aber ich lache nicht mit.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "ninja"], "goal": "BLITZ GEGEN BLITZ!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "zip_honest", "steps": [
				S._say("ninja", "Du bist schneller als ich. Aber nur, wenn du nicht nachdenkst. Wenn du denkst, wirst du langsam. Interessant."),
				S._say("hero", "Darum denke ich nie."),
			], "else": [
				S._say("ninja", "Du lachst beim Kämpfen. Zu laut. Ich kenne das. Ich habe auch mal so gelacht. Danach kam der Absturz."),
			]},
			{"t": "fx", "kind": "flash"},
			S._narr("Ein Licht fällt vom Himmel auf das Dach. Es ist kein Blitz. Es ist ein Flügel."),
		]},
		{"id": "zip_3", "title": "Anhalten", "arena": "heaven_spheres", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["virtus", 3.0, -1], ["ninja", -4.0, 1], ["oma", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Anhalten"},
			S._narr("Zip rennt. Er rennt durch Wolken, über Licht, zwischen Sphären hindurch. Dann kann er auf einmal nicht mehr. Seine Beine bewegen sich nicht."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("virtus", "Kurier. Ich bin die Kraft, die alles in Bewegung hält. Und ich halte dich jetzt an. Nur einmal."),
			S._say("virtus", "Wohin rennst du, wenn alle Briefe zugestellt sind? Was passiert, wenn du ankommst?"),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ich komme nie an. Dafür sorge ich. Wenn man nie ankommt, muss man nie lesen, was dort wartet."),
			S._say("virtus", "Dann werde ich dich lehren, stillzustehen. Bis du es aushältst."),
			S._say("hero", "Niemand hält mich an. Nicht mal ein Engel!"),
			S._music("boss"),
			{"t": "branch", "flag": "zip_honest", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("ninja", "Ein Rennen unter Engeln! Diesmal laufen wir in dieselbe Richtung, Kurier."),
				{"t": "fight", "cast": ["hero", "ninja", "virtus"], "goal": "DURCHBRICH DEN STILLSTAND!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "fight", "cast": ["hero", "virtus"], "goal": "DURCHBRICH DEN STILLSTAND!", "lives": [3, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Virtus lässt los. Aber Zip rennt nicht sofort weiter. Er steht. Er atmet. Er hört sein eigenes Herz."),
			S._say("virtus", "Siehst du? Stillstehen bringt dich nicht um. Es bringt dich nur bei dir an."),
			S._say("hero", "Mein Herz ist so laut. War das immer so laut?"),
			S._say("virtus", "Immer. Du warst nur nie lange genug still, um es zu hören. Geh jetzt. Lies den Brief. Er wartet länger als jeder andere."),
			S._say("hero", "Und wenn darin steht, dass ich ein Versager bin?"),
			S._say("virtus", "Dann hat ihn ein Neunjähriger geschrieben, der Angst hatte. Und du bist jetzt neunzehn. Antworte ihm."),
		]},
		{"id": "zip_4", "title": "An mich. Später.", "arena": "bg_neon_alley", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["klein", 2.0, -1], ["oma", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "An mich. Später."},
			S._narr("Eine Gasse in der Neonstadt. Hier hat er gewohnt, mit neun. Zip zieht den alten Umschlag aus der Tasche. Seine Hände zittern."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("klein", "Du hast ihn nie gelesen. Zehn Jahre. Ich hab mir so viel Mühe gegeben mit der Schrift."),
			S._say("hero", "Ich hatte Angst, dass da drinsteht, dass ich es nicht geschafft habe. Dass ich immer noch der bin, den alle zurückgelassen haben."),
			S._say("klein", "Dann lauf weg. Wie immer. Fang mich, wenn du kannst – aber dann musst du stehen bleiben, um zu lesen!"),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "klein"], "goal": "HOL DEN KLEINEN ZIP EIN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 1.0),
			S._narr("Zip öffnet den Brief. Kinderschrift, krumm, mit einem Fleck, der eine Träne gewesen sein könnte."),
			S._say("klein", "Lieber großer Zip. Ich hoffe, du hast jemanden gefunden, der wartet, bis du ankommst. Und wenn nicht – dann warte du auf jemanden."),
			S._narr("Zip liest ihn dreimal. Dann rennt er los. Aber diesmal weiß er, wohin."),
			S._cam("two", 0, 1.6, 2),
			S._say("hero", "Frau Weber. Ich habe keinen Brief von Ihrem Enkel. Aber ich habe Zeit. Darf ich mich zu Ihnen setzen?"),
			S._say("oma", "Zehn Jahre hat das keiner gefragt. Komm rein, Junge. Es gibt Kuchen."),
			S._say("hero", "Frau Weber … Ihr Enkel. Tobias. Hatte er eine Narbe am Kinn? Vom Fahrrad?"),
			S._say("oma", "Woher … woher weißt du das?"),
			S._narr("Zip fasst sich ans Kinn. Er sagt nichts. Er muss nichts sagen. Die alte Frau lässt den Kuchenteller fallen und hält ihn fest – zum ersten Mal hält ihn jemand fest."),
			S._say("hero", "Ich bin angekommen, Oma. Ich bin endlich angekommen."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Zip · Der Brief an mich"},
			S._narr("Relikt erhalten: Der zerknitterte Umschlag  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
