extends RefCounted
## Legende: BRUNHILD – „Die Kleinste der Sippe“.
## Brunhild war die Kleinste ihrer Riesensippe, bis sie die goldene Axt aus dem Gletscher zog und wuchs.
## Sie glaubt, sie ist nur groß, solange sie die Axt hält. Die Lichtpaladinin Boltar verspottet sie,
## Michael verlangt die Axt für den Himmel zurück, und am Ende steht ihr das kleine Mädchen im Schnee gegenüber.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die Kleinste der Sippe",
	"summary": "Brunhild war die Kleinste unter Riesen, bis sie die goldene Axt aus dem Gletscher zog und wuchs. Sie hat Angst, wieder klein zu werden, sobald sie die Axt loslässt.",
	"relic": "Der Fäustling aus Kindertagen",
	"relic_text": "Ein winziger, gestrickter Fäustling. Er passt Brunhild nur noch über einen Finger – und sie trägt ihn trotzdem in jeder Schlacht.",
}

const CAST := {
	"hero": {"preset": "brunhild", "name": "BRUNHILD", "title": "Die Riesin mit der goldenen Axt", "color": "facc15"},
	"boltar": {"preset": "valkyrie", "name": "BOLTAR", "title": "Lichtpaladinin", "color": "fde68a"},
	"tove": {"preset": "lepora", "name": "TOVE", "title": "Ihre kleine Schwester", "color": "bae6fd"},
	"raider": {"preset": "warrok_brute", "name": "BERGRÄUBER", "title": "Will das Gold der Axt", "color": "a8a29e"},
	"raider2": {"preset": "mutant_titan", "name": "BERGRÄUBER", "title": "Will das Gold der Axt", "color": "a8a29e"},
	"michael": {"boss": "michael", "name": "MICHAEL", "title": "Erzengel des Himmels", "color": "fef3c7"},
	"klein": {"preset": "brunhild", "name": "DIE KLEINE BRUNHILD", "title": "Das Mädchen im Schnee", "color": "e0f2fe"},
}

static func chapters() -> Array:
	return [
		{"id": "brunhild_1", "title": "Die Axt im Gletscher", "arena": "frozen_summit", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["raider", 2.8, -1], ["raider2", 4.2, -1], ["tove", -3.5, 1]]),
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "BRUNHILD · DIE KLEINSTE DER SIPPE", "sub": "Kapitel I – Die Axt im Gletscher"},
			S._narr("Unter den Riesen des Nordens war Brunhild die Kleinste. Ihre Brüder trugen Bäume. Sie trug Holzscheite. Man nannte sie Däumling."),
			S._narr("Mit zwölf Jahren kletterte sie allein auf den Gletscher und zog eine goldene Axt aus dem Eis. Am nächsten Morgen überragte sie ihren Vater."),
			S._cam("two", 0, 1.6, 3),
			S._say("tove", "Erzähl die Geschichte noch mal! Wie du die Axt rausgezogen hast und alle umgefallen sind!"),
			S._say("hero", "Nicht jetzt, Tove. Wir haben Besuch. Unhöflichen Besuch."),
			S._cam("two", 0, 1.4, 1),
			S._say("raider", "Die Riesin mit der Goldaxt. Das Ding ist ein Vermögen wert. Gib her, und wir lassen den Zwerg da in Ruhe."),
			S._say("hero", "Den Zwerg nennt man Schwester. Und die Axt bekommt niemand. Ohne sie bin ich …"),
			S._narr("Sie spricht den Satz nicht zu Ende. Sie spricht ihn nie zu Ende."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "MIDAS-BEBEN!", "flag": "brunhild_quake",
				"success": [S._narr("Die Axt schlägt in den Boden. Der ganze Gletscher dröhnt wie eine Glocke.")],
				"fail": [S._narr("Die Axt rutscht ihr fast aus der Hand. Für einen Moment wird ihr schwindlig.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "raider", "raider2"], "goal": "VERTEIDIGE DAS DORF DER RIESEN!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "brunhild_quake", "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.6, 3),
			S._say("tove", "Du hast sie alle geschafft! Mit der Axt bist du unbesiegbar!"),
			S._say("hero", "Mit der Axt, ja."),
			S._cam("close", 0, 1.4),
			S._narr("In der Nacht schläft Brunhild mit der Axt im Arm. Wie immer. Seit zwölf Jahren hat sie sie nie losgelassen."),
			S._say("tove", "Schwester? Was passiert, wenn du sie mal loslässt? Nur ganz kurz?"),
			S._say("hero", "Schlaf, Tove."),
			S._say("tove", "Ich hab dich lieb, auch wenn du klein bist. Nur dass du es weißt."),
			S._narr("Brunhild liegt lange wach. Die Axt ist kalt in ihren Armen. Sie war immer kalt. Das ist ihr bisher nie aufgefallen."),
		]},
		{"id": "brunhild_2", "title": "Die Paladinin", "arena": "gladiator_fortress", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["boltar", 2.5, -1], ["tove", -3.5, 1]]),
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Paladinin"},
			S._narr("Die Festung der Gladiatoren hat eine Herausforderung ausgerufen: Wer die Lichtpaladinin Boltar schlägt, bekommt einen Platz im Rat der Krieger."),
			S._cam("two", 0, 1.6, 1),
			S._say("boltar", "Eine Riesin mit geliehener Größe. Ich kenne die Geschichte. Ohne die Axt bist du wieder das kleine Mädchen im Schnee."),
			S._say("hero", "Wer hat dir das erzählt?"),
			S._say("boltar", "Jeder im Norden. Sie lachen darüber am Feuer. Die große Brunhild, die nachts die Axt umarmt wie ein Kuscheltier."),
			S._say("tove", "Das ist gemein! Hau sie, Schwester!"),
			{"t": "choice", "text": "Wie kämpft Brunhild?", "options": [
				{"label": "Ohne Axt", "flag": "brunhild_bare", "steps": [
					S._narr("Brunhild lehnt die Axt an die Wand. Ihre Hände zittern. Sie schrumpft nicht. Noch nicht."),
					S._say("boltar", "Mutig. Oder dumm. Wir werden sehen, was davon.")]},
				{"label": "Mit Axt", "flag": "brunhild_axe", "steps": [
					S._say("hero", "Lacht ruhig. Diese Axt hat mehr Schlachten gesehen als euer ganzes Lagerfeuer."),
					S._say("boltar", "Die Axt, ja. Und du?")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "boltar"], "goal": "BESTEHE DIE HERAUSFORDERUNG!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "brunhild_bare", "steps": [
				S._say("boltar", "Du bist nicht geschrumpft. Nicht einen Zoll. Ist dir das aufgefallen?"),
				S._say("hero", "Ich … habe nicht hingesehen. Ich hatte zu viel Angst."),
			], "else": [
				S._say("boltar", "Die Axt hat gewonnen. Gratuliere ihr von mir."),
				S._narr("Brunhild antwortet nicht. Der Sieg schmeckt nach Metall."),
			]},
			{"t": "fx", "kind": "flash"},
			S._narr("Ein Lichtstrahl fällt in die Festung, so hell, dass alle die Augen schließen. Eine Stimme wie eine Posaune ruft: Die Axt gehört dem Himmel."),
		]},
		{"id": "brunhild_3", "title": "Der Erzengel und die Axt", "arena": "heaven_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["michael", 3.0, -1], ["tove", -4.0, 1], ["boltar", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Erzengel und die Axt"},
			S._narr("Brunhild steht vor der Himmelspforte. Die Axt in ihrer Hand glüht, als wüsste sie, wo sie ist."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("michael", "Diese Axt fiel aus meiner Rüstung, als ich gegen den Drachen kämpfte. Vor tausend Jahren. Sie gehört dem Himmel. Gib sie zurück."),
			S._say("hero", "Wenn ich sie zurückgebe, werde ich wieder klein. Dann lachen sie wieder."),
			S._say("michael", "Möglich. Aber sie ist nicht deine. Groß zu sein mit geliehener Kraft ist Diebstahl, Riesin."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Ich habe sie nicht gestohlen. Ich habe sie gefunden. Ich war zwölf und hatte Angst und bin trotzdem allein auf den Gletscher gestiegen."),
			S._say("michael", "Dann beweise, dass du sie verdienst. Oder dass du sie nicht brauchst."),
			S._music("boss"),
			{"t": "branch", "flag": "brunhild_bare", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("boltar", "Du hast ohne Axt gegen mich gekämpft. Ich schulde dir einen Kampf mit ihr. Gegen den Himmel, wenn es sein muss."),
				{"t": "fight", "cast": ["hero", "boltar", "michael"], "goal": "STEH VOR DEM ERZENGEL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("tove", "Ich bin klein, aber ich kann beißen! Lass meine Schwester in Ruhe, Vogelmann!"),
				{"t": "fight", "cast": ["hero", "tove", "michael"], "goal": "STEH VOR DEM ERZENGEL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Michael senkt sein Schwert. In seinen Augen ist kein Zorn. Nur eine Frage, die er nicht ausspricht."),
			S._say("michael", "Behalte sie noch. Bis du weißt, was du ohne sie bist. Dann bring sie mir. Oder nicht."),
		]},
		{"id": "brunhild_4", "title": "Das Mädchen im Schnee", "arena": "bg_aurora_peaks", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["klein", 2.0, -1], ["tove", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Das Mädchen im Schnee"},
			S._narr("Zurück auf dem Gletscher, an der Stelle, wo alles begann. Das Loch im Eis, aus dem sie die Axt zog, ist noch da."),
			S._cam("two", 0, 1.6, 2),
			S._say("tove", "Wenn du sie zurücksteckst, wirst du dann wieder so klein wie ich?"),
			S._say("hero", "Ich weiß es nicht, Tove. Ich habe zwölf Jahre lang Angst vor dieser Antwort gehabt."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("klein", "Ich bin du. Mit zwölf. Klein und frierend und ausgelacht. Ohne die Axt bist du wieder ich. Willst du das?"),
			S._say("hero", "Du bist allein auf diesen Gletscher gestiegen. Durch einen Schneesturm. Ohne Axt."),
			S._say("klein", "… Ja. Weil ich es satt hatte, klein zu sein."),
			S._say("hero", "Dann warst du nie klein. Zeig es mir."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "klein"], "goal": "BESIEGE DEIN KLEINES ICH!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Slam", 1.0),
			S._narr("Brunhild stößt die goldene Axt zurück ins Eis. Sie lässt den Griff los. Sie wartet. Sie schrumpft nicht."),
			S._narr("Sie war es die ganze Zeit. Die Axt hat sie nicht groß gemacht. Sie hat ihr nur Zeit gegeben, es zu merken."),
			S._cam("two", 0, 1.6, 2),
			S._say("tove", "Du bist immer noch riesig! Riesig und ohne Axt!"),
			S._say("hero", "Und weißt du was? Morgen bringen wir sie dem Erzengel. Zusammen. Du darfst auf meinen Schultern sitzen."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Brunhild · Die Kleinste der Sippe"},
			S._narr("Relikt erhalten: Der Fäustling aus Kindertagen  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
