extends RefCounted
## Legende: NEKRA, DIE SEELENHIRTIN – „Morgen“.
## Nekra hütet einen Garten aus Knochen, in dem die Seelen vergessener Tiere ruhen. Sie spricht mit
## den Toten, weil die Lebenden nie zurückgegrüßt haben. Flayer will aus ihren Knochen Werkzeuge machen,
## Ahriman bietet eine Herde ohne Ende – und ein lebendiger Hund will einfach mit nach Hause.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Morgen",
	"summary": "Nekra hütet die Seelen vergessener Tiere in einem Garten aus Knochen. Die Toten grüßen zurück. Die Lebenden haben es nie getan – also hat sie aufgehört, sie zu grüßen.",
	"relic": "Das Halsband von Morgen",
	"relic_text": "Ein abgewetztes Lederhalsband mit einer Marke. Darauf steht nur ein Wort: MORGEN. Es riecht nach nassem Hund und nach Zuhause.",
}

const CAST := {
	"hero": {"preset": "nekra", "name": "NEKRA", "title": "Die Seelenhirtin", "color": "a78bfa"},
	"flayer": {"preset": "skeleton_reaper", "name": "FLAYER", "title": "Der Seelenernter", "color": "a3a3a3"},
	"hound": {"preset": "reaper_hound", "name": "MORGEN", "title": "Ein Hund, der noch lebt", "color": "fde68a"},
	"dorf": {"preset": "steel_knight", "name": "DORFVOGT", "title": "Hält sie für eine Hexe", "color": "94a3b8"},
	"dorf2": {"preset": "swat_specops", "name": "DORFWACHE", "title": "Hält sie für eine Hexe", "color": "94a3b8"},
	"ahriman": {"boss": "ahriman", "name": "AHRIMAN", "title": "Der Hirte der Stille", "color": "7c3aed"},
	"stumm": {"preset": "nekra", "name": "DIE STUMME HIRTIN", "title": "Nekra, die nur noch Tote liebt", "color": "3b0764"},
}

static func chapters() -> Array:
	return [
		{"id": "nekra_1", "title": "Der Knochengarten", "arena": "blood_moon", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["dorf", 2.8, -1], ["dorf2", 4.0, -1], ["hound", 7.0, -1]]),
			{"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "NEKRA · MORGEN", "sub": "Kapitel I – Der Knochengarten"},
			S._narr("Hinter dem Dorf, unter dem Blutmond, liegt ein Garten. Statt Blumen wachsen dort Knochen: Vogelflügel, Fuchsschädel, das Rückgrat eines alten Pferdes."),
			S._narr("Hier ruhen die Tiere, die keiner begraben wollte. Nekra hütet ihre Seelen. Sie singt ihnen abends vor. Die Toten grüßen zurück."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Ruhig, meine Kleinen. Die Hirtin ist da. Heute kam ein Spatz dazu. Er heißt Federchen. Seid nett zu ihm."),
			S._cam("two", 0, 1.4, 1),
			S._say("dorf", "Die Knochenhexe! Seit sie hier ist, heulen nachts die Hunde. Die Kinder haben Albträume. Wir räumen diesen Garten."),
			S._say("hero", "Die Hunde heulen, weil sie ihre toten Freunde riechen. Die Kinder träumen, weil ihr ihnen Geschichten über mich erzählt."),
			S._say("dorf2", "Sie redet mit Knochen! Schnell, bevor sie uns verflucht!"),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "KNOCHENGARTEN!", "flag": "nekra_garden",
				"success": [S._narr("Aus dem Boden wachsen Knochen wie Hecken und schließen den Garten ein. Niemand wird verletzt. Niemand kommt hinein.")],
				"fail": [S._narr("Die Knochen regen sich nur schwach. Die Toten haben Angst vor den Fackeln.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "dorf", "dorf2"], "goal": "SCHÜTZE DEN KNOCHENGARTEN!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "nekra_garden", "ai": 3},
			S._music("sad"),
			S._cam("close", 0, 1.4),
			S._narr("Die Dorfleute fliehen. Nekra sieht ihnen nach. Sie hat nie jemanden verflucht. Aber jeder flieht, bevor sie Hallo sagen kann."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": 2.0, "time": 1.2},
			S._cam("two", 0, 1.6, 3),
			S._narr("Aus dem Dunkel trottet ein Hund. Mager, mit zerzaustem Fell und einer Schnauze voller Kletten. Er ist nicht tot. Er wedelt."),
			S._say("hero", "Du gehörst nicht hierher, Kleiner. Hier ist nur für die Toten. Geh zu den Lebenden."),
			S._say("hound", "Wuff."),
			S._narr("Er legt sich vor ihre Füße. Er bleibt die ganze Nacht."),
			S._say("hero", "Du bist warm. Die anderen sind alle kalt. Ich hatte vergessen, wie sich warm anfühlt."),
			S._narr("Im Knochengarten regen sich die Seelen. Ein alter Hundeschädel, lange begraben, bellt leise. Es klingt wie ein Gruß. Oder wie eine Erlaubnis."),
			S._say("hero", "Bodo meint, du darfst bleiben. Bodo war hier der Älteste. Aber nur eine Nacht."),
			S._narr("Es bleibt nicht bei einer Nacht."),
			S._say("hound", "Wuff."),
		]},
		{"id": "nekra_2", "title": "Werkzeuge und Freunde", "arena": "mystic_grove", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["flayer", 2.5, -1], ["hound", -3.4, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Werkzeuge und Freunde"},
			S._narr("Der Hund geht nicht weg. Nekra schickt ihn fort, jeden Morgen. Jeden Abend liegt er wieder vor dem Garten. Sie nennt ihn nicht beim Namen. Wer einen Namen hat, kann man verlieren."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("flayer", "Seelenhirtin. Knochen sammeln, Nekra? Ich mache aus ihnen Werkzeuge. Du machst daraus Freunde. Was für eine Verschwendung."),
			S._say("hero", "Sie sind keine Werkzeuge. Sie haben gelebt. Sie hatten Namen."),
			S._say("flayer", "Hatten. Und der Köter da? Hat der einen? Oder sparst du dir das, bis er tot ist und in deinen Garten passt?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 0.8),
			{"t": "choice", "text": "Was tut Nekra?", "options": [
				{"label": "Dem Hund einen Namen geben", "flag": "nekra_named", "steps": [
					S._say("hero", "Er heißt … Morgen. Weil er jeden Morgen wiederkommt. Und weil er noch nicht tot ist."),
					S._say("hound", "Wuff!"),
					S._say("flayer", "Wie rührend. Jetzt hast du etwas zu verlieren. Pass gut auf.")]},
				{"label": "Den Hund wegschicken", "flag": "nekra_alone", "steps": [
					S._say("hero", "Er gehört nicht zu mir. Lauf, Hund! Lauf zu den Lebenden!"),
					S._say("flayer", "Er läuft nicht. Interessant. Er ist dümmer als du – oder klüger.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "flayer"], "goal": "VERTEIDIGE DIE SEELEN DES GARTENS!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "nekra_named", "steps": [
				S._say("flayer", "Du hast besser gekämpft, seit du ihm einen Namen gegeben hast. Das ist unlogisch. Und ärgerlich."),
				S._say("hero", "Die Toten geben mir Ruhe. Er gibt mir einen Grund."),
			], "else": [
				S._say("flayer", "Du kämpfst wie eine, die schon gestorben ist. Kein Wunder, dass dich die Lebenden meiden."),
			]},
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("In der Nacht verstummen die Seelen im Garten. Alle auf einmal. Etwas hat sie gerufen. Etwas, das nach Rauch riecht und sehr leise lächelt."),
		]},
		{"id": "nekra_3", "title": "Die stumme Herde", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["ahriman", 3.0, -1], ["hound", -4.0, 1], ["flayer", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die stumme Herde"},
			S._narr("Nekra folgt den Seelen bis an das Höllentor. Dort stehen sie, Tausende, Vögel und Füchse und Pferde, in Reihen. Stumm. Mit leeren Augen."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("ahriman", "Hirtin. Ich biete dir eine Herde ohne Ende. Alle Seelen der Welt. Für immer bei dir. Für immer stumm. Sie werden dich nie verlassen."),
			S._say("ahriman", "Die Lebenden fürchten dich. Und sie haben recht. Du gehörst zu uns. Zu den Stillen."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Für immer bei mir … Niemand, der wegläuft. Niemand, der flieht."),
			S._say("ahriman", "Niemand, der stirbt. Sie sind ja schon tot. Kein Abschied mehr. Nie wieder."),
			S._say("hero", "Aber auch niemand, der grüßt. Meine Kleinen haben mir immer zurückgesungen. Diese hier singen nicht. Du hast ihnen die Stimme genommen."),
			S._music("boss"),
			{"t": "branch", "flag": "nekra_named", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("hound", "WUFF! WUFF WUFF!"),
				S._narr("Morgen bellt. Laut, lebendig, ganz und gar nicht stumm. Und zwischen den Reihen der toten Tiere hebt ein Fuchsschädel den Kopf."),
				{"t": "fight", "cast": ["hero", "hound", "ahriman"], "goal": "GIB DER HERDE IHRE STIMME ZURÜCK!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("flayer", "Er nimmt dir deine Seelen weg? Das ist MEIN Geschäft. Ich lasse mich nicht unterbieten."),
				{"t": "fight", "cast": ["hero", "flayer", "ahriman"], "goal": "GIB DER HERDE IHRE STIMME ZURÜCK!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Ahriman löst sich in Rauch auf. Und die Herde singt. Tausende Stimmen, Vogelpfiffe und Fuchsgebell und ein altes Pferd, das wiehert. Dann ziehen sie heim in den Garten."),
		]},
		{"id": "nekra_4", "title": "Morgen", "arena": "bg_rain_rooftop", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["stumm", 2.0, -1], ["hound", -3.2, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Morgen"},
			S._narr("Regen auf den Dächern des Dorfes. Morgen ist krank. Er hustet, er frisst nicht. Nekra sitzt neben ihm und weiß genau, was das bedeutet. Sie hat es tausendmal gesehen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("stumm", "Siehst du? Darum liebt man nur Tote. Sie können nicht mehr sterben. Lass ihn gehen. Er kommt in den Garten. Dann ist er für immer bei dir."),
			S._say("hero", "Er ist noch nicht tot. Er ist krank. Kranke kann man pflegen. Das habe ich vergessen, weil ich nur noch Knochen hatte."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "stumm"], "goal": "KÄMPFE FÜR DIE LEBENDEN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._narr("Nekra trägt Morgen durch den Regen ins Dorf. Sie klopft an die erste Tür, die sie findet. Es ist die Tür des Vogts."),
			S._say("hero", "Bitte. Er ist krank. Ich weiß, wie man Tote hütet. Ich weiß nicht, wie man Lebende rettet. Helft mir."),
			S._narr("Der Vogt starrt sie an. Dann sieht er den Hund. Dann öffnet er die Tür ganz. Seine Frau holt Decken, seine Tochter warme Milch."),
			S._cam("two", 0, 1.6, 2),
			S._narr("Drei Tage später frisst Morgen wieder. Am vierten Tag wedelt er. Am fünften grüßt die Tochter des Vogts Nekra auf der Straße."),
			S._say("hero", "Guten Morgen."),
			S._say("hound", "Wuff."),
			S._narr("Es ist das erste Mal, dass Nekra einen Lebenden grüßt. Es wird nicht das letzte Mal sein. Abends singt sie trotzdem im Garten. Jetzt mit Hund."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Nekra · Morgen"},
			S._narr("Relikt erhalten: Das Halsband von Morgen  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
