extends RefCounted
## Legende: SORCERESS MEDEA – „Der eine Zauber“.
## Medea lernte jeden Zauber der Welt – bis auf den einen, der einen Menschen zurückbringt: ihren
## Bruder Iason, der im Sturm ertrank. Amethya will ihre Bibliothek für die Lebenden, Lilith verkauft
## den verbotenen Zauber gegen ihr Spiegelbild, und am Ende muss Medea etwas tun, das keine Magie ist.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der eine Zauber",
	"summary": "Medea beherrscht jeden Zauber der Welt – bis auf den einen, der ihren ertrunkenen Bruder zurückbringen würde. Sie sammelt Macht, um eine Leere zu füllen, die keine Magie füllt.",
	"relic": "Die Kerze ohne Zauber",
	"relic_text": "Eine einfache Wachskerze, mit einem Streichholz angezündet. Keine Rune, kein Spruch. Sie brennt erstaunlich lange.",
}

const CAST := {
	"hero": {"preset": "sorceress_medea", "name": "MEDEA", "title": "Die Erzmagierin", "color": "a78bfa"},
	"amethya": {"preset": "amethya", "name": "AMETHYA", "title": "Die Donnerhexe", "color": "c084fc"},
	"iason": {"preset": "jubei", "name": "IASON", "title": "Ihr Bruder – oder ein Echo", "color": "93c5fd"},
	"dieb": {"preset": "specter", "name": "GRIMOIRE-DIEBIN", "title": "Will das Buch der Toten", "color": "475569"},
	"dieb2": {"preset": "nekra", "name": "GRIMOIRE-DIEBIN", "title": "Will das Buch der Toten", "color": "475569"},
	"lilith": {"boss": "lilith", "name": "LILITH", "title": "Händlerin verbotener Dinge", "color": "e11d48"},
	"spiegel": {"preset": "sorceress_medea", "name": "MEDEAS SPIEGELBILD", "title": "Was sie verkaufen wollte", "color": "4c1d95"},
}

static func chapters() -> Array:
	return [
		{"id": "sorceress_medea_1", "title": "Die Bibliothek unter dem Blutmond", "arena": "blood_moon", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["dieb", 2.8, -1], ["dieb2", 4.0, -1]]),
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "MEDEA · DER EINE ZAUBER", "sub": "Kapitel I – Die Bibliothek unter dem Blutmond"},
			S._narr("In einem Turm unter dem Blutmond liegen elftausend Zauberbücher. Medea hat jedes gelesen. Sie kann Sterne verschieben und Flüsse rückwärts fließen lassen."),
			S._narr("Nur einen Zauber kennt sie nicht. Den, der ihren Bruder Iason zurückholt, der vor zwanzig Jahren im Sturm ertrank, als sie ihn hätte retten können."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Elftausend Bücher. Und keins sagt mir, wie man einen Menschen zurückbringt. Nur, warum man es nicht soll."),
			S._cam("two", 0, 1.4, 1),
			S._say("dieb", "Das Buch der Toten. Wir wissen, dass du es hast. Gib es uns, Hexe. Wir haben Kunden, die gut zahlen."),
			S._say("hero", "Das Buch der Toten ist leer. Ich habe jede Seite gelesen. Es steht nichts darin, was ihr verkaufen könntet."),
			S._say("dieb2", "Dann lügst du. Oder du hast nicht richtig gelesen."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "ASTRAL-EXPLOSION!", "flag": "sorceress_medea_astral",
				"success": [S._narr("Ein Kreis aus Sternenlicht entfaltet sich um Medea. Die Diebinnen werden zurückgeschleudert.")],
				"fail": [S._narr("Die Formel stockt. Medea hat einen Moment zu lange an Iason gedacht.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "dieb", "dieb2"], "goal": "SCHÜTZE DIE BIBLIOTHEK!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "sorceress_medea_astral", "ai": 3},
			S._music("sad"),
			S._cam("close", 0, 1.4),
			S._narr("Die Diebinnen fliehen. Auf dem Boden liegt ein Zettel, den eine von ihnen verloren hat. Darauf ein Siegel: eine rote Lippe. Und ein Satz."),
			S._say("hero", "»Der Zauber existiert. Er hat nur einen Preis.« … Lilith."),
			S._narr("Medea steckt den Zettel ein. Sie weiß, dass sie ihn verbrennen sollte. Sie tut es nicht."),
			S._cam("low", 0, 1.6),
			S._say("hero", "Iason. Du hast immer gesagt, ich lese zu viel und lebe zu wenig. Wenn du wüsstest, wie recht du hattest."),
			S._narr("Die Kerzen der Bibliothek flackern, obwohl kein Wind geht. Medea hat elftausend Zauber für Licht. Sie benutzt keinen davon."),
		]},
		{"id": "sorceress_medea_2", "title": "Die Donnerhexe", "arena": "bg_storm_roof", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["amethya", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Donnerhexe"},
			S._narr("Sturm über den Dächern. Medea sucht in den Wolken nach einer Spur des Siegels. Sie findet stattdessen eine junge Hexe, die mit Blitzen jongliert."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("amethya", "Die große Medea! Ich habe von deiner Bibliothek gehört. Elftausend Bücher, und du lässt niemanden rein. Warum?"),
			S._say("hero", "Weil Wissen gefährlich ist, Kind."),
			S._say("amethya", "Blitze auch. Trotzdem lernt man sie. Ich habe mir alles selbst beigebracht, weil keine Meisterin mich nehmen wollte. Du hättest mich nehmen können."),
			S._say("hero", "Ich nehme keine Schüler. Schüler wollen Dinge wissen. Und dann gehen sie und tun Dummheiten damit."),
			S._say("amethya", "Du kannst alles, Medea – außer loslassen. Das sagt jeder. Du suchst den Zauber für deinen Bruder, oder? Lilith hat es überall herumerzählt."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 0.8),
			{"t": "choice", "text": "Was antwortet Medea?", "options": [
				{"label": "Es zugeben", "flag": "sorceress_medea_admit", "steps": [
					S._say("hero", "Ja. Ich suche ihn seit zwanzig Jahren. Ich habe alles gelernt, nur um diesen einen Satz zu finden."),
					S._say("amethya", "Danke, dass du ehrlich bist. Trotzdem: Lilith ist eine Falle. Ich halte dich auf, wenn ich muss.")]},
				{"label": "Es leugnen", "flag": "sorceress_medea_deny", "steps": [
					S._say("hero", "Gerüchte. Ich suche Wissen. Nichts weiter. Geh mir aus dem Weg."),
					S._say("amethya", "Du lügst schlecht für jemanden, der so viel weiß. Ich lasse dich nicht zu ihr.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "amethya"], "goal": "STERNE GEGEN DONNER!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "sorceress_medea_admit", "steps": [
				S._say("amethya", "Du hättest mich mit einem Wort erledigen können. Du hast gezögert. Weil ich jung bin. Wie dein Bruder damals?"),
				S._say("hero", "Er war siebzehn. Er hat auch immer zu viel geredet."),
			], "else": [
				S._say("amethya", "Du bist stärker als ich. Aber du kämpfst, als wärst du schon tot. Geh nicht zu ihr, Medea."),
			]},
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Medea geht trotzdem. In der Nacht spricht sie den Namen auf dem Zettel aus. Der Boden öffnet sich wie ein Mund."),
		]},
		{"id": "sorceress_medea_3", "title": "Der Preis", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lilith", 3.0, -1], ["iason", 1.0, -1], ["amethya", -4.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Preis"},
			S._narr("Hinter dem Höllentor ein Marktplatz aus Spiegeln. In jedem Spiegel eine Erinnerung, die jemand verkauft hat."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lilith", "Medea. Ich habe auf dich gewartet. Der Zauber existiert. Ich kann dir deinen Bruder zurückgeben. Heute. Jetzt."),
			S._say("lilith", "Der Preis ist klein: dein Spiegelbild. Du wirst dich nie wieder sehen. Aber ihn wirst du jeden Tag sehen."),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("iason", "Schwester? Bist du das? Du bist so alt geworden. Warum hast du mich nicht aus dem Wasser gezogen?"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.2),
			S._say("hero", "Das … das ist nicht er. Er hätte gelacht. Er hätte gesagt: Du hast mich nicht rausgezogen, weil ich zu schwer war, Dummkopf."),
			S._say("lilith", "Kleinigkeiten. Er wird lernen, wieder zu lachen. Unterschreib."),
			S._say("iason", "Schwester. Bitte. Es ist so kalt im Wasser. Hol mich raus. Diesmal schaffst du es."),
			S._narr("Medeas Hand zittert über dem Vertrag. Zwanzig Jahre hat sie auf diesen Moment gewartet. Und jetzt, wo er da ist, fühlt er sich falsch an. Wie ein Zauber mit einem Fehler in der dritten Zeile."),
			S._say("hero", "Nein. Wer ohne Spiegelbild lebt, sieht nur noch andere. Und nie, was er selbst getan hat. Das ist kein Leben. Für keinen von uns."),
			{"t": "vanish", "who": 2},
			S._music("boss"),
			{"t": "branch", "flag": "sorceress_medea_admit", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("amethya", "Ich habe gesagt, ich halte dich auf. Jetzt halte ich sie auf. Zusammen sind wir lauter als jeder Höllenmarkt!"),
				{"t": "fight", "cast": ["hero", "amethya", "lilith"], "goal": "ZERBRICH DEN SPIEGELMARKT!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "fight", "cast": ["hero", "lilith"], "goal": "ZERBRICH DEN SPIEGELMARKT!", "lives": [3, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Die Spiegel zerspringen. Hunderte verkaufte Erinnerungen flattern wie Vögel nach Hause. Iasons Bild ist nicht darunter. Es war nie hier."),
		]},
		{"id": "sorceress_medea_4", "title": "Eine Geschichte für die Flamme", "arena": "bg_moon_temple", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["spiegel", 2.0, -1], ["amethya", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Eine Geschichte für die Flamme"},
			S._narr("Im Mondtempel, am Ufer des Meeres, in dem Iason ertrank. Medea hat elftausend Zauber im Kopf. Keiner davon hilft ihr jetzt."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("spiegel", "Ich bin das, was du verkaufen wolltest. Dein Spiegelbild. Ich sehe, was du getan hast. Du hast im Sturm gezögert. Eine Sekunde."),
			S._say("spiegel", "Ohne Macht bist du nur eine Frau, die jemanden vermisst."),
			S._say("hero", "Ja. Genau das bin ich. Ich habe zwanzig Jahre Macht gesammelt, um das nicht sein zu müssen."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "spiegel"], "goal": "SIEH DICH SELBST AN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 1.0),
			S._narr("Medea zieht eine einfache Kerze aus der Tasche. Sie zündet sie an. Mit einem Streichholz. Ohne Formel."),
			S._say("hero", "Iason. Du hast immer zu viel geredet. Du hast Fische gehasst und bist trotzdem jeden Tag schwimmen gegangen. Du hast falsch gepfiffen."),
			S._narr("Sie erzählt der Flamme eine Geschichte. Die ganze Nacht. Es ist der einzige Zauber, der wirkt: Er bringt niemanden zurück. Aber er bringt sie zurück."),
			S._cam("two", 0, 1.6, 2),
			S._say("amethya", "Die Bibliothek. Darf ich jetzt mal rein?"),
			S._say("hero", "Du darfst. Alle dürfen. Bücher sind zum Lesen da. Nicht zum Verstecken."),
			S._say("amethya", "Und du? Was liest du als Nächstes?"),
			S._say("hero", "Gar nichts. Ich gehe schwimmen. Iason hat es mir hundertmal angeboten. Ich hatte immer etwas Wichtigeres zu lesen."),
			S._narr("Am nächsten Morgen steht die Erzmagierin knietief im kalten Meer und lacht, weil es so furchtbar kalt ist. Die Kerze am Ufer brennt noch."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Medea · Der eine Zauber"},
			S._narr("Relikt erhalten: Die Kerze ohne Zauber  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
