extends RefCounted
## Legende: DON VALENTE, DER UNTERWELTPATE – „Der Koffer“.
## Don Valente kam mit einem Koffer in die Stadt. Heute gehört ihm jede Straße – aber kein einziger Freund.
## Der SWAT-Agent jagt ihn seit zwanzig Jahren, Mammon verlangt seine Seele als Anzahlung, und im Koffer
## liegt noch immer, was er vor dreißig Jahren mitgebracht hat.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der Koffer",
	"summary": "Don Valente kam mit einem Koffer in die Neonstadt. Heute gehört ihm jede Straße – aber kein einziger Freund. Er vertraut niemandem, weil er weiß, wie leicht man Menschen kaufen kann.",
	"relic": "Der alte Koffer",
	"relic_text": "Ein abgewetzter Lederkoffer mit einem Riss im Futter. Darin: ein Foto von zwei Jungen auf einer Hafenmauer und ein Brief, der nie abgeschickt wurde.",
}

const CAST := {
	"hero": {"preset": "don_valente", "name": "DON VALENTE", "title": "Der Unterweltpate", "color": "d4af37"},
	"agent": {"preset": "swat_specops", "name": "SWAT-AGENT", "title": "Jagt ihn seit zwanzig Jahren", "color": "64748b"},
	"sal": {"preset": "bruno", "name": "SAL", "title": "Sein Jugendfreund", "color": "fbbf24"},
	"capo": {"preset": "pirate_captain", "name": "BIANCA", "title": "Seine rechte Hand", "color": "57534e"},
	"rivale": {"preset": "vanguard_soldier", "name": "RIVALISIERENDE FAMILIE", "title": "Will seine Straßen", "color": "7f1d1d"},
	"mammon": {"boss": "mammon", "name": "MAMMON", "title": "Der letzte Geschäftspartner", "color": "eab308"},
	"pate": {"preset": "don_valente", "name": "DER PATE", "title": "Was er aus sich gemacht hat", "color": "1c1917"},
}

static func chapters() -> Array:
	return [
		{"id": "don_valente_1", "title": "Ein Angebot", "arena": "neon_metropolis", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["rivale", 2.8, -1], ["capo", -2.6, 1]]),
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "DON VALENTE · DER KOFFER", "sub": "Kapitel I – Ein Angebot"},
			S._narr("Vor dreißig Jahren stieg ein junger Mann mit einem Lederkoffer aus dem Nachtzug. Er hatte kein Geld, keine Freunde, keinen Plan. Nur den Koffer."),
			S._narr("Heute gehört Don Valente jede Straße der Neonstadt. Er hat Polizisten gekauft, Richter, Bürgermeister. Den Koffer trägt er immer noch. Niemand weiß, was drin ist."),
			S._cam("two", 0, 1.4, 1),
			S._say("rivale", "Valente. Die Familie Marconi übernimmt ab heute die Hafenstraße. Das ist keine Bitte."),
			S._say("hero", "Ich mache euch ein Angebot, das ihr nicht ablehnen könnt: Geht nach Hause. Lebend."),
			S._say("capo", "Don, die haben mehr Leute als wir."),
			S._say("hero", "Bianca. Ich habe nicht mehr Leute. Ich habe bessere Geschütze."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.3, "text": "LEIBWÄCHTER-GESCHÜTZ!", "flag": "don_valente_turret",
				"success": [S._narr("Ein goldenes Geschütz klappt aus dem Bürgersteig. Die Marconis gehen in Deckung.")],
				"fail": [S._narr("Das Geschütz klemmt. Der Don wirft einen Blick auf seine Uhr. Unpünktlichkeit hasst er.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "rivale"], "goal": "VERTEIDIGE DIE HAFENSTRASSE!", "lives": [3, 2], "qte": "don_valente_turret", "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.6, 2),
			S._say("capo", "Gut gemacht, Don. Wie immer. Darf ich Sie etwas fragen? In zehn Jahren habe ich Sie nie lachen sehen. Haben Sie Freunde?"),
			S._say("hero", "Freunde kann man kaufen, Bianca. Ich weiß das, ich habe sehr viele gekauft. Darum habe ich keine."),
			S._say("capo", "Und mich? Haben Sie mich auch gekauft?"),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ich zahle dir das Dreifache eines Polizistengehalts. Was glaubst du?"),
			S._narr("Bianca antwortet nicht. Sie geht. Der Don sieht ihr nach und umklammert den Koffer ein bisschen fester."),
		]},
		{"id": "don_valente_2", "title": "Zwanzig Jahre", "arena": "bg_night_market", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["agent", 2.5, -1], ["sal", 5.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Zwanzig Jahre"},
			S._narr("Auf dem Nachtmarkt, zwischen dampfenden Garküchen, steht der Mann, der ihn seit zwanzig Jahren jagt. Er trägt keine Uniform. Er sieht müde aus."),
			S._cam("two", 0, 1.6, 1),
			S._say("agent", "Zwanzig Jahre jage ich dich, Don. Heute endet es. Ich habe Beweise. Echte. Die man nicht kaufen kann."),
			S._say("hero", "Jeder Beweis hat einen Preis, Agent. Nenn mir deinen."),
			S._say("agent", "Ich habe den Geburtstag meiner Tochter verpasst, um dich zu jagen. Drei Jahre lang. Das ist mein Preis. Ich habe ihn schon bezahlt."),
			S._cam("close", 0, 1.4),
			S._narr("Zum ersten Mal seit Jahren weiß der Don nicht, was er bieten soll. Gegen jemanden, der schon alles verloren hat, hilft kein Geld."),
			{"t": "choice", "text": "Was tut Don Valente?", "options": [
				{"label": "Ein ehrliches Wort", "flag": "don_valente_honest", "steps": [
					S._say("hero", "Ich habe auch etwas verpasst, Agent. Den Tag, an dem mein bester Freund aus dem Gefängnis kam. Ich hatte ihn verraten, um meine erste Straße zu kaufen."),
					S._say("agent", "… Warum erzählst du mir das?"),
					S._say("hero", "Weil man es niemandem erzählen kann, den man bezahlt. Kämpfen wir. Ehrlich, ohne Geschütze.")]},
				{"label": "Ein Angebot machen", "flag": "don_valente_bribe", "steps": [
					S._say("hero", "Eine Million. Und ein Haus am Meer. Für dich und deine Tochter. Zerreiß die Akte."),
					S._say("agent", "Sie will kein Haus am Meer. Sie will einen Vater am Meer. Das kannst du nicht kaufen.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "agent"], "goal": "DER PATE GEGEN DAS GESETZ!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "don_valente_honest", "steps": [
				S._say("agent", "Dein Freund. Wie hieß er?"),
				S._say("hero", "Sal. Er wartet seit zwanzig Jahren in einer Garküche am Hafen, dass ich mich entschuldige. Ich bin nie hingegangen."),
				S._say("agent", "Dann geh. Ich verhafte dich morgen. Heute hast du einen Termin."),
			], "else": [
				S._say("agent", "Du kämpfst wie jemand, der glaubt, dass alles einen Preis hat. Was kostet es, dich selbst zurückzukaufen, Don?"),
			]},
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Der Koffer in seiner Hand wird schwer. Schwerer als je zuvor. Eine Stimme aus dem Futter flüstert: Ich kaufe ihn dir ab. Alles. Für einen guten Preis."),
		]},
		{"id": "don_valente_3", "title": "Das letzte Geschäft", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["mammon", 3.0, -1], ["agent", -4.0, 1], ["capo", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Das letzte Geschäft"},
			S._narr("Eine Stadt aus Gold, tief unter der Neonstadt. Hier wird alles gehandelt: Kronen, Seelen, Jahre. Am größten Tisch sitzt der Einzige, der dem Don noch etwas anbieten kann."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("mammon", "Valente. Mein Lieblingsschüler. Du hast eine ganze Stadt gekauft. Jetzt kaufe ich dich. Deine Seele als Anzahlung. Dafür gehört dir die Welt."),
			S._say("mammon", "Und den Koffer. Den nehme ich auch. Was immer da drin ist – es macht dich weich."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Die Welt. Und alles, was ich dafür geben muss, ist das Letzte, was nicht verkauft ist."),
			S._say("mammon", "Du kaufst Menschen, weil du nicht weißt, wie man sie gewinnt. Warum also nicht gleich alle kaufen?"),
			S._say("hero", "Weil ich genau weiß, was ich dann bekomme. Leute, die nicken. Ich habe dreißig Jahre Leute gekauft, die nicken. Keiner davon hat mich je angerufen, nur um zu reden."),
			S._music("boss"),
			{"t": "branch", "flag": "don_valente_honest", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("agent", "Ich verhafte dich morgen, Don. Bis dahin bist du mein Zeuge. Und Zeugen lasse ich mir nicht wegkaufen."),
				{"t": "fight", "cast": ["hero", "agent", "mammon"], "goal": "VERKAUF NICHT DEINE SEELE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("capo", "Sie haben gefragt, ob Sie mich gekauft haben. Nein, Don. Ich bin geblieben, weil ich dachte, irgendwann lachen Sie mal. Ich warte immer noch."),
				{"t": "fight", "cast": ["hero", "capo", "mammon"], "goal": "VERKAUF NICHT DEINE SEELE!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Mammons Tisch kippt. Gold rollt über den Boden. Der Don hebt keine einzige Münze auf. Er hebt nur den Koffer auf."),
			S._say("mammon", "Du lässt das Gold liegen? DU? Valente, was ist aus dir geworden?"),
			S._say("hero", "Das, was ich vor dreißig Jahren war, bevor ich aus dem Zug stieg. Ein Junge mit einem Koffer."),
			S._say("hero", "Und dieser Junge hat noch eine Rechnung offen. Nicht bei dir. Bei einem Freund."),
		]},
		{"id": "don_valente_4", "title": "Die Garküche am Hafen", "arena": "pirate_galleon", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["pate", 2.0, -1], ["sal", 4.5, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Die Garküche am Hafen"},
			S._narr("Der Hafen, an dem er vor dreißig Jahren ankam. Hinter dem alten Schiff an der Mole: eine kleine Garküche. Licht brennt. Jemand ist noch wach."),
			S._cam("close", 0, 1.4),
			S._narr("Der Don öffnet zum ersten Mal seit dreißig Jahren den Koffer. Darin: ein Foto. Zwei Jungen auf einer Hafenmauer. Und ein Brief, adressiert an Sal. Nie abgeschickt."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("pate", "Mach den Koffer zu. Ein Pate entschuldigt sich nicht. Ein Pate bietet an. Biete ihm Geld. Ein Restaurant. Eine Straße. Er wird annehmen. Alle nehmen an."),
			S._say("hero", "Genau das ist das Problem. Alle nehmen an. Und keiner bleibt."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "pate"], "goal": "BESIEGE DEN PATEN IN DIR!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("sal", "Valente. Dreißig Jahre. Du bist alt geworden."),
			S._say("hero", "Sal. Ich habe kein Angebot. Ich habe nur einen Brief, den ich dir vor zwanzig Jahren hätte geben sollen. Darin steht: Es tut mir leid."),
			S._narr("Sal nimmt den Brief. Er liest ihn nicht. Er steckt ihn ein. Dann schiebt er dem Don eine Schale Nudeln hin."),
			S._say("sal", "Drei Münzen. Wie früher. Für dich mache ich keine Ausnahme."),
			S._say("hero", "Ich habe keine drei Münzen dabei. Ich hatte seit Jahren kein Kleingeld mehr in der Tasche."),
			S._say("sal", "Dann schuldest du mir was. Komm morgen wieder und bezahl. Und übermorgen auch."),
			S._narr("Und Don Valente, dem jede Straße der Stadt gehört, lacht. Zum ersten Mal seit dreißig Jahren. Es kostet nichts."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Don Valente · Der Koffer"},
			S._narr("Relikt erhalten: Der alte Koffer  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
