extends RefCounted
## Legende: KAIRO, DER STURMMÖNCH – „Das Gelächter des Sturms“.
## Dreißig Jahre Stille auf dem Gipfel, bis der Sturm an den Berg klopft. Eine Novizin mit zu viel
## Energie, eine Teehändlerin, die alles anschreibt, ein Erzengel mit einer einzigen Frage – und ein
## Deckel auf einem kochenden Kessel. Erzählt in drei Atemzügen; zeigt, woher die Solarflut kommt.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Das Gelächter des Sturms",
	"summary": "Seit dreißig Jahren schluckt Kairo jeden Sonnenaufgang und schweigt. Dann klopft der Sturm an den Berg – und der Mönch merkt, dass er dabei lächelt.",
	"relic": "Meister Dorns Teekessel",
	"relic_text": "Ein verbeulter Eisenkessel ohne Deckel. Er pfeift, bevor es zu spät ist – und das ist sein ganzes Geheimnis.",
}

const CAST := {
	"hero": {"preset": "kairo", "name": "KAIRO", "title": "Der Sturmmönch", "color": "7dd3fc"},
	"mina": {"preset": "shira", "name": "MINA", "title": "Novizin mit zu viel Energie", "color": "f472b6"},
	"sirra": {"preset": "albion", "name": "SIRRA", "title": "Tochter des Nordsturms", "color": "a5f3fc"},
	"pela": {"preset": "brunhild", "name": "OMA PELA", "title": "Teehändlerin vom Nachtmarkt", "color": "fde68a"},
	"varakh": {"preset": "varakh", "name": "VARAKH", "title": "Eroberer dreier Reiche", "color": "ef4444"},
	"michael": {"boss": "michael", "name": "MICHAEL", "title": "Erzengel der einen Frage", "color": "fff7c2"},
	"deckel": {"preset": "kairo", "name": "KAIRO, DER DECKEL", "title": "Dreißig Jahre Schweigen", "color": "475569"},
}

static func chapters() -> Array:
	return [
		{"id": "kairo_1", "title": "Das Klopfen", "arena": "frozen_summit", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["mina", -4.0, 1], ["sirra", 3.5, -1]]),
			{"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAIRO · DAS GELÄCHTER DES STURMS", "sub": "Kapitel I – Das Klopfen"},
			S._pose(0, "Crouch", 1.0),
			S._narr("Auf dem höchsten Gipfel des Nordens sitzt ein Mönch. Seit dreißig Jahren. Er hat sich nicht bewegt, sagen sie im Tal. Nicht einmal zum Niesen."),
			S._narr("Jeden Morgen atmet er den ersten Sonnenstrahl ein. Und atmet ihn nie wieder aus."),
			{"t": "move", "who": 1, "x": -2.6, "time": 1.0},
			S._cam("two", 0, 1.6, 1),
			S._say("mina", "Meister Kairo! Tee! Diesmal mit nur einem Blatt Schnee drin. Ich habe geübt!"),
			S._say("hero", "Mina. Du bist die Treppe wieder hochgerannt. Neunhundert Stufen, und du schnaufst wie ein Blasebalg."),
			S._say("mina", "Ihr hört alles und bewegt Euch nie. Das ist unheimlich, wisst Ihr das?"),
			S._say("hero", "Dreißig Jahre Stille, Kind. Irgendwann hört man sogar, wie der Schnee überlegt, wohin er fällt."),
			{"t": "fx", "kind": "shake"},
			S._narr("Da klopft es. Nicht an einer Tür – hier oben gibt es keine. Es klopft an den Berg selbst."),
			S._music("tense"),
			{"t": "appear", "who": 2},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 2, 1.4),
			S._pose(2, "Roar", 1.0),
			S._say("sirra", "Mönch! Ich bin Sirra, Tochter des Nordsturms. Dreißig Jahre umkreise ich diesen Gipfel. Dreißig Jahre stiehlst du mir die Sonne."),
			S._say("sirra", "Jeden Morgen schluckst du den ersten Strahl. Gib zurück, was du hortest – oder ich wehe dich von deinem Kissen."),
			S._cam("two", 0, 1.4, 2),
			S._say("hero", "Ich horte nichts. Ich bewahre auf. Das ist ein Unterschied, den nur alte Männer verstehen."),
			S._say("mina", "Meister … Eure Hände. Ihr ballt die Fäuste. Und – lächelt Ihr etwa?"),
			S._cam("close", 0, 1.2),
			S._narr("Dreißig Jahre hat Kairo die Stille gesucht. Jetzt, wo der Sturm klopft, spürt er sie zum ersten Mal: im Bauch, kurz vor dem ersten Schlag."),
			{"t": "qte", "kind": "sequence", "keys": ["block", "jump", "standard"], "time": 3.0, "text": "ERSTER ATEM: EIN – HALTEN – AUS!", "flag": "kairo_breath1",
				"success": [S._pose(0, "Charge", 0.8), S._narr("Kairo atmet ein. Der Wind um ihn wird still, als hätte er Angst, ihn zu stören.")],
				"fail": [S._narr("Kairo verschluckt sich an einer Schneeflocke. Dreißig Jahre Übung – und ausgerechnet jetzt.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "sirra"], "goal": "ZEIG DEM STURM DEINE RUHE!", "lives": [2, 2], "qte": "kairo_breath1", "ai": 4},
			S._music("hope"),
			S._cam("two", 0, 1.4, 2),
			S._pose(2, "Dazed", 1.0),
			S._say("sirra", "Wie … Ein Mann, der kaum atmet, schlägt zu wie ein Gewitter."),
			S._say("hero", "Ich atme. Nur langsamer als du. Jeden Morgen eine Sonne in die Lunge, dreißig Jahre lang. Irgendwo muss das Licht ja hin."),
			S._narr("So entstand die Solarflut: aus elftausend verschluckten Morgen, die nur auf einen Grund warten, wieder hinauszudürfen."),
			S._say("sirra", "Unten im Tal klopft schon ein anderer an deine Tür, Mönch. Einer, der lauter ist als ich. Mal sehen, ob du dann noch lächelst."),
			{"t": "fx", "kind": "flash"},
			{"t": "vanish", "who": 2},
			S._cam("two", 0, 1.4, 1),
			S._pose(0, "Rise", 1.0),
			S._say("mina", "Meister. Ihr steht. Ihr STEHT! Dreißig Jahre, und Ihr steht einfach auf!"),
			S._say("hero", "Meine Knie knacken wie ein Lagerfeuer. Hol die Sandalen, Mina. Wir gehen ins Tal."),
		]},
		{"id": "kairo_2", "title": "Tee auf dem Nachtmarkt", "arena": "bg_night_market", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["mina", -3.4, 1], ["pela", 1.0, -1], ["varakh", 8.0, -1]]),
			{"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Tee auf dem Nachtmarkt"},
			S._narr("Der Nachtmarkt im Tal riecht nach Ingwer, Rauch und gerösteten Nüssen. Als Kairo zuletzt hier war, brannten die Laternen noch mit Öl."),
			S._cam("two", 0, 1.6, 2),
			S._say("pela", "Na, sieh mal an! Der Bergmönch. Dreißig Jahre weg, und dann kommst du ausgerechnet zur Hauptgeschäftszeit."),
			S._say("hero", "Pela. Du bist alt geworden."),
			S._say("pela", "Und du bist immer noch kein bisschen höflicher. Setz dich. Der Tee geht aufs Haus – du hast meinen Stand damals vor den Banditen gerettet."),
			S._say("mina", "Ihr habt gekämpft, Meister? Früher? Richtig mit Fäusten?"),
			S._say("pela", "Kind, der hat sich mit jedem geprügelt, der ihm schief vorkam. Deshalb ist er ja auf den Berg. Zum Abkühlen."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Abkühlen dauert eben, Pela. Bei manchen Kesseln dreißig Jahre."),
			{"t": "fx", "kind": "shake"},
			S._music("tense"),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": 3.5, "time": 1.2},
			S._cam("two", 0, 1.4, 3),
			S._say("varakh", "Da bist du, Sturmmönch. In drei Reichen erzählt man von dem Mann, der auf einem Berg sitzt und den Wind verprügelt."),
			S._say("varakh", "Dreißig Jahre gesessen, Mönch? Ich habe in der Zeit drei Reiche erobert. Steh auf und zeig mir, wofür du so lange gebraucht hast."),
			S._say("hero", "Ich bin heute schon einmal aufgestanden. Das hat für einen Tag gereicht."),
			S._say("pela", "Nicht an meinem Stand! Wer hier kämpft, bezahlt die Tassen!"),
			{"t": "choice", "text": "Varakh steht vor dir. Der Tee dampft.", "options": [
				{"label": "Ihm Tee einschenken", "flag": "kairo_tea", "steps": [
					S._say("hero", "Setz dich, Prinz. Ein Reich erobert man in Jahren. Einen Tee trinkt man in einem Atemzug. Probier das Schwierigere."),
					S._say("varakh", "Du bietest MIR Tee an? … Er ist zu heiß. Den hast du absichtlich zu heiß gemacht!"),
					S._say("hero", "Nein. Du bist nur zu ungeduldig.")]},
				{"label": "Die Faust ballen", "flag": "kairo_fist", "steps": [
					S._pose(0, "Charge", 0.8),
					S._say("hero", "Drei Reiche. Dann hast du dreimal öfter gekämpft als ich. Lass sehen, ob du dabei etwas gelernt hast."),
					S._say("mina", "Meister! Ihr grinst schon wieder!"),
					S._say("varakh", "Endlich. Einer, der sich nicht hinter seinem Tee versteckt.")]},
			]},
			S._music("fight"),
			{"t": "branch", "flag": "kairo_fist", "steps": [
				{"t": "fight", "cast": ["hero", "varakh"], "goal": "SCHLAG ZU, BEVOR DER TEE KALT WIRD!", "lives": [2, 2], "time": 70, "mods": {"0": {"power": 1.25, "kb": 1.15}}, "ai": 6},
			], "else": [
				{"t": "fight", "cast": ["hero", "varakh"], "goal": "BLEIB GELASSEN, BEVOR DER TEE KALT WIRD!", "lives": [2, 2], "time": 70, "mods": {"0": {"kb": 0.8}, "1": {"power": 1.15}}, "ai": 5},
			]},
			S._music("hope"),
			S._cam("two", 0, 1.4, 3),
			S._pose(3, "HitReact", 0.8),
			S._say("varakh", "Das war kein Sieg, Mönch. Das war … ein Unentschieden mit Tee."),
			S._say("hero", "Bei mir zählt das als Sieg. Komm wieder, wenn dir dein viertes Reich genauso wenig Ruhe lässt wie die ersten drei."),
			{"t": "move", "who": 3, "x": 9.0, "time": 1.0},
			{"t": "branch", "flag": "kairo_fist", "steps": [
				S._cam("two", 0, 1.2, 2),
				S._say("pela", "Drei Tassen, ein Hocker und mein Ladenschild. Ich schreib's an, Mönch."),
				S._say("hero", "Schreib es an. Ich habe ohnehin noch dreißig Jahre Zinsen offen."),
			], "else": [
				S._cam("two", 0, 1.2, 1),
				S._say("pela", "Kein einziger Scherbenhaufen. Kairo, du wirst ja doch noch erwachsen."),
				S._say("mina", "Und er hat sogar noch Tee übrig!"),
			]},
			S._cam("low", 0, 1.8),
			S._narr("Nachts sieht Mina, wie ihr Meister auf seine Hände schaut. Sie zittern nicht vor Angst. Sie zittern, weil sie mehr wollen."),
			{"t": "fx", "kind": "flash"},
			S._narr("Und hoch über dem Markt öffnet sich der Himmel wie ein Auge, das eine Frage hat."),
		]},
		{"id": "kairo_3", "title": "Die Frage des Erzengels", "arena": "heaven_spheres", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["michael", 3.0, -1], ["sirra", -5.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Frage des Erzengels"},
			S._narr("Kairo meditiert unter freiem Himmel – und der Himmel zieht ihn einfach nach oben. Sphäre um Sphäre, bis die Sterne unter seinen Füßen liegen."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.6),
			S._pose(1, "Rise", 1.0),
			S._say("michael", "Mönch. Ich bin Michael. Ich trage das Schwert, damit andere es nicht tragen müssen. Und ich habe eine einzige Frage an dich."),
			S._say("michael", "Warum ballt ein Mann des Friedens so gern die Fäuste?"),
			{"t": "branch", "flag": "kairo_fist", "steps": [
				S._say("michael", "Ich sah dich auf dem Nachtmarkt. Der Tee war noch heiß, und du hast schon gegrinst."),
			], "else": [
				S._say("michael", "Ich sah dich auf dem Nachtmarkt. Du hast Tee eingeschenkt. Aber unter dem Tisch war deine Hand eine Faust."),
			]},
			S._cam("two", 0, 1.4, 1),
			S._pose(0, "Crouch", 1.0),
			S._say("hero", "Weil … weil ich es gern tue. Da. Jetzt ist es raus. Dreißig Jahre Schweigen, nur um mir das nicht sagen zu müssen."),
			S._say("michael", "Die Wahrheit ist ein Anfang. Nun zeig mir, ob du kämpfen kannst, ohne dass der Kampf dich führt."),
			S._say("michael", "Bevor die Sphären sich einmal gedreht haben, will ich meine Antwort. Danach schicke ich dich zurück – mit oder ohne."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.4, "text": "ZWEITER ATEM: HALTE DAS LICHT!", "flag": "kairo_breath2",
				"success": [S._pose(0, "Charge", 0.8), S._narr("Elftausend Morgen glühen in Kairos Brust. Er hält sie fest – noch.")],
				"fail": [S._narr("Das Licht drängt zu früh hinaus. Kairo hustet goldenen Staub.")]},
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "michael"], "goal": "ANTWORTE, BEVOR DIE SPHÄREN SICH DREHEN!", "lives": [3, 1], "time": 150, "qte": "kairo_breath2", "ai": 6},
			S._music("hope"),
			S._cam("two", 0, 1.4, 1),
			S._say("michael", "Du hast gelacht. Mitten im Kampf, als meine Klinge an deinem Ohr vorbeiging. Hast du es gemerkt?"),
			S._say("hero", "Ich … habe ich?"),
			S._say("michael", "Kein Zorn. Freude. Wer aus Freude kämpft, braucht keinen Deckel. Er braucht ein Ventil, das niemanden verbrennt."),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -3.4, "time": 0.8},
			S._cam("two", 0, 1.2, 2),
			S._say("sirra", "Erzengel! Der Mönch gehört dem Sturm. Ich bin noch nicht fertig mit ihm."),
			S._say("michael", "Dann geh mit ihm, Tochter des Windes. Ein Sturm, der zuhört, ist seltener als ein Engel, der lacht."),
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "vanish", "who": 1},
			S._narr("Michael lacht. Es klingt wie Glocken, die zu lange geschwiegen haben. Dann fällt Kairo – sanft wie ein Blatt – zurück durch die Sphären."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Sirra. Mal ehrlich. Hast du mich eben aufgefangen?"),
			S._say("sirra", "Ich habe dich zufällig gestreift. Bild dir nichts ein, Mönch."),
		]},
		{"id": "kairo_4", "title": "Der kochende Kessel", "arena": "bg_dojo", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["deckel", 2.0, -1], ["mina", -3.8, 1], ["sirra", -6.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der kochende Kessel"},
			S._narr("Das alte Kloster am Fuß des Gipfels. Hier hat Kairo als Junge gelernt – und als junger Mann einen Mitschüler so hart geschlagen, dass er nie zurückkam."),
			S._cam("two", 0, 1.6, 2),
			S._say("mina", "Darum seid Ihr auf den Berg gegangen. Nicht wegen der Stille."),
			S._say("hero", "Wegen des Kessels. Meister Dorn hatte hier einen eisernen Teekessel. Er sagte: Kairo, du bist dieser Kessel. Dann legte er einen Deckel drauf."),
			S._pose(0, "Crouch", 1.0),
			S._cam("close", 0, 1.4),
			S._narr("Kairo hebt den alten Kessel vom kalten Herd. Drinnen brodelt etwas, schwarz wie verbrannter Tee."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._music("tense"),
			S._cam("two", 0, 1.6, 1),
			S._say("deckel", "Du hast mich dreißig Jahre gehalten. Ich bin deine Ruhe. Der Deckel auf dem kochenden Topf."),
			S._say("deckel", "Nimm mich ab, und du verbrennst wieder jemanden. Wie damals. Bleib sitzen. Bleib still. Bleib zu."),
			S._say("hero", "Weißt du, was ein Kessel ohne Ventil macht, Deckel? Er platzt. Ich bin nicht ruhig. Ich bin nur kurz vor dem Pfeifen."),
			{"t": "qte", "kind": "mash", "keys": ["special"], "count": 14, "time": 3.0, "text": "DRITTER ATEM: LASS DEN DAMPF RAUS!", "flag": "kairo_breath3",
				"success": [{"t": "fx", "kind": "flash"}, S._narr("Kairo atmet aus. Zum ersten Mal seit dreißig Jahren. Ein Strahl Sonnenlicht schießt durch das Dach.")],
				"fail": [S._narr("Kairo hält die Luft an, aus alter Gewohnheit. Der Deckel drückt ihn in die Knie.")]},
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "deckel"], "goal": "NIMM DEN DECKEL AB!", "lives": [2, 3], "damage": {"0": 25}, "qte": "kairo_breath3", "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 2.0),
			S._pose(0, "Beam", 1.2),
			S._narr("Die Solarflut bricht aus ihm heraus – nicht als Waffe. Als Morgen. Elftausend Sonnenaufgänge auf einmal, und das ganze Tal wird golden."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": -3.0, "time": 0.8},
			S._cam("two", 0, 1.4, 3),
			S._say("sirra", "Du hast sie losgelassen. Alle Sonnen. Mönch, du Idiot – der Himmel brennt orange!"),
			S._say("mina", "Meister … Ihr … Ihr lacht ja!"),
			S._cam("close", 0, 1.4),
			S._pose(0, "Victory", 1.0),
			S._narr("Kairo lacht. Laut, mit offenem Mund, zum ersten Mal seit dreißig Jahren, bis ihm die Tränen kommen. Und der Sturm legt sich, um zuzuhören."),
			S._say("hero", "Mina, ab morgen trainieren wir. Mit Fäusten. Danach Tee. Und wenn einer wütend wird, lachen wir so lange, bis es vorbei ist."),
			S._say("mina", "Und der Berg? Euer Kissen?"),
			S._say("hero", "Das Kissen bekommt Sirra. Sie hängt da oben doch sowieso den ganzen Tag herum."),
			S._say("sirra", "… Es ist ein sehr weiches Kissen."),
			S._cam("sky", 0, 3.0),
			S._narr("Seitdem hört man im Norden manchmal ein Lachen im Wind. Dann sagen die Leute im Tal: Der Mönch und der Sturm streiten wieder. Und sie setzen Tee auf."),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Kairo · Das Gelächter des Sturms"},
			S._narr("Relikt erhalten: Meister Dorns Teekessel  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
