extends RefCounted
## Legende: PYRAX, DIE GLUTWYVERN – „Leise Glut“.
## Die Tochter der Drachin Vulkara schlüpft zwanzig Jahre nach dem Tod ihrer Mutter. Alles, was sie
## berühren will, verbrennt. Erst eine Frostassassine mit gefrorenem Herz hält ihre Hitze aus –
## und Lilith bietet ihr an, einfach alles brennen zu lassen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Leise Glut",
	"summary": "Pyrax will nur, dass jemand sie festhält. Doch jeder, den sie umarmt, verbrennt. Bis sie jemanden trifft, der kälter ist als ihr Feuer heiß.",
	"relic": "Die gesprungene Eierschale",
	"relic_text": "Ein Stück der Schale, aus der Pyrax schlüpfte. Innen hat jemand mit Reif eine Hand gezeichnet. Sie schmilzt nie.",
}

const CAST := {
	"hero": {"preset": "pyrax", "name": "PYRAX", "title": "Die Glutwyvern", "color": "fb923c"},
	"glaciem": {"preset": "glaciem", "name": "GLACIEM", "title": "Die Frostassassine", "color": "7dd3fc"},
	"templar": {"preset": "dragon", "name": "TEMPLAR", "title": "Der Mann, der ihre Mutter erschlug", "color": "f97316"},
	"hunter": {"preset": "vanguard_soldier", "name": "DRACHENJÄGER", "title": "Kopfgeld auf Schuppen", "color": "94a3b8"},
	"lilith": {"boss": "lilith", "name": "LILITH", "title": "Die ewige Flamme", "color": "e11d48"},
	"pyre": {"preset": "pyrax", "name": "DER SCHEITERHAUFEN", "title": "Alles, was sie je verbrannt hat", "color": "991b1b"},
}

static func chapters() -> Array:
	return [
		{"id": "pyrax_1", "title": "Das erste Frieren", "arena": "volcano_sanctum", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["hunter", 3.5, -1], ["templar", 9.0, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "PYRAX · LEISE GLUT", "sub": "Kapitel I – Das erste Frieren"},
			S._narr("Zwanzig Jahre lag ein Ei im Krater, bewacht von niemandem. Dann brach die Schale, und eine kleine Wyvern blinzelte in die Lava."),
			S._narr("Sie hielt Lava für Wasser und Rauch für Wolken. Erst als sie zum Kraterrand kletterte, lernte sie das Wort, das alles ändert: kalt."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 0.8),
			S._say("hero", "Brrr! Was ist DAS? Die Luft beißt! Mama? Mama, wo bist du?"),
			S._narr("Unten im Tal sah sie Lichter. Kleine warme Punkte. Häuser, in denen Menschen sich aneinander drängten."),
			S._say("hero", "Die halten sich fest, damit sie nicht frieren. Das will ich auch!"),
			{"t": "appear", "who": 1},
			{"t": "move", "who": 1, "x": 2.5, "time": 0.8},
			S._cam("two", 0, 1.4, 1),
			S._say("hunter", "Da ist sie. Vulkaras Brut. Ihre Schuppen bringen in der Stadt einen Sack Gold. Jede einzelne."),
			S._say("hero", "Hallo! Bist du warm? Darf ich mich an dich drücken?"),
			S._say("hunter", "Bleib mir vom Leib, Feuerechse!"),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.3, "text": "AUSWEICHEN!", "flag": "pyrax_dodged",
				"success": [S._narr("Das Netz fliegt ins Leere. Pyrax weiß nicht, warum der Mann so wütend ist.")],
				"fail": [S._narr("Das Netz trifft – und verbrennt in einem Atemzug. Der Jäger flucht.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "hunter"], "goal": "ENTKOMME DEM DRACHENJÄGER!", "lives": [3, 2], "qte": "pyrax_dodged", "ai": 3},
			S._music("sad"),
			S._cam("close", 0, 1.4),
			S._narr("Der Jäger flieht. Wo er stand, brennt das Gras. Wo Pyrax hintritt, brennt es auch."),
			S._say("hero", "Ich wollte doch nur … warum geht alles kaputt, was ich anfasse?"),
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("templar", "Weil du die Tochter deiner Mutter bist. Geh zurück in den Krater, Kleine. Dort kannst du niemandem wehtun."),
			S._narr("Sie wusste nicht, wer der Ritter war. Aber sein Schwert roch nach Zuhause."),
		]},
		{"id": "pyrax_2", "title": "Die Frau aus Eis", "arena": "frozen_summit", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["glaciem", 2.0, -1]]),
			{"t": "vanish", "who": 1},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Die Frau aus Eis"},
			S._narr("Pyrax flog weg vom Tal. So weit, bis der Schnee nicht mehr schmolz, wenn sie landete. Dort oben war niemand, den sie verbrennen konnte."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Hier ist es still. Und kalt. Und leer. Leer ist schlimmer als kalt."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("glaciem", "Du schmilzt meinen Gipfel, Wyvern. Ich habe hundert Jahre gebraucht, um ihn so still zu kriegen."),
			S._say("hero", "Du … du dampfst nicht! Ich stehe direkt neben dir und du dampfst nicht!"),
			S._say("glaciem", "Mein Herz ist aus Eis. Ich habe es selbst gefroren. Dein Feuer kommt nicht hinein. Nichts kommt hinein."),
			{"t": "choice", "text": "Was tut Pyrax?", "options": [
				{"label": "Sie umarmen", "flag": "pyrax_hugged", "steps": [
					S._narr("Pyrax springt, bevor sie es sich anders überlegt, und schlingt die Flügel um die Frau aus Eis."),
					S._say("glaciem", "Was – lass das! Du – ich – … das war … nicht unangenehm. Trotzdem: Wehr dich, ich will wissen, ob du stark bist!")]},
				{"label": "Abstand halten", "flag": "pyrax_distant", "steps": [
					S._say("hero", "Ich komme nicht näher. Ich habe gelernt, dass das keine gute Idee ist."),
					S._say("glaciem", "Kluges Tier. Dann zeig mir aus der Ferne, was dein Feuer kann.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "glaciem"], "goal": "FEUER GEGEN EIS!", "lives": [2, 2], "ai": 4},
			S._music("hope"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "pyrax_hugged", "steps": [
				S._say("glaciem", "Du hast mich zweimal getroffen, und ich bin nicht geschmolzen. Nur ein bisschen … warm geworden. Erzähl das niemandem."),
				S._say("hero", "Darf ich wiederkommen? Morgen? Und übermorgen?"),
				S._say("glaciem", "Wenn du vorher anklopfst. Mit Abstand."),
			], "else": [
				S._say("glaciem", "Du hältst dich zurück. Das erkenne ich. Ich halte mich seit hundert Jahren zurück."),
				S._say("hero", "Hilft es?"),
				S._say("glaciem", "Nein. Aber man gewöhnt sich daran. Das ist schlimmer."),
			]},
			{"t": "fx", "kind": "shake"},
			S._narr("Da bebt der Gipfel. Tief unter ihnen brüllt der Vulkan, und eine süße Stimme ruft Pyrax beim Namen."),
		]},
		{"id": "pyrax_3", "title": "Die ewige Flamme", "arena": "hell_flames", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lilith", 3.0, -1], ["glaciem", -4.0, 1], ["templar", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die ewige Flamme"},
			S._narr("Die Stimme zieht sie durch den Krater hinab, tiefer als jede Lava, bis in einen Kreis aus Feuer, das nie heruntergebrannt ist."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lilith", "Kleine Flamme. Hier unten brennt alles. Niemand weicht vor dir zurück, weil alle schon brennen."),
			S._say("lilith", "Bleib bei mir. Lass die Welt oben auch brennen. Dann bist du nie wieder die Einzige, die glüht."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Wenn alle brennen … dann kann mich auch keiner mehr festhalten. Dann gibt es niemanden mehr, der festhält."),
			S._say("lilith", "Festhalten ist überschätzt. Man kann auch einfach zusammen brennen."),
			S._say("hero", "Nein. Ich will nicht, dass alle so werden wie ich. Ich will lernen, leiser zu brennen."),
			S._music("boss"),
			{"t": "branch", "flag": "pyrax_hugged", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("glaciem", "Du hast nicht angeklopft, bevor du verschwunden bist. Ich bin trotzdem gekommen. Mein Eis hält das aus."),
				{"t": "fight", "cast": ["hero", "glaciem", "lilith"], "goal": "LÖSCHE DIE EWIGE FLAMME!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("templar", "Ich habe deiner Mutter das Leben genommen, Kleine. Ich lasse nicht zu, dass dieser Dämon dir deines nimmt."),
				{"t": "fight", "cast": ["hero", "templar", "lilith"], "goal": "LÖSCHE DIE EWIGE FLAMME!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Lilith weicht zurück in ihre Flammen. Zum ersten Mal hat jemand ihr Feuer abgelehnt, weil er ein eigenes hat."),
			S._say("hero", "Leiser. Ich muss lernen, leiser zu brennen."),
		]},
		{"id": "pyrax_4", "title": "Leise Glut", "arena": "bg_aurora_peaks", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["pyre", 2.0, -1], ["glaciem", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Leise Glut"},
			S._narr("Unter dem Polarlicht übt Pyrax jede Nacht. Ausatmen, ohne Flamme. Landen, ohne Krater. Es klappt fast nie."),
			S._cam("two", 0, 1.6, 2),
			S._say("glaciem", "Du presst. Du versuchst, das Feuer festzuhalten. Feuer will man nicht festhalten. Man lässt es atmen."),
			S._say("hero", "Woher weißt du das? Du hast doch Eis."),
			S._say("glaciem", "Mit Eis ist es genauso. Ich habe es nur zu spät gemerkt."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("pyre", "Erinnerst du dich an das Gras? An die Scheune? An den Zaun der Kinder? Ich bin alles, was du verbrannt hast."),
			S._say("pyre", "Du wirst nie leise. Du bist ein Scheiterhaufen mit Flügeln."),
			S._say("hero", "Vielleicht. Aber ich bin ein Scheiterhaufen, der übt."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "pyre"], "goal": "ÜBERWINDE DEINEN SCHEITERHAUFEN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Idle", 1.0),
			S._narr("Pyrax atmet aus. Keine Flamme. Nur ein warmer Hauch, der das Polarlicht flimmern lässt."),
			S._cam("two", 0, 1.6, 2),
			S._narr("Glaciem streckt die Hand aus. Pyrax legt ihre Kralle hinein. Es zischt. Es dampft. Niemand lässt los."),
			{"t": "branch", "flag": "pyrax_hugged", "steps": [
				S._say("glaciem", "Siehst du? Man muss nicht aufhören zu brennen. Man muss nur jemanden finden, der es aushält."),
			], "else": [
				S._say("glaciem", "Abstand halten war klug. Jetzt ist es Zeit für etwas Dummes. Komm her."),
			]},
			S._say("hero", "Du bist warm geworden, Glaciem. Nur ein kleines bisschen."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Pyrax · Leise Glut"},
			S._narr("Relikt erhalten: Die gesprungene Eierschale  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
