extends RefCounted
## Legende: RAVENNA, DIE SCHATTENKLINGE – „Kein Spiegelbild“.
## Eine Gruselgeschichte von der anderen Seite: Ravenna ist der Geist, vor dem das Dorf Angst hat.
## Sie trug die Laterne in der Glasgrube, als der Stollen einstürzte, und kam als Kristall zurück,
## der jedes Licht schluckt. Hier lernt sie den Schattenschritt – von Schatten zu Schatten.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Kein Spiegelbild",
	"summary": "Ravenna trug die Laterne in der Glasgrube, als der Stollen einstürzte. Jetzt ist sie zurück – als Kristall, der jedes Licht schluckt, und ein ganzes Dorf flieht vor ihr.",
	"relic": "Die erloschene Grubenlaterne",
	"relic_text": "Ravennas alte Laterne. Sie brennt nicht mehr – aber wer hineinsieht, sieht keinen Schatten, sondern eine kleine Flamme.",
}

const CAST := {
	"hero": {"preset": "specter", "name": "RAVENNA", "title": "Die Schattenklinge", "color": "9b30ff"},
	"jorik": {"preset": "tobi", "name": "JORIK", "title": "Ein Junge mit einer Kerze", "color": "fde68a"},
	"oda": {"preset": "sorceress_medea", "name": "ODA", "title": "Die blinde Laternenmacherin", "color": "fbbf24"},
	"geist1": {"preset": "skeleton_reaper", "name": "GRUBENGEIST", "title": "Was in der Glasgrube blieb", "color": "64748b"},
	"geist2": {"preset": "nekra", "name": "GRUBENGEISTIN", "title": "Was in der Glasgrube blieb", "color": "64748b"},
	"vesperin": {"preset": "vampire_lord", "name": "GRAF VESPERIN", "title": "Sammler von Schatten", "color": "b91c1c"},
	"haldor": {"preset": "kettenwart", "name": "HALDOR", "title": "Steiger der Glasgrube, Joriks Vater", "color": "94a3b8"},
	"lilith": {"boss": "lilith", "name": "LILITH", "title": "Die Mutter der Nacht", "color": "7e22ce"},
	"spiegel": {"preset": "specter", "name": "SPIEGEL-RAVENNA", "title": "Was bleibt, wenn man das Licht abzieht", "color": "e2e8f0"},
}

static func chapters() -> Array:
	return [
		{"id": "specter_1", "title": "Die Frau ohne Spiegelbild", "arena": "blood_moon", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["jorik", 2.6, -1], ["oda", 8.0, -1], ["geist1", 9.0, -1], ["geist2", 10.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("sad"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "RAVENNA · KEIN SPIEGELBILD", "sub": "Kapitel I – Die Frau ohne Spiegelbild"},
			S._narr("Unter dem Dorf Gramfeld liegt die Glasgrube. Dort wachsen Kristalle, so klar, dass man darin das eigene Herz schlagen sieht."),
			S._narr("Vor einem Jahr stürzte der Stollen ein. Ravenna trug die Laterne vorneweg. Die Laterne ging aus. Ravenna kam nicht zurück."),
			S._narr("Bis heute Nacht. Unter dem Blutmond steigt eine Gestalt aus violettem Kristall aus dem Schacht. Wo sie geht, wird es dunkler."),
			S._cam("close", 0, 1.8),
			S._say("hero", "Gramfeld. Die Bäckerei hat einen neuen Anstrich. Der Brunnen quietscht immer noch. Ich bin … zu Hause?"),
			S._pose(0, "Crouch", 0.8),
			S._narr("Sie beugt sich über den Brunnen. Im Wasser spiegelt sich der rote Mond. Nur sie nicht."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Block", 0.6),
			S._say("jorik", "Bleib weg! Ich hab eine Kerze! Geister mögen keine Kerzen, das weiß jeder!"),
			S._say("hero", "Ich bin kein Geist, Kleiner. Ich bin … ich weiß nicht genau, was ich bin. Aber ich mag Kerzen."),
			S._say("jorik", "Dann sag deinen Namen. Geister wissen ihre Namen nicht mehr."),
			S._say("hero", "Ravenna. Ich habe die Laterne in der Glasgrube getragen."),
			S._pose(1, "HitReact", 0.8),
			S._say("jorik", "Die Laternenträgerin? Mein Vater war da unten. Haldor. Du solltest ihn rausbringen. Du hast es versprochen!"),
			S._cam("close", 0, 1.2),
			S._narr("Die Kerze in Joriks Hand flackert. Dann neigt sich die Flamme zu Ravenna hin – und versickert in ihrem Kristall wie Wasser im Sand."),
			S._say("hero", "Nein … das wollte ich nicht. Ich schlucke Licht. Ich schlucke einfach alles Licht."),
			{"t": "fx", "kind": "shake"},
			S._music("tense"),
			S._narr("Aus dem Schacht kriecht etwas hinterher. Grubengeister – angelockt von der neuen Dunkelheit."),
			{"t": "appear", "who": 3}, {"t": "appear", "who": 4},
			{"t": "move", "who": 3, "x": 4.2, "time": 1.2},
			{"t": "move", "who": 4, "x": 5.6, "time": 1.4},
			S._cam("two", 1, 1.0, 3),
			S._say("geist1", "Dunkel. Endlich dunkel. Das Kind zuerst. Kinder leuchten so laut."),
			{"t": "qte", "kind": "sequence", "keys": ["block", "special"], "time": 3.0, "text": "SCHATTENSCHRITT – ZWISCHEN SIE UND DAS KIND!", "flag": "specter_step",
				"success": [
					{"t": "vanish", "who": 0},
					{"t": "fx", "kind": "ink", "who": 1},
					{"t": "move", "who": 0, "x": 3.3, "time": 0.05},
					{"t": "appear", "who": 0},
					{"t": "face", "who": 0, "facing": 1},
					S._narr("Ravenna tritt in ihren eigenen Schatten – und kommt aus Joriks Schatten wieder heraus. Genau zwischen ihm und den Geistern.")],
				"fail": [
					S._pose(0, "HitReact", 0.6),
					{"t": "move", "who": 0, "x": 1.6, "time": 0.6},
					S._narr("Der Schritt durch die Dunkelheit gelingt nur halb. Ravenna stolpert, Kristallsplitter klirren übers Pflaster.")]},
			S._say("hero", "So also geht das. Wo ein Schatten ist, bin ich auch. Hört gut zu, ihr da: Dieses Kind steht in MEINEM Schatten."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "geist1", "geist2"], "goal": "BESCHÜTZE JORIK, BEVOR DER MOND SINKT!", "lives": [2, 1, 1], "teams": [0, 1, 1], "time": 80, "qte": "specter_step", "ai": 3},
			S._music("calm"),
			{"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": 4.6, "time": 1.4},
			S._cam("two", 0, 1.4, 2),
			S._say("oda", "Ich rieche Kristallstaub und Angst. Und eine Stimme, die ich zwölf Jahre lang jeden Morgen gehört habe. Ravenna?"),
			S._say("hero", "Oda. Du bist die Einzige, die nicht wegläuft."),
			S._say("oda", "Ich bin blind, Kind. Für mich warst du immer schon eine Stimme. Und die ist ganz dieselbe geblieben."),
			S._say("oda", "Ich habe deine Laterne gebaut. Wenn du Licht schluckst, dann bleibt es vielleicht irgendwo in dir. Wir finden heraus, wo."),
			S._cam("low", 0, 1.8),
			S._narr("Jorik sagt nichts mehr. Aber als Ravenna geht, stellt er eine neue Kerze ins Fenster. Wie jede Nacht. Für seinen Vater."),
		]},
		{"id": "specter_2", "title": "Der Schattenmarkt", "arena": "bg_night_market", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["oda", -3.4, 1], ["vesperin", 2.8, -1], ["jorik", 6.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Schattenmarkt"},
			S._narr("Jede Blutmondnacht öffnet am Rand von Gramfeld ein Markt, der auf keiner Karte steht. Hier verkauft man Schatten. Am Stück oder im Glas."),
			S._cam("two", 0, 1.6, 1),
			S._say("oda", "Halt dich an meinem Arm fest. Hier sieht keiner richtig hin – der einzige Markt, auf dem ich im Vorteil bin."),
			S._say("hero", "Jorik ist uns gefolgt. Ich spüre seine Kerze. Wie ein warmer Punkt im Nacken."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 2},
			S._cam("close", 2, 1.2),
			S._pose(2, "Summon", 1.0),
			S._say("vesperin", "Willkommen! Graf Vesperin, Sammler von Schatten, Kenner der Dunkelheit. Und du, Liebes … du bist ein ganzer Kristall voll davon."),
			S._say("vesperin", "Kristall und Dunkelheit, Liebes – wir zwei gehören zusammen. Ich gebe dir einen Ehrenplatz. Mittlere Vitrine, gute Beleuchtung."),
			S._say("hero", "Ich schlucke Beleuchtung. Deine Vitrine wäre in fünf Minuten finster."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": 4.2, "time": 0.8},
			S._cam("two", 2, 1.0, 3),
			S._say("jorik", "Lass mich los, du Fledermaus mit Halskrause! Das ist die Kerze für meinen Vater!"),
			S._say("vesperin", "Eine Kerze, die seit einem Jahr für einen Toten brennt. So ein Licht ist selten. Das stelle ich gleich neben dich."),
			S._cam("two", 0, 1.2, 2),
			S._say("vesperin", "Ein Tausch, Laternenträgerin: Du kommst in meine Sammlung, der Junge geht nach Hause. Sonst behalte ich beide."),
			{"t": "choice", "text": "Wie holt Ravenna Jorik zurück?", "options": [
				{"label": "Schluck jedes Licht des Marktes", "flag": "specter_dark", "steps": [
					S._say("hero", "Du willst Dunkelheit, Graf? Hier ist sie. Alle."),
					{"t": "fx", "kind": "ink", "who": 0},
					S._narr("Alle Lampen des Marktes erlöschen auf einmal. Auch Joriks Kerze. Im Finstern lacht nur eine – und es ist nicht Vesperin.")]},
				{"label": "Trag Joriks Kerze", "flag": "specter_light", "steps": [
					S._say("hero", "Gib mir die Kerze, Jorik. Ich trage sie. Diesmal lasse ich sie nicht ausgehen."),
					S._pose(0, "Charge", 1.0),
					S._narr("Die Flamme beißt in den Kristall wie Säure. Ravenna schluckt sie nicht. Sie hält sie fest. Es tut weh – und sie lässt nicht los.")]},
			]},
			S._narr("Der Blutmond steht hinter dem Grafen. In seinem Licht ist Vesperin schwerer zu treffen als ein Gedanke."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "vesperin"], "goal": "KEINE VITRINE FÜR DICH!", "lives": [2, 2], "mods": {"1": {"power": 1.15, "kb": 0.85}}, "ai": 5},
			S._music("calm"),
			S._pose(2, "Defeat", 1.2),
			S._cam("two", 0, 1.4, 3),
			{"t": "branch", "flag": "specter_light", "steps": [
				S._say("jorik", "Du hast sie nicht ausgehen lassen. Du … du bist wirklich die Laternenträgerin."),
				S._say("hero", "Eine schlechte. Aber ich übe."),
			], "else": [
				S._say("jorik", "Es war so dunkel. DU warst so dunkel. Bist du sicher, dass du kein Geist bist?"),
				S._say("hero", "Nein, Jorik. Sicher bin ich mir nicht."),
			]},
			S._cam("close", 2, 1.2),
			S._say("vesperin", "Närrin. In meinem Katalog steht, wer dich zurückgeholt hat. Sie nennt dich Tochter. Und sie hat deinen Steiger behalten."),
			S._say("oda", "Lilith. Die Mutter der Nacht. Die Bergleute haben früher Brot in den Schacht geworfen, damit sie still bleibt."),
			S._cam("low", 0, 1.8),
			{"t": "branch", "flag": "specter_light", "steps": [
				S._narr("Ravenna sieht an sich herab. Tief drinnen im Kristall glimmt etwas Rotes. Joriks Flamme. Sie brennt weiter."),
			], "else": [
				S._narr("Ravenna sieht an sich herab. Im Kristall ist es still und schwarz. Ganz schwarz."),
			]},
		]},
		{"id": "specter_3", "title": "Die Mutter der Nacht", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["lilith", 3.0, -1], ["haldor", 6.5, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Mutter der Nacht"},
			S._narr("Ravenna steigt in die Glasgrube hinab. Tiefer als der Stollen, tiefer als jede Karte. Unten ist ein See gefroren, und im Eis stehen Schatten."),
			S._narr("Bergleute. Dutzende. Jeder mit erhobener Hand, als hielte er eine Laterne, die es nicht mehr gibt."),
			{"t": "appear", "who": 1},
			{"t": "fx", "kind": "ink", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("lilith", "Meine Tochter. Du hast den Weg nach Hause gefunden."),
			S._say("hero", "Ich bin nicht deine Tochter. Meine Mutter hat Brot gebacken und konnte nicht singen."),
			S._say("lilith", "Ich habe dich gemacht, als dein Licht ausging. Aus dem Dunkel, das du so tapfer getragen hast. Wer sonst wäre deine Mutter?"),
			S._say("lilith", "Bleib. Hier gibt es keine Sonne, die dich beschämt, und keinen Spiegel, der dir fehlt. Ein Reich ohne Sonne. Dein Reich."),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": 5.0, "time": 1.4},
			S._cam("two", 0, 1.4, 2),
			S._say("haldor", "Laternenträgerin … du bist es. Sag Jorik … nein. Sag ihm nichts. Er soll aufhören zu warten."),
			S._say("hero", "Haldor. Du hast im Stollen gesagt: Geh vor, ich halte die Decke. Und dann hast du sie gehalten. Bis zuletzt."),
			S._say("lilith", "Sie bleiben, solange du bleibst. Geh – und mein Eis behält sie alle."),
			{"t": "branch", "flag": "specter_light", "steps": [
				{"t": "fx", "kind": "flash"},
				S._cam("close", 0, 1.4),
				S._narr("Da glüht es in Ravennas Brust. Joriks Flamme – sie hat sie nie geschluckt. Sie hat sie getragen."),
				S._say("hero", "Siehst du das, Mutter der Nacht? Das ist kein Schatten. Das ist ein Versprechen mit Docht."),
				S._narr("Im Eis drehen sich die Bergleute zum Licht. Einer nach dem anderen. Liliths Reich bekommt Risse."),
				S._music("boss"),
				{"t": "fight", "cast": ["hero", "lilith"], "goal": "FÜHR DIE BERGLEUTE ANS LICHT!", "lives": [3, 2], "mods": {"1": {"power": 0.85}}, "ai": 6},
			], "else": [
				S._cam("close", 0, 1.4),
				S._narr("Ravenna sucht in sich nach einem Licht. Da ist keins. Sie hat auf dem Markt alles geschluckt."),
				S._say("hero", "Dann eben ohne Licht. Ich hatte ein Jahr Zeit, das Dunkel kennenzulernen. Ich weiß, wo deine Schatten Lücken haben."),
				{"t": "qte", "kind": "mash", "keys": ["special"], "count": 14, "time": 3.0, "text": "SCHATTENSPRÜNGE – BRICH DAS EIS!", "flag": "specter_ice",
					"success": [{"t": "fx", "kind": "burst", "who": 0}, S._narr("Ravenna springt von Schatten zu Schatten, von Bergmann zu Bergmann – und schlägt bei jedem Sprung einen Riss ins Eis.")],
					"fail": [{"t": "fx", "kind": "shake"}, S._narr("Das Eis hält. Ravenna muss es auf die harte Art versuchen.")]},
				S._music("boss"),
				{"t": "fight", "cast": ["hero", "lilith"], "goal": "BRICH DAS EIS DER MUTTER!", "lives": [2, 2], "mods": {"1": {"power": 1.15}}, "ai": 7, "qte": "specter_ice"},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 1},
			{"t": "vanish", "who": 1},
			S._cam("sky", 0, 2.6),
			S._narr("Das Eis des Sees springt. Die Schatten der Bergleute steigen auf, durch den Schacht hinauf – dorthin, wo in einem Fenster eine Kerze brennt."),
			S._cam("two", 0, 1.4, 2),
			S._say("haldor", "Danke, Laternenträgerin. Jetzt geh vor. Diesmal halte ich nichts mehr. Diesmal gehe ich einfach mit."),
			{"t": "vanish", "who": 2},
			S._cam("close", 0, 1.6),
			S._pose(0, "Dazed", 1.2),
			S._narr("Ravenna bleibt allein zurück. Im blanken Eis sieht sie zum ersten Mal seit einem Jahr eine Gestalt. Aber das Spiegelbild lächelt nicht."),
		]},
		{"id": "specter_4", "title": "Der Regenbogen an der Wand", "arena": "mystic_grove", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["spiegel", 2.2, -1], ["jorik", -3.4, 1], ["oda", -4.6, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der Regenbogen an der Wand"},
			S._narr("Die letzte Stunde vor Sonnenaufgang. Auf der Lichtung über der Grube warten Jorik und Oda. Die Bergleute sind fortgezogen, leicht wie Rauch."),
			S._cam("two", 0, 1.6, 2),
			S._say("jorik", "Mein Vater hat gewunken. Ganz kurz. Ich hab die Kerze ausgemacht. Er braucht sie jetzt nicht mehr."),
			S._say("hero", "Und ich? Wenn die Sonne kommt … ich weiß nicht, was mit Kristall passiert, der Licht schluckt. Vielleicht schluckt er die Sonne. Oder sie ihn."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("spiegel", "Du weißt es genau. Du warst nie lebendig. Du bist nur ein Spiegelbild – das letzte Bild, das die Laterne warf, bevor sie ausging."),
			S._say("spiegel", "Ich bin, was übrig ist. Kein Herz, kein Name, nur Glas. Wenn das Licht kommt, geht es durch dich hindurch. Und dann ist da nichts."),
			S._say("oda", "Hör nicht auf das Glas. Ich habe dich nie gesehen, Ravenna. Und trotzdem wusste ich immer, dass du da bist."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Ein Spiegelbild hat nur so viel Kraft, wie man ihm gibt. Gut. Dann gebe ich dir heute keine."),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.4, "text": "DIE SPIEGELLANZE STICHT – PARIERE!", "flag": "specter_parry",
				"success": [S._pose(0, "Counter", 0.6), S._narr("Lanze gegen Lanze, Kristall gegen Kristall. Es klingt wie eine Glocke.")],
				"fail": [S._pose(0, "HitReact", 0.6), {"t": "fx", "kind": "shake"}, S._narr("Die Spiegellanze trifft. Ein feiner Riss läuft durch Ravennas Schulter.")]},
			S._narr("Ein Leben gegen drei. Aber jedes Mal, wenn Ravenna nicht zurückweicht, wird das Spiegelbild ein bisschen blasser."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "spiegel"], "goal": "GIB DEM SPIEGELBILD KEINE KRAFT!", "lives": [1, 3], "mods": {"1": {"power": 0.7, "kb": 1.25}}, "ai": 8, "qte": "specter_parry"},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("sky", 0, 3.0),
			S._narr("Die Sonne steigt über den Rand der Lichtung. Ihr erster Strahl trifft Ravenna mitten in die Brust."),
			S._narr("Sie schluckt ihn nicht. Der Kristall bricht das Licht – und malt einen Regenbogen an die Wand von Odas Werkstatt."),
			S._cam("two", 0, 1.4, 2),
			{"t": "branch", "flag": "specter_light", "steps": [
				S._say("jorik", "Da! In der Mitte vom Regenbogen – das ist meine Kerzenflamme! Die ist ja immer noch da!"),
				S._say("hero", "Ich hab sie nicht ausgehen lassen, Jorik. Ich hab doch gesagt, ich übe."),
			], "else": [
				S._say("jorik", "Guck! Du bist ja bunt! Ich dachte, in dir ist alles schwarz!"),
				S._say("hero", "Ich auch, Jorik. Ich auch."),
			]},
			S._cam("two", 0, 1.4, 3),
			S._say("oda", "Beschreib ihn mir. Den Regenbogen. Ich will endlich wissen, wie du aussiehst."),
			S._say("hero", "Rot zuerst. Dann Gold, dann Grün. Und ganz am Ende, ganz schmal … ein bisschen Violett. Das bin wohl ich."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Ravenna · Kein Spiegelbild"},
			S._narr("Relikt erhalten: Die erloschene Grubenlaterne  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
