extends RefCounted
## Legende: VARAKH, DER SCHARLACHFÜRST – „Die sechs Namen“.
## Ein Hofdrama in Entscheidungen: eine maskierte Rebellin mit goldenen Augen, ein Mantel aus dem
## Purpur von sieben Häusern, ein alter Kammerdiener, der nichts verbrennt – und sechs Namen, die
## niemand aussprechen darf. Zeigt, wie der jüngste Prinz die Sterne fing (Sternenfall).

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Die sechs Namen",
	"summary": "Varakh hat sechs Geschwister verbannt und ihre Namen verboten. Am Tag seiner Krönung steht eine Rebellin im Thronsaal – mit Augen so golden wie seine.",
	"relic": "Iseks Namensliste",
	"relic_text": "Ein vergilbtes Blatt mit sechs Namen, nie verbrannt. Die Tinte ist an einer Stelle verwischt – dort, wo eine Träne fiel.",
}

const CAST := {
	"hero": {"preset": "varakh", "name": "VARAKH", "title": "Der Scharlachfürst", "color": "dc2626"},
	"isek": {"preset": "kettenwart", "name": "ISEK", "title": "Kammerdiener der sieben Prinzen", "color": "94a3b8"},
	"maske": {"preset": "phoenix", "name": "DIE MASKE", "title": "Anführerin der Rebellen", "color": "f59e0b"},
	"ilva": {"preset": "phoenix", "name": "ILVA", "title": "Die vierte Prinzessin", "color": "fbbf24"},
	"rebell": {"preset": "steel_knight", "name": "REBELL", "title": "Mit gestohlenem Schild", "color": "78716c"},
	"kairo": {"preset": "kairo", "name": "KAIRO", "title": "Der Mönch am Tor", "color": "7dd3fc"},
	"lucifer": {"boss": "lucifer", "name": "LUZIFER", "title": "Der Morgenstern", "color": "fef3c7"},
	"schatten": {"preset": "varakh", "name": "VARAKH, DER EINSAMSTE", "title": "Der Siebte auf sieben Thronen", "color": "7f1d1d"},
}

static func chapters() -> Array:
	return [
		{"id": "varakh_1", "title": "Sieben Throne", "arena": "blood_moon", "stars": 0, "steps": [
			S._stage([["hero", 0.0, 1], ["isek", -2.6, 1], ["maske", 8.5, -1], ["rebell", 9.5, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "VARAKH · DIE SECHS NAMEN", "sub": "Kapitel I – Sieben Throne"},
			S._narr("Unter dem Blutmond wird ein Fürst gekrönt. Im Thronsaal stehen sieben Throne. Sechs davon sind mit schwarzen Tüchern verhängt."),
			S._narr("Varakh war der jüngste von sieben Prinzen. Heute ist er der Einzige, der noch im Saal steht."),
			S._cam("two", 0, 1.6, 1),
			S._say("isek", "Hoheit. Das Protokoll verlangt, dass bei der Krönung die Namen aller Geschwister verlesen werden. Ich habe sie aufgeschrieben. Alle sechs."),
			S._say("hero", "Verbrenn das Blatt, Isek."),
			S._say("isek", "Ich habe Euch die Windeln gewechselt, Hoheit. Euren Brüdern und Schwestern auch. Ich verbrenne gar nichts."),
			S._say("hero", "Dann lies sie leise. In deiner Kammer. Wenn ich schlafe. Ich verbeuge mich vor niemandem – auch nicht vor einer Liste."),
			S._cam("close", 0, 1.4),
			S._narr("Als Kind bekam der siebte Prinz immer das, was übrig blieb. Die kleinste Kammer. Das älteste Pferd. Und den Himmel, wenn die anderen schliefen."),
			S._narr("Also fing er Sterne. Jede Nacht, wenn einer fiel, streckte er die Hände aus. Und eines Nachts – fiel einer hinein."),
			S._pose(0, "Summon", 1.0),
			{"t": "fx", "kind": "burst", "who": 0},
			S._say("hero", "Sie nennen es Sternenfall. Ich nenne es: das Einzige, was mir nie jemand weggenommen hat."),
			{"t": "fx", "kind": "shake"},
			S._music("fight"),
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3},
			{"t": "move", "who": 2, "x": 3.0, "time": 1.0},
			{"t": "move", "who": 3, "x": 4.4, "time": 1.2},
			S._cam("two", 0, 1.2, 2),
			S._say("maske", "Ein Fürst, der die Namen seiner Geschwister verbietet, ist kein Fürst. Er ist ein Dieb mit Krone."),
			S._say("hero", "Und eine Rebellin mit Maske ist nur eine Feige mit Hut. Zwei gegen einen? Wie höflich. Ich hatte mit fünf gerechnet."),
			{"t": "fight", "cast": ["hero", "maske", "rebell"], "goal": "VERTEIDIGE DEN THRON!", "lives": [3, 1, 1], "teams": [0, 1, 1], "ai": 4},
			S._music("tense"),
			S._cam("two", 0, 1.4, 2),
			S._pose(2, "Dazed", 1.0),
			S._narr("Die Maske bekommt einen Riss. Darunter: ein Auge, so golden wie Varakhs eigenes."),
			S._say("isek", "Hoheit … diese Augen. Das ist doch –"),
			S._say("hero", "Schweig, Isek. Es ist eine Rebellin. Nichts weiter."),
			{"t": "choice", "text": "Was tut der neue Fürst mit der Gefangenen?", "options": [
				{"label": "Lass sie gehen", "flag": "varakh_mercy", "steps": [
					S._say("hero", "Geh. Bevor ich es mir anders überlege. Und nimm deinen Hut mit."),
					S._say("maske", "Du erkennst mich. Ich sehe es dir an. Feigling."),
					{"t": "move", "who": 2, "x": 9.0, "time": 1.0},
					{"t": "move", "who": 3, "x": 10.0, "time": 1.0}]},
				{"label": "In den Kerker", "flag": "varakh_cell", "steps": [
					S._say("hero", "In den Kerker. Ohne Maske, ohne Namen. So will es das Gesetz."),
					S._say("maske", "Das Gesetz hast du dir selbst geschrieben, kleiner Bruder."),
					{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}]},
			]},
			S._cam("low", 0, 1.8),
			S._say("isek", "Sie hat Bruder gesagt, Hoheit."),
			S._say("hero", "Sie hat gelogen. Lösch die Fackeln. Der Fürst will schlafen."),
		]},
		{"id": "varakh_2", "title": "Der Mönch am Tor", "arena": "bg_colosseum_dusk", "stars": 1, "steps": [
			S._stage([["hero", -2.5, 1], ["kairo", 2.5, -1], ["isek", -4.0, 1]]),
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Mönch am Tor"},
			S._narr("Einen Monat später reitet Varakh zum Abendturnier der Fürsten. Alle sollen sehen, wer der Größte ist."),
			S._narr("Doch am Tor der Arena sitzt ein Mönch im Schneidersitz. Er versperrt den Weg. Er trinkt Tee."),
			S._cam("two", 0, 1.6, 1),
			S._say("kairo", "Schöner Mantel, Prinz. Ist der schwer?"),
			S._say("hero", "Gewebt aus dem Purpur von sieben Königshäusern. Natürlich ist er schwer. Geh zur Seite, Mönch."),
			S._say("kairo", "Stolz ist ein schwerer Mantel, Prinz. Irgendwann erdrückt er dich. Ich habe dreißig Jahre gebraucht, meinen abzulegen. Meiner war aus Schweigen."),
			S._say("isek", "Er meint es nicht böse, Hoheit. Mönche reden so. Eine Berufskrankheit."),
			S._say("hero", "Ich kenne dich. Kairo, der Mann, der den Sturm verprügelt hat. Ich wollte schon immer wissen, ob du die Geschichten wert bist."),
			S._say("kairo", "Dann zieh den Mantel aus. Sonst kämpfe ich gegen dein Gewand, nicht gegen dich."),
			S._cam("close", 0, 1.2),
			{"t": "choice", "text": "Der Mantel der sieben Häuser:", "options": [
				{"label": "Mantel ablegen", "flag": "varakh_unrobed", "steps": [
					S._pose(0, "Idle", 0.6),
					S._narr("Varakh löst die Spange. Der Purpur fällt in den Staub. Er fühlt sich nackt – und erstaunlich leicht."),
					S._say("hero", "Wenn ich ihn wieder aufhebe, dann selbst. Merk dir das, Mönch.")]},
				{"label": "Mantel anbehalten", "flag": "varakh_robed", "steps": [
					S._pose(0, "Roar", 0.8),
					S._say("hero", "Der Mantel bleibt. Ein Fürst zieht sich nicht aus, weil ein Bettler mit Teetasse es verlangt."),
					S._say("kairo", "Wie du willst. Dann wird es ein langer Abend für deine Schultern.")]},
			]},
			S._music("fight"),
			{"t": "branch", "flag": "varakh_robed", "steps": [
				{"t": "fight", "cast": ["hero", "kairo"], "goal": "KÄMPFE IM MANTEL DER SIEBEN!", "lives": [2, 2], "time": 90, "mods": {"0": {"power": 1.25, "kb": 0.75}}, "ai": 7},
			], "else": [
				{"t": "fight", "cast": ["hero", "kairo"], "goal": "ZEIG, WER DU OHNE MANTEL BIST!", "lives": [2, 2], "mods": {"0": {"kb": 1.15}}, "ai": 6},
			]},
			S._music("hope"),
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Dazed", 1.0),
			S._say("kairo", "Ha! Du kämpfst gut, Prinz. Aber nach jedem Schlag schaust du über die Schulter. Als ob jemand zusieht."),
			S._say("hero", "Es sieht immer jemand zu. Sechs Throne. Jeden Tag."),
			S._say("kairo", "Dann dreh dich doch mal ganz um. Vielleicht winken sie ja."),
			{"t": "branch", "flag": "varakh_robed", "steps": [
				S._cam("two", 0, 1.2, 2),
				S._say("isek", "Hoheit, Ihr schwitzt wie ein Schmied. Darf ich Euch den Mantel abnehmen?"),
				S._say("hero", "Niemals. Sie sollen sehen, dass ich ihn tragen kann."),
			], "else": [
				S._cam("two", 0, 1.2, 2),
				S._say("isek", "Euer Mantel, Hoheit. Soll ich ihn aufheben?"),
				S._say("hero", "Lass ihn liegen. Vielleicht braucht ihn ein Bettler mit Teetasse."),
			]},
			S._cam("low", 0, 1.8),
			S._narr("In der Nacht träumt Varakh von einem Mann aus Licht, der genauso lächelt wie der erste Stern am Abend. Er träumt, dass er fällt."),
		]},
		{"id": "varakh_3", "title": "Der Morgenstern", "arena": "cocytus", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["lucifer", 3.0, -1], ["ilva", -6.0, 1], ["isek", -6.5, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Morgenstern"},
			S._narr("Der Blutmond färbt sich schwarz. Varakh stürzt – durch den Boden des Thronsaals, durch Stein und Feuer, bis hinab in ein Meer aus Eis."),
			S._narr("Ganz unten in der Hölle brennt nichts. Hier ist es kalt. So kalt wie ein Saal mit sechs verhängten Thronen."),
			{"t": "fx", "kind": "flash"},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 2.0),
			S._pose(1, "Rise", 1.2),
			S._say("lucifer", "Kleiner Prinz. Ich bin Luzifer. Auch ich war einmal der Jüngste und der Hellste. Auch ich wollte mich vor niemandem verbeugen."),
			S._say("lucifer", "Du hast sechs Geschwister hinter dir gelassen. Ich einen ganzen Himmel. Wir sind uns gleich, du und ich."),
			S._cam("two", 0, 1.4, 1),
			S._say("lucifer", "Komm an meine Seite. Zwei Throne, nur zwei. Kein Saal voller Tücher. Du wärst nie wieder einsam – nur noch erhaben."),
			S._say("hero", "Zwei Throne, ganz unten im Eis. Das ist kein Angebot. Das ist eine Zelle mit besserem Ausblick."),
			S._say("lucifer", "Du hast gezögert, Prinz. Einen halben Herzschlag lang. Ich habe es gesehen."),
			S._music("boss"),
			{"t": "branch", "flag": "varakh_mercy", "steps": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -0.6, "time": 1.0},
				{"t": "fx", "kind": "burst", "who": 2},
				S._cam("two", 0, 1.2, 2),
				S._say("ilva", "Keinen halben Herzschlag mehr, kleiner Bruder. Du hast mich gehen lassen. Jetzt bin ich dran."),
				S._say("hero", "Ilva. Die Vierte. Du warst die Einzige, die meine Sterne nie ausgelacht hat."),
				S._say("ilva", "Ich habe sie gezählt, alle, die du gefangen hast. Komm. Wir fallen zusammen über ihn her."),
				{"t": "fight", "cast": ["hero", "ilva", "lucifer"], "goal": "BRUDER UND SCHWESTER GEGEN DEN MORGENSTERN!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -3.6, "time": 1.0},
				S._cam("two", 0, 1.2, 3),
				S._say("isek", "Hoheit! Ich bin Euch nachgesprungen. In meinem Alter! Ich bitte um eine Gehaltserhöhung."),
				S._say("isek", "Die Gefangene im Kerker hat mir etwas mitgegeben: Er soll ihren Namen rufen. Dann trifft sein Stern."),
				{"t": "qte", "kind": "sequence", "keys": ["special", "special", "standard"], "time": 3.0, "text": "RUF IHREN NAMEN: IL – VA – !", "flag": "varakh_name",
					"success": [S._say("hero", "ILVA!"), S._narr("Zum ersten Mal seit Jahren spricht er einen der sechs Namen aus. Der Stern in seiner Hand brennt doppelt so hell.")],
					"fail": [S._narr("Der Name bleibt ihm im Hals stecken. Stolz ist ein zäher Knoten.")]},
				{"t": "fight", "cast": ["hero", "lucifer"], "goal": "STÜRZE DEN MORGENSTERN!", "lives": [3, 1], "qte": "varakh_name", "ai": 7},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "flash"},
			S._cam("close", 1, 1.4),
			S._pose(1, "Defeat", 1.0),
			S._say("lucifer", "Du wirst enden wie ich, Prinz. Allein auf dem höchsten Platz. Es sei denn …"),
			S._say("hero", "Es sei denn was?"),
			{"t": "vanish", "who": 1},
			S._cam("close", 0, 1.6),
			S._narr("Doch das Eis hat Luzifer schon verschluckt. Varakh steht in der Kälte, sechs Namen auf der Zunge, die er nicht ausspricht."),
		]},
		{"id": "varakh_4", "title": "Sechs Namen", "arena": "bg_moon_temple", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["isek", -3.6, 1], ["ilva", -7.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Sechs Namen"},
			S._narr("Der Mondtempel, in dem die sieben Prinzen als Kinder Verstecken spielten. Varakh kommt allein. Nur Isek folgt ihm, mit Laterne und einem alten Blatt Papier."),
			S._cam("two", 0, 1.6, 2),
			S._say("isek", "Ich habe es nie verbrannt, Hoheit. Ihr wusstet das."),
			S._say("hero", "Ich wusste es. Ich habe dich jeden Abend darum beneidet, dass du sie lesen darfst."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			S._narr("Er hat sie nicht getötet. Er hat sie verbannt, einen nach dem anderen, in ferne Provinzen – weil jeder von ihnen größer war als er. Dann verbot er ihre Namen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._music("tense"),
			S._cam("two", 0, 1.6, 1),
			S._say("schatten", "Du warst nie der Größte. Du warst nur der Einsamste. Sieben Throne – und du sitzt auf allen, damit keiner neben dir sitzen kann."),
			S._say("schatten", "Sag die Namen, und du bist wieder der Siebte. Der Kleinste. Der mit dem alten Pferd. Willst du das wirklich?"),
			S._say("hero", "Ich will … ich will, dass wieder jemand mit mir Sterne fängt."),
			{"t": "branch", "flag": "varakh_robed", "steps": [
				S._say("schatten", "Dann zieh doch den Mantel aus, den du am Tor nicht ablegen wolltest. Ach nein. Er ist ja längst mit dir verwachsen."),
				S._narr("Der Purpur der sieben Häuser zieht Varakh zu Boden. Er hat ihn zu lange getragen."),
				S._music("boss_final"),
				{"t": "fight", "cast": ["hero", "schatten"], "goal": "BESIEGE DEN EINSAMSTEN – TROTZ DES MANTELS!", "lives": [2, 2], "damage": {"0": 35}, "mods": {"1": {"power": 1.2}}, "ai": 8},
			], "else": [
				S._say("schatten", "Ohne Mantel? Wie mutig. Wie nackt. Wie dumm."),
				S._narr("Ohne den Purpur ist Varakh leicht. Zum ersten Mal kämpft er nicht für einen Thron."),
				S._music("boss_final"),
				{"t": "fight", "cast": ["hero", "schatten"], "goal": "BESIEGE DEN EINSAMSTEN!", "lives": [2, 2], "mods": {"0": {"power": 1.15}}, "ai": 7},
			]},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 2.0),
			S._pose(0, "Crouch", 1.2),
			S._narr("Varakh kniet. Nicht vor einem Herrscher. Vor sechs Namen."),
			S._say("hero", "Corvan. Merek. Sadra. Ilva. Tovin. Jarel."),
			S._narr("Bei jedem Namen fällt draußen eine Sternschnuppe. Sechs Stück, eine nach der anderen, genau über dem Tempel."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": -3.0, "time": 1.2},
			S._cam("two", 0, 1.4, 3),
			{"t": "branch", "flag": "varakh_mercy", "steps": [
				S._say("ilva", "Meinen hast du an vierter Stelle gesagt. Genau richtig. Endlich hältst du dich mal an die Reihenfolge."),
			], "else": [
				S._say("ilva", "Isek hat mich aus dem Kerker gelassen. Er sagte, du würdest heute Nacht etwas Dummes tun. Etwas Gutes, meinte er."),
			]},
			S._say("hero", "Ilva. Hilf mir, sechs Briefe zu schreiben. Ich weiß nicht, wie man anfängt."),
			S._say("ilva", "Man fängt mit Entschuldigung an. Danach wird es leichter. Ein bisschen."),
			S._say("isek", "Ich hole Tinte, Hoheit. Viel Tinte. Und Taschentücher."),
			S._cam("sky", 0, 3.0),
			S._narr("Im Frühling reiten sechs Reiter auf den Palast zu. Im Thronsaal stehen keine sieben Throne mehr – nur ein langer Tisch. Und am Ende ein Platz für den Jüngsten."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Varakh · Die sechs Namen"},
			S._narr("Relikt erhalten: Iseks Namensliste  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
