extends RefCounted
## Legende: DIE DORNENHEXE – „Vierzig Frühlinge“.
## Vierzig Jahre hat niemand an ihr Tor geklopft. Dann zwängt sich ein Mädchen mit einem Korb durch die Dornen,
## eine Kirschkriegerin nagelt einen Brief an ihre Mauer, und Lilith bietet ihr einen Garten, in dem nie wieder
## jemand geht. Hier wird erklärt, warum ihre Dornensaat beißt – und warum die Mauer immer nur nachts wächst.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Vierzig Frühlinge",
	"summary": "Die Dornenhexe hat seit vierzig Jahren keinen Besuch mehr bekommen. Ihre Mauer wächst jede Nacht – und plötzlich klopfen alle gleichzeitig.",
	"relic": "Holms Honigglas",
	"relic_text": "Vierzig Frühlinge lang stand es vor der Mauer. Der Honig darin ist nie verdorben – Honig kann warten.",
}

const CAST := {
	"hero": {"preset": "thorn_witch", "name": "DIE DORNENHEXE", "title": "Hüterin der Dornenmauer", "color": "4ade80"},
	"fenna": {"preset": "lepora", "name": "FENNA", "title": "Das Mädchen mit dem Korb", "color": "fca5a5"},
	"ren": {"preset": "ren", "name": "REN", "title": "Hüterin des alten Kirschbaums", "color": "f9a8d4"},
	"holm": {"preset": "kairo", "name": "HOLM", "title": "Der Imker von früher", "color": "fbbf24"},
	"holm_stein": {"preset": "kairo", "name": "HOLM AUS STEIN", "title": "Liliths Geschenk", "color": "94a3b8"},
	"lilith": {"boss": "lilith", "name": "LILITH", "title": "Gärtnerin der Stille", "color": "be123c"},
	"mauer": {"preset": "thorn_witch", "name": "DIE DORNENMAUER", "title": "Was sie vierzig Jahre gebaut hat", "color": "14532d"},
}

static func chapters() -> Array:
	return [
		{"id": "thorn_witch_1", "title": "Der Korb am Tor", "arena": "mystic_grove", "stars": 0, "steps": [
			S._stage([["hero", 1.6, -1], ["fenna", -7.0, 1]]),
			{"t": "vanish", "who": 1},
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "DIE DORNENHEXE · VIERZIG FRÜHLINGE", "sub": "Kapitel I – Der Korb am Tor"},
			S._narr("Mitten im Nebelwald steht eine Mauer aus Dornen, hoch wie drei Kirchtürme. Die Kinder im Dorf sagen, dahinter wohnt eine Hexe, die Finger frisst."),
			S._narr("Das mit den Fingern stimmt nicht. Den Rest hat sie selbst gepflanzt."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Montag: niemand da. Dienstag: niemand da. Mittwoch … ach, wen interessiert schon Mittwoch."),
			S._say("hero", "Vierzig Jahre ohne Besuch. Ich habe die Wochentage abgeschafft. Sie fühlten sich ohnehin alle gleich an."),
			{"t": "fx", "kind": "shake"},
			S._narr("Da raschelt es in der Mauer. Jemand quetscht sich durch die Dornen. Klein, zerkratzt, mit einem Korb."),
			{"t": "appear", "who": 1},
			{"t": "move", "who": 1, "x": -2.0, "time": 1.4},
			S._cam("two", 0, 1.4, 1),
			S._say("fenna", "Au. Au! AU! Wer pflanzt denn bitte Dornen mit Zähnen?"),
			S._say("hero", "Ich. Damit genau so etwas wie du draußen bleibt. Kehr um, Kind, solange du noch alle zehn Finger hast."),
			S._say("fenna", "Ich heiße Fenna. Meine Oma hat Fieber, seit elf Tagen. Sie sagt, hinter der Mauer wächst eine Rose, die jedes Fieber bricht."),
			S._say("fenna", "Sie sagt auch, früher war das hier der schönste Garten im ganzen Wald. Und dass die Hexe damals gelacht hat."),
			S._cam("close", 0, 1.2),
			S._say("hero", "Deine Oma redet zu viel. Hier wachsen keine Rosen mehr. Nur Dornen. Und die teile ich nicht."),
			S._narr("Das ist gelogen. Ganz hinten im Schatten wächst noch eine einzige rote Rose. Die Hexe gießt sie jeden Morgen. Heimlich – sogar vor sich selbst."),
			S._say("fenna", "Dann kämpfe ich eben darum! Ich hab Oma versprochen, nicht mit leerem Korb heimzukommen!"),
			S._say("hero", "Mut hat sie. Verstand weniger. Na gut, Dornen – zeigt ihr, warum hier niemand bleibt. Aber beißt nicht zu fest."),
			S._pose(0, "Crouch", 1.0),
			S._narr("Die Hexe streut Samen ins Moos. Wo sie landen, springen Dornenfallen auf – Ableger der Rosen, die sie einst für Gäste pflanzte, die nie kamen. Darum beißen sie."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "fenna"], "goal": "VERSCHEUCH SIE – OHNE IHR WEHZUTUN!", "lives": [2, 1], "time": 60, "ai": 2,
				"mods": {"1": {"power": 0.6, "kb": 1.4}}},
			S._music("sad"),
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Dazed", 1.0),
			S._say("fenna", "Ich … geh nicht. Ich kann nicht. Wenn ich ohne Rose heimkomme, wer kocht dann morgen für Oma?"),
			{"t": "choice", "text": "Was tut die Dornenhexe?", "options": [
				{"label": "Gib ihr die letzte Rose", "flag": "thorn_witch_rose", "steps": [
					S._narr("Die Hexe geht nach hinten in den Schatten. Als sie zurückkommt, hält sie die rote Rose. Ihre Hände bluten ein bisschen."),
					S._say("hero", "Nimm. Und erzähl niemandem, dass ich nett war. Ich habe einen Ruf zu verlieren."),
					S._say("fenna", "Danke! Ich komme wieder, ganz bestimmt! Ich bring dir was mit!"),
					S._say("hero", "Das sagen sie alle.")]},
				{"label": "Schick sie fort", "flag": "thorn_witch_closed", "steps": [
					S._say("hero", "Geh nach Hause, Fenna. Lauf, bevor die Mauer sich hinter dir schließt."),
					S._say("fenna", "Du bist genau so, wie alle sagen!"),
					S._narr("Fenna rennt. Die Dornen schließen sich hinter ihr. Ganz hinten im Schatten lässt die rote Rose den Kopf hängen.")]},
			]},
			{"t": "move", "who": 1, "x": -8.0, "time": 1.2},
			{"t": "vanish", "who": 1},
			S._cam("low", 0, 1.8),
			S._narr("In dieser Nacht wächst die Mauer um eine Elle. Das tut sie immer, wenn jemand geht. Die Dornen wachsen nicht, wenn die Hexe wütend ist. Sie wachsen, wenn sie traurig ist."),
			S._say("hero", "Dummes Gestrüpp. Hört nie auf mich."),
		]},
		{"id": "thorn_witch_2", "title": "Der Kirschbaum im Würgegriff", "arena": "bg_jungle_ruins", "stars": 1, "steps": [
			S._stage([["hero", 1.8, -1], ["ren", -7.0, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Kirschbaum im Würgegriff"},
			S._narr("Drei Tagesmärsche östlich, in den Ruinen eines Schreins, steht ein Kirschbaum, der seit dreihundert Jahren blüht. Dieses Jahr nicht."),
			S._narr("Schwarze Ranken liegen um seinen Stamm. Sie kamen unter der Erde, aus dem Westen. Aus dem Nebelwald."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Ich bin nicht freiwillig hier. Jemand hat mir einen Brief an die Mauer genagelt. Mit einem Pfeil. Sehr unhöflich."),
			{"t": "appear", "who": 1},
			{"t": "move", "who": 1, "x": -1.8, "time": 1.0},
			S._cam("two", 0, 1.2, 1),
			S._say("ren", "Der Pfeil war von mir. Du hast meinen Baum verflucht, Hexe. Ich bin gekommen, um ihn zurückzuholen."),
			S._say("hero", "Ich verfluche keine Bäume. Bäume sind die Einzigen, die nie weggehen."),
			S._say("ren", "Dann erklär mir, warum deine Dornen ihn erwürgen! Meine Großmutter hat unter diesen Blüten geheiratet. Meine Mutter auch."),
			S._say("hero", "Ich erkläre gar nichts. Ich wollte nur sagen, dass ich es nicht war. Gut. Gesagt. Ich gehe."),
			S._say("ren", "Du gehst nirgendwohin, solange der Baum nicht atmet!"),
			S._pose(1, "Charge", 0.8),
			{"t": "qte", "kind": "press", "keys": ["block"], "time": 1.3, "text": "DER KIRSCHPFEIL! BLOCKEN!", "flag": "thorn_witch_parry",
				"success": [S._pose(0, "Block", 0.6), S._narr("Eine Dornenranke schnellt hoch und fängt den Pfeil aus der Luft. Ren schnalzt anerkennend mit der Zunge.")],
				"fail": [S._pose(0, "HitReact", 0.6), S._say("hero", "Mein Hut! Das war mein guter Hut!")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "ren"], "goal": "STELL DICH DER KIRSCHKRIEGERIN!", "lives": [2, 2], "qte": "thorn_witch_parry", "ai": 5,
				"mods": {"1": {"power": 1.25, "kb": 0.85}}},
			S._music("sad"),
			S._cam("two", 0, 1.4, 1),
			S._pose(1, "Dazed", 1.0),
			S._say("ren", "Warum ziehen sie sich nicht zurück? Du hast gewonnen. Befiehl es ihnen doch!"),
			S._say("hero", "Ich kann nicht. Sie haben nie auf mich gehört."),
			S._narr("Und dann sagt die Dornenhexe etwas, das sie in vierzig Jahren niemandem gesagt hat."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Sie wachsen, wenn ich traurig bin. Jeder Abend allein – ein neuer Trieb. Ich hab das nie gewollt. Ich hatte nur … sehr viele Abende."),
			S._cam("close", 1, 1.2),
			S._say("ren", "Dann ist mein Baum nicht verflucht. Er wird nur von deinem Heimweh umarmt. Versuch es anders. Nicht mit Befehlen. Erzähl ihnen was Schönes."),
			{"t": "qte", "kind": "mash", "keys": ["special"], "count": 12, "time": 3.0, "text": "ERZÄHL DEN DORNEN WAS SCHÖNES!", "flag": "thorn_witch_bloom",
				"success": [{"t": "fx", "kind": "burst", "who": 0},
					S._narr("Die Hexe erzählt von einem Sommer vor vierzig Jahren. Von Bienen und einem Mann, der zu laut lachte. Die Ranken lockern sich. Eine Blüte springt auf."),
					S._say("ren", "Er blüht! Du hast deinen Dornen etwas erzählt, und mein Baum hat zugehört.")],
				"fail": [S._narr("Die Hexe versucht es. Aber die schönen Erinnerungen tun genauso weh wie die schlechten. Die Ranken lockern sich nur ein kleines Stück."),
					S._say("ren", "Es ist ein Anfang. Ich komme jede Woche und erinnere dich daran.")]},
			{"t": "branch", "flag": "thorn_witch_rose", "steps": [
				S._say("ren", "Übrigens: In meinem Dorf erzählt ein kleines Mädchen jedem, dass die Hexe ihr eine Rose geschenkt hat. Die Oma ist wieder gesund."),
				S._say("hero", "Lügen. Alles Lügen. … Ist sie wirklich gesund?"),
			], "else": [
				S._say("ren", "Übrigens: In meinem Dorf weint ein kleines Mädchen, weil die Hexe sie weggeschickt hat."),
				S._say("hero", "Ich weiß. Ich höre die Mauer nachts wachsen."),
			]},
			S._cam("low", 0, 1.8),
			S._narr("Auf dem Heimweg findet die Hexe eine leere Bienenwabe am Wegrand. Sie bleibt lange davor stehen und weiß nicht, warum ihr Herz so laut klopft."),
		]},
		{"id": "thorn_witch_3", "title": "Der Garten, in dem niemand stört", "arena": "hell_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.4, 1], ["lilith", 3.2, -1], ["holm_stein", 1.2, -1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Der Garten, in dem niemand stört"},
			S._narr("In der kürzesten Nacht des Jahres wachsen die Dornen so tief, dass sie ein Loch in die Unterwelt stechen. Die Hexe fällt hindurch."),
			S._narr("Sie landet weich. In Rosen. Weißen, roten, goldenen. Ein Garten, so schön wie ihrer damals. Und vollkommen still."),
			{"t": "fx", "kind": "ink", "who": 1},
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.2),
			S._say("lilith", "Willkommen, Schwester. Vierzig Jahre Mauer – das nenne ich Hingabe. Hier musst du nie wieder auf jemanden warten. Hier geht niemand."),
			S._say("lilith", "Sieh nur, wer schon auf dich wartet."),
			{"t": "appear", "who": 2},
			S._cam("close", 2, 1.6),
			S._narr("Zwischen den Rosen steht eine Statue aus grauem Stein. Ein Mann mit Imkerhut und einem Lächeln, das zu breit für ein Gesicht ist."),
			S._cam("close", 0, 1.2),
			S._pose(0, "Dazed", 1.0),
			S._say("hero", "Holm. Das ist Holm. Er hat gesagt, er kommt im Frühling wieder. Mit seinen Bienen. Er ist nie gekommen."),
			S._say("lilith", "Jetzt ist er da. Aus Stein, ja. Aber Stein geht nicht weg. Stein verspricht nichts, was er nicht hält. Bleib bei ihm. Für immer."),
			{"t": "move", "who": 0, "x": -0.6, "time": 1.6},
			S._narr("Die Hexe macht einen Schritt auf die Statue zu. Dann noch einen. Ihre Dornen legen sich wie ein Zaun um sie beide."),
			S._cam("two", 0, 1.4, 2),
			S._say("hero", "Aber er lacht nicht. Holm hat immer gelacht. Zu laut, beim Essen, beim Imkern, sogar im Schlaf. Das hier ist nicht er."),
			S._say("hero", "Das ist nur eine Mauer, die aussieht wie er. Und von Mauern, Lilith, verstehe ich mehr als du."),
			S._music("boss"),
			S._say("lilith", "Undankbares Unkraut. Dann wirst du eben selbst zu Stein. Holm – halt sie fest."),
			S._pose(2, "Rise", 0.8),
			{"t": "branch", "flag": "thorn_witch_rose", "steps": [
				{"t": "fx", "kind": "flash"},
				S._narr("Da glimmt etwas in der Tasche der Hexe: ein rotes Rosenblatt. Fenna hat es ihr beim Abschied heimlich hineingesteckt."),
				S._say("hero", "Dieses kleine Biest. Hat mir ein Blatt meiner eigenen Rose dagelassen."),
				S._narr("Wo das Blatt leuchtet, welkt Liliths Garten. Ein verschenkter Dorn ist stärker als ein gestohlener Garten."),
				{"t": "fight", "cast": ["hero", "lilith", "holm_stein"], "goal": "ZERREISS LILITHS GARTEN!", "lives": [3, 1, 1], "teams": [0, 1, 1],
					"mods": {"1": {"power": 0.8}, "2": {"power": 0.7}}},
			], "else": [
				S._narr("Die Hexe ist allein. Wie immer. Aber diesmal ist das Alleinsein ihre Entscheidung – nicht die einer Mauer."),
				{"t": "fight", "cast": ["hero", "lilith", "holm_stein"], "goal": "ZERREISS LILITHS GARTEN!", "lives": [3, 1, 1], "teams": [0, 1, 1], "ai": 6},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 2},
			{"t": "vanish", "who": 2},
			{"t": "vanish", "who": 1},
			S._narr("Die Statue zerspringt. Darin ist nichts. Lilith hatte nie Holm – nur das Bild, das die Hexe sich selbst von ihm gemalt hat."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Dann lebt er vielleicht noch. Irgendwo. Und hat mich einfach … vergessen."),
			S._narr("Das ist schlimmer als Stein. Aber es ist wahr. Die Hexe klettert an ihren eigenen Dornen zurück nach oben."),
		]},
		{"id": "thorn_witch_4", "title": "Vierzig Gläser", "arena": "mystic_grove", "stars": 3, "steps": [
			S._stage([["hero", -1.0, 1], ["mauer", 2.2, -1], ["holm", -7.0, 1], ["fenna", -7.6, 1], ["ren", -8.2, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3}, {"t": "vanish", "who": 4},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Vierzig Gläser"},
			S._narr("Zurück im Nebelwald. Zum ersten Mal will die Hexe hinaus. Und die Mauer lässt sie nicht."),
			S._say("hero", "Mach Platz. Ich habe dich gepflanzt, ich darf dich auch stutzen."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("mauer", "Mich stutzen? Ich BIN du. Jeder Abend allein am Tor. Jedes ‚Er kommt nicht mehr‘. Ich habe nur aufgeschrieben, was du gefühlt hast."),
			S._say("mauer", "Dornen schützen nicht, Liebes. Sie halten dich gefangen. Aber gefangen ist sicher. Draußen könnte dich wieder jemand verlassen."),
			S._say("hero", "Und drinnen verlässt mich jeden Tag ein Stück von mir selbst. Ich hab’s satt. Ich will endlich mal wieder einen Mittwoch."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "mauer"], "goal": "REISS DIE MAUER EIN – DORN UM DORN!", "lives": [1, 3], "ai": 7,
				"mods": {"1": {"power": 0.75}}},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("low", 0, 2.0),
			S._pose(0, "Cast", 1.0),
			S._narr("Die Mauer fällt nicht mit einem Knall. Sie seufzt. Ranke um Ranke legt sich ins Moos wie ein müder Hund."),
			S._narr("Und darunter, wo vierzig Jahre niemand hinsah, stehen Gläser. Reihe um Reihe. Mit Honig gefüllt."),
			S._say("hero", "Vierzig. Es sind vierzig Gläser. Eins für jeden Frühling."),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -3.0, "time": 2.0},
			S._cam("two", 0, 1.6, 2),
			S._say("holm", "Ich hab sie jedes Jahr vor die Mauer gestellt. Ich kam nicht durch, die Dornen waren zu hoch. Also hab ich gewartet. Bin gegangen. Wiedergekommen."),
			S._say("holm", "Meine Augen sind schlecht geworden, Elsbeth. Aber deine Stimme hab ich gleich erkannt. Du schimpfst immer noch wie ein Eichelhäher."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Elsbeth. So hat mich seit vierzig Jahren keiner mehr genannt. Ich dachte, du hättest mich vergessen."),
			S._say("holm", "Vergessen? Ich hab dich jeden Frühling vermisst. Das ist das Gegenteil davon."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": -4.4, "time": 1.2},
			{"t": "branch", "flag": "thorn_witch_rose", "steps": [
				S._say("fenna", "Hexe! Oma fragt, ob du zum Tee kommst. Und das halbe Dorf will deinen Garten sehen. Ich hab ein bisschen angegeben."),
				S._say("hero", "Das halbe Dorf. In meinem Garten. … Sie sollen sich die Schuhe abtreten."),
			], "else": [
				S._say("fenna", "Ich bin wieder da. Ich hab keine Angst mehr vor dir. Nur ein bisschen. Ist die Rose noch da?"),
				S._say("hero", "Ja. Und diesmal nimmst du sie mit. Man muss Dinge verschenken, solange jemand vor der Tür steht."),
			]},
			{"t": "appear", "who": 4},
			{"t": "move", "who": 4, "x": -5.8, "time": 1.2},
			S._say("ren", "Ich hab dir einen Zweig von meinem Kirschbaum mitgebracht. Ich dachte, dein Garten könnte Gesellschaft brauchen."),
			S._cam("sky", 0, 3.0),
			S._narr("Am Morgen öffnet sich zwischen den alten Dornen eine einzige weiße Rose. Ren pflückt sie nicht. Fenna pflückt sie nicht. Sie bleibt."),
			S._narr("Die Dornen sind nicht verschwunden. Aber sie haben jetzt ein Tor. Und das Tor steht offen – besonders mittwochs."),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Die Dornenhexe · Vierzig Frühlinge"},
			S._narr("Relikt erhalten: Holms Honigglas  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
