extends RefCounted
## Legende: DER HÖLLENHUND – „Der Weg nach Hause“.
## Dreitausend Jahre hat er das Tor der Toten bewacht. Dann steht ein lebendiges Kind davor, das
## sich aus einem Krankenhausflur verlaufen hat. Eine Reise rückwärts durch die Unterwelt: ein Fährmann,
## die Jägerin, die ihn großgezogen hat, die Stadt der Gier – und ein Fenster, das sich bei Sonnenaufgang schließt.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der Weg nach Hause",
	"summary": "Ein Kind, das noch atmet, steht am Tor der Toten. Zum ersten Mal in dreitausend Jahren dreht der Höllenhund dem Tor den Rücken zu – und bringt es nach Hause.",
	"relic": "Linas Goldmünze",
	"relic_text": "Eine Münze aus Mammons Stadt, im Halsband getragen. Fährgeld für einen Weg, den er nie mehr allein gehen muss.",
}

const CAST := {
	"hero": {"preset": "reaper_hound", "name": "DER HÖLLENHUND", "title": "Wächter des Totentors", "color": "d6d3d1"},
	"lina": {"preset": "ren", "name": "LINA", "title": "Neun Jahre, verlaufen", "color": "fda4af"},
	"lina_alt": {"preset": "ren", "name": "LINA, ERWACHSEN", "title": "Tierärztin", "color": "fda4af"},
	"obol": {"preset": "skeleton_reaper", "name": "OBOL", "title": "Fährmann am Schwarzen Fluss", "color": "a8a29e"},
	"nyx": {"preset": "nyx", "name": "NYX", "title": "Hüterin der Meute", "color": "7c3aed"},
	"gier1": {"preset": "specter", "name": "GIERIGER SCHATTEN", "title": "Will, was noch warm ist", "color": "334155"},
	"gier2": {"preset": "vampire_lord", "name": "GIERIGER SCHATTEN", "title": "Will, was noch warm ist", "color": "334155"},
	"mammon": {"boss": "mammon", "name": "MAMMON", "title": "Der Herr der goldenen Leine", "color": "facc15"},
	"wachhund": {"preset": "reaper_hound", "name": "DER WACHHUND", "title": "Der Teil von ihm, den nie jemand gestreichelt hat", "color": "57534e"},
}

static func chapters() -> Array:
	return [
		{"id": "reaper_hound_1", "title": "Das Kind am Tor", "arena": "hell_gate", "stars": 0, "steps": [
			S._stage([["hero", -0.5, -1], ["lina", -2.8, 1], ["gier1", 8.0, -1], ["gier2", 9.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "DER HÖLLENHUND · DER WEG NACH HAUSE", "sub": "Kapitel I – Das Kind am Tor"},
			S._narr("Am Tor der Toten gilt eine einzige Regel, und der Höllenhund bewacht sie seit dreitausend Jahren: Wer hindurchgeht, kommt nicht zurück."),
			S._narr("Er hat nie gebellt, nie geschlafen, nie gefragt. Bis eines Nachts etwas vor dem Tor steht, das nach Seife und Kakao riecht."),
			S._cam("two", 0, 1.6, 1),
			S._say("lina", "Hallo, großer Hund. Ich glaub, ich hab mich verlaufen. Ich lag im Krankenhaus, dann war da ein Flur, und jetzt bin ich hier."),
			S._say("hero", "GRRR. Tor. Nicht für dich. Du riechst … lebendig."),
			S._say("lina", "Du bist ja nur Knochen! Frierst du nicht? Du siehst aus wie Krümel. Das war Omas Hund. Der war auch so dünn."),
			S._say("hero", "Nicht Krümel. Wächter. Wächter friert nicht."),
			S._narr("Hinter ihnen regt sich etwas in den Schatten. Lebendige Herzen am Tor sind selten. Und manche hier unten hatten lange nichts Warmes mehr."),
			{"t": "appear", "who": 2}, {"t": "appear", "who": 3},
			{"t": "move", "who": 2, "x": 3.0, "time": 1.2},
			{"t": "move", "who": 3, "x": 4.4, "time": 1.4},
			S._cam("close", 2, 1.2),
			S._say("gier1", "Ein warmes Herz … so lange keins mehr gehabt. Gib es her, Hündchen. Du bewachst doch nur Tote."),
			{"t": "face", "who": 0, "facing": 1},
			S._pose(0, "Roar", 1.0),
			{"t": "fx", "kind": "shake"},
			S._say("hero", "GRRRRRR. Niemand geht hier durch. Und niemand nimmt das Kind."),
			{"t": "qte", "kind": "press", "keys": ["special"], "time": 1.2, "text": "SCHATTENSPRUNG!", "flag": "reaper_hound_leap",
				"success": [S._narr("Der Hund versinkt in seinem eigenen Schatten – und taucht hinter den Gierigen wieder auf.")],
				"fail": [S._narr("Der Sprung kommt zu spät. Kalte Finger streifen Linas Ärmel.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "gier1", "gier2"], "goal": "LASS NIEMANDEN AN LINA HERAN!", "lives": [3, 1, 1], "teams": [0, 1, 1], "time": 75, "qte": "reaper_hound_leap", "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.6, 1),
			S._say("lina", "Du hast mich beschützt! Du bist doch ein Krümel. Ein ganz großer, gruseliger Krümel."),
			S._narr("Das Gesetz verlangt, das Kind durchs Tor zu schicken. Aber das Kind ist nicht tot. Noch nicht. Irgendwo schlägt ein Herz an Maschinen."),
			S._say("hero", "Weg zurück. Über den Fluss. Durch die Stadt aus Gold. Bis zum Licht. Weit. Gefährlich."),
			S._say("lina", "Kommst du mit?"),
			{"t": "face", "who": 0, "facing": -1},
			S._cam("low", 0, 2.0),
			S._narr("Zum ersten Mal in dreitausend Jahren dreht der Höllenhund dem Tor den Rücken zu."),
		]},
		{"id": "reaper_hound_2", "title": "Der Fährmann und die Jägerin", "arena": "blood_moon", "stars": 1, "steps": [
			S._stage([["hero", -1.5, 1], ["lina", -3.0, 1], ["obol", 2.5, -1], ["nyx", 8.0, -1]]),
			{"t": "vanish", "who": 3},
			S._music("calm"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Fährmann und die Jägerin"},
			S._narr("Der Schwarze Fluss fließt unter einem roten Mond. Nur einer setzt über: Obol, der Fährmann, der niemals umsonst rudert."),
			S._cam("two", 0, 1.6, 2),
			S._say("obol", "Sieh an. Der Torhund, weit weg von seinem Tor. Und ein Kind, das noch atmet. Fahrgeld, bitte."),
			S._say("lina", "Ich hab nur einen Kaugummi. Der ist aber schon benutzt."),
			S._say("obol", "Mm. Nein. Aber der Hund hat etwas. Die Glocke an seinem Halsband. Mit ihr ruft die Meute ihn zurück, wenn er sich verläuft."),
			S._say("hero", "Glocke … ist Posten. Ohne Glocke: kein Weg zurück zum Tor. Nie mehr."),
			{"t": "choice", "text": "Was gibt der Höllenhund dem Fährmann?", "options": [
				{"label": "Die Glocke", "flag": "reaper_hound_bell", "steps": [
					S._pose(0, "Crouch", 1.0),
					S._narr("Er senkt den knochigen Kopf. Obol löst die Glocke. Sie klingt ein letztes Mal – dann ist es still an seinem Hals."),
					S._say("hero", "Kein Posten mehr. Nur noch Weg.")]},
				{"label": "Den besten Knochen", "flag": "reaper_hound_bone", "steps": [
					S._say("hero", "Glocke bleibt. Hier. Bester Knochen. Dreitausend Jahre aufgehoben."),
					S._say("obol", "Ein Knochen. Von einem Hund, der selbst aus Knochen ist. Das ist so absurd, dass ich ihn nehme.")]},
			]},
			{"t": "vanish", "who": 2},
			S._narr("Die Fähre legt am anderen Ufer an. Dort wartet jemand mit einer Sense, die im Mondlicht glänzt."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": 3.0, "time": 1.2},
			S._cam("close", 3, 1.2),
			S._say("nyx", "Komm zurück an deinen Posten, Hund. Das Tor wartet nicht. Seit du fort bist, steht es offen, und die Gierigen wandern."),
			S._say("hero", "Kind zuerst. Dann Tor."),
			S._say("nyx", "Ich habe dich als Welpen aus der Asche gezogen. Ich habe dir beigebracht, wem du gehorchst. Sitz."),
			{"t": "branch", "flag": "reaper_hound_bell", "steps": [
				S._say("nyx", "Ich läute nach dir – warum klingt nichts? Wo ist deine Glocke?!"),
				S._say("hero", "Weg. Wie Hund. GRRR."),
				S._music("fight"),
				{"t": "fight", "cast": ["hero", "nyx"], "goal": "KEIN BEFEHL HÄLT DICH – BESIEGE NYX!", "lives": [2, 2], "ai": 6},
			], "else": [
				{"t": "fx", "kind": "shake"},
				S._pose(0, "Dazed", 1.0),
				S._narr("Nyx schlägt mit der Sense gegen die Glocke an seinem Hals. Der Klang reißt an jedem Knochen. Sitz. Gehorch. Bleib."),
				S._say("hero", "Nicht … sitzen. Nicht … jetzt."),
				S._music("fight"),
				{"t": "fight", "cast": ["hero", "nyx"], "goal": "SCHÜTTLE DEN GLOCKENBEFEHL AB!", "lives": [2, 2], "damage": {"0": 35}, "ai": 6},
			]},
			S._music("hope"),
			S._pose(3, "Dazed", 1.0),
			S._cam("two", 0, 1.6, 3),
			S._say("nyx", "Du hast nie gekämpft, um zu gewinnen. Immer nur, um etwas zu beschützen. Das hätte ich merken müssen."),
			S._say("lina", "Bist du seine Mama?"),
			S._say("nyx", "… So etwas in der Art. Eine schlechte. Geh, Hund. Ich halte das Tor, bis du zurück bist. Falls du zurückkommst."),
			S._narr("Hinter dem Fluss beginnt die Stadt aus Gold. Dort wohnt einer, der für alles einen Preis kennt."),
		]},
		{"id": "reaper_hound_3", "title": "Die Leine aus Gold", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.0, 1], ["lina", -3.6, 1], ["mammon", 3.0, -1]]),
			{"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Die Leine aus Gold"},
			S._narr("Die Straßen glänzen. Die Häuser glänzen. Selbst die Pfützen sind aus geschmolzenen Münzen. Lina hält sich die Nase zu: Gold riecht nach gar nichts."),
			{"t": "appear", "who": 2},
			{"t": "fx", "kind": "burst", "who": 2},
			S._cam("sky", 2, 2.4),
			S._say("mammon", "Ein Wachhund ohne Wache! Wie traurig. Weißt du, was du wert bist, Hündchen? Ich weiß es. Ich weiß es von allem."),
			S._say("mammon", "Hier: eine Leine aus purem Gold. Und ein Herr, der niemals stirbt. Nie wieder allein am Tor. Nur sitzen. Und gehören."),
			S._cam("close", 0, 1.6),
			S._narr("Der Hund starrt die Leine an. Dreitausend Jahre ohne eine Hand auf dem Kopf. Die Leine glänzt wie ein Versprechen."),
			S._pose(0, "Crouch", 1.0),
			S._say("lina", "Krümel, nicht! Das ist keine Leine für einen Hund. Das ist eine Kette, die so tut, als wär sie Schmuck!"),
			{"t": "qte", "kind": "mash", "keys": ["grab"], "count": 12, "time": 3.0, "text": "REISS DIE GOLDENE LEINE AB!", "flag": "reaper_hound_free",
				"success": [{"t": "fx", "kind": "flash"}, S._narr("Gold splittert wie Glas. Der Hund schüttelt sich – und Münzen regnen aufs Pflaster.")],
				"fail": [S._narr("Die Leine hält. Er zerrt, bis sie ihm ein Stück Halswirbel abreißt. Dann ist er frei. Schief, aber frei.")]},
			S._say("mammon", "Undankbares Vieh! Dann nehme ich eben das Kind. Ein lebendiges Herz ist mehr wert als diese ganze Stadt!"),
			S._narr("Da sieht Lina, warum der Hund so schnell ist. Er läuft nicht durch die Luft. Er springt von Schatten zu Schatten, wie durch Türen zwischen zwei Welten."),
			S._say("hero", "Hund holt Seelen. Dreitausend Jahre. Jeder Schatten ist Tür. Zweimal beißen, bevor einer blinzelt."),
			S._say("hero", "Gold hat keinen Schatten. Nur Glanz. GRRR. Leicht zu finden."),
			S._narr("Die Toten nennen es das Grabmaul: zwei Sprünge durch die Schattenwelt, so schnell, dass man nur einen sieht."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "mammon"], "goal": "BEISS DICH DURCH DIE GIER – BEVOR LINA VERBLASST!", "lives": [2, 1], "time": 120, "mods": {"1": {"power": 1.25}}, "qte": "reaper_hound_free", "ai": 6},
			S._music("hope"),
			{"t": "fx", "kind": "flash"},
			{"t": "vanish", "who": 2},
			S._cam("two", 0, 1.6, 1),
			S._narr("Mammon zerfällt zu einem Haufen Münzen. Lina hebt eine auf und steckt sie dem Hund ins Halsband."),
			S._say("lina", "Fürs Fährgeld. Falls du mal zurückmusst. Dann musst du nicht wieder deinen Knochen hergeben."),
			S._pose(1, "Dazed", 1.0),
			S._narr("Doch Lina ist blasser als vorher. Durchsichtig an den Rändern. Irgendwo da oben wird die Zeit knapp."),
			S._say("lina", "Krümel … mir ist so kalt."),
			S._say("hero", "Fast da. Hund trägt."),
		]},
		{"id": "reaper_hound_4", "title": "Die Schwelle", "arena": "bg_rain_rooftop", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["lina", -3.2, 1], ["wachhund", 2.0, -1], ["lina_alt", 7.0, -1]]),
			{"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Die Schwelle"},
			S._narr("Das Licht am Ende ist ein Fenster. Dahinter ein Krankenhauszimmer, eine Mutter, die im Sitzen schläft, und ein Mädchen, das nicht aufwacht."),
			S._narr("Vor dem Fenster, im Regen auf dem Dach, steht ein zweiter Höllenhund. Er sieht genauso aus. Nur seine Augen sind leer."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 2},
			S._cam("two", 0, 1.6, 2),
			S._say("wachhund", "Du bist nur ein Wachhund. Keiner wird dich je streicheln. Bring sie zurück, und sie vergisst dich, sobald sie aufwacht."),
			S._say("wachhund", "Komm mit mir zurück ans Tor. Da gehörst du hin. Da tut Vergessen nicht weh."),
			S._say("hero", "Vielleicht vergisst sie. Hund vergisst nicht."),
			S._say("lina", "Ich vergess dich nicht! Ich schwör's! Du bist Krümel!"),
			S._say("wachhund", "Krümel. Ein Name, den ein Kind im Fieber erfunden hat. Wächter haben keine Namen."),
			S._say("hero", "Doch. Einen. GRRRR."),
			S._narr("Am Horizont wird es grau. Geht die Sonne auf, bevor Lina durch das Fenster ist, schließt es sich für immer."),
			{"t": "qte", "kind": "sequence", "keys": ["jump", "special", "block"], "time": 3.0, "text": "STELL DICH ZWISCHEN LINA UND DEN SCHATTEN!", "flag": "reaper_hound_guard",
				"success": [S._narr("Er stellt sich vor das Fenster. Wie am Tor. Nur bewacht er diesmal etwas, das lebt.")],
				"fail": [S._narr("Der Schatten ist schneller. Er steht schon halb vor dem Fenster, als der Hund ihn erreicht.")]},
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "wachhund"], "goal": "HALTE DIE SCHWELLE BIS ZUM SONNENAUFGANG!", "lives": [2, 3], "time": 90, "qte": "reaper_hound_guard", "ai": 8},
			S._music("hope"),
			{"t": "vanish", "who": 2},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 1, 1.4),
			S._narr("Die Sonne geht auf. Lina klettert durchs Fenster, zurück in ihr Bett, zurück in ihren Atem. Drinnen fängt eine Mutter an zu weinen. Vor Glück."),
			{"t": "vanish", "who": 1},
			{"t": "branch", "flag": "reaper_hound_bell", "steps": [
				S._narr("Keine Glocke ruft ihn zurück. Also bleibt er. Er schläft unter Brücken und bewacht die Kinder der Stadt, die sich nachts verlaufen."),
			], "else": [
				S._narr("Die Glocke an seinem Hals läutet leise. Nyx ruft. Er kehrt ans Tor zurück – aber jetzt sitzt er so, dass er auch hinaussehen kann."),
			]},
			S._cam("wide", 0, 1.6),
			S._narr("Zwanzig Jahre später."),
			{"t": "appear", "who": 3},
			{"t": "move", "who": 3, "x": 0.5, "time": 1.6},
			S._cam("two", 0, 1.6, 3),
			S._say("lina_alt", "Hallo, großer Hund. Ich bin Tierärztin geworden. Ich hab jeden Hund gefragt, ob er dich kennt."),
			S._say("lina_alt", "Ich hab's dir doch versprochen. Ich hab dich nicht vergessen, Krümel."),
			S._pose(0, "Crouch", 1.0),
			S._narr("Sie kniet sich hin und krault dem Höllenhund die knochigen Ohren. Er sagt nichts. Sein Schwanz klappert wie ein Windspiel."),
			S._say("hero", "… Wuff."),
			S._pose(0, "Victory", 1.4),
			S._cam("sky", 0, 3.0),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Der Höllenhund · Der Weg nach Hause"},
			S._narr("Relikt erhalten: Linas Goldmünze  ·  +400 Münzen  ·  Glückstruhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
