extends RefCounted
## Legende: DER KOMMANDANT – „Neunundneunzig“.
## Der Kommandant führte hundert Schwerter und verlor neunundneunzig in einer einzigen Nacht.
## Er kämpft, um den einen zu ehren, der überlebte – sich selbst kann er nicht verzeihen.
## Jubei war jener Nacht fern, Michael fordert seine Kapitulation vor sich selbst, und am Ende
## pflanzt der Silberwolf neunundneunzig Bäume.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Neunundneunzig",
	"summary": "Der Kommandant führte hundert Schwerter in die Schlacht am Silberpass. Neunundneunzig kamen nicht zurück. Er war der Hundertste – und hat sich das nie verziehen.",
	"relic": "Der Setzling vom Silberpass",
	"relic_text": "Ein junger Kirschbaum in einem Leinenbeutel. Einer von hundert. Auf dem Schildchen steht kein Name – nur eine Zahl: 100.",
}

const CAST := {
	"hero": {"preset": "samurai_dreyar", "name": "DER KOMMANDANT", "title": "Der Silberwolf", "color": "cbd5e1"},
	"jubei": {"preset": "jubei", "name": "JUBEI", "title": "Der Wanderer, der nicht kam", "color": "34d399"},
	"aiko": {"preset": "ren", "name": "AIKO", "title": "Schwester eines Gefallenen", "color": "f9a8d4"},
	"ronin": {"preset": "pirate_captain", "name": "RŌNIN", "title": "Ohne Herrn, ohne Ehre", "color": "78716c"},
	"ronin2": {"preset": "kettenwart", "name": "RŌNIN", "title": "Ohne Herrn, ohne Ehre", "color": "78716c"},
	"michael": {"boss": "michael", "name": "MICHAEL", "title": "Der Erzengel", "color": "fef3c7"},
	"hundert": {"preset": "samurai_dreyar", "name": "DER HUNDERTSTE", "title": "Der, der überlebte", "color": "334155"},
}

static func chapters() -> Array:
	return [
		{"id": "samurai_dreyar_1", "title": "Der Silberpass", "arena": "gladiator_fortress", "stars": 0, "steps": [
			S._stage([["hero", -1.0, 1], ["ronin", 2.8, -1], ["ronin2", 4.0, -1], ["aiko", -3.5, 1]]),
			{"t": "vanish", "who": 3},
			S._music("sad"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "DER KOMMANDANT · NEUNUNDNEUNZIG", "sub": "Kapitel I – Der Silberpass"},
			S._narr("Hundert Schwerter folgten dem Silberwolf in die Schlacht am Silberpass. Es war eine Falle. Bei Sonnenaufgang stand nur noch einer."),
			S._narr("Seitdem trägt der Kommandant neunundneunzig Namen auf einer Schriftrolle an seinem Rücken. Jeden Morgen liest er sie. Seinen eigenen hat er durchgestrichen."),
			S._cam("close", 0, 1.6),
			S._say("hero", "Haru. Kenji. Daichi. Ryo. … Neunundneunzig. Ich höre auf, wenn ich es verdient habe, aufzuhören."),
			S._cam("two", 0, 1.4, 1),
			S._say("ronin", "Der Silberwolf. Hundert Schwerter, Kommandant? Ich sehe nur eins, und das zittert."),
			S._say("ronin2", "Man sagt, er ist geflohen. Damals. Darum lebt er noch."),
			S._say("hero", "Man sagt viel. Zieht. Dann sehen wir, wer zittert."),
			{"t": "qte", "kind": "press", "keys": ["standard"], "time": 1.0, "text": "IAI!", "flag": "samurai_dreyar_iai",
				"success": [S._narr("Ein einziger Schnitt aus der Scheide. Der Wind hört ihn erst, als er vorbei ist.")],
				"fail": [S._narr("Die Hand zögert über dem Griff. Neunundneunzig Namen sind schwer.")]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "ronin", "ronin2"], "goal": "BESIEGE DIE RŌNIN!", "lives": [3, 1, 1], "teams": [0, 1, 1], "qte": "samurai_dreyar_iai", "ai": 3},
			S._music("calm"),
			{"t": "appear", "who": 3},
			S._cam("two", 0, 1.6, 3),
			S._say("aiko", "Kommandant. Ich bin Aiko. Mein Bruder Kenji war einer der Hundert. Ich will wissen, wie er gestorben ist."),
			S._say("hero", "Er starb, weil ich euch in eine Falle geführt habe. Mehr gibt es nicht zu wissen."),
			S._say("aiko", "Doch. Es gibt mehr. Er hat mir einen Brief geschrieben, in der Nacht davor. Ich habe ihn nie zu Ende gelesen. Ich lese ihn dir vor – wenn du mir zuhörst."),
			S._cam("close", 0, 1.4),
			S._narr("Der Kommandant dreht sich weg. Er ist nicht bereit. Er war seit zwölf Jahren nicht bereit."),
			S._say("aiko", "Ich gehe nicht weg. Ich folge dir, bis du zuhörst. Kenji war genauso stur. Es liegt in der Familie."),
			S._say("hero", "Dann folge mir. Aber halte Abstand. Wer mir zu nah ist, stirbt."),
			S._say("aiko", "Neunundneunzig sind gestorben. Einer hat überlebt. Vielleicht stirbt nicht, wer dir nahe ist – sondern wer dich allein lässt."),
			S._narr("Der Kommandant bleibt stehen. Er sagt nichts. Aber er streicht zum ersten Mal nicht seinen eigenen Namen durch, als er die Rolle liest."),
		]},
		{"id": "samurai_dreyar_2", "title": "Der Wanderer", "arena": "bg_dojo", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["jubei", 2.5, -1], ["aiko", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Der Wanderer"},
			S._narr("Im alten Dojo trifft der Kommandant einen Mann mit drei Klingen. Jubei. Der Schüler des alten Meisters – der in jener Nacht nicht kam."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("jubei", "Kommandant. Du hast mir einmal gesagt, ich trage Feigheit mit Scheide. Vielleicht hattest du recht. Aber du trägst Schuld mit Schriftrolle."),
			S._say("hero", "Ich habe die Namen meiner Männer bei mir. Du hast nur ein Schwert, das du nie ziehst."),
			S._say("jubei", "Inzwischen ziehe ich es. Es ist stumpf. Ich schleife es jeden Tag. Was tust du jeden Tag? Außer lesen?"),
			{"t": "choice", "text": "Wie antwortet der Kommandant?", "options": [
				{"label": "Aiko den Brief vorlesen lassen", "flag": "samurai_dreyar_letter", "steps": [
					S._say("hero", "Aiko. Lies ihn. Den Brief deines Bruders. Ich höre zu."),
					S._say("aiko", "»Wenn ich morgen falle, sag dem Kommandanten, dass ich freiwillig gegangen bin. Er soll nicht …« – der Rest ist verwischt. Ich weiß nicht, was er nicht soll."),
					S._say("jubei", "Ich kann es mir denken. Kämpfen wir. Dann denkst du auch daran.")]},
				{"label": "Schweigen und ziehen", "flag": "samurai_dreyar_silent", "steps": [
					S._narr("Der Kommandant zieht. Mehr Antwort hat er nicht."),
					S._say("jubei", "Ich kenne das. Ich habe zwölf Jahre so geantwortet.")]},
			]},
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "jubei"], "goal": "SILBERWOLF GEGEN WINDKLINGE!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			{"t": "branch", "flag": "samurai_dreyar_letter", "steps": [
				S._say("jubei", "Er soll nicht aufhören zu leben. Das wollte Kenji schreiben. Das schreibt jeder, der in die Schlacht geht."),
				S._say("hero", "… Woher willst du das wissen?"),
				S._say("jubei", "Weil mein Meister es mir geschrieben hat. Ich habe zwölf Jahre gebraucht, um den Brief zu öffnen."),
			], "else": [
				S._say("jubei", "Dein Schwert ist schärfer als meins. Dein Herz stumpfer. Pass auf, Silberwolf."),
			]},
			{"t": "fx", "kind": "flash"},
			S._narr("Ein Lichtstrahl fällt ins Dojo. Eine Stimme wie eine Posaune: Kommandant. Leg die Waffen nieder. Vor dir selbst."),
		]},
		{"id": "samurai_dreyar_3", "title": "Kapitulation", "arena": "heaven_gate", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["michael", 3.0, -1], ["jubei", -4.0, 1], ["aiko", -4.8, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2}, {"t": "vanish", "who": 3},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Kapitulation"},
			S._narr("Vor der Himmelspforte stehen neunundneunzig Schatten in Reih und Glied. Sie haben keine Gesichter. Sie warten auf einen Befehl."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("michael", "Silberwolf. Deine Männer haben die Pforte längst durchschritten. Diese Schatten hier hast du gemacht. Aus Schuld. Sie halten dich fest."),
			S._say("michael", "Kapituliere. Nicht vor mir. Vor dir selbst. Gib zu, dass du nicht alle retten konntest."),
			S._cam("close", 0, 1.4),
			S._say("hero", "Neunundneunzig starben, weil ich zu stolz war, zu fliehen. Das ist die Wahrheit."),
			S._say("michael", "Nein. Neunundneunzig starben, weil ein Feind sie verraten hat. Du warst nur der, der es überlebt hat. Das ist kein Verbrechen."),
			S._say("hero", "Dann beweise es mir. Mit dem Schwert. Anders verstehe ich nichts mehr."),
			S._music("boss"),
			{"t": "branch", "flag": "samurai_dreyar_letter", "steps": [
				{"t": "appear", "who": 3},
				{"t": "move", "who": 3, "x": -1.5, "time": 0.8},
				S._say("aiko", "Kenji ist freiwillig gegangen. Ich gehe auch freiwillig. Neben dir, Kommandant."),
				{"t": "fight", "cast": ["hero", "aiko", "michael"], "goal": "STELL DICH DEM ERZENGEL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			], "else": [
				{"t": "appear", "who": 2},
				{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
				S._say("jubei", "Ich war in jener Nacht nicht da. Heute bin ich da. Das muss reichen."),
				{"t": "fight", "cast": ["hero", "jubei", "michael"], "goal": "STELL DICH DEM ERZENGEL!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Michael senkt das Schwert. Die neunundneunzig Schatten verbeugen sich – nicht vor dem Engel, vor dem Kommandanten. Dann verblassen sie, einer nach dem anderen."),
			S._say("michael", "Sie haben dir nie etwas vorgeworfen, Silberwolf. Das hast du allein getan. Zwölf Jahre lang."),
			S._say("hero", "Was soll ich jetzt tun? Ohne die Schuld weiß ich nicht, wofür ich aufstehe."),
			S._say("michael", "Steh für das auf, wofür sie aufgestanden sind. Sie sind nicht für deine Schuld gestorben. Sie sind für das Tal gestorben. Das Tal lebt. Pflanze etwas darin."),
		]},
		{"id": "samurai_dreyar_4", "title": "Neunundneunzig Bäume", "arena": "bg_aurora_peaks", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["hundert", 2.0, -1], ["aiko", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Neunundneunzig Bäume"},
			S._narr("Der Silberpass, zwölf Jahre später. Schnee liegt auf dem Schlachtfeld. Der Kommandant trägt einen Sack auf dem Rücken. Aiko trägt einen zweiten."),
			{"t": "fx", "kind": "ink", "who": 0},
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("hundert", "Du willst hier Bäume pflanzen? Für sie? Du hast kein Recht dazu. Du bist der Hundertste. Der, der lebt. Der Feigling."),
			S._say("hero", "Ich bin der Hundertste. Der, der lebt. Und das ist meine Aufgabe. Nicht meine Strafe."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "hundert"], "goal": "VERGIB DEM HUNDERTSTEN!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("close", 0, 1.6),
			S._pose(0, "Crouch", 1.0),
			S._narr("Den ganzen Tag graben sie. Neunundneunzig Löcher im gefrorenen Boden. Neunundneunzig Kirschsetzlinge. An jedem ein Schild mit einem Namen."),
			S._cam("two", 0, 1.6, 2),
			S._say("aiko", "Du hast noch einen übrig. Der hundertste."),
			S._say("hero", "Den nehme ich mit. Er braucht keinen Namen. Nur einen Ort, an dem er wachsen darf."),
			S._say("aiko", "Kenji hätte gelacht. Er hat immer gesagt, du nimmst alles zu ernst."),
			S._say("hero", "Dann lerne ich es jetzt. Langsam. Es wird ein bisschen dauern."),
			S._narr("Im Frühling blüht der Silberpass zum ersten Mal. Neunundneunzig Bäume. Und weit weg, vor einer kleinen Hütte, ein hundertster."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Der Kommandant · Neunundneunzig"},
			S._narr("Relikt erhalten: Der Setzling vom Silberpass  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
