extends RefCounted
## Legende: DUSTY, DER RODEO-RANGER – „Der Zaun“.
## Dusty reitet seit zwanzig Jahren von Rodeo zu Rodeo durch die Prärie. Er bleibt nie länger als eine
## Nacht. Seraphine fängt ihn mit seinem eigenen Trick, Mammon bietet ihm Gold für die Freiheit, und am
## Ende baut er einen Zaun – nicht um etwas einzusperren, sondern um irgendwo anzukommen.

const S = preload("res://scripts/story_legends.gd")

const INFO := {
	"epithet": "Der Zaun",
	"summary": "Dusty reitet seit zwanzig Jahren von Rodeo zu Rodeo. Er gewinnt jeden Pokal und lässt ihn im nächsten Saloon stehen. Er bleibt nie länger als eine Nacht.",
	"relic": "Der erste Zaunpfahl",
	"relic_text": "Ein krummer Holzpfahl mit eingeritztem Stern. Der erste von hundert. Daran hängt Dustys Lasso – für immer aufgerollt.",
}

const CAST := {
	"hero": {"preset": "dusty", "name": "DUSTY", "title": "Der Rodeo-Ranger", "color": "fde68a"},
	"rose": {"preset": "thorn_witch", "name": "ROSE", "title": "Wirtin vom Saloon", "color": "4ade80"},
	"bulle": {"preset": "mossback", "name": "BIG RED", "title": "Der wildeste Bulle", "color": "b22234"},
	"seraphine": {"preset": "pirate_captain", "name": "SERAPHINE", "title": "Fängt mit dem Haken", "color": "d6d3d1"},
	"mammon": {"boss": "mammon", "name": "MAMMON", "title": "Der Gierige", "color": "facc15"},
	"schatten": {"preset": "dusty", "name": "DER REITER", "title": "Der Dusty, der immer weiterzieht", "color": "3c3b6e"},
}

static func chapters() -> Array:
	return [
		{"id": "dusty_1", "title": "Acht Sekunden", "arena": "gladiator_fortress", "stars": 0, "steps": [
			S._stage([["hero", -1.5, 1], ["bulle", 2.8, -1], ["rose", -3.5, 1]]),
			S._music("calm"),
			S._cam("sky", 0, 0.01),
			{"t": "title", "text": "DUSTY · DER ZAUN", "sub": "Kapitel I – Acht Sekunden"},
			S._narr("Eine Kleinstadt in der Prärie, ein Rodeo, eine Fahne mit Sternen und Streifen über der Tribüne. Und ein Bulle namens Big Red, den noch niemand acht Sekunden lang geritten hat."),
			S._narr("Dusty ist gestern Abend angekommen. Morgen früh wird er weg sein. Wie immer."),
			S._cam("two", 0, 1.6, 2),
			S._say("rose", "Du bist also der berühmte Dusty. Zwanzig Jahre, hundert Pokale, und keiner davon steht bei dir zu Hause."),
			S._say("hero", "Ich hab kein Zuhause, Ma'am. Nur einen Sattel. Howdy übrigens."),
			S._say("rose", "Big Red hat heute Morgen den Zaun eingerannt. Wenn du ihn reitest, gibt's Freibier für die ganze Stadt."),
			S._say("hero", "Yeehaw. Dann sattelt ihn."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "bulle"], "goal": "ACHT SEKUNDEN AUF BIG RED!", "lives": [3, 1], "ai": 3},
			S._music("calm"),
			S._cam("two", 0, 1.4, 2),
			S._say("rose", "Neun Sekunden! Die ganze Stadt jubelt! Bleib doch zum Feiern, Cowboy."),
			S._say("hero", "Ich feiere unterwegs, Ma'am. Behalten Sie den Pokal."),
			S._narr("Am nächsten Morgen ist Dusty weg. Aber zum ersten Mal dreht er sich auf dem Hügel noch einmal um."),
		]},
		{"id": "dusty_2", "title": "Gefangen", "arena": "pirate_galleon", "stars": 1, "steps": [
			S._stage([["hero", -2.0, 1], ["seraphine", 2.5, -1]]),
			{"t": "vanish", "who": 1},
			S._music("tense"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL II", "sub": "Gefangen"},
			S._narr("Am Hafen von Galveston will Dusty auf ein Schiff nach Süden. Irgendwohin, wo er noch nie war. Die Kapitänin hat einen Enterhaken – und einen Ruf."),
			{"t": "appear", "who": 1},
			S._cam("two", 0, 1.6, 1),
			S._say("seraphine", "Ein Cowboy auf meinem Schiff? Du bist der, der nie bleibt. Ich fange Leute, die weglaufen. Das ist mein Hobby."),
			S._say("hero", "Ich lauf nicht weg, Ma'am. Ich reite nur weiter."),
			S._say("seraphine", "Das sagen alle, bevor ich sie an Deck ziehe. Zeig mal, was dein Seil kann."),
			S._music("fight"),
			{"t": "fight", "cast": ["hero", "seraphine"], "goal": "LASSO GEGEN ENTERHAKEN!", "lives": [2, 2], "ai": 5},
			S._music("calm"),
			S._cam("two", 0, 1.4, 1),
			S._say("seraphine", "Du hast mich erwischt. Respekt. Und jetzt? Segelst du mit nach Süden?"),
			S._say("hero", "… Eigentlich hab ich an die Kleinstadt gedacht. An Big Red. Und an die Wirtin."),
			S._say("seraphine", "Ha! Der Cowboy, der nie bleibt, hat Heimweh nach einem Ort, an dem er nur eine Nacht war."),
			{"t": "fx", "kind": "ink", "who": 0},
			S._narr("Auf dem Rückweg wird der Himmel golden. Zu golden. Auf dem Weg liegt ein Nugget, dann noch eins. Eine Spur aus Gold, die von der Stadt weg führt."),
		]},
		{"id": "dusty_3", "title": "Goldrausch", "arena": "hell_city", "stars": 2, "steps": [
			S._stage([["hero", -2.5, 1], ["mammon", 3.0, -1], ["rose", -4.0, 1]]),
			{"t": "vanish", "who": 1}, {"t": "vanish", "who": 2},
			S._music("tense"),
			S._cam("low", 0, 0.01),
			{"t": "title", "text": "KAPITEL III", "sub": "Goldrausch"},
			S._narr("Die Spur endet in einer Stadt aus Gold. Die Straßen glänzen, die Fenster glänzen, und niemand wohnt dort. Auf einem Berg aus Münzen sitzt der Gierige."),
			{"t": "appear", "who": 1},
			S._cam("sky", 1, 2.4),
			S._say("mammon", "Cowboy. Du brauchst kein Zuhause. Du brauchst Gold. Damit kannst du überall hin. Für immer. Nie wieder anhalten."),
			S._say("hero", "Nie wieder anhalten … So hab ich zwanzig Jahre gelebt."),
			S._say("mammon", "Und es war die beste Zeit deines Lebens. Nimm. Alles. Dann musst du nie an einem Ort bleiben."),
			S._cam("close", 0, 1.4),
			S._pose(0, "Dazed", 1.0),
			{"t": "appear", "who": 2},
			{"t": "move", "who": 2, "x": -1.5, "time": 0.8},
			S._say("rose", "Dusty! Big Red ist dir hinterhergerannt, und ich ihm hinterher! Die ganze Stadt sucht dich! Wir wollen dir was zeigen!"),
			S._say("hero", "Ihr habt mich gesucht? Mich hat noch nie jemand gesucht."),
			S._say("hero", "Hey, Goldjunge. Du hast eine ganze Stadt und keinen einzigen Nachbarn. Ich hatte zwanzig Jahre die ganze Prärie und keinen Freund. Das hört heute auf."),
			S._music("boss"),
			{"t": "fight", "cast": ["hero", "rose", "mammon"], "goal": "LASSO GEGEN GIER!", "lives": [3, 2, 1], "teams": [0, 0, 1]},
			S._music("hope"),
			{"t": "fx", "kind": "burst", "who": 0},
			S._narr("Das Lasso zischt, der Münzberg rutscht, und Mammon versinkt in seinem eigenen Gold. Die Stadt zerfällt zu Sand. Übrig bleibt die Prärie – und ein Weg zurück."),
		]},
		{"id": "dusty_4", "title": "Der Zaun", "arena": "gladiator_fortress", "stars": 3, "steps": [
			S._stage([["hero", -1.5, 1], ["schatten", 2.0, -1], ["rose", -3.5, 1]]),
			{"t": "vanish", "who": 1},
			S._music("sad"),
			S._cam("wide", 0, 0.01),
			{"t": "title", "text": "KAPITEL IV", "sub": "Der Zaun"},
			S._narr("Zurück in der Kleinstadt. Die Leute haben ein Stück Land am Fluss abgesteckt, mit einem Schild: »Dustys Ranch«. Doch am Tor wartet ein Reiter mit Dustys Hut und gesatteltem Pferd."),
			{"t": "appear", "who": 1},
			S._cam("close", 1, 1.4),
			S._say("schatten", "Steig auf, Partner. Hinter dem Hügel ist die nächste Stadt. Das nächste Rodeo. Wer bleibt, wird alt und langsam."),
			S._say("hero", "Wer nie bleibt, wird auch alt. Nur allein. Hold your horses, Partner – diesmal reitest du ohne mich."),
			S._music("boss_final"),
			{"t": "fight", "cast": ["hero", "schatten"], "goal": "BLEIB!", "lives": [2, 2], "damage": {"0": 30}, "ai": 7},
			S._music("hope"),
			{"t": "vanish", "who": 1},
			{"t": "fx", "kind": "flash"},
			S._cam("two", 0, 1.6, 2),
			S._say("rose", "Und? Was machst du als Erstes auf deiner Ranch, Cowboy?"),
			S._say("hero", "Einen Zaun, Ma'am. Keinen, um was einzusperren. Einen, an den man sich lehnen kann, wenn man den Sonnenuntergang anschaut. Mit Freunden."),
			S._narr("Der erste Pfahl ist krumm. Dusty ritzt einen Stern hinein und hängt sein Lasso daran. Big Red grast auf der Weide und hat keine Lust mehr, Zäune einzurennen."),
			S._cam("sky", 0, 3.0),
			S._pose(0, "Victory", 1.4),
			{"t": "title", "text": "LEGENDE VOLLENDET", "sub": "Dusty · Der Zaun"},
			S._narr("Relikt erhalten: Der erste Zaunpfahl  ·  +400 Münzen  ·  Legenden-Truhe  ·  Goldrahmen  ·  +15 % Heilung im Abenteuer"),
		]},
	]
